### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [eclipse/mosquitto#1]
Would you like to add more error handling for return values from functions like the following?
- [fwrite](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fwrite.html "Binary output") ⇒ [my_message_callback](https://github.com/eclipse/mosquitto/blob/bf959ef9b0ae0e4d74bf80158ffb0b7c69da533d/client/sub_client.c#L36)
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [client_config_load](https://github.com/eclipse/mosquitto/blob/bf959ef9b0ae0e4d74bf80158ffb0b7c69da533d/client/client_shared.c#L93)

**Comment by ralight** [comment]
The malloc calls - yes definitely.

The call to fwrite - there's not a lot that can be done if it fails so there isn't much point checking it.

**Comment by ralight** [comment]
Closed in https://github.com/eclipse/mosquitto/commit/35c4d3d59a34c0dfebe1b447a352be1e1d9a6e1c

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Would you like to detect every error situation as early as possible?

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for this software?

**Comment by ralight** [comment]
In this case ignoring the return value of fwrite is only as "bad" as ignoring the return value from printf.

The project is run through Coverity Scan on a fairly regular basis.

**Comment by elfring** [comment]
I wonder still how many return values are ignored (or "overlooked") at the moment.
Would you like to care also for return codes from functions of the POSIX thread programming interface (for example)?

**Comment by ralight** [comment]
Thanks for your input, but it is not helpful to just make speculative comments like this. If you have specific bug reports to make, please do open more reports.

**Comment by elfring** [comment]
>…, but it is not helpful to just make speculative comments like this.

Does [your use of the tool "Coverity"](https://scan.coverity.com/projects/mosquitto "Coverity Scan") point open issues out [around Pthread functions](https://github.com/eclipse/mosquitto/blob/26b015908e5c4ff8a2a365eba176f0c27779d1a7/lib/mosquitto.c#L204 "Checking pthread_mutex_init() calls?")?

**Comment by ralight** [comment]
Yes, coverity points out issues with the use of pthreads.

I'm sure you are well intentioned, but the manner in which you approach issues here on github in lots of projects is not very ameanable. I would suggest that you do not reply to every comment with a vague question, instead if you can offer specific help I would be happy to receive it.

Please do not comment on this issue again, the specific issues you highlighted have been fixed. If you believe there are other issues, please open a new report.

**Comment by elfring** [comment]
>Yes, coverity points out issues with the use of pthreads.

I find it unclear for me which implementation details are in the waiting queue for further considerations already because of source code analysis reports by this tool.


> If you believe there are other issues, please open a new report.

Do you really want a separate bug report for almost every return value that is ignored so far?

**Comment by kartben** [comment]
I think what would be really helpful would be pull requests, that the
community would be able to review depending on the tradeoff between
improving actually robustness, or just changing the code just in order to
make some code analysis tool happy.
If you can demonstrate the value of the changes via actual code changes, I
think it'll be much more productive and valuable than endlessly commenting
on bugs. It would also help to indicate what actual problem you are trying
to solve for each specific pull request.

Le lun. 14 mars 2016 21:05, Markus Elfring <notifications@github.com> a
écrit :

**Comment by ralight** [comment]
There are two outstanding issues found by coverity scan. They are viewable by anyone.

What I would like is specific bug requests, not vague questions. I do not want a bug report for each return value that is ignored, I would like considered bug reports that include an analysis of why that particular situation is a problem.

You seem to assume that there hasn't been any consideration of return values, this isn't the case. In a very few cases there may be a bug, but just questioning all possible return codes is not constructive.

**Comment by elfring** [comment]
Some update candidates were pointed out by a script in [the semantic patch language (Coccinelle)](http://coccinelle.lip6.fr/ "Program analysis with Coccinelle").
Do you find the attached excerpt from an analysis result interesting?
[unstored_return_values-POSIX-example-20160318.zip](https://github.com/eclipse/mosquitto/files/179783/unstored_return_values-POSIX-example-20160318.zip)
