### ISSUE TITLE
Why does SSL work without cafile/capath?

### ISSUE THREAD

**Issue by chessweb01** [eclipse/mosquitto#1000]
The documentation for mosquitto.conf states "_At least one of cafile or capath must be provided to allow SSL support._"

I noticed, that this is not the case. In the mosquitto.conf file I am using, I have specified certfile and keyfile but neither cafile nor capath. Nevertheless SSL seems to be working just fine with certfile and keyfile alone.  

Am I missing something here?

**Comment by dirkfeytons** [comment]
Have you checked (e.g. with Wireshark) that it actually uses TLS?

Based on my knowledge of the code and some quick testing it seems that if no `cafile` nor `capath` is configured the broker will simply open a regular unsecured socket. If the client doesn't attempt to use TLS (e.g. you don't pass a `--cafile` or `--capath` option to `mosquitto_sub`) then the connection will succeed but it's actually unsecured.

**Comment by Assar63** [comment]
This may depend on how openSSL behaves. It has a default path chain which often is where the default certs are. If you instead use another ssl library, they do not always refer to a default directory.
If you use "strace" to trace application behaviour you can see the different attempts.

**Comment by ralight** [comment]
@Assar63 That's a good thought, but Mosquitto doesn't load the default certificates. I suspect that @dirkfeytons is correct.

**Comment by ralight** [comment]
There hasn't been an update on this for a while, and I don't believe it is a bug in mosquitto, but a mistake in testing, so I'm going to close this for now. If you think it is still a problem, please reopen this and provide some more details.
