### ISSUE TITLE
SSL using  Websocket Protocol

### ISSUE THREAD

**Issue by satsdeva** [eclipse/mosquitto#1002]
i used the following configuration for SSL web socket connection.

port 8883
protocol mqtt
cafile C:\mos\certs\ca.crt
keyfile C:\mos\certs\ia.key
certfile C:\mos\certs\ia.crt
require_certificate false
tls_version tlsv1.2

listener 9883
protocol websockets
cafile C:\mos\certs\ca.crt
keyfile C:\mos\certs\ia.key
certfile C:\mos\certs\ia.crt
require_certificate false
tls_version tlsv1.2

i tried to connect  web client, i'm getting  "failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR"..

i'm not able to trace the error.Please suggest me , to resolve the error.
OS:Windows 2012 R2,
OpenSSL 1.0.2 ,
Mosquitto 1.4.9

**Comment by ralight** [comment]
Did you compile the broker yourself? If not, websocket support isn't included in the provided 1.4.9 version. I'd suggest trying 1.5.3.

**Comment by satsdeva** [comment]
@ralight : Without SSL,through web socket protocol method working.But,it is not working with SSL method.I will try with  mosquitto1.5.3  & let you know.

**Comment by satsdeva** [comment]
@ralight : i tried with 1.5.3 and  open ssl 1.1.0i. and 
i used the mqtt spy for the client connection.
i'm getting "SSLException: Unrecognized SSL message, plaintext connection?"

Created another  java script web page for client connection.
Error: "ERR_SSL_PROTOCOL_ERROR Connection Failure -AMQJS0007E  socket error.undefined."

Please suggest me how to debug the error.

**Comment by stoinov** [comment]
there might be a WS issue with 1.5.3 as per #1004

**Comment by ralight** [comment]
Yes, I'm pretty certain now this is the same as #1005, so I'm closing this as a duplicate. I realise your report was first, but #1005 better describes the issue.
