### ISSUE TITLE
Is the test server down again?

### ISSUE THREAD

**Issue by projectb-temp** [eclipse/mosquitto#1006]
Hi there.
Since several days it seems test.mosquitto.org is down or at least not fully working (several disconnects/reconnects per day).

Starting from 2018.10.07 things became more or less  unusable for me (using MQTTfx, Node-RED or a FHEM instance). I couldn't connect any more using port 1883 or 8080.

My local mosquitto installation works fine, so I assume the server being buggy, down or not accepting unencrypted connections any more. Sadly there is no information about this on the mosquitto test server website.

Are there any news when the test server will be usable for us again?

Thank you for your assistance and keep up your good work!
Best regards

**Comment by ralight** [comment]
Sorry to hear you're having problems, but you definitely should note the caveats section on https://test.mosquitto.org/

This situation definitely applies at the moment. I am running unreleased server code in a variety of debug environments and that can lead to problems. It's also worth noting that the hosting provider has an automatic DOS protection service, and I normally get a dozen or two emails about it being activated every day, so it could be that you have been affected by somebody else connecting a few thousand clients at once.

**Comment by projectb-temp** [comment]
Thank you for your fast reply!
I know about the caveats section and the fact that it's a system that is heavily tested. And I really appreciate it that you use this system for testing your software.

Up to now it was rock stable for my testing purposes,l with only very few connection issues within the last several months. Only starting at October it started to fail more of less completely for a couple of days in a row - at least for me.

Thank you for informing me regarding the DOS protection service! Usually only 1 or 2 clients from me connect to the server in parallel. But yes, it's very likely that your DOS prevention system kicks in when several thousand clients connect at once.

Best regards

**Comment by ralight** [comment]
One difference is that prior to October it was running mostly undisturbed by me! I've been making more tests recently.
