### ISSUE TITLE
Publish with Wrong Password/

### ISSUE THREAD

**Issue by namjitharavind** [eclipse/mosquitto#1008]
When i try to publish with wrong password. Its allowing.

**Comment by ralight** [comment]
Could you please share your configuration (not the password file) and what version of mosquitto you are using?

**Comment by namjitharavind** [comment]
since i am using vernemq ,following is the config file.

allow_anonymous = off
allow_multiple_sessions = off
allow_publish_during_netsplit = off
allow_register_during_netsplit = off
allow_subscribe_during_netsplit = off
allow_unsubscribe_during_netsplit = off
crl_refresh_interval = 60000
default_reg_view = vmq_reg_trie
default_schema_dir = off
distributed_cookie = vmq
erlang.K = on
erlang.W = w
erlang.async_threads = 64
erlang.crash_dump = /var/log/vernemq/erl_crash.dump
erlang.fullsweep_after = 0
erlang.max_ets_tables = 256000
erlang.max_ports = 262144
erlang.process_limit = 256000
erlang.smp = enable
graphite_api_key = 
graphite_connect_timeout = 5000
graphite_enabled = off
graphite_host = localhost
graphite_interval = 20000
graphite_port = 2003
graphite_prefix = 
graphite_reconnect_timeout = 15000
http_modules = [vmq_metrics_http,vmq_http_mgmt_api, vmq_status_http]
leveldb.block.restart_interval = 16
leveldb.block.size = 4KB
leveldb.block.size_steps = 16
leveldb.block_cache_threshold = 32MB
leveldb.bloomfilter = on
leveldb.compaction.trigger.tombstone_count = 1000
leveldb.compression = on
leveldb.data_root = $(platform_data_dir)/leveldb
leveldb.fadvise_willneed = false
leveldb.limited_developer_mem = off
leveldb.maximum_memory.percent = 70
leveldb.sync_on_write = off
leveldb.threads = 71
leveldb.tiered = off
leveldb.verify_checksums = on
leveldb.verify_compaction = on
leveldb.write_buffer_size_max = 60MB
leveldb.write_buffer_size_min = 30MB
leveldb_message_store.directory = /var/lib/vernemq/msgstore
listener.http.default = 0.0.0.0:8888
listener.http.default.config_fun = config
listener.http.default.config_mod = vmq_http_config
listener.http.default.max_connections = -1
listener.http.default.nr_of_acceptors = 10
listener.http.max_connections = -1
listener.http.nr_of_acceptors = 10
listener.http.proxy_protocol = off
listener.http.proxy_protocol_use_cn_as_username = on
listener.https.cafile = 
listener.https.certfile = 
listener.https.ciphers = 
listener.https.crlfile = 
listener.https.depth = 1
listener.https.keyfile = 
listener.https.max_connections = -1
listener.https.nr_of_acceptors = 10
listener.https.require_certificate = off
listener.https.tls_version = tlsv1.2
listener.max_connections = 10000
listener.mountpoint = off
listener.nr_of_acceptors = 10
listener.ssl.allowed_protocol_versions = [3,4]
listener.ssl.cafile = 
listener.ssl.certfile = 
listener.ssl.ciphers = 
listener.ssl.crlfile = 
listener.ssl.depth = 1
listener.ssl.keyfile = 
listener.ssl.max_connections = -1
listener.ssl.mountpoint = 
listener.ssl.nr_of_acceptors = -1
listener.ssl.require_certificate = off
listener.ssl.tls_version = tlsv1.2
listener.ssl.use_identity_as_username = off
listener.tcp.allowed_protocol_versions = [3,4]
listener.tcp.default = 127.0.0.1:1883
listener.tcp.default.max_connections = -1
listener.tcp.default.mountpoint = 
listener.tcp.default.nr_of_acceptors = -1
listener.tcp.max_connections = -1
listener.tcp.mountpoint = 
listener.tcp.nr_of_acceptors = -1
listener.tcp.proxy_protocol = off
listener.tcp.proxy_protocol_use_cn_as_username = on
listener.vmq.clustering = 0.0.0.0:44053
listener.vmq.clustering.max_connections = -1
listener.vmq.clustering.mountpoint = 
listener.vmq.clustering.nr_of_acceptors = 10
listener.vmq.max_connections = -1
listener.vmq.mountpoint = 
listener.vmq.nr_of_acceptors = 10
listener.vmqs.cafile = 
listener.vmqs.certfile = 
listener.vmqs.ciphers = 
listener.vmqs.crlfile = 
listener.vmqs.depth = 1
listener.vmqs.keyfile = 
listener.vmqs.max_connections = -1
listener.vmqs.mountpoint = 
listener.vmqs.nr_of_acceptors = 10
listener.vmqs.require_certificate = off
listener.vmqs.tls_version = tlsv1.2
listener.ws.allowed_protocol_versions = [3,4]
listener.ws.max_connections = -1
listener.ws.mountpoint = 
listener.ws.nr_of_acceptors = -1
listener.ws.proxy_protocol = off
listener.ws.proxy_protocol_use_cn_as_username = on
listener.wss.allowed_protocol_versions = [3,4]
listener.wss.cafile = 
listener.wss.certfile = 
listener.wss.ciphers = 
listener.wss.crlfile = 
listener.wss.depth = 1
listener.wss.keyfile = 
listener.wss.max_connections = -1
listener.wss.mountpoint = 
listener.wss.nr_of_acceptors = -1
listener.wss.require_certificate = off
listener.wss.tls_version = tlsv1.2
listener.wss.use_identity_as_username = off
log.console = file
log.console.file = /var/log/vernemq/console.log
log.console.level = info
log.crash = on
log.crash.file = /var/log/vernemq/crash.log
log.crash.maximum_message_size = 64KB
log.crash.rotation = $D0
log.crash.rotation.keep = 5
log.crash.size = 10MB
log.error.file = /var/log/vernemq/error.log
log.error.messages_per_second = 100
log.error.redirect = on
log.syslog = off
max_client_id_size = 100
max_drain_time = 500
max_inflight_messages = 20
max_message_rate = 0
max_message_size = 0
max_msgs_per_drain_step = 100
max_offline_messages = 1000
max_online_messages = 1000
message_size_limit = 0
nodename = VerneMQ@127.0.0.1
outgoing_clustering_buffer_size = 10000
persistent_client_expiration = never
platform_data_dir = /var/lib/vernemq
plugins.vmq_acl = off
plugins.vmq_bridge = off
plugins.vmq_diversity = on
plugins.vmq_passwd = off
plugins.vmq_webhooks = off
plumtree.directory = /var/lib/vernemq/meta
plumtree.outstanding_limit = 250000
queue_deliver_mode = fanout
queue_sup_sup_children = 50
queue_type = fifo
reg_views = [vmq_reg_trie]
remote_enqueue_timeout = 5000
retry_interval = 20
runtime_health.thresholds.busy_ports = 2
runtime_health.thresholds.busy_processes = 30
runtime_health.triggers.distribution_port = on
runtime_health.triggers.port = on
runtime_health.triggers.process.garbage_collection = off
runtime_health.triggers.process.heap_size = 160444000
runtime_health.triggers.process.long_schedule = off
sasl = off
setup.data_dir = /var/lib/vernemq/
setup.log_dir = /var/log/vernemq/
shared_subscription_policy = prefer_local
shared_subscription_timeout_action = ignore
systree_enabled = on
systree_interval = 20000
systree_mountpoint = 
systree_qos = 0
systree_reg_view = vmq_reg_trie
systree_retain = off
tcp_listen_options = [{nodelay, true}, {linger, {true, 0}}, {send_timeout, 30000}, {send_timeout_close, true}]
upgrade_outgoing_qos = off
vmq_acl.acl_file = /etc/vernemq/vmq.acl
vmq_acl.acl_reload_interval = 10
vmq_bridge.registry_mfa = {vmq_reg,direct_plugin_exports,[vmq_bridge]}
vmq_diversity.auth_mongodb.enabled = off
vmq_diversity.auth_mongodb.script = /usr/share/vernemq/lua/auth/mongodb.lua
vmq_diversity.auth_mysql.enabled = on
vmq_diversity.auth_mysql.script = /usr/share/vernemq/lua/auth/mysql.lua
vmq_diversity.auth_postgres.enabled = off
vmq_diversity.auth_postgres.script = /usr/share/vernemq/lua/auth/postgres.lua
vmq_diversity.auth_redis.enabled = off
vmq_diversity.auth_redis.script = /usr/share/vernemq/lua/auth/redis.lua
vmq_diversity.clique_lead_line =     script      Manage lua scripts

vmq_diversity.keep_state = off
vmq_diversity.memcache.host = localhost
vmq_diversity.memcache.port = 11211
vmq_diversity.mongodb.host = localhost
vmq_diversity.mongodb.pool_size = 5
vmq_diversity.mongodb.port = 27017
vmq_diversity.mongodb.r_mode = master
vmq_diversity.mongodb.w_mode = safe
vmq_diversity.mysql.database = streaming
vmq_diversity.mysql.host = 127.0.0.1
vmq_diversity.mysql.password = *******
vmq_diversity.mysql.pool_size = 5
vmq_diversity.mysql.port = 3306
vmq_diversity.mysql.user = root
vmq_diversity.nr_lua_states = 1
vmq_diversity.postgres.database = vernemq_db
vmq_diversity.postgres.host = localhost
vmq_diversity.postgres.password = password
vmq_diversity.postgres.pool_size = 5
vmq_diversity.postgres.port = 5432
vmq_diversity.postgres.user = root
vmq_diversity.redis.database = 0
vmq_diversity.redis.host = localhost
vmq_diversity.redis.password = 
vmq_diversity.redis.pool_size = 5
vmq_diversity.redis.port = 6379
vmq_diversity.script_dir = /usr/share/vernemq/lua
vmq_passwd.password_file = /etc/vernemq/vmq.passwd
vmq_passwd.password_reload_interval = 10
vmq_webhooks.clique_lead_line =     webhooks    Manage webhooks

vmq_webhooks.pool_max_connections = 100
vmq_webhooks.pool_timeout = 60000
wait_for_proc = vmq_server_sup

**Comment by Assar63** [comment]
@namjitharavind 
Please use mosquitto broker and try to reproduce.
Vernemq is a different bird.

**Comment by namjitharavind** [comment]
Thanks a lot for your help. I had two brokers vernemq and mosquitto on same port. I have removed and working.

**Comment by ralight** [comment]
Ok, good to hear you've got it working.
