### ISSUE TITLE
Cannot install additional software after upgrade to 1.5 (docker)

### ISSUE THREAD

**Issue by agross** [eclipse/mosquitto#1011]
```sh
$ docker run eclipse-mosquitto:latest apk update
ERROR: Unable to lock database: No such file or directory
ERROR: Failed to open apk database: No such file or directory

$ docker run eclipse-mosquitto:1.5 apk update
ERROR: Unable to lock database: No such file or directory
ERROR: Failed to open apk database: No such file or directory

$ docker run eclipse-mosquitto:1.5.3 apk update
ERROR: Unable to lock database: No such file or directory
ERROR: Failed to open apk database: No such file or directory
```

This has been working before:
```sh
$ docker run eclipse-mosquitto:1.4.12 apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
...
```

**Comment by ralight** [comment]
Ok, I guess I've taken reducing the image size down a bit too far. It's a shame, that optimisation saves ~6GB bandwidth per day. I'll sort it out.

**Comment by agross** [comment]
I have no idea how apk works but I guess it's OK to wipe the cache (and save bandwidth), but keep the data that is required to run an update (package sources?).

**Comment by ruimarinho** [comment]
Just remove `rm -rf /build /etc/apk /lib/apk` and use `--no-cache` in front of all apk commands so that it doesn't store state.

Another option would be to use multi-stage builds so that only compiled artifacts go into the final image. Much better for code maintainability.

**Comment by ralight** [comment]
https://github.com/docker-library/official-images/pull/5031

**Comment by ralight** [comment]
Multi-stage builds are ok for normal docker images, but not for official images: https://github.com/docker-library/official-images/issues/3383
