### ISSUE TITLE
A TLS Error Occurred

### ISSUE THREAD

**Issue by kaysond** [eclipse/mosquitto#1012]
I'm having trouble getting `mosquitto_sub` to work.

I have the following in `conf.d/ssl.conf`

```
listener 8883
certfile /etc/ssl/certs/domain.com.crt
keyfile /etc/ssl/private/domain.com.key
cafile /etc/ssl/certs/domain.com.pem
```
Where all of the above are generated by letsencrypt. If I run `mosquitto_sub -h localhost -p 8883 -v -t 'owntracks/#' --cafile /etc/ssl/certs/domain.com.pem`, I get `Error: A TLS error occurred.`

`mosquitto.log` has:

```
1541280248: New connection from ::1 on port 8883.
1541280248: OpenSSL Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
1541280248: Socket error on client <unknown>, disconnecting.
```

`openssl s_client -connect localhost:8883`:

```
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = domain.com
verify return:1
---
Certificate chain
 0 s:/CN=domain.com
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
XXX
-----END CERTIFICATE-----
subject=/CN=domain.com
issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3881 bytes and written 269 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 40E721166788C4C80BBAADA79B56D9873F1049DEB4DA10A28D1F3F8E81BE2E52
    Session-ID-ctx:
    Master-Key: B6D5297B4DDDBAF351B992C9ED24218A378291EC3B6A95987B0A30D78884F118B33E7AA91FD4EB2A78108E24C99AC8FD
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 8a 4b 14 75 9f 1a 8e dc-f9 4c ef 69 2d 73 d6 cf   .K.u.....L.i-s..
    0010 - a3 cc c3 9a b1 82 17 51-72 9e 72 84 c4 4d 91 98   .......Qr.r..M..
    0020 - 6a d5 de f3 bd 2d 38 e6-b7 c9 0b 0b b7 c8 53 89   j....-8.......S.
    0030 - 50 0e 82 8f 92 ce 98 b8-7b 70 e4 d1 89 51 99 a4   P.......{p...Q..
    0040 - ea 60 f0 82 1c d8 4b e9-4a 32 fd 39 4b d8 ec c4   .`....K.J2.9K...
    0050 - 8c f1 8d 53 b0 8a 44 53-27 32 6b 98 16 aa 2e 99   ...S..DS'2k.....
    0060 - 71 1d 0b e3 49 2f 2a 9c-3a e8 4a e2 3f dc 4b f1   q...I/*.:.J.?.K.
    0070 - 04 46 8d c9 bd 09 af 34-6e f6 ca a3 bc fc c9 e1   .F.....4n.......
    0080 - 67 66 50 9e 9e 08 2c d4-b0 a9 51 9d f6 af d2 a0   gfP...,...Q.....
    0090 - c1 1b ea 95 40 74 62 21-43 5d 16 4c f0 57 0c a1   ....@tb!C].L.W..
    00a0 - 83 d3 ab 2a a5 d0 8a 4a-e0 91 f6 56 74 68 8d ae   ...*...J...Vth..

    Start Time: 1541280986
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---
```
But! [owntracks](https://owntracks.org/) can connect and publish just fine. What am I doing wrong?

**Comment by ralight** [comment]
If you use a more recent version of mosquitto (1.5.x) you should get more informative TLS error messages on the client side, which might help.

Note that you must connect using the correct hostname, as is in the certificate. You are connecting to localhost, this will not match the certificate name from letsencrypt and so it will fail there.

What certificates does `domain.com.pem` contain? If it doesn't contain the root CA certificate, then that is probably the cause of the "unknown" error.

**Comment by kaysond** [comment]
> What certificates does domain.com.pem contain? If it doesn't contain the root CA certificate, then that is probably the cause of the "unknown" error.

Ah that's the problem. My chain includes the intermediate but not the root CA. Using the root cert fixed the problem. Is there any way to make `--capath` read a different file extension? The default ubuntu certs all end in `.pem`, so I had to use `--cafile`

**Comment by ralight** [comment]
I don't believe there is anything you can do in mosquitto itself, capath loading is something openssl deals with internally.

You could try using a symbolic link to the cert though, that is the route that ubuntu takes in /etc/ssl/certs.

**Comment by kaysond** [comment]
Thanks.
