### ISSUE TITLE
mosquitto_passwd

### ISSUE THREAD

**Issue by thl-mot** [eclipse/mosquitto#1014]
I am running mosquito inside a docker container as followig:
`docker run -it -p 1883:1883 -p 9001:9001 -v $PWD/mosquitto-default.conf:/mosquitto/config/mosquitto.conf -v $PWD/mosquitto-passwd:/etc/mosquitto/passwd eclipse-mosquitto`

How can I add users to the passwd file without installing mosquitto on my local system. 
Inside the container I couldn't finde the mosquitto_passwd script.

**Comment by karlp** [comment]
Duplicate of #1009

**Comment by ralight** [comment]
I'm closing this as a duplicate, it should be fixed soon anyhow.
