### ISSUE TITLE
misleading error message when connecting with password flag but no user flag

### ISSUE THREAD

**Issue by tabascoeye** [eclipse/mosquitto#1015]
Due to an error in my client, I connected to mosquitto 1.4.12 with connect flags:

    Connect Flags: 0x6e, Password Flag, Will Retain, QoS Level: At least once delivery (Acknowledged deliver), Will Flag, Clean Session Flag
        0... .... = User Name Flag: Not set
        .1.. .... = Password Flag: Set

and the payload also only containing a password, no username.

Mosquitto yields some unspecific "socket error on client" and instantly closes the connection with FIN,ACK.
This could at least yield some better error message like "password set but no username" or something.

**Comment by tabascoeye** [comment]
error message is:

    New connection from 192.168.0.16 on port 1883.
    Socket error on client (unknown), disconnecting.

**Comment by ralight** [comment]
Thanks for the report, an error message is given now. This will be in 1.5.4 shortly.

**Comment by karlp** [comment]
if we're going to break out explicit cases like this, there's lots more that could be covered too....
