### ISSUE TITLE
snap install mosquitto issue

### ISSUE THREAD

**Issue by sideralis** [eclipse/mosquitto#1017]
Not sure this is the right place to post this bug, but here is my problem.
If I install mosquitto with snap on my ubuntu 18.04 I have problem when using the --cafile option with mosquitto_pub command. I always get: "Error: Problem setting TLS options"

After a snap remove and an apt install mosquitto_clients, the exactly same command is working fine.

I think there is something wrong with the snap install.

1- For info:
version of mosquitto_pub installed with snap:
mosquitto_pub version 1.5.3 running on libmosquitto 1.5.3.

version of mosquitto_pub installed with apt
mosquitto_pub version 1.4.15 running on libmosquitto 1.4.15

2- For info too:
I compiled from source mosquitto (from this tar file: mosquitto-1.5.3.tar.gz) and install it, and my command was working fine, not TLS error.

**Comment by ralight** [comment]
My bet here would be that you're running into problems accessing files where the snap isn't permitted. It can only access files in `/var/snap/mosquitto/common/` when running as the system service, or `~/snap/mosquitto/common` if being run by a user. If your certificates aren't in this path, you'll not be able to access them. Copy them in and update your configuration and you should be good to go.

If that's not your problem, could you please provide a few more details on what you're actually running?

**Comment by sideralis** [comment]
Good bet :+1: . I moved my cafile to `~/snap/mosquitto/common/` and it works fine now.
I will remember this next time I use snap to install a package.

Thanks.
