### ISSUE TITLE
Mosquitto bridge doesn't honor restart_timeout setting

### ISSUE THREAD

**Issue by abiliojr** [eclipse/mosquitto#1019]
The restart_timeout value is only effective right after a bridged connection failure. Once the period elapses, the reconnection attempts will happen as quick as possible (in the order of dozens per second) until one succeed.

This only happens if ADNS is disabled.

**Comment by abiliojr** [comment]
Fix in pull request https://github.com/eclipse/mosquitto/pull/1020

**Comment by ralight** [comment]
This is fixed as per your pull request, thanks very much.
