### ISSUE TITLE
Mosquitto does not see the user

### ISSUE THREAD

**Issue by EmilTK** [eclipse/mosquitto#1025]
I want to raise the MQTT mosquito broker on the zyxel keneetic. Installed mosquitto-nossl, libmosquitto-nossl, mosquitto-client-nossl I want to make access only for users who are in password_file In the configuration file /opt/etc/mosquito/mosquitto.conf everything is used by default, except for:

I'm running mosquitto -c /opt/etc/mosquitto/mosquitto.conf
Please tell me where the config file is located by default, if I just run mosquitto, it does not launch /opt/etc/mosquitto/mosquitto.conf

```
per_listener_settings true
log_dest syslog
log_facility 5
log_type error
log_type warning
log_type information
allow_anonymous false
password_file /opt/etc/mosquitto/users.list
acl_file /opt/etc/mosquitto/mosquitto.acl
```
File 'users.list' contains login: test, password:test to check the mosquito, access the file 777

`test:$6$5Prq6fKi/BKhXVd+$SK2AYMVcMUKP94nzkZF3YIy6SXQhA5HBjDM/5n0X07YbIVPJP8Mnl4YGlRDkyWxSWs1mnxhP+CEzw9xvtV6F/Q==`

File mosquitto.acl
```
user test
topic #
```
When I try to connect under the account "test" in the logs I get the error 
`"Socket error on client <unknown> , disconnecting."` 
Please tell me why he does not see the account "test"?

**Comment by ralight** [comment]
I'm unfamiliar with the packages you are using, so it's difficult to say much. There is no default config file for mosquitto as such, for these packages I don't know what might have been set.

I notice you're using a "nossl" package, presumably that means compiled without SSL/TLS support. The routines Mosquitto uses for hashing passwords relies on openssl, so if it is not available has to use unencrypted passwords. Could you try with `test:password` as password file? This might seem a bit insecure, but remember that if you're not using encrypted connections then the password will be sent in the clear anyway.

**Comment by ralight** [comment]
Great, glad you got it working.

**Comment by karlp** [comment]
fyi, openwrt uses the /etc/config/mosquitto files by default.  There's an (obvious) option there to turn off if you want to use your own file, and then, it will use the default /etc/mosquitto/mosquitto.conf.  If you want to use files in /opt, you need to make your own changes to the init scripts.

the mosquitto_passwd tool is available out of the box when you install the -ssl versions.
