### ISSUE TITLE
windows service stuck on starting

### ISSUE THREAD

**Issue by bayuTam** [eclipse/mosquitto#1026]
I used version 1.5.3, but there was a problem when I started servicing, the service stuck at starting. I have restarted The PC still at starting

**Comment by ruant** [comment]
Same here, Not sure what's going on. Running with `-v` works fine, and I see clients connecting and sending messages as well.

**Comment by ralight** [comment]
There have been substantial changes to Windows support since 1.5.3, so I'm going to close this issue. If it's still a problem, please feel free to open a new issue.
