### ISSUE TITLE
bridge connection failure delayed by keepalive_interval

### ISSUE THREAD

**Issue by abiliojr** [eclipse/mosquitto#1028]
This bug happens using ADNS with a bridge.

Any bridge connection attempt that fails more than once seems to be delayed by `keepalive_interval`, and not only by `restart_timeout`.

Log sample, using `restart_timeout = 3` and `keepalive_interval = 5`:
```
1541844877: Connecting bridge (step 1) amb (localhost:1884)
1541844877: Connecting bridge (step 2) amb (localhost:1884)
1541844877: Socket error on client local.abiliojr.amb, disconnecting.
1541844881: Connecting bridge (step 1) amb (localhost:1884)
1541844881: Connecting bridge (step 2) amb (localhost:1884)
1541844886: Socket error on client local.abiliojr.amb, disconnecting.
```

See that in the second attempt, 5 seconds pass until the socket error is detected.

This seems to be caused by a reuse of the context without proper cleaning, leaving `context->events` dirty. This makes the condition `if(!(context->events & EPOLLOUT))` in file loop.c to be evaluated to `false` in the subsequent attempts, changing the behavior and triggering the extra delay.

**Comment by abiliojr** [comment]
Solution in [pull request 1029](https://github.com/eclipse/mosquitto/pull/1029)

**Comment by ckrey** [comment]
I think this issue can be closed as fixed
