### ISSUE TITLE
Docker: Make uid/gid explicit

### ISSUE THREAD

**Issue by daenney** [eclipse/mosquitto#1031]
Currently the Docker image just creates a user and a group for mosquitto. This is fine but users might need to map this to a user/group on their host.

It should be documented somewhere that this results in `uid=100` and `gid=101`. Ideally these would be environment variables that users could change when they build the image, which would also ensure they don't accidentally change across rebuilds. Ideally they'd also use a different pair of uids as the current auto-assigned ones are almost certain to clash with the host.

However, on my host 100:101 results in the files seemingly being owned by `systemd-network:systemd-journal`. Perhaps more useful would be to have mosquitto run as the user `nobody` by default and its group `nogroup`. nobody:nogroup always has 65534 as uid/gid in just about any *nix distribution avoiding potential host/container uid/gid mapping shenanigans when volumes are used.

**Comment by Assar63** [comment]
I agree that it is a bit irritating having different user/group on host and container.

**Comment by Assar63** [comment]
I agree that it is a bit irritating having different user:group on host and container.
In some applications this is really annoying.
However the nobody:nogroup is not good, especially if I want to have the "persistence" activated.
On the other hand the user:group need to get a proper and useful match on host if I want to store this file on host.

**Comment by daenney** [comment]
Why is the nobody:nogroup no good? It will exist on both the host and the container and always maps to the same uid and gid regardless of host.

**Comment by ralight** [comment]
The default uid definitely needs updating, I agree, but it's worth pointing out that using `docker run -u user:group eclipse-mosquitto` will solve most of your problems.

**Comment by daenney** [comment]
I'm not sure how that would work here. The user is created in a `RUN` command and the directories mosquitto writes do are owned by that `uid:gid` combination. By default an `mkdir` will use a `umask` of `0022`, meaning we end up with directories with a mask of `0755` making them only writable for `uid` `100`.

If I now start with `-u 1000:1000` the process won't be able to write into `/mosquitto/data` and `/mosquitto/log` from what I can tell.

**Comment by ralight** [comment]
This will be set as uid 1883 in the 1.5.5 release.
