### ISSUE TITLE
mosquitto_passwd only creates (null):$6$(null)$

### ISSUE THREAD

**Issue by jkoopmann** [eclipse/mosquitto#1032]
Hi,

no matter how I use mosquitt_passwd it only creates these lines:

(null):$6$(null)$

I am running this within a jail in FreeBSD. Any idea?

Regards,
   JP

**Comment by ralight** [comment]
The first (null) should be the username. The only way this would end up as (null) is if you somehow passed a null pointer as an argument on the command line, which I'm sure isn't the case.

For clarity, could you confirm which version you are using and an example command line?

This is me (on Ubuntu, not FreeBSD), creating a new password file, for example:

https://asciinema.org/a/a7ZPWyXlu3HZ6m22Skb1iWRup

**Comment by jkoopmann** [comment]
https://asciinema.org/a/F5hz1adeZGPrESmRbnodqwfY1

mosquitto 1.5.3

Thanks a lot for looking into it.

**Comment by ralight** [comment]
I've just tried on a DigitalOcean droplet with FreeBSD 11.1. I confirm that the version from `pkg install mosquitto` shows the same behaviour you are seeing. If I download the mosquitto source and compile it myself then it works as expected. Perhaps this needs to be taken to FreeBSD instead?

**Comment by jkoopmann** [comment]
That is very strange. I e-mailed the FreeBSD port maintainer. Let's see what Joe comes up with. Otherwise I will have to compile it myself to get a working version... Or can you drop yours somewhere for temporary download?

**Comment by jbenden** [comment]
Hello,

I've [posted a request on the bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=232168) that relates to the [OpenSSL compat](https://github.com/freebsd/freebsd-ports/blob/master/net/mosquitto/files/patch-src_mosquitto__passwd.c) code added to this tool.

Please use the bug report as a means for tracking and reporting.

Best regards,
-Joe

**Comment by AriSuutariST** [comment]
It seems that mosquitto_passwd works in FreeBSD 12.0. The problem affects only 11.x (maybe because the openssl is older version there).

**Comment by AriSuutariST** [comment]
Here is a new issue with a fix:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235834

**Comment by ralight** [comment]
This is fixed and will be in 1.5.8 today, thanks for the help everybody.
