### ISSUE TITLE
Bridge Enhancement: Improve back-off mechanism

### ISSUE THREAD

**Issue by abiliojr** [eclipse/mosquitto#1035]
In the current implementation of bridge connections, back-off `restart_timeout` is a single constant. 

In situations where several thousand mosquittos are bridged to another broker in the cloud and the such broker disconnects all clients at the same time, a huge load peak might be seen when they retry. It could be improved by adding some randomness (jitter) in the mechanism.

I've implemented a single form of such mechanism in the form of [decorrelated jitter](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/).

`restart_timeout` can take the usual 1 parameter for a constant back-off, or 2, as the base and cap.

Please check [pull request 1126](https://github.com/eclipse/mosquitto/pull/1126) for the code

**Comment by ralight** [comment]
This was resolved a while back.
