### ISSUE TITLE
mosquitto crash on save db?

### ISSUE THREAD

**Issue by drJeckyll** [eclipse/mosquitto#1039]
Since couple of days my mosquitto start to crash (segfault).

Running in gdb shows:
Program received signal SIGSEGV, Segmentation fault.
0x000055555556c525 in persist__subs_retain_write (db=db@entry=0x555555586960 <int_db>, db_fptr=db_fptr@entry=0x55555561f6d0, node=0x5555555d26c0,
    topic=<optimized out>, topic@entry=0x555555651fb0 "home/myroom/desk/lamp/settings", level=level@entry=6) at persist.c:291
291                             length = htonl(2+strlen(sub->context->id) + 2+strlen(thistopic) + sizeof(uint8_t));

That's Gentoo Linux and mosquitto 1.5.3

**Comment by ralight** [comment]
Thanks for the backtrace!

Could you try the code from the `fixes` branch to see if you have a problem there?

**Comment by ralight** [comment]
Sorry for the delay, you had me confused for a while there. If you're running in gdb, it will stop on a SIGPIPE by default. It isn't mosquitto crashing, it is gdb stopping. Mosquitto ignores SIGPIPE.

To use gdb you need to run the following command before you start mosquitto:

```
handle SIGPIPE nostop
```

**Comment by drJeckyll** [comment]
Yes, sorry I figured that out after I post reply. 
It's working alright and I don't receive any crashes since then.

**Comment by ralight** [comment]
Excellent, glad to hear it :)
