### ISSUE TITLE
if one bridge is failing, other bridge connections fail as well

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto#104]
migrated from Bugzilla [#452916](https://bugs.eclipse.org/bugs/show_bug.cgi?id=452916)
status NEW severity _normal_ in component _Mosquitto_ for _---_
Reported in version _unspecified_ on platform _PC_
Assigned to: Roger Light

On 2014-11-23 16:14:54 -0500, Roger Light wrote:

> (imported from launchpad)
> 
> I have defined 3 bridge configurations
> However, once I switched on of the servers off, but did not remove the configuration the connection to the other bridges also stopped working.
> Once I removed the bridge definition containing the switched off server the other bridges started to work again.

**Comment by cjmaynard** [comment]
Do you have "round_robin false"?  Try setting it to "false".  I think issue #481 is a duplicate of this one.

**Comment by ralight** [comment]
I'm closing this as a duplicate even though it is the earlier report because #481 has more discussion.
