### ISSUE TITLE
mosquitto has two build systems (and not just for windows)

### ISSUE THREAD

**Issue by gdt** [eclipse/mosquitto#1041]
The documentation says to use cmake on Windows and Mac, and otherwise just a makefile.   This has multiple problems:
 * the makefile is not portable.  Trying to make it portable is essentially reinventing autoconf or cmake
 * Mac is a POSIXy system, so it should be using the same build system as Linux and *BSD.
 * surely the makefile and cmake will get out of date
 * I see QNX changes just happened in cmake, which is inconsistent with the instructions to use the makefile on that platform.

I suggest
 * ask on the list if anyone is using the makefile, and ask them to test with cmake
 * change the instructions to just say to use cmake, always
 * delete the makefile (as soon as we can be sure nobody will be in trouble)

If it turns out that cmake is not ok, because it's too piggy, or platforms can build mosquitto but can't build cmake, then I would suggest
 * add autoconf/automake and make that the standard build for everything but native windows
 * restrict the cmake build to error out except on windows, and rip out all other support.

**Comment by ralight** [comment]
Thanks for your comments Greg, but this isn't something I want to change. If there is a concrete problem with a particular build, then please let us know so it can be fixed.

**Comment by ralight** [comment]
Closing because there are no plans to change this. The cmake builds have been improved a lot recently as well.
