### ISSUE TITLE
connect_async(): Misleading return codes? Segfault on TLS Errors?

### ISSUE THREAD

**Issue by hetit** [eclipse/mosquitto#1047]
Sorry if I make a stupid mistake by not understanding the threaded interface entirely, but as an application programmer only, I am missing the skills for a more precise analysis ...

Environment:
Raspberry Pi, Stretch
mosquitto 1.5.3 and 1.5.4 (slightly different behaviour), using the mosquittopp C++ wrapper
TLS-PSK with the simplest possible configuration

Since 1.5.3 (never saw this in earlier versions) I get return codes from mosquittopp::connect_async() that should not be possible. To be specific: this are the return values from connect_async() - not an errno set in conjunction with MOSQ_ERR_ERRNO.
I got: '15' on a failed hostname resolution (reason was a misconfiguration in /etc/hosts). This is reproduceable in 1.5.4 as well - and it has nothing to to with TLS.
But: '8' (followed by a segfault) when a TLS error occurs. This behaves slightly different in 1.5.4: The connect_async() call doesn't return before the segfault is signalled so I cannot see a return code any more. But in both versions the on_log callback is always still executed(!) and shows alternating one of

OpenSSL Error: error:14094085:SSL routines:ssl3_read_bytes:ccs received early
OpenSSL Error: error:14183067:SSL routines:tls_get_message_header:bad change cipher spec
OpenSSL Error: error:14094044:SSL routines:ssl3_read_bytes:internal error
OpenSSL Error: error:140940F5:SSL routines:ssl3_read_bytes:unexpected record
and perhaps others I have missed

before the segfault. This happens only 1 time out of 10 on an irregular basis. (Might this really be the frequency of TLS errors?). 90% of the calls work as expected with TLS and 100% without TLS.

Since 1.5.4 (dont't know if 1.5.3 too) I get another 'wrong' error code from mosquittopp::subscribe() when there was no CONNACK before calling subscribe(): MOSQ_ERR_SUCCESS instead of MOSQ_ERR_NO_CONN as earlier versions did. I'm not entirely shure, but as far as I remeber this worked correctly up to 1.5.2.

Sorry again if my problem is of the stupid sort, I would appreciate any helping comment!

**Comment by ralight** [comment]
I suspect that some of this might be down to documentation being a bit out of date. A return code of 15 is  `MOSQ_ERR_EAI`, which is related to host name lookups. That error code isn't referenced anywhere in mosquitto.h though, so that's our problem not yours.

Are you able to share a simple example that shows the segfault?

**Comment by hetit** [comment]
Thank you for the reply and the hint with the documentation!
So I should stop throwing exceptions on return codes I don't know :-)
Code example follows shortly (I have 1:9 chance to produce the failure)

**Comment by hetit** [comment]
What I am doing is:

`// before calling loop_start() and connect_async()`
`int mlrc = mosquittopp::tls_psk_set(tls_psk.c_str(), tls_psk_id.c_str());`

This always returned MOSQ_ERR_SUCCESS so far and the following loop_start() as well. 
But the following code, executed immediately after loop_start(), occasionally fails:

`errno = 0;`
`int mlrc = mosquittopp::connect_async(broker_host.c_str(), port, keepalive.count());`
`std::cout << "Back from connect_async()" << std::endl;`
 `switch (mlrc) {`
`    case MOSQ_ERR_SUCCESS:`
`     llog(MOSQ_LOG_DEBUG, "Connection request to broker at " + broker_info() + ": " + mosquitto_strerror(mlrc));`
`      break;`
`    case MOSQ_ERR_ERRNO:`
`// check all other (known) return codes ...`

That's what my logger logs on success:

. . .
[DEBUG]   Started MQTT service loop: No error.
[DEBUG]   From mosquitto library: Client CT-Surveyor sending CONNECT
Back from connect_async()
[DEBUG]   Connection request to broker at Surveyor:8883: No error.
. . .

And on failure:

. . .
[DEBUG]   Started MQTT service loop: No error.
[ERR]     From mosquitto library: OpenSSL Error: error:14094085:SSL routines:ssl3_read_bytes:ccs received early
Speicherzugriffsfehler                <-- THIS IS THE SEGFAULT (my Raspian is German)
pi@Surveyor:~ $ <-- Bailed out

So in both cases the on_log() callback executes, otherwise the '[ERR]' logline couldn't have been printed. But connect_async() doesn't return in the failure case.

I tested a few hundred times, but whenever the segfault occours, I receive an on_log() callback with an OpenSSL Error message immediately before. This never happened with any other on_log() message.

Sorry, but I am a bit at a loss for the moment.

**Comment by ralight** [comment]
There's no chance I could have a complete file for testing?

**Comment by hetit** [comment]
Yes there is a chance! Only - I cannot bother you with my current client. It consist of some thousands lines of code spread over different compile units using lots of helper classes. (Partly because of its excessive error checking, logging, statistics collection, configuration possibilities and a strict encapsulation design.) You would not believe that I have tracked down the problem to this single connect_async() call. Neither did I at first, by the way ...
So I will try to reproduce my problem in a minimalistic client which I need to write first. But I have no chance to start this task before the weekend (presumably longer). Perhaps I get some insights and have to apologise ...
I'm only confused by the fact that this 'monster-client' worked several weeks in 24/7 mode on several distributed Pis until I foolishly did two things at once: upgraded from 1.5.2 to 1.5.3 (and later 1.5.4) and started to implement TLS-PSK. My client still works 100% reliable without TLS and with TLS when there are no OpenSSL Errors during the connect (aside from the accepted subscriptions although not connected - with and without TLS).
I can't get rid of the suspicion that I misunderstand something fundamentaly with the threaded interface...

Meanwhile I thank you very much for your concern and time as well as for your work in general! I've started with some late 1.3... version of mosquitto and can witness the evolution since then.

**Comment by hetit** [comment]
```c++
#include <iostream>
#include <string>
#include <mosquittopp.h>

static bool connected {false};

class Service : mosqpp::mosquittopp
{

  bool use_tls {true};
  std::string host {"localhost"};
  std::string user {"Test"};
  std::string pass {"Test"};
  std::string tls_id {"Default"};
  std::string psk {"0123456789ABCDEF"};

  void on_connect_with_flags(int code, int flags)
  {
    std::cout << "CONNACK: " << mosquitto_connack_string(code)
<< ", flags: " << flags << std::endl;
    connected = true;
  }

  void on_log(int level, const char *message)
  {
    std::cout << "Liblog: (" << level << ") " << message << std::endl;
  }

public:

  Service() : mosqpp::mosquittopp("Testclient")
  {
    mosqpp::lib_init();
    mosquittopp::username_pw_set(user.c_str(), pass.c_str());
    if (use_tls) {
      mosquittopp::tls_psk_set(psk.c_str(), tls_id.c_str());
    }
  }

  ~Service()
  {
    mosqpp::lib_cleanup();
  }

  void start()
  {
    mosquittopp::loop_start();
    int port = use_tls ? 8883 : 1883;
    int rc = mosquittopp::connect_async(host.c_str(), port);
    std::cout << "Back from connect_async(): " << mosquitto_strerror(rc) << std::endl;
  }

  void stop()
  {
    mosquittopp::disconnect();
    mosquittopp::loop_stop();
  }

};

int main() {
  Service mqtt;
  mqtt.start();
  while (!connected) {

  }
  mqtt.stop();
  std::cout << "finished" << std::endl;
  return 0;
}

```
```
# Makefile for the MQTTService

COMP = g++
CFLAGS = -Wall -std=c++14
LFLAGS = -pthread -lmosquitto -lmosquittopp
all: MQTTService
MQTTService : MQTTService.o
	$(COMP) -o $@ $^ $(CFLAGS) $(LFLAGS)
%.o : %.cc
	$(COMP) -c -o $@ $< $(CFLAGS)
.PHONY : clean
clean:
	rm -f *.o *.d *.gch
```

**Comment by hetit** [comment]
Managed the testfile earlier than I expected ...

Now this is the code (MQTTService.cpp):

```c++
#include <iostream>
#include <string>
#include <mosquittopp.h>

static bool connected {false};

class Service : mosqpp::mosquittopp
{

  bool use_tls {true};
  std::string host {"localhost"};
  std::string user {"Test"};
  std::string pass {"Test"};
  std::string tls_id {"Default"};
  std::string psk {"0123456789ABCDEF"};

  void on_connect_with_flags(int code, int flags)
  {
    std::cout << "CONNACK: " << mosquitto_connack_string(code)
        << ", flags: " << flags << std::endl;
    connected = true;
  }

  void on_log(int level, const char *message)
  {
    std::cout << "Liblog: (" << level << ") " << message << std::endl;
  }

public:

  Service() : mosqpp::mosquittopp("Testclient")
  {
    mosqpp::lib_init();
    mosquittopp::username_pw_set(user.c_str(), pass.c_str());
    if (use_tls) {
      mosquittopp::tls_psk_set(psk.c_str(), tls_id.c_str());
    }
  }

  ~Service()
  {
    mosqpp::lib_cleanup();
  }

  void start()
  {
    mosquittopp::loop_start();
    int port = use_tls ? 8883 : 1883;
    int rc = mosquittopp::connect_async(host.c_str(), port);
    std::cout << "Back from connect_async(): " << mosquitto_strerror(rc) << std::endl;
  }

  void stop()
  {
    mosquittopp::disconnect();
    mosquittopp::loop_stop();
  }

};

int main() {
  Service mqtt;
  mqtt.start();
  while (!connected) {  }
  mqtt.stop();
  std::cout << "finished" << std::endl;
  return 0;
}
```

The makefile:

```
# Makefile for the MQTTService

COMP = g++
CFLAGS = -Wall -std=c++14
LFLAGS = -pthread -lmosquitto -lmosquittopp

all: MQTTService

MQTTService : MQTTService.o
	$(COMP) -o $@ $^ $(CFLAGS) $(LFLAGS)

%.o : %.cpp
	$(COMP) -c -o $@ $< $(CFLAGS)

.PHONY : clean
clean:
	rm -f *.o *.d *.gch
```

And the terminal output when running the example. This time the third try failed (but I had test sessions with the program working more than 20 times before failure). The failure is ALWAYS preceded by an OpenSSL erorr message passed via the on_log() callback and happens ONLY when this is the case.

```bash
pi@Surveyor:~/Projekte/MQTTTest $ ./MQTTService
Liblog: (16) Client Testclient sending CONNECT
Back from connect_async(): No error.
Liblog: (16) Client Testclient received CONNACK (0)
CONNACK: Connection Accepted., flags: 0
Liblog: (16) Client Testclient sending DISCONNECT
finished
pi@Surveyor:~/Projekte/MQTTTest $ ./MQTTService
Liblog: (16) Client Testclient sending CONNECT
Back from connect_async(): No error.
Liblog: (16) Client Testclient received CONNACK (0)
CONNACK: Connection Accepted., flags: 0
Liblog: (16) Client Testclient sending DISCONNECT
finished
pi@Surveyor:~/Projekte/MQTTTest $ ./MQTTService
Liblog: (8) OpenSSL Error: error:14094044:SSL routines:ssl3_read_bytes:internal error
Speicherzugriffsfehler
pi@Surveyor:~/Projekte/MQTTTest $
```

**Comment by hetit** [comment]
Just now I had this situation too (1 out of hundreds of testruns)

```bash
pi@Surveyor:~/Projekte/MQTTTest $ ./MQTTService
Liblog: (8) OpenSSL Error: error:14094085:SSL routines:ssl3_read_bytes:ccs received early
Liblog: (8) OpenSSL Error: error:141A10F4:SSL routines:ossl_statem_client_read_transition:unexpected message
Back from connect_async(): A TLS error occurred.
^C
pi@Surveyor:~/Projekte/MQTTTest $
```

Two on_log() calls, connect_async() returns with correct return code, then the infinite loop of course, because of missing CONNACK.

**Comment by hetit** [comment]
Closing this issue now as I didn't receive any reaction so far. I meanwhile stopped using mosquitopp and developed my own C++ interface ...
