### ISSUE TITLE
Build fails when using uClibc

### ISSUE THREAD

**Issue by doragasu** [eclipse/mosquitto#1053]
Version 1.5.4 fails when building with uClibc instead of GNU libc.

I have fixed it with the following patch: https://github.com/doragasu/mosquitto/commit/b0e5e184b6ed7cfc8225f98ee5d2dbd20a0d2285

If you think the fix is OK, I can send a PR.

**Comment by karlp** [comment]
Just build with WITH_MEMORY_TRACKING set to no.  that's how it's been done for years in the openwrt packaging.

**Comment by doragasu** [comment]
That makes sense, I'm closing this issue. Thanks!
