### ISSUE TITLE
Issues about Bridging Mechanism

### ISSUE THREAD

**Issue by deniztumer91** [eclipse/mosquitto#1055]
Hi,

I have made several scenarios in the mosquitto environment to understand how the topic remapping mechanism in the bridging could work. After the ending of these scenarios, some unexpected results have occurred.  

The settings of the scenarios:
- In all scenarios, there is a bridge broker and a normal broker. (The normal broker uses the port 1883, and the bridge broker uses the port 1884)
- Every broker has a client that subscribes every topic. (These clients are created after the bridge is made between the brokers)
- Connection name is "bridge-01".
- Methodology: First, I create a normal broker with the default conf file. (mosquitto -p 1883 -v) After that, I create a broker which also work as a bridge. (mosquitto -c mosquitto.conf -p 1884 -v) Before this creation, I have manipulated the conf file for implementing my scenarios. After the bridge is connected, I create two clients that every one of them can subscribe to specific brokers. (mosquitto_sub -p 1883 -t # -k 600 -v and mosquitto_sub -p 1884 -t # -k 600 -v) Lastly, I publish 4 messages (one of them is mosquitto_pub -p 1883 -t sensor1 -m piccolo) and monitor the subscribed clients that take these messages or not.

The Manipulated Conf File: (Used in 1884 broker)
log_type all
connection_messages true
connection bridge-01
address 127.0.0.1:1883
*** topic sensor1 out 2 "" b2/
cleansession true
keepalive_interval 600

*** This configuration is changed in every scenario.

The Result of the Scenarios: (QoS Level=0)

1)manipulated configuration: topic # out 0 "" b2/			(1884->b2,1883->no name)
	
Messages =>						1883	,					1884
-p 1883 -t sensor1 -m piccolo =>		+	(sensor1)		,	              	-
-p 1883 -t b1/sensor1 -m grande =>		+	(b1/sensor1)		,		-
-p 1884 -t b2/sensor1 -m lungo =>		+	(b2/b2/sensor1)	,		+	(b2/sensor1)
-p 1884 -t sensor1 -m ciao =>			+	(b2/sensor1)		,		+	(sensor1)
			
2)manipulated configuration: topic sensor1 out 0 "" b2/		(1884->b2,1883->no name)

Messages =>						1883			,		1884
-p 1883 -t sensor1 -m piccolo =>		+	(sensor1)			,	-
-p 1883 -t b1/sensor1 -m grande =>		+	(b1/sensor1)		,        -
-p 1884 -t b2/sensor1 -m lungo =>	-					 ,       	+	(b2/sensor1)
-p 1884 -t sensor1 -m ciao =>		+	(b2/sensor1)		 ,              +	(sensor1)

3)manipulated configuration: topic # both 0 b1/ b2/			(1884->b2,1883->b1)
		
Messages =>						1883		,			1884
-p 1883 -t sensor1 -m piccolo =>        +	(sensor1)		     ,            	-
-p 1883 -t b1/sensor1 -m grande =>	+	(b1/sensor1)	     ,            	-
-p 1884 -t b2/sensor1 -m lungo =>	-				,	         	+	(b2/sensor1)
-p 1884 -t sensor1 -m ciao =>		-					,        	+	(sensor1)

4)manipulated configuration: topic sensor1 both 0 b1/ b2/	(1884->b2,1883->b1)
	
Messages =>						1883			,		1884
-p 1883 -t sensor1 -m piccolo =>	        +	(sensor1)		,	                -
-p 1883 -t b1/sensor1 -m grande =>	+	(b1/sensor1)	,	                -
-p 1884 -t b2/sensor1 -m lungo =>	-				,		        +	(b2/sensor1)
-p 1884 -t sensor1 -m ciao =>		-				,		        +	(sensor1)

5)manipulated configuration: topic # out 0 "" b2/
							 topic # in 0 b1/ ""			(1884->b2,1883->b1)
							 
Messages =>						1883		,			1884
-p 1883 -t sensor1 -m piccolo =>	        +	(sensor1)			,                +	(b1/sensor1)
-p 1883 -t b1/sensor1 -m grande =>+	(b1/sensor1)		    ,            +	(b1/b1/sensor1)
-p 1884 -t b2/sensor1 -m lungo =>	+	(b2/b2/sensor1)	,	        +	(b2/sensor1)
-p 1884 -t sensor1 -m ciao =>		+	(b2/sensor1)		,                +	(sensor1)

6)manipulated configuration: topic sensor1 out 0 "" b2/
							 topic sensor1 in 0 b1/ ""		(1884->b2,1883->b1)

Messages =>						1883			,		1884
-p 1883 -t sensor1 -m piccolo =>	        +	(sensor1)			,                +	(b1/sensor1)
-p 1883 -t b1/sensor1 -m grande =>	+	(b1/sensor1)		,                -
-p 1884 -t b2/sensor1 -m lungo =>	-					,	        +	(b2/sensor1)
-p 1884 -t sensor1 -m ciao =>		+	(b2/sensor1)		 ,               +	(sensor1)

After these results, I think, I have some problems. (I tried many times these scenarios but the results do not change)
Problems:
1)For example: in the second scenario I don't understand why the third message is not taken by broker 1883. 
2)Or, I expect 3rd scenario and 5th scenario have the same results.(Also, 4th and 6th should have same results) But there are many differences between these results. 
3)Last thing is 3rd and 4th have the same results, but why 1st and 2nd have not same results. (Also, I expect 5th and 6th should have same results)

P.S: I have used the mosquitto version 1.4.14 on Windows. Local and remote broker were created on the same PC.

**Comment by ralight** [comment]
I'll try to work through this tomorrow, thanks for the details.

**Comment by ralight** [comment]
I think this all makes sense to me. I've gone through each of your scenarios and explained what is happening. If it still doesn't make sense, let me know.

---

1)
`topic # out 0 "" b2/`

This means:
Subscribe to `#` on the local 1884 broker, then publish anything that matches `#` to the 1883 broker with a `b2/` prefix. For example a topic of `deniztumer91/bridge` on 1884 would be published to `b2/deniztumer91/bridge`. There is no bridging from 1883 to 1884.

Messages => 1883 , 1884
`-p 1883 -t sensor1 -m piccolo => + (sensor1) , -` : makes sense
`-p 1883 -t b1/sensor1 -m grande => + (b1/sensor1) , -` : makes sense
`-p 1884 -t b2/sensor1 -m lungo => + (b2/b2/sensor1) , + (b2/sensor1)` : makes sense
`-p 1884 -t sensor1 -m ciao => + (b2/sensor1) , + (sensor1)` : makes sense

---
2)
`topic sensor1 out 0 "" b2/ `

This means:
Subscribe to `sensor1` on the local 1884 broker, then publish anything that matches `sensor1` to the 1883 broker with a `b2/` prefix. For example a topic of `sensor1` on 1884 would be published to `b2/sensor1`. There is no bridging from 1883 to 1884.

Messages => 1883 , 1884
`-p 1883 -t sensor1 -m piccolo => + (sensor1) , -` : makes sense
`-p 1883 -t b1/sensor1 -m grande => + (b1/sensor1) , -` : makes sense
`-p 1884 -t b2/sensor1 -m lungo => - , + (b2/sensor1)` : makes sense (doesn't match `sensor1`)
`-p 1884 -t sensor1 -m ciao => + (b2/sensor1) , + (sensor1)` : makes sense (does match, has prefix added)

---

3)
`topic # both 0 b1/ b2/`

This means:
Subscribe to `b1/#` on the local 1884 broker, then publish anything that matches `b1/#` to the 1883 broker, by removing the `b1/` prefix and adding a `b2/` prefix. For example a topic of `b1/sensor1` on 1884 would be published to `b2/sensor1`. This uses `both`, so the 1884 broker also subscribes to `b2/#` on the 1883 broker. Any messages that come in on that topic have the `b2/` prefix removed, and the `b1/` prefix added.

Messages => 1883 , 1884
`-p 1883 -t sensor1 -m piccolo => + (sensor1) , -` : makes sense (doesn't match `b2/#`)
`-p 1883 -t b1/sensor1 -m grande => + (b1/sensor1) , -` : makes sense (doesn't match `b2/#`)
`-p 1884 -t b2/sensor1 -m lungo => - , + (b2/sensor1)` : makes sense (doesn't match `b1/#`)
`-p 1884 -t sensor1 -m ciao => - , + (sensor1)` : makes sense (doesn't match `b1/#`)

---

4)
`topic sensor1 both 0 b1/ b2/`

This means:
Subscribe to `b1/sensor1` on the local 1884 broker, then publish anything that matches `b1/sensor1` to the 1883 broker, by removing the `b1/` prefix and adding a `b2/` prefix. For example a topic of `b1/sensor1` on 1884 would be published to `b2/sensor1` on 1883. This uses `both`, so the 1884 broker also subscribes to `b2/sensor1` on the 1883 broker. Any messages that come in on that topic have the `b2/` prefix removed, and the `b1/` prefix added.

Messages => 1883 , 1884
`-p 1883 -t sensor1 -m piccolo => + (sensor1) , -` : makes sense (doesn't match `b2/sensor1`)
`-p 1883 -t b1/sensor1 -m grande => + (b1/sensor1) , -` : makes sense (doesn't match `b2/sensor1`)
`-p 1884 -t b2/sensor1 -m lungo => - , + (b2/sensor1)` : makes sense (doesn't match `b1/sensor1`)
`-p 1884 -t sensor1 -m ciao => - , + (sensor1)` : makes sense (doesn't match `b1/sensor1`)

---

5)
```
topic # out 0 "" b2/
topic # in 0 b1/ ""
```
This means:
Subscribe to `#` on the local 1884 broker, then publish anything that matches `#` to the 1883 broker, by adding a `b2/` prefix. For example a topic of `b2/sensor1` on 1884 would be published to `b2/b2/sensor1` on 1883.  No bridging from 1883 to 1884.

Subscribe to `#` on the remote 1883 broker, then any messages that come in on that topic have a `b1/` prefix added for the 1884 broker.

Messages => 1883 , 1884
`-p 1883 -t sensor1 -m piccolo => + (sensor1) , + (b1/sensor1)` : makes sense
`-p 1883 -t b1/sensor1 -m grande =>+ (b1/sensor1) , + (b1/b1/sensor1)` : makes sense
`-p 1884 -t b2/sensor1 -m lungo => + (b2/b2/sensor1) , + (b2/sensor1)` : makes sense
`-p 1884 -t sensor1 -m ciao => + (b2/sensor1) , + (sensor1)` : makes sense

---
6)

```
topic sensor1 out 0 "" b2/
topic sensor1 in 0 b1/ ""
```
This means:
Subscribe to `sensor1` on the local 1884 broker, then publish anything that matches `sensor1` to the 1883 broker, by adding a `b2/` prefix. For example a topic of `sensor1` on 1884 would be published to `b2/sensor1` on 1883.  No bridging from 1883 to 1884.

Subscribe to `sensor1` on the remote 1883 broker, then any messages that come in on that topic have a `b1/` prefix added for the 1884 broker.

Messages => 1883 , 1884
`-p 1883 -t sensor1 -m piccolo => + (sensor1) , + (b1/sensor1)` : makes sense
`-p 1883 -t b1/sensor1 -m grande => + (b1/sensor1) , -` : makes sense (doesn't match `sensor1`)
`-p 1884 -t b2/sensor1 -m lungo => - , + (b2/sensor1)` : makes sense (doesn't match `sensor1`)
`-p 1884 -t sensor1 -m ciao => + (b2/sensor1) , + (sensor1)` : makes sense

**Comment by deniztumer91** [comment]
Thank you ralight, I understand clearly.
