### ISSUE TITLE
mosquitto_sub should give up if not authorized

### ISSUE THREAD

**Issue by benbarbour** [eclipse/mosquitto#1056]
Currently if you call mosquitto_sub with an incorrect username and/or password it keeps retrying the connection, which gives an infinite stream of

```
Connection Refused: not authorised.
Connection Refused: not authorised.
Connection Refused: not authorised.
Connection Refused: not authorised.
```

It seems to me that mosquitto_sub should recognize that the connection will never work with it's current configuration and give up.

**Comment by karlp** [comment]
Ben Barbour <notifications@github.com> wrote:
> Currently if you call mosquitto_sub with an incorrect username
> and/or password it keeps retrying the connection, which gives
> an infinite stream of
> 
> ```
> Connection Refused: not authorised.
> Connection Refused: not authorised.
> Connection Refused: not authorised.
> Connection Refused: not authorised.
> ```
> 
> It seems to me that mosquitto_sub should recognize that the
> connection will never work with it's current configuration and
> give up.
> 

It might start working :) just as servers can be started/stopped,
so can auth changes. I think, for consistency, that mosquitto_sub
should retry forever, just as it does, on all errors, or no
errors, not try and mix up some errors as being special.

Cheers,
Karl P

**Comment by ralight** [comment]
I've had a similar thought to be honest.

I think perhaps it really needs a review of what happens in the different situations that can arise. At the moment there is inconsistency - if you start mosquitto_sub then the broker goes down, it will carry on trying to connect. If you start mosquitto_sub when the broker isn't up though, it will just quit straight away, for example.

**Comment by Assar63** [comment]
The favoured behaviour depend on which situation I use mosquitto_sub in.
If I just want to test connection and do some test, it often does not matter.
If I use mosquitto_sub in a script I would like to be able to use both of them.
A good solution would be to keep current behaviour as standard and add one or two switches to tweek the behaviour.
Example:
-X 0 - Current behaviour. Keep trying on authorization failure, Quit when no server at start, Keep trying when loosing connection.
-X 1 - ...
-X 2 - ...
-X 1 -

**Comment by ralight** [comment]
The behaviour now is to give up if the CONNACK is rejected, and has been for a whlle so I'm closing this issue.
