### ISSUE TITLE
CONNACK after mosquitto_reconnect()?

### ISSUE THREAD

**Issue by amasmiller** [eclipse/mosquitto#1058]
I am experiencing differing behavior between two recent versions of `mosquitto`, and am unsure if the behavior is expected.

When running the `mosquitto` broker binary (version `1.4.14`  on Fedora 27) and I use the API in a client to reconnect via the `mosquitto_reconnect()` API call after a successful `mosquitto_connect()` call, I receive a CONNACK back from the `mosquitto` broker binary.

However, if I upgrade to version `1.5.3-1.fc27`,  I do not receive a CONNACK back from the broker after calling `mosquitto_reconnect()` from the client API.

Is this expected?  As far as I can tell from the MQTT standard, a CONNACK should always be sent after a connection attempt, even if it is a reconnect.

**Comment by ralight** [comment]
Closing due to no more information, if you still have the issue please reopen and provide more details.
