### ISSUE TITLE
logging not enabled on password utility

### ISSUE THREAD

**Issue by ppeters0502** [eclipse/mosquitto#1060]
Logging is currently set (when enabled) for logging publish request data, subscription request data, broker statistics, and server status statistics. Currently nothing is being logged by the broker for any events that involve the password utility (mosquitto_passwd), since this is a separate utility outside of the broker workflow. 

Even though this utility is (generally) only accessible from the host machine, A security feature that could be implemented is that this utility could include logging of events such as the creation of a new user, the deletion of a user, password changes, and batch commands. This could give insight to events such as an unauthorized user resetting passwords of higher level broker accounts, key broker accounts being deleted prematurely, and other security issues that currently aren't being tracked by the broker.

**Comment by ralight** [comment]
I believe this is out of scope for the password utility. Perhaps this needs to be clearer in the documentation. You should probably think of mosquitto_passwd as being akin to the Apache2 htpasswd utility, which is used by a website admin to add simple authentication to a web page. It's not something you give general access to. If you need this type of authentication, you need to use an authentication plugin.

**Comment by ppeters0502** [comment]
Makes sense, I understand! Thanks fr the response, I'll close the issue.
