### ISSUE TITLE
misleading error message when using ADNS without internet connection

### ISSUE THREAD

**Issue by jsaak** [eclipse/mosquitto#1062]
When the broker tries to connect to a bridge when there is no internet, then error message is:
"Error creating bridge: Protocol not supported."
instead of
"Network unreachable"

I added some debug code:
```
1543645727: Connecting bridge (step 1) olivia (1.1.1.1:188)
1543645727: net__try_connect_step1
1543645727: Connecting bridge (step 2) olivia (1.1.1.1:188)
1543645727: net__try_connect_step2
1543645727: addrinfo: (ai_flags: 40, ai_family: 2, ai_socktype: 1, ai_protocol: 6)
1543645727: addrinfo: (ai_flags: 40, ai_family: 2, ai_socktype: 2, ai_protocol: 17)
1543645727: addrinfo: (ai_flags: 40, ai_family: 2, ai_socktype: 3, ai_protocol: 0)
1543645727: 3Error creating bridge: Protocol not supported.
```

This means, that when there is no internet, adns gives back 3 addrinfo: 6 == TCP, 17 == UDP and 0 which is invalid.

I think the best solution would be to give SOCK_STREAM to getaddrinfo_a.
We do not want UDP connections at all.
And with the hint, it does not give back protocol 0.

In lib/net_mosq.c:net__try_connect_step1
```
  struct addrinfo hints;
  memset(&hints, 0, sizeof(struct addrinfo));
  hints.ai_socktype = SOCK_STREAM;
  mosq->adns->ar_request = &hints;
```

The reason this is not a pull request, is that i am not sure that stack allocated addrinfo is a good solution. It may need to be heap allocated.

**Comment by ralight** [comment]
Thanks very much. In my testing it was still unreliable using a stack allocated hints struct, so I've implemented it with the heap. It's in the fixes branch if you would like to give it a test.
