### ISSUE TITLE
Unable to start windows service

### ISSUE THREAD

**Issue by svanderh** [eclipse/mosquitto#1063]
i have installed version 1.5.4 but i'm not able to start the windows service.
- All files are there, 
- Config file is the default one
- MOSQUITTO_DIR is set
- mosquitto -v mode works

but when you try to install mosquitto as a service nothing happens (returns command prompt, service is not started, and services is not started after a reboot)

Can someone help or give a hint ?

(I have already installed mosquitto several times on linux, this is the first time on a windows 10 machine...)

edit: it's no problem to install version 1.3.5 as a service on the pc.

**Comment by ralight** [comment]
How are you trying to install it as a service? Running `mosquitto install` should do it. You'll need to do that from a command prompt running as an admin user.

**Comment by ralight** [comment]
I've added some error messages in case the service install fails, it will be in 1.5.5.

**Comment by ruant** [comment]
This also touches what i'm stuggeling with.
The service showed up after rebooting however, but the service is set to run `mosquitto.exe run`
Whice never actually starts the service

However running `mosquitto.exe -v` works fine.

**Comment by ralight** [comment]
The 1.5.5 version is available if you'd like to give that a try.

**Comment by ralight** [comment]
There have been substantial changes to Windows support since 1.5.5, so I'm closing this issue. If it's still a problem, please feel free to open a new issue.
