### ISSUE TITLE
Provide pkg-config library file

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto#107]
migrated from Bugzilla [#433243](https://bugs.eclipse.org/bugs/show_bug.cgi?id=433243)
status UNCONFIRMED severity _enhancement_ in component _Mosquitto_ for _---_
Reported in version _unspecified_ on platform _All_
Assigned to: Roger Light

On 2014-04-22 15:02:31 -0400, Nicholas Humfrey wrote:

> Please can you provide and install libmosquitto.pc pkg-config file to make it easier to detect libmosquitto.

**Comment by jensschroer** [comment]
@ralight I am happy to try to provide a PR for this but the debian branch seems to be broken and out of sync with debian upstream according https://qa.debian.org/cgi-bin/vcswatch?package=mosquitto 
Appreciate any suggestions on how I could help with this.

**Comment by ralight** [comment]
This was completed for the Debian packaging a while back.
