### ISSUE TITLE
Connection problems for a webadress with tls

### ISSUE THREAD

**Issue by Torsten12** [eclipse/mosquitto#1074]

**Comment by Torsten12** [comment]
Sorry for the first empty message - I miss clicked.
So I have the following problem I need to get a c++ connection to a mqtt server, which uses tlsv1.2.
There is no certificate, just a username/password security check. 
I try to post just the key lines

backendmanager.h:

    #ifndef TEMPERATURE_CONVERSION_H
    #define TEMPERATURE_CONVERSION_H
    #include <mosquittopp.h>
    #include <boost/move/unique_ptr.hpp>
    #include <boost/thread.hpp>
    #include <boost/shared_ptr.hpp>
    #include <boost/make_shared.hpp>
    namespace mqtt {

    class BackendManager : public mosqpp::mosquittopp
	{
	public:
		BackendManager(const ConfigBackendManager &config);
		virtual ~BackendManager();

		void on_connect(int rc);
		void on_message(const struct mosquitto_message *message);
		void on_subscribe(int mid, int qos_count, const int *granted_qos);
	};
    }
    #endif

backendmanager.cpp:

    #include <cstdio>
    #include <cstring>
    #include <string>
    #include "BackendManager.h"
    namespace mqtt {

	enum SSL_VERIFCATION :uint8_t
	{
		SSL_VERIFY_NONE = 0,
		SSL_VERIFY_PEER  = 1
	};


	BackendManager::BackendManager(const ConfigBackendManager &config) : mosquittopp(config.id_), m_config(config)
	{
		tls_insecure_set(true);

		// Enable ssl, but deactivate CERTIFICATE checks
		if (tls_opts_set(SSL_VERIFCATION::SSL_VERIFY_NONE, "tlsv1.2", 0) != MOSQ_ERR_SUCCESS)
		{
			LOG_ERROR_STREAM("Setting of advanced SSL/TLS options failed");
			return;
		}		

		// Set the username/password + checkup
		if (username_pw_set(m_config.username_, m_config.password_) != MOSQ_ERR_SUCCESS)
		{
			LOG_ERROR_STREAM("Wrong authenfication - check username and password for mqtt");
			return;
		}

		if (auto result = connect("remas-api.ivi.fraunhofer.de", 8883, 60) != MOSQ_ERR_SUCCESS)
		{
			uint8_t code = static_cast<uint8_t>(result);
			LOG_ERROR_STREAM("No connection");
			return;
		}

	};

	BackendManager::~BackendManager()	{}

	void BackendManager::on_connect(int rc)
	{
		LOG_ERROR_STREAM("Mqtt connected");
		if (rc == 0) {
			/* Only attempt to subscribe on a successful connect. */
			for each (auto channel in m_config.subcribechannels_)
			{
				subscribe(NULL, channel);
			}			
			// create message handler object, reuse message store
			m_messageHandler = boost::movelib::make_unique<BackendMessageHandler>(m_messageStore);
		}
	}

	void BackendManager::on_message(const struct mosquitto_message *message)
	{
		if (!strcmp(m_config.subcribechannels_[0], message->topic))
		{
			m_messageHandler->handleMessage((char*)message->payload);
		}
	}

	void BackendManager::on_subscribe(int mid, int qos_count, const int *granted_qos)
	{
		LOG_ERROR_STREAM("Subscription succeeded.\n");
	}
    }

main:

     void service()
    {
	// initiate mosquitto library usage
	mosqpp::lib_init();
	
	std::vector<const char*> subcribechannels;
	subcribechannels.push_back("remas/tud-vlp/airport");

	m_backendManager = boost::movelib::make_unique<mqtt::BackendManager>(mqtt::ConfigBackendManager("example",
		"xxxx.de",
		8883,
		"username",
		"password",
		subcribechannels,
		600));

	m_backendManager->loop_forever();
    }

So the problem is I don't come to the on_connect/on_subscribe/on_message. There isn't any error in the connect function. The code just proceeds to the loop_forever() - method and hangs in the thread. I set up a local mqtt server, without tls and it just works fine. 

So my next move was to do the whole thing in python 
here is the short version of it.

python:

    from json import load
    from logging import basicConfig, getLogger, DEBUG, INFO
    from paho.mqtt.client import Client, MQTT_ERR_SUCCESS
    from psutil import process_iter
    from subprocess import PIPE, Popen
    from ssl import CERT_NONE

    ###############
    # CONNECTIONS #
    ###############
    # remote host information
    REMOTE_HOST = "remas-api.ivi.fraunhofer.de"
    REMOTE_PORT = 8883
    # local host information
    LOCAL_HOST = "localhost"
    LOCAL_PORT = 1883
    # common clients keepalive
    KEEPALIVE = 600

    ##################
    # AUTHENTICATION #
    ##################
    # auth file without path appending
    AUTHENTICATION_FILE = "configuration/authorization_mqtt.json"
    # leave default username and password if no authorization.json configuration file was given
    DEFAULT_USERNAME = "roman.busse"
    DEFAULT_PASSWORD = "VojUriLKhOsmzUJQ1lld"

    MOSQUITTO_SERVER = "mosquitto.exe"

    ##########
    # TOPICS #
    ##########
    #TRAFFIC_LIGHTS_VAMOS_TOPIC = "remas/tud-vlp/airport/flatbuffers"
    TRAFFIC_LIGHTS_VAMOS_TOPIC = "remas/tud-vlp/airport"

    SUBSCRIBE_TOPICS = [TRAFFIC_LIGHTS_VAMOS_TOPIC]

    def on_connect(client, userdata, flags, result_code):
	"""
	Connect Handler -> Subscribes to the test topic.
	
	:param client: the client the message comes from
	:param userdata: userdata from the connection
	:param flags from the connection
	:param result_code: result code
	"""
	logger.info("Connected with result code %s" %(result_code, ))
	for subscribe_topic in SUBSCRIBE_TOPICS:
		logger.info("Subscribe to Topic %s" %(subscribe_topic, ))
		result = client.subscribe(subscribe_topic)
		if result[0] == MQTT_ERR_SUCCESS:
			logger.info("Subscribe was successful")

    def on_message(client, userdata, message):
	...

    if __name__ == "__main__":
	try:
		start_mosquitto()
		# create client acting as remote client for the backend
		remote_client = Client()
		# create client for data publishing (relaying) to localhost
		local_client = Client()
		# register handlers
		remote_client.on_connect = on_connect
		remote_client.on_message = on_message
		remote_client.on_disconnect = on_disconnect
		local_client.on_disconnect = on_disconnect
		# update authorization data
		username, password = get_authentication(DEFAULT_USERNAME, DEFAULT_PASSWORD)
		# enable ssl, but deactivate CERTIFICATE checks
		remote_client.tls_set(cert_reqs=CERT_NONE)
		# remote_client.tls_insecure_set(True)
		# set authentication
		remote_client.username_pw_set(username=username, password=password)
		
		try:
			# connect client to remote host
			remote_client.connect(host=REMOTE_HOST, port=REMOTE_PORT, keepalive=KEEPALIVE)
		except Exception as exception:
			logger.error("Could not connect remote client. Does your network allow connections to port: %s?" %(REMOTE_PORT))
			raise exception
		try:
			# connect client to local host
			local_client.connect(host=LOCAL_HOST, port=LOCAL_PORT, keepalive=KEEPALIVE)
		except Exception as exception:
			logger.error("Could not connect local client. Did you start the Mosquitto Server via mosquitto.exe?")
			raise exception
		# wait for new messages
		# loop forever implements reconnects for us
		remote_client.loop_forever()
	except KeyboardInterrupt, SystemExit:
		logger.error("Closed due to Keyboardinterrupt")
	except Exception as exception:
		logger.error("Closed due to Exception: %s" %(exception, ))

So in python it actually works without problems. 

So what I have done to solve the problem:
I manualy build the lib with  the WIN64 OpenSSL v1.1.1a (not the light version, because than I can't build it) from http://slproweb.com/products/Win32OpenSSL.html.
I cmaked it with the flags USE_TLS
![cmake](https://user-images.githubusercontent.com/22800837/49800727-8ffd1280-fd48-11e8-96e7-22a06b12342e.PNG)

I even used wireshark to see the difference between the python version and the cpp version and what I see is that in the python version the TLSv1.2 is used and in the cpp the SSL protocoll is used. 

python.
![python](https://user-images.githubusercontent.com/22800837/49800977-2f220a00-fd49-11e8-999b-66daed3430e6.PNG)

cpp.
![cpp](https://user-images.githubusercontent.com/22800837/49800988-334e2780-fd49-11e8-8c10-7808d1838d7e.PNG)

So I think the problem is in the tls_opt_set(..) part. But I tryed a lot of stuff and I don't know how to go further...

**Comment by ralight** [comment]
I think the problem is that you're not actually telling your client to use TLS. You need to use `tls_set()` to activate TLS mode, and you will need to pass either cafile or capath to tell it what certificates to trust.

At the moment you are communicating in plain text, the packet size of 110 bytes suggests that the length of your username and password combined is around 12 bytes. Because the communication is on port 8883, wireshark is trying (but failing) to decode it as TLS/SSL. If you tell it you decode it as MQTT you should see a CONNECT packet instead of the 110 byte packet.

**Comment by ralight** [comment]
As an addendum, if you tell the client not to verify the server certificate when using certificate based TLS, you're creating a false sense of security.

**Comment by ralight** [comment]
I think the answer above should have solved this. If not, please reopen and add some more details.
