### ISSUE TITLE
Specifying secure and non-secure listeners causes immediate exit with code 1

### ISSUE THREAD

**Issue by sirockin** [eclipse/mosquitto#1075]
Docker image eclipse-mosquitto:latest (1.5).
Host OS: Linux instance-1 4.14.67+

mosquitto.conf excerpt:
```
# Uncommenting the next line makes server exit with error code 1
# listener 1883 # Unencrypted

# mqtt/tls
listener 8883
cafile /certificate/ca_bundle.crt
certfile /certificate/certificate.crt
keyfile /certificate/private.key

# listener 1884   # Non-encrypted

listener 9001
protocol websockets
cafile /certificate/ca_bundle.crt
certfile /certificate/certificate.crt
keyfile /certificate/private.key

```

Output with 'listener 1883' line uncommented:
```
mqtt-broker_1  | 1544611789: mosquitto version 1.5.5 starting
mqtt-broker_1  | 1544611789: Config loaded from /mosquitto/config/mosquitto.conf.
gclouddeploy_mqtt-broker_1 exited with code 1
```

**Comment by ralight** [comment]
My guess is that the # is causing problems. # is valid and expected input for some of the options so it is only valid as a comment when on the very first character of the line.

If that is the problem, I'll leave this open to see if there can be anything done to improve it - especially the error reporting.

**Comment by sirockin** [comment]
Yes that worked - thanks!

**Comment by kumar003vinod** [comment]
Hi @ralight 
I have proposed one solution for this with #1091. Please take a look.

**Comment by ralight** [comment]
Closing this thanks to the PR from @kumar003vinod !
