### ISSUE TITLE
Broker can't restart with log file on Windows

### ISSUE THREAD

**Issue by lcouz** [eclipse/mosquitto#1080]
Hello,
Running on Windows (in service mode) with logging configuration to file  : "log_dest file ..." in configuration file, when stop the service, the service can't restart.
By reading the code,  in util_mosq.c l.422, "CreateFile" function is called with "CREATE_NEW" parameter.
In cas of an existinf log fille, INVALID_HANDLE_VALUE is returned , this case is not tested in code.
I suggest to use "CREATE_ALWAYS" parameter instead.

Not tested, but problem is probably also present in "application" mode.

**Comment by ralight** [comment]
I've made a change that handles this case for reading an existing file, creating a new file or appending to an existing file. It will be in 1.5.6 soon.
