### ISSUE TITLE
Mosquitto will not build without deprecated OpenSSL APIs

### ISSUE THREAD

**Issue by neheb** [eclipse/mosquitto#1094]
A sample patch is provided at: https://github.com/openwrt/packages/pull/7772

Both OpenSSL 1.1 and 1.0.2 are affected in different ways.

**Comment by karlp** [comment]
Does that patch also work for building with 1.0.2 with deprecated apis disabled? or only for 1.1 with deprecated disabled?

**Comment by neheb** [comment]
Both

**Comment by ralight** [comment]
Thanks for the report!
