### ISSUE TITLE
Cpp static build

### ISSUE THREAD

**Issue by JeremieFiniel** [eclipse/mosquitto#1098]
Hello,
I try to use the cpp static library.
In my cmake I set WITH_STATIC_LIBRARIES and WITH_PIC to ON and set the target_link_libraries with mosquitopp_static. But I got endefined reference error.
In lib/cpp/CMakeLists.txt, mosquittopp_static is linked with ${LIBRARIES} which is empty in my case.
Is this normal behaviour? 
Compilation work if I had libmosquito_static to my target_link_libraries. Is that how it supposed to be used?

Thank you in advance for your help.

**Comment by ralight** [comment]
I'm not entirely clear on what you're asking - is this when compiling your own project, or when compiling the mosquitto source?

Either way, libmosquittopp is just a wrapper around libmosquitto, so if you are using the static libraries you will need to link both of them.

As a side note, libmosquittopp will be going away in the future: https://mosquitto.org/roadmap/

**Comment by ralight** [comment]
I'm closing this because it hasn't seen any activity. If it is still an issue please reopen and provide more details.
