### ISSUE TITLE
client connect/disconnect notification

### ISSUE THREAD

**Issue by danielstock** [eclipse/mosquitto#1106]
i am using mosquitto as the main communication server, with serveral iot devices connecting to it. And my application server also connects to the mosquitto, to get data feed from the devices.

 i assigned each device with a unique client id,  the mosquitto itself knows when the devices connect/disconnect to it,  and the corresponding client ids

But is there any way that  my application server could be notified with above informations? 
The application server should be aware of the device online/offline status.

Thanks.

**Comment by ralight** [comment]
The common way to achieve this is for your client to publish a message
to a known topic, perhaps something like

client/status/<client id>

The message can be anything that you recognise as meaning "online".
I'd suggest "1". It should be a retained message.

The second part is that you need to have your client provide a Will
message, which the broker will publish on behalf of the client when
the client disconnects unexpectedly. The message goes to the same
topic and is set to retained, and has a payload which means "offline".
I'd suggest "0".

**Comment by danielstock** [comment]
Problem solved, thanks roger!
