### ISSUE TITLE
Problem with paho.mqtt, connection failing immediately.

### ISSUE THREAD

**Issue by Laro88** [eclipse/mosquitto#1108]
I get the error code 6 from paho.mqtt using the paho sample applications and my own application.
It looks like mosquitto immediately reject the connection with error code 6. It might as well be a problem with paho, since MQTT.fx is behaving ok, however it could also be some edge case that I have bumped into.

I am on windows 10, compiling x86 using the latest paho ond mosquitto libraries from github.

**Comment by ralight** [comment]
Paho is a project with many different MQTT client implementations. Which one are you using? Can you provide example code?

**Comment by Laro88** [comment]
I am using samples in the github repo for paho.mqtt.cpp
paho.mqtt.cpp\src\samples "data_publish.cpp" and "sync_publish.cpp". As I wrote MQTT.fx works as normal so I am suspecting that the paho client is doing "something" illegal.
I will try to get a proper debug setup to see if I can inspect this issue further.

**Comment by Laro88** [comment]
I have just tried the paho 32bit applications and they work flawlessly with mosquitto so I must be building them a bad configuration. I will spend some more time with this in a couple of weeks when I will get back to fiddling with my builds.
Conclusion. Mosquitto is fine (my bad somewhere) as test apps from Paho is ok.
