### ISSUE TITLE
Increase number in mosq_err_t structure

### ISSUE THREAD

**Issue by Tifaifai** [eclipse/mosquitto#1109]
https://github.com/eclipse/mosquitto/blob/326292681afb835b8b4bb821319171ce9c311461/lib/mosquitto.h#L92
https://github.com/eclipse/mosquitto/blob/326292681afb835b8b4bb821319171ce9c311461/lib/mosquitto.h#L93
https://github.com/eclipse/mosquitto/blob/326292681afb835b8b4bb821319171ce9c311461/lib/mosquitto.h#L94
https://github.com/eclipse/mosquitto/blob/326292681afb835b8b4bb821319171ce9c311461/lib/mosquitto.h#L95

19 - 22 => 21 - 24

**Comment by ralight** [comment]
Well spotted! That's fixed now thank you.
