### ISSUE TITLE
Question about cleansession

### ISSUE THREAD

**Issue by mrpre** [eclipse/mosquitto#1113]
As `[MQTT-3.1.2-5]`  says
```
After the disconnection of a Session that had CleanSession set to 0, the Server MUST store further QoS 1 and QoS 2 messages that match any subscriptions that the client had at the time of disconnection as part of the Session state .   
```  
Does it means that the broker should save further `PUBLISH`(may from other client) that match client's subscriptions which has already closed before ?   
After this client reconnect with CleanSession=0, broker should send the saved `PUBLISH` to client?    
I tried with `mosquitto` but found that the `mosquitto` didn't send the `PUBLISH` to client when client reconnected.  
Does I misunderstand the `[MQTT-3.1.2-5]`?

**Comment by karlp** [comment]
a) the messages must have been published at qos 1 or higher.
b) the client id must be the same, not just reconnecting with clean session = 0.

Those are far and away the most common causes of this queueing not working for people
