### ISSUE TITLE
A way to prevent retained messages?

### ISSUE THREAD

**Issue by realsquash** [eclipse/mosquitto#1115]
I need to prevent all messages from ever being retained, but I don't see any relevant config options for this.  Some client apps set the retained flag (for no good reason) and it's causing a lot of problems for a remote control application.

**Comment by ralight** [comment]
It depends a bit on what you want to do. If you are happy to just have retained messages *denied*, then you could create a plugin. Something like [plugin_no_retain.c](https://github.com/eclipse/mosquitto/files/2789251/plugin_no_retain.txt) should do the job, but I've not tested it.

Alternatively, the `mqtt5` branch, which will become part of version 1.6, has this functionality built in - although it will disconnect a client that sends a message with retain set. Config option is `

If you just want to have the retain flag effectively be ignored, then patching with
[noretain.diff](https://github.com/eclipse/mosquitto/files/2789322/noretain.txt) would be your best short term solution.

**Comment by ralight** [comment]
This has been possible for a while using the `retain_available` broker option.
