### ISSUE TITLE
mosquitto_connect seems to leak memory when using TLS

### ISSUE THREAD

**Issue by Pehoh** [eclipse/mosquitto#1116]
When using mosquitto_connect() with these functions called before:
- mosquitto_lib_init()
- mosquitto_new()
- mosquitto_connect_callback_set()
- mosquitto_message_callback_set()
- mosquitto_publish_callback_set()
- mosquitto_username_pw_set()
- mosquitto_tls_set()
- mosquitto_tls_opts_set()

Valgrind reports me some memory lost (20 bytes definitely lost and 16 bytes indirectly lost).

If I remove the TLS part of my application (mosquitto_tls_set() and mosquitto_tls_opts_set()) and remove the TLS configuration on the broker, the memory lost fall to 0 byte.

Configuration:
Mosquitto 1.5.3, TLS v1.2, server certificate only.

Are you aware of this?

**Comment by ralight** [comment]
Could you provide the two valgrind traces please?

**Comment by aaronovz1** [comment]
Maybe related to #592 which was fixed in 1.5.4?

**Comment by ralight** [comment]
I can't reproduce this myself, and you were having trouble doing the same, plus this has been dormant for a while so I'm going to close this issue. If it is still a problem please reopen and provide details.
