### ISSUE TITLE
Windows 64 install page not readable

### ISSUE THREAD

**Issue by freking** [eclipse/mosquitto#1118]
The dependencies page of the installer cuts off one of the required programs, libcrypto-1_1-x64.dll.
In my case this file is not present and causes a system error when opening Mosquitto.  If the user doesn't know they need to install this driver they won't know why the installer continues to fail.

**Comment by ralight** [comment]
Which version are you using? Version 1.5.5 at least doesn't even have a dependencies page.

**Comment by ralight** [comment]
I'm closing this because I think it is fixed and it hasn't seen any updates for a while. If it's still a problem please reopen.
