### ISSUE TITLE
man page typo for mosquitto-conf (use_username_as_clientid)

### ISSUE THREAD

**Issue by pjpapad** [eclipse/mosquitto#1120]
man page for mosquitto-conf (https://mosquitto.org/man/mosquitto-conf-5.html)

_use_username_as_clientid_
`... This allows authentication to be tied to the _clientid_, ...`
this should probably be:
`... This allows authentication to be tied to the **_username_**, ...`

**Comment by ralight** [comment]
The way this was written (and I assert that it does still mean this! :) was to mean "authentication and the client id are linked together", but I think you are reading it as "authentication becomes dependant on the client id", which you are right to say isn't correct. If you've read it wrong, there's some possible confusion so needs rewriting. How about:

```
This allows a one to one mapping between usernames
and client ids (because they are forced to be identical),
and that the only way a client can claim a client id, is to
authenticate with the identical username. This means
that it is possible to prevent one client disconnecting
another by using the same client id, assuming they do
not share the same username/password.
```

**Comment by pjpapad** [comment]
Hi! I think it is much clearer now!

**Comment by ralight** [comment]
Great!
