### ISSUE TITLE
Question: Is mosquitto Broker (1.5.4) supports tls v1.3 version?

### ISSUE THREAD

**Issue by bharanidharan81** [eclipse/mosquitto#1122]

**Comment by ralight** [comment]
Yes, as long as you have openssl 1.1.1 and do not explicitly ask for a different TLS version, then TLS 1.3 will be available.

**Comment by bharanidharan81** [comment]
@ralight  Thanks for response. It works as expected.

**Comment by ralight** [comment]
Great!

**Comment by m0ot** [comment]
hi,
I support mosquitto version 1.5.8 and OpenSSL 1.0.2q  20 Nov 2018. I think both versions support already tls 1.3. But when my client connect the broker then it will be connected with tls 1.2. 
Anyone has an idea?
thanks
