### ISSUE TITLE
Building 1.5.5 with Threading on Windows

### ISSUE THREAD

**Issue by AistisT** [eclipse/mosquitto#1127]
I am trying to build 1.5.5 version of Mosquitto on Windows with threading support.
From what I gather its still there and still uses pthreadVC2.dll
I am using CMAKE to create VS 2017 solution, without UUID as that is not available on windows.
Without websockets and SRV as well.

I am able to build the solution successfully and to gather all required files, but every time I start mosquitto.exe it hangs after following 4 lines:

> 1548676368: mosquitto version 1.5.5 starting
1548676368: Using default config.
1548676368: Opening ipv6 listen socket on port 1883.
1548676368: Opening ipv4 listen socket on port 1883.
> 

Windows service does not fully start either.
Any help would be appreciated in building 1.5.5 with threading support on Windows.

**Comment by AistisT** [comment]
Tiny update, seems its actually semi working and I was rushing to conclusion. Mosquitto.exe does not hang and responds, but I am still unable to start the service. Is system variable still required?  From the readme it does not sound like it is.

**Comment by AistisT** [comment]
Service seems to be working after adding MOSQUITTO_DIR environmental variable, this possibly should be included in the readme file as it was removed.

**Comment by AistisT** [comment]
Reopening - built mosquito depends on SSLEAY32 and LIBEYA32 dlls, instead of renamed dll's.

**Comment by ralight** [comment]
I've added a note about MOSQUITTO_DIR in the Windows readme, thanks for the suggestion.
