### ISSUE TITLE
yum update troubles (likely due to repo file differences)

### ISSUE THREAD

**Issue by JRDavisUF** [eclipse/mosquitto#1129]
I'm getting the following error when I tried to update mosquitto on my RHEL 7 x86_64 host:

file /usr/lib64/libmosquitto.so.1 from install of mosquitto-1.5.5-2.el7.x86_64 conflicts with file from package libmosquitto1-1.5.5-1.1.x86_64

I think this is due to me having both the OpenSuse Oojah and EPEL repos enabled and them providing different versions of mosquitto....but I've had this setup for a while and never run into an issue before, so I'm wondering if something is just out of sync...especially as I'd think the Oojah one would be the more current release...

RHEL EPEL:   mosquitto-1.5.5-2.el7.x86_64.rpm
http://mirror.cs.princeton.edu/pub/mirrors/epel/7/x86_64/Packages/m/

OpenSuse:   mosquitto-1.5.5-1.1.x86_64.rpm
http://download.opensuse.org/repositories/home:/oojah:/mqtt/RedHat_RHEL-7/x86_64/

**Comment by JRDavisUF** [comment]
OK, thx. 

Apparently OpenSuse splits the distribution into multiple pacakges which EPEL doesn't.  As such, I had to delete a couple of those in order for the main package to get upgraded:

rpm -e libmosquitto1-1.5.5-1.1.x86_64 mosquitto-clients-1.5.5-1.1.x86_64

Once that was done, the EPEL update worked fine.

**Comment by ralight** [comment]
Ok, glad you got it sorted.
