### ISSUE TITLE
Return value of mosquitto_new is not checked in mosquittopp::mosquittopp()

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto#113]
migrated from Bugzilla [#473105](https://bugs.eclipse.org/bugs/show_bug.cgi?id=473105)
status UNCONFIRMED severity _normal_ in component _Mosquitto client library_ for _1.4_
Reported in version _1.3.x_ on platform _All_
Assigned to: Roger Light

On 2015-07-20 14:24:18 -0400, Trygve LaugstÃ¸l wrote:

> The v1.3 and v1.4 constructor both look like this:
> 
> ```
> m_mosq = mosquitto_new(id, clean_session, this);
> mosquitto_connect_callback_set(m_mosq, on_connect_wrapper);
> ```
> 
> If the user does something dumb (like passing in NULL and false for id and clean_session) mosquitto_new will return NULL and set errno to EINVAL. The next call will then execute pthread_mutex_lock(&mosq->callback_mutex); but mosq will be NULL.
> 
> I'm not sure what the best way to handle the problem is. Options include throwing an exception, just drop setting the callbacks and have the sub-class/user check errno or have a static method that returns the instance. The last option makes it harder to follow the current pattern of extending mosquittopp.

**Comment by elfring** [comment]
Is such a bug report [similar to the issue "Completion of error handling"](https://github.com/eclipse/mosquitto/issues/1 "More error handling")?
