### ISSUE TITLE
Question: I have 2 listeners. Is it possible to deny the access for a device to one listener (non-SSL listener)? 

### ISSUE THREAD

**Issue by rbboo** [eclipse/mosquitto#1130]
Hello,

I have two listeners configured in my mosquitto.conf file. One with SSL configured and the other one not. Is it possible to deny the access for a client on the non SSL listener ?

Thanks!

**Comment by ralight** [comment]
Yes, you can have different authentication options on different listeners if you use `per_listener_settings true`. For example:

```
per_listener_settings true

listener 1883
password_file no-tls.passwd

listener 8883
cafile ca.crt
certfile server.crt
keyfile server.key
password_file tls.passwd
```

It's not just `password_file` which can be listener specific, most of the auth/access options are. Does that help?

**Comment by rbboo** [comment]
Hi @ralight,
Great!
Thanks for your help.
Regards
