### ISSUE TITLE
bridge remote_username with spaces doesn't work

### ISSUE THREAD

**Issue by beville** [eclipse/mosquitto#1131]
I'm trying to set the bridge username to be something with spaces.  For example:

`remote_username user one`

Unfortunately the config parser doesn't seem to like this.  I see there is an older issue (#150) that had the same issue for the bridge password.  

For someone who knows this config parser well, this would probably be a pretty straightforward fix.

**Comment by beville** [comment]
I actually had a go at this, and I got it to work.  Not fully tested, though, so instead of a pull request, just attaching a patch file (zipped).

[remote_username_spaces.patch.zip](https://github.com/eclipse/mosquitto/files/2810051/remote_username_spaces.patch.zip)

**Comment by ralight** [comment]
That's lovely, thanks very much. I've made the appropriate change on my local branch and it will be part of 1.5.6 soon.

**Comment by karlp** [comment]
(incoming, bug reports that usernames can't start or end with quote marks...., spec says it can be any utf8 encoded string)
