### ISSUE TITLE
use_identity_as_username typo/confict in mosquuito.conf man page

### ISSUE THREAD

**Issue by adrianp-sti** [eclipse/mosquitto#1134]
In the man page for mosquitto.conf under "Authentication" it has:

"If set to true, use_identity_as_user causes the Common Name (CN) from the client certificate to be used instead of the MQTT username for access control purposes. The password is **not** replaced because it is assumed that only authenticated clients have valid certificates."

Later in the man page it has:

"use_identity_as_username

If require_certificate is true, you may set use_identity_as_username to true to use the CN value from the client certificate as a username. If this is true, **the password_file option will not be used** for this listener."

I'm assuming here that the initial para in the Authentication section is wrong and the word "not" needs to be removed ? i.e. if you set use_identity_as_user then passwords/password_file option is ignored.

Also it referrs to "use_identity_as_user" in the same para when I think it means "use_identity_as_username"

**Comment by ralight** [comment]
Thanks, I agree that is a bit confusing. If you use `require_certificate true`, and set `use_identity_as_username true`, then the authentication is carried out through you having the certificate, and so a provided username and password are not used. I've updated the file in my local branch and fixed the other typo as well. It'll be part of 1.5.6 soon.
