### ISSUE TITLE
Mosquitto websocket unknown client timeout produce segfault

### ISSUE THREAD

**Issue by Pehoh** [eclipse/mosquitto#1135]
We use paho.mqtt.js to set a mosquitto session on our website to communicate with other applications on our system. We are facing to an issue when we reboot the system and still connected to a web page using mosquitto. The function onConnectionLost is called on the web page calling the connect function each time our timeout is reached. The issue comes after around 2 minutes with this debug:

> Client <unknown> has exceeded timeout, disconnecting.
> Error in epoll disconnecting websockets: No such file or directory
> Segmentation fault (core dumped)
> 

We think the client on the web page connect again once the mosquitto service is alive on our system after the reboot and reconnect with the same options. That's why the web server client is considered as unknown client. The issue is that mosquitto crashes with a Segmentation fault. So even if we force the service to restart we lose all retained messages.
We noticed that if we update the web page before the 2 minutes timeout, the unknown client is disconnected without segmentation fault:

> Socket error on client <unknown>, disconnecting.

Do we have a way to avoid this Segmentation fault? 

We use mosquitto 1.5.3 without TLS/SSL. We use libwebsocket 2.1.1.

**Comment by ralight** [comment]
Can you provide any example code and an exact procedure to get this to occur?

**Comment by Pehoh** [comment]
Please find the example code on my  [gist](https://gist.github.com/Pehoh/13f6489b2c1ab62a2c381bdad748dbb2). There is a README, a mosquitto.conf file, a html and paho MQTT javascript client code.

We tested another version of paho MQTT client, the segfault is still occuring, but not every time. There is still "unknown" client disconnection.

**Comment by stlawrance** [comment]
FWIW I've also seen this (unknown client disconnect, followed by a segfault) but it never seems to happen when I have time to debug it (I just disable websockets and carry on).  I'm using libwebsockets 2.4.2 with TLS.  I've just tried again several times with the above scenario but it hasn't crashed.

**Comment by ralight** [comment]
Thanks for the example code, that made it easy to debug. This was actually fixed in 1.5.4, please try it out and check yourself.

**Comment by Pehoh** [comment]
Thanks ralight, we updated our mosquitto to 1.5.5 and it solves the issue.

**Comment by ralight** [comment]
Thanks for confirming!
