### ISSUE TITLE
Crash of mosquitto broker on Windows when client disconnects from websocket connection

### ISSUE THREAD

**Issue by krismattheus** [eclipse/mosquitto#1137]
There is a bug in the callback_mqtt function in websockets.c, that causes a crash of the mosquitto broker on Windows when a client closes its websocket connection.

https://github.com/eclipse/mosquitto/blob/19fbbd872638904d6900ea4390e5e97e05e1bd11/src/websockets.c#L249 should be changed to:

`if((int)mosq->sock > 0){`
or
`if(mosq->sock != INVALID_SOCKET){`

A socket on Windows is an unsigned int, so this test succeeds even when the value is INVALID_SOCKET.
This invalid test causes the HASH_DELETE to be called again when the socket is already closed. This causes the crash. After changing the code the crash no longer happens.

Some extra info:
We use mosquitto version 1.5.5 and libwebsockets 3.0.1

**Comment by ralight** [comment]
Thanks, that's fixed in my local branch and will be pushed as part of 1.5.6 shortly.
