### ISSUE TITLE
QOS-2 messages not saved when per_listener_settings set to true

### ISSUE THREAD

**Issue by alflexRH** [eclipse/mosquitto#1146]
as discussed and investigated in issue #1081 , it seems to me that QOS2 messages are not stored when per_listener_settings is set to true. 
I can reproduce this with the config file: 
```
port 1884
per_listener_settings true
pid_file /var/run/mosquitto2.pid
```
if i swap between true and false, the problem appears and disappears.

my publish command: mosquitto_pub -t 'test' -m 'test' -q 2
my subscribe command: mosquitto_sub -t 'test' -q 2 -c -i testing

my sequence:

start subscriber
publish
-- message arrives
kill subscriber
publish again
start subscriber again
-- i now expect a message, but there is nothing, if per_listener_settings is true, if its false, it works.

**Comment by ralight** [comment]
Erm, ok :) Do you have any more information to add that couldn't go on the other bug report? If there is a new bug then please go ahead and describe it, otherwise I think this is just duplicating #1081.

**Comment by ralight** [comment]
Ok great!
