### ISSUE TITLE
Can't compile db_dump from v1.5.5 (Linux)

### ISSUE THREAD

**Issue by adrianp-sti** [eclipse/mosquitto#1147]
Trying to compile db_dump on 1.5.5 gets me the following

make mosquitto_db_dump
cc -Wall -ggdb -O2 -I.. -I../../lib -I../.. -c db_dump.c -o db_dump.o
In file included from db_dump.c:28:0:
../mosquitto_broker_internal.h:52:10: fatal error: uthash.h: No such file or directory
 #include "uthash.h"
          ^~~~~~~~~~
compilation terminated.
make: *** [db_dump.o] Error 1

Adding "-I../deps" to the CFLAGS_FINAL line in src/db_dump/Makefile fixes the problem for me

**Comment by ralight** [comment]
Thanks for reporting it, I'm happy to say I'd already caught it in my local branch and it will be part of 1.5.6 soon.
