### ISSUE TITLE
Problems with "mosquitto_pub -l" - no CONACK

### ISSUE THREAD

**Issue by davidgurr** [eclipse/mosquitto#1150]
mosquitto_pub version 1.5.5 running on libmosquitto 1.5.5.

I don't seem to be getting a CONNACK when using stdin as the message source.

When I issue the command line:

> mosquitto_pub -d -h 192.168.0.35 -t garden/cameras/YiCamGarden/stat/ALARM -m ON

I get:

> Client mosqpub|12444-yi-hack-v sending CONNECT
> Client mosqpub|12444-yi-hack-v received CONNACK (0)
> Client mosqpub|12444-yi-hack-v sending PUBLISH (d0, q0, r0, m1, 'garden/cameras/YiCamGarden/stat/ALARM', ... (2 bytes))
> Client mosqpub|12444-yi-hack-v sending DISCONNECT

But when I use:

> mosquitto_pub -d -h 192.168.0.35 -t garden/cameras/YiCamGarden/stat/ALARM -l

I get:

> Client mosqpub|11205-yi-hack-v sending CONNECT

and nothing else. I can type message values and hit enter, but nothing gets sent. 

What gives?

**Comment by karlp** [comment]
"works for me" ?
```
$ mosquitto_pub -t bvlah -d  -l
Client mosqpub|8931-strem sending CONNECT
Client mosqpub|8931-strem received CONNACK (0)
asdf
Client mosqpub|8931-strem sending PUBLISH (d0, q0, r0, m1, 'bvlah', ... (4 bytes))
asdf
Client mosqpub|8931-strem sending PUBLISH (d0, q0, r0, m2, 'bvlah', ... (4 bytes))
^C
```
Anything else going on?

**Comment by davidgurr** [comment]
I built from source for a very small footprint device, so a lot is turned off. This might be a factor, but I can't spot anything  suspicious - here's my flags from config.mk:

> WITH_WRAP:=no
> 
> # Comment out to disable SSL/TLS support in the broker and client.
> # Disabling this will also mean that passwords must be stored in plain text. It
> # is strongly recommended that you only disable WITH_TLS if you are not using
> # password authentication at all.
> WITH_TLS:=no
> 
> # Comment out to disable TLS/PSK support in the broker and client. Requires
> # WITH_TLS=yes.
> # This must be disabled if using openssl < 1.0.
> WITH_TLS_PSK:=no
> 
> # Comment out to disable client threading support.
> WITH_THREADING:=yes
> 
> # Comment out to remove bridge support from the broker. This allow the broker
> # to connect to other brokers and subscribe/publish to topics. You probably
> # want to leave this included unless you want to save a very small amount of
> # memory size and CPU time.
> WITH_BRIDGE:=no
> 
> # Comment out to remove persistent database support from the broker. This
> # allows the broker to store retained messages and durable subscriptions to a
> # file periodically and on shutdown. This is usually desirable (and is
> # suggested by the MQTT spec), but it can be disabled if required.
> WITH_PERSISTENCE:=no
> 
> # Comment out to remove memory tracking support from the broker. If disabled,
> # mosquitto won't track heap memory usage nor export '$SYS/broker/heap/current
> # size', but will use slightly less memory and CPU time.
> WITH_MEMORY_TRACKING:=no
> 
> # Compile with database upgrading support? If disabled, mosquitto won't
> # automatically upgrade old database versions.
> # Not currently supported.
> WITH_DB_UPGRADE:=no
> 
> # Comment out to remove publishing of the $SYS topic hierarchy containing
> # information about the broker state.
> WITH_SYS_TREE:=no
> 
> # Build with systemd support. If enabled, mosquitto will notify systemd after
> # initialization. See README in service/systemd/ for more information.
> WITH_SYSTEMD:=no
> 
> # Build with SRV lookup support.
> WITH_SRV:=no
> 
> # Build using libuuid for clientid generation (Linux only - please report if
> # supported on your platform).
> WITH_UUID:=no
> 
> # Build with websockets support on the broker.
> WITH_WEBSOCKETS:=no
> 
> # Use elliptic keys in broker
> WITH_EC:=yes
> 
> # Build man page documentation by default.
> WITH_DOCS:=no
> 
> # Build with client support for SOCK5 proxy.
> WITH_SOCKS:=no
> 
> # Strip executables and shared libraries on install.
> WITH_STRIP:=yes
> 
> # Build static libraries
> WITH_STATIC_LIBRARIES:=yes
> 
> # Build shared libraries
> WITH_SHARED_LIBRARIES:=no
> 
> # Build with async dns lookup support for bridges (temporary). Requires glibc.
> WITH_ADNS:=no
> 
> # Build with epoll support.
> WITH_EPOLL:=no
> 
> # Build with bundled uthash.h
> WITH_BUNDLED_DEPS:=yes

**Comment by davidgurr** [comment]
With "log_type all" on the mosquitto server, I get the following in the server logs:

> 1549636212: New connection from 192.168.0.31 on port 1883.
> 1549636212: New client connected from 192.168.0.31 as mosqpub|30318-yi-hack-v (c1, k60).
> 1549636212: Sending CONNACK to mosqpub|30318-yi-hack-v (0, 0)

So it looks like the broker is sending CONNACK. It's just not getting received.

**Comment by ralight** [comment]
Are you positive that it is build with thread support? `-l` requires it.

**Comment by davidgurr** [comment]
You're right, I'd managed to mangle the Makefile. Thanks!

**Comment by ralight** [comment]
Thanks for confirming :)
