### ISSUE TITLE
mosquitto_pub -l doesn't handle server failures

### ISSUE THREAD

**Issue by dustin** [eclipse/mosquitto#1152]
I've got a shell script that's spitting out a number periodically into `mosquitto_pub -t something -q 2 -l` and have found that any server failures (e.g., restarting the server) is seemingly ignored.  The program continues to run, but never sends data to the MQTT broker again.

I'd prefer one of:

1. reconnect
2. just exit with a failure

**Comment by ralight** [comment]
Work for me with a quick test. I'll do more tests, but for the moment which version are you using and on what platform?

**Comment by dustin** [comment]
> mosquitto_pub version 1.5.6 running on libmosquitto 1.5.6.

> $ cat /etc/debian_version 
> buster/sid

> $ uname -a
> Linux eve 4.19.0-1-amd64 #1 SMP Debian 4.19.12-1 (2018-12-22) x86_64 GNU/Linux

I've got the following script running persistently.  I noticed I had not got any data since around the time I restarted to debug something else last night.  The script and its constituent parts were still running, but no data showed up in mqtt until I restarted it.

```
#!/bin/sh -e

sample() {
    while : 
    do
            echo 'select count(*) from spool' | sqlite3 $HOME/influx.spool
            sleep 60
    done
}

sample | mosquitto_pub --will-topic errors --will-payload 'sj spool reporter discod' \
                       -q 2 -t 'sj/influxer/spool' -l
```

**Comment by ralight** [comment]
I've pushed a change which fixes this, if you want to give it a try it is on the `fixes` branch. Thanks for the report, this will be part of 1.6.3.
