### ISSUE TITLE
typo in docker entrypoint shebang

### ISSUE THREAD

**Issue by nelsonpina** [eclipse/mosquitto#1156]
https://github.com/eclipse/mosquitto/blob/66dfa573946425661626e2f574ef125ab01b01f5/docker/1.5/docker-entrypoint.sh#L1

**Comment by karlp** [comment]
and what is the typo exactly?

**Comment by nelsonpina** [comment]
oops, I suppose it's meant to be the `almquist shell` then..  when I first looked at it it seemed like it had an extra `a` :)
