### ISSUE TITLE
$SYS/broker/time

### ISSUE THREAD

**Issue by nwf** [eclipse/mosquitto#1157]
I'd like to suggest revisiting https://bugs.eclipse.org/bugs/show_bug.cgi?id=491229.

`$SYS/broker/time` would be very convenient to have just as a coarse check for clock drift between clients.  It should, IMHO, be updated along with all the other periodic `$SYS` topics, notably including `$SYS/broker/uptime`, which is very time-like, just with a somewhat arbitrarily chosen epoch.  It's even nominally required by https://github.com/mqtt/mqtt.github.io/wiki/SYS-Topics.

It would be convenient if `$SYS/broker/time` were in POSIX seconds UTC or some other easily parsed format rather than a human-friendly string, but I'll take whatever I can get. :)

Thanks,
--nwf;

**Comment by karlp** [comment]
As then, why are you not just implementing this in your own application layer?  some people want this magically given only once when they subscribe to it, others want it published every X, just do it in your own application space.

**Comment by nwf** [comment]
I guess I'm not opposed to running my own time-publishing daemon, but given that all the functionality already exists in mosquitto's server, it's not clear to me what the benefit of introducing my own topic outside `$SYS` is.  But if there's strong objection, perhaps someone with authority should edit the MQTT wiki link above.

**Comment by chriswue** [comment]
Well, it's listed as optional which leaves it up to the broker implementation whether to provide it or not.

**Comment by nwf** [comment]
Fair 'nough.

**Comment by nwf** [comment]
Though amusingly that changed as of 2 hours ago.  So, I guess someone really did take my request to heart, or there's a really amusing coincidence!

**Comment by ralight** [comment]
Sorry, I still think this is something that should be provided externally. The broker only really publishes information about itself, not the system it is on. The benefit is that everybody wants information in different ways and to support that means extra complexity in the broker that is unnecessary. To do what you want exactly as you want it is only a few lines of Python.
