### ISSUE TITLE
Segfault in Ubuntu 16.04 LTS ,  libc-2.23.so

### ISSUE THREAD

**Issue by DHDSP** [eclipse/mosquitto#1158]
Hi all,

ubuntu 16.04 LTS does every day cleanup routines, this morning after the daily routine mosquitto broker does not start anymore. A manual start of the broker produces a segfault too. 

I tried updating and upgrading, rebooting,  and I reinstalled the package, reinstalled libc6 but nothing changes.

From my Syslog after reinstalling the package:

Feb 12 10:37:25 xxx systemd[1]: Reloading.
Feb 12 10:37:28 xxx systemd[1]: message repeated 2 times: [ Reloading.]
Feb 12 10:37:28 xxx systemd[1]: Reloading.
Feb 12 10:37:29 xxx systemd[1]: Starting LSB: mosquitto MQTT v3.1 message broker...
Feb 12 10:37:29 xxx mosquitto[12894]:  * Starting network daemon: mosquitto
Feb 12 10:37:29 xxx mosquitto[12894]:    ...done.
Feb 12 10:37:29 xxx systemd[1]: Started LSB: mosquitto MQTT v3.1 message broker.
**Feb 12 10:37:29 xxx kernel: [ 3026.835679] mosquitto[12905]: segfault at 7ffea1784fc4 ip 00007f847ad2384e sp 00007ffea176eab8 error 4 in libc-2.23.so[7f847
ac84000+1c0000]**

My Ubuntu version:

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

My installed package version:
Package: mosquitto
Status: install ok installed
Priority: optional
Section: net
Installed-Size: 297
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: foreign
Version: 1.4.8-1ubuntu0.16.04.5
Depends: adduser (>= 3.10), libuuid1 (>= 2.16), lsb-base (>= 4.1+Debian11ubuntu7), libc6 (>= 2.14), libssl1.0.0 (>= 1.0.1), libwebsockets7 (>= 1.6.0), libwrap0 (>= 7.6-4~)
Suggests: apparmor
Conffiles:
 /etc/init.d/mosquitto 7c1c057c3c625deaac042ba97032ec69
 /etc/init/mosquitto.conf 97d9bc16841e4ba66a68ef1ee280fd9f
 /etc/logrotate.d/mosquitto 7f203558c910819d152ee3f033063cff
 /etc/mosquitto/ca_certificates/README c1c6ae67f2def06c6a483be09b49d4de
 /etc/mosquitto/certs/README 4d8a70d4cefab07d4dabc5be1f786c1f
 /etc/mosquitto/conf.d/README b4ac621550824082a735732bfb42b51d
 /etc/mosquitto/mosquitto.conf 379a6d6e30d19bfdedf8099a9f3f8770
Description: MQTT version 3.1/3.1.1 compatible message broker
 This is a message broker that supports version 3.1 and 3.1.1 of the MQTT
 protocol.
 .
 MQTT provides a method of carrying out messaging using a publish/subscribe
 model. It is lightweight, both in terms of bandwidth usage and ease of
 implementation. This makes it particularly useful at the edge of the network
 where a sensor or other simple device may be implemented using an arduino for
 example.
Homepage: http://mosquitto.org/
Original-Maintainer: Roger A. Light <roger@atchoo.org>

**Comment by DHDSP** [comment]
After some more research, I have probably found the cause for the segfault:
I removed the persistence options from my mosquitto.conf and the broker starts regularly.

Now I deleted (modved) the mosquitto.db in /var/lib/mosquitto and re-added the persistence options. 

The broker is now functional again.

Is this a case worth debugging? A corrupt (?) persistence database does cause a segfault.

**Comment by karlp** [comment]
You're running a quite outdated version, I suspect this has just been fixed already.

**Comment by ralight** [comment]
@karlp I think this might be a regression with the security update, but I haven't managed to reproduce it yet.

**Comment by ralight** [comment]
@DHDSP you can track the progress of the fix here (so I'm going to close this):

https://bugs.launchpad.net/ubuntu/+source/mosquitto/+bug/1815695

**Comment by DHDSP** [comment]
Thank you !
