### ISSUE TITLE
ESP8266 clients not able to connect/subscribe since update

### ISSUE THREAD

**Issue by balert** [eclipse/mosquitto#1159]
I'm seeing a lot of errors like the following since the (automated) update of mosquitto to 1.4.8-1ubuntu0.16.04.5 tonight:

1549949350: Client xxxx has exceeded timeout, disconnecting.
1549949350: Socket error on client xxxx, disconnecting.

At least all ESP8266 using the Arduino PubSubClient library seem not able to connect anymore. Any ideas how to debug and solve this? I believe other clients are still able to use mosquitto, but have to check this. Also seems like the problem lies in the clients being not able to subscribe topics.

**Comment by balert** [comment]
is it possible this is caused by all ESP8266 using the same credentials (none) to subscribe to mosquitto? (c.f. https://github.com/eclipse/mosquitto/issues/523#issuecomment-384449673) But why did it work perfectly until todays update?

**Comment by balert** [comment]
This issue can be closed, as I found the cause of the problem not being Mosquitto but a different service, not mosquitto related. (Sorry)

**Comment by ralight** [comment]
Ok, thanks for letting us know.
