### ISSUE TITLE
Segmentation fault on FreeBSD

### ISSUE THREAD

**Issue by antkachenko** [eclipse/mosquitto#1160]
Installed from ports on FreeBSD 11.2, version  1.5.5. During startup saing "Error: Invalid password hash for user" and "mosquitto_passwd -U /usr/local/etc/mosquitto/pwfile" returns "Segmentation fault". Memory dump attached.

Could you please advise what am I doing wrong?

[mosquitto_passwd.zip](https://github.com/eclipse/mosquitto/files/2860583/mosquitto_passwd.zip)

**Comment by ralight** [comment]
It sounds like your password file is corrupt, it should look something like this, could you check:

```
test:$6$hDNQYw+15n9R53vu$GccuIDxsierZFALUUy6DCMEuSwQr4Fj4D3BTC9Ju+jPGtv/r7QulD2oLvDT4i1JRttQdEDKc2D3cfAdIymapxA==
```

**Comment by ralight** [comment]
I'm closing this due to no response. If this is still a problem for you please reopen.
