### ISSUE TITLE
User can't connect if acl_file contains no username block

### ISSUE THREAD

**Issue by quonb** [eclipse/mosquitto#1162]
If _acl_file_ contains only pattern rules or there is no definition for user then `acl__find_acls` function returns `MOSQ_ERR_INVAL`.
https://github.com/eclipse/mosquitto/blob/6b43ba820172a031bfeae51ddaeaf7bb96546f12/src/security_default.c#L645-L647
This causes immediate disconnect despite correct username/password pair
https://github.com/eclipse/mosquitto/blob/6b43ba820172a031bfeae51ddaeaf7bb96546f12/src/handle_connect.c#L614-L615

This regression were caused by https://github.com/eclipse/mosquitto/commit/c40957a7d8f2d866cd919f2d53f4927c785fcef1

**Comment by ralight** [comment]
Thanks for finding this. For information, the description isn't quite right, it only happens if the anonymous ACL list is defined but there are no specific user ACLs. I've pushed a fix to the fixes branch.
