### ISSUE TITLE
ACL issue: not able to connect with username that is not defined in aclfile

### ISSUE THREAD

**Issue by elementzonline** [eclipse/mosquitto#1164]
My ACL file contents look like this

`# This affects access control with no username

topic readwrite /mediatronix/anonymous/#`

`# This affects all clients

topic readwrite /test/#`

`# This only affects clients with usename

user testuser123
topic readwrite /test/#`

`# This affects all clients

pattern readwrite /test/%u/#`

///////////////////////////////////
I am able to connect with username testuser123, which is mentioned in the acl file. But when other usernames are used in client, the following error occurs,

Socket error on client <unknown>, disconnecting.

**The same acl is working fine for mosquitto version 1.4.8, but not working for new version 1.4.15.** 

More info:
_Tested with Ubuntu 18.04 and 1.4.15 - Acl issue as mentioned above
Tested with Ubuntu 16.04 and 1.4.8 - ACL working fine_

**Comment by quonb** [comment]
I think it is the same problem that was described in #1162.

**Comment by elementzonline** [comment]
> I think it is the same problem that was described in #1162.

Exactly. 
Rectified the issue by installing the mosquitto server from the fixes branch. 

For others who experience the same issue use the following commands as a temporary soln

// Use fixes branch from mosquitto repository

git clone https://github.com/eclipse/mosquitto.git
cd mosquitto
git checkout -b origin/fixes
git pull


// Build the source and install
make
sudo make install
