### ISSUE TITLE
SSL Certificate Verify Failed; IP address mismatch. Python 3.7

### ISSUE THREAD

**Issue by chimera786** [eclipse/mosquitto#1166]
Hello!

Here is what I have: A MQTT broker (mosquitto) configured to accept client certificates to authenticate connections. I did so by generating self signed certificates and editing the conf file for mosquito to point towards the certificates. I followed the directions on this page to generate the certs: https://mosquitto.org/man/mosquitto-tls-7.html.  I used a MQTT client called MQTTFX as a quick check where I passed the certificates, port # and my local IP. All worked fine.

Then I figured i'd run this on python to get some automation going. I generated a virtualenv with python 3.7 (windows 7), installed, paho mqtt and wrote a couple scripts to basically connect to the mosquitto broker (running local on my machine---replicating the MQTTFX set up essentially).

Script 1: 
```
import os.path
certificates_path_CA = "some/location/for/CA"
certificates_path_client = "some/other/location/for/board_certificates/client"
ca_certificate = os.path.join(certificates_path_CA, "ca1.crt")
client_certificate = os.path.join(certificates_path_client, "client.crt")
client_key = os.path.join(certificates_path_client, "client.key")

mqtt_server_host = "192.168.1.99"
mqtt_server_port = 88xx
mqtt_keepalive = 60
```

Script 2:
```
from config import *
import paho.mqtt.client as mqtt

def on_connect(client, userdata, flags, rc):
    print("Result from connect: {}".format(mqtt.connack_string(rc)))
# Subscribe to the vehicles/vehiclepi01/tests topic filter
    client.subscribe("vehicles/vehiclepi01/tests", qos=2)
def on_subscribe(client, userdata, mid, granted_qos):
    print("I've subscribed with QoS: {}".format(granted_qos[0]))
def on_message(client, userdata, msg):
    print("Message received. Topic: {}. Payload: {}".format(msg.topic,str(msg.payload)))

if __name__ == "__main__":
    client = mqtt.Client(protocol=mqtt.MQTTv311)
    client.on_connect = on_connect
    client.on_subscribe = on_subscribe
    client.on_message = on_message
    client.tls_set(ca_certs=ca_certificate, certfile = client_certificate, keyfile = client_key)
    #client.tls_insecure_set(1)
    client.connect(host=mqtt_server_host, port=mqtt_server_port, keepalive=mqtt_keepalive)
client.loop_forever()
```

Here is the error:

> self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '192.168.1.99'. (_ssl.c:1056)

Now, I read up on this link (https://stackoverflow.com/questions/52855924/problems-using-paho-mqtt-client-with-python-3-7) and according to the OP, the error is caused by IP addresses in CN name and it was apparently deprecated a long time ago but earlier python versions up to 3.6 allowed it. Python 3.7 however, doesn't allow it. 

What is this error? I don't fully understand it. Also, if the IP is the main issue due to the deprecated reason, how do I go around it?

Note: I tried this client certificate connection on test.mosquitto.org and it worked with my python code. I accomplished this by getting the CA from test.mosquitto.org, genereated a csr request and had the ca sign it (test.mosquitto.org/ssl). I placed those in the appropriate directories, edited my code and it worked fine.

Thanks for looking!

**Comment by ralight** [comment]
I'm not quite sure what the question is here, it sounds like the question you linked to solves the problem, and it's seems like it's a Python problem rather than with Mosquitto anyway. Could you clarify further?

**Comment by chimera786** [comment]
I suppose it is a python error. Have you ever experienced this error? using python 3.7 to connect to a mosquitto broker as a client using authentication?

**Comment by ralight** [comment]
Not exactly like that, no. I would suggest trying without the client certificates first to isolate the problem, and/or experimenting with `openssl s_client` with your certificates.

**Comment by ralight** [comment]
I don't believe this is a problem with Mosquitto, so I'm closing this issue. If you disagree, please reopen and explain away :)
