### ISSUE TITLE
MQTTv5: does not update Subcription Identifiers on re-SUBSCRIBE

### ISSUE THREAD

**Issue by ckrey** [eclipse/mosquitto#1169]
- Client SUBSCRIBEs to topic with Subscription Identifier "1"

- Client (re)SUBSCRIBEs to same topic with Subscription Identifier "2" OR
- Client (re)SUBSCRIBEs to same topic without Subscription Identifier

- a message is PUBLISHed to the topic

result:
- Client receives PUBLISH message with Subscription Identifier "1"

expected result (3.8.2.1.2 Subscription Identifiers):
- Client receives PUBLISH message with Subscription Identifier "2" OR
- Client receives PUBLISH message without Subscription Identifier

**Comment by ralight** [comment]
This should be fixed now, could you please confirm it works your end?

**Comment by ckrey** [comment]
Thanks Roger, works as expected now
