### ISSUE TITLE
mosquitto_loop_stop() hangs on windows

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto#117]
migrated from Bugzilla [#452918](https://bugs.eclipse.org/bugs/show_bug.cgi?id=452918)
status NEW severity _normal_ in component _Mosquitto client library_ for _---_
Reported in version _unspecified_ on platform _PC_
Assigned to: Roger Light

On 2014-11-23 16:29:33 -0500, Roger Light wrote:

> (imported from launchpad)
> 1. On many unix-like systems, system call such as read, write is a thread cancellation point specified by posix. But on windows, pthread_win32 implementation, socket family system call is not thread cancellation point, that means if i enable the thread support in mosquitto, there wouldn't be any thread cacellation point in mosquitto_loop_forever. So if calling mosquitto_loop_stop(mosq, true), then the pthread_join() which is called after pthread_cancel() will be blocked as the mosquitto_loop_forever() has not any cancellation point.
> 
> a patch to lib/mosquitto.c below to setup a cancellation point manually:
> # 
> 
> @@ -868,6 +868,9 @@ int mosquitto_loop_forever(struct mosquitto *mosq, int timeout, int max_packets)
> 
>   while(run){
>    do{
> +#ifdef WIN32
> - pthread_testcancel();
>   +#endif
>   rc = mosquitto_loop(mosq, timeout, max_packets);
>   if (reconnects !=0 && rc == MOSQ_ERR_SUCCESS){
>    reconnects = 0;
> # 
> 1. Sleep() call on windows is not a cancellation point, too. And it is used in mosquitto_loop_forever() to do backoff in reconnecting phase, it will also prevent mosquitto_loop_stop() from returning immediately. pthread_cond_timewait() may be a better alternative.

**Comment by SiggyBar** [comment]
Excellent, thank you for the fix 👍

**Comment by ralight** [comment]
No problem. I just didn't have the time to be happy with your other patch, but I've not forgotten it.
