### ISSUE TITLE
Question: A file format for archiving MQTT messages?

### ISSUE THREAD

**Issue by nigels-com** [eclipse/mosquitto#1170]
I understand that MQTT is formulated in terms of the "here and now" transport of information.
Short-term buffering and queuing, or long-term local archiving seems beyond the scope of MQTT.

I'm looking around for a toolset for recording or logging MQTT data streams in a manner that can be re-played or queried in an ad-hoc manner.  Such as "all messages from December 12th 2018" or "replay from 3:00pm yesterday in real-time".

It seems to me that file or S3 storage ought to suffice for a lightweight sort of solution that ought to scale to small projects or household-wide data streams.  And it also seems like libmosquitto could be used as a basis for an MQTT bridge implementation.  Otherwise the archiving could be bolted directly into mosquitto as an optional auditing mode.

I can happily wrangle some JSON and Python ad-hoc to implement this sort of use-case, but I do wonder if there is something off the shelf that would be more turn-key.

Apologies if this is too off-topic, you're welcome to delete/close as appropriate.

**Comment by ralight** [comment]
You might get a better response elsewhere, but for my money what you're describing sounds like a time series database would do the job. Influxdb is a time series database with mqtt support, it might be worth a shot.

**Comment by nigels-com** [comment]
Thanks for the mention of Influxdb.  What I was thinking was something lightweight enough to deploy on an existing 24/7 NAS, rather than a pay-as-you-go cloud instance.

**Comment by ralight** [comment]
I guess it depends on the capability of your nas - a colleague runs his own instance of influx on a very modest vps.

**Comment by nigels-com** [comment]
Browsing the Influx-sphere lead me to Fluent-bit, which looks like one way of archiving and/or forwarding streams of MTQQ in a lightweight, flexible and ad-hoc manner.  I'll see what sort of throughput I can squeeze from a Raspberry Pi / USB 2.0 envelope.

https://github.com/fluent/fluent-bit/blob/master/README.md

**Comment by ralight** [comment]
Nice, I haven't seen that before.

**Comment by nigels-com** [comment]
One notable constraint of Fluent-bit is that it's text/JSON-centric, eventhough it uses msgpack internally.
The consequence is that Fluent-bit rejects non-JSON payload, but it's not clear if that's a design decision or an implementation limitation.  One aspect of MQTT I find appealing is to support binary payloads such as msgpack, gzip, tar, or encryption but that limits the filtering etc that Fluent-bit provides.

**Comment by ralight** [comment]
I don't think this needs to stay open any more does it? I'm doing a clean of old issues where possible. If you have more to say on this, please reopen and do so.
