### ISSUE TITLE
IoT Subscriber not receiving CONACK and messages published

### ISSUE THREAD

**Issue by dhruv479** [eclipse/mosquitto#1176]

**Comment by ralight** [comment]
Without any details it's not possible to help you. My suggestion is to try what you are doing but with mosquitto_sub instead. If that works, then the problem lies with your client not with anything mosquitto.

**Comment by dhruv479** [comment]
Thanks for the help but the issue is already resolved. I was using Character Data Type for buffer instead of Unsigned Character due to which the compiler behaves differently.
