### ISSUE TITLE
mosquitto  failed to make connection to ubidot!

### ISSUE THREAD

**Issue by methaqali** [eclipse/mosquitto#1178]
Hi,
I install mosquitto 1.5.7 on win 7 and make subscribe and publish successfully in local host but mosquitto  failed to make connection to ubidot  the publish (mosquitto_pub -h "things.api.ubidots.com" -t "/v1.6/devices/plc" -u "9NUybJdaPXDnuujb4DFcZDXsySn5dS " -p 1883 -q 1 -m '{"water level": 17}' ) give the result 
“Unable to connect (Lookup error.).” and when tring “mosquitto -c configfile” the result is
” Error: Unable to open config file
Error found at configfile:0.
Error: Unable to open configuration file”
I need to connect MQTT to opc server for connect my plc to IoT.
When make mosquitto -v   I get this messges:
C:\Program Files\mosquitto>mosquitto -v
1550907715: mosquitto version 1.5.7 starting
1550907715: Using default config.
1550907715: Opening ipv6 listen socket on port 1883.
1550907715: Error: Only one usage of each socket address (protocol/network address/port) is normally permitted.
I need help.

**Comment by ralight** [comment]
I don't have access to Windows 7 so I can't comment on that specifically. It sounds like there is a network related problem of some sort. The mosquitto_pub error (Lookup error) would normally suggest that the DNS entry isn't found or DNS lookups are failing, which isn't a problem with Mosquitto itself. Having said that, your error for `mosquitto -v` is a bit baffling which could indicate a wider problem. Is that message consistent every time you try to start mosquitto?

`mosquitto -c configfile` - does configfile exist? I'll see about improving that error message.

**Comment by methaqali** [comment]
Thank you ralight, for replay.
The problem is solved. the error is in host domain name the new correct one is 
things.ubidots.com.

**Comment by ralight** [comment]
Great, glad you got it sorted.
