### ISSUE TITLE
Mosquitto install fails (version 1.5.7) Windows 10 pro  64bit OS version 1809 build 17763.316

### ISSUE THREAD

**Issue by heidnerd** [eclipse/mosquitto#1179]
Just download Misquitto 1.5.7 installer for 64 bit windows.  it fails wtih:

"The code execution cannot proceed because VCRUNTIME140.dll was not found.  Reinstalling the program may fix this problem>"

Reinstalling it doesn't fix the problem.

It looks like the installer has some preconditions for windows missing,  Some kind of documentation that perhaps suggests installing the Visual C runtime.

**Comment by archerian** [comment]
Try intalling mosquitto after installing the VC 2015 or 2017 runtime.

**Comment by heidnerd** [comment]
Thanks,  I was hoping you'd say that VC 2017 is okay.  I'd rather not
install based on an already 4 year old release of VC.  Mosquitto might
break later if MS then auto updates.   I'm trying to replicate a setup
that I expect some college students to be repeating later this spring.

Dennis Heidner

(206) 817-1164 

On 2019-02-27 18:17, Arun Kirthi Cherian wrote:

> Try intalling mosquitto after installing the VC 2015 or 2017 runtime. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/eclipse/mosquitto/issues/1179#issuecomment-468109391
[2]

**Comment by ralight** [comment]
@heidnerd The Windows binaries are compiled with Visual Studio 2017 Community, so the 2017 runtimes should be what you need.

**Comment by ralight** [comment]
Closing as solved, and there have been more installer improvements since the last comment anyway.
