### ISSUE TITLE
TLS connection with websocket impossible

### ISSUE THREAD

**Issue by sk4ry** [eclipse/mosquitto#1181]
Hi !

I'm trying to update our mosquitto to 1.5.6 (last version available on docker hub) to permit to get the corrected issue #1143 .
However it's impossible to connect using cert over websocket.
I have 3 listeners over websocker configured inside my broker configured like this :
```
retry_interval 20
sys_interval 10
user mosquitto
max_inflight_messages 40
max_queued_messages 200
queue_qos0_messages false
message_size_limit 0
allow_zero_length_clientid true
persistent_client_expiration 3m
allow_duplicate_messages false
connection_messages true
log_timestamp true
log_dest stderr
log_type all
allow_zero_length_clientid true
allow_anonymous true
websockets_log_level 65535

# acls
acl_file /mosquitto/config/mosquitto.acl
password_file /mosquitto/config/mosquitto.passwd

## Listeners

listener 1883

# websockets
listener 9883
protocol websockets

# websockets
listener 9443
protocol websockets

# TLS for 9443
cafile /mosquitto/config/ca.pem
certfile /mosquitto/config/server.pem
keyfile /mosquitto/config/server-key.pem
require_certificate true
tls_version tlsv1.2
use_identity_as_username true
```
Using this code (mqtt.js is required) reproduced the issue :
```javascript
let mqtt = require('mqtt')
let fs = require('fs')

let client = mqtt.connect('wss://10.0.0.1:9443', {
    protocol: 'wss',
    ca: [ fs.readFileSync('./client_cert/ca.pem') ],
        cert: fs.readFileSync('./client_cert/client.pem'),
        key: fs.readFileSync('./client_cert/client-key.pem'),
    rejectUnauthorized: false,
    checkServerIdentity: () => { return null; }
})

client.on('connect', () => console.log('connected'))

client.on('close', () => console.log('close event'))

client.on('reconnect', () => console.log('reconnect event'))
```
The client certificate contains a CN to valid the use_identity_as_username configuration.
I'm getting the following error in logs on client connection :
```
1551282108: Error in epoll disconnecting websockets: No such file or directory
1551282108: Socket error on client <unknown>, disconnecting.
```

Is this problem come from my configuration, which is valid with the previous version ?

Thx in advance for you help.

**Comment by ralight** [comment]
I don't think this is your configuration. In previous versions, if a client that connected with a username  didn't have an ACL explicitly set for them, they were given the ACL of the anonymous users, which was incorrect. What happens now is that if a client with a username connects and they do not have an ACL assigned to them, meaning that they would be unable to send or receive anything, then they are disconnected. I'll see about adding some extra logging to make it clearer what is happening.

For your case - does the CN of your certificate have an entry in your acl file?

**Comment by sk4ry** [comment]
No, all my wss client take their right using a pattern configuration like that :
```
pattern read read/topic/%u/#
pattern readwrite write/topic/%u/#
```

**Comment by ralight** [comment]
Yes, you're right, I was forgetting about that case, that was the whole reason that disconnecting the clients is the wrong thing to do. This is fixed in the `fixes` branch like I mentioned and I'm hoping to make a release today.

**Comment by sk4ry** [comment]
Ok, i see the problem.
Thank you for your reactivity !

Another question is how the releases and their docker version are managed ? I see that the tag 1.5.7 is already done but there is no tag 1.5.7 on the docker hub.

**Comment by ralight** [comment]
That's down to me. 1.5.6 and 1.5.7 were a bit rushed to get in to the Ubuntu freeze, I thought I'd just let the dust settle to make sure nothing else came up. I'll be updating it for the 1.5.8 release.
