### ISSUE TITLE
[MQTT5] Please provide a Windows installer for MQTT5 test1 release

### ISSUE THREAD

**Issue by mpe85** [eclipse/mosquitto#1185]
It would be very nice if you could provide binaries for windows of the MQTT5 test1 release.
I'm interested in MQTT5 but I don't have much experience in compiling C projects.
Thanks! :thumbsup:

**Comment by ralight** [comment]
I'll see what I can do.

**Comment by ralight** [comment]
Here you go: https://mosquitto.org/files/source/test/

**Comment by mpe85** [comment]
Great, thank you very much!
