### ISSUE TITLE
login access

### ISSUE THREAD

**Issue by danielstock** [eclipse/mosquitto#1186]
if there are thousands of devices in the system, it would not be convenient to create one login account for each of them.
so i'd divide those devices in groups, all the devices in the same group would share one same login account.
then, how can i deny one particular device from login later? it's not possible to change the account password, otherwise all the devices in the same group would not be able to login.

**Comment by ralight** [comment]
I suppose you might be able to come up with an authentication plugin to help you, but honestly shared passwords just don't seem like a great idea to me.

**Comment by danielstock** [comment]
@ralight    thanks.  is there any specification for the authentication plugin ?
should the plugin be developed in dll format for windows platform?

**Comment by ralight** [comment]
The plugin details are contained in https://github.com/eclipse/mosquitto/blob/master/src/mosquitto_plugin.h , you can see a reasonably comprehensive example at https://github.com/jpmens/mosquitto-auth-plug

There are also functions you can make use of in https://github.com/eclipse/mosquitto/blob/master/src/mosquitto_broker.h

Yes, it should be a dll on windows.
