### ISSUE TITLE
Not able to find mosquitto 1.5.7-0mosquitto1~xenial1 in ppa:mosquitto-dev/mosquitto-ppa 

### ISSUE THREAD

**Issue by shubhamcoc** [eclipse/mosquitto#1187]
after the release of latest version 1.5.8-0mosquitto1~xenial1 
Not able to install mosquitto 1.5.7-0mosquitto1~xenail1 using apt-get install mosquitto=mosquitto 1.5.7-0mosquitto1~xenail1 command.
how to install the previous version using apt-get command?

**Comment by ralight** [comment]
I think the only option is to download the package manually and install with dpkg

https://launchpad.net/~mosquitto-dev/+archive/ubuntu/mosquitto-ppa/+files/mosquitto_1.5.7-0mosquitto1~xenial1_amd64.deb
