### ISSUE TITLE
Why I can't find the source-code of function mosquitto_userdata?

### ISSUE THREAD

**Issue by Hapoa** [eclipse/mosquitto#1191]
mosquitto version: 1.5.1 , 1.5.8

When I use the function 'mosquitto_userdata', it came across an error: undefined reference of 'mosquitto_userdata'.

So, I opened the source codes of version 1.5.8, and searched the keyword 'mosquitto_userdata', I only finded the  
declaration but no definition.

Is forget? Or other reasons?

**Comment by ralight** [comment]
You're quite right, it must have got missed off the commit. Obviously nobody else found a need for it until now. I've just pushed the change with it in. Thanks for the report!

**Comment by Hapoa** [comment]
:smile::smile::smile:
