### ISSUE TITLE
Unable to install mosquitto in Raspberry Pi

### ISSUE THREAD

**Issue by sureshp1994** [eclipse/mosquitto#1192]
sudo apt-get install mosquitto
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mosquitto : Depends: libssl1.0.0 (>= 1.0.0) but it is not installable
             Depends: libwebsockets3 (>= 1.2) but it is not installable
E: Unable to correct problems, you have held broken packages.

This issue is in the Raspbian Stretch OS

**Comment by ralight** [comment]
Based on those dependencies, it seems like you have the jessie repo enabled instead of stretch.

Could you check `/etc/apt/sources.list.d/` to make sure it is correct?

**Comment by ralight** [comment]
I'm closing this due to no more details, if this is still a problem please reopen and explain further.
