### ISSUE TITLE
Unable to install mosquitto in Debian Stretch i386 from repo.mosquitto.org

### ISSUE THREAD

**Issue by reibuehl** [eclipse/mosquitto#1195]
I run mosquitto since more than a year now and have installed it on a Debian i386 system from repo.mosquitto.org. The version 1.5.8-0mosquitto1 that I got through an apt-get upgrade on March 7 2019, mosquitto however fails to install properly. I removed the package manually and tried to reinstall it but it still fails with the following error message:

hostname:~# LANG=en_US.UTF-8 apt-get install mosquitto
Reading package lists... Done
Building dependency tree
Reading state information... Done
mosquitto is already the newest version (1.5.8-0mosquitto1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up mosquitto (1.5.8-0mosquitto1) ...
Job for mosquitto.service failed because a timeout was exceeded.
See "systemctl status mosquitto.service" and "journalctl -xe" for details.
invoke-rc.d: initscript mosquitto, action "restart" failed.
● mosquitto.service - Mosquitto MQTT v3.1/v3.1.1 Broker
   Loaded: loaded (/lib/systemd/system/mosquitto.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/mosquitto.service.d
           └─restart.conf
   Active: activating (auto-restart) (Result: timeout) since Sat 2019-03-09 16:46:56 CET; 11ms ago
     Docs: man:mosquitto.conf(5)
           man:mosquitto(8)
  Process: 9983 ExecStart=/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf (code=exited, status=0/SUCCESS)

Mar 09 16:46:56 hostname systemd[1]: mosquitto.service: Unit entered failed state.
Mar 09 16:46:56 hostname systemd[1]: mosquitto.service: Failed with result 'timeout'.
dpkg: error processing package mosquitto (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 mosquitto
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by reibuehl** [comment]
Installing the older version 1.5.6-0mosquitto1 with apt-get install mosquitto=1.5.6-0mosquitto1 works, so it seems to be related to 1.5.8-0mosquitto1.

**Comment by ralight** [comment]
Could you test out what happens if you install the package and try to run mosquitto manually with `/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf`?

**Comment by reibuehl** [comment]
If I start it manually, it seems to run fine. No unexpected errors in the mosquitto.log. 

 /etc/systemd/system/mosquitto.service is empty after the upgrade. So it seems to be a issue with the creation of that file.

**Comment by ralight** [comment]
Thanks, that's a great help.

**Comment by ralight** [comment]
Sorry this has been neglected. I've been looking at packaging today trying to figure this out, and the package doesn't actually install anything to `/etc/systemd/system/mosquitto.service`. Its systemd unit file is at `/lib/systemd/system/mosquitto.service`. Running `dpkg -S /etc/systemd/system/mosquitto.service` should tell you which package installed the file, or else that none did.

**Comment by reibuehl** [comment]
At least the previous version of the package seems to have installed something in /etc/systemd/system/mosquitto.service since this file exists and has content if I revert back to 1.5.6-0mosquitto1 via apt.

**Comment by ralight** [comment]
How very peculiar! There are no systemd files in the 1.5.6 i386 package at all. I wonder if this is an automatic unit file being generated to act as a helper for sysv only packages.

**Comment by reibuehl** [comment]
I will check with dpkg -S what provides that file next week when I have access to the system again.

**Comment by reibuehl** [comment]
I now checked the situation when 1.5.6-0mosquitto1 is installed: I do not see a /etc/systemd/system/mosquitto.service file there either. I have a /etc/systemd/system/mosquitto.service.d/restart.conf but that is not part of any dpkg package according to dpkg -S, so it might have been auto-generated somehow.

**Comment by ralight** [comment]
Does that mean this issue can be closed?

**Comment by reibuehl** [comment]
Yes, it seems that removing /etc/systemd/system/mosquitto.service.d/restart.conf before installing the new package solves the issue.
