### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by mauriziogreci** [eclipse/mosquitto#1196]
Hello,
working on tags 1.5.5 I'm receiving these warnings.
This issue has been solved in the most recent tags?

lib/handle_pubrel.c:39:41: warning: unused parameter ‘db’ [-Wunused-parameter]
lib/helpers.c:41:63: warning: unused parameter ‘rc’ [-Wunused-parameter]
lib/messages_mosq.c:369:52: warning: unused parameter ‘mosq’ [-Wunused-parameter]
lib/messages_mosq.c:369:71: warning: unused parameter ‘message_retry’ [-Wunused-parameter]
lib/net_mosq.c:313:40: warning: unused parameter ‘mosq’ [-Wunused-parameter]
lib/net_mosq.c:609:49: warning: unused parameter ‘mosq’ [-Wunused-parameter]
lib/net_mosq.c:609:67: warning: unused parameter ‘host’ [-Wunused-parameter]
lib/net_mosq.c:609:82: warning: unused parameter ‘port’ [-Wunused-parameter]
lib/net_mosq.c:609:100: warning: unused parameter ‘bind_address’ [-Wunused-parameter]
lib/net_mosq.c:609:119: warning: unused parameter ‘blocking’ [-Wunused-parameter]
lib/options.c:90:41: warning: unused parameter ‘mosq’ [-Wunused-parameter]
lib/options.c:90:59: warning: unused parameter ‘cafile’ [-Wunused-parameter]
lib/options.c:90:79: warning: unused parameter ‘capath’ [-Wunused-parameter]
lib/options.c:90:99: warning: unused parameter ‘certfile’ [-Wunused-parameter]
lib/options.c:90:121: warning: unused parameter ‘keyfile’ [-Wunused-parameter]
lib/options.c:90:136: warning: unused parameter ‘pw_callback’ [-Wunused-parameter]
lib/options.c:176:46: warning: unused parameter ‘mosq’ [-Wunused-parameter]
lib/options.c:176:56: warning: unused parameter ‘cert_reqs’ [-Wunused-parameter]
lib/options.c:176:79: warning: unused parameter ‘tls_version’ [-Wunused-parameter]
lib/options.c:176:104: warning: unused parameter ‘ciphers’ [-Wunused-parameter]
lib/options.c:212:50: warning: unused parameter ‘mosq’ [-Wunused-parameter]
lib/options.c:212:61: warning: unused parameter ‘value’ [-Wunused-parameter]
lib/options.c:224:45: warning: unused parameter ‘mosq’ [-Wunused-parameter]
lib/options.c:224:63: warning: unused parameter ‘psk’ [-Wunused-parameter]
lib/options.c:224:80: warning: unused parameter ‘identity’ [-Wunused-parameter]
lib/options.c:224:102: warning: unused parameter ‘ciphers’ [-Wunused-parameter]
lib/socks_mosq.c:60:44: warning: unused parameter ‘mosq’ [-Wunused-parameter]
lib/socks_mosq.c:60:62: warning: unused parameter ‘host’ [-Wunused-parameter]
lib/socks_mosq.c:60:72: warning: unused parameter ‘port’ [-Wunused-parameter]
lib/socks_mosq.c:60:90: warning: unused parameter ‘username’ [-Wunused-parameter]
lib/socks_mosq.c:60:112: warning: unused parameter ‘password’ [-Wunused-parameter]
lib/srv_mosq.c:57:45: warning: unused parameter ‘mosq’ [-Wunused-parameter]
lib/srv_mosq.c:57:63: warning: unused parameter ‘host’ [-Wunused-parameter]
lib/srv_mosq.c:57:73: warning: unused parameter ‘keepalive’ [-Wunused-parameter]
lib/srv_mosq.c:57:96: warning: unused parameter ‘bind_address’ [-Wunused-parameter]
lib/util_mosq.c:166:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:212:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:214:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:218:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:274:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:274:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:276:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:278:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:288:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:288:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:291:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:291:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:306:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:310:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:313:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:313:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:322:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:331:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:332:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:345:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
lib/util_mosq.c:345:62: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

**Comment by ralight** [comment]
I've fixed the signed/unsigned warnings and unused parameter warnings, thanks for the report.

**Comment by mauriziogreci** [comment]
Sorry for the question. The fixing is on the master and will in the next tag?

**Comment by ralight** [comment]
It's on the `develop` branch and will be in the 1.6 release. They are pretty trivial warnings though, I wouldn't lose sleep over them.
