### ISSUE TITLE
Mosquitto 1.5.8 spontaneous ghost restart and terminating

### ISSUE THREAD

**Issue by arzaman** [eclipse/mosquitto#1206]
Hi 
I have a really strange behavior of my Mosquitto 1.5.8 istance installed on ubunt AWS EC2 server

It seems that every night at same time the broker make an attempt to start and than terminate due to a conflict on address already in use 

1553143503: mosquitto version 1.5.8 starting
1553143503: Config loaded from /etc/mosquitto/mosquitto.conf.
1553143503: Opening ipv4 listen socket on port 1883.
1553143503: Error: Address already in use

Notice that

- before restart NO client connected, all clean, no errors in the log
- I have disabled perdiodic in memory DB dump to disk (persistence = false)
- there is no task in crontab

this is my conf file

> allow_anonymous false
> password_file /etc/mosquitto/passwordfile
> 
> pid_file /var/run/mosquitto.pid
> 
> persistence false
> persistence_location /var/lib/mosquitto/
> 
> log_dest file /var/log/mosquitto/mosquitto.log
> 
> include_dir /etc/mosquitto/conf.d
> 
> listener 1883
> listener 1884
> listener 9001
> protocol websockets
> listener 8083
> protocol websockets

any idea why this happens periodically and systematically ??

**Comment by karlp** [comment]
You may have some log rotation service restarting things?

**Comment by arzaman** [comment]
> You may have some log rotation service restarting things?

yes is something periodic and systematic...I was suspecting in memory DB dump to file but I disable
How can I check log rotation ? Why restart create anyway a conflict ??

**Comment by arzaman** [comment]
I see now

/etc/logrotate.d/mosquitto  log rotate script

/var/log/mosquitto/mosquitto.log {
        rotate 7
        daily
        compress
        size 100k
        nocreate
        missingok
        postrotate
                /usr/bin/killall -HUP mosquitto
        endscript
}


I see a post rotate kill.... so should be this that generate the conflict..

**Comment by arzaman** [comment]
Still not sure what happens every day

this is my crontab...does it points to logrotate mosquitto script ?

17 *    * * *   root    cd / && run-parts --report /etc/cron.hourly
25 6    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6    * * 7   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6    1 * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
#

maybe cron.daily point to logrotate that point to mosquitto script ?

more over if I execute manually the reload command /usr/bin/killall -HUP mosquitto_ I don't see any disconnection with -HUP command

**Comment by ralight** [comment]
`kill -HUP` should just reload the config file, not restart the broker (as you've seen when doing it manually).

Are there any scripts in /etc/cron.*/ that could be causing the problem? Or maybe take a look at your cron logs if you can, to see what ran at the same time the restart happened.

**Comment by ggggh** [comment]
I have a similar issue.  One of my mosquitto clients keeps disconnecting at 6:25AM most days, and can't seem to connect back.  There's certainly an issue with the code on that client, which I need to figure out, but to me this means that my broker is restarting at 6:25.  Probably my client tries to publish right at that time, can't, and goes into a loop...so I need to fix that on the client, but would like to figure out what's happening on my broker at 6:25 for it not to accept messages for a bit.  Is it purely a conf file reload?

**Comment by ralight** [comment]
@ggggh it's your system, I don't know what happens at 6.25 :) Maybe check your system logs to see what happened then.

How did you install the broker?

**Comment by ggggh** [comment]
Ahh, sorry :)  I was basing my question on the prior messages on the thread, where we can see cron.daily runs at 6:25.  I guess that's sort of standard (at least on Raspbian).  cron.daily calls logrotate, and it does that "/usr/bin/killall -HUP mosquitto"

I notice this as output of that job:
```
/etc/cron.daily/logrotate:
error: Compressing program wrote following message to stderr when compressing log /var/log/mosquitto/mosquitto.log.1:
gzip: stdin: file size changed while zipping
```

**Comment by ralight** [comment]
The logrotate error should be fixed by `delaycompress` to `/etc/logrotate.d/mosquitto` after the `compress` line. It shouldn't make any difference to the broker.

**Comment by ggggh** [comment]
Hasn't happened again after I removed mosquitto from logrotate, so I guess the `killall -HUP` was creating a situation where my client couldn't reach it for an instant and getting messed up.   Just not sure whether that `-HUP ` for mosquitto is meant to create a short interval of no-service.

**Comment by arzaman** [comment]
back again on this issue that drives me crazy !!
log rotation has been disabled but for an unknown reason mosquitto process stop almost randomly , the mosquitto log doesn't help so much and I don't know what to look further
notice that this happens mainly on my mosquito test instance deployed on AMAZON EC2 with Ubuntu 16

hope someone has any idea...

log berfore crash

```
`1566967503: Opening websockets listen socket on port 8083.
1566975980: New connection from 122.228.19.80 on port 1883.
1566975980: Socket error on client <unknown>, disconnecting.
1567024251: New connection from 198.108.66.80 on port 1883.
1567053903: mosquitto version 1.6.3 starting
1567053903: Config loaded from /etc/mosquitto/mosquitto.conf.
1567053903: Opening ipv4 listen socket on port 1883.
1567053903: Error: Address already in use
1567024251: Socket error on client <unknown>, disconnecting.
1567053903: mosquitto version 1.6.3 terminating`

```

**Comment by ralight** [comment]
Do you know for certain that it is crashing? The log looks to me like the old instance is still running and a new one starts up, hence that's why the socket is still open.

**Comment by ralight** [comment]
Closing this issue because it doesn't seem to be a problem any more. If you disagree, please reopen and add more information.
