### ISSUE TITLE
Segmentation Fault in mosquitto_passwd if passwd file is corrupt

### ISSUE THREAD

**Issue by srasku-ge** [eclipse/mosquitto#1207]
Tested with 1.5.3 and 1.5.8.

The following command results in a segmentation fault with the attached file.
```
# mosquitto_passwd -D /data/passwd app_srasku_egd
Segmentation fault (core dumped)
```
[passwd.txt](https://github.com/eclipse/mosquitto/files/2993503/passwd.txt)

**Comment by ralight** [comment]
Thanks very much! I've just pushed a change that fixes this.
