### ISSUE TITLE
Issue with MQTT publish / ESP32

### ISSUE THREAD

**Issue by pfeno** [eclipse/mosquitto#1210]
Hi,
Seem to have same issue @sislakd in https://github.com/eclipse/mosquitto/issues/1198#issuecomment-473407385_

I have following line in mosquitto.log : 

> 1553609007: New connection from 10.228.5.126 on port 1883.
> 1553609007: New client connected from 10.228.5.126 as arduinoClient (c1, k15).
> 1553609007: Client arduinoClient disconnected.
> 1553609007: New connection from 10.228.5.126 on port 1883.
> 1553609007: New client connected from 10.228.5.126 as arduinoClient (c1, k15).
> 1553609007: Client arduinoClient disconnected.
> 1553609007: New connection from 10.228.5.126 on port 1883.
> 1553609007: New client connected from 10.228.5.126 as arduinoClient (c1, k15).
> 1553609007: Client arduinoClient disconnected.
 
My mosquitto.conf was very simple :

> pid_file /var/run/mosquitto.pid
> log_dest file /var/log/mosquitto/mosquitto.log
> allow_anonymous true
> listener 1883

the sketch is very simple : 
```
#include <SPI.h>
#include <WiFi.h>
#include <PubSubClient.h>

IPAddress server(10, 228, 5, 91);

void callback(char* topic, byte* message, unsigned int length) {
  // handle message arrived
  Serial.print("Message arrived on topic: ");
  Serial.print(topic);
  Serial.print(". Message: ");
  String messageTemp;

  for (int i = 0; i < length; i++) {
    Serial.print((char)message[i]);
    messageTemp += (char)message[i];
  }
  Serial.println();
}

WiFiClient ethClient;
PubSubClient client(ethClient);

long lastReconnectAttempt = 0;

boolean reconnect() {
  if (client.connect("arduinoClient")) {
    client.publish("outTopic", "hello world");
    client.subscribe("inTopic");
  }
  return client.connected();
}

void setup() {
  Serial.begin(9600);

  WiFi.begin("...", "...");
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.println("WiFi connected");
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());

  client.setServer(server, 1883);
  client.setCallback(callback);

  delay(1500);
  lastReconnectAttempt = 0;
}

void loop() {
  if (!client.connected()) {
    long now = millis();
    if (now - lastReconnectAttempt > 50000) {
      lastReconnectAttempt = now;
      // Attempt to reconnect
      if (reconnect()) {
        lastReconnectAttempt = 0;
      }
    }
  } else {
    client.loop();
  }
}
```

My question is why do I have a disconnect right after the connection?

**Comment by sislakd** [comment]
My issue has to be related to some change in authentication of newer Mosquitto version because it is working with PubSubClient from ESP8266 if I allow anonymous connections and remove acls in Mosquitto.

**Comment by ralight** [comment]
@sislakd Is there any chance you could share a tcpdump file (no TLS)? We can do that privately if you would prefer.

**Comment by pfeno** [comment]
I install mosquitto on my windows laptop and check if I have the same issue  :-(

**Comment by sislakd** [comment]
@ralight  When I've tried to capture new tcpdump with the latest version (mosquitto_1.5.8-0mosquitto1_armhf), I found that PubSubClient connection from ESP8266 is working well again. The issue was observed on some previous version for which I haven't kept pcap recording. As it is already working, there is no more issues from my side.

**Comment by ralight** [comment]
@sislakd Thanks for checking and replying.

@pfeno Let me know if you find anything else out.

**Comment by KurabiyeCanavari** [comment]
@pfeno Is your broker located in Raspberry Pi, if so,  I had the same issue with ESP_IDF with older versions of MQTT. I switched to 1.5.6, then it was never disconnected but had a different issue: #1208

**Comment by sislakd** [comment]
@pfeno Add mosquitto repository into your rasbian and try the latest version mosquitto 1.5.8 . This one is working well with user credentials, acls and TLS as well.

**Comment by pfeno** [comment]
@sislakd need to return home because at work, some trouble with proxy ;)

**Comment by ralight** [comment]
Can this be closed? It sounds very much like a network problem rather than a mosquitto problem.

**Comment by pfeno** [comment]
I'm at University now and test lab in industry. I check Monday or Tuesday.



Le jeu. 11 avr. 2019 à 22:45, Roger Light <notifications@github.com> a
écrit :
