### ISSUE TITLE
broken: pattern read devices/%u

### ISSUE THREAD

**Issue by reza-n** [eclipse/mosquitto#1217]
I suddenly realized target devices are not getting MQTT messages, while it used to work before. I have a workaround but it seems something is wrong.

Commands used in Linux (actual implementation in paho-mqtt):
`mosquitto_sub -h HOST.com -t devices/73/# -p 8883 --cafile /etc/ssl/certs/DST_Root_CA_X3.pem -u 73 -P SECRET_PASSWORD -d -i 73-console -q 2 -d`

`mosquitto_pub -h HOST.com -t devices/73 -p 8883 --cafile /etc/ssl/certs/DST_Root_CA_X3.pem -u admin -P SECRET_ADMIN_PASSWORD -d -i admin-console -q 1 -m "test message" -d`

This works:

```
user admin
topic readwrite devices/+

pattern write $SYS/broker/connection/%c/state
user 73
topic read devices/73

```

This does not work, while in theory these are the same:
```
user admin
topic readwrite devices/+

pattern write $SYS/broker/connection/%c/state
pattern read devices/%u/+

```
In fact, it does not even connect:
Client 73-console sending CONNECT
Client 73-console sending CONNECT
Client 73-console sending CONNECT
Client 73-console sending CONNECT
Client 73-console sending CONNECT
Client 73-console sending CONNECT
Client 73-console sending CONNECT

Also tried:
`pattern read devices/%u/#`

and 
`pattern read devices/%u`

None of which works now. I had to create individual "topic read devices/user_id_here" rule for each user, and now everything is working again. Cannot tell when it broke, first noticed the issue in February.

Have the patterns changed? 

I tried to debug a bit further, but debug prints now (loglevel all) is not enough. Is there a way I can get even more debug messages so I can read the source?

**Comment by reza-n** [comment]
Forgot to mention the version: 1.5.8-0mosquitto1~xenial1 
(same issue exists in 1.4.8)

**Comment by momoskitto** [comment]
I have the same issues with brokers 1.4.10 and 1.5.6. I can also confirm that it used to work on an earlier version of the broker (I don't remember which, and I cannot test because the older packages are not easily available any more).
However, I have just tested again against different versions of the broker, and the bug does not occur on version 1.5.8 (package 1.5.8-0mosquitto1 from http://repo.mosquitto.org/debian for ARM). Are you certain that the bug occurs on version 1.5.8?

**Comment by momoskitto** [comment]
ok, so I have done some more testing, using the ARM packages from repo.mosquitto.org:

some version older than 1.4.10: works
1.4.10: does not work (package from raspbian.raspberrypi.org)
1.4.14: works
1.4.15: works
1.5: works
1.5.3: works
1.5.4: works
1.5.5: works
1.5.6: does not work
1.5.8: works

Of the versions tested, only 1.4.10 and 1.5.6 do not work for me, everything in between works, and the latest 1.5.8 works as well (1.6 is not yet available as ARM package for debian).

**Comment by reza-n** [comment]
I have verified that it works with 1.6.2 (1.6.2-0mosquitto2~xenial1 on Ubuntu).
