### ISSUE TITLE
Set timezone?

### ISSUE THREAD

**Issue by GoNzCiD** [eclipse/mosquitto#1219]
I have read than mosquitto doesn't read envirinment variables, and I can't see any option in .config file to set timezone.

Is it possible to set timezone in mosquitto? or always works in UTC?

**Comment by ralight** [comment]
If you mean for timestamp logging purposes, then in 1.6 you will be able to specify a timestamp format that follows the local timezone.

**Comment by GoNzCiD** [comment]
OK, I'll wait for 1.6 then.

Thanks
