### ISSUE TITLE
mosquitto_sub -F "%j" not encoding correctly

### ISSUE THREAD

**Issue by benbarbour** [eclipse/mosquitto#1220]
**Steps to Reproduce**
1. `echo -n '"DATA"' | mosquitto_pub -s -r -t myTopic`
2. `mosquitto_sub -t "myTopic/#" -F "%j" -W 1`

**Expected Output:**
```
{
 "tst": 1554139867,
  "topic": "myTopic",
  "qos": 0,
  "retain": 1,
  "payloadlen": 6,
  "payload": "\"DATA\""
}
```

**Actual Output:**
```
{
 "tst": 1554139867,
  "topic": "myTopic",
  "qos": 0,
  "retain": 1,
  "payloadlen": 6,
  "payload": "\u0034DATA\u0034"
}
```

When I decode the actual output's payload using [jq](https://jqplay.org/s/BaI4jtzmUf) I get an error. When I try to [unescape it](https://www.freeformatter.com/json-escape.html) (using a few different tools) I get `"4DATA4"`.

**Comment by ralight** [comment]
Thanks very much, this was a silly mistake. It will be in 1.6 shortly.
