### ISSUE TITLE
mosquitto_sub -F "%J" can output invalid JSON

### ISSUE THREAD

**Issue by benbarbour** [eclipse/mosquitto#1222]
If something publishes invalid JSON, like a single "{" or double-quote character, to a given topic and then it's picked up by `mosquitto_sub -t <topic> -F "%J"` then that will print:

```
{
  "tst":1554162699,
  "topic":"foo",
  "qos":0,
  "retain":1,
  "payloadlen":2,
  "payload":{
}
```

which cannot be parsed.

Would it make sense for `mosquitto_sub` to output something like this if it can't properly format the output? Or maybe print nothing to stdout for that message and instead print to stderr?

```
{
  "tst":1554162699,
  "topic":"foo",
  "qos":0,
  "retain":1,
  "payloadlen":2,
  "payload": "<INVALID_JSON>"
}
```

**Comment by ralight** [comment]
This is a good point. The documentation states the payload must be valid json, but it should definitely handle the case where it isn't.
