### ISSUE TITLE
Retained LWT sent after client reconnect

### ISSUE THREAD

**Issue by aboulfad** [eclipse/mosquitto#1223]
Hello,
the standard is unclear or rather I am unclear if the standard defines LWT behaviour for this scenario: 
- Broker handling of retained LWT to re-subscribed clients after LWT Client reconnects

```
Client1 connects with will/topic1/retain to broker
Client2 connects and subscribes to topic1
Client1 publishes stuff
Client1 abruptly disconnects triggering broker to send LWT
Client2 receives Client1 LWT as expected
Client2 disconnects for any reason

Client1 reconnects, publishes,...
Client2 reconnects and still receives the retained LWT even though Client1 is connected
```

The above described behaviour is the current one in Mosquitto broker v1.5.8 Debian, is it fair to expect that Client2 should not receive Client1 LWT if Client1 has already re-connected?

```
Client1: esp8266 pubsubclient
Client2: node mqtt rpi (debian)
Broker: Mosquitto v1.5.8 rpi (debian)
```

Regards and thanks.

**Comment by ralight** [comment]
I think the behaviour you are describing is exactly what is supposed to happen. If you set the retained bit on a message, the broker will store that message as a last known good value until another retained message is sent for that same topic, or it is cleared by sending a zero length retained message. There is no special handling of LWT messages, they are treated exactly the same.

If you want to have the behaviour of the message disappearing once Client1 reconnects, then Client1 must publish a new retained message to update/delete the existing message.

**Comment by aboulfad** [comment]
Thank you for the hint, I will check how it works in my scenarios on the client side. So when client1 reconnects, it shall send a zero length retained msg to the LWT topic to clear the existing message.

In the meantime, I was looking into moquitto's connect code to see if client connection state is saved, and found this https://github.com/eclipse/mosquitto/blob/ae309b331cf79663d6a0f2df9a976c6511c552fa/src/handle_connect.c#L560  which kinda implies the connection state is persistent. 

I've hit that piece of the code many times (not all the times) but I can't figure out what triggers it from my device's interaction with the broker. So in theory and in practice, I can devise a broker based solution where if the client is reconnecting after a disconnect, to disable sending the LWT to future subscribed clients ?

Granted, I am learning that client connection state handling is not so much fully covered in the standard and broker implementations. Its good to know there are workaround/solutions on the client side.

**Comment by ralight** [comment]
You can hit that situation in two ways.

The first is if you have a client connect to the broker with the same client id as a client that is currently connected to the broker.

The second way is if a client connects to the broker with `clean session` set to false, then disconnects (and the client state is persisted), then reconnects later on, again with `clean session` set to false.
