### ISSUE TITLE
Websocket connection doesn’t get messages on subscription after terminated reconnect #645

### ISSUE THREAD

**Issue by usernametaken** [eclipse/mosquitto#1227]
1) I am running mosquitto 1.5.8 (Windows)
2) I am connecting using websockets
3) I am having a similar issue to #645 (https://github.com/eclipse/mosquitto/issues/645)
4) I connect with a Fixed ClientID
5) CleanSession = False (with CleanSession = True ... no problem)
6) QoS is irrelevant to the problem (I tried all levels)

a) I start my application connect, subscribe and publish... everything works fine
b) I kill my application without sending a DISCONNECT first 
        > Socket error on client Client1, disconnecting
    Everything works fine

c) I send a DISCONNECT before disconnecting :-( The problem starts
   After Reconnecting , and subscribing to the same Topic, 
       I don't receive PUBLISHed messages anymore
d) If I kill my client application and start again.... It still does not work.
e) If I stop and restart mosquitto ... reconnect and subscribe (with or without restarting the client)... everything works.

Doing the same with a TCP client... all works fine

**Comment by ralight** [comment]
Thanks for the easy to follow steps. I confirm this is behaving as you state. It's a bit involved to fix, so won't be part of 1.6.

**Comment by usernametaken** [comment]
Thanks... I am fine for now.
As a workaround I just don't send DISCONNECT before disconnecting, if CleanSession is false, 
... I simply close the socket.

**Comment by ralight** [comment]
Yes that works - as long as you don't want to control whether a Will is sent or not, which is why I didn't suggest it as the solution.

**Comment by ralight** [comment]
I've just pushed a fix for this to the `fixes` branch. If you feel you can give it a try and report back that would be great. It turns out the fix wasn't as involved as I thought, which is good.
