### ISSUE TITLE
Mosquitto websockets not work with paho clients

### ISSUE THREAD

**Issue by AxisNewEngland** [eclipse/mosquitto#1228]
Hi,

I am trying to get some paho clients to work with a mosquitto server running on ubuntu 18.02. I've confirmed that the websocket is open on the desired port (both through netstat and logs). I'm running version 1.5.8 built with libwebsockets version 1.4 (I tried with the most recent libwebsockets version but that didn't work either). I keep getting Socket error: undefined on the paho js utility when trying to connect. Any advice on helping me narrow down the issue here?

Thanks!

**Comment by ralight** [comment]
libwebsockets 2.4 has proved to be the most stable version in my experience.

Could you share your broker config?

**Comment by AxisNewEngland** [comment]
Here it is, the only changes I made from the default were
port 1883
listener 9001
protocol websockets

[mosquitto.txt](https://github.com/eclipse/mosquitto/files/3090810/mosquitto.txt)

**Comment by ralight** [comment]
Could you try connecting to test.mosquitto.org port 8080? This is a websockets listener and has many people connecting to it. If that fails for you, then it is the client that is at fault.

**Comment by AxisNewEngland** [comment]
I actually fixed it, my browser was blocking external scripts from running on browser pages.

**Comment by ralight** [comment]
Great to hear, I'll close this report then.
