### ISSUE TITLE
tests are not available via the standard interface

### ISSUE THREAD

**Issue by gdt** [eclipse/mosquitto#1230]
Normally (in the world according to autoconf :-), "make check" runs tests.  From Roger's comment on the list, it seems that tests aren't available when building with cmake, and with regular make the target is test.  This ticket asks for:
 * make check to run the tests when building that way
 * tests to run via cmake's standard approach when building that way
 * README to explain how to run tests

**Comment by ralight** [comment]
`make check` works now, plus there is a readme-tests.md. CMake tests crude support with the standard `make test` target which just runs `make -C ${mosquitto_SOURCE_DIR}/test test`.
