### ISSUE TITLE
bundled uthash is not explained in README

### ISSUE THREAD

**Issue by gdt** [eclipse/mosquitto#1231]
There's a bundled copy of uthash.  Packaging norms are to depend on a package instead, to enable fixing bugs in uthash via new releases rather than needing a new uthash and then new mosquitto release.  README.txt  should explain that this is a dependency (which could be satisfied by the bundled dependency, for those who prefer that).

**Comment by ralight** [comment]
Fixed for 1.6.1, with comments on how to disable the bundled deps.
