### ISSUE TITLE
test build does not respect CPPFLAGS/LDFLAGS from environment

### ISSUE THREAD

**Issue by gdt** [eclipse/mosquitto#1232]
Doing "gmake tests" (without cmake) does not respect CPPFLAGS and LDFLAGS from the environment.  This is needed in my case to find CUnit and uthash, which are built with prefix of /usr/pkg. This is an issue in the tests subdirectory, not just top-level.

The test makefile does not separate LDFLAGS (for -L/-R) and LDADD (for -lfoo).  That contributes to not being able to pass in LDFLAGS.

(I believe that the non-cmake build should be retired, but as it is the only way to run tests at the moment, I thought I should report this.)

**Comment by ralight** [comment]
This is fixed for 1.6.1, thanks.
