### ISSUE TITLE
Add memory limits

### ISSUE THREAD

**Issue by didjcodt** [eclipse/mosquitto#1237]
Dear community, 

I'm currently using mosquitto inside docker and I'm having issues with the cgroup memory limits making the mosquitto being OOM Killed when I send to many messages, or big binary messages.

I tried to find an option to limit its usage in order to refuse messages when there is no memory left, but the options I found are either:
- `max_queued_messages`, which is not enough for this use case (There can be multiple mid-size messages and some very huge messages).
- `max_queued_bytes`, but I need to control the number of devices that connect to the broker in order to set that parameter.

The ideal option in my case would have been some kind of general limit, not considering per-device/per-message limit.

I saw a message from Dec 2016 mentioning the same kind of option (https://www.eclipse.org/lists/mosquitto-dev/msg01400.html)

My proposal would be to add a `total_memory_limit_bytes` option, usable only when the memory tracking is enabled, that would refuse new messages from devices when full.

I am willing to implement this feature and give you a pull request, I was just wondering if there was another already-implemented option and if it would be ok for you?

Thanks

**Comment by ralight** [comment]
Did you see the `memory_limit` option?

**Comment by karlp** [comment]
is memory_limit in the docs (yet?) it's in the changelog, but not the man pages that I can see.

**Comment by didjcodt** [comment]
Wow that's a great news! Thank you for this, I didn't see that option! I'll try it asap!

**Comment by ralight** [comment]
@karlp Good point, I'll get it documented.

**Comment by ralight** [comment]
I've documented this option now, so I'm closing this. If it doesn't do what you hoped then reopen and add more details.
