### ISSUE TITLE
ACL pattern clause insufficient 

### ISSUE THREAD

**Issue by srieche** [eclipse/mosquitto#1241]
I just migrated my config files from an older version (maybe 1-2 years) to the latest debian release and encountered a strange issue.
I have my ACL file setup as follows

```
# This affects all clients.
 pattern write $SYS/broker/connection/%c/state
 pattern read %u/cmnd/#
 pattern readwrite %u/stat/#
 pattern readwrite %u/tele/#
```
I also have the corresponding password file setup correctly, but when attempting to publish to an allowed topic, the mosquitto-clients cli returns this:

```
user@debian:~$ mosquitto_pub -h localhost -u esp-001 -P password -t 'esp-001/tele/LWT' -m 'sdfoij'
Error: The connection was lost.
```
The log file shows:

```
...: New connection from x.x.x.x on port 1883.
...: Socket error on client <unknown>, disconnecting.
```

I know this setup was working correctly on an older release so am confident it's not an error on my part. Interestingly enough, after investigating a little, I noticed that I can achieve the expected behaviour by adding in a dummy `user` clause to the ACL file like this:

```
user esp-001
topic read null
```

I'm relatively certain this isn't intended but it's a suitable workaround for anyone encountering a similar issue. Please don't hesitate to ask for more information - happy to dig deeper if it helps :)

**Comment by ralight** [comment]
When you say "the latest Debian release", do you mean 1.4.10-3+deb9u2 on stretch, 1.4.10-3+deb9u4 on stretch-security, 1.5.7-1 on testing, or 1.5.8/1.6.1 from repo.mosquitto.org? :)

My bet is on 1.4.10-3+deb9u2.

**Comment by srieche** [comment]
Good point, sorry for being ambigious. It's 1.4.10-3+deb9u4 from the raspbian stretch repo.

**Comment by ralight** [comment]
Right, this is a not unknown problem with that specific patched version I'm afraid. If you have a client connect with a username but there are no acls specific to that username, then it will be disconnected, even if pattern acls would match. I don't believe a patch fixing this would meet the Debian requirements, so it is unlikely to change. My advice would be to use the repository at repo.mosquitto.org if you can. The armhf packages there are suitable for Raspbian, and you can choose any package version back to 1.4.15.

**Comment by srieche** [comment]
Thanks for your response. That's fair enough, the only reason I wanted this functionality was to asign _default_ permissions to new usernames added to the password file but I completely understand if this was an intentional design decision.
Once again, thanks for the quick and helpful response - feel free to close the issue (unless I need to) :)

**Comment by ralight** [comment]
It's not an intentional decision, it just made it into that specific version. If you move to a different version it should work just fine the same way you had it.
