### ISSUE TITLE
Warning: Received PUBREL from 866971030943919 for an unknown packet identifier 1

### ISSUE THREAD

**Issue by dongwencai** [eclipse/mosquitto#1243]
Warning: Received PUBREL from 866971030943919 for an unknown packet identifier 1

**Comment by ralight** [comment]
This means that your client sent a message that the broker wasn't expecting. It isn't a problem in itself, but could indicate that your client is misbehaving or that the broker lost state (was it restarted?), or possibly that the broker used one of the new negative acknowledgement results in MQTT v5, and your client did not respect it. Without more details it is impossible to say.

**Comment by ralight** [comment]
I'm closing this because there isn't any information, if it's still a problem please reopen and provide more details.
