### ISSUE TITLE
$SYS/broker/version is no longer published in 1.6.1

### ISSUE THREAD

**Issue by ckrey** [eclipse/mosquitto#1245]
with default or explicit sys_interval > 0

- #sys_interval 10
- sys_interval 10

**Comment by ralight** [comment]
It works for me, do you have any other config? I used `./mosquitto` on its own, or `./mosquitto -c m.conf`, where `m.conf` was just

```
sys_interval 10
```

**Comment by ckrey** [comment]
I tracked the problem down to the use of

> check_retain_source true

`$SYS/broker/version` is not published if `check_retain_source` is true, but is published if false.

When `check_retain_source` is not explicitly set the result is unpredictable* because I see no 
initialization of `config->check_retain_source` in `conf.c`.

* I have two systems, one on Debian, one running Centos which behave differently with the same config

**Comment by ckrey** [comment]
If you want an example on a server you control:

```
$ mosquitto_sub -t '$SYS/broker/+' -v -h test.mosquitto.org
$SYS/broker/uptime 407352 seconds
```

**Comment by ralight** [comment]
test.mosquitto.org spends a lot of time running under valgrind, I'm sure it would have come up if `check_retain_source` wasn't being initialised. The first line of `config__init` should clear `check_retain_source`:

```
memset(config, 0, sizeof(struct mosquitto__config));
```

When the config is reloaded memset is used as well.

I confirm the behaviour with `check_retain_source` set to true.

Did you compile the Debian/Centos packages manually, or if not where were they from?

**Comment by ralight** [comment]
Aha! You've spotted two bugs here. The first is around `check_retain_source`, the second is that `$SYS/broker/version` was being expired after 60 seconds. This explains the different behaviour you've seen.
