### ISSUE TITLE
mosquitto_sub abort when broker not running

### ISSUE THREAD

**Issue by ckrey** [eclipse/mosquitto#1246]
version 1.6.1 
```
$ mosquitto_sub -t '#' -v
Error: Connection refused
free(): double free detected in tcache 2
Aborted
```

**Comment by ralight** [comment]
Thank you - fixed in my local branch ready for tomorrow. This is annoying but minor, it only happens as part of the client exiting.

**Comment by ckrey** [comment]
Thanks for fixing it. And yes, annoying only
