### ISSUE TITLE
"free(): invalid pointer" error when using -L option

### ISSUE THREAD

**Issue by andrewjfreyer** [eclipse/mosquitto#1248]
### **Installation Details:**

Raspbian GNU/Linux 9

mosquitto_pub version 1.6.1 running on libmosquitto 1.6.1

### **Steps to reproduce:**

```bash
mosquitto_pub -L "mqtt://{username}:{password}@{address}:{port}/{topic}" -m ""
```

### **Result:**

```bash
*** Error in `mosquitto_pub': free(): invalid pointer: 0x{pointer address} ***
Aborted
```

### **Expected result:** 

Silent completion of posted message, as with previous versions.

**Comment by ralight** [comment]
Thank you! This is fixed in my local branch ready for release tomorrow.

**Comment by andrewjfreyer** [comment]
excellent!

**Comment by andrewjfreyer** [comment]
Confirmed fixed on my end. Thanks for addressing this so quickly!

**Comment by ralight** [comment]
Thanks for confirming :)
