### ISSUE TITLE
pkgconfig files are installed in share

### ISSUE THREAD

**Issue by gdt** [eclipse/mosquitto#1251]
Because the contents of mosquitto.pc will vary with architecture (if only for lib64), they cannot be reused in an arch-independent $prefix/share mount.  Therefore they should be installed to $libdir/pkgconfig, which seems to be the standard approach.

(See mailinglist discussion.)

**Comment by chewi** [comment]
This was fixed years ago in 99ace10dafa206a3370b6a390c015aaf18a6b7b1.

**Comment by gdt** [comment]
Great, thanks for pointing this out.   Indeed the current pkgsrc control files show them in the right place.
