### ISSUE TITLE
Add client address parameter to the plugin function mosquitto_auth_unpwd_check?

### ISSUE THREAD

**Issue by leojay** [eclipse/mosquitto#1252]
Right now, there is no way to verify the ip address of the client. Do you think ip address can be added to the mosquitto_auth_unpwd_check plugin function?
Or, as an alternative, provide a function to get the address from a mosquitto*?
Thanks!
Leo

**Comment by ralight** [comment]
Happily, this is already available in the mosquitto_broker.h header:

```
/*
 * Function: mosquitto_client_address
 *
 * Retrieve the IP address of the client as a string.
 */
const char *mosquitto_client_address(const struct mosquitto *client);
```

It isn't installed on the ubuntu or debian packages though, I'll fix that. I can't comment on other packages.

**Comment by leojay** [comment]
But how do I use this function? does that mean I have to link my plugin against libmosquitto.so?

**Comment by ralight** [comment]
The function is provided in the mosquitto broker itself and is accessible to the plugin once it has been loaded by the broker. All you should need to do is `#include <mosquitto_broker.h>` and then call the function.
