### ISSUE TITLE
Increased connection time to mqtt

### ISSUE THREAD

**Issue by Ing-Med** [eclipse/mosquitto#1253]
Hi Guys,

i am reaching out to you here because i just cannot find a solution to my problem. I use mosquitto as an addon to home-assistant (hassio). They recently updated their mosquitto version making ACL for example necessary in order to work properly again. 
However thats not my problem. My problem is, that devices which have not been connected recently have an increased connection time. Its about 3-3,5 seconds it takes until my device is connected to my mqtt server. As i have only battery driven devices, this reduces my battery life significantly. The problem has only appeared after updating to the latest mosquitto version (i have been behind a couple versions i think). 

Here is my original post on the homeassistant community forums.
https://community.home-assistant.io/t/after-mosquitto-update-increased-connection-time

Attached is a part of the log file

Thanks in advance ! 

> 1556468733: New connection from 10.10.10.30 on port 1883.
> 1556468733: |-- mosquitto_auth_unpwd_check(iot)
> 1556468733: |-- ** checking backend http
> 1556468733: |-- url=http://127.0.0.1:8080/login
> 1556468733: |-- data=username=iot&password=xxxxxx&topic=&acc=-1&clientid=
> [INFO] found iot on local database
> 1556468736: |-- getuser(iot) AUTHENTICATED=1 by http
> 1556468736: New client connected from 10.10.10.30 as kuchenbox (c1, k15, u’iot’).
> 1556468736: Client kuchenbox disconnected.
> 1556468823: New connection from 10.10.10.33 on port 1883.
> 1556468823: |-- mosquitto_auth_unpwd_check(iot)
> 1556468823: |-- ** checking backend http
> 1556468823: |-- url=http://127.0.0.1:8080/login
> 1556468823: |-- data=username=iot&password=xxxxxx&topic=&acc=-1&clientid=
> [INFO] found iot on local database
> 1556468826: |-- getuser(iot) AUTHENTICATED=1 by http
> 1556468826: New client connected from 10.10.10.33 as Neon (c1, k15, u’iot’).
> 1556468826: Client Neon disconnected.
> 1556468870: New connection from 10.10.10.32 on port 1883.
> 1556468870: |-- mosquitto_auth_unpwd_check(iot)
> 1556468870: |-- ** checking backend http
> 1556468870: |-- url=http://127.0.0.1:8080/login
> 1556468870: |-- data=username=iot&password=xxxxxx&topic=&acc=-1&clientid=
> [INFO] found iot on local database
> 1556468872: |-- getuser(iot) AUTHENTICATED=1 by http
> 1556468872: New client connected from 10.10.10.32 as Io (c1, k15, u’iot’).
> 1556468873: Client Io disconnected.
> 1556468967: New connection from 10.10.10.30 on port 1883.
> 1556468967: |-- mosquitto_auth_unpwd_check(iot)
> 1556468967: |-- ** checking backend http
> 1556468967: |-- url=http://127.0.0.1:8080/login
> 1556468967: |-- data=username=iot&password=xxxxxx&topic=&acc=-1&clientid=
> [INFO] found iot on local database
> 1556468970: |-- getuser(iot) AUTHENTICATED=1 by http
> 1556468970: New client connected from 10.10.10.30 as kuchenbox (c1, k15, u’iot’).
> 1556468993: Client kuchenbox has exceeded timeout, disconnecting.
> 1556468993: Socket error on client kuchenbox, disconnecting.
> 1556469203: New connection from 10.10.10.30 on port 1883.
> 1556469203: |-- mosquitto_auth_unpwd_check(iot)
> 1556469203: |-- ** checking backend http
> 1556469203: |-- url=http://127.0.0.1:8080/login
> 1556469203: |-- data=username=iot&password=xxxxxx&topic=&acc=-1&clientid=
> [INFO] found iot on local database
> 1556469205: |-- getuser(iot) AUTHENTICATED=1 by http
> 1556469205: New client connected from 10.10.10.30 as kuchenbox (c1, k15, u’iot’).
> 1556469228: Client kuchenbox has exceeded timeout, disconnecting.
> 1556469228: Socket error on client kuchenbox, disconnecting.
> 1556469438: New connection from 10.10.10.30 on port 1883.
> 1556469438: |-- mosquitto_auth_unpwd_check(iot)
> 1556469438: |-- ** checking backend http
> 1556469438: |-- url=http://127.0.0.1:8080/login
> 1556469438: |-- data=username=iot&password=xxxxxx&topic=&acc=-1&clientid=
> [INFO] found iot on local database
> 1556469441: |-- getuser(iot) AUTHENTICATED=1 by http
> 1556469441: New client connected from 10.10.10.30 as kuchenbox (c1, k15, u’iot’).
> 1556469464: Client kuchenbox has exceeded timeout, disconnecting.
> 1556469464: Socket error on client kuchenbox, disconnecting.
> 1556469508: New connection from 10.10.10.33 on port 1883.
> 1556469508: |-- mosquitto_auth_unpwd_check(iot)
> 1556469508: |-- ** checking backend http
> 1556469508: |-- url=http://127.0.0.1:8080/login
> 1556469508: |-- data=username=iot&password=xxxxxx&topic=&acc=-1&clientid=
> [INFO] found iot on local database
> 1556469511: |-- getuser(iot) AUTHENTICATED=1 by http
> 1556469511: New client connected from 10.10.10.33 as Neon (c1, k15, u’iot’).
> 1556469511: Client Neon disconnected.
> 1556469547: New connection from 10.10.10.32 on port 1883.
> 1556469547: |-- mosquitto_auth_unpwd_check(iot)
> 1556469547: |-- ** checking backend http
> 1556469547: |-- url=http://127.0.0.1:8080/login
> 1556469547: |-- data=username=iot&password=xxxxxx&topic=&acc=-1&clientid=
> [INFO] found iot on local database
> 1556469550: |-- getuser(iot) AUTHENTICATED=1 by http
> 1556469550: New client connected from 10.10.10.32 as Io (c1, k15, u’iot’).
> 1556469550: Client Io disconnected.
> 1556469674: New connection from 10.10.10.30 on port 1883.
> 1556469674: |-- mosquitto_auth_unpwd_check(iot)
> 1556469674: |-- ** checking backend http
> 1556469674: |-- url=http://127.0.0.1:8080/login
> 1556469674: |-- data=username=iot&password=xxxxxx&topic=&acc=-1&clientid=
> [INFO] found iot on local database
> 1556469676: |-- getuser(iot) AUTHENTICATED=1 by http
> 1556469676: New client connected from 10.10.10.30 as kuchenbox (c1, k15, u’iot’).
> 1556469699: Client kuchenbox has exceeded timeout, disconnecting.
> 1556469699: Socket error on client kuchenbox, disconnecting.
> 1556469910: New connection from 10.10.10.30 on port 1883.
> 1556469910: |-- mosquitto_auth_unpwd_check(iot)
> 1556469910: |-- ** checking backend http
> 1556469910: |-- url=http://127.0.0.1:8080/login
> 1556469910: |-- data=username=iot&password=xxxxxx&topic=&acc=-1&clientid=
> [INFO] found iot on local database
> 1556469912: |-- getuser(iot) AUTHENTICATED=1 by http
> 1556469912: New client connected from 10.10.10.30 as kuchenbox (c1, k15, u’iot’).
> 1556469913: Client kuchenbox disconnected.

**Comment by Ing-Med** [comment]
Thank you for your reply. Isn't the authentication Part of the mqtt protocol/Server or am i confused here?

**Comment by ralight** [comment]
It is, but mosquitto provides a plugin interface for others to write their own authentication. Your log messages do not originate in mosquitto itself, so they must come from an authentication plugin. I can see lines like "AUTHENTICATED by http" - there is no http based authentication in the core mosquitto.

**Comment by Ing-Med** [comment]
You are right. It indeed seems to be a problem solely caused by homeassistant. I fired up a separate mosquitto instance, and the 3second delay is gone! 
Thanks!
