### ISSUE TITLE
Windows v1.6.2 binary downloads are not available

### ISSUE THREAD

**Issue by hjhsalo** [eclipse/mosquitto#1256]
'mosquitto-1.6.2-install-windows-x64.exe' and 'mosquitto-1.6.2-install-windows-x32.exe' are listed at https://mosquitto.org/download/ , but both download links are broken.

Folder the x64 link points to doesn't seem to contain the file:
https://mosquitto.org/files/binary/win64/ 

Workaround mentioned in https://github.com/eclipse/mosquitto/issues/929#issuecomment-416052541 doesn't seem to work for 1.6.x

**Comment by ralight** [comment]
Thanks for reporting this, it was fixed quite a while ago now.
