### ISSUE TITLE
Disable Secure Client-Initiated Renegotiation

### ISSUE THREAD

**Issue by daenney** [eclipse/mosquitto#1257]
I'd like the ability to configure mosquitto to disable Secure Client-Initiated Renegotiation. It's a [potential DoS vector](https://blog.qualys.com/ssllabs/2011/10/31/tls-renegotiation-and-denial-of-service-attacks).

**Comment by ralight** [comment]
Would it be reasonable to have this disabled completely rather than configurable?

**Comment by ralight** [comment]
From what I've read, the movement appears to be towards disabling renegotiation completely.

**Comment by daenney** [comment]
Yes, I would disable it completely but I figured it should at least be configurable.

**Comment by ralight** [comment]
Renegotiation disabled! Thanks for the report.
