### ISSUE TITLE
mosquitto_sub unknown option

### ISSUE THREAD

**Issue by urkelbundy** [eclipse/mosquitto#1265]
Hi all,

Mosquitto clients installed from the mosquitto repository on a cubieboard with Debian Stretch armhf.
mosquitto_pub works fine but mosquitto_sub complains about unknown options.
E.g. mosquitto_sub -d -h localhost -t mytopic
First it complains about the -d option. When I remove this option it complains about the -t option.
The same options work fine with mosquitto_pub.

These are basic options and should work so I assume something is wrong in Debian Stretch installed on this cubieboard but I do not know where to start looking.

Best regards

**Comment by ralight** [comment]
My guess would be there is a compilation/processor option incompatibility. Could you try compiling it yourself to see if that fixes the problem for you?

**Comment by ralight** [comment]
I presume this isn't an issue any more, so am going to close this. If it is, please reopen and provide more details.
