### ISSUE TITLE
Question: Is the database file compatible across 1.3 1.4 and 1.5? How can i upgrade without losing state?

### ISSUE THREAD

**Issue by jsaak** [eclipse/mosquitto#1269]
Is the database file compatible across 1.3 1.4 and 1.5?
How can i upgrade without losing state?

**Comment by ralight** [comment]
The file format has changed, but the broker can read all older versions. It only saves out in the latest format, so once you are on 1.5 you can't go back with the new persistence file. I would suggest taking a copy of the file and trying it out with the newer broker, then on the off chance that you do see a problem your main broker hasn't been affected.

**Comment by jsaak** [comment]
Thank you that is good news.

**Comment by jsaak** [comment]
Added upgrading documentation to man mosquitto: https://github.com/eclipse/mosquitto/pull/1276
