### ISSUE TITLE
MQTT 5.0: Authentication with only password does not work with mosquitto_pub.

### ISSUE THREAD

**Issue by eerimoq** [eclipse/mosquitto#1274]
Hello!

The MQTT version 5.0 specification allows a client to send a password
with no user name in the connect packet. The ``mosquitto_pub``, and
probably ``mosquitto_sub``, programs does now support this it seems.

Copied from the specification:

"This version of the protocol allows the sending of a Password with no
User Name, where MQTT v3.1.1 did not. This reflects the common use of
Password for credentials other than a password."

A warning is printed if a password is given but no user name. The password is not sent to the broker.

``` text
$ mosquitto_pub -V mqttv5 -t myt -m mym -d -P mypass
Warning: Not using password since username not set.
Client (null) sending CONNECT
Client (null) received CONNACK (0)
Client (null) sending PUBLISH (d0, q0, r0, m1, 'myt', ... (3 bytes))
Client (null) sending DISCONNECT
```

The command works when both user name and password are given.

``` text
$ mosquitto_pub -V mqttv5 -t myt -m mym -d -u myuser -P mypass
Client (null) sending CONNECT
Client (null) received CONNACK (134)
Bad User Name or Password
```

**Comment by ralight** [comment]
Thanks very much, I've just pushed a change that fixes this and will be part of 1.6.3.
