### ISSUE TITLE
Bus error when trying to start the broker with websockets

### ISSUE THREAD

**Issue by Laysowski** [eclipse/mosquitto#1275]
Hello everyone,

the very first thing I'd like to say that I tried my best to start the mosquitto broker with websockets but I failed.

I prepared all necessary dependancies, went through 'make' and 'make install' stuff.
Secondly, I can easily start normal mosquitto broker without websockets.
The problem is I can't start working on the broker with websockets - I compiled mosquitto with WITH_WEBSOCKETS:=yes.

In my mosquitto.conf file I added following lines:
port 1883
listener 9001
protocol websockets

Everytime i try to run 'mosquitto -c mosquitto.cong' I get the same "Bus error"

**1557694095: mosquitto version 1.4.10 (build date 2019-05-12 22:33:48+0200) starting
1557694095: Config loaded from mosquitto.conf.
1557694095: Opening websockets listen socket on port 9001.
Bus error**

What am I doing wrong?

mosquitto version: 1.4.10 (MQTT Broker v3.1)
libwebsockets version: 2.1.1
Raspberry Pi

**Comment by ralight** [comment]
I don't know, my best guess would be is that there is a problem with the compilation like compiling for the wrong arm processor.

Are you able to use the packages provided by the project at https://repo.mosquitto.org/debian/ instead? They have websockets support.

**Comment by ralight** [comment]
This hasn't seen any activity for a while, and the versions in use are a lot out of date. If this is still an issue please reopen and give more details.
