### ISSUE TITLE
Silensed mosquitto_sub with qos 2

### ISSUE THREAD

**Issue by Assar63** [eclipse/mosquitto#1278]
Situation:
* Hardware running Ubuntu Bionic on laptop with sleep enabled when closing lid.
* Running mosquitto 1.6.2-0mosquitto1~bionic1 from launchpad with ditto client.
* Started mosquitto_sub -q 2 -c -i matest -v -t \# during last working session. It works well.
* In parallel I also run mosquitto_sub -v -t \#
* Data is published in slow pace with qos 2 on local broker.
* Closed lid while travelling and computer is asleep nice and well.
* When lid is opened both mosquitto as  well as the two listeners processes were running.

Expected result:
* Both listeners should present new messages from now on.

What hapened:
* The unnamed listener presents all new incoming messages.
* The "matest" named listener is quiet. Even after restarting the listener it stays quiet, tested ten times.
* Starting a third "matestX" named listener with qos 2 presents everything ok.
* Changing the same "matest" named topic to a more qualified one results in data coming in (mosquitto_sub -q 2 -c -i matest -v -t evt/#) . After that I could use first wildcard topic again whith original mosquito_sub -q 2 -c -i matest -v -t \#.

I will try to reproduce this until tomorrow. Since this may involve a problem on the broker it might raise a problem, but my mosquitto server is not likely to be run on a laptop it is probably not affecting me.

**Comment by Assar63** [comment]
This morning it worked ok.
The issue happened during weekend. 
Need to test next weekend then.

**Comment by Assar63** [comment]
I cannot reproduce this problem.
Closing it

**Comment by ralight** [comment]
Thanks for trying and giving the feedback.
