### ISSUE TITLE
How to disconnect and close the struct mosquitto object safely?

### ISSUE THREAD

**Issue by Hapoa** [eclipse/mosquitto#1282]
I have a GUI program, I detach a thread to run `mosquitto_loop_forever`. When received signal from user's close-button-click, I should let mosquitto object disconnect with broker and destroy itself to free its memory.

So, **In another thread**, I managed this mosquitto object, and when received signal from user's close-button-click, I call `mosquitto_disconnect`, and next `mosquitto_loop_forever` exit normally, so I can continue to call `mosquitto_destroy`.

It is a good action? `mosquitto_disconnect` in another thread? Because I found , sometimes, my program will crash when close-button-click happen.

Thanks in advance.

**Comment by ralight** [comment]
libmosquitto has two modes it can run in - threaded and non-threaded. If you use `mosquitto_loop_start()`, the library starts a new thread to run the network loop. If you use `mosquitto_loop_forever()`, it does not start a new thread and also assumes that you are not using threads so it can make some optimisations. Those optimisations may cause problems if you are using multiple threads, so I imagine that is what you are seeing.

I would suggest using `mosquitto_loop_start()`, then `mosquitto_disconnect()` and `mosquitto_loop_stop()`. Alternatively, you could try using `mosquitto_threaded_set(mosq, true)` in your existing code before you call `mosquitto_loop_forever()`, to tell the library that you are using threads.

**Comment by Hapoa** [comment]
Thanks a lot, I get it !
