### ISSUE TITLE
Adding '--quiet' does not suppress warning

### ISSUE THREAD

**Issue by robdejonge** [eclipse/mosquitto#1284]
Firing `mosquitto_pub` from scripts launched by both `systemd` and Duplicati, in both cases results in an error message: 
> Warning: Unable to locate configuration directory, default config not loaded

I run `mosquitto_pub` with a defined MQTT host, topic and message as parameters. The script launched by `systemd` is just printing messages into the syslog, but the script fired by Duplicati is actually resulting in warnings being passed up the chain. I'm not happy with this and would like the warnings gone. Running directly from the command line does not throw those errors. 

What I've already tried: 
- Installed the mosquitto daemon, to see if this would install some kind of configuration that the tool would be happy enough with. Nope. 
- Tried to figure out how and where a config should be saved, but couldn't find much information to this. 

So I thought I'd use the ugly solution: 
- Add the `--quiet` switch as it's advertised to not print error messages.

Doesn't work!

**Comment by ralight** [comment]
Thanks Rob, I've pushed a change that fixes that. It'll be in 1.6.3.
