### ISSUE TITLE
Building auth-plugin now (since 2016?) requires mosquitto_internal.h which is not installed by Makefiles

### ISSUE THREAD

**Issue by D-r-P-3-p-p-3-r** [eclipse/mosquitto#1288]
When implementing an auth-plugin using `mosquitto_plugin.h` the use of `struct mosquitto` is required. This is the case since the interface declared in `mosquitto_plugin.h` has changed (I assume since commit ccedc6d7092f70dcb00663eb9dc03a6637a721eb).
The struct is defined in `mosquitto_internal.h` which is _not_ installed during build. Thus building an auth-plugin is not possible.

I fixed this for me by adding the installation of
- mosquitto_internal.h
- config.h
- time_mosq.h
to the Makefiles.

I believe the CMake-based build is affected as well. I didn't try this though.

**Comment by ralight** [comment]
`struct mosquitto` is an opaque type, you aren't allowed to see what is in it directly. The size and members of this struct may change at any point, if you are accessing it directly your plugin will cause a crash at some point unless you recompile every time a new version is released.

Please use the functions provided in `mosquitto_broker.h` to access information in the mosquitto struct.

If you'd like to complain that this isn't documented very well then I have no choice but to agree with you.

**Comment by D-r-P-3-p-p-3-r** [comment]
Excellent. Thanks.
I had just found `mosquitto_plugin.h` and tried to work from there...
Maybe a comment in there'd be helpful.
