### ISSUE TITLE
extern "C" missing from mosquitto_broker.h and mosquitto_plugin.h

### ISSUE THREAD

**Issue by D-r-P-3-p-p-3-r** [eclipse/mosquitto#1290]
This makes it a little tricky to write an auth-plugin in C++.

You have to include the files like this
```
extern "C" {
#include <mosquitto_broker.h>
}
```

or C++ name mangeling is going to get in your way, e.g. like this
```
mosquitto[1076]: Error: Unable to load auth plugin "/foo/auth.so".
mosquitto[1076]: Load error: /foo/auth.so: undefined symbol: _Z25mosquitto_client_usernamePK9mosquitto
```

Most likely all "public" headers should provide `extern "C"` support - like `mosquitto.h` does.

**Comment by ralight** [comment]
Completely agree, thanks done now thanks very much.
