### ISSUE TITLE
function-like macro '__GNUC_PREREQ' is not defined

### ISSUE THREAD

**Issue by LiamFry** [eclipse/mosquitto#1291]
I have this problem when building mosquitto on macOS 10.13.6/High Sierra.
I prepare with `cmake -DWITH_TLS_PSK=OFF -DWITH_TLS=OFF .`
(No errors)
Then compile with `make`
And I get this:
```
[ 31%] Building C object lib/CMakeFiles/libmosquitto.dir/util_mosq.c.o
/Users/rando/root/pkg/tool/mosquitto/mosquitto-1.6.2/lib/util_mosq.c:328:29: error: function-like macro '__GLIBC_PREREQ' is not defined
#elif defined(__GLIBC__) && __GLIBC_PREREQ(2, 25)
                            ^
1 error generated.
make[2]: *** [lib/CMakeFiles/libmosquitto.dir/util_mosq.c.o] Error 1
make[1]: *** [lib/CMakeFiles/libmosquitto.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by ralight** [comment]
Thanks for the report.

This has already been fixed in https://github.com/eclipse/mosquitto/commit/d05bd958813b7ead344f66653ce9b13b00e67595 and will be part of 1.6.3.

For now, just remove the `&& __GLIBC_PREREQ(2, 25)` and you should be fine.
