### ISSUE TITLE
Client binaries do not respect LDFLAGS

### ISSUE THREAD

**Issue by oxr463** [eclipse/mosquitto#1294]
Compiled with the command, `LDFLAGS="-Wl,--defsym=__check_ldflags__=0" CLIENT_LDFLAGS="${LDFLAGS}" make`.

Output from `objdump`:

```terminal
objdump -x lib/libmosquitto.so.1 | grep __check
0000000000011340 l     F .text  000000000000016e              mosquitto__check_keepalive
000000000000ceb0 l     F .text  000000000000003b              packet__check_oversize
0000000000000000 l       *ABS*  0000000000000000              __check_ldflags__
objdump -x client/mosquitto_pub | grep __check
objdump -x client/mosquitto_sub | grep __check
objdump -x client/mosquitto_rr | grep __check
```

Note: checking for the `__check_ldflags__` symbol returned `1` for the client binaries.

**Comment by oxr463** [comment]
If I pass the `-e` to make it will respect the environment variables.

See also: https://github.com/eclipse/mosquitto/issues/1232

**Comment by ralight** [comment]
You can now do this with just `make LDFLAGS="-Wl,--defsym=__check_ldflags__=0"` in the fixes branch.
