### ISSUE TITLE
Version 1.6.2 websockets error in Windows: "Error in poll: No such file or directory. "

### ISSUE THREAD

**Issue by digitop** [eclipse/mosquitto#1300]
Hi!

I downloaded and installed the 1.6.2 x64 version (binaries). After enabling the websockets, the log file fills up with the error message: "Error in poll: No such file or directory. ". In a few seconds a thousands of error messages logged.
If I comment out the websockets support, this error does not happens.
What could be wrong?

**Comment by ralight** [comment]
I'm not sure, and I can't get access to a Windows machine to test it for about a week I'm afraid.

**Comment by corelgott** [comment]
+1 - same here!

**Comment by corelgott** [comment]
Ok, I think I'd like to make an educated guess here:

I was able to resolve the issue by adding `socket_domain ipv4` [see here](https://mosquitto.org/man/mosquitto-conf-5.html#socket_domain)

The problem seemd to be, that mosquitto tried to bind to the ipv6-addr also. Which didn't work for [reasons]

In addition to that: If you get some kind of error like: `An attempt was made to access a socket in a way forbidden by its access permissions.` the Internet Connection Sharing service (ICS), which is used by hyper-v, might be the origin of that. If a docker container has a reservation for that port (From what I see, the container might not even need to run!) the ics grabs that port and blocks it.

Hope that helps to resolve the issue!

Regards,

Corelgott

**Comment by corelgott** [comment]
After testing around quite alot, I think I've figured a configuration that works:

```
port 1883
protocol mqtt
socket_domain ipv4

listener 9001
protocol websockets
socket_domain ipv4
```
If I remove the `protocol mqtt` part, it breaks again. So for some reason there needs to be both. I'm not 100% sure if the `socket_domain` part really is necessary, but for my usecase it surfices.

**Comment by digitop** [comment]
corelgott: thanks for the solution, I've tested it, and it works! :)

**Comment by gemignani** [comment]
Same works for me by adding socket_domain ipv4.
Just for future reference, I had a working eclipse-mosquitto docker image in my ubuntu server 18.04 LTS until I removed ipv6, so seems like the docker can't listen to ipv6 sockets and just fails.
