### ISSUE TITLE
Regression: Zero length input using --stdin-line not handled properly

### ISSUE THREAD

**Issue by marwatk** [eclipse/mosquitto#1302]
Looks like #676 has cropped back up. It works fine with 1.5.3 but not 1.6.2:

```
root@softwareradio:~# mosquitto_pub --help | head -2
mosquitto_pub is a simple mqtt client that will publish a message on a single topic and exit.
mosquitto_pub version 1.6.2 running on libmosquitto 1.6.2.

root@softwareradio:~# dd if=/dev/zero count=0 | mosquitto_pub --stdin-line --topic sensors/433_raw --host <redacted> --port 1883 -d
0+0 records in
0+0 records out
0 bytes copied, 0.00390834 s, 0.0 kB/s
Client mosq/sCYUoZnobu8Y2A3y5a sending CONNECT
Client mosq/sCYUoZnobu8Y2A3y5a received CONNACK (0)
```

Here's with 1.5.3:
```
0+0 records in
0+0 records out
0 bytes copied, 0.0366094 s, 0.0 kB/s
Client mosqpub|11313-softwarer sending CONNECT
Client mosqpub|11313-softwarer received CONNACK (0)
Client mosqpub|11313-softwarer sending DISCONNECT
```

**Comment by ralight** [comment]
Are you able to check with the fixes branch? There was a -l related fix there already. I'm on holiday right now so it's tricky to check myself at the moment.

**Comment by ralight** [comment]
A fix is in the `fixes` branch now, I'm not entirely sure about other behaviour though.

**Comment by marwatk** [comment]
Sorry, must have missed the first email. Is there anything you'd still like
tested?

**Comment by ralight** [comment]
The fix is related to a previous commit that was fixing some -l messages not being sent at QoS > 0. I think it was just the final message not being sent. It all looks fine to me, but if you are able to confirm you get the behaviour you expect it would be nice to hear.
