### ISSUE TITLE
Mqtt fails to start on boot, manual start needed

### ISSUE THREAD

**Issue by waldorffsmama** [eclipse/mosquitto#1305]
Hello,
Sorry for not being able to figure it out myself although I went through a lot of threads with similar issues. None really seemed to apply to the one I encountered. So here it is:

When booting the Raspberry Pi with Stretch, Mqtt will not start. A manual start with "mosquitto -d" works, though. So I checked mosquitto.service with "sudo systemctl status mosquitto.service"

> ● mosquitto.service - Mosquitto MQTT v3.1/v3.1.1 Broker
>    Loaded: loaded (/lib/systemd/system/mosquitto.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Mon 2019-06-03 23:41:18 AKDT; 1min 3s ago
>      Docs: man:mosquitto.conf(5)
>            man:mosquitto(8)
>   Process: 541 ExecStart=/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf (code=exited, status=1/FAILURE)
>  Main PID: 541 (code=exited, status=1/FAILURE)
> 
> Jun 03 23:41:17 RaspiCNXHome systemd[1]: mosquitto.service: Unit entered failed state.
> Jun 03 23:41:17 RaspiCNXHome systemd[1]: mosquitto.service: Failed with result 'exit-code'.
> Jun 03 23:41:18 RaspiCNXHome systemd[1]: mosquitto.service: Service hold-off time over, scheduling restart.
> Jun 03 23:41:18 RaspiCNXHome systemd[1]: Stopped Mosquitto MQTT v3.1/v3.1.1 Broker.
> Jun 03 23:41:18 RaspiCNXHome systemd[1]: mosquitto.service: Start request repeated too quickly.
> Jun 03 23:41:18 RaspiCNXHome systemd[1]: Failed to start Mosquitto MQTT v3.1/v3.1.1 Broker.
> Jun 03 23:41:18 RaspiCNXHome systemd[1]: mosquitto.service: Unit entered failed state.
> Jun 03 23:41:18 RaspiCNXHome systemd[1]: mosquitto.service: Failed with result 'exit-code'.
> 

Here is the conf.d:

> pid_file /var/run/mosquitto.pid
> 
> persistence true
> persistence_location /var/lib/mosquitto/
> 
> log_dest topic
> 
> 
> log_type error
> log_type warning
> log_type notice
> log_type information
> 
> connection_messages true
> log_timestamp true
> 
> include_dir /etc/mosquitto/conf.d
> 
> allow_anonymous false
> password_file c:\mosquitto\passwordfile
>

Any pointer available?

**Comment by ralight** [comment]
My bet is that you've tried to use a Windows path for the password file, and it doesn't exist.

**Comment by waldorffsmama** [comment]
Awesome! Thanks so much for taking the time to have a look into this mess of a noob and sorting it out! That was it. Not sure how this got in there. 

Thanks again!
