### ISSUE TITLE
Publish on topic from outside the MQTT-SN gateway

### ISSUE THREAD

**Issue by jelalanne** [eclipse/mosquitto#1306]
Hi,
I'm trying to publish a message on a specific topic directly on mosquitto (using mosquitto_pub), and I want it to be transfered to the MQTT-SN gateway's client which is subscribed to that topic.
My architecture is as followed:
Device <-{Thread network}-> Gateway (uses specific network interface wpan0) <-> TLS mosquitto <-> {other}

I have tried to use mosquitto_pub to publish on the gateway from that {other} segment, but it's not transmited to the Device.

Thanks!

**Comment by ralight** [comment]
Does a mosquitto_sub client subscribed to the appropriate topic on the broker receive the message? If it does, then the problem is with the gateway and you'll need to ask somewhere else for help :)

**Comment by jelalanne** [comment]
Yes it receives it, no problem with that.
I've just made few tests, and it appears that it works with iot.eclipse.org broker, but not my local one

**Comment by jelalanne** [comment]
I can't remember, it's been a while! Lets close it
