### ISSUE TITLE
How to deal with the problem "This feature is  not supported"

### ISSUE THREAD

**Issue by realgsg** [eclipse/mosquitto#1309]
I use mosquitto v1.6.2. When the function mosquitto_loop_start is called, it returns MOSQ_ERR_NOT_SUPPORTED. The connection will be established, but my code can not process subscription messages.

```
int CMainFrame::ConnectMQTT()
{
	char *host = "localhost";
	int port = 1883;
	int keepalive = 60;
	int ret = 0;

	ret = mosquitto_lib_init();
	mosq = mosquitto_new("abc123", true, NULL);
	if (!mosq) {
		Log("Error: Out of memory.");
		return CNC_FAIL;
	}

	mosquitto_username_pw_set(mosq, "gsg", "123");

//	mosquitto_reconnect_delay_set(mosq, 3, 60, true);
//	mosquitto_log_callback_set(mosq, my_log_callback);
//	mosquitto_connect_callback_set(mosq, my_connect_callback);
//	mosquitto_message_callback_set(mosq, my_message_callback);
//	mosquitto_subscribe_callback_set(mosq, my_subscribe_callback);

//	if (mosquitto_connect(mosq, host, port, keepalive)) {
	if (mosquitto_connect_async(mosq, host, port, keepalive)) {
		Log("Unable to connect.");
		return CNC_FAIL;
	}

//	mosquitto_loop_forever(mosq, -1, 1);
	ret = mosquitto_loop_start(mosq);
	if (ret != MOSQ_ERR_SUCCESS)
	{
		Log("mosquitto loop error");
		return CNC_FAIL;
	}

	bMqttConnected = true;

	return CNC_OK;
}
```

**Comment by karlp** [comment]
what platform are you on? does your platform support multithreading?

**Comment by ralight** [comment]
The Windows binaries aren't compiled with threading support enabled because pthreads-win32 is problematic because I've had issues with it functionally, and because distributing it is complicated in the context of an Eclipse project.

If you want to compile it yourself to add in support I could give you some pointers, with the caveat that I have had problems with it before like I've said.

**Comment by Laro88** [comment]
@realgsg On windows (mosquittopp) I ended doing something like this (c++ 11), this is roughly the run method for a c++ thread, shutting down nicely is a bitch in some cases.

```
void wrappermosquittopp::runLoop()
{
	while(m_isalive && _controlledBlowupFromDestructor == false)  //set elsewhere for a graceful shutdown
	{
		try
		{
			if(m_IsConnected) //are (or do we at least think :-) - that we have conn to mqtt server
			{
				std::lock_guard<std::mutex> guard(mutexmqtt);
				int rc = loop(0, 1);
				handleError(rc, "run_loop"); //ok, lets handle errorcode (!0) nicely if possible
			}

			using namespace std::chrono_literals;
			std::this_thread::sleep_for(10ms);
		}
		catch(const std::exception& e)     
		{
			logger->error(e.what());
		}
		catch(...)
		{
			logger->error("Unspecific exception occurred");
		}
	}
}
```

**Comment by realgsg** [comment]
First of all, thank you for your attention and reply.Due to the rush of time, I switched to another MQTT Library in my project.
 @ralight  If I use mosquitto Library in the future, I hope I can get your help.
