### ISSUE TITLE
Feature request: Specify bridge interface

### ISSUE THREAD

**Issue by beville** [eclipse/mosquitto#1311]
I'm pretty sure this isn't a feature yet, so calling it a feature request.

We have a Linux device where we use mosquitto to connect to a remote broker over a cell modem connection.  There are occasions (testing, installation) where other interfaces exist when mosquitto starts up, and it uses the wrong interface to connect to the remote broker.

It would be nice to have an option similar to "bind_interface", but specifically for the bridge interface.

Thanks!

**Comment by ralight** [comment]
Sounds like a reasonable request to me.

**Comment by ralight** [comment]
This will be part of 2.0 with `bridge_bind_address`.
