### ISSUE TITLE
Disable retained flag on bridged messages to AWS

### ISSUE THREAD

**Issue by Curley-Joe** [eclipse/mosquitto#1312]
I need a way to retain messages on the local broker, but clear the retained flag when those messages are bridged to AWS, because AWS will disconnect if the retained flag is set.

**Comment by Assar63** [comment]
> I need a way to retain messages on the local broker, but clear the retained flag when those messages are bridged to AWS, because AWS will disconnect if the retained flag is set.

One way is to do a short program that listens to those locally retained topics and republish them with a slightly different topic without the retained flag. Also set up the bridge to only expose those tweaked topics.

**Comment by Curley-Joe** [comment]
Yeah, I can write my own bridge, which is what I ended up doing.

But AWS IOT is sort of a big deal, and a lot of people want to bridge to it, so it would be nice if it were easier.

**Comment by Assar63** [comment]
My proposed way is the quick and easy way.
The extended way would be to add a feature to mosquitto:
* In bridge configuration add a flag "bridge_protocol_conformity" which might for instance might use retain-prohibit

**Comment by Curley-Joe** [comment]
It would have been quick and easy if I had been only bridging a single topic, but to bridge multiple topics I have to run the mosquitto_pub executable for each message, which is kind of slow.

**Comment by ralight** [comment]
This could be achieved with a new `retain_as_published` option. If true, then the retain would be set as the publishing client set, otherwise it would only be set on already existing retained messages when a subscription was made.

**Comment by stolstov** [comment]
https://github.com/eclipse/mosquitto/commit/2af260ba58afc4055bbbc3710f8662dcec92ff22

**Comment by ralight** [comment]
Closing, this is supported in `bridge_outgoing_retain` option which will be in 2.0.
