### ISSUE TITLE
How do you match the topics by regex right now?

### ISSUE THREAD

**Issue by SeppPenner** [eclipse/mosquitto#1317]
I wanted to know if there is a generic regex for MQTT topic validation. I did only find some `old-regex.txt` and do not know it it's the correct one?

**Comment by ralight** [comment]
Regexes just complicate things here to be honest. If you want to validate a topic, then check whether it is valid UTF-8 and whether it contains a `+` or `#` if it is a topic for publishing and you are done.

**Comment by SeppPenner** [comment]
Well, I wanted to check whether a user has the right to access a topic or not. (Sure, you can specify every topic explicitely, but that's not the idea)...

**Comment by SeppPenner** [comment]
@ralight To verify if a user has the rights to access a topic by checking it against a list of valid topics:

Would it be ok to replace the `#` by a regex allowing all UTF-8 chars and `+` by a regex allowing all UTF-8 chars without `\`?

I will provide an example:

|Topic on the broker|Topic in the validation list|Regex used (in the validation list)|
|-|-|-|
|`a/b/c/d/something`|`a/b/#`|`a/b/{someRegexUtf8}`|
|`a/b/c`|`a/b/+`|`a/b/{someRegexUtf8WithoutSlash}`|

**Comment by SeppPenner** [comment]
I'm right now doing it like this:

```csharp
/// <summary>
/// A class to test the topics accoridng to the regex provided.
/// </summary>
public static class TopicChecker
{
    /// <summary>
    /// Does a regex check on the topics.
    /// </summary>
    /// <param name="allowedTopic">The allowed topic.</param>
    /// <param name="topic">The topic.</param>
    /// <returns><c>true</c> if the topic is valid, <c>false</c> if not.</returns>
    public static bool Test(string allowedTopic, string topic)
    {
        var realTopicRegex = allowedTopic.Replace(@"/", @"\/").Replace("#", @"[a-zA-Z0-9 \/_+.-]*").Replace("+", @"[a-zA-Z0-9 _.-]*");
        var regex = new Regex(realTopicRegex);
        var matches = regex.Matches(topic);

        foreach (var match in matches.ToList())
        {
            if (match.Value == topic)
            {
                return true;
            }
        }

        return false;
    }
}
```

**Comment by ralight** [comment]
This is the code I use: https://github.com/eclipse/mosquitto/blob/master/lib/util_topic.c#L138

Only allowing the characters you suggest is a huge compromise. Topics can contain just about any UTF-8 character.

**Comment by SeppPenner** [comment]
> This is the code I use: https://github.com/eclipse/mosquitto/blob/master/lib/util_topic.c#L138

Thanks, I will check it.

> Only allowing the characters you suggest is a huge compromise. Topics can contain just about any UTF-8 character.

Technically, you're absolute right. But please consider two things:

1. Just because it's possible, doesn't mean you should necessarily do it. From https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/ (I know, concurrence product):
* Never use a leading forward slash
* Never use spaces in a topic
* Keep the topic short and concise
* Use only ASCII characters, avoid non printable characters
* Embed a unique identifier or the Client Id into the topic
* Use specific topics, not general ones
And I totally agree with them. In my opinion a topic name like `ñç¼© ± ` or similar doesn't make sense at all... (Yes, it even contains two non-printable chars).
2. The regex can be extended and customized.

But thanks again for the code, I will check it and give it a try.

**Comment by SeppPenner** [comment]
I have moved your code now to C# code: https://gist.github.com/SeppPenner/17be9fc44b0605619d4b2eefa7f1f105.

I have a few questions regarding topics and there matchings:

|Valid topic|Topic to match|Result of the function|Remark|
|-|-|-|-|
|`a/#`|`a/+`|`false`|In my opinion this is wrong.|
|`a/#`|`a/#/a/#/b`|`false`|Is the topic to match even valid?|
|`a/#`|`a/#/+/a/+/#`|`false`|Is the topic to match even valid?|
|`a/#`|`a/+/+/a`|`false`|Is the topic to match even valid?|
|`a/#`|`a/#/a`|`false`|Is the topic to match even valid?|
|`a/#`|`a/+/a`|`false`|In my opinion this is wrong.|
|`a/#`|`a/#/+/a/+/#`|`false`|Is the topic to match even valid?|

Are there any specific rules for the use of wildcard characters in general? I didn't find that much on this topic.

**Comment by ralight** [comment]
Rules on wildcards - you're best off looking at the mqtt spec.

The reason the function doesn't do what you expect, is because you're doing something different. My function (make sure you follow the license if you're copying) checks whether a topic, which is where a message is published to and can never contain a wildcard, matches against a topic filter, which may contain wildcards, and is used in subscriptions. Topics and topic filters look similar, but are different. It looks like you are trying to match two topic filters, which is a whole other subject.

**Comment by SeppPenner** [comment]
> Rules on wildcards - you're best off looking at the mqtt spec.

I have already found some information on this, thanks.

> The reason the function doesn't do what you expect, is because you're doing something different. My function (make sure you follow the license if you're copying) checks whether a topic, which is where a message is published to and can never contain a wildcard, matches against a topic filter, which may contain wildcards, and is used in subscriptions. Topics and topic filters look similar, but are different. It looks like you are trying to match two topic filters, which is a whole other subject.

Ah okay, I didn't know that there is a difference between topic and topic filter. I have added the license information to the snippet.

Just another question (Sorry for disturbing you again...): Do you by any chance have a matching function for two topic filters, too? This would be what I need for my project...
