### ISSUE TITLE
Mosquitto 4.1+ Hassio integration failure - only on Google WiFi network ?

### ISSUE THREAD

**Issue by c3reeman** [eclipse/mosquitto#1319]
Hi hoping some one can help and point me in the right direction, I run a google WiFi wired mesh network with a couple of network switches, I don’t  Get any connectivity problems with anything on my network apart from recently when I upgrade Mosquitto in Hassio above 4.0 I get problems.... Hassio discovers it in integrations section but when ever I press to connect I get an error “ unable to connect to broker” I have noted that mqtt explorer also regularly connects and disconnects.

First thought initially was this was a home assistant configuration error, but it’s not it’s defiantly a networking issues of some kind I’ve proved this by trying mqtt integration on a fresh Hassio install and I get the same error, I’ve also tested my install and recently setup a friend with Hassio on different networks and encountered  zero errors and everything worked. Reverting my mqtt back to 4.0 in Hassio and configuring mqtt in the configuration.yaml instead of the Hassio integration option I find everything works once again 

Look forward to anyone who can help me with this I’ve been well and truly stumped for weeks

**Comment by ralight** [comment]
Sorry this hasn't been answered before, but I think this is a Hassio issue and you'd be better off asking there.
