### ISSUE TITLE
Status of mosquitto_db_dump and mosquitto_db version 5

### ISSUE THREAD

**Issue by ckrey** [eclipse/mosquitto#1320]
Since 1.6.x mosquitto uses DB version 5 for the `mosquitto_db` persistence file.

Unfortunately, the utility `mosquitto_db_dump` does not process version 5 files. 

```
mosquitto_db_dump mosquitto.db
Mosquitto DB dump
CRC: 0
DB version: 5
Warning: Unsupported chunk "0" in persistent database file. Ignoring.
```

Do you plan to upgrade `mosquitto_db_dump`? I would volunteer to help
. Or will the utility become obsolete with the persistence API announced for mosquitto 2.0?

**Comment by ralight** [comment]
I do intend to upgrade it. It should be easier now to do so now, the reading functions are split out from the other persistence code so it shouldn't be necessary to maintain a separate set of functions in db_dump.c.

**Comment by ralight** [comment]
This should be working now.

**Comment by ckrey** [comment]
Thanks @ralight works now.

 You may want to eliminate some of the debug output in `--client-stats`:

```
...
ADD msgs 97429804
ADD msgs 97429731
ADD msgs 71387105
FOUND xyz
FOUND xyz
FOUND S abc
FOUND S abc
...
```

**Comment by ralight** [comment]
Ah, oops. Sorted now thanks.
