### ISSUE TITLE
Is there an option to match two topic filters?

### ISSUE THREAD

**Issue by SeppPenner** [eclipse/mosquitto#1324]
As already discussed here: https://github.com/eclipse/mosquitto/issues/1317:

@ralight: Do you have some function to check for two topic filters if they match?

**Comment by ralight** [comment]
I'm afraid not.

**Comment by SeppPenner** [comment]
Ok, thanks. I will check if I can add this functionality to your function^^

**Comment by SeppPenner** [comment]
Another short question: Is the usage and the licensing ok in the project: https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfigHashedPasswords#further-information and https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfigHashedPasswords/blob/9bb5111a014f308d9929db3cd3ee18f4994ef4ad/NetCoreMQTTExampleJsonConfigHashedPasswords/TopicChecker.cs#L35?
