### ISSUE TITLE
Wrong will recvice

### ISSUE THREAD

**Issue by mofywong** [eclipse/mosquitto#1327]
Hello,
I have a program in project. Simplified scene such as below：
It has two client we call ca and cb, and connect to the same broker. the two client has all set its persistence will with topic v1/ca/sts and v1/cb/sts, and subscribe each othre topic。application running normal under normal circumstances, but it happen some probrem when i find in log. ca recive the cb's will but the on_disonnect function not been callback in ca. So ca always thinks it is online, the application run in error status.
I don't know how this program can happen, and it's has appeared twice。
I use the mosquitto lib and mosquitto broker version are 1.5.3.

**Comment by ralight** [comment]
Are you able to post some example code? It's very difficult to say what could be happening from your description I'm afraid.

**Comment by mofywong** [comment]
@ralight Sorry，I think It's a bug in my process that the on_message callback has been blocking, it's my wrong and I have resolve it. Thank you for your reply!

**Comment by ralight** [comment]
Great, I'm glad you got it sorted.
