### ISSUE TITLE
max_inflight_messages=1 broken on Mosquitto-1.6.3

### ISSUE THREAD

**Issue by xmas79** [eclipse/mosquitto#1332]
Hello,
it seems that **max_inflight_messages=1** is broken on the new mosquitto-1.6.3 broker implementation. A client (tried with mosquitto_pub v1.6.3 and older releases as well) publishing messages with **QoS2** to a such configured broker will just stuck waiting for a reply.

As I understand it, the problem seems related to outgoing QoS quota being decremented for the **CONNACK** packet, leaving the broker without any quota left for answering subsequent requests. 

A simple "dialogue" between a broker and a client:

**Log from Mosquitto Broker:**
```
1562328636: New connection from 192.168.0.87 on port 1883.
1562328636: New client connected from 192.168.0.87 as mosquitto_pub (p2, c1, k60).
1562328636: No will message specified.
1562328636: Sending CONNACK to mosquitto_pub (0, 0)
1562328636: Received PUBLISH from mosquitto_pub (d0, q2, r0, m1, 'test', ... (5 bytes))
1562328696: Received PINGREQ from mosquitto_pub
1562328696: Sending PINGRESP to mosquitto_pub
```

**Log from mosquitto_pub:**
```
mosquitto_pub -h 192.168.0.88 -t "test" -q 2 -d -m "hello" -i "mosquitto_pub"
Client mosquitto_pub sending CONNECT
Client mosquitto_pub received CONNACK (0)
Client mosquitto_pub sending PUBLISH (d0, q2, r0, m1, 'test', ... (5 bytes))
Client mosquitto_pub sending PINGREQ
Client mosquitto_pub received PINGRESP
```

**Comment by ilovemilk** [comment]
I have the same problem. The issue also exists in version 1.6.2.

**Comment by ralight** [comment]
Thanks for the reports both, I believe this is now fixed in the `fixes` branch.
