### ISSUE TITLE
arm64 snap?

### ISSUE THREAD

**Issue by anonymouse64** [eclipse/mosquitto#1335]
The snap is not currently published for arm64, but the debian package is available for arm64, is it possible to get the snap built for arm64 as well?

**Comment by ryanjyoder** [comment]
I forked this repo and it built with zero changes on build.snapcraft.io for all architectures.

+1 for arm64 (just got my pi4 :)

**Comment by ralight** [comment]
I've now got the snap building on all architectures. @ryanjyoder are you planning on keeping your snap up to date, or make it different to the official snap in any way?

**Comment by anonymouse64** [comment]
Thanks @ralight

**Comment by ryanjyoder** [comment]
@ralight No, it was just a test to estimate the work needed to build on arm64. In fact I'll delete it to eliminate any confusion. Thanks for this! I'll trying it out this weekend :D

**Comment by ralight** [comment]
Thanks @ryanjyoder , I was hoping you'd say something like that.
