### ISSUE TITLE
test.mosquitto.org server specifications

### ISSUE THREAD

**Issue by kaushalkumarjoshi** [eclipse/mosquitto#1338]
Hi,

Can you please let me know the hardware specifications for the server running mosquitto at test.mosquitto.org?

Best Regards

**Comment by ralight** [comment]
It's an Atom N2800 with 2GB RAM.

**Comment by kaushalkumarjoshi** [comment]
Hi Roger,

Searched over Internet and not able to find proper information. I hope you can help me with this:
"How much TCP/IP connections are supported simultaneously on Mosquitto?
For your machine configuration, how many MQTT clients have connected simultaneously?
Is there any rule to link RAM and hardware to no. of TCP/IP(MQTT) connections?"

Best Regards,
Kaushal
