### ISSUE TITLE
mosquitto_sub, please provide a way to print hex payload

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto#134]
migrated from Bugzilla [#464458](https://bugs.eclipse.org/bugs/show_bug.cgi?id=464458)
status RESOLVED severity *normal* in component *Mosquitto clients* for *1.5*
Reported in version *1.4* on platform *PC*
Assigned to: Roger Light

On 2015-04-12 04:48:07 -0400, Gianfranco Costamagna wrote:

> As in the subject, I really would like to have a way to print the received content in hex format.
> 
> We already patch the source to print the payload, but of course this patch should be cleaned up and a command line option should be provided.
> 
> I'm posting it here to ask for your best opinion on this.
> 
> diff --git a/client/sub_client.c b/client/sub_client.c
> index 3c6c225..e7331c5 100644
> --- a/client/sub_client.c
> +++ b/client/sub_client.c
> @@ -17,6 +17,7 @@ Contributors:
>  #include <assert.h>
>  #include <errno.h>
>  #include <stdio.h>
> +#include <stdint.h>
>  #include <stdlib.h>
>  #include <string.h>
>  #ifndef WIN32
> @@ -38,6 +39,7 @@ void my_message_callback(struct mosquitto *mosq, void *obj, const struct mosquit
>         struct mosq_config *cfg;
>         int i;
>         bool res;
> +       uint8_t* payload=message->payload;
> 
>         if(process_messages == false) return;
> 
> @@ -59,6 +61,10 @@ void my_message_callback(struct mosquitto *mosq, void *obj, const struct mosquit
>                         if(cfg->eol){
>                                 printf("\n");
>                         }
> +                       fprintf(stdout,"Start payload: len=%d\n",message->payloadlen);
> +                       for (i = 0; i < message->payloadlen; i++)
> +                               fprintf(stdout,"%02X ", payload[i]);
> +                       fprintf(stdout,"\nEnd payload.\n\n");
>                 }else{
>                         if(cfg->eol){
>                                 printf("%s (null)\n", message->topic);
> @@ -72,6 +78,10 @@ void my_message_callback(struct mosquitto *mosq, void *obj, const struct mosquit
>                                 printf("\n");
>                         }
>                         fflush(stdout);
> +                       fprintf(stdout,"Start payload: len=%d\n",message->payloadlen);
> +                       for (i = 0; i < message->payloadlen; i++)
> +                               fprintf(stdout,"%02X ", payload[i]);
> +                       fprintf(stdout,"\nEnd payload.\n\n");
>                 }
>         }
>         if(cfg->msg_count>0){
> 
> 
> of course you have my complete permission to take apply or do whatever you prefer with the patch.
> 
> cheers,
> 
> G.

On 2015-04-17 17:05:34 -0400, Roger Light wrote:

> Thanks, I've committed a change to implement this.

On 2015-04-18 04:34:02 -0400, Gianfranco Costamagna wrote:

> thanks a lot, can you please push it on git? I'll be happy to test it :)

**Comment by SurenMJ** [comment]
Hi ralight,
In the latest mosquitto version 1.4.14, i didn't get option to format the payload in 'mosquitto_sub'. If this fix is not merged, can I get the beta version of it?

Thanks,
Surendra
