### ISSUE TITLE
Support for Unix domain sockets on Linux

### ISSUE THREAD

**Issue by fpagliughi** [eclipse/mosquitto#1341]
More and more I'm using Mosquitto as a central message bus on Embedded Linux devices and/or using clients running on the same Linux server back-end as the broker. It would be awesome to get the performance boost that Unix-domain sockets would provide in these situations, and I can't imagine that it would be too difficult to implement.

Would a PR doing this be accepted? Any hints on where to start or possible gotcha's.

**Comment by karlp** [comment]
Consider https://github.com/eclipse/mosquitto/pull/467 first.  (ie, you'll need to provide strong justification to outweigh the prior discussions on this, with metrics)

**Comment by fpagliughi** [comment]
Ah. Apologies. I searched for the topic, but must have been looking at open issues...
That's interesting. I am maintaining a number of products on old 2.6 kernels. But I hadn't benchmarked the performance on new ones. I'll look closer at it.
