### ISSUE TITLE
Mosquitto Bridge Socket Error

### ISSUE THREAD

**Issue by jeroenst** [eclipse/mosquitto#1343]
When connecting to a bridge (test.mosquitto.org and io.afafruit.com) the connection fails:

```
1562942622: Connecting bridge (step 1) mybridge (test.mosquitto.org:1883)
1562942622: Connecting bridge (step 2) mybridge (test.mosquitto.org:1883)
1562942622: Bridge server.mybridge sending CONNECT
1562942622: Socket error on client local.server.mybridge, disconnecting.
```

Issue happens on V1.4.10, V1.4.15, V1.5.7, V1.6.3 and current master (a5620d9d554cb1b28799eb0491336b53265b6a24)

This is the  config :
```
connection mybridge
address test.mosquitto.org
topic test out 0
```

**Comment by ralight** [comment]
I've just tried all of those versions with your config and they all work fine. I've tried on ubuntu 19.04 and 16.04. Do you have any details of your system and how you built mosquitto?

**Comment by jeroenst** [comment]
I use ubuntu 18.04.2 LTS.

I build mosquitto just by running make...

I attached the build and run log.

[build and run log mosquitto.txt](https://github.com/eclipse/mosquitto/files/3432027/build.and.run.log.mosquitto.txt)

**Comment by ralight** [comment]
I don't think the problem is your end. Some helpful person has connected as many clients to test.mosquitto.org as they can from a single ip - thousands of clients - and has hit the limit of open sockets set on that instance. I've blocked them so you should be able to connect now.

**Comment by jeroenst** [comment]
It seems to work now...

1564074287: Bridge local.server.mybridge doing local SUBSCRIBE on topic test
1564074287: Connecting bridge mybridge (test.mosquitto.org:1883)
1564074287: Bridge server.mybridge sending CONNECT
1564074287: Received CONNACK on connection local.server.mybridge.
1564074287: Bridge local.server.mybridge sending UNSUBSCRIBE (Mid: 2, Topic: test)
1564074287: Received PUBACK from local.server.mybridge (Mid: 1, RC:0)
1564074287: Received UNSUBACK from local.server.mybridge

But I have the same problem on io.adafruit.com:

1564074414: Bridge local.server.mybridge doing local SUBSCRIBE on topic test
1564074414: Connecting bridge mybridge (io.adafruit.com:8883)
1564074414: Bridge server.mybridge sending CONNECT
1564074414: Socket error on client local.server.mybridge, disconnecting.

Here is the config:
connection mybridge
remote_username secretuser
remote_password secretkey
address io.adafruit.com:8883
topic test out 0

Here is the logging (listen socket on port 1000 preventing clients log):
1564074537: mosquitto version 1.6.3 starting
1564074537: Config loaded from ../mosquitto.conf.
1564074537: Opening ipv4 listen socket on port 1000.
1564074537: Opening ipv6 listen socket on port 1000.
1564074537: Bridge local.server.mybridge doing local SUBSCRIBE on topic test
1564074537: Connecting bridge mybridge (io.adafruit.com:8883)
1564074537: Bridge server.mybridge sending CONNECT
1564074538: Socket error on client local.server.mybridge, disconnecting.

**Comment by ralight** [comment]
Ah yes - adafruit doesn't support the non-standard bridge mode. Please add this line below your `connection` part:

```
try_private false
```

**Comment by jeroenst** [comment]
Ok, I tried that, but no success...

My Config:
```connection mybridge
try_private false
remote_username jeroensteenhuis
remote_password 149b1607250d490eb12999d4802d1f66
address io.adafruit.com:8883
topic test out 0
listener 8888
```


Mosquitto Log:
```1564119356: mosquitto version 1.6.3 starting
1564119356: Config loaded from ../mosquitto.conf.
1564119356: Opening ipv4 listen socket on port 8888.
1564119356: Opening ipv6 listen socket on port 8888.
1564119356: Bridge local.server.mybridge doing local SUBSCRIBE on topic test
1564119356: Connecting bridge mybridge (io.adafruit.com:8883)
1564119356: Bridge server.mybridge sending CONNECT
1564119357: Socket error on client local.server.mybridge, disconnecting.
^C1564119357: mosquitto version 1.6.3 terminating
```

**Comment by jeroenst** [comment]
Thank you very much for helping out!

Closing (configuration) issue.
