### ISSUE TITLE
mosquitto_rr protocol error

### ISSUE THREAD

**Issue by HowJMay** [eclipse/mosquitto#1344]
**platform**
Ubuntu 16.04

I built `rr_client` on my local machine and once I ran it, I met protocol error.
error message: `Error: A network protocol error occurred when communicating with the broker.
`
All of the other clients worked fine on my machine.
I used the following command `mosquitto_rr  -h <IP> -t <topic> -m <message> -e <response_topic>`
Did I do something wrong with the command?

**Comment by ralight** [comment]
The problem is most likely because you are connecting to a broker that does not have MQTT v5 support. `mosquitto_rr` only works with MQTT v5.

**Comment by ralight** [comment]
I've changed things so the error message is clearer now. If you spot anything thing else like this that could do with better explanation please post another issue. Thanks for reporting this one!
