### ISSUE TITLE
Duplicate client id subscribed on different topic receive wrong messages.

### ISSUE THREAD

**Issue by dankhan-adl** [eclipse/mosquitto#1348]
I am using the same client id to subscribe to two different topics on the same broker with clean session disabled.   

    mosquitto_sub -h xx.xx.xx.xx -p 1883 -d -c -i '123' -q 2 -t TP1

and 

    mosquitto_sub -h xx.xx.xx.xx -p 1883 -d -c -i '123' -q 2 -t TP2

When published on both topics I receive messages of topic TP1 on topic TP2  

    mosquitto_pub -h xx.xx.xx.xx -p 1883 -q 2 -t TP1 -m "Topic 1"
    mosquitto_pub -h xx.xx.xx.xx -p 1883 -q 2 -t TP2 -m "Topic 2" 

I see the debug results printed on terminal. It seems like subscribers are disconnecting and reconnecting, as using the same client id results in this behaviour. Is the behaviour is same even if I subscribe to different topic?

**Comment by karlp** [comment]
connecting with cleansession=false and a fixed clientid will disconnect the existing client.  mosquitto_sub has reconnect logic, so yes, you're just going to be bouncing back and forth.   What are you actually trying to do?

**Comment by dankhan-adl** [comment]
> connecting with cleansession=false and a fixed clientid will disconnect the existing client. mosquitto_sub has reconnect logic, so yes, you're just going to be bouncing back and forth. What are you actually trying to do?

I was trying to create a single client and then subscribe it to different topics. But seems like it is not possible with command line options. I am going to write a C program using `libmosquitto`  and see if I can subscribe a client to multiple topics.

**Comment by karlp** [comment]
just use mutiple -t arguments.read the help :)
```
 -t : mqtt topic to subscribe to. May be repeated multiple times.
```

**Comment by dankhan-adl** [comment]
> just use mutiple -t arguments.read the help :)
> 
> ```
>  -t : mqtt topic to subscribe to. May be repeated multiple times.
> ```

Holy cow! Thanks. I am closing it.
