### ISSUE TITLE
undefined reference to `SSL_CTX_set_alpn_protos'

### ISSUE THREAD

**Issue by guoyanzhang0817** [eclipse/mosquitto#1349]
**cc  -L../lib pub_client.o pub_shared.o client_shared.o client_props.o -o mosquitto_pub  ../lib/libmosquitto.so.1
../lib/libmosquitto.so.1: undefined reference to `SSL_CTX_set_alpn_protos'**

how to solve it ？

**Comment by dellelce** [comment]
Are you linking manually !?  If so you are missing `-lssl` 
If you are not linking manually and not missing `-lssl` probably you need to update the version of openssl you have.

**Comment by guoyanzhang0817** [comment]
> Are you linking manually !? If so you are missing `-lssl`
> If you are not linking manually and not missing `-lssl` probably you need to update the version of openssl you have.

ok，maybe it need at least 1.1.0k, thanks.
