### ISSUE TITLE
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_num'

### ISSUE THREAD

**Issue by guoyanzhang0817** [eclipse/mosquitto#1350]
cc  -L../lib pub_client.o pub_shared.o client_shared.o client_props.o -o mosquitto_pub  ../lib/libmosquitto.so.1
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_num'
../lib/libmosquitto.so.1: undefined reference to `SSL_CTX_up_ref'
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_pop_free'
../lib/libmosquitto.so.1: undefined reference to `SSL_CTX_set_alpn_protos'
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_value'
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_init_crypto'
../lib/libmosquitto.so.1: undefined reference to `SSL_CTX_set_options'
../lib/libmosquitto.so.1: undefined reference to `TLS_client_method'
../lib/libmosquitto.so.1: undefined reference to `ASN1_STRING_get0_data'
----------------------------
root@ab8021002cab:/data/mosquitto-master/mosquitto-master# openssl version
OpenSSL 1.1.0k  28 May 2019

hi, how to solve it ?

**Comment by ralight** [comment]
Can you give any more details about your build environment? Is openssl 1.1.0 the only version of openssl installed?

**Comment by Hapoa** [comment]
You should give your libmosquitto version. I think it's your openssl version's problem. If you are using the latest libmosquitto, you can try openssl 1.1.1.

And these links will help you.

<https://github.com/Hapoa/personal-notes/blob/master/openssl/openssl%20%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85.md>

<https://github.com/Hapoa/personal-notes/blob/master/mqtt/%E7%BC%96%E8%AF%91%20libmosquitto.md>

**Comment by FernandoGarcia** [comment]
Hi!

I'm facing the same problem with Ubuntu 14.04 and develop branch.

**$ make**
```
.
.
.
cc  -L../lib pub_client.o pub_shared.o client_shared.o client_props.o -o mosquitto_pub  ../lib/libmosquitto.so.1
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_num'
../lib/libmosquitto.so.1: undefined reference to `SSL_CTX_up_ref'
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_pop_free'
../lib/libmosquitto.so.1: undefined reference to `SSL_CTX_set_alpn_protos'
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_value'
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_init_crypto'
../lib/libmosquitto.so.1: undefined reference to `SSL_CTX_set_options'
../lib/libmosquitto.so.1: undefined reference to `TLS_client_method'
../lib/libmosquitto.so.1: undefined reference to `ASN1_STRING_get0_data'
collect2: error: ld returned 1 exit status
make[1]: *** [mosquitto_pub] Error 1
make[1]: Leaving directory `/root/new_mosquitto/mosquitto-develop/client'
make: *** [mosquitto] Error 2
```

**$ openssl version**

`OpenSSL 1.1.1  11 Sep 2018`

**$ openssl version -d**

`OPENSSLDIR: "/usr/local/ssl"`

Can someone help me please?

Best regards.

**Comment by mfe-** [comment]
An `undefined reference` error is caused because it didn't found the libary of `openssl`. So you have to give some hints to the linker (LDFLAGS) and the compiler.

I had a similar issue. So I gave the linker some hints, where to look for the openssl lib (which I installed into /usr/local/ssl):

`LDFLAGS="-L/usr/local/ssl/ -L/usr/local/ -L/usr/local/bin/ -Wl,-rpath,/usr/local/ssl/,-rpath,/usr/local/lib/,--export-dynamic" LIBS="-ldl" make WITH_DOCS=no`

Not sure whether its fixed with the current version, but I also ran into during `make` into into `ld cannot find -lssl` 
The problem was that someparts of the MAKEFILE doesn't consider LDFLAGS. Therefore I executed the command manual:  

1. (switch to src folder)
2. execute the command which failed manual. This was for me: `cc  -Wl -L/usr/local/ssl/ -L/usr/local/ssl/lib -L/usr/local/ -L/usr/local/bin/ -Wl,-rpath,/usr/local/ssl/,-rpath,/usr/local/lib/ mosquitto.o alias_mosq.o bridge.o conf.o conf_includedir.o context.o database.o handle_auth.o handle_connack.o handle_connect.o handle_disconnect.o handle_ping.o handle_pubackcomp.o handle_publish.o handle_pubrec.o handle_pubrel.o handle_suback.o handle_subscribe.o handl`
3. run again `make` and the build should be successful

**Comment by huxianguan** [comment]
> ## cc -L../lib pub_client.o pub_shared.o client_shared.o client_props.o -o mosquitto_pub ../lib/libmosquitto.so.1
> ../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_num' ../lib/libmosquitto.so.1: undefined reference to `SSL_CTX_up_ref'
> ../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_pop_free' ../lib/libmosquitto.so.1: undefined reference to `SSL_CTX_set_alpn_protos'
> ../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_value' ../lib/libmosquitto.so.1: undefined reference to `OPENSSL_init_crypto'
> ../lib/libmosquitto.so.1: undefined reference to `SSL_CTX_set_options' ../lib/libmosquitto.so.1: undefined reference to `TLS_client_method'
> ../lib/libmosquitto.so.1: undefined reference to `ASN1_STRING_get0_data'
> root@ab8021002cab:/data/mosquitto-master/mosquitto-master# openssl version
> OpenSSL 1.1.0k 28 May 2019
> 
> hi, how to solve it ?

**Comment by EthsonLiu** [comment]
It failed while generate `mosquitto_pub` exe, because it can't link the right ssl lib.

If you just want the `libmosquitto.so*`, I think you can get them now, you can try search the key word `mosquitto.so` in the current mosquitto root directory.

**Comment by ralight** [comment]
@huxianguan Do you have multiple versions of the openssl library installed? That could cause there to be a confusion.

**Comment by EthsonLiu** [comment]
Maybe I found the solution, just add one line in config.mk,

```
ifeq ($(WITH_TLS),yes)
	BROKER_LDADD:=$(BROKER_LDADD) -lssl -lcrypto
	LIB_LIBADD:=$(LIB_LIBADD) -lssl -lcrypto
	PASSWD_LDADD:=$(PASSWD_LDADD) -lcrypto
	STATIC_LIB_DEPS:=$(STATIC_LIB_DEPS) -lssl -lcrypto
	CLIENT_LDADD:=$(CLIENT_LDADD) -lssl -lcrypto # --->>>>here 
	
	CLIENT_CPPFLAGS:=$(CLIENT_CPPFLAGS) -DWITH_TLS
	BROKER_CPPFLAGS:=$(BROKER_CPPFLAGS) -DWITH_TLS
	LIB_CPPFLAGS:=$(LIB_CPPFLAGS) -DWITH_TLS

	ifeq ($(WITH_TLS_PSK),yes)
		BROKER_CPPFLAGS:=$(BROKER_CPPFLAGS) -DWITH_TLS_PSK
		LIB_CPPFLAGS:=$(LIB_CPPFLAGS) -DWITH_TLS_PSK
		CLIENT_CPPFLAGS:=$(CLIENT_CPPFLAGS) -DWITH_TLS_PSK
	endif
endif
```

CLIENT_LDADD is null, but while exec `client/Makefile`,

```
mosquitto_pub : pub_client.o pub_shared.o client_shared.o client_props.o
	${CROSS_COMPILE}${CC} $(CLIENT_LDFLAGS) $^ -o $@ $(CLIENT_LDADD)

## equal 

mosquitto_pub : pub_client.o pub_shared.o client_shared.o client_props.o
	${CROSS_COMPILE}${CC} $(CLIENT_LDFLAGS) $^ -o $@
```

If you crosscompile, you will get an error like the above, so set CLIENT_LDADD to `-lssl -lcrypto` will be ok.

@ralight Am I right?

**Comment by metalalive** [comment]
Got the similar problem solved today. In my case, I built all OpenSSL libraries & binary file from source (clone the repository from OpenSSL official Github) on my Ubuntu 14.04.

I found that all those built libraries went to `/use/local/lib` after installation , and current version of mosquitto doesn't do extra check & look for potential location of these OpenSSL libraries (`libssl.so` and `libcrypto.so`), that could also lead to the **undefined reference** linking error

Here's what I do instead : 
```
make   WITH_DOCS=no  LDFLAGS="-L/usr/local/lib/  -Wl,-rpath,/usr/local/lib/"
```
the linking error never showed up again.

For those who install OpenSSL using  package management tool (e.g. `apt-get` in Ubuntu) , they might not have such build issue , but I think it would be better to add extra default path to `LDFLAGS `  in `config.mk`, in order to point to correct OpenSSL libraries. (maybe I can help to contribute this to `config.mk` ?)

**Comment by loulansuiye** [comment]
I met the alike problem now ,have any body solve that?

**Comment by loulansuiye** [comment]
/home/xxx//libmosquitto.so: undefined reference to `ENGINE_cleanup'
/home/xxx//libmosquitto.so: undefined reference to `ENGINE_free'
/home/xxx//libmosquitto.so: undefined reference to `SSL_get_peer_cert_chain'
/home/xxx//libmosquitto.so: undefined reference to `SSL_get_ex_new_index'
/home/xxx//libmosquitto.so: undefined reference to `ENGINE_by_id'
/home/xxx//libmosquitto.so: undefined reference to `OCSP_cert_status_str'
/home/xxx//libmosquitto.so: undefined reference to `SSL_CTX_set_default_passwd_cb'
/home/xxx//libmosquitto.so: undefined reference to `OPENSSL_add_all_algorithms_conf'
/home/xxx//libmosquitto.so: undefined reference to `SSL_get_ex_data_X509_STORE_CTX_idx'
/home/xxx//libmosquitto.so: undefined reference to `OCSP_response_get1_basic'
/home/xxx//libmosquitto.so: undefined reference to `SSL_CTX_new'
/home/xxx//libmosquitto.so: undefined reference to `SSL_CTX_use_certificate_chain_file'
/home/xxx//libmosquitto.so: undefined reference to `SSL_CTX_use_PrivateKey'
/home/xxx//libmosquitto.so: undefined reference to `SSL_shutdown'
/home/xxx//libmosquitto.so: undefined reference to `BN_bn2bin'
/home/xxx//libmosquitto.so: undefined reference to `SSL_set_ex_data'
/home/xxx//libmosquitto.so: undefined reference to `OCSP_basic_verify'
/home/xxx//libmosquitto.so: undefined reference to `SSL_get_error'
/home/xxx//libmosquitto.so: undefined reference to `SSL_CTX_ctrl'
/home/xxx//libmosquitto.so: undefined reference to `SSL_get_ex_data'
/home/xxx//libmosquitto.so: undefined reference to `ENGINE_init'
/home/xxx//libmosquitto.so: undefined reference to `ENGINE_finish'
/home/xxx//libmosquitto.so: undefined reference to `SSL_CTX_set_cipher_list'
/home/xxx//libmosquitto.so: undefined reference to `SSL_CTX_load_verify_locations'
/home/xxx//libmosquitto.so: undefined reference to `SSL_set_bio'
/home/xxx//libmosquitto.so: undefined reference to `UI_method_set_reader'
/home/xxx//libmosquitto.so: undefined reference to `sk_pop_free'
/home/xxx//libmosquitto.so: undefined reference to `SSL_CTX_use_PrivateKey_file'
/home/xxx//libmosquitto.so: undefined reference to `ENGINE_load_builtin_engines'
/home/xxx//libmosquitto.so: undefined reference to `UI_destroy_method'
/home/xxx//libmosquitto.so: undefined reference to `SSL_pending'
/home/xxx//libmosquitto.so: undefined reference to `ENGINE_load_private_key'
/home/xxx//libmosquitto.so: undefined reference to `ERR_error_string'
/home/xxx//libmosquitto.so: undefined reference to `SSL_ctrl'
/home/xxx//libmosquitto.so: undefined reference to `SSLv23_client_method'
/home/xxx//libmosquitto.so: undefined reference to `BN_hex2bn'
/home/xxx//libmosquitto.so: undefined reference to `SSL_read'
/home/xxx//libmosquitto.so: undefined reference to `SSL_CTX_set_psk_client_callback'
/home/xxx//libmosquitto.so: undefined reference to `OCSP_crl_reason_str'
/home/xxx//libmosquitto.so: undefined reference to `X509_STORE_CTX_get_error_depth'
/home/xxx//libmosquitto.so: undefined reference to `ERR_free_strings'
/home/xxx//libmosquitto.so: undefined reference to `SSL_load_error_strings'
/home/xxx//libmosquitto.so: undefined reference to `SSL_library_init'
/home/xxx//libmosquitto.so: undefined reference to `SSL_connect'
/home/xxx//libmosquitto.so: undefined reference to `BN_num_bits'
/home/xxx//libmosquitto.so: undefined reference to `EVP_cleanup'
/home/xxx//libmosquitto.so: undefined reference to `X509_get_subject_name'
/home/xxx//libmosquitto.so: undefined reference to `UI_method_get_opener'
/home/xxx//libmosquitto.so: undefined reference to `d2i_OCSP_RESPONSE'
/home/xxx//libmosquitto.so: undefined reference to `UI_method_get_reader'
/home/xxx//libmosquitto.so: undefined reference to `UI_method_set_closer'
/home/xxx//libmosquitto.so: undefined reference to `OCSP_BASICRESP_free'
/home/xxx//libmosquitto.so: undefined reference to `SSL_CTX_set_default_passwd_cb_userdata'
/home/xxx//libmosquitto.so: undefined reference to `SSL_write'
/home/xxx//libmosquitto.so: undefined reference to `SSL_CTX_set_verify'
/home/xxx//libmosquitto.so: undefined reference to `UI_create_method'
/home/xxx//libmosquitto.so: undefined reference to `OCSP_RESPONSE_free'
/home/xxx//libmosquitto.so: undefined reference to `BIO_new_socket'
/home/xxx//libmosquitto.so: undefined reference to `OCSP_resp_count'
/home/xxx//libmosquitto.so: undefined reference to `SSL_free'
/home/xxx//libmosquitto.so: undefined reference to `CONF_modules_unload'
/home/xxx//libmosquitto.so: undefined reference to `SSL_new'
/home/xxx//libmosquitto.so: undefined reference to `sk_num'
/home/xxx//libmosquitto.so: undefined reference to `SSL_CTX_check_private_key'
/home/xxx//libmosquitto.so: undefined reference to `OCSP_check_validity'
/home/xxx//libmosquitto.so: undefined reference to `OCSP_resp_get0'
/home/xxx//libmosquitto.so: undefined reference to `ENGINE_ctrl_cmd'
/home/xxx//libmosquitto.so: undefined reference to `ASN1_STRING_data'
/home/xxx//libmosquitto.so: undefined reference to `SSL_CTX_set_alpn_protos'
/home/xxx//libmosquitto.so: undefined reference to `SSL_CTX_callback_ctrl'
/home/xxx//libmosquitto.so: undefined reference to `GENERAL_NAME_free'
/home/xxx//libmosquitto.so: undefined reference to `RAND_bytes'
/home/xxx//libmosquitto.so: undefined reference to `sk_value'
/home/xxx//libmosquitto.so: undefined reference to `SSL_CTX_get_cert_store'
/home/xxx//libmosquitto.so: undefined reference to `UI_method_set_writer'
/home/xxx//libmosquitto.so: undefined reference to `BN_free'
/home/xxx//libmosquitto.so: undefined reference to `UI_OpenSSL'
/home/xxx//libmosquitto.so: undefined reference to `X509_STORE_CTX_get_ex_data'
/home/xxx//libmosquitto.so: undefined reference to `X509_NAME_get_text_by_NID'
/home/xxx//libmosquitto.so: undefined reference to `X509_get_ext_d2i'
/home/xxx//libmosquitto.so: undefined reference to `SSL_CTX_free'
/home/xxx//libmosquitto.so: undefined reference to `ERR_clear_error'
/home/xxx//libmosquitto.so: undefined reference to `UI_method_get_closer'
/home/xxx//libmosquitto.so: undefined reference to `OCSP_response_status_str'
/home/xxx//libmosquitto.so: undefined reference to `ERR_get_error'
/home/xxx//libmosquitto.so: undefined reference to `ERR_remove_thread_state'
/home/xxx//libmosquitto.so: undefined reference to `OCSP_single_get0_status'
/home/xxx//libmosquitto.so: undefined reference to `X509_STORE_CTX_get_current_cert'
/home/xxx//libmosquitto.so: undefined reference to `UI_method_set_opener'
/home/xxx//libmosquitto.so: undefined reference to `UI_method_get_writer'
/home/xxx//libmosquitto.so: undefined reference to `CRYPTO_cleanup_all_ex_data'
/home/xxx//libmosquitto.so: undefined reference to `CRYPTO_add_lock'
/home/xxx//libmosquitto.so: undefined reference to `OCSP_response_status'

**Comment by ralight** [comment]
@loulansuiye can you provide more details: what are you compiling when the error occurs? How did you compile libmosquitto?

In my experience this only happens with broken build tools, or if the build process has been modified in some way. What OS are you using?

**Comment by ralight** [comment]
Closing because the original issue has been resolved. If the extra issue is still a problem, please feel free to open a new issue.
