### ISSUE TITLE
mosquitto_passwd is not entirely scriptable

### ISSUE THREAD

**Issue by gdt** [eclipse/mosquitto#1352]
mosquitto_passwd(1) explains that one can use -c with a username to 1) create a password file and 2) add that user.  (BTW, It would be nice to have -c just create an empty file, and separate adding a user to a file, but I realize that's hard to change now.)

One can use -b to pass the password on the command line.

However, there does not seem to be a way to both create and use -b at the same time.   Thus if one wants to write a shell script to entirely write the password database, it doesn't seem possible just using mosquitto_passwd.

A workaround is to cp /dev/null to the password file, so obviously this issue is not particularly important.   But it would be nice if -c and -b were accepted together.

**Comment by ralight** [comment]
The command line interface is intended to be compatible with htpasswd, so I agree that `-c` and `-b` should be possible at the same time.

**Comment by ralight** [comment]
This was implemented... some while back. It'll be part of 2.0, so I'm closing this.
