### ISSUE TITLE
did not return a certificate

### ISSUE THREAD

**Issue by sawyerliu** [eclipse/mosquitto#1355]
hello everyone,
  If set "require_certificate false" in .conf file, I think I don't need provide certificate in client end. but if this, the mosquitto server will occur error.
"mosquitto openssl error: error:1417C0C7: SSL routines: tls_procese_client_certificate:peer did not return a certificate"

**Comment by ralight** [comment]
Could you provide an example configuration that shows this behaviour?

**Comment by sawyerliu** [comment]
Hello,
       I am so sorry, it is my mistake. I didn’t modify the .conf file successfully in C:\Program File\mosquitto folder, due to permission.
       Thanks.


Best Regards
Sawyer Liu(刘维峰)

**Comment by ralight** [comment]
Ok, thanks for confirming.
