### ISSUE TITLE
How to use client libaries.

### ISSUE THREAD

**Issue by Elyorbe** [eclipse/mosquitto#1356]
I am sorry if my question is stupid but I spend whole day but couldn't figure out. This is my first time using mosquitto.  I installed mosquitto on windows. Now I want to use client libraries in C.  When I include header files IDE says it can't find the file. Should I download all of this project and put in the same directory?. I tried to do so and configure Cmake file but failed. I am using Clion. Which folders should i download from github and? How should I configure Cmake file if I want to use C client libraries? I didn't understand mosquitto_SOURCE_DIR parts. How should I change.
`include_directories(${mosquitto_SOURCE_DIR} ${mosquitto_SOURCE_DIR}/lib
			${mosquitto_SOURCE_DIR}/src/deps
			${STDBOOL_H_PATH} ${STDINT_H_PATH}
			${OPENSSL_INCLUDE_DIR} ${PTHREAD_INCLUDE_DIR})` 
Could anyone explain step by step?

**Comment by ralight** [comment]
If you've installed from the installer, then you should have files in `C:\Program Files\mosquitto\devel`. This is the path that you will need to tell your compiler to look for include and library files.

Let me reboot into windows, I'll edit this with the updated information.

**Comment by ralight** [comment]
In Visual Studio:

* Right click on your project and select `Properties`
* Click on the `C/C++` entry
* Add `C:\Program Files\mosquitto\devel\` to the `Additional Include Directories`
* Click on the `Linker` entry
* Add `C:\Program Files\mosquitto\devel\` to the `Additional Library Directories`
* Expand the `Linker` entry
* Click on `Input`
* Add `mosquitto.lib` to the `Additional Dependencies` list

When you run your program you will also need the mosquitto.dll, libssl-1_1-x64.dll and libcrypto-1_1-x64.dll available.

**Comment by Elyorbe** [comment]
I did exactly the same as you explained. I checked for mosquitto.dll, libssl-1_1-x64.dll and libcrypto-1_1-x64.dll. They are all available in C:\Program Files\mosquitto\ directory. But, now I am getting linker tools problem. 
`Error	LNK2019	unresolved external symbol __imp__mosquitto_lib_init referenced in function _main	EclipseMosquitto	C:\Users\Elyor\source\repos\EclipseMosquitto\EclipseMosquitto\main.obj	1	`

`Error	LNK1120	1 unresolved externals	EclipseMosquitto	C:\Users\Elyor\source\repos\EclipseMosquitto\Debug\EclipseMosquitto.exe	1	
`
Visual studio Solution explorer shows all header files in external dependencies path. I also tried to use `extern`, but no success. All the suggestions on the web doesn't seem to be solution to my problem. How can I solve it?

**Comment by ralight** [comment]
`Error LNK2019 unresolved external symbol __imp__mosquitto_lib_init referenced in function _main EclipseMosquitto C:\Users\Elyor\source\repos\EclipseMosquitto\EclipseMosquitto\main.obj 1 `

This tells us that you haven't got the mosquitto_lib_init function linked in to your final executable. Did you definitely add `mosquitto.lib` to the Linker additional dependencies?

**Comment by Elyorbe** [comment]
I included in Linker dependencies. It's exactly the same as explanation. Here is the screenshot 
![mosquitto](https://user-images.githubusercontent.com/44853589/61932139-8d8cb780-afbd-11e9-93f8-69625bc930a9.PNG)

**Comment by ralight** [comment]
You're compiling for 32-bit - do you have the library for the 64 or 32 bit version? It must match.

**Comment by Elyorbe** [comment]
I included libraries for 64-bit version and tried to compile for 64 bit. Again the same. Then I downloaded 32-bit binary package  from` https://mosquitto.org/files/binary/win32/mosquitto-1.6.2-install-windows-x86.exe`. Changed the directories for 32 bit version and compiled for 32-bit. Again the same linker problem. Here is the screenshot of configuration. 
![1](https://user-images.githubusercontent.com/44853589/61936434-b619af00-afc7-11e9-8724-1c467438240d.PNG)
![2](https://user-images.githubusercontent.com/44853589/61936437-b7e37280-afc7-11e9-9033-8eb146646b6a.PNG)
![3](https://user-images.githubusercontent.com/44853589/61936438-b9ad3600-afc7-11e9-9877-481ffdf06e04.PNG)
![4](https://user-images.githubusercontent.com/44853589/61936442-bade6300-afc7-11e9-98d5-66b13c7e3f25.PNG)

**Comment by ralight** [comment]
This visual studio project works for me, are you able to test it out?

[MosqDemo.zip](https://github.com/eclipse/mosquitto/files/3471720/MosqDemo.zip)

**Comment by Elyorbe** [comment]
Thank you Roger. I solved the problems and everything is working great now.
