### ISSUE TITLE
_GNU_SOURCE redefined error building with -Werror

### ISSUE THREAD

**Issue by MikeDombo** [eclipse/mosquitto#1357]
```
[-Werror] config.h:19:0: error: "_GNU_SOURCE" redefined
#define _GNU_SOURCE
^
```

Anyone else seeing this? If so, can mosquitto add an ifndef check to not redefine it?

**Comment by ralight** [comment]
I've not seen that. What system are you compiling on?

**Comment by MikeDombo** [comment]
Using GCC 4.9.4 and compiling using our own CMake files on linux x64. It goes away without the -Werror, but ideally we'd keep that. I just tried adding #ifndef around it and that does make the error go away as I expected.

**Comment by ralight** [comment]
Fair enough. I can't reproduce it, but I've added an #ifdef guard anyway.
