### ISSUE TITLE
mosquitto_string_option returns 3 for MOSQ_OPT_TLS_KEYFORM with proper input

### ISSUE THREAD

**Issue by MikeDombo** [eclipse/mosquitto#1360]
mosquitto_string_option returns 3 which is MOSQ_ERR_INVAL when setting MOSQ_OPT_TLS_KEYFORM because the success cases don't return success, they just fallthrough and return the default.

**Comment by ralight** [comment]
Thanks, that should be fixed now.

**Comment by MikeDombo** [comment]
Thanks for the quick fix!
