### ISSUE TITLE
link at the contribution.md is broken

### ISSUE THREAD

**Issue by FurkanTheHuman** [eclipse/mosquitto#1362]
Link at the [CONTRIBUTION.md 
](https://github.com/eclipse/mosquitto/blob/master/CONTRIBUTING.md) file is returns 404. (project description section)
https://projects.eclipse.org/projects/technology.mosquitto

**Comment by ralight** [comment]
Thanks, that's the old Eclipse top level project that Mosquitto was originally part of. It's now fixed.
