### ISSUE TITLE
make test issue with OSError report

### ISSUE THREAD

**Issue by fabe33** [eclipse/mosquitto#1372]
Hi everybody,

I'm trying to install mosquitto from source (1.6.4) my OS is opensuse LEAP 15.1 64 bits.

make lib and bin seems to be ok

make test failed with this issue

`make[3]: Leaving directory '/opt/mosquitto-1.6.4/test/broker/c'
./01-connect-anon-denied.py
Traceback (most recent call last):
  File "./01-connect-anon-denied.py", line 22, in <module>
    broker = mosq_test.start_broker(filename=os.path.basename(__file__), use_conf=True, port=port)
  File "/opt/mosquitto-1.6.4/test/mosq_test.py", line 63, in start_broker
    raise IOError
OSError
make[2]: *** [Makefile:23: 01] Error 1
make[2]: Leaving directory '/opt/mosquitto-1.6.4/test/broker'
make[1]: *** [Makefile:10: test] Error 2
make[1]: Leaving directory '/opt/mosquitto-1.6.4/test'
make: *** [Makefile:75: test] Error 2
`

I don't know what's append ?

Cordialy,

Fabien

**Comment by ralight** [comment]
```
broker = mosq_test.start_broker(filename=os.path.basename(__file__), use_conf=True, port=port)
```

This failing suggests the test isn't able to start the broker. My guess would be that you are running the tests as root. If mosquitto runs as root it will try to change to the `mosquitto` user by default, if this fails then it will not start. Try adding a mosquitto system user, or better running the tests as a normal user.

**Comment by fabe33** [comment]
Thanks a lot for your quick answer, this step pass successfuly with a mosquitto user enable, but an other error raised 

`Traceback (most recent call last):
  File "./04-retain-check-source-persist-diff-port.py", line 105, in <module>
    do_test("true", username=None)
  File "./04-retain-check-source-persist-diff-port.py", line 97, in do_test
    os.remove(persistence_file)
FileNotFoundError: [Errno 2] No such file or directory: '04-retain-check-source-persist-diff-port.db'
make[2]: *** [Makefile:109: 04] Error 1
make[2]: Leaving directory '/opt/mosquitto/test/broker'
make[1]: *** [Makefile:10: test] Error 2
make[1]: Leaving directory '/opt/mosquitto/test'
make: *** [Makefile:75: test] Error 2
A
`

There is no 04-retain-check-source-persist-diff-port.db in the folder.

**Comment by fabe33** [comment]
Thanks a lot with a mosquitto user all works fine.
