### ISSUE TITLE
mosquitto_publish should use size_t instead of int for payloadlen

### ISSUE THREAD

**Issue by nicola-lunghi** [eclipse/mosquitto#1373]
https://github.com/eclipse/mosquitto/blob/a5cd27a68ebb0acc828f2b490cc631acfdbd272c/lib/mosquitto.h#L762

**Comment by karlp** [comment]
why? Why just this function? and why just that one parameter?

**Comment by nicola-lunghi** [comment]
0) all the sizes of the objects type should be changed
1) if the value represent the size of an object should be unsigned int to be in line with std c library
3) usually size_t is unsigned int
4) malloc require size_t argument
5) so you usually need a cast (uint -> int)
6) the cast in theory if the data is big should be checked for overflow

char *pip;
size_t mylen = 2;
pip = malloc(my_len);

mosquitto_publish(... , pip, (int) mylen, ...)

Then the compiler doesn't complain about size_t but you have converted an unsigned int to int

**Comment by nicola-lunghi** [comment]
See here

https://www.viva64.com/en/a/0050/

**Comment by ralight** [comment]
Yes, it would be better to be using size_t, but it isn't an critical issue. Modifying the arguments would have to wait for a 2.0 release as it is a breaking change.

The only important reason for changing this out of your list is to remove compiler complaints. The size of data objects is irrelevant in this situation, unless you are running on an I16P32 device, which isn't something that we aim to support - the maximum allowable payload easily fits within a 32 bit signed int, and out of range values are already checked for.

**Comment by ralight** [comment]
Closing as per the last comment.
