### ISSUE TITLE
Where can i find topic's data in filemanager ubuntu?

### ISSUE THREAD

**Issue by KrYpToDeN** [eclipse/mosquitto#1375]
Hello.

Where can i find created topic's data in filemanager ubuntu?

Thank you.

**Comment by ralight** [comment]
Sorry I don't know what you mean, can you explain a bit further?

**Comment by KrYpToDeN** [comment]
> Sorry I don't know what you mean, can you explain a bit further?

When i publish message into my topic, where is it stored?

Or it's only in online. One person - publish. Another - subscribe and read it in the moment.
=> I would like to find DB/Files/.., where topic's information stored after it was published to write some scripts for reading it in any time.

Best wishes,

**Comment by FernandoGarcia** [comment]
Hi!
You should look for retained messages since messages are not stored in any database by what I know.
Best regards.

**Comment by ralight** [comment]
General messages are not stored, only messages for persistent clients that are offline, and have subscriptions with QoS>0, or retained messages as Fernando says. They are stored in the persistence file which is sometimes stored at /var/lib/mosquitto/mosquitto.db, but is a custom file just for mosquitto.
