### ISSUE TITLE
Server does not send disconnect notification for MQTT 5.0

### ISSUE THREAD

**Issue by wlisac** [eclipse/mosquitto#1378]
I've noticed that the mosquitto server does not send a `DISCONNECT` notification packet to clients when the server disconnects – it simply closes the connection.

I believe this is a new feature in MQTT 5.0 – is there a way to enable the `DISCONNECT` notification?

https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901205

Thanks,
Will

**Comment by ralight** [comment]
Hi Will, it does send a DISCONNECT in some situations, but you're right not in all of them. It's not required that the broker (or client) send a DISCONNECT, which is why all situations aren't covered right now. It is something that will be improved.

**Comment by wlisac** [comment]
@ralight Makes sense – thanks 👍 

Do you happen to know of any situations that will send disconnect packets?

**Comment by Andreyooo** [comment]
I´m also curious to which extend this feature can be used right now.

**Comment by ralight** [comment]
Bit of a delay...

The current develop branch sends disconnects for:

* packet too large
* protocol error
* not authorised (on extended auth re-auth)
* bad authentication method
* session taken over
* administrative action (kicked by e.g. dynsec plugin)
* malformed packet
* qos not supported
* retain not supported
* topic alias invalid
