### ISSUE TITLE
how to config acl and user auth in database?

### ISSUE THREAD

**Issue by jeremyLi1990** [eclipse/mosquitto#1379]
Hi, how to config acl and user auth in database with latest mosquitto version 1.6.X? 
i have tried Mosquitto-Auth-Plugin（https://github.com/jpmens/mosquitto-auth-plug）, but when i try to build it , there are many errors .

can you help me?

thanks!

Followings are build errors:

[root@vps-mqtt02 mosquitto-auth-plug-0.1.2]# make
Selected backends:          MySQL
Using mosquitto source dir: /root/mqtt/mosquitto-1.6.3/src
OpenSSL install dir:        /usr

If you changed the backend selection, you might need to 'make clean' first

CFLAGS:   -I/root/mqtt/mosquitto-1.6.3/src/src/ -I/root/mqtt/mosquitto-1.6.3/src/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  -I/usr/include/mysql -I/src -DDEBUG=1 -I/usr/include
LDFLAGS:   -L/root/mqtt/mosquitto-1.6.3/src/lib/
LDADD:    -L/usr/lib64/mysql -lmysqlclient -lpthread -lz -lm -ldl -lssl -lcrypto -L/usr/lib -lcrypto -lmosquitto

cc  -I/root/mqtt/mosquitto-1.6.3/src/src/ -I/root/mqtt/mosquitto-1.6.3/src/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/include   -c -o auth-plug.o auth-plug.c
auth-plug.c:102:5: 错误：与‘mosquitto_auth_plugin_init’类型冲突
 int mosquitto_auth_plugin_init(void **userdata, struct mosquitto_auth_opt *auth_opts, int auth_opt_count)
     ^
In file included from auth-plug.c:35:0:
/usr/local/include/mosquitto_plugin.h:132:5: 附注：‘mosquitto_auth_plugin_init’的上一个声明在此
 int mosquitto_auth_plugin_init(void **user_data, struct mosquitto_opt *opts, int opt_count);
     ^
auth-plug.c:413:5: 错误：与‘mosquitto_auth_plugin_cleanup’类型冲突
 int mosquitto_auth_plugin_cleanup(void *userdata, struct mosquitto_auth_opt *auth_opts, int auth_opt_count)
     ^
In file included from auth-plug.c:35:0:
/usr/local/include/mosquitto_plugin.h:154:5: 附注：‘mosquitto_auth_plugin_cleanup’的上一个声明在此
 int mosquitto_auth_plugin_cleanup(void *user_data, struct mosquitto_opt *opts, int opt_count);
     ^
auth-plug.c:455:5: 错误：与‘mosquitto_auth_security_init’类型冲突
 int mosquitto_auth_security_init(void *userdata, struct mosquitto_auth_opt *auth_opts, int auth_opt_count, bool reload)
     ^
In file included from auth-plug.c:35:0:
/usr/local/include/mosquitto_plugin.h:182:5: 附注：‘mosquitto_auth_security_init’的上一个声明在此
 int mosquitto_auth_security_init(void *user_data, struct mosquitto_opt *opts, int opt_count, bool reload);
     ^
auth-plug.c:460:5: 错误：与‘mosquitto_auth_security_cleanup’类型冲突
 int mosquitto_auth_security_cleanup(void *userdata, struct mosquitto_auth_opt *auth_opts, int auth_opt_count, bool reload)
     ^
In file included from auth-plug.c:35:0:
/usr/local/include/mosquitto_plugin.h:210:5: 附注：‘mosquitto_auth_security_cleanup’的上一个声明在此
 int mosquitto_auth_security_cleanup(void *user_data, struct mosquitto_opt *opts, int opt_count, bool reload);
     ^
auth-plug.c:466:5: 错误：与‘mosquitto_auth_unpwd_check’类型冲突
 int mosquitto_auth_unpwd_check(void *userdata, const char *username, const char *password)
     ^
In file included from auth-plug.c:35:0:
/usr/local/include/mosquitto_plugin.h:254:5: 附注：‘mosquitto_auth_unpwd_check’的上一个声明在此
 int mosquitto_auth_unpwd_check(void *user_data, struct mosquitto *client, const char *username, const char *password);
     ^
auth-plug.c:527:5: 错误：与‘mosquitto_auth_acl_check’类型冲突
 int mosquitto_auth_acl_check(void *userdata, const char *clientid, const char *username, const char *topic, int access)
     ^
In file included from auth-plug.c:35:0:
/usr/local/include/mosquitto_plugin.h:237:5: 附注：‘mosquitto_auth_acl_check’的上一个声明在此
 int mosquitto_auth_acl_check(void *user_data, int access, struct mosquitto *client, const struct mosquitto_acl_msg *msg);
     ^
auth-plug.c:643:5: 错误：与‘mosquitto_auth_psk_key_get’类型冲突
 int mosquitto_auth_psk_key_get(void *userdata, const char *hint, const char *identity, char *key, int max_key_len)
     ^
In file included from auth-plug.c:35:0:
/usr/local/include/mosquitto_plugin.h:282:5: 附注：‘mosquitto_auth_psk_key_get’的上一个声明在此
 int mosquitto_auth_psk_key_get(void *user_data, struct mosquitto *client, const char *hint, const char *identity, char *key, int max_key_len);

**Comment by FernandoGarcia** [comment]
Hi!
Jpmens's version is not compatible with Mosquitto 1.6.x try this: https://github.com/coldfire84/mosquitto-auth-plug
Also I don't think this is the rigth place to talk about auth plug.
Best regards.

**Comment by jeremyLi1990** [comment]
Hi，


  Thanks a lot！  i will try it.  Anyway， is  this the plug maintained by eclipse?  I have a concern about if i want to upgrade my mosquitto version, just like mosquitto 1.7.x in future, i wander if this plug will be upgraded too.


Thanks & Best regards!


------------------ 原始邮件 ------------------
发件人: "Fernando Garcia"<notifications@github.com>;
发送时间: 2019年8月15日(星期四) 凌晨4:48
收件人: "eclipse/mosquitto"<mosquitto@noreply.github.com>;
抄送: "伴读小書瞳"<597916434@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [eclipse/mosquitto] how to config acl and user auth in database?(#1379)




Hi!
 Jpmens's version is not compatible with Mosquitto 1.6.x try this: https://github.com/coldfire84/mosquitto-auth-plug
 Also I don't think this is the rigth place to talk about auth plug.
 Best regards.

**Comment by FernandoGarcia** [comment]
Not, It's an abandoned project from Jean Piet Mens. You should search for updated forks as I did. Look for this: https://github.com/jpmens/mosquitto-auth-plug/network

**Comment by jeremyLi1990** [comment]
Ok, thank you!




------------------ 原始邮件 ------------------
发件人: "Fernando Garcia"<notifications@github.com>;
发送时间: 2019年8月15日(星期四) 上午9:22
收件人: "eclipse/mosquitto"<mosquitto@noreply.github.com>;
抄送: "伴读小書瞳"<597916434@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [eclipse/mosquitto] how to config acl and user auth in database?(#1379)




Not, It's an abandoned project from Jean Piet Mens. You should search for updated forks as I did. Look for this: https://github.com/jpmens/mosquitto-auth-plug/network

**Comment by ralight** [comment]
Closing because I think this is resolved.
