### ISSUE TITLE
2019-08-14T11:24:05: Warning: Received PUBREL from xxxxx    for an unknown packet identifier 1.

### ISSUE THREAD

**Issue by tianlongyuan** [eclipse/mosquitto#1381]
My mosquitto version:   mosquitto version 1.6.0
My mosquitto.conf file infomation:
`autosave_interval 60`
`persistence true`
`persistence_file mosquitto.db`
`persistence_location /home/mosquitto/`
`log_dest  file /var/log/mosquitto.log`
`log_type all`
`log_timestamp true`
`log_timestamp_format %Y-%m-%dT%H:%M:%S`
`allow_anonymous false`
`password_file /etc/mosquitto/pwfile`

After a lot of testing, we found similar problems as long as the mosquitto persistent file reaches 4026 bytes.

When my persistent DB size is 3612, I can receive messages normally，
The following are mosquiito. DB size information and mosquitto. log message information
`-rw------- 1 mosquitto mosquitto 3612 Aug 14 11:08 mosquitto.db`
`2019-08-14T11:08:50: New connection from 192.168.1.96 on port 1883.`
`2019-08-14T11:08:50: New client connected from 39.100.120.96 as pushBatchCommandClient (p2, c0, k60, u'user_name').`
`2019-08-14T11:08:50: No will message specified.`
`2019-08-14T11:08:50: Sending CONNACK to pushBatchCommandClient (1, 0)`
`2019-08-14T11:08:50: Received PUBLISH from pushBatchCommandClient (d0, q2, r0, m1, 'service/msg/VKEYEFBA', ... (272 bytes))`
`2019-08-14T11:08:50: Sending PUBREC to pushBatchCommandClient (m1, rc0)`
`2019-08-14T11:08:50: Received PUBREL from pushBatchCommandClient (Mid: 1)`
`2019-08-14T11:08:50: Sending PUBCOMP to pushBatchCommandClient (m1)`
`2019-08-14T11:08:50: Sending PUBLISH to PP36811807001880 (d0, q2, r0, m11, 'service/msg/VKEYEFBA', ... (272 bytes))`
`2019-08-14T11:08:50: Received DISCONNECT from pushBatchCommandClient`
`2019-08-14T11:08:50: Client pushBatchCommandClient disconnected.`
`2019-08-14T11:08:50: Received PUBREC from PP36811807001880 (Mid: 11)`
`2019-08-14T11:08:50: Sending PUBREL to PP36811807001880 (m11)`
`2019-08-14T11:08:50: Received PUBCOMP from PP36811807001880 (Mid: 11, RC:0)`

When the file size of mosquitto. DB reached 4026, the device could not receive messages properly.
The following are mosquiito. DB size information and mosquitto. log message information
`-rw------- 1 mosquitto mosquitto 4026 Aug 14 11:09 mosquitto.db`
`2019-08-14T11:10:00: New connection from 39.100.120.96 on port 1883.`
`2019-08-14T11:10:00: New client connected from 39.100.120.96 as pushBatchCommandClient (p2, c0, k60, u'user_name').`
`2019-08-14T11:10:00: No will message specified.`
`2019-08-14T11:10:00: Sending CONNACK to pushBatchCommandClient (1, 0)`
`2019-08-14T11:10:00: Received PUBLISH from pushBatchCommandClient (d0, q2, r0, m1, 'service/msg/VKEYEFBA', ... (272 bytes))`
`2019-08-14T11:10:00: Sending PUBREC to pushBatchCommandClient (m1, rc0)`
`2019-08-14T11:10:00: Received PUBREL from pushBatchCommandClient (Mid: 1)`
`2019-08-14T11:10:00: Warning: Received PUBREL from pushBatchCommandClient for an unknown packet identifier 1.`
`2019-08-14T11:10:00: Sending PUBCOMP to pushBatchCommandClient (m1)`
`2019-08-14T11:10:00: Received DISCONNECT from pushBatchCommandClient`
`2019-08-14T11:10:00: Client pushBatchCommandClient disconnected.`
I hope I can get your help.

**Comment by tianlongyuan** [comment]
I found new problems.
When I use the org. eclipse. paho. ui. app tool, I can publish subscription messages normally, in any case (whether to clear the session and whether to retain the message)

But when I subscribe to messages using a JAVA client, this problem arises.
Here is my JAVA client dependency
`<dependency>`
      `<groupId>org.eclipse.paho</groupId>`
      `<artifactId>org.eclipse.paho.client.mqttv3</artifactId>`
      `<version>1.0.2</version>`
 `</dependency>`


This is my gradle dependency on the device side
 `compile'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0'` 
` compile 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'`

**Comment by ralight** [comment]
I can't comment on the java points, but for Mosquitto have you tried using 1.6.4 instead?

**Comment by tianlongyuan** [comment]
Okay, I'll try to use version 1.6.4.  Thank you !

**Comment by tianlongyuan** [comment]
We have changed to version 1.6.4 and tested it according to the previous testing process.There seems to be no problem with message reception. I don`t quite understand why? But we also found a new problem. We set the `auto_interval 60` parameter to 60 frequencies to push messages to devices that are not online . The persistent data is not saved to mosquitto.db each time.

**Comment by ralight** [comment]
Why - some bugs were fixed. If nothing is being saved to mosquitto.db, can you verify that you have all of the following:

* A client with clean start set to 0
* That client with a subscription with QoS 1 or 2
* The client must then be disconnected
* Another client then publish a message to the subscription topic with QoS 1 or 2

**Comment by ralight** [comment]
I don't believe this is a problem with mosquitto, and the log message is not an error, nor warning, but informational. I'm closing the issue, if you disagree please reopen and add more information.
