### ISSUE TITLE
mosquitto_loop_forever return A TLS error occurred

### ISSUE THREAD

**Issue by Hapoa** [eclipse/mosquitto#1383]
I self-signed server and client certificates, and test them by using MQTT.fx (broker is emqx, opensource mqtt broker), all is well.

But after I used mosquitto_tls_set, and then call mosquitto_loop_forever, it return an error: A TLS error occurred.

Here are self-signed commands refering to [emqx doc](https://www.emqx.io/cn/blog/42):

```
# rootca
openssl genrsa -out certs/root-ca.key 2048
openssl req -new -x509 -days 365 -config ./openssl.cnf -key certs/root-ca.key -out certs/root-cacert.pem -subj "/C=CN/ST=xiamen/O=EMQ/CN=RootCA"

# client ca
openssl genrsa -out certs/client.key 2048
openssl req -new -days 365 -key certs/client.key -out certs/client-cert.csr -subj "/C=CN/ST=xiamen/O=EMQ/CN=Client"
openssl ca -config ./openssl.cnf -extensions v3_req -days 365 -in certs/client-cert.csr -out certs/client-cert.pem -cert certs/root-cacert.pem -keyfile certs/root-ca.key

# server ca
openssl genrsa -out certs/server.key 2048
openssl req -new -days 365 -key certs/server.key -out certs/server-cert.csr -subj "/C=CN/ST=xiamen/O=EMQ/CN=Server"
openssl ca -config ./openssl.cnf -extensions v3_req -days 365 -in certs/server-cert.csr -out certs/server-cert.pem -cert certs/root-cacert.pem -keyfile certs/root-ca.key
```

Here are the c++ codes with mosquitto version 1.6.3 on Ubuntu 14.04 x64,

```c++
#include <mosquitto.h>
#include <iostream>
#include <string>
#include <stdio.h>

void my_message_callback(struct mosquitto *mosq, void *userdata, const struct mosquitto_message *message)
{
    printf("[%s] [%s]", message->topic, message->payload);

    fflush(stdout);
}

int main()
{
    struct mosquitto *mosq = NULL;

    mosquitto_lib_init();

    mosq = mosquitto_new("sub-client-tls", true, NULL);

    int ret = mosquitto_tls_set(mosq, "certs/root-cacert.pem", 
     "/home/hapoa/projects/emq_tls_test/certs/", 
     "certs/client-cert.pem", 
     "certs/client.key", 0);

    if (ret != MOSQ_ERR_SUCCESS)
    {
        printf("mosquitto_tls_set failed, %s\n", mosquitto_strerror(ret));
        return 0;
    }

    mosquitto_message_callback_set(mosq, my_message_callback);

    if (mosquitto_connect(mosq, "x.x.x.x", 8883, 60))
    {
        printf("connect failed\n");
    }
    else
    {
        printf("connect success.\n");
        mosquitto_subscribe(mosq, NULL, "emq/tls/test", 0);
        int ret = mosquitto_loop_forever(mosq, -1, 1);
        printf("mosquitto_loop_forever , %s\n", mosquitto_strerror(ret));
    }

    mosquitto_destroy(mosq);
    mosquitto_lib_cleanup();

    return 0;
}
```

**Comment by Hapoa** [comment]
I found the reason. After add `mosquitto_tls_insecure_set(mosq, true)`, all is well in mosquitto.

But I have a doubt: In [doc](https://mosquitto.org/api/files/mosquitto-h.html#mosquitto_tls_insecure_set), mosquitto_tls_insecure_set is not advised to set to true, because `This can be useful in initial server testing, but makes it possible for a malicious third party to impersonate your server through DNS spoofing, for example.  Do not use this function in a real system.  Setting value to true makes the connection encryption pointless.`

Now assume that: I set mosquitto_tls_insecure_set to true, and person-A impersonate my server through DNS spoofing. I think my client still will not connect to the dummy server, unless person-A get my server-ca and server-private-key (if person-A get them, all is useless, we can ignore this situation.)

Just my personal analysis, I'm new to study OpenSSL recently.

**Comment by ralight** [comment]
In the specific example where your server uses a self generated CA that nobody else has access to, and that your client only trusts certificates generated by that single CA, then I do not believe that it is possible for your client to be misled, but I am not an expert either.

If you trust a variety of CAs, and don't carry out hostname verification, then any valid server certificate would be accepted. If you trusted the Lets Encrypt CA, for example, then your client would happily connect to any server with a Lets Encrypt certificate if you were not doing hostname verification.

**Comment by Hapoa** [comment]
If server use public CA, such as Lets Encrypt, DigiCert, etc. set  `mosquitto_tls_insecure_set` to false is necessary, because person-A may use the same public CA.

But for self-signed certificate, it only be used myself. If I make sure it that any server including the self-sighed certificate can be trusted and can connect to it, then I don't need to verify the hostname.

Am I right?

**Comment by ralight** [comment]
I believe that to be correct. However, if you control everything then you should be able to verify the hostname anyway. If you are just using IP addresses, then a subjectAltName part of your certificate with your IP address should work. The `generateCA.sh` script from https://github.com/owntracks/tools/tree/master/TLS has examples of how to generate certificates with that section.

**Comment by Hapoa** [comment]
Thanks for your warm response, I get it.
