### ISSUE TITLE
MQTT Client disconnects on Date time change on android device

### ISSUE THREAD

**Issue by kavidriod** [eclipse/mosquitto#1388]
MQTT Client disconnects on changing date and time in Android device,Error code I got is "32002" which means Client timed out while waiting to write messages to the server."

From my opinion it is due to ping request and response

E/ClientState: paho17858228622551: Timed out as no write activity, keepAlive=10,000 lastOutboundActivity=1,575,883,094,183 lastInboundActivity=1,575,883,094,206 time=1,575,969,501,073 lastPing=1,575,883,094,186

Here is the error log from android device,

Can anyone please confirm, why the connection lost in android device?

**Comment by ralight** [comment]
It looks like you're using a Paho client, you'd be better off asking at the project that you're using rather than Mosquitto.
