### ISSUE TITLE
log_timestamp_format & Millisecond

### ISSUE THREAD

**Issue by TingYu-Lee** [eclipse/mosquitto#1389]
Hello, I want log_timestamp can show millisecond
but I try many ways and failed
seens mosquitto not support output timestamp to millisecond

This is a free text string which will be passed to the strftime function. To
get an ISO 8601 datetime, for example: 
%Y-%m-%dT%H:%M:$S

and I try to follow ISO 8601 datetime format in config "log_timestamp_format"
==> %Y-%m-%dT%H:%M:$S.%L

--ISO 8601 format (I think it's right)--
 Time (Hour, Minute, Second, Subsecond):
 %H - Hour of the day, 24-hour clock, zero-padded (00..23)
 %k - Hour of the day, 24-hour clock, blank-padded ( 0..23)
 %I - Hour of the day, 12-hour clock, zero-padded (01..12)
 %l - Hour of the day, 12-hour clock, blank-padded ( 1..12)
 %P - Meridian indicator, lowercase (``am'' or ``pm'')
 %p - Meridian indicator, uppercase (``AM'' or ``PM'')
 %M - Minute of the hour (00..59)
 %S - Second of the minute (00..59)
 %L - Millisecond of the second (000..999)
 %N - Fractional seconds digits, default is 9 digits (nanosecond)
          %3N  millisecond (3 digits)   %15N femtosecond (15 digits)
          %6N  microsecond (6 digits)   %18N attosecond  (18 digits)
          %9N  nanosecond  (9 digits)   %21N zeptosecond (21 digits)
          %12N picosecond (12 digits)   %24N yoctosecond (24 digits)

**Comment by ralight** [comment]
It looks like you are looking at the Ruby strftime implementation, where Mosquitto uses the C version of course. There isn't a millisecond precision format specifier in the C strftime.

The available format specifiers are:

* Linux: http://man7.org/linux/man-pages/man3/strftime.3.html
* Windows: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?view=vs-2019

**Comment by karlp** [comment]
Or consider using syslog.

**Comment by ralight** [comment]
I'm closing this because I don't want to effectively have to implement my own copy of strftime, and it is possible to get sub second precision through syslog. Feel free to reopen if you have more information.
