### ISSUE TITLE
Websocket SSL is not working

### ISSUE THREAD

**Issue by siddjoshi** [eclipse/mosquitto#1393]
Hi,

I am running mosquitto in container. Everything works as expected but websocket SSL does not work properly. I can connect to it,  can publish and subscribe however messages for subscribed topic does not reach the client. Mosquitto logs does not give any error. Also browser slows down significantly while connecting on websocket TLS. 

I tried running it on VM with similar results. 

below is the config we are using

mosquitto.conf
==================

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /etc/mosquitto/data/

user mosquitto

port 1883
socket_domain ipv4

log_dest file /etc/mosquitto/log/mosquitto.log
log_dest stdout

include_dir /etc/mosquitto/conf.d

===================================

conf.d directory has default.conf which has below content

=======================================

allow_anonymous false
password_file /etc/mosquitto/certs/passwd
#listener 1883
#socket_domain ipv4
listener 9001
protocol websockets
socket_domain ipv4

listener 8083
protocol websockets
socket_domain ipv4
certfile /etc/mosquitto/certs/cert.crt
cafile /etc/mosquitto/ca_certificates/CA.crt
keyfile /etc/mosquitto/certs/cert-key.key

=======================================

below are the mosquitto logs

=============

1566796323: Loading config file /etc/mosquitto/conf.d/default.conf
1566796323: mosquitto version 1.6.4 starting
1566796323: Config loaded from /etc/mosquitto/mosquitto.conf.
1566796323: Opening websockets listen socket on port 8083.
1566796323: Opening ipv4 listen socket on port 1883.

==============================

Are there any known issues with websocket TLS or I have something wrong with the config ?

Regards
Siddharth

**Comment by ralight** [comment]
There shouldn't be any problems with websockets. Could you try using test.mosquitto.org:8081 as a test, with the CA certificate from http://test.mosquitto.org/ssl/mosquitto.org.crt ? That rules out your config being a problem then.

**Comment by siddjoshi** [comment]
I am not able to connect to  test.mosquitto.org:8081 with wss. Getting connection error, SSL handshake is not successful despite using CA cert. Attaching the wireshark capture for handshake. 

Also attaching the connection settings i used. 

Are you able to connect using wss to this server ? 
 
[wss-test-mosquitto.pcapng.gz](https://github.com/eclipse/mosquitto/files/3555497/wss-test-mosquitto.pcapng.gz)
![wss-connection-settings](https://user-images.githubusercontent.com/5179418/63940082-6591e780-ca86-11e9-9cd8-374b86cf9b9c.JPG)

**Comment by ralight** [comment]
It doesn't look like you've chosen a CA file according to that picture.

**Comment by ralight** [comment]
Ah, sorry I've lead you astray a bit. I had forgotten that the encrypted websocket certificate is a Lets Encrypt certificate, it's not the custom Mosquitto CA. If you use the DST Root X3 certificate as your CA, or your system default CA list, then it should work fine. On my system the CA cert is at `/etc/ssl/certs/DST_Root_CA_X3.pem`

**Comment by siddjoshi** [comment]
yes, it's working when i don't provide any CA certificate. 
I'm still not able to figure out what is wrong with my setup. I am going to build a fresh image again and see if that works.

**Comment by siddjoshi** [comment]
I managed to get it working by compiling the mosquitto again. Probably i overlooked some errors when i last time i compiled it.
