### ISSUE TITLE
Unable to add another user using mosquitto_passwd 

### ISSUE THREAD

**Issue by Vijay614** [eclipse/mosquitto#1394]
when use following cmd
$ sudo mosquitto_passwd -c /etc/mosquitto/passwd username

passwd file overwritten by default ,not append new added user.

Plese change to append file new add user.

**Comment by karlp** [comment]
from the help
```
 -c : create a new password file. This will overwrite existing files.
```

If you want to add a user, just don't use -c.  As the help says.

**Comment by ralight** [comment]
I'm closing this because the answer is above. If you need more information, please reopen and ask.
