### ISSUE TITLE
subscribe 'channel#12345' return MOSQ_ERR_INVAL

### ISSUE THREAD

**Issue by wzzaz** [eclipse/mosquitto#1395]
function `mosquitto_sub_topic_check` in file 'util_topic.c' I found this annotation:
`Search for + or # in a topic, check they aren't in invalid positions such as foo/#/bar, foo/+bar or foo/bar#.`

and in code:
`
}else if(str[0] == '#'){
    if((c != '\0' && c != '/')  || str[1] != '\0'){
        return MOSQ_ERR_INVAL;
    }
}
`

What I mean by that is that the comments are inconsistent with the implementation;
Ignore my poor English;

**Comment by karlp** [comment]
"channel#12345" _is_ an illegal subscription, so if you're getting MOSQ_ERR_INVAL then, yes, that's correct and expected.  The comments are just a subset of the mqtt spec on this, and are only examples to remind the reader, not an exhaustive list of disallowed.

**Comment by ralight** [comment]
Karl is correct here, those are just examples. The function is behaving as expected, so I'm closing this. If you disagree, please reopen and explain why :)

**Comment by wzzaz** [comment]
Thanks for your reply, I have avoided using this illegal subscription
