### ISSUE TITLE
Build with memory tracking enabled in alpine dockerfile

### ISSUE THREAD

**Issue by didjcodt** [eclipse/mosquitto#1404]
Hello, 

By looking in the dockerfiles it seems the mosquitto binaries are built using `WITH_MEMORY_TRACKING` flag, but as it is using an alpine binary the `__GLIBC__` symbol is not defined, thus this option seems to be doing nothing. 
Do you confirm that this option has no effect in the dockerfiles, and if yes, should I make a pull request to remove this option to avoid confusions?

Thank you :)

**Comment by ralight** [comment]
You're right, that could be a bit confusing. No need to open a PR, I've removed the offending lines. Thanks!
