### ISSUE TITLE
Licenses and GPL compliance

### ISSUE THREAD

**Issue by hb-peer** [eclipse/mosquitto#1408]
Hello!

I am sorry if this has been answered before, my search didn't find anything.

You are building the mosquitto image and distributing it through docker hub. This is the way I got to test it.

Now, if I want to distribute this image further, I have to comply with all FOSS licenses with regards to this image.

The base is an alpine image, which certainly has a lot of GPL parts.

How should I go if I want to distribute this binary image further to stay GPL compliant? Can you provide all the licenses and copyleft source code that is contained within this image? As you are distributing it, you should be able to provide it. Correct?

I know a lot of people ignore FOSS licenses and just distribute. I would like to know how you guys handle that.

Thanks for any help!

Best regards,

Peer

**Comment by ralight** [comment]
Closing because I think this is resolved. If not, please reopen and add more details.

**Comment by hb-peer** [comment]
Yes, all right. Thanks for your help!

Best regards,

Peer

Von: Roger Light <notifications@github.com>
Gesendet: Dienstag, 24. September 2019 23:05
An: eclipse/mosquitto <mosquitto@noreply.github.com>
Cc: Ketterle, Peer <P.Ketterle@haverboecker.com>; Author <author@noreply.github.com>
Betreff: Re: [eclipse/mosquitto] Licenses and GPL compliance (#1408)


Closing because I think this is resolved. If not, please reopen and add more details.
