### ISSUE TITLE
mosquitto_passwd returns 0 instead of 1 if the specified user was not found.

### ISSUE THREAD

**Issue by kdgde** [eclipse/mosquitto#1414]
224	if(!found){
225		fprintf(stderr, "Warning: User %s not found in password file.\n", username);
226 }

Better for scripts (get return code):
224	if(!found){
225		fprintf(stderr, "Warning: User %s not found in password file.\n", username);
225		return 1;
227 }

**Comment by ralight** [comment]
Agreed, that should be an error. Thanks for the suggestion, it will be in 1.6.6.
