### ISSUE TITLE
libmosquitto 1.6.6 threaded usage - won't connect

### ISSUE THREAD

**Issue by tillz** [eclipse/mosquitto#1415]
After upgrading libmosquitto to version 1.6.6 from the [eclipse repository](https://mosquitto.org/blog/2013/01/mosquitto-debian-repository/), the threaded interface stopped working for me.
[This gist](https://gist.github.com/tillz/5827f0c41dc23fe116257ee870296308) shows a minimal example, which works with libmosquitto 1.6.4 but not with 1.6.6. 
I even tried it with `mosquitto_connect` instead of `mosquitto_connect_async`, without any difference. 
Of course I might just have missed a part of the documentation for the threaded api, however it worked without any problem in older versions.

I already started debugging this problem, it appears that the `CONNECT`-message is sent successfully, and the server replies with `CONNACK`, however the connect_callback is never called. Moreover, the mosquitto-thread seems to sleep forever without ever reading from the socket.
Maybe [this commit](https://github.com/eclipse/mosquitto/commit/808bbedb6a9616a2300f6fbf85ff4908c0bc62bd) introduced an issue (@ralight?).

Thanks in advance for investigating this issue.

**Comment by karlp** [comment]
possibly same regression as https://github.com/eclipse/mosquitto/issues/1385 too?

**Comment by tillz** [comment]
I had a look at that issue before opening this one and therefore tested and reproduced the problem on a secondary x86_64 machine (nearly fresh Debian 10). So it seems this isn‘t specific to ARM cpus.

**Comment by Pehoh** [comment]
Same issue for me, I use mosquitto on my Ubuntu (16.04) for test purposes, and the connect_callback is never called since the 1.6.6 update.

**Comment by ralight** [comment]
A fix will be here today/early tomorrow.

**Comment by ralight** [comment]
If you are able to try out the `fixes` branch and report back I would appreciate it.

```
git clone https://github.com/eclipse/mosquitto
cd mosquitto
git checkout fixes
make
```

**Comment by tillz** [comment]
Thanks for your quick fix, I can confirm everything is working fine again (at least for me) with the fixes branch.

**Comment by karlp** [comment]
Works for me now too, thanks

**Comment by Pehoh** [comment]
I can confirm it is working with the fix.
