### ISSUE TITLE
Consider adding MQTT v5 properties to output of mosquito_sub

### ISSUE THREAD

**Issue by manifest** [eclipse/mosquitto#1416]
It seems reasonable to output MQTT v5 properties in the output of `mosquito_sub`. That may be hidden behind by `-v`, `-d`, and `-F` flags.

The current behavior
```bash
## Default
mosquitto_sub -V 5 -t 'foo'
bar

## Verbose
mosquitto_sub -v -V 5 -t 'foo'
foo bar

## JSON output of message parameters
mosquitto_sub -F "%j" -V 5 -t 'foo'
{
  "tst": 1568918942,
  "topic": "foo",
  "qos": 0,
  "retain": 0,
  "payloadlen": 3,
  "payload": "bar"
}
```

For
```bash
mosquitto_pub -V 5 -t 'foo' -m 'bar' -D publish user-property a b
```

Mosquitto version: **1.6.4**
OS: macOS

**Comment by ralight** [comment]
Yes.

I'm not sure the best way to approach it though. Perhaps it could be restricted to the json output.

**Comment by manifest** [comment]
> I'm not sure the best way to approach it though. Perhaps it could be restricted to the json output.
That will work for us.

**Comment by ralight** [comment]
This should now be working fully. Please give it a try on the `develop` branch. You can have it either in the JSON output using `-F %j` or `-F %J`, or using new format specifiers: `-F %A %C %D %E %F %P %R %S`.

![tmp-props](https://user-images.githubusercontent.com/79578/66843244-69a99400-ef64-11e9-915b-8692b03fe68c.png)

**Comment by manifest** [comment]
That seems fine to me. Thanks.

**Comment by manifest** [comment]
Just a note about binaries: it may be a bit more useful (readable) to represent them as an arrays of integers (in range of 0 - 255). We always know which properties have the binary type, so there won't be any confusion.

**Comment by manifest** [comment]
Payload is also a binary. It would be nice to attempt representing it as a string, at first. If not possible, to fall to the binary representation (array of integers).
