### ISSUE TITLE
mosquitto_sub -E does not work without -d

### ISSUE THREAD

**Issue by didjcodt** [eclipse/mosquitto#1418]
Hi!
The `-E` option in mosquitto_sub which makes the software exit after the subscriptions have been acknowledged does not work if the debug messages are not enabled.

In fact, in the `client/sub_client.c`, the function `my_subscribe_callback` (in which the flag `exit_after_sub` is used) is registered as a callback only if the `debug` flag is set.

Is it the wanted behaviour (just undocumented), or a bug?

**Comment by ralight** [comment]
This is indeed a bug, thanks for spotting it. I've just pushed a change to the `fixes` branch that sorts it out.

Thanks very much!
