### ISSUE TITLE
Can connect using websocket but not mqtt 

### ISSUE THREAD

**Issue by pranz24** [eclipse/mosquitto#1423]
Hi,

One of the issues I'm facing with Mosquitto 1.6.3 is that even with anonymous as true (only for write), devices on MQTT port are not able to connect to mosquitto while devices on Websocket are able to connect and publish.

Mosquitto.conf:
```
# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d

password_file /etc/mosquitto/passwd
allow_anonymous true
``` 

acls:
```
topic write #

user ad-sqs
topic read A/+/data

user lora-sqs
topic read app/#

user gateway_sqs
topic read gw/+/+/+

user urlk
topic readwrite ur/+/urs/22/+
```
mosquitto.logs:
```
1569309050: New connection from 127.0.0.1 on port 1883.
1569309050: New client connected from 127.0.0.1 as auto-D1EEC23A-99BC-1C37-2DCF-4E6F1FA88637 (p2, c1, k15, u'gateway_sqs').
1569309059: New connection from 127.0.0.1 on port 1883.
1569309059: New client connected from 127.0.0.1 as auto-44BFDDDD-CD5B-4737-4F7A-335DE4EDF54B (p2, c1, k15, u'lora-sqs').
1569309061: New connection from 27.97.82.28 on port 1883.
1569309061: Socket error on client <unknown>, disconnecting.
1569309069: New connection from 27.97.81.186 on port 1883.
1569309069: Socket error on client <unknown>, disconnecting.
1569309080: New connection from 27.97.82.171 on port 1883.
1569309080: Socket error on client <unknown>, disconnecting.
```

**Comment by ralight** [comment]
My guess is that you've defined port 1883 as a websockets listener and haven't got any other listeners for normal mqtt. I would try:

```
listener 1883
protocol mqtt

listener 8080
protocol websockets
```

**Comment by pranz24** [comment]
I don't think that is the problem.
Sorry! for not explaining the problem properly.

And according to the acls file, if I understand correctly, an anonymous user can connect to mosquitto and publish but can't subscribe to a topic.

I am able to publish anonymously using the mosquitto_pub command.

Maybe the problem is related to the device rather than mosquitto. The device is able to connect if I provide the read/write credentials from acls. But is not able to connect anonymously and publish.

I have defined both the ports in ./confd folder
./conf.d/mqtt.conf:
```
listener 1883
```
and ./conf.d/websocket.conf:
```
listener 10554
protocol websockets
```

**Comment by ralight** [comment]
Are you certain that the device is connecting anonymously? Could you use something like wireshark to look at the packets when the device connects?

**Comment by kaushalkumarjoshi** [comment]
Hi,

The specification mentions that if you connect with anonymous client and cleansession=false, the broker terminates the connection.
Maybe that is the case!!

**Comment by pranz24** [comment]
Oh... No
It was a stupid mistake from the manufacturer of the device.
They have a UI for the device where I was disabling username and password.

Using Wireshark:
So apparently, even when the username and password are disabled, I still received packets with username & password flags as `Set`.
And that's why I was getting `Return Code: Connection Refused: not authorized (5)`.


Sorry for this stupid issue I'll close it.

**Comment by ralight** [comment]
Glad to hear you've got it sorted.
