### ISSUE TITLE
Ubuntu 18.04 - Failed to start Mosquitto MQTT v3.1/v3.1.1 Broker.

### ISSUE THREAD

**Issue by guydillen** [eclipse/mosquitto#1428]
Trying to install on a vanilla Ubuntu 18.04 Mosquitto v1.6.7:

$ sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa
$ sudo apt-get update
$ sudo apt-get install mosquitto

results in:
Sep 25 16:17:57 ip-172-26-2-126 systemd[1]: mosquitto.service: Failed with result 'timeout'.
Sep 25 16:17:57 ip-172-26-2-126 systemd[1]: Failed to start Mosquitto MQTT v3.1/v3.1.1 Broker.

**Comment by peteakalad** [comment]
See #1427 raised just before this.

**Comment by guydillen** [comment]
ok thx.
