### ISSUE TITLE
Memory tracking miscount

### ISSUE THREAD

**Issue by gbour** [eclipse/mosquitto#1437]
Hello,

We hit a memory tracking issue in mosquitto (both 1.6.4 and master tested). This leads to client connections being rejected when used memory exceed the limit set in mosquitto.conf (memory tracking enabled).
We identified that at some point, there is a `memcount` counter underflow and because it is a `unsigned long`, its value becomes greater than `max_memcount` and all new client connections are rejected.
The role of our `mosquitto-memleak.patch` patch is to print a stacktrace and force-crashing mosquitto when the underflow happens.
```
100 void mosquitto__free(void *mem)                                                                      
101 {                                                                                                    
102 #ifdef REAL_WITH_MEMORY_TRACKING                                                                     
103     if(!mem){                                                                                        
104         return;                                                                                      
105     }                                                                                                
106     if (memcount < malloc_usable_size(mem)) {                                                        
107         print_stacktrace();                                                                          
108         assert (0);                                                                                  
109     } 
```

This is 100% reproducible with following scenario:
```
shell1> patch -p1 < mosquitto-memleak.patch
shell1> ./src/mosquitto -c mosquitto-memleak.conf
shell2> while true; do mosquitto_sub -h 127.0.0.1 -t '$PROBE' -E -d; sleep .1; done
```
in less than 10 minutes, mosquitto is crashing with following stacktrace:
```
=== BACKTRACE ===
./src/mosquitto(mosquitto__free+0x48)[0x4162d8]
./src/mosquitto(context__free_disused+0x37)[0x40e9a7]
./src/mosquitto(mosquitto_main_loop+0x1d6)[0x415756]
./src/mosquitto(main+0x338)[0x409148]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb)[0x7f91695ecbbb]
./src/mosquitto(_start+0x2a)[0x4092ca]
=== /BACKTRACE ===
```

[mosquitto-memleak.zip](https://github.com/eclipse/mosquitto/files/3676305/mosquitto-memleak.zip) contains:
- mosquitto-memleak.patch
- mosquitto-memleak.conf
- mosquitto-memleak.core

**Comment by ralight** [comment]
Thanks for the report - as you've just noted it's a memory tracking problem not a leak. I've just pushed a fix.

**Comment by gbour** [comment]
You're awesome :+1: 
I'll test it

**Comment by gbour** [comment]
works perfectly fine, I cannot hit the issue anymore

**Comment by ralight** [comment]
Thank you for confirming.
