### ISSUE TITLE
How to clean the database on Snap-Install?

### ISSUE THREAD

**Issue by Sequenzial** [eclipse/mosquitto#1447]
Does anyone know how to clean the db? 
On old apt installation I have a mosquitto.db that can be deleted while the service is down.
It is rebuild when starting the service.
But on Snap install there is no mosquitto.db (or I cannot find it)

How can I do a db clean on Snap Install?

Thx

**Comment by ralight** [comment]
The default snap install does not have persistence enabled.

If you want to enable it, you should create `/var/snap/mosquitto/common/mosquitto.conf` with the options that you want. The persistence location must then be set to `/var/snap/mosquitto/common/`.
