### ISSUE TITLE
Protocol violation: mosquitto does not close connection on receiving websocket connection with wrong subprotocol

### ISSUE THREAD

**Issue by rogierschouten** [eclipse/mosquitto#1456]
When connecting through a web socket, on most errors, mosquitto will maintain the connection but simply stop replying. 

For instance, failing to supply websocket subprotocol 'mqtt' results in this behaviour. 

The problem with this behavior is that a client cannot know that something is wrong.

According to the MQTT v3.1.1 spec (https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/mqtt-v3.1.1.html) 

> [MQTT-4.8.0-1] | Unless stated otherwise, if either the Server or Client encounters a protocol violation, it MUST close the Network Connection on which it received that Control Packet which caused the protocol violation.

Technically establishing a web socket doesn't count as a Control Packet but I think in the spirit of the spec, Mosquitto should actively close the web socket connection.

**Comment by ralight** [comment]
Just looking at sending subprotocols that don't match `mqtt`, I don't see the behaviour you describe. If the subprotocol isn't `mqtt` or `mqttv3.1` then I see, and would expect, that the connection is closed.

What version of Mosquitto, and more importantly libwebsockets are you using, and on what platform?

**Comment by rogierschouten** [comment]
Thank you @ralight for looking into this. 
I'm using Mosquitto 1.6.4 on Docker, with Node.JS 10 and the ws package. 

As you cannot reproduce it, I'll close this issue for now and see if I can pinpoint it to the websockets lib. Thanks again.
