### ISSUE TITLE
mosquitto 1.6.7 windows installer does not install the request response client mosquitto_rr

### ISSUE THREAD

**Issue by raisonchacko** [eclipse/mosquitto#1463]
I used the binary installer for Windows 64 bit (mosquitto-1.6.7-install-windows-x64.exe) from Mosquitto official downloads (https://mosquitto.org/download/)

Installation went successful, but the new request response client for MQTT V5 , mosquitto_rr was not installed.
As per the release notes ,it should install mosquitto_rr  as well.
I tried with some earlier version of mosquitto release which support MQTT V5 (mosquitto 1.6 as well) and that also did not work.
mosquitto_rr  is required for me to test the request-response feature added in MQTT V5.

**Comment by raisonchacko** [comment]
Any hints?

**Comment by ralight** [comment]
Sorry, I've been away.

This is just an oversight. It will be in the next release. Thanks for letting us know.
