### ISSUE TITLE
PSK option is hardcoded disabled in dockerfile, any way around that?

### ISSUE THREAD

**Issue by swdn** [eclipse/mosquitto#1466]
Hey Im using the docker-image and I want to use the PSK option, but its disabled by default in the compiling process (dockerfile).

Is there any way to use mosquitto docker with the psk option enabled (without overwriting the whole file)?

**Comment by ralight** [comment]
Unfortunately libressl doesn't have support for TLS-PSK - I can't remember whether they disabled it at compile time or completely removed it. If you want to use TLS-PSK, you'll need to use openssl and I don't really want to just make that change for everybody who is using the Docker image already.

**Comment by mjeanrichard** [comment]
Could we create an additional image with PSK enabled? Otherwise I have to roll my own and wont be automatically be notified of new image versions.

**Comment by mjeanrichard** [comment]
I just realized that there is already a Docker image published with tag openssl. I guess this solves this issue?

**Comment by ralight** [comment]
@mjeanrichard Yes that's correct, the `*-openssl` builds have TLS-PSK support (so I'm closing this issue)
