### ISSUE TITLE
mosquitto_pub -l sends null messages on empty line

### ISSUE THREAD

**Issue by majekw** [eclipse/mosquitto#1474]
According to man page, empty line on stdin input should be ignored, but right now they send null messages.
It could be great if man and real life behavior would be consistent.

I could prepare fix for this (man page or code). If code needs to fixed it would be easier to work on top of #1473 :-)

**Comment by ralight** [comment]
My feeling with this is that sending an empty message is the correct thing to do, so the man page should be updated. Would you agree?

**Comment by majekw** [comment]
In my opinion sending null is better than silently dropping empty message. So, man page update should be enough to fix this.

**Comment by ralight** [comment]
Great, thanks.
