### ISSUE TITLE
mosquitto_pub -l losts last mesage if not ended with new line

### ISSUE THREAD

**Issue by majekw** [eclipse/mosquitto#1475]
When last line of stdin stream is not ended with `\n`, code don't send what it have in buffer, but allocate more memory and exits.

I could prepare fix for this, but it would be easier to do it on top of #1473 :-)

**Comment by ralight** [comment]
Fixed via: https://github.com/eclipse/mosquitto/commit/1e04b22833597acae79dbe479a22c6cc84266e9e

If you could confirm that works for you that would be great.

**Comment by majekw** [comment]
Works for me, compiled from current fixes branch. Thanks!
