### ISSUE TITLE
Mosquitto does not accept password in passwordfile with special chars

### ISSUE THREAD

**Issue by amanfrinati** [eclipse/mosquitto#1477]
I configured my aclfile to accept readwrite to a topic from user and I configured password with a strong password to that user (the password is `a#wEStev3w21Z5f`). I don't know why but mosquitto authenticated user but doesn't allow to publish on that topic.. Then, after some tries, I changed password to new one more simple `uSTx4mRGBFbE7Pd` (without *#*) and publish works well.

Test on mosquitto version 1.4.15 (build date Tue, 18 Jun 2019 11:42:22 -0300)

**Comment by ralight** [comment]
I haven't managed to reproduce this.

I did:

```
$ mosquitto_passwd -c pwfile bob
(entered password with # as given)
```

My config:

```
listener 1883
allow_anonymous false
password_file pwfile
```

Verifying connection:

```
$ mosquitto_sub -t '$SYS/#' -v -u bob -P a#wEStev3w21Z5f
$SYS/broker/version mosquitto version 1.4.15
$SYS/broker/timestamp 2019-10-31 11:27:52+0000
$SYS/broker/uptime 0 seconds
...
```

How does this differ from what you did?

**Comment by amanfrinati** [comment]
Sorry, my bad. Probably some errors caused by missing docker sync or similar..
