### ISSUE TITLE
Documentation is out-of-sync.

### ISSUE THREAD

**Issue by LiamFry** [eclipse/mosquitto#1478]
It appears the documentation page has been updated recently. Unfortunately, it seems many of the routines and their details are out of sync. Consider `mosquitto_sub_topic_tokens_free`
The signature is `libmosq_EXPORT int mosquitto_sub_topic_tokens_free(char*** topics, int count )` but the body of the text describes the following parameters: `sub`, `sublen`, `topic`, `topiclen`, `result`.

**Comment by karlp** [comment]
which documentation page?

**Comment by karlp** [comment]
I see https://mosquitto.org/api/files/mosquitto-h.html#mosquitto_sub_topic_tokens_free as being correct, but I agree, many other items on the page appear broken.

**Comment by ralight** [comment]
Thank you, this should now be fixed on the repo and on the web page.
