### ISSUE TITLE
Have different access levels for publish and subscribe

### ISSUE THREAD

**Issue by ramakrid** [eclipse/mosquitto#1483]
Should be able to allow anonymous access to publishing clients and check credentials in the connection from subscribers ( Or vice versa ).

**Comment by BrandtHill** [comment]
You can do this currently with the acl file. If `allow_anonymous` is true in your configuration, The top part of your acl will refer to anonymous connections. Take this snippet from an acl file as an example:
```
topic v1/app/data/# write
topic test/hello/world write

user admin
topic v1/app/data/# readwrite
topic test/hello/world readwrite
```
In this example, connections made anonymously (no credentials) are allowed to publish (write) to topics `v1/app/data/#` and `test/hello/world`. The user `admin`, however, is allowed to publish and subscribe (write and read) to those same topics.

**Comment by ralight** [comment]
Closing because the answer above covers the question.
