### ISSUE TITLE
No messages delivered after websocket client takeover

### ISSUE THREAD

**Issue by bverhoeven** [eclipse/mosquitto#1489]
Using Mosquitto 1.6.7 (checked both 'master' and 'fixes' branches), I'm seeing an issue with the web socket 'take over' behavior where, once a client has taken over an old session, it doesn't get any messages if it subscribes to the same topics as the old session.

## Situation

A publisher is writing data to `example/example1` every second.

A websocket client is connected with client_id `example`, subscribed to `example/example1` (qos 1), receiving all those messages just fine. After a while that connection is somehow lost without a clean shutdown (network issues, client crash, bad link, etc.) and the client reconnects.

Mosquitto then correctly prints "Client example already connected, closing old connection".  

The new client happily subscribes to the `example/example1` topic again, which is acknowledged with `SUBACK`, all seemingly fine. As of this point, however, the client never gets the messages that are published to `example/example` until it reconnects again.

There are no errors in mosquitto's logs.

## Reproducing

I think I've found an easy way to reproduce this by having:
* a websocket client connected with client id `example`, 
* a small publisher running (publishing a message every second): 
`(while true; do mosquitto_pub -h localhost -t example/example1 -m pong; sleep 1; done) &
`

And then connecting my own client using `mosquitto_sub` with the `example` client id:

```
$ mosquitto_sub -h localhost -q 1 -i example -t example/example1 -v -d
Received CONNACK
Received SUBACK
Subscribed (mid: 1): 1
^C
```

(No data is received).

The old client is disconnected. No data is ever received for the new session. If I then, however, close this connection, and try to connect again, it'll immediately work:

```
$ mosquitto_sub -h localhost -q 1 -i example -t example/example1 -v -d
Received CONNACK
Received SUBACK
Subscribed (mid: 1): 1
Received PUBLISH (d0, q0, r0, m0, 'example/example1', ... (4 bytes))
example/example1 pong
```

It'll also immediately work if:
* I use a different client id
* I subscribe to the same topic with a different pattern, e.g. `example/+`

This makes it seem as if the old session isn't cleaned up properly and mosquitto still "sees" the old session, and all it's subscriptions. It's almost as if it feels that "the client with id 'example'" is already subscribed to "example/example1" and thus doesn't feel a need to actually subscribe to it "again".

## Possible fix

After some debugging I've tracked this down to the way that websocket clients are cleaned up in a takeover situation, as last changed by https://github.com/eclipse/mosquitto/commit/50882025294a70499173ec9e4dddef944b389185.

This issue seems similar to #1227, but the fix there doesn't seem to have helped and I'm wondering if it's doing what it should be doing:

https://github.com/eclipse/mosquitto/blob/b622aaeee48fd06e825ad04f35f30ff464586255/src/loop.c#L678-L686

If I replace this call to `context__add_to_disused(db, context);` this seems to be resolved: the old client is still disconnected, but, on new connection, re-subscribing works and the client gets the messages as expected.

The rationale behind this change is the fact that `context__disconnect` also calls this function, which _then_ calls the `context__remove_from_by_id` referenced in the code above, but also seems to free up some more structures.

I've just started with mosquitto so I'm not knowledgeable enough to see if this change would cause any issues. I'd appreciate it if someone with more in-depth knowledge of mosquitto could take a peek.

**Comment by ralight** [comment]
Thanks for the detailed description. I haven't checked this yet, but I'm sure you're right. Websockets is a right pain.

I don't think what you've proposed is correct. Adding the client to the disused list (using `context__add_to_disused()`) means that the client will be completley freed soon. This could happen before the websockets part of the code finishes, so bad things would happen.

I'll take a proper look at it soon.

**Comment by bverhoeven** [comment]
Good point, hadn't considered that. That makes sense and I could definitely see it causing issues.

Not sure if it's of any help, but I've done some more testing myself and it seems that I can only reproduce this problem when the web socket listener is using SSL: If I test with regular web sockets then everything works as expected. I can only speculate as to why this is, but it may be related to the fact that it takes a while for a SSL connection to be properly closed?

I've created a small test script (Python 3) that can always reproduce the issue for me, when I have SSL enabled: https://gist.github.com/bverhoeven/00b638487df9f0a1b24a58d6954ffaaa#file-issue-1489-py, I've also included the test [configuration](https://gist.github.com/bverhoeven/00b638487df9f0a1b24a58d6954ffaaa#file-mosquitto-conf) I've used.

Example output:

```
Connecting publisher...
Publisher: Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b'example-publisher'
Publisher: Received CONNACK (0, 0)
Ready for tests.

## Client 1
Client 1: Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b'example-client'
Client 1: Received CONNACK (0, 0)
Client 1: Sending SUBSCRIBE (d0, m1) [(b'example/example1', 1)]
Client 1: Received SUBACK
Client 1: Subscribed, publishing message with publisher..
Publisher: Sending PUBLISH (d0, q0, r0, m1), 'b'example/example1'', ... (7 bytes)
Client 1: Received PUBLISH (d0, q0, r0, m0), 'example/example1', ...  (7 bytes)

OK: Client received published message.

## Client 2
Client 2: Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b'example-client'
Client 1: Disconnected (rc=1)
Client 2: Received CONNACK (0, 0)
Client 2: Sending SUBSCRIBE (d0, m1) [(b'example/example1', 1)]
Client 2: Received SUBACK
Client 2: Subscribed, publishing message with publisher..
Publisher: Sending PUBLISH (d0, q0, r0, m2), 'b'example/example1'', ... (7 bytes)

FAIL: Client did not get published message.
```

**Comment by ralight** [comment]
I've also reproduced it thanks to your test file, that's very much appreciated.

**Comment by ralight** [comment]
Experimental fix (I'm clocking off for this evening, it works but I haven't tested it further):

```
diff --git a/src/handle_connect.c b/src/handle_connect.c
index 17434b2..695ce2a 100644
--- a/src/handle_connect.c
+++ b/src/handle_connect.c
@@ -160,6 +160,9 @@ int connect__on_authorised(struct mosquitto_db *db, struct mosquitto *context, v
                        }
                }
 
+               if(context->clean_start == true){
+                       sub__clean_session(db, found_context);
+               }
                session_expiry__remove(found_context);
                will_delay__remove(found_context);
                will__clear(found_context);
```

**Comment by bverhoeven** [comment]
At first glance that does seem to fix the issue, but by the looks of it only when connecting with 'clean session' set? 

A quick test on my side confirms that if I set `clean_session=False`, in the test script, the issue reappears.

**Comment by ralight** [comment]
The takeover case when clean session is false is actually easier. In that case, the taking over client takes over the subscriptions of the old client and they are removed from the old client. That means this shouldn't be an issue. I can't reproduce it. Here is what I get for both clean session = True and False:
![wstakeover](https://user-images.githubusercontent.com/79578/68388939-a9c1f800-0159-11ea-869f-cb6b261c17d1.png)

**Comment by bverhoeven** [comment]
Interesting. For me, with your patch applied, I'm still seeing the issue with clean_start == false (e.g. clean_session=False):

### clean_session=True
```
## Client 2
Client 2: Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b'example-client'
Client 1: Disconnected (rc=1)
Client 2: Received CONNACK (0, 0)
Client 2: Sending SUBSCRIBE (d0, m1) [(b'example/example1', 1)]
Client 2: Received SUBACK
Client 2: Subscribed, publishing message with publisher..
Publisher: Sending PUBLISH (d0, q0, r0, m2), 'b'example/example1'', ... (7 bytes)
Client 2: Received PUBLISH (d0, q0, r0, m0), 'example/example1', ...  (7 bytes)

OK: Client received published message.
```

### clean_session=False
```
## Client 2
Client 2: Sending CONNECT (u0, p0, wr0, wq0, wf0, c0, k60) client_id=b'example-client'
Client 1: Disconnected (rc=1)
Client 2: Received CONNACK (0, 0)
Client 2: Sending SUBSCRIBE (d0, m1) [(b'example/example1', 1)]
Client 2: Received SUBACK
Client 2: Subscribed, publishing message with publisher..
Publisher: Sending PUBLISH (d0, q0, r0, m2), 'b'example/example1'', ... (7 bytes)

FAIL: Client did not get published message.
```

**Comment by ralight** [comment]
What version of libwebsockets are you using?

**Comment by bverhoeven** [comment]
I'm using the `docker/local/Dockerfile` provided by the project as my main environment, that one fetches libwebsockets version 2.4.2.

**Comment by ralight** [comment]
Hmm, very odd. I have tried on a few different systems and can't reproduce it. I am really surprised that you're seeing the problem, it would mean that the whole concept of taking over an existing clean session=false session was broken.

**Comment by ralight** [comment]
I know you're not seeing it completely fixed, but that is the commit with the above patch in for now.

**Comment by bverhoeven** [comment]
Honestly, for our current setup this fix would probably be enough. We don't ever use `clean_session=False` and it seems that the issue hasn't reappeared since applying that change (with clean_session set). 

I'd still love to help in figuring out what's happening here. I can definitely still see it happening and can easily reproduce it in my test environment. I'll do some more digging and see if I can find a better way to reproduce it, or somehow get closer to a cause. 

Also, my apologies for the earlier confusion: I for some reason thought that subscriptions would not be part of a 'session', and thus would not be affected by 'clean session'. After reading the v3.1.1 standard, it turns out that subscriptions are in fact very much part of the session and everything should indeed be working exactly as you described.

**Comment by bverhoeven** [comment]
I've been running a version with this patch applied in production for the past week and all seems to be working as expected. Thanks again for your quick response and again my apologies for the confusion I caused by accidentally stripping out pieces of code.
