### ISSUE TITLE
can not stop mosquitto service on ubuntu 14.04 x64

### ISSUE THREAD

**Issue by leenux** [eclipse/mosquitto#149]
Hi,
I can't stop the mosquitto service.
Ubuntu 14.04 x64
mosquitto 1.4.8
used apt-get from http://repo.mosquitto.org/debian/mosquitto-wheezy.list to install
screen:
root@ubuntu:/etc/rc5.d# sudo /etc/init.d/mosquitto stop
root@ubuntu:/etc/rc5.d# ps -aux | grep mosqui*
mosquit+   3309  0.0  0.1  32968  4644 ?        Ss   13:15   0:01 /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
root       3565  0.0  0.0  15944  2280 pts/3    S+   13:59   0:00 grep --color=auto mosqui*
root@ubuntu:/etc/rc5.d# kill -15 3309
root@ubuntu:/etc/rc5.d# ps -aux | grep mosqui*
mosquit+   3586  0.0  0.1  32968  4500 ?        Ss   14:04   0:00 /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
root       3589  0.0  0.0  15944  2284 pts/3    S+   14:04   0:00 grep --color=auto mosqui*

---------------------------------
When kill -15 the pid,the process maybe was killed and auto-restart.the pid chg from 3309 to 3586.

TY

**Comment by ralight** [comment]
Try this instead

sudo stop mosquitto

**Comment by leenux** [comment]
@ralight 
Thank you !
Yes,it is work fine.
