### ISSUE TITLE
MQTT Broker not allowing client connect with acl_file on mosquitto.conf | Ubuntu 18.04 LTS.

### ISSUE THREAD

**Issue by TiMladenov** [eclipse/mosquitto#1492]
Hello everyone,

I am deeply sorry if I am asking a stupid question and won't be mad if you people joke about my issue, but....

I develop an application with MQTT Broker locally and deploy it to another computer, in this case, a VM running _Ubuntu 18.04 LTS_. Now I added an acl file. On my local computer, I run _Ubuntu 16.04 LTS_. I also use TLS certificates and password files. I got no problems connecting from my local machine. Sweet.

Now I transferred the code to the VM. Including the added files for acl and password. I noticed that my clients weren't connecting. I checked permissions and file owners. Everything is exactly like on my local machine, i.e. _root:root_ as owner, same permissions. I tested everything, certificates, passwords and got to the problem.... 
For some reason, when I add the "acl_file <path>" to the mosquitto.conf, I am getting stuck on: `"Client mosqsub|3386-<server_name>- sending CONNECT". `
In Mosquitto's log, I am only getting:
```
New connection from 127.0.0.1 on port 8883
Socket error on client <unknown>, disconnection.
```
When I remove the ACL file from the configuration, I can connect to the MQTT Broker without any problems with password and/or certificates.

Any ideas what am I missing?
Thank you in advance!

**Comment by ralight** [comment]
What version of Mosquitto are you running, and how did you install it on the two different systems?

**Comment by TiMladenov** [comment]
Om my 16.04 LTS installation, I added the 'ppa:mosquitto-dev/mosquitto-ppa' repository, which installed version 1.6.7. On the VM with the 18.04 I installed Mosquitto directly from Ubuntu central repository, where the latest version is 1.4.15. Under 18.04 I added the mosquito repository and upgraded to 1.6.7.

The problem is fixed, everything runs like a charm now. Thanks!

**Comment by ralight** [comment]
Great! I'm glad you've got it sorted.
