### ISSUE TITLE
Warning: TLS not working with wrong port order

### ISSUE THREAD

**Issue by Giacomo-Papaluca** [eclipse/mosquitto#1497]
Hello, I don't know if it's a feature or a malfunction but the current version of mosquitto seem to have a problem if you use a double configuration with username&password on port 1883 and TLS or psk-TLS on port 8883. If you want to use TLS and u&p you have to set 8883 as primary port and 1883 as other listener or it won't work, instead if you want to use psk-TLS you have to set 1883 as primary port and 8883 as other listener.

**Comment by ralight** [comment]
Could you please give example configurations for the different cases so I'm exactly clear what you mean?

**Comment by Giacomo-Papaluca** [comment]
Ok I want to use both TLS and username&password. So the .conf file should be like:
...
password_file passwd
cafile myca.crt
certfile server.crt
keyfile server.key
port 8883
listener 1883
...
It works fine like this but if you change the order of ports, and so you write port 1883 and listener 8883, TLS won't work and outputs some ssl error. The same with psk-TLS but in the opposite order: port 1883 and listener 8883 works, port 8883 and listener 1883 doesn't.

**Comment by ralight** [comment]
From your explanations you have two scenarios:

## 1
```
password_file passwd
cafile myca.crt
certfile server.crt
keyfile server.key
port 8883
listener 1883
```

## 2
```
password_file passwd
cafile myca.crt
certfile server.crt
keyfile server.key
port 1883
listener 8883
```

In scenario 1, you configure the TLS settings for the default listener. You assign the port for the default listener to be 8883. You then create a new listener which uses port 1883 and does not have TLS enabled.

In scenario 2, you configure the TLS settings for the default listener. You assign the port for the default listener to be 18883. You then create a new listener which uses port 8883 and does not have TLS enabled.

Each time you use the `listener` argument, a new listener is created which doesn't share any of the TLS settings with the previous listener.

My suggestion would be to not use the default listener, but do the following:

```
# This means that authentication settings, i.e. passwords, are not shared between listeners
per_listener_settings true

listener 1883
# This has no TLS enabled, or any other security, I don't know if that is your intent. If you want password authentication, add a password_file entry here.

listener 8883
# This is a separate listener which has password authentication and TLS enabled
password_file passwd
cafile myca.crt
certfile server.crt
keyfile server.key
```

I hope that is clearer.

**Comment by Giacomo-Papaluca** [comment]
Port 1883 will be listening by default so if you add "listener 1883" in your .conf mosquitto will output this:
![mosqport](https://user-images.githubusercontent.com/18098347/69475675-38787b00-0dd0-11ea-9538-99c240bc28a7.png)

So the problem occurs only if you write "port 1883" + "listener 8883" in your .conf but it is just useless because port 1883 is listening by default. 
So just write listener 8883 and no other port-like line in the mosquitto.conf and it's all right.
