### ISSUE TITLE
Documentation issue - mosquitto_connect_srv

### ISSUE THREAD

**Issue by basavesh** [eclipse/mosquitto#1499]
I'm not able to understand the difference between `mosquitto_connect_bind_async` vs. `mosquitto_connect_srv` what does `srv` mean in `mosquitto_connect_srv`?

`srv` doesn't have a `port` parameter.

**Comment by basavesh** [comment]
This is with respect to information present in https://mosquitto.org/api/files/mosquitto-h.html

> Connect to an MQTT broker.  This is a non-blocking call.  If you use mosquitto_connect_async your client must use the threaded interface mosquitto_loop_start.  If you need to use mosquitto_loop, you must use mosquitto_connect to connect the client. 
This extends the functionality of mosquitto_connect_async by adding the bind_address parameter.  Use this function if you need to restrict network communication over a particular interface. 
May be called before or after mosquitto_loop_start.

**Comment by ralight** [comment]
Thank you, I've now added some guidance on that function.
