### ISSUE TITLE
Mosquitto broker exhausting all the RAM when sending 1000 messages of size 2048 bytes from 153 Paho clients

### ISSUE THREAD

**Issue by DaftMountain** [eclipse/mosquitto#1502]
**Setup**: 

- 153 C++ Paho Clients publishing
- SSL Enabled
- Bridging Enabled
- 153 clients running local brokers
- 1 remote broker
- 1 subscriber running on the remote server

**Versions**:
Mosquitto: 1.6.4
Paho C: 1.3.1
Paho CPP: 1.1

**Problem**: 
We have 153 C++ Paho Clients publishing 1000 messages of size 2048 bytes to the local mqtt broker which is bridged to a remote broker. Each client is publishing to a unique topic for a total of 153 unique topics. The remote broker will consume all available memory until it exhausts all the memory. 

We tried using the memory_limit, but just like it's stated in the documentation, the messages get dropped once the limit is reached.

Also, we don't see this issue if a smaller size(32 byte) message is sent.

Here is the remote broker mosquitto.conf
```
#access
user root
allow_anonymous false
password_file /opt/mosquitto/mosquitto.pwd
acl_file /opt/mosquitto/mosquitto.acl

#network
port 1883
socket_domain ipv4

max_inflight_messages 0
max_queued_messages 0
queue_qos0_messages true
log_type error

#ssl settings
keyfile /opt/server/certs/server.key
certfile /opt/server/certs/remoteBridgeServer.crt
capath /opt/server/certs
```

Is this a limitation in mosquitto or a memory leak?

**Comment by karlp** [comment]
Is that the config of the remote broker or the local?  where are the bridge settings? what is the intent of the max_inflight and max queued to be zero?  Do you only see it if you bridge? not with the just sending your messages directly to the remote broker?  Does your remote broker happen to have a durable subscriber that is offline?

**Comment by DaftMountain** [comment]
That's the remote broker config. Here is the local broker config: 
```
#access
user root
allow_anonymous false
password_file /opt/mosquitto/mosquitto.pwd
acl_file /opt/mosquitto/mosquitto.acl

#network
port 1883
socket_domain ipv4

max_inflight_messages 0
max_queued_messages 0
queue_qos0_messages true

#ssl settings
keyfile /opt/local/certs/server.key
certfile /opt/local/certs/localServer.crt
capath /opt/local/certs

#bridge settings
connection remote-bridge
remote_username test
remote_password pwd
address 192.168.2.2:1883
topic # out 0
topic # in 0
bridge_cafile /opt/local/certs/remoteBridgeClient.crt
```

We didn't want to set a limit to max_inflight_messages and max_queued_messages. So, we set it to 0 which will allow unlimited number of messages. The default value for max_inflight_messages is 20 and max_queued_messages is 100. However, we did test by setting these values to 153000 but the broker still ended up exhausting all the memory.  

We see this problem with bridging enabled, without bridging(directly publishing to the remote broker), with SSL enabled, and without SSL enabled.

There is only one subscriber which is online and runs on the remote server.

**Comment by karlp** [comment]
I totally understand higher values for max queued, but can't say I really recommend no limits max inflight.  Does the target broker have persistence?  I'd be interested in a db dump making sure that there was no "unexpected" persistent client in the db.

**Comment by DaftMountain** [comment]
Persistence is not set and by default the value is false. Is there another way to check if there are any unexpected clients?

**Comment by ralight** [comment]
Your local bridges default to `cleansession false`, which means if one goes offline then you are asking the remote broker to store infinite messages.

You could try enabling persistence, then using `mosquitto_db_dump` to have a look at the persistence file to see what is being stored. Or if possible use `valgrind --tool=massif mosquitto -c remote.conf` to get a trace of the heap usage.

**Comment by DaftMountain** [comment]
We ran with cleansession set to true and it didn't make a difference. 

Here is the output of running  valgrind --tool=massif mosquitto -c remote.conf
[massif.out_8101.txt](https://github.com/eclipse/mosquitto/files/3881746/massif.out_8101.txt)

We published about 7000 messages of size 2048 bytes from 150 clients with valgrind. The memory steadily went up to about 9.5GB, but after the clients finished publishing the memory freed itself. We have never seen memory free itself when running mosquitto without valgrind. Normally, we have to restart the broker in order to free the memory. 
```

--------------------------------------------------------------------------------
  n        time(i)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
 44  7,188,180,031    1,170,699,664    1,138,170,617    32,529,047            0
 45  7,427,321,818    1,123,901,936    1,095,383,979    28,517,957            0
 46  7,570,704,920    1,093,347,504    1,067,903,032    25,444,472            0
 47  7,809,677,930    1,034,043,600    1,015,389,786    18,653,814            0
 48  8,000,783,623      944,048,080      931,542,679    12,505,401            0
 49  8,144,139,320      850,463,952      839,197,806    11,266,146            0
 50  8,247,346,365      784,512,928      774,135,067    10,377,861            0
 51  8,350,550,001      719,186,832      709,699,039     9,487,793            0
 52  8,453,733,324      653,538,336      645,004,217     8,534,119            0
 53  8,556,916,730      588,890,224      581,278,155     7,612,069            0
 54  8,660,120,844      523,730,880      517,036,917     6,693,963            0
 55  8,763,304,324      457,217,248      451,360,175     5,857,073            0
```

Is this a normal memory usage case?

**Comment by barryboneless** [comment]
What is the time difference between the finishing of the publishing and the naturally clearing of all the memory? This seems like it's more likely related to the number of connections and not the number of stored messages. What is the environment/hardware you are running this on? That may be a factor.

**Comment by DaftMountain** [comment]
Can't reproduce the issue anymore...closing for now.
