### ISSUE TITLE
mosquitto-clients tlv1.3 unsuported

### ISSUE THREAD

**Issue by The-Idle-Sloth** [eclipse/mosquitto#1503]
Hello,

I'm using the package mosquitto-clients (1.4.15-2ubuntu0.18.04.3) which seems to be the latest version according :
```
~$ apt-cache policy mosquitto-clients
mosquitto-clients:
  Installé : 1.4.15-2ubuntu0.18.04.3
  Candidat : 1.4.15-2ubuntu0.18.04.3
 Table de version :
 *** 1.4.15-2ubuntu0.18.04.3 500
        500 http://fr.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages
        100 /var/lib/dpkg/status
     1.4.15-2 500
        500 http://fr.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

Commands ```mosquitto_pub``` and ```mosquitto_sub``` doesn't accept the option ```--tls-version tlsv1.3```.

When I run the command, I get the message ```Error: Problem setting TLS options.```

Best regards,
The-Idle-Sloth

**Comment by karlp** [comment]
it's only the latest version on that ubuntu repo.  it's actually _far_ from the latest version.  1.4.15 was released in february 2018.  The current version is 1.6.7.

See mosquitto.org for methods of getting newer packages.

**Comment by ralight** [comment]
I'm closing this because I think you've got the information you need. Please reopen and ask for more details if you need.
