### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by vlumikero** [eclipse/mosquitto#1512]
Hi,

After having run a sudo apt-get update, I'm now getting a seg fault when I try to start mosquitto. I've seen a previous issue on this, tried the resolution but it did not help.

So basically, I'm running:
sudo mosquitto -c /etc/mosquitto/mosquitto.conf

and getting
Segmentation fault

Thanks,
Ville

**Comment by basavesh** [comment]
Could you please run it in verbose mode and also, post the debug mode logs? 
(not a mosquitto maintainer, trying to understand the problem)

**Comment by vlumikero** [comment]
the verbose mode gives the exact same result. how do I get the debug mode logs?

**Comment by basavesh** [comment]
You need to set this in your conf file.
log_type debug
> https://mosquitto.org/man/mosquitto-conf-5.html

**Comment by ralight** [comment]
Are you running on a Raspberry Pi? If so, please try updating.

**Comment by ralight** [comment]
I think this was fixed in an update to the raspberry pi repo, so I'm going to close this bug. If it's still an issue please reopen and provide details.
