### ISSUE TITLE
make ptest (03-publish-c2b-qos2-maximum-qos-1.py) fails when called multiple times back to back. 

### ISSUE THREAD

**Issue by basavesh** [eclipse/mosquitto#1515]
Failure `./03-publish-c2b-qos2-maximum-qos-1.py`
Takes couple tries to reproduce the issue. May be a race?
> 0.427s : ./01-will-set.py
> Traceback (most recent call last):
>   File "./03-publish-c2b-qos2-maximum-qos-1.py", line 54, in <module>
>     if mosq_test.expect_packet(conn, "disconnect", disconnect_packet):
>   File "/<home path>/mosquitto/test/mosq_test.py", line 83, in expect_packet
>     packet_recvd = sock.recv(rlen)
> ConnectionResetError: [Errno 104] Connection reset by peer
> 0.949s : ./03-publish-c2b-qos2-receive-maximum-1.py
> 0.849s : ./03-publish-c2b-qos1-receive-maximum.py
> 0.733s : ./03-publish-b2c-qos1.py
> 1.018s : ./03-publish-c2b-qos2-maximum-qos-1.py
> 0.998s : ./03-publish-b2c-qos2.py
> ...waiting...
> Already exited should_run....
> ...waiting...
> Already exited should_run....

**Comment by ralight** [comment]
Yes it is. The problem is that the DISCONNECT packet gets passed to the kernel, but we have no way of knowing if it actually got sent. If I manually enable TCP_NODELAY on the socket then I can't reproduce the problem.

**Comment by basavesh** [comment]
Thanks for the clarification. I noticed that there is a fix in develop branch for this.
