### ISSUE TITLE
Undefined symbols of _SSL_CTX_set_psk_client_callback

### ISSUE THREAD

**Issue by tripleCC** [eclipse/mosquitto#152]
[  1%] Linking C shared library libmosquitto.dylib
Undefined symbols for architecture x86_64:
  "_SSL_CTX_set_psk_client_callback", referenced from:
      __mosquitto_socket_connect in net_mosq.c.o
  "_TLSv1_1_client_method", referenced from:
      __mosquitto_socket_connect in net_mosq.c.o
  "_TLSv1_2_client_method", referenced from:
      __mosquitto_socket_connect in net_mosq.c.o
ld: symbol(s) not found for architecture x86_64

how to resolve this error?

**Comment by anonymouse64** [comment]
What system are you compiling on?

**Comment by tripleCC** [comment]
Darwin tripleCC.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

ProductName:	Mac OS X
ProductVersion:	10.11.4
BuildVersion:	15E65

**Comment by ralight** [comment]
It looks like you're using a very old version of openssl that doesn't support TLS-PSK or modern versions of TLS - or else one that has those features removed. Either way, honestly the best approach would be to look at upgrading openssl first.

**Comment by tripleCC** [comment]
@ralight  it seems that the openssl which I'm using is up to date 

brew upgrade openssl
Error: openssl 1.0.2g already installed

**Comment by anonymouse64** [comment]
It's probably trying to use the built-in OpenSSL on Mac. Are you defining the location of OpenSSL from brew to CMake?

**Comment by tripleCC** [comment]
I disable  TLS-PSK  by changing config.mk  ：

`WITH_TLS:=no
WITH_TLS_PSK:=no`

But it did not work

**Comment by ralight** [comment]
Try `cmake -DWITH_TLS_PSK=OFF` or `cmake -DWITH_TLS_PSK=OFF -DWITH_TLS=OFF`

**Comment by tripleCC** [comment]
@anonymouse64 
I think I have defined the location of OpenSSL by exec command below:
`cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include`

**Comment by tripleCC** [comment]
@ralight 
It's a nice solution 👍

**Comment by ralight** [comment]
I'm sure you're aware, but if you just want mosquitto installed then you can get it from homebrew as well.

**Comment by tripleCC** [comment]
@ralight 
thank you for your help! I had install mosquitto from homebrew . And I want to insert some log code to server, so that I can test my client more comprehensively. It's why I compile it manually

**Comment by anonymouse64** [comment]
Are you able to compile it now?

**Comment by tripleCC** [comment]
@anonymouse64 
I disabled TLS-PSK by trying `cmake -DWITH_TLS_PSK=OFF -DWITH_TLS=OFF`,  and then it can be compiled successfully

**Comment by anonymouse64** [comment]
I think this issue can be closed in that case. Glad it worked for you.

**Comment by nmlt** [comment]
I had the same problem (also building mosquitto on Mac). I solved with installing openssl with brew (for me it was installed in `/usr/local/opt/openssl`) and setting the following options with `ccmake`:
```
OPENSSL_CRYPTO_LIBRARY           /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
OPENSSL_INCLUDE_DIR              /usr/local/opt/openssl/include
OPENSSL_SSL_LIBRARY              /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
```
(I checked the exact filenames of the dylibs in the directory)
I'am a beginner with cmake so I was quite happy this worked.
