### ISSUE TITLE
Not freeing config->log_timestamp_format in src/config.c:config__cleanup

### ISSUE THREAD

**Issue by basavesh** [eclipse/mosquitto#1523]
There is a minor memory leak due to not freeing config->log_timestamp_format in config__cleanup during mosquitto shutdown.

Verified using valgring and ASAN
> valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes ./src/mosquitto -c ~/mosquitto.conf 
> ==32280== Memcheck, a memory error detector
> ==32280== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
> ==32280== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
> ==32280== Command: ./src/mosquitto -c /home/basavesh/mosquitto.conf
> ==32280== 
> ^C==32280== 
> ==32280== FILE DESCRIPTORS: 3 open at exit.
> ==32280== Open file descriptor 2: /dev/pts/0
> ==32280==    <inherited from parent>
> ==32280== 
> ==32280== Open file descriptor 1: /dev/pts/0
> ==32280==    <inherited from parent>
> ==32280== 
> ==32280== Open file descriptor 0: /dev/pts/0
> ==32280==    <inherited from parent>
> ==32280== 
> ==32280== 
> ==32280== HEAP SUMMARY:
> ==32280==     in use at exit: 18 bytes in 1 blocks
> ==32280==   total heap usage: 4,864 allocs, 4,863 frees, 187,347 bytes allocated
> ==32280== 
> ==32280== 18 bytes in 1 blocks are definitely lost in loss record 1 of 1
> ==32280==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
> ==32280==    by 0x5DDB9B9: strdup (strdup.c:42)
> ==32280==    by 0x11E05D: mosquitto__strdup (memory_mosq.c:147)
> ==32280==    by 0x10FC60: conf__parse_string (conf.c:2383)
> ==32280==    by 0x1133D9: config__read_file_core (conf.c:1536)
> ==32280==    by 0x1140B2: config__read_file (conf.c:2232)
> ==32280==    by 0x1141C8: config__read (conf.c:647)
> ==32280==    by 0x114CE1: config__parse_args (conf.c:407)
> ==32280==    by 0x10D5FA: main (mosquitto.c:248)
> ==32280== 
> ==32280== LEAK SUMMARY:
> ==32280==    definitely lost: 18 bytes in 1 blocks
> ==32280==    indirectly lost: 0 bytes in 0 blocks
> ==32280==      possibly lost: 0 bytes in 0 blocks
> ==32280==    still reachable: 0 bytes in 0 blocks
> ==32280==         suppressed: 0 bytes in 0 blocks
> ==32280== 
> ==32280== For counts of detected and suppressed errors, rerun with: -v
> ==32280== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

**Comment by ralight** [comment]
Thanks, this is now fixed.
