### ISSUE TITLE
Does Mosquitto client supports Mqtt v5

### ISSUE THREAD

**Issue by adityaMundhara** [eclipse/mosquitto#1531]
I'm wondering if the mosquitto client provides support to the mqtt v5, as on the github, It is not clear weather mqtt 5 is supported by mosquitto client.

**Comment by ralight** [comment]
Yes it does. Try

```
...
mosq = mosquitto_new(...);
mosquitto_int_option(mosq, MOSQ_OPT_PROTOCOL_VERSION, MQTT_PROTOCOL_V5);
...
```

And then use the functions ending in `_v5` if you wish to set properties on any messages.

**Comment by adityaMundhara** [comment]
Thanks for the support .

**Comment by adityaMundhara** [comment]
Is this not available for linux ? as the header files are not same for debian version and windows version.

**Comment by ralight** [comment]
If you have installed from the Debian repository then you will probably have version 1.5.7, which doesn't support MQTT v5. You could use the project provided repositories at https://repo.mosquitto.org/ , or compile 1.6.8 from source.

**Comment by adityaMundhara** [comment]
will that have libmosquitto.so file ? I'm using c++ for programming mqtt client in debian ,  and apt-get install mosquitto is not providing header files and libs, this happens when using snap.
Even make command doesn't provide the libs and mosquitto headers, will be glad if you help me with this.

**Comment by daenney** [comment]
Please take a moment to use the Debian packages search in the future: https://packages.debian.org/search?keywords=mosquitto&searchon=names&suite=all&section=all. Alternatively invoke `apt search mosquitto`.

The mosquitto package does not install C/C++ header files, that's what the libmosquitto*-dev packages are for. The same goes for the packages on https://repo.mosquitto.org/debian/pool/main/m/mosquitto/.

**Comment by ralight** [comment]
I believe this is now resolved, so I'm closing the issue. If you've still got problems please reopen and provide more details.
