### ISSUE TITLE
memory issue after small code modification

### ISSUE THREAD

**Issue by sh4d0v1** [eclipse/mosquitto#1532]
[This is not an issue with the published code, but a request for an explanation of the same.]

I want to extend mosquitto's functionality to allow direct writing of the MQTT payload data into a database, without having to include a second process subscribed to the broker. I got this functionality working, but am observing some artifact chars at the end of the payload in some cases. I assume these to rise from a memory issue.

I reduced the modified code to demonstrate the problem to one line: In `src/handle_publish.c` the following line https://github.com/eclipse/mosquitto/blob/6bfd52af9e29165bbf82e3c67b0c4f8310e92b43/src/handle_publish.c#L297 

changed to 

```log__printf(NULL, MOSQ_LOG_DEBUG, "Received PUBLISH from %s (d%d, q%d, r%d, m%d, '%s', '%s' (%ld bytes))", context->id, dup, qos, retain, mid, topic, UHPA_ACCESS(payload, payloadlen), (long)payloadlen);```

will print the payload data with the debug output, but also produce a memory issue (valgrind output):

```2019-12-11T23:46:09: mosquitto version 1.6.8 starting
2019-12-11T23:46:09: Config loaded from /etc/mosquitto/mosquitto.conf.
2019-12-11T23:46:09: Opening ipv4 listen socket on port 1883.
2019-12-11T23:46:09: Opening ipv6 listen socket on port 1883.
2019-12-11T23:46:10: New connection from 127.0.0.1 on port 1883.
2019-12-11T23:46:10: New client connected from 127.0.0.1 as mosq-WgVdzYIrVBtghWA3Eo (p2, c1, k60).
2019-12-11T23:46:10: No will message specified.
2019-12-11T23:46:10: Sending CONNACK to mosq-WgVdzYIrVBtghWA3Eo (0, 0)
==18498== Invalid read of size 1
==18498==    at 0x4838C74: strlen (vg_replace_strmem.c:460)
==18498==    by 0x4DD89EE: vfprintf (vfprintf.c:1638)
==18498==    by 0x4DFF79F: vsnprintf (vsnprintf.c:114)
==18498==    by 0x11CA7B: log__vprintf (logging.c:276)
==18498==    by 0x11D016: log__printf (logging.c:367)
==18498==    by 0x11B43D: handle__publish (handle_publish.c:298)
==18498==    by 0x121A4C: packet__read (packet_mosq.c:486)
==18498==    by 0x11E1F6: loop_handle_reads_writes (loop.c:828)
==18498==    by 0x11E1F6: mosquitto_main_loop (loop.c:511)
==18498==    by 0x10E1D9: main (mosquitto.c:367)
==18498==  Address 0x4ffd81b is 0 bytes after a block of size 107 alloc'd
==18498==    at 0x483577F: malloc (vg_replace_malloc.c:299)
==18498==    by 0x11E4C0: mosquitto__malloc (memory_mosq.c:87)
==18498==    by 0x11B8E9: handle__publish (handle_publish.c:270)
==18498==    by 0x121A4C: packet__read (packet_mosq.c:486)
==18498==    by 0x11E1F6: loop_handle_reads_writes (loop.c:828)
==18498==    by 0x11E1F6: mosquitto_main_loop (loop.c:511)
==18498==    by 0x10E1D9: main (mosquitto.c:367)
==18498== 
2019-12-11T23:46:10: Received PUBLISH from mosq-WgVdzYIrVBtghWA3Eo (d0, q0, r0, m0, '1', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' (107 bytes))
2019-12-11T23:46:10: Received DISCONNECT from mosq-WgVdzYIrVBtghWA3Eo
2019-12-11T23:46:10: Client mosq-WgVdzYIrVBtghWA3Eo disconnected.
```

(The same happens for use of the UHPA_ACCESS_STR macro. In this example there is no artifact at the end of payload.)

I assume to access the payload data in the intended way (the union of heap pointer and array), but where is the off-by-one bug related to the allocation of the payload data?

Thank you very much for taking the time and possibly explaining the issue.

**Comment by ralight** [comment]
The problem is simple - the payload is not a string, it is just a series of bytes. There is no guarantee that it will be zero terminated. In fact, it is highly unlikely to be zero terminated. printf assumes zero termination, so goes off and keeps printing until it finds a zero.

**Comment by sh4d0v1** [comment]
Well, that indeed is a simple explanation. Extending (a copy of) the payload with a null terminator solves the memory issue as expected.

Thank you very much!
