### ISSUE TITLE
bind_interface option not working when having additional listeners.

### ISSUE THREAD

**Issue by nihilus** [eclipse/mosquitto#1533]
Have 2 instance of bind_interface and only the latter is in effect:

Dec 13 14:45:39 daemon.notice mosquitto: 1576244739: mosquitto version 1.6.8 starting
Dec 13 14:45:39 daemon.notice mosquitto: 1576244739: Config loaded from /etc/mosquitto.conf.
Dec 13 14:45:39 daemon.notice mosquitto: 1576244739: Opening ipv6 listen socket on port 8883.
Dec 13 14:45:39 daemon.notice mosquitto: 1576244739: Warning: Address family not supported by protocol
Dec 13 14:45:39 daemon.notice mosquitto: 1576244739: Opening ipv4 listen socket on port 8883.
Dec 13 14:45:39 daemon.notice mosquitto: 1576244739: Binding listener to interface "br0".
Dec 13 14:45:39 daemon.notice mosquitto: 1576244739: Opening ipv6 listen socket on port 1883.
Dec 13 14:45:39 daemon.notice mosquitto: 1576244739: Warning: Address family not supported by protocol
Dec 13 14:45:39 daemon.notice mosquitto: 1576244739: Opening ipv4 listen socket on port 1883.

**Comment by karlp** [comment]
Can you share your actual config snippets please?

**Comment by karlp** [comment]
(by my reading of the manual, you canonly have bind_interface on the default listener, additional listeners have bind paramters as optional ags to the listener directive)

**Comment by nihilus** [comment]
The thing is that it worked on the contrary way. The default listener using the port directive didn't bind. Using the listener directive for it solved the issue.

**Comment by ralight** [comment]
`bind_interface` works with the non-default listeners. That's not clear from the documentation.

Could you share the problem configuration?

**Comment by ralight** [comment]
I think this should be fixed now.
