### ISSUE TITLE
If nobody subscribes the topic which msgs of qos2...

### ISSUE THREAD

**Issue by duelqiuqiu** [eclipse/mosquitto#1537]
If nobody subscribes the topic which msgs of qos2 had been published, what will happen in broker?
Out of memory?

**Comment by karlp** [comment]
if nobody has ever subscribed, then nothing, they're just dropped.  If a durable (non-cleansession) client has subscribed in the past, and is offline, they'll be queued up to the limit of max_queued_messages / max_queued_bytes, and then dropped.  There's also a memory_limit directive you can use too.

**Comment by ralight** [comment]
I think this can be closed, if you need more information please reopen it and ask.
