### ISSUE TITLE
Using libmosquitto to upgrade to wss

### ISSUE THREAD

**Issue by stelfrag** [eclipse/mosquitto#1540]
I have been trying without much lack to see if I can use libmosquitto and build an application that connects to a mosquitto broker and upgrades that connection to wss (secure websockets) 

Other that seeing a mention of websockets in the 
```
libmosq_EXPORT int mosquitto_string_option(	struct 	mosquitto 	*	mosq,
enum 	mosq_opt_t 		option,
const 	char 	*	value	)
```

```
MOSQ_OPT_TLS_ALPN If the broker being connected to has multiple services available on a single TLS port, such as both MQTT and WebSockets
```
I have not found any mention of websockets anywhere in the library. 

My question:
- Can it be done? (am I missing the obvious?)
   - If yes , I would appreciate any suggestion on how would I go about doing this 
- If not, are there plans to support this? (What would it take to implement?)

**Comment by ralight** [comment]
libmosquitto doesn't support websockets at the moment. It's something that I was hoping to sort out in the next minor release.

**Comment by stelfrag** [comment]
> libmosquitto doesn't support websockets at the moment. It's something that I was hoping to sort out in the next minor release.

Thank you for the information. Looking forward to that :-)  Do you have a time plan in mind?

**Comment by stelfrag** [comment]
Hi @ralight is this still in the works for the next minor release? (any dates in mind)? 

Thank you so much!!!!

**Comment by bbinet** [comment]
I would also be interested in websocket support in libmosquitto

**Comment by psriniva007** [comment]
Is it possible to configure mosquitto client library to connect to the MQTT broker using websockets (port 443) ?
Any sample application (c / c++) or pointers to relevant documentation, would be very helpful.

**Comment by mm-ark** [comment]
It seems libmosquitto still does not support websockets. I am also interested in this functionality.

**Comment by ralight** [comment]
libmosquitto has websockets support in the `develop` branch which will be version 2.1 "soon", so I'm closing this issue.
