### ISSUE TITLE
Package mosquitto_sub client into the Docker image

### ISSUE THREAD

**Issue by asoltesz** [eclipse/mosquitto#1548]
The mosquitto_sub client is very often needed to debug connectivity problems around the MQTT server (monitor message flow).

When working in a Dockerized environment, it is a fairly big hindrance that there is no ARM based mqtt client packaged in any Docker image (neither the Mosquitto image, nor third parties, all of them ar x86/x64).

The cleanest solution would be to simply package the clients with the Mosquitto server image, so that debug tooling is available at all times.

**Comment by ralight** [comment]
The client tools have been packaged in the eclipse-mosquitto 1.6 image since version 1.6.1. I did think they were in the 1.5 image as well, but it appears not.
