### ISSUE TITLE
Msqtt - crashes if libmosquitto deployed with missing dependecies ( libopenssl / libcrypt)

### ISSUE THREAD

**Issue by NOELV70** [eclipse/mosquitto#155]
Hi all, 

Want to report an issue where libmosquitto crashes if you install it on a target where some depencies are missing.

If you install and use libmosquitto on a target ( embedded arm platform in this case) where the libopenssl and/or libcrypt are missing you get a crash after aprox 8 minutes of running. 

It would be nice to have the 

mosquitto_lib_init(); 
or 	
mosquitto_new

to return an error code ( what is not the case now).

Best Regards
Noel

**Comment by ralight** [comment]
If libmosquitto has support for openssl compiled in but the openssl libraries are not available, then the runtime linker should fail before the application even starts. Calling mosquitto_lib_init() makes use of openssl functions, so if they are not available it is not possible for that function to be called.

The only way I can see that the scenario you describe could occur is if you are loading libmosquitto using dlopen/LoadLibrary - but even in that case it would fail immediately you called mosquitto_lib_init(), not 8 minutes later.

**Comment by ralight** [comment]
I don't see how this could be possible on any system. I believe it must be another problem in your application. If you can provide an example that demonstrates this problem feel free to open this issue again.
