### ISSUE TITLE
Async API never yields which causes the thread to eat CPU.

### ISSUE THREAD

**Issue by nihilus** [eclipse/mosquitto#1550]
The async API never yields which causes the thread to eat lots of CPU (about 99%). Adding usleep(10); to mosquitto_loop_misc() fixes this. However I am unsure if that is appropriate.

**Comment by karlp** [comment]
could you share a snippet of how you're using the apis?

**Comment by nihilus** [comment]
```
	mosq_ret = mosquitto_connect_async(mosq, ipstr, 1883, 0);
	if(mosq_ret != MOSQ_ERR_SUCCESS){
	    fprintf(stderr, "Unable to connect (%s)!\n", mosquitto_strerror(mosq_ret));
       	    goto exit;
        }

	mosq_ret = mosquitto_loop_start(mosq);
	if(mosq_ret != MOSQ_ERR_SUCCESS){
	    fprintf(stderr, "Unable to start loop (%s)!\n", mosquitto_strerror(mosq_ret));
       	    goto exit;
        }

	while(run == -1){
		nanosleep(&tv, NULL);
	}
```

**Comment by nihilus** [comment]
I will check if #1542 solves the issue tomorrow.

**Comment by ralight** [comment]
```
mosq_ret = mosquitto_connect_async(mosq, ipstr, 1883, 0);
```

You've set the `keepalive` parameter to 0 here. This should be rejected as an invalid value, but it isn't.  I would suggest using a value of 10 as the absolute minimum value.

**Comment by nihilus** [comment]
Ah, explains.

**Comment by nihilus** [comment]
@ralight FWIW: Your suggestion worked perfectly. So the bug is that it doesn't validate the argument then.
