### ISSUE TITLE
mosquitto-repo.gpg.key expired

### ISSUE THREAD

**Issue by Pisgah** [eclipse/mosquitto#1551]
I get this error when trying to update with apt-get update:

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repo.mosquitto.org/debian buster InRelease: The following signatures were invalid: EXPKEYSIG 61611AE430993623 Mosquitto Apt Repository <repo@mosquitto.org>

and I did:

 sudo apt-key list

got:

pub   rsa4096 2013-01-04 [SC] [expired: 2019-12-31]
      8277 CCB4 9EC5 B595 F2D2  C713 6161 1AE4 3099 3623
uid           [ expired] Mosquitto Apt Repository <repo@mosquitto.org>

System is Raspberry Pi 3B+ with Dietpi Buster

Any tip? thank you very much!

**Comment by Pisgah** [comment]
I have reinstalled a new key from Eclipse websie:

wget http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
sudo apt-key add mosquitto-repo.gpg.key

and then:

cd /etc/apt/sources.list.d/
sudo wget http://repo.mosquitto.org/debian/mosquitto-buster.list

all done!

**Comment by Elexy** [comment]
Thanks!

**Comment by Rudi1952** [comment]
I have the same issue, but was not able to resolve this.
When i give: sudo apt-get update i get the following errors

Err:4 https://repo.mosquitto.org/debian buster InRelease
  The following signatures were invalid: EXPKEYSIG 61611AE430993623 Mosquitto Apt Repository <repo@mosquitto.org>
Err:5 https://repo.mosquitto.org/debian jessie InRelease
  The following signatures were invalid: EXPKEYSIG 61611AE430993623 Mosquitto Apt Repository <repo@mosquitto.org>
Err:7 https://repo.mosquitto.org/debian stretch InRelease

My system is a RPI 3B+
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

I tried te resove it with the commands mentioned above:

wget http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
sudo apt-key add mosquitto-repo.gpg.key

but still the same error, 
pub   rsa4096 2013-01-04 [SC] [expired: 2019-12-31]
      8277 CCB4 9EC5 B595 F2D2  C713 6161 1AE4 3099 3623
uid           [ expired] Mosquitto Apt Repository <repo@mosquitto.org>

what can i do about this?

**Comment by Nic2012** [comment]
I had the same issue on Stretch (PiZero). I have fixed it by deleting old key at first:
```
apt-key list
/etc/apt/trusted.gpg
--------------------

pub   rsa4096 2013-01-04 [SC] [expired: 2019-12-31]
      8277 CCB4 9EC5 B595 F2D2  C713 6161 1AE4 3099 3623
uid           [ expired] Mosquitto Apt Repository <repo@mosquitto.org>

sudo apt-key del 30993623
```
So before y fetch new key by wget, delete it with above command. Afterwards I was able to get new key [expires: 2029-12-29] and updated mosquitto to version 1.6.8.

**Comment by Rudi1952** [comment]
The last command worked for me, besides that i had to remove the old file ' mosquitto-repo.gpg.key' from the /home/pi directory.

sudo apt-get update is working now, thanks for your help

**Comment by eos1d3** [comment]
Confirmed the above, have to  remove `mosquitto-repo.gpg.key` before using use Pisgah instructions.
