### ISSUE TITLE
mosquitto_pub --id doesn't work (-i works)

### ISSUE THREAD

**Issue by jshep321** [eclipse/mosquitto#1553]
mosquitto_pub --id idname doesn't work (default ID appears in broker logs: mosq-XXXXXXXXXXXXXXXXXX )

mosquitto_pub -i idname works as expected

**Comment by ralight** [comment]
Which version? I've tried 1.4, 1.5, 1.6, and 1.6.8 and they are all ok.

**Comment by jshep321** [comment]
I must have made a variable mistake. Works fine!  Sorry.
