### ISSUE TITLE
Mosquito_sub converts int type to char 

### ISSUE THREAD

**Issue by adityaMundhara** [eclipse/mosquitto#1554]
When broker publish an integer type value, the mosquito_sub , example 67 is sent as "C" (ASCII code conversion).

**Comment by ralight** [comment]
Yes, that is correct. MQTT doesn't for the most part tell you what the payload is. mosquitto_sub just prints everything as it is received, and integer bytes get treated as text strings.  Put another way, there is no way for mosquitto_sub to know whether the byte `67` should be printed as it is received, or converted to a text representation of 67.

One option you do have is to use output formatting to display as hex:

`mosquitto_sub -F %x ...`

**Comment by ralight** [comment]
I'm closing this because I don't think it is a bug. If you still do, please reopen and provide more details.
