### ISSUE TITLE
How to set mqtt_v5 properties?

### ISSUE THREAD

**Issue by adityaMundhara** [eclipse/mosquitto#1556]
This is a stupid question, but I'm not able to find how to set the properties for mqtt_v5, in order to pass it in v5 functions, further is documentation available for setting up the properties.

**Comment by ralight** [comment]
Everything is explained in mosquitto.h, but I realise this is a bit long to trawl through. You need the `mosquitto_property_add_*()` set of functions.

For example:

```
mosquitto_property *proplist = NULL;

mosquitto_property_add_int32(&proplist, MQTT_PROP_MESSAGE_EXPIRY_INTERVAL, 86400);
mosquitto_property_add_byte(&proplist, MQTT_PROP_PAYLOAD_FORMAT_IDENTIFIER, 1);

mosquitto_publish_v5(mosq, NULL, "topic", payloadlen, payload, 0, false, proplist);
mosquitto_property_free_all(&proplist);
```

**Comment by ralight** [comment]
I think this is answered, so I'm going to close this issue. If you need more information please feel free to reopen and ask more.
