### ISSUE TITLE
Mosquitto uses between 80% - 100% of CPU

### ISSUE THREAD

**Issue by victorct-ouyeah** [eclipse/mosquitto#1559]
I have one server running mosquitto 1.4.15, the server has 15G of RAM and 6 CPU's, here is the CPU info: 

```
- Architecture:        x86_64
- CPU op-mode(s):      32-bit, 64-bit
- Byte Order:          Little Endian
- CPU(s):              6
- On-line CPU(s) list: 0-5
- Thread(s) per core:  1
- Core(s) per socket:  1
- Socket(s):           6
- NUMA node(s):        1
- Vendor ID:           GenuineIntel
- CPU family:          6
- Model:               85
- Model name:          Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
- Stepping:            4
- CPU MHz:             2294.608
- BogoMIPS:            4589.21
- Virtualization:      VT-x
- Hypervisor vendor:   KVM
- Virtualization type: full
- L1d cache:           32K
- L1i cache:           32K
- L2 cache:            1024K
- L3 cache:            25344K
- NUMA node0 CPU(s):   0-5
```

The problem is mosquitto shows it's consuming between 80% and 100% of the CPU, most of the time and it stops sending the messages to the topics, so I have to restart whenever this happens:

<img width="1196" alt="Captura de Pantalla 2020-01-13 a la(s) 9 57 46" src="https://user-images.githubusercontent.com/56493007/72270953-9b75d980-35eb-11ea-83f3-ccc1f60278ac.png">

But on DataDog it says that the highest peak we are using of CPU, is not even 20%:
<img width="1100" alt="Captura de Pantalla 2020-01-13 a la(s) 10 02 01" src="https://user-images.githubusercontent.com/56493007/72271403-733aaa80-35ec-11ea-8f08-f25896bcb91d.png">

So I think mosquitto is only taking advantage of 1 CPU of the 6 the server has.

This is my $SYS :

<img width="647" alt="Captura de Pantalla 2020-01-13 a la(s) 10 03 40" src="https://user-images.githubusercontent.com/56493007/72271188-0de6b980-35ec-11ea-925f-4ce0be21e8ae.png">

Here is my configuration file: 

```
pid_file /var/run/mosquitto.pid
allow_anonymous false
password_file /etc/mosquitto/passwd
listener 2052 0.0.0.0
persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d

```

Any help is appreciated :D

**Comment by karlp** [comment]
You _definitely_ want to use a newer version of mosquitto :)

**Comment by victorct-ouyeah** [comment]
@karlp Will update today and let you know if it improves :D

**Comment by CrubyGoo** [comment]
You really should update your Mosquitto to a newer version. ;)

**Comment by ravaan** [comment]
@victorct-ouyeah did updating help you?

I am planning on implementing mosquitto for a large scale project, this would be a deal-breaker.

**Comment by victorct-pronto** [comment]
@ravaan Yes it worked a lot, maximum I have seen as CPU now is 11%

**Comment by karlp** [comment]
great, kinda more like expected :)  Can we close this issue then @victorct-ouyeah ?
