### ISSUE TITLE
Shared subscriptions and bridge mode

### ISSUE THREAD

**Issue by gbour** [eclipse/mosquitto#1560]
Hello,

Playing with shared subscriptions, it works very well on 1 mosquitto.
But seems not working with two mosquittos bridged together, when subscribers are not connected to the same mosquitto.

Is it planned to implement shared subscriptions over bridging ?
Cheers, Guillaume.

**Comment by ralight** [comment]
Yes. MQTT v5 support for bridges is one of the items for 1.7.

**Comment by gbour** [comment]
Hi @ralight,
This is a very good news, thanks for the information :)
