### ISSUE TITLE
Bridge Config to Azure IoT Hub won't work

### ISSUE THREAD

**Issue by fsity** [eclipse/mosquitto#1562]
Hi, 

I'm currently trying to bridge local mosquitto messages to Azure IoT Hub. I gathered the available Information for example here: [https://github.com/eclipse/mosquitto/issues/953](url) 

Unfortunately it won't work in mosquitto version 1.6.8 with the following bridge config. Even with a working mosquitto_pub command.

Pub_Command:

> mosquitto_pub -h mxchipflsei.azure-devices.net -u "mxchipflsei.azure-devices.net/iotoctopibridge/?api-version=2018-06-30" -P "SharedAccessSignature sr=mxchipflsei.azure-devices.net%2Fdevices%2Fiotoctopibridge&sig=***" -t "devices/iotoctopibridge/messages/events/" --cafile /home/pi/baltimore.pem -p 8883 -i iotoctopibridge -V mqttv311 -d  -m '{"id":"123"}'

Bridge_Config:

> # Bridge configuration
> connection azureiot-bridge
> 
> log_type all
> 
> address mxchipflsei.azure-devices.net:8883
> remote_username mxchipflsei.azure-devices.net/iotoctopibridge
> remote_password SharedAccessSignature sr=mxchipflsei.azure-devices.net%2Fdevices%2Fiotoctopibridge&sig=***
> remote_clientid iotoctopibridge
> bridge_cafile /home/pi/baltimore.pem
> try_private false
> cleansession true
> start_type automatic
> bridge_insecure false
> bridge_protocol_version mqttv311
> bridge_tls_version tlsv1.2
> notifications false
> notification_topic events/
> 
> topic devices/iotoctopibridge/messages/events/# out 1

log

> 1579163115: Bridge local.iotoctopibridge doing local SUBSCRIBE on topic devices/iotoctopibridge/messages/events/#
> 1579163115: Connecting bridge (step 1) azureiot-bridge (mxchipflsei.azure-devices.net:8883)
> 1579163115: Connecting bridge (step 2) azureiot-bridge (mxchipflsei.azure-devices.net:8883)
> 1579163115: Bridge iotoctopibridge sending CONNECT
> 1579163116: Received CONNACK on connection local.iotoctopibridge.
> 1579163116: Bridge local.iotoctopibridge sending UNSUBSCRIBE (Mid: 2, Topic: devices/iotoctopibridge/messages/events/#)
> 1579163116: Received UNSUBACK from local.iotoctopibridge

Before I used the remote id "iotoctopibridge" I had the id "iotoctopi" which was qual to the name of my raspberry. There I got Logs with information like:

> 1579162482: Bridge local.iotoctopi doing local SUBSCRIBE on topic devices/iotoctopi/messages/events/#
> 1579162482: Connecting bridge (step 1) azureiot-bridge (mxchipflsei.azure-devices.net:8883)
> 1579162482: Connecting bridge (step 2) azureiot-bridge (mxchipflsei.azure-devices.net:8883)
> 1579162482: Bridge iotoctopi sending CONNECT
> 1579162483: Received CONNACK on connection local.iotoctopi.
> 1579162483: Connection Refused: broker unavailable
> 1579162483: Socket error on client local.iotoctopi, disconnecting.

Any Ideas? 

Thanks in advance and best Regards
Florian

**Comment by karlp** [comment]
Why doyou have a remote client id? YOu don't have that in your working mosquitto_pub command.  Also, I don't think "notifications false" and "notifications_topic blah" should be given together.  You either need notifications off, local only, or a topic that azure allows publishing to.  Your remote username doesn't match your working mosquitto_pub command either.

**Comment by fsity** [comment]
The existing documentation stated, that you have to have it. See the posted [link ](https://github.com/eclipse/mosquitto/issues/953)and Microsofts docu [https://docs.microsoft.com/de-de/azure/iot-hub/iot-hub-mqtt-support](https://docs.microsoft.com/de-de/azure/iot-hub/iot-hub-mqtt-support):

> If a device cannot use the device SDKs, it can still connect to the public device endpoints using the MQTT protocol on port 8883. In the CONNECT packet, the device should use the following values:
> 
> For the ClientId field, use the deviceId...


When I delete it I get:

> 1579177030: Connecting bridge (step 1) azureiot-bridge (mxchipflsei.azure-devices.net:8883)
> 1579177030: Connecting bridge (step 2) azureiot-bridge (mxchipflsei.azure-devices.net:8883)
> 1579177030: Bridge iotoctopi.azureiot-bridge sending CONNECT
> 1579177030: Received CONNACK on connection local.iotoctopi.azureiot-bridge.
> 1579177030: Connection Refused: not authorised
> 1579177030: Socket error on client local.iotoctopi.azureiot-bridge, disconnecting.
> 1579177036: Bridge local.iotoctopi.azureiot-bridge doing local SUBSCRIBE on topic devices/iotoctopibridge/messages/events/#

The remote username probably doesn't need an api version anymore (I read it somerwhere here). Netherless I added it and commented out the notification_topic:

> # Bridge configuration
> connection azureiot-bridge
> 
> log_type all
> 
> address mxchipflsei.azure-devices.net:8883
> remote_username mxchipflsei.azure-devices.net/iotoctopi/?api-version=2018-06-30
> remote_password SharedAccessSignature sr=mxchipflsei.azure-devices.net%2Fdevices%2Fiotoctopibridge&sig=***
> remote_clientid iotoctopibridge
> bridge_cafile /home/pi/baltimore.pem
> try_private false
> cleansession true
> start_type automatic
> bridge_insecure false
> bridge_protocol_version mqttv311
> bridge_tls_version tlsv1.2
> notifications false
> #notification_topic events/
> 
> topic devices/iotoctopibridge/messages/events/# out 1


Unfortunately I still get errors:

> 1579177222: Bridge local.iotoctopibridge doing local SUBSCRIBE on topic devices/iotoctopibridge/messages/events/#
> 1579177222: Connecting bridge (step 1) azureiot-bridge (mxchipflsei.azure-devices.net:8883)
> 1579177222: Connecting bridge (step 2) azureiot-bridge (mxchipflsei.azure-devices.net:8883)
> 1579177222: Bridge iotoctopibridge sending CONNECT
> 1579177222: Received CONNACK on connection local.iotoctopibridge.
> 1579177222: Bridge local.iotoctopibridge sending UNSUBSCRIBE (Mid: 2, Topic: devices/iotoctopibridge/messages/events/#)
> 1579177222: Received UNSUBACK from local.iotoctopibridge


What can I check further?

**Comment by karlp** [comment]
You're right, I missed the clientid parameter in the original mosquitto_pub command.  In your latest post though, there are no errors now.  Is there more log?  The local unsubscribe is normal, (and you'll see a local subscribe too, you can change this iwth the "attempt_unsubscribe" if you read about what it's for and decide you don't need it)

**Comment by fsity** [comment]
Unfortunately that's all to find in the mosquitto.log. When I try to send a message through, with

> mosquitto_pub -t /devices/iotoctopibridge/messages/events/ -m '{"id":"123"}'

i get

> 1579187481: Bridge iotoctopibridge sending CONNECT
> 1579187481: Received CONNACK on connection local.iotoctopibridge.
> 1579187499: New connection from ::1 on port 1883.
> 1579187499: New client connected from ::1 as mosq-QWVmVwsZWwCN4rNSm1 (p2, c1, k60).
> 1579187499: No will message specified.
> 1579187499: Sending CONNACK to mosq-QWVmVwsZWwCN4rNSm1 (0, 0)
> 1579187499: Received PUBLISH from mosq-QWVmVwsZWwCN4rNSm1 (d0, q0, r0, m0, '/devices/iotoctopibridge/messages/events/', ... (12 bytes))
> 1579187499: Received DISCONNECT from mosq-QWVmVwsZWwCN4rNSm1
> 1579187499: Client mosq-QWVmVwsZWwCN4rNSm1 disconnected.
> 1579187541: Sending PINGREQ to local.iotoctopibridge

But that probably doesn't help. As you see I added bidge_attempt_unsubscribe false to the config. Is there a main downside of using the mosquitto.conf in that way and don't go through the conf.d folder? Thats my whole mosquitto.conf:

> # Place your local configuration in /etc/mosquitto/conf.d/
> #
> # A full description of the configuration file is at
> # /usr/share/doc/mosquitto/examples/mosquitto.conf.example
> 
> pid_file /var/run/mosquitto.pid
> 
> persistence true
> persistence_location /var/lib/mosquitto/
> 
> log_dest file /var/log/mosquitto/mosquitto.log
> 
> include_dir /etc/mosquitto/conf.d
> 
> 
> 
> 
> # Bridge configuration
> connection azureiot-bridge
> 
> log_type all
> 
> address mxchipflsei.azure-devices.net:8883
> remote_username mxchipflsei.azure-devices.net/iotoctopibridge/?api-version=2018-06-30
> remote_password SharedAccessSignature sr=mxchipflsei.azure-devices.net%2Fdevices%2Fiotoctopibridge&sig=***
> remote_clientid iotoctopibridge
> bridge_cafile /home/pi/baltimore.pem
> try_private false
> cleansession true
> start_type automatic
> bridge_insecure false
> bridge_protocol_version mqttv311
> bridge_tls_version tlsv1.2
> notifications false
> #notification_topic events/
> bridge_attempt_unsubscribe false
> 
> topic devices/iotoctopibridge/messages/events/# out 1

On the azure side I can't find my attempts as failed logs.

**Comment by ralight** [comment]
From the log:

> 1579187499: Received PUBLISH from mosq-QWVmVwsZWwCN4rNSm1 (d0, q0, r0, m0, '/devices/iotoctopibridge/messages/events/', ... (12 bytes))

And from your bridge config:

> topic devices/iotoctopibridge/messages/events/# out 1

You're sending on one topic and bridging another. The key difference is the leading `/`.

```
/devices/iotoctopibridge/messages/events/# out 1
devices/iotoctopibridge/messages/events/# out 1
```

Try fixing that and you should be fine.

**Comment by fsity** [comment]
> From the log:
> 
> > 1579187499: Received PUBLISH from mosq-QWVmVwsZWwCN4rNSm1 (d0, q0, r0, m0, '/devices/iotoctopibridge/messages/events/', ... (12 bytes))
> 
> And from your bridge config:
> 
> > topic devices/iotoctopibridge/messages/events/# out 1
> 
> You're sending on one topic and bridging another. The key difference is the leading `/`.
> 
> ```
> /devices/iotoctopibridge/messages/events/# out 1
> devices/iotoctopibridge/messages/events/# out 1
> ```
> 
> Try fixing that and you should be fine.

That sounds plausiblen. I‘ll try this the day after tomorrow when I‘m back In the Network :-)

**Comment by fsity** [comment]
> From the log:
> 
> > 1579187499: Received PUBLISH from mosq-QWVmVwsZWwCN4rNSm1 (d0, q0, r0, m0, '/devices/iotoctopibridge/messages/events/', ... (12 bytes))
> 
> And from your bridge config:
> 
> > topic devices/iotoctopibridge/messages/events/# out 1
> 
> You're sending on one topic and bridging another. The key difference is the leading `/`.
> 
> ```
> /devices/iotoctopibridge/messages/events/# out 1
> devices/iotoctopibridge/messages/events/# out 1
> ```
> 
> Try fixing that and you should be fine.

I had the chance to test it out already today. You were absolutely right! Thank you very much.

The running config now looks like that:

> 
> # Place your local configuration in /etc/mosquitto/conf.d/
> #
> # A full description of the configuration file is at
> # /usr/share/doc/mosquitto/examples/mosquitto.conf.example
> 
> pid_file /var/run/mosquitto.pid
> 
> persistence true
> persistence_location /var/lib/mosquitto/
> 
> log_dest file /var/log/mosquitto/mosquitto.log
> 
> include_dir /etc/mosquitto/conf.d
> 
> 
> 
> 
> # Bridge configuration
> connection azureiot-bridge
> 
> log_type all
> 
> address mxchipflsei.azure-devices.net:8883
> remote_username mxchipflsei.azure-devices.net/iotoctopibridge/?api-version=2018-06-30
> remote_password SharedAccessSignature sr=mxchipflsei.azure-devices.net%2Fdevices%2Fiotoctopibridge&sig=***
> remote_clientid iotoctopibridge
> bridge_cafile /home/pi/baltimore.pem
> try_private false
> cleansession true
> start_type automatic
> bridge_insecure false
> bridge_protocol_version mqttv311
> bridge_tls_version tlsv1.2
> notifications false
> #notification_topic events/
> bridge_attempt_unsubscribe false
> 
> topic devices/iotoctopibridge/messages/events/# out 1
>
