### ISSUE TITLE
mosquitto.conf: password file not found if there is a space at the end of the line.

### ISSUE THREAD

**Issue by kollokollo** [eclipse/mosquitto#1566]
If this line in /etc/mosquitto/conf.d/a.conf has a blank at the end of the line, then the passwords file is not found, because it thinks the blank is part of the filename. 

`password_file /etc/mosquitto/passwords `

Found on:
mosquitto version 1.4.10

**Comment by ralight** [comment]
Thanks, this has now been fixed.

1.4.10 is pretty old by the way, you might want to look into upgrading.
