### ISSUE TITLE
Use multi-stage build for Docker

### ISSUE THREAD

**Issue by minusdavid** [eclipse/mosquitto#1576]
Looking at https://github.com/eclipse/mosquitto/blob/6bfd52af9e29165bbf82e3c67b0c4f8310e92b43/docker/1.6/Dockerfile, it really looks like you'd benefit from switching to multi-stage builds: https://docs.docker.com/develop/develop-images/multistage-build/

You could turn that massive RUN statement into a first stage and then just copy over the relevant binaries and /mosquito folder.  Then do the group, user, permissions, etc. It would make it easier to debug, maintain, and you wouldn't have to do as much cleanup (although good job on that) to get a clean final image.

Anyway, just an idea!

**Comment by ralight** [comment]
It's a fair comment, but as an official image, the rules are a bit different. It's only relatively recently that any form of multi stage images are allowed in official images, and there are limitations on what will be accepted.

https://github.com/docker-library/faq#multi-stage-builds

If you wanted to submit a PR which uses multi-stage builds and follows the above guidelines, we could see whether the official-images team would accept it.

**Comment by minusdavid** [comment]
Yikes, it does sound much more restrictive. I had no idea.

I haven't started using Mosquitto yet, but if  I go ahead with it, I'll keep that in mind.

**Comment by ralight** [comment]
I'm happy to leave this as "you might do this at some point", but if that's the case I'd prefer to close this if that's ok.

**Comment by minusdavid** [comment]
I have so many items on my "someday" to do list that it's probably not going to happen, so close away.
