### ISSUE TITLE
Missing: docbook-xsl in Debian packaging

### ISSUE THREAD

**Issue by smurfix** [eclipse/mosquitto#1579]
Debian packaging needs a build dependency on docbook-xsl.

You may not notice because older Debian versions allowed downloading it during the build, but current Debian Testing wants to do the reproducible build thing and thus forbids network access.

**Comment by ralight** [comment]
This only applies if you are building your own debian packages based on the git repo. The debian packaging provided by debian and this project all work on the released tar archives, which don't require docbook-xsl because the man pages are already built.
