### ISSUE TITLE
9001 port is used on windows 10

### ISSUE THREAD

**Issue by pherbel** [eclipse/mosquitto#1580]
After I restarted my windows 10, I can't start my MQTT docker image. Previously it has worked.
I'm getting this error:

> ERROR: for mqtt Cannot start service mqtt: Ports are not available: listen tcp 0.0.0.0:9001: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

After I checked the port usage, it seems system service (PID 4) uses the 9001 port. It is very interesting.

Does anybody have the same issue?

**Comment by ralight** [comment]
You could try removing `-p 9001:9001` from your docker command. If you haven't configured that port for use in your mosquitto config, then that part isn't doing anything anyway.

**Comment by pherbel** [comment]
Yeah I removed and the image starts, but I'm getting errors

> Client <unknown> disconnected due to protocol error.

**Comment by ralight** [comment]
Ok, my guess would be that you are getting a mismatch between your listener and client in terms of being configured for unencrypted MQTT/encrypted MQTT/MQTT over unencrypted websockets/MQTT over encrypted websockets. Can you check what your broker configuration is, and whether the client matches what you would expect?

This shows the config options you might have:
```
# Plain MQTT
listener 1883

# Encrypted MQTT
listener 8883
cafile <path>
certfile <path>
keyfile <path>

# Plain WebSockets
listener 8000
protocol websockets

# Encrypted WebSockets
listener 8001
protocol websockets
cafile <path>
certfile <path>
keyfile <path>
```

You could also try using a different client to connect and see if that has the same problem.

**Comment by sfitts** [comment]
I've started seeing the same thing -- though it is obviously not an MQTT issue.  Suddenly port 9001 was already in use by "System" and so my Mosquitto wouldn't start.  

Based on this issue -- https://github.com/cretueusebiu/valet-windows/issues/131 it appears that Intel started using this for some of there drivers.  Bad Intel.  

There does not appear to be a way to configure that, so it is time to move MQTT to a different port.

**Comment by ralight** [comment]
@sfitts Thanks for the tip on Intel, it's good to know the cause. I've push a change to the examples in the readme to use port 8080 instead.

**Comment by ralight** [comment]
I think this can be closed now.

**Comment by martinandersen3d** [comment]
Solved.

This is a intel graphics card software related issue on windows 10.

How to fix:

In windows, go to:

Star menu
Type: Services:
Find the service called: "Intel(R) Graphics Command Center Service"
Rightclick > Properties > Startup type = Disabled

This fixed the problem for me.. :-)

**Comment by shaolonger** [comment]
> Intel(R) Graphics Command Center Service

That works for me, thx very much!

**Comment by jinweijie** [comment]
> Solved.
> 
> This is a intel graphics card software related issue on windows 10.
> 
> How to fix:
> 
> In windows, go to:
> 
> Star menu
> Type: Services:
> Find the service called: "Intel(R) Graphics Command Center Service"
> Rightclick > Properties > Startup type = Disabled
> 
> This fixed the problem for me.. :-)

Thanks! Also works for me! Hey Intel, what are you doing?

**Comment by self-debug** [comment]
> > Solved.
> > This is a intel graphics card software related issue on windows 10.
> > How to fix:
> > In windows, go to:
> > Star menu
> > Type: Services:
> > Find the service called: "Intel(R) Graphics Command Center Service"
> > Rightclick > Properties > Startup type = Disabled
> > This fixed the problem for me.. :-)
> 
> Thanks! Also works for me! Hey Intel, what are you doing?


Works for me too! Thanks a lot!

**Comment by RajahArumugam** [comment]
Worked for me Thanks

**Comment by hasanbasri1993** [comment]
> Solved.
> 
> This is a intel graphics card software related issue on windows 10.
> 
> How to fix:
> 
> In windows, go to:
> 
> Star menu
> Type: Services:
> Find the service called: "Intel(R) Graphics Command Center Service"
> Rightclick > Properties > Startup type = Disabled
> 
> This fixed the problem for me.. :-)

solved
thanks you

**Comment by klassisch** [comment]
disabling Intel(R) Graphics Command Center Service worked for me as well. Win10 Pro stock without Docker, VM etc. Thanks a lot for sharing this fix!

**Comment by wll1234** [comment]
> # SOLVED :: SOLUTION:
> This is a intel graphics card software related issue on windows 10.
> 
> # How to fix:
> **In windows, go to:**
> 
> * Star menu
> * Type: **Services**
> * Find the service called: **Intel(R) Graphics Command Center Service**
> * Rightclick > Properties > Startup type = Disabled
> 
> This fixed the problem for me.. :-)

It works! thanks.
