### ISSUE TITLE
--remove-retained does not consider filtered topics

### ISSUE THREAD

**Issue by MrMcX** [eclipse/mosquitto#1585]
The example `mosquitto_sub -t 'bbc/#' -T bbc/bbc1 --remove-retained` from the man page is currently not excluding the topic filtered with -T.

To achieve this, the file `client/sub_client.c` should be changed to move the respective block (lines 79-81) after the statement checking for filtered topics (lines 91-97)

**Comment by ralight** [comment]
Thank you for this. I've pushed the change that fixes this. I didn't look at the updates properly, I just saw the "ubilab-escape/operator" line and assumed they were all related to that. That means I didn't see your pull request, I'm sorry it wasn't intentional that I didn't use it.

**Comment by MrMcX** [comment]
Thank you for fixing it so fast, I had problem with signing off the commit correctly anyway ;)
