### ISSUE TITLE
Issue with AT+S.WSOCKW coamnnd in SPWF04SA WiFi Module

### ISSUE THREAD

**Issue by 12sameera** [eclipse/mosquitto#1591]
Hi All,
I am developing a IoT application using SPWF04SA using WebSockets. The problem which I have faced at the moment is sending data to a WebServer using websockets.

When i send data for the first time it works. But, when a try to send multiple times without closing the connection, the data is not sent to the server. Here is the sample code:

`
  memset(&Command[0],0,100);//clear the content of the command
 strcat(Command,"AT+S.WSOCKW=0,1,1,0,");//concatenate command to the array
 Command[20]='7';//define the length of data
 Command[21]='\r';//set carriage return following the length field
 strcat(Command,"*PARAM?");//Set the payload
 _Read_From_WiFi_Module(Command,29,0,1,0,0);//Send data to the verver

HAL_Delay(5000);
//This part is not sending data
 memset(&Command[0],0,100);//clear the content of the command
 strcat(Command,"AT+S.WSOCKW=0,1,1,0,");
 Command[20]='7';
 Command[21]='\r';
 strcat(Command,"*PARAM?");
 _Read_From_WiFi_Module(Command,29,0,1,0,0);`

The webserver is working fine. When i created a client HTML Websocket and send data continuously, the data is sent without any issue.
Therefore, I believe that the problem is with the SPWF04 end.
Any help is very much appreciated.
Thanks.

**Comment by ralight** [comment]
I'm sorry, I don't see how this relates to Mosquitto. You would be better off asking for support at the appropriate SPWF04SA place.
