### ISSUE TITLE
Mosquitto with SSL in docker container

### ISSUE THREAD

**Issue by ochstobi** [eclipse/mosquitto#1592]
Hello, 
I try to log the mosquittos logs to an file. So I added this line in mosquitto.config: log_dest file /mosquitto/log/mosquitto.log

The applicationis started in docker with this command: `sudo docker run --name="mqtt" --restart=always --net=host -tid -p 8883:8883 -p 9001:9001 -v /volume1/docker/mqtt/config:/mosquitto/config:ro -v /volume1/docker/mqtt/log:/mosquitto/log -v /volume1/docker/mqtt/data/:/mosquitto/data/  eclipse-mosquitto`

But at startup I get this error: **Error: Unable to open log file /mosquitto/log/mosquitto.log for writing.**
What am I missing?

Thanks in advance,
Tobias

**Comment by michaeliu** [comment]
Add / after
 -v /volume1/docker/mqtt/log:/mosquitto/log ？

Not sure but try this：
-v /volume1/docker/mqtt/log/:/mosquitto/log/

**Comment by ochstobi** [comment]
> 
> 
> Add / after
> -v /volume1/docker/mqtt/log:/mosquitto/log ？
> 
> Not sure but try this：
> -v /volume1/docker/mqtt/log/:/mosquitto/log/

Sadly this didn't work

**Comment by michaeliu** [comment]
touch /volume1/docker/mqtt/log/mosquitto.log
chmod 777 /volume1/docker/mqtt/log/mosquitto.log

try this for check if this is a premition issue？

**Comment by ochstobi** [comment]
Thanks for this hint. This solved the problem. Forgot about the permissions thing on linux.
