### ISSUE TITLE
What happens with messages exceeding max_queued_messages & max_queued_bytes limit?

### ISSUE THREAD

**Issue by Andreyooo** [eclipse/mosquitto#1593]
Do they get deleted or maybe the new messages replace the old in queue?

**Comment by karlp** [comment]
This is (IMO quite clearly) documented: https://mosquitto.org/man/mosquitto-conf-5.html  Please follow up if you feel the documentation isn't clear on this behaviour.

**Comment by Andreyooo** [comment]
I don`t see any information what happens with messages that exceed the limit. Is it assumed they get ignored?

**Comment by karlp** [comment]
From the manual linked, under max_queued_bytes  (max_queued_messages says to see max_queued_bytes for more information)
```
...
Once this limit has been reached, subsequent messages will be silently dropped.
...
```

**Comment by Andreyooo** [comment]
I see, ty
