### ISSUE TITLE
Question about persistent sessions

### ISSUE THREAD

**Issue by Andreyooo** [eclipse/mosquitto#1594]
During a persistent session, if connection is lost, subscriptions are saved and incoming QoS 1&2 messages are queued. 
Is it possible to have the subscriptions-saved feature, without the queueing QoS 1&2 messages feature?

**Comment by karlp** [comment]
you can use qos 0, and you can set max queued messages to 0, but I'm curious what the purpose would be.  If you don't want messages queued while you were offline, just resubscribe when you connect.

**Comment by Andreyooo** [comment]
Ok, thx.
I´m adding a mqtt-service to a home automation system. Subscribes and Unsubscribes are fired automaticly and information about existing subscriptions are not stored yet, so resubscribing would need more implementation.
The hardware is limited and queueing offline messages is not needed, retained messages are enough.

Will test what the better option here is.
