### ISSUE TITLE
Mosquitto with SSL is not working in Docker

### ISSUE THREAD

**Issue by Bean900** [eclipse/mosquitto#1595]
Hello :)

I am trying to start MQQT-Mosquitto in Docker (I tried version 1.6.8 and 1.4.12). This works to the point where I use ssl / tls.
Once this is configured, I get the following error in mqtt.fx:
`org.eclipse.paho.client.mqttv3.MqttException: Unable to connect to server` and `Caused by: java.net.ConnectException: Connection refused: connect`
Now the funny part of the story: D
When starting Mosquitto 1.4.15 with the same configuration in Ubuntu (so no docker) (installed via Apt), everything works.

Here is my Dockerfile:
```
FROM eclipse-mosquitto:1.6.8

ADD mosquitto.conf /mosquitto/config/mosquitto.conf
ADD passwd /passwd

ADD cert/m2mqtt_ca.crt /m2mqtt_ca.crt
ADD cert/m2mqtt_srv.crt /m2mqtt_srv.crt
ADD cert/m2mqtt_srv.key /m2mqtt_srv.key

EXPOSE 8883
```

And my config:
```
port 8883
cafile /m2mqtt_ca.crt
certfile /m2mqtt_srv.crt
keyfile /m2mqtt_srv.key
tls_version tlsv1.2
log_type all
allow_anonymous false
password_file /passwd
```
Maybe one of you can help me :/

**Comment by michaeliu** [comment]
Could you check docker log? maybe  some
 hints there.

**Comment by Bean900** [comment]
In Docker nothing is happening :/ 
There is just the Info that the port is opened at ipv4 and ipv6

**Comment by michaeliu** [comment]
Try telnet MQTT port of the ip address at docker host，and what the command to start docker？ do you expose port with -p？

**Comment by Bean900** [comment]
![grafik](https://user-images.githubusercontent.com/12278604/74506669-85b14800-4efa-11ea-93fb-ec5007f33967.png)

thx.
But funny that it works without ssl without -p
