### ISSUE TITLE
mosquitto on docker, ca-certificate not found

### ISSUE THREAD

**Issue by coolcodecding** [eclipse/mosquitto#1596]
I am trying to run an encrypted communication with mosquito and therefore wanted to use ssl/tls.
Mosquitto is running on a raspberry pi 4 with raspbian buster.

I followed this tutorial:
http://www.steves-internet-guide.com/mosquitto-tls/

I created the certificates with openssl and edited the mosquitto.conf file accordingly:

`###### ENABLE TLS ######
port 8883
cafile cafile /home/pi/fhem-docker/mqtt/config/ca.crt
certfile /home/pi/fhem-docker/mqtt/config/server.cert
keyfile /home/pi/fhem-docker/mqtt/config/server.key
`

Restarting the container leads to the following log:

`1581624014:` mosquitto version 1.6.8 starting
1581624014: Config loaded from /mosquitto/config/mosquitto.conf.
1581624014: Opening websockets listen socket on port 9001.
1581624014: Opening ipv4 listen socket on port 8883.
1581624014: Opening ipv6 listen socket on port 8883.
1581624014: Error: Unable to load CA certificates. Check cafile "cafile /home/pi/fhem-docker/mqtt/config/ca.crt".
1581624014: Error: No such file or directory`

I tried `cd /home/pi/fhem-docker/mqtt/config/`, succesfully and the `ca.crt` was inside, as expected.

What could be the reason for this behaviour?
I have tried different folders and names, but i keep geeting the same result.

I would be happy for any advice!

**Comment by Bean900** [comment]
Did you add your ca.crt to your Docker container?
Did you mount the certificate as a volume?
Note that your Docker image will not have access to your files on your PC if it is not configured.
https://docs.docker.com/storage/

You can do something like this in your Dockerfile:
```
...
ADD /home/pi/fhem-docker/mqtt/config/ca.crt /ca.crt
...
```

And than in your config:
```
...
cafile /ca.crt 
...
```

**Comment by coolcodecding** [comment]
Thanks for responding! This is how my command looks like now: 

```
sudo docker run -itd \
--name="mosquitto_test" \
--restart on-failure \
-p 1883:1883 \
-p 8883:8883 \
-p 9001:9001 \
-v /home/pi/fhem-docker/mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf  \
-v  /home/pi/fhem-docker/mqtt/config/ca.crt:/ca.crt \
-v  /home/pi/fhem-docker/mqtt/data:/mosquitto/data \
-v  /home/pi/fhem-docker/mqtt/log:/mosquitto/log \
eclipse-mosquitto
```
with the following log:

```
1582013151: mosquitto version 1.6.8 starting
1582013151: Config loaded from /mosquitto/config/mosquitto.conf.
1582013151: Opening ipv4 listen socket on port 8883.
1582013151: Opening ipv6 listen socket on port 8883.
1582013151: Error: Unable to load CA certificates. Check cafile "/home/pi/fhem-docker/mqtt/config/ca.crt".
1582013151: Error: No such file or directory
```
I have tried `sudo chmod 755 /home/pi/fhem-docker/mqtt/*`

Any other ideas or recomendations?

**Comment by Bean900** [comment]
In your mosquitto.conf, you have to set `cafile` to `/ca.crt` and not to `/home/pi/fhem-docker/mqtt/config/ca.crt`

**Comment by coolcodecding** [comment]
This was the point! So for those who have the same problem, this is how i got it working:
mosquitto.conf:
`port 8883

cafile /ca.crt
keyfile /server.key
certfile /server.crt
tls_version tlsv1.2

persistence true
persistence_location /mosquitto/data/
`
and execute

`sudo docker run -itd \
--name="mosquitto_test" \
--restart on-failure \
-p 1883:1883 \
-p 8883:8883 \
-p 9001:9001 \
-v /home/pi/fhem-docker/mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf  \
-v  /home/pi/fhem-docker/mqtt/config/ca.crt:/ca.crt \
-v  /home/pi/fhem-docker/mqtt/config/server.crt:/server.crt \
-v  /home/pi/fhem-docker/mqtt/config/server.key:/server.key \
-v  /home/pi/fhem-docker/mqtt/data:/mosquitto/data \
-v  /home/pi/fhem-docker/mqtt/log:/mosquitto/log \
eclipse-mosquitto`

It seems to be a bit chaotic with all the volumes, but somehow i couldn't get it working otherwis. For now it does the job and secures my connection and I might give it a cleaner try another day!

Thanks for your support @Bean900 !
