### ISSUE TITLE
 Fix for Corrupt Mosquitto Database / Suddenly Stopped Sending Messages #1214 

### ISSUE THREAD

**Issue by spietika** [eclipse/mosquitto#1601]
I am troubleshooting a problem that may be caused by #1214. Based on the comments in the original issue, it is unclear in which version this fix has been released in.

Could you link the fix commit hash or release version to the original issue to help trace this.

**Comment by ralight** [comment]
I believe it is this change, which is part of 1.6.3.

https://github.com/eclipse/mosquitto/commit/587debc0132f733f6ec33187b4d4ad4a3e007f17

**Comment by spietika** [comment]
The last comment in the original issue implied that the fix would not have been in 1.6.3. But double-checking from git log, the commit you mentioned is indeed included in the release tagged v1.6.3.

Thanks for the clarification and quick reply!
