### ISSUE TITLE
specific interface listening?

### ISSUE THREAD

**Issue by fredless** [eclipse/mosquitto#1602]
Beating my head against the wall on something that seems like it should be simple.  _EDIT because I screwed up the problem details the 1st time through._

Mosquitto 1.6.8 on debian buster, with multiple ipv4 interfaces.  ipv6 disabled on OS.  no iptables rules active.

Works fine when started _without_ the below listener directive, accepts thing like `mosquitto_sub -h 127.0.0.1 -t testtopic` without complaint.

```bash
fredless@localhost:/etc/mosquitto# netstat -tnlp                     
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:1833            0.0.0.0:*               LISTEN      17550/mosquitto  
```

When I add the `listener` line below and restart, appears to be listening on the single interface as expected, but the machine does not accept connections on the intended interface.

```bash
fredless@localhost:/etc/mosquitto# cat mosquitto.conf 
# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d

listener 1833 127.0.0.1

fredless@localhost:/etc/mosquitto# cat conf.d/default.conf 
allow_anonymous true
password_file /etc/mosquitto/passwd
```

```bash
fredless@localhost:/etc/mosquitto# netstat -tnlp
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:1833      0.0.0.0:*               LISTEN      20253/mosquitto    

fredless@localhost:/etc/mosquitto# mosquitto_sub -h 127.0.0.1 -t testtopic
Error: Connection refused
```

**Comment by ralight** [comment]
Your listener is on port 1833. MQTT normally runs on port 1883. You're running mosquitto_pub without a port option, so it will default to port 1883. Either change the port in your config, or use `mosquitto_pub -h 127.0.0.1 -t testtopic -p 1833`.

**Comment by fredless** [comment]
Ugh - typos. Can't believe I didn't spot that. I stared at this for a long while. Thank you.
