### ISSUE TITLE
Mosquitto Auth Plugin never gets called when client connects via Websockets

### ISSUE THREAD

**Issue by WebDust21** [eclipse/mosquitto#1604]
This is a really weird bug, and seemingly quite a major one.  Unless there's something wrong with my MQTT configuration.
My setup: Mosquitto 1.6.8 (latest as of this time) running on Amazon EC2, together with a standard LAMP stack (Linux + Apache Web + MySQL + PHP) for a web server.  I am using the "mosquitto-auth-plug-master" authentication plugin (with some bug fixes + customized modifications) to handle authentication.  So far so good.

It is being used for an IoT project, with ESP32's as device clients.  No issues there.
One user client I've tested is the IoT MQTT Panel app (connecting via TCP @ port 1883), which works as expected, no issues.  
Another client I have (where I noticed the issue) is a web browser running the Paho MQTT client (connecting over websockets @ port 9001).  This is where things get interesting.  User/password authentication is working fine.  But inexplicably, the "mosquitto_auth_acl_check" routine in the auth plugin NEVER gets called.  All requests (subscribe, read, write) are simply allowed by Mosquitto.  Here's a sample log output:

> 1582075331: Loading config file /etc/mosquitto/conf.d/sysconfig.conf
> 1582075331: mosquitto version 1.6.8 starting
> 1582075331: Config loaded from /etc/mosquitto/mosquitto.conf.
> 1582075331: Loading plugin: /home/ubuntu/www/auth-plug.so
> 1582075331: |-- *** auth-plug: startup
> 1582075331:  ├── Username/password checking enabled.
> 1582075331:  ├── TLS-PSK checking enabled.
> 1582075331:  └── Extended authentication not enabled.
> 1582075331: |-- ** Configured order: mysql
> 
> 1582075331: |-- }}}} MYSQL
> 1582075331: |-- SSL is disabled
> 1582075331: Opening websockets listen socket on port 9001.
> 1582075331: Opening ipv4 listen socket on port 1883.
> 1582075331: Opening ipv6 listen socket on port 1883.
> 1582075352: New client connected from ###.###.###.### as webclient30211 (p2, c1, k60).
> 

That's all I ever get on log from the Websockets client--although it most certainly is reading from about 8 different channels every 5 seconds, not to mention writing back to one channel.

Here's a log output with the IoT MQTT Panel app.  Same login credentials, same topics--the only difference here is that I'm connected over port 1883, standard TCP:

> 1582076238: Loading config file /etc/mosquitto/conf.d/sysconfig.conf
> 1582076238: mosquitto version 1.6.8 starting
> 1582076238: Config loaded from /etc/mosquitto/mosquitto.conf.
> 1582076238: Loading plugin: /home/ubuntu/www/auth-plug.so
> 1582076238: |-- *** auth-plug: startup
> 1582076238:  ├── Username/password checking enabled.
> 1582076238:  ├── TLS-PSK checking enabled.
> 1582076238:  └── Extended authentication not enabled.
> 1582076238: |-- ** Configured order: mysql
> 
> 1582076238: |-- }}}} MYSQL
> 1582076238: |-- SSL is disabled
> 1582076238: Opening websockets listen socket on port 9001.
> 1582076238: Opening ipv4 listen socket on port 1883.
> 1582076238: Opening ipv6 listen socket on port 1883.
> 1582076293: New connection from ###.###.###.### on port 1883.
> 1582076293: |-- mosquitto_auth_unpwd_check(#####USERNAME#####)
> 1582076293: |-- ** checking backend mysql
> 1582076293: |-- getuser(#####USERNAME#####) AUTHENTICATED=1 by mysql
> 1582076293: New client connected from ###.###.###.### as Control 011ts (p2, c1, k60, u'#####USERNAME#####').
> 1582076294: |-- mosquitto_auth_acl_check(clientid: Control 011ts, username: #####USERNAME#####, topic: #####TOPIC#####, access: 4)
> 1582076294: |-- Device Owner: #####USERNAME#####(THESE ARE MY DEBUG OUTPUTS)
> 1582076294: |-- Requester: #####USERNAME#####(DITTO)
> 1582076294: |-- aclcheck(#####USERNAME#####, #####TOPIC#####, 4) trying to acl with mysql
> 1582076294: |-- aclcheck(#####USERNAME#####, #####TOPIC#####, 4) AUTHORIZED=1 by mysql
> 1582076294: |--  Cached  [63BDC90CDD6F33871D4AB57039F067CC0B3254B0] for (Control 011ts,#####USERNAME#####,4)
> 
and on and on for another couple of pages of ACL authentication requests, new ones for every single request.

Now before we blame the Paho MQTT client, I did a test.  I edited the configuration in the IoT MQTT Panel app, switching the protocol from TCP @ 1883 to Websockets @ 9001.

> 1582076310: |-- mosquitto_auth_acl_check(clientid: Control 011ts, username: ####USERNAME####, topic: ####WRITE TO TOPIC####, access: 2)
> 1582076310: |-- aclcheck(####USERNAME####, ####WRITE TO TOPIC####, 2) CACHEDAUTH: 0
> 1582076310: |-- mosquitto_auth_acl_check(clientid: Control 011ts, username: ####USERNAME####, topic: ####WRITE TO TOPIC####, access: 1)
> 1582076310: |-- aclcheck(####USERNAME####, ####WRITE TO TOPIC####, 1) CACHEDAUTH: 0
> 1582076355: Client Control 011ts disconnected.  ###SWITCHING TO WEBSOCKETS###
> 1582076363: New client connected from ###.###.###.### as Control 011ts (p2, c1, k60, u'####USERNAME####').
> 

And that's all I got.

What in the world is going on here?  If I connect over TCP -> ACL auth plugin works.  If I connect over Websockets -> there is no ACL authentication, everything is just allowed.

Suggestions?

EDIT: Was just reading over it again, and noticed that the "mosquitto_auth_unpwd_check" user verification check wasn't getting called either.  Sure enough: an invalid username + password check goes right through "accepted."  But if I try it on TCP, the invalid username + password gets immediately rejected.  What in the world is going on here?  (I'd disable Websockets in a heartbeat if there was any way to connect to MQTT over TCP from a web browser!)  Help!

**Comment by ralight** [comment]
My guess here is that you're using `per_listener_settings true`, and not configuring the plugin for both listeners.

There are two configurations below and the log results for both of them when connecting a TCP and WebSockets client. All plugin_debug.so does is print out a message when each plugin call is made, and allows everything. It also produces colour coded output, but github isn't letting me upload pictures today.

Does that help?

# Test 1
```
listener 9001
protocol websockets

listener 1883

auth_plugin ./plugin_debug.so
```

Results:

```
1582814653: mosquitto version 1.6.8 starting
1582814653: Config loaded from m.conf.
1582814653: Loading plugin: ./plugin_debug.so
PLUGIN ::: mosquitto_auth_plugin_version()
1582814653:  ├── Username/password checking enabled.
1582814653:  ├── TLS-PSK checking enabled.
1582814653:  └── Extended authentication enabled.
PLUGIN ::: mosquitto_auth_plugin_init(,,0)
PLUGIN ::: mosquitto_auth_security_init(,,0, 0)
1582814653: Opening websockets listen socket on port 9001.
1582814653: Opening ipv4 listen socket on port 1883.
1582814653: Opening ipv6 listen socket on port 1883.
1582814655: New connection from 127.0.0.1 on port 1883.
PLUGIN ::: mosquitto_auth_unpwd_check((nil), roger, roger)
1582814655: New client connected from 127.0.0.1 as mosq-YeHwUzLzPXQMfEtO3H (p2, c1, k60, u'roger').
PLUGIN ::: mosquitto_auth_acl_check((nil), 4, roger, this is the tcp client subscribing)
PLUGIN ::: mosquitto_auth_unpwd_check((nil), username, username)
1582814657: New client connected from 127.0.0.1 as auto-C62B22BE-E307-9A86-6709-079F0FA69BE1 (p2, c1, k60, u'username').
PLUGIN ::: mosquitto_auth_acl_check((nil), 4, username, this is the websockets client subscribing)
```

# Test 2

```
per_listener_settings true

listener 9001
protocol websockets

listener 1883

auth_plugin ./plugin_debug.so
```

Results:
```
1582814746: mosquitto version 1.6.8 starting
1582814746: Config loaded from mp.conf.
1582814746: Loading plugin: ./plugin_debug.so
PLUGIN ::: mosquitto_auth_plugin_version()
1582814746:  ├── Username/password checking enabled.
1582814746:  ├── TLS-PSK checking enabled.
1582814746:  └── Extended authentication enabled.
PLUGIN ::: mosquitto_auth_plugin_init(,,0)
PLUGIN ::: mosquitto_auth_security_init(,,0, 0)
1582814746: Opening websockets listen socket on port 9001.
1582814746: Opening ipv4 listen socket on port 1883.
1582814746: Opening ipv6 listen socket on port 1883.
1582814747: New connection from 127.0.0.1 on port 1883.
PLUGIN ::: mosquitto_auth_unpwd_check((nil), roger, roger)
1582814747: New client connected from 127.0.0.1 as mosq-YeHwUzLzPXQMfEtO3H (p2, c1, k60, u'roger').
PLUGIN ::: mosquitto_auth_acl_check((nil), 4, roger, this is the tcp client subscribing)
1582814787: New client connected from 127.0.0.1 as auto-04978E67-0BD6-EA5E-2CB4-CC30FC0356CD (p2, c1, k60, u'username').
```

**Comment by ralight** [comment]
![test1](https://user-images.githubusercontent.com/79578/75455463-5c200400-5971-11ea-8e3b-2ed5bdffeba7.png)
![test2](https://user-images.githubusercontent.com/79578/75455482-604c2180-5971-11ea-9a13-ca16f8937c05.png)

**Comment by WebDust21** [comment]
OK, so I bumped "per_listener_settings" out, and auth plugin over Websockets works perfectly now.  (I couldn't imagine that such a major thing wasn't implemented in Mosquitto!)  Works on TCP as well.

@ralight Thank you very much for your response.  Looks like I already had a "sniffer" subscribing to "#" on the server due to the nonworking auth on websockets...but now the auth plugin is happily rejecting them!  Thanks again for such a marvelous piece of software.

**Comment by ralight** [comment]
That part of the docs isn't meant to encompass the whole of the effect of per_listener_settings. If you look further down the mosquitto.conf man page, or in the example mosquitto.conf then I hope you would agree it is explained more adequately. I completely agree that the part you are referring to isn't sufficiently clear, and might be as far as someone would read. I will see about improving it.
