### ISSUE TITLE
mosquitto_loop returns MOSQ_ERR_INVAL for big data

### ISSUE THREAD

**Issue by nedo99** [eclipse/mosquitto#1608]
Hi,

`mosquitto_loop` returns `MOSQ_ERR_INVAL` when sending a bigger amount of data.

- Sending data with size ~66KB - works fine - no errors
- Sending big data ~310KB - MOSQ_ERR_INVAL - calling mosquitto_socket says socket is 1119, which is bigger than `FD_SETSIZE ` (1024). According to your code that is the reason you return `MOSQ_ERR_INVAL`.

An alternative is using read and write loop instead:
```
mosquitto_loop_read()
mosquitto_loop_write()
```
but this is still not the desired solution since these are blocking calls, and `max_packets` parameter is unused right now. This can result in a big blocking call for huge amount of data.

**_NOTE: This issue is re-raising the issue https://github.com/eclipse/mosquitto/issues/1299 since there were no follow up for more than 6 months._**

Regards,
Nedim

**Comment by karlp** [comment]
That doesn't in anyway make it a new issue.

**Comment by nedo99** [comment]
> 
> 
> That doesn't in anyway make it a new issue.

That is clear, I just wanted to get attention to the old one. I will close this one.

**Comment by karlp** [comment]
Simply commenting on the old one marked it as recently updated again, and sent mail to everyone watching,  absolutely no need for making clone issues.
