### ISSUE TITLE
Multiple new connections from 172.17.0.1 upon start.

### ISSUE THREAD

**Issue by O14P** [eclipse/mosquitto#1609]
I'm new to Docker and Mosquitto and I'm encountering following issue. Anyone a tip?

Latest version of "Docker for Mac" and "Eclipse-Mosquitto", starting the Docker with the following:  `docker run -p 1883:1883 -p 9001:9001 --name mqtt --restart=always  -tid`
 
I get following output:
1582471440: mosquitto version 1.6.8 starting
1582471440: Config loaded from /mosquitto/config/mosquitto.conf.
1582471440: Opening ipv4 listen socket on port 1883.
1582471440: Opening ipv6 listen socket on port 1883.
1582471440: New connection from 172.17.0.1 on port 1883.
1582471440: Client <unknown> disconnected due to protocol error.
1582471441: New connection from 172.17.0.1 on port 1883.
1582471441: Client <unknown> disconnected due to protocol error.
1582471442: New connection from 172.17.0.1 on port 1883.
1582471442: Client <unknown> disconnected due to protocol error.
1582471443: New connection from 172.17.0.1 on port 1883.
1582471443: Client <unknown> disconnected due to protocol error.
1582471444: New connection from 172.17.0.1 on port 1883.
1582471444: Client <unknown> disconnected due to protocol error.
1582471445: New connection from 172.17.0.1 on port 1883.
1582471445: Client <unknown> disconnected due to protocol error.
1582471446: New connection from 172.17.0.1 on port 1883.
1582471446: Client <unknown> disconnected due to protocol error.
1582471447: New connection from 172.17.0.1 on port 1883.
1582471447: Client <unknown> disconnected due to protocol error.
1582471448: New connection from 172.17.0.1 on port 1883.
1582471448: Client <unknown> disconnected due to protocol error.
1582471449: New connection from 172.17.0.1 on port 1883.
1582471449: Client <unknown> disconnected due to protocol error.
1582471450: New connection from 172.17.0.1 on port 1883.
1582471450: Client <unknown> disconnected due to protocol error.
1582471451: New connection from 172.17.0.1 on port 1883.
1582471451: Client <unknown> disconnected due to protocol error.
1582471492: New connection from 172.17.0.1 on port 1883.
1582471492: Client <unknown> disconnected due to protocol error.
1582471493: New connection from 172.17.0.1 on port 1883.
1582471493: Client <unknown> disconnected due to protocol error.
1582471494: New connection from 172.17.0.1 on port 1883.
1582471494: Client <unknown> disconnected due to protocol error.
1582471495: New connection from 172.17.0.1 on port 1883.
1582471495: Client <unknown> disconnected due to protocol error.
1582471496: New connection from 172.17.0.1 on port 1883.
1582471496: Client <unknown> disconnected due to protocol error.
1582471497: New connection from 172.17.0.1 on port 1883.
1582471497: Client <unknown> disconnected due to protocol error.

Nothing should be trying to connect, how to get rid of these connection attempts?

Thank you.

**Comment by ralight** [comment]
I don't think this is likely to be related to Mosquitto. Running something like `netstat -atnp` might give you an idea what is trying to connect. Alternatively use wireshark or tcpdump to see what is actually being sent to the broker, that might give a clue.

**Comment by BrandtHill** [comment]
172.17.0.1 seems like an interface for another docker container. Maybe run `docker ps` and `docker ps -a` to see if another container is running and trying connect to your mosquitto instance.

**Comment by ralight** [comment]
This hasn't received any updates for a while, so I'm assuming it's fixed. If that's not the case, please reopen and provide some more details.
