### ISSUE TITLE
topic subscription control

### ISSUE THREAD

**Issue by danielstock** [eclipse/mosquitto#1610]
if my system has thousands of devices, authentication plugin could be used for login access control.

it is requied that each device could only receive the data of its own,   how could this be done?

specify one unique subscription topic for each device?

**Comment by ralight** [comment]
Yes, that would work. If you're writing your own plugin already, then just using the acl check should work fine. You probably want to include the username in your topic (rather than the client id). The client id is unique on the broker, but clients can pick which client id they want (although you can control that in the plugin as well, on authentication). The username is authenticated by your plugin, so it is safer to use. Note that you must deny clients with `#` or `+` in their usernames if they are going to be in a topic, otherwise it may allow access to topics they are not authorised to, or result in a topic which it is not possible to publish to.

**Comment by danielstock** [comment]
thanks for your reply!

(1) i found the following project in github
https://github.com/jpmens/mosquitto-auth-plug/blob/master/examples/mysql.sql
there are two tables:  users and acls
i could define the username and corresponding topic for each devcie there:
    INSERT INTO users (username, pw, super) VALUES ('dev1', 'pwd1',	0);
    INSERT INTO acls (username, topic, rw) VALUES ('dev1', 'datatopic/dev1', 2);
that'll do the acl check fine.

(2)what is client id?  does it mean the identification specified for the mosquitto client connection, which could be  random, and has nothing to do with the username?

**Comment by BrandtHill** [comment]
Client ID is separate from the username. It's usually randomly generated, but MQTT client libraries often allow you to set it manually. Multiple connections cannot be made to a broker with the same client ID, it should have some element of uniqueness or randomness. Setting the client ID when connecting might be something like `clientId = "my_app_" + randomString(10)`

If you're looking to do something on a per-device basis without any additional plugins, checkout the "acl" and "patterns" section of [the manual](https://mosquitto.org/man/mosquitto-conf-5.html)
You can do something like this: `pattern v1/%u/data/# readwrite`
The %u represents the username used to login, so given each device would has their own username, 
 they would have access to their own topics: `myfirstdevice` would have access to `v1/myfirstdevice/data/#`, `device2` would have access to `v1/device2/data/#`, etc.

**Comment by danielstock** [comment]
@BrandtHill   thanks a lot!
the pattern %u mode is used for username basic.  so i only have to write one single sentence like 'pattern v1/%u/data/# readwrite'  in the config file, even though i might have thousands of devices?

and what about the logging access control (without additional plugins) for this ,  should i create different username/pwd for each device in the pwfile ?

**Comment by BrandtHill** [comment]
Yes, the `pattern` statements allow you to apply blanket rules for all usernames or clientIds by substituting `%u` for username and `%c` for clientId. As I mentioned, though, clientId is usually partially or fully randomly generated, so `%u` username substitution is probably the most useful.
An additional idea might be to have an `admin` user that's allowed to see all the topics, so the acl_file would look something like this:
```
# Following 'topics' apply to 'admin' user
user admin
topic     v1/+/data/#         readwrite
topic     otheradminstuff/#   readwrite

# Following 'pattern' applies to all users, and %u is substituted
pattern   v1/%u/data/#        readwrite 
```

For your password file, you'll want each device to have a different usename/password if you plan on using the `pattern %u` substitution and/or you're concerned about one device being able to read/write on another device's topic.
The `mosquitto_passwd` utility that comes with mosquitto will help you with manage this process. Here's an example of a script using the `-b` option to create/update multiple users at the same time:
```bash
#!/usr/bin/env bash

PASSWD_FILE='./my_mosquitto_passwords'
USERS_AND_PASSES=('dev1 3ggn0g' 'dev2 pickleree' 'dev3 cr3m34ngl4is3')

touch "$PASSWD_FILE"
for i in "${USERS_AND_PASSES[@]}"; do
        USER=$(echo $i | awk '{ print $1 }')
        PASS=$(echo $i | awk '{ print $2 }')
        echo "--- Username: $USER, Password: $PASS"
        mosquitto_passwd -b "$PASSWD_FILE" "$USER" "$PASS"
done
```
The resulting `my_mosquitto_passwords` file will look something like this, where each line has username followed by the salted password hash:
```
dev1:$6$Tiy44JeXGcjHp3qO$TQO0JHdf9FZ+dUKqb/0kYqMKWylSQOw6Wc+f7aSc5Hp/37+fD8OzoE9YuApeYxYRM7T5DS8lF4mMEQZ/mRFjlw==
dev2:$6$PcD+D8+08GwMfVJW$LJSkHBpR4C2d9ObnEmpe8uTvG6j4SvyPA7FQl7GzsZroAOnO9wZnW2oZPFiiHY5LPwdF6fD6G4SK9U69E64kAQ==
dev3:$6$zW4DCF7OUCdtfc6A$7Jlz87IuupiegAjM2vo4dSit2n+Yw8WXbvU9ZhAyr/FHJ8ZZf5if5bn/FMalnExCQQN7mykwWjraxfukOnTGxg==
```
I believe mosquitto also accepts plain text password files that would look like this:
```
dev1:3ggn0g
dev2:pickleree
dev3:cr3m34ngl4is3
```
Luckily the `mosquitto_passwd` utility also provides a `-U` option which updates a plain text password file to use password hashes. So, it may be easier to generate a plain text password, copy it to where mosquitto is looking for the password file, then run `mosquitto_passwd -U my_otherwise_plaintext_password_file` to make it more secure by using salted hashes.

**Comment by danielstock** [comment]
@BrandtHill   
i am so greatful because you have gone to great lengths to help me with this.
i would try this with the information you recommended.
thanks again!

**Comment by ralight** [comment]
I think this is resolved, so I'm closing the issue.
