### ISSUE TITLE
libwebsockets with ipv6 support

### ISSUE THREAD

**Issue by teddibaer** [eclipse/mosquitto#1615]
Hi,

It seems that mosquitto does not configure ipv6 support for libwebsockets - at least on my raspi with 1.6.8 the "normal" mqtt sockets are openend properly on both (ipv4 and ipv6) but the websockets listener refuses to listen on ipv6 addresses.

(As a sidenote: when using nginx as reverse proxy from ipv6 to ipv4 websocket, the connection is not properly handled, reverse proxy from ipv4 to ipv4 works).

Thx

**Comment by ralight** [comment]
I'm afraid that the version of libwebsockets that is used by Debian and derivatives like Raspbian has IPv6 support disabled. If your libwebsockets version is 2.0.3 (try `apt-cache policy libwebsockets-dev` on the command line) then this affects you. The in development version for Debian and Ubuntu is 3.2.1, and has been configured to enable IPv6.

If this is important to you, you would have to compile libwebsockets yourself to include support. I can give you hints if you wish.

**Comment by ralight** [comment]
I don't think there is anything more I can do here, so I'm closing this issue. If you disagree, please add more information and reopen.
