### ISSUE TITLE
net_mosq.c declaration issues

### ISSUE THREAD

**Issue by mostafaimam** [eclipse/mosquitto#1622]
in the function net__socket_connect_tls
declaration  of the variable long res; is under the function ERR_clear_error(); it suppose to be the opposite to be able to compile using old c compilers.
and the same issue in the same file in function net__init_ssl_ctx the variable EVP_PKEY *pkey the declaration suppose to be at the top of the function not in the middle.
thanks,

**Comment by karlp** [comment]
do you really still have a compiler that doesn't support c99 that you need to use?

**Comment by mostafaimam** [comment]
if you are working with embedded systems, the answer is yes a lot of embedded system compiler can't support C99

**Comment by karlp** [comment]
You should complain to your vendor.  Loudly.

**Comment by mostafaimam** [comment]
I did already and they will not be able to support that for different reasons and it is also not supported by the INTEGRITY operating system which most of the drones and medical devices use.
However, currently I did those changes by myself to be able to compile and use. but it will be much better to apply it it master branch so, anyone else can use it.

**Comment by michaeliu** [comment]
@karlp Compiler do not support C99 sound strange, but it's true in embedded system world. there are lots of vendor do not have plan to upgrade (It's sad...)

So, could you please consider to accept the suggestion and the PR.

**Comment by karlp** [comment]
They'll never lift a finger while their users keep being complicit and supporting them either :)  I'm not a project owner here, just another user, so I'm not accepting or rejecting this PR.  However, I'm not convinced it's even true for the case at hand, according to Green Hills themselves:

> C++11 and C++14 support
Green Hills Compilers support ISO/IEC 14882:2011 (C++11) and ISO/IEC 14882:2014 (C++14) which offers a number of new language features and standard libraries. These includes standardized threading support for mutexes, atomics, future/promise, and the use of the thread_local keyword. These features are supported on the INTEGRITY RTOS and can be easily customized to work on other OS.

**Comment by mostafaimam** [comment]
@karlp I am work with latest version of Green Hills compilers and believe me  when I said it is not working and we arranged with them sever meetings to ask them to support it. and they support threading but not all threading are supported and also I am not here to convince you as well. I already did those changes but I was putting this as a isuess for other users.
thanks,

**Comment by michaeliu** [comment]
> They'll never lift a finger while their users keep being complicit and supporting them either :) I'm not a project owner here, just another user, so I'm not accepting or rejecting this PR. However, I'm not convinced it's even true for the case at hand, according to Green Hills themselves:
> 
> > C++11 and C++14 support
> > Green Hills Compilers support ISO/IEC 14882:2011 (C++11) and ISO/IEC 14882:2014 (C++14) which offers a number of new language features and standard libraries. These includes standardized threading support for mutexes, atomics, future/promise, and the use of the thread_local keyword. These features are supported on the INTEGRITY RTOS and can be easily customized to work on other OS.

Thanks for reply and maybe mosquitto team will take care and consider this : )

**Comment by ralight** [comment]
Fixed as per the commit above. Supporting <C99 isn't something that is an express goal of the project, so there's no guarantees it won't break in the future.
