### ISSUE TITLE
Broker changes qos setting to zero when sending to subscriber

### ISSUE THREAD

**Issue by maxlein** [eclipse/mosquitto#1633]
Hi guys,  

Playing around with qos settings when sending a request msg I saw that the qos settings are always set to zero, although publisher and subscriber are set to the same qos settings. ( Tried with qos 1 and 2, same result )  

Then looking at the wireshark trace, I saw that the ACK packets say they are malformed.  
See this screenshot:  

![image](https://user-images.githubusercontent.com/11796203/77169401-b700d300-6ab9-11ea-85b2-d3cba3de80f9.png)

It looks like the broker is generating a malformed packet?  
But you guys see better what's malformed here...  

I also show you the published message:  

![image](https://user-images.githubusercontent.com/11796203/77169737-4908db80-6aba-11ea-800b-f302476b5461.png)

In general the messages are delivered but not with the qos setting I set it to.  
I am using the latest paho release and my mosquitto broker version is 1.6.9.

**Comment by karlp** [comment]
Looks mor elike a wireshark decoder issue. you can see your publish message has qos 1 set. Perhaps the decoder is stumbling over the odd sequence of mids?

**Comment by maxlein** [comment]
Ok, maybe also an issue with wireshark here.  
But why is then qos set back to 0?  
From what I see, the message is published with qos 1 and the broker resets it to 0 and is received as qos 0 by the subscriber, although the subscriber was set to qos 1.

**Comment by ralight** [comment]
Wireshark 3.x should be able to cope with all MQTT v5 messages.

I just tried this in one terminal window:

```
mosquitto_rr -t asdf -m 1 -q 1 -e response
```

And then in a separate window:

```
mosquitto_pub -q 1 -t response -m 2
```
The result I got was this, which looks fine to me:
![ws](https://user-images.githubusercontent.com/79578/77209186-82127180-6af5-11ea-9cf2-e450c4ee1c29.png)

**Comment by maxlein** [comment]
Thanks, wireshark was not up to date. Changed the title accordingly, as the broker seems to change qos setting when passing to the subscriber, also with your command:  

![image](https://user-images.githubusercontent.com/11796203/77310823-4b0fac00-6cff-11ea-9282-6da71d99b535.png)

**Comment by karlp** [comment]
Are you _sure_ the subscriber subscribed at qos1?  because rewriting down to the highest qos of the subscriber is exactly what's mean to happen.   This works easily and demonstrably with mosquitto_sub at the CLI, I'd recheck your code that it's subscribing the way you think it is.

**Comment by maxlein** [comment]
You are right, there was a bug in my wrapper! Thanks  
Btw: Calling `token->get_reason_code()` is always zero, but it should return the used qos setting if there is no error?  
Because I saw some examples were it's only an error, when `reason_code> mqtt::ReasonCode::GRANTED_QOS_2`  

Reason why I am asking is, it's always zero for me, also when it succeeded with qos > 0.

**Comment by karlp** [comment]
I'm afraid I don't know anything about whatever api "token->get_reason_code()" is, you may want to ask that question elsewhere? I can't find in any paho docs at least.  Are you possibly assuming some mqtt5 features in mqtt3 or anything?

**Comment by maxlein** [comment]
Sorry, thought I am in the paho repository...  

But for reference, here is an example:  

https://github.com/eclipse/paho.mqtt.cpp/blob/f3a2a52259b5463ab50eee6d1c033cba18d6e84b/src/samples/rpc_math_cli.cpp#L94
