### ISSUE TITLE
Socket error on bridge connection to the things network (TTN)

### ISSUE THREAD

**Issue by pokerazor** [eclipse/mosquitto#1635]
Hi. We are trying to set up an inward bridge connection to https://www.thethingsnetwork.org/docs/applications/mqtt/api.html

The config looks like this:
```
connection external-bridge
address eu.thethings.network:1883

notifications false
topic # in 0 /foo/buzz /foo/bar
cleansession true
local_username XXX
local_password XXX
#remote_clientid customclient
remote_username XXX
remote_password ttn-account-v2.XXX
bridge_protocol_version mqttv311
try_private false
```
But we are getting an error as follows:
```
1584968360: Connecting bridge (step 1) external-bridge (eu.thethings.network:1883)
1584968360: Connecting bridge (step 2) external-bridge (eu.thethings.network:1883)
1584968360: Socket error on client local.mosquitto.external-bridge, disconnecting.
```

It works via the commandline:
`mosquitto_sub  -u XXX -P ttn-account-v2.XXX -t 'XXX/#' -h eu.thethings.network -d -v -p 1883`

We tried with and without TLS, we are certain that the credentials are correct (otherwise we get an auth error), also it looks suspicious that the `local.mosquitto.external-bridge` is mentioned with the `local.` part, so it seems the external connection works, but the local not? The connection attempt is repeated every couple of seconds, always with the same result. We also tried connecting to our own server through the external port, that worked. Any idea what we're might be doing wrong or how we could debug better? Unfortunately, the log doesn't say what kind of socket error or why...
Thanks in advance.

**Comment by karlp** [comment]
try adding attempt_unsubscribe = false, that's another one I've had to add with some cloud brokers? but you've already covered the usual suspects (notifications, try_private and cleansession) so nothing obvious

**Comment by ralight** [comment]
```
topic # in 0 /foo/buzz /foo/bar
```

The documentation states `For incoming topics, the bridge will prepend the pattern with the remote prefix and subscribe to the resulting topic on the remote broker` That means that your bridge is trying to subscribe to `/foo/bar#`, which in an invalid topic. That's assuming your config there matches what you have in reality. I've just pushed a change which will report these invalid combinations at configuration time, rather than letting the bridge fail in an unexpected way like you are seeing.

**Comment by pokerazor** [comment]
Thanks for your responses! Yes, the problem was the notation of the topic for the local client.
We now got it running with `topic # both 2 external/ttn/ ""`, none of the additional 
```
    bridge_protocol_version mqttv311
    try_private false
    bridge_attempt_unsubscribe false
    cleansession true
    notifications false
```
was necessary for connecting to The Things Network.

Those additional checks and detailed error messages at config parsing time will be extremely helpful, thank you! :-)
