### ISSUE TITLE
Problems with AUTH

### ISSUE THREAD

**Issue by dieschoenstefrau** [eclipse/mosquitto#1638]
I'm trying to set up mosquitto with custom auth plugin and communicate with MQTT.js client. I did follow steps:
1. The client send `CONNECT` with `auth` request, 
2. my plugin received auth piggybacked on `CONNECT` with function `mosquitto_auth_start`, and the function sets up the auth data & method in response, and finally returns `MOSQ_ERR_SUCCESS`. 
3. Then mosquitto send connack with my auth data & method. 
But then mosquitto reports `Client dev1 disconnected due to protocol error.`, and sends `DISCONNECT` to client. 
Why does mosquitto report protocol error, what's wrong with my procedure, or maybe mosquitto has problems with auth?

**Comment by ralight** [comment]
There are only a few situations where mosquitto will end up sending a disconnect with protocol error.

When handling an AUTH packet:
1. If the AUTH reason code is neither `continue-authentication` nor `reauthenticate`
2. If the AUTH reason code is `reauthenticate` and the client hasn't previously authenticated
3. if `auth-method` is empty, or if the `auth-method` in the packet does not match the auth method given by the client in the CONNECT packet.

When handling a DISCONNECT packet:
4. If the client used a `session-expiry-interval` of 0 in the CONNECT packet, but set a non-zero `session-expiry-interval` in the DISCONNECT packet.

My bet is that you're seeing number 3. Something you could do to check is use wireshark to inspect the contents of the relevant packets to make sure everything is as you expect.

**Comment by dieschoenstefrau** [comment]
I found out that the client library implementation is wrong. Thank you for your comments.
