### ISSUE TITLE
Apparmor dependency is necessary?

### ISSUE THREAD

**Issue by hhromic** [eclipse/mosquitto#164]
Hello,

Mosquitto is a great MQTT broker, however I got frustrated when I realised that the available Debian packages from the official Mosquitto repository depend on `apparmor`. On a clean Raspbian Jessie installation, `apparmor` pulls a lot of unwanted dependencies even when you don't plan to use `apparmor` at all (18.9 MB of unused stuff!):

```
Will install 14 packages, and remove 0 packages.
18.9 MB of disk space will be used
===============================================================================
[INSTALL, DEPENDENCIES] apparmor:armhf
[INSTALL, DEPENDENCIES] dh-python:armhf
[INSTALL, DEPENDENCIES] libapparmor-perl:armhf
[INSTALL, DEPENDENCIES] libapparmor1:armhf
[INSTALL, DEPENDENCIES] libmpdec2:armhf
[INSTALL, DEPENDENCIES] libpython3-stdlib:armhf
[INSTALL, DEPENDENCIES] libpython3.4-minimal:armhf
[INSTALL, DEPENDENCIES] libpython3.4-stdlib:armhf
[INSTALL, DEPENDENCIES] libwebsockets3:armhf
[INSTALL, DEPENDENCIES] python3:armhf
[INSTALL, DEPENDENCIES] python3-minimal:armhf
[INSTALL, DEPENDENCIES] python3.4:armhf
[INSTALL, DEPENDENCIES] python3.4-minimal:armhf
[INSTALL] mosquitto:armhf
===============================================================================
```

I understand that there are users that use `apparmor` but the package doesn't even include a profile for Mosquitto. I believe the forced dependency on `apparmor` is not necessary and breaks the idea of a "lightweight MQTT broker".

Any thoughts? Perhaps `apparmor` should be a suggested dependency instead of required?

Cheers,
Hugo.

**Comment by hhromic** [comment]
Hi again,
I just saw that this had been addressed as I suggest before in the "debian" branch:

https://github.com/eclipse/mosquitto/blob/debian/debian/changelog

Perhaps you just need to rebuild/update the package in the repository?

Cheers,
Hugo.

**Comment by ralight** [comment]
Yes that's right, I honestly thought it was already done on the mosquitto repository. The real bug here is that the apparmor profile isn't installed. I'll work on getting the repository updated.

**Comment by hhromic** [comment]
Thanks!

I still believe apparmor should be left as a suggested dependency instead of a forced one. However the profile should be shipped as well in case an apparmor user needs it. This of course could be documented in README. I understand there is also a formal official way to distribute application profiles for apparmor that even goes beyond Debian [1].

Cheers!
Hugo.

[1] https://wiki.debian.org/AppArmor/Contribute/Upstream

**Comment by hhromic** [comment]
I did a quick reading and I think the easiest way to do it is to ship the apparmor profile (which I assume already exists by now) with the package. I used the example `tlsdate` package [1] shipped with Debian, and what they do is the following in the `rules` file:

```
override_dh_install:
        cp apparmor-profile debian/tlsdate/etc/apparmor.d/usr.bin.tlsdate
        dh_apparmor --profile-name=usr.bin.tlsdate -ptlsdate
```

Basically they copy the profile into the `/etc/apparmor.d/` directory and then make an installed apparmor to update this state. In the case of mosquitto it should be named `/etc/apparmor.d/usr.sbin.mosquitto`.

Please note that the `tlsdate` example package also has apparmor as suggested instead of a hard dependency, so the situation is very similar to what mosquitto is trying to achieve.

Hope this is useful!
Hugo.

[1] https://tracker.debian.org/pkg/tlsdate

**Comment by ralight** [comment]
The repository should have updated packages with just "suggests" now.

**Comment by hhromic** [comment]
Hi Roger,
I can confirm that now the `mosquitto` package installs cleanly without `apparmor` anymore =). Very lightweight on my Raspberry Pi's SD Card!

Thanks a lot,
Hugo.

**Comment by ralight** [comment]
Good to hear it works for you.

**Comment by hhromic** [comment]
Hi Roger,
In the recent release (1.4.10) the hard dependency on `apparmor` re-appeared in the Debian package =(.

Cheers,
Hugo.

**Comment by ralight** [comment]
This was fixed a while ago, thanks for the reminder.
