### ISSUE TITLE
Problem compiling (CMake)

### ISSUE THREAD

**Issue by gizmocuz** [eclipse/mosquitto#1641]
Trying to compile resulted in a few errors, hope they are minor

The CMakeList.txt should check if the uthash-dev package is installed for utlist.h include that is used throughout the project

Now it compiles, with 'make'

when running

sudo make install

there is a error:

CMake Error at man/cmake_install.cmake:41 (file):
  file INSTALL cannot find "/home/user/mosquitto/man/mosquitto_passwd.1": No  such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:62 (include)

The following files are present in this folder

mosquitto/man/mosquitto_passwd.1.meta
mosquitto/man/mosquitto_passwd.1.xml

**Comment by Ozaq** [comment]
I have run into the same issue, you can get it to build with cmake if you skip building documentation with `-DDOCUMENTATION=OFF`. 

More annoying is that UThash is not part of the bundled deps, this looks like a bug / omission to me.

**Comment by gizmocuz** [comment]
Thanks for finding !
Would be great when there where options to disable building:

- mosquittopp
- mosquitto_sub
- mosquitto_pub
- mosquitto_rr
- mosquitto
- mosquitto_passwd

This way we could only build the library, specially handing when using this as git submodule in another CMake project

**Comment by gizmocuz** [comment]
Thank you very much for this !
