### ISSUE TITLE
Yet another PUBREL issue

### ISSUE THREAD

**Issue by jsaak** [eclipse/mosquitto#1642]
Using version 1.5.7
Server is handling PUBREL packets wrong again.
We fixed this 4 years ago:
https://github.com/eclipse/mosquitto/commit/a187b3f5fa800387ab7507aae5a738b43464630e

And you reintroduced the error when you split `mqtt3_db_message_delete()` function into these two `db__message_release_incoming(), message__remove()`

On master you removed the warning, but still have the buggy implementation.
(returning MOSQ_ERR_NOT_FOUND in this case)
https://github.com/eclipse/mosquitto/blob/master/lib/handle_pubrel.c#L84

This very version crashed multiple times, and sometimes disconnects all clients.
If i can reproduce the error, i will submit another issue here.
I am having a hard time finding a version which is stable enough for production use :(
(the latest version i found was 1.4.10 which is usable)

Using mosquitto server as clients in bridge mode:

```
2020.03.27 16:01:31 : Warning: Received PUBREL from MV/14 for an unknown packet identifier 2872.
2020.03.27 16:01:31 : Warning: Received PUBREL from MV/14 for an unknown packet identifier 2872.
2020.03.27 16:01:31 : Warning: Received PUBREL from MV/14 for an unknown packet identifier 2872.
2020.03.27 16:01:31 : Warning: Received PUBREL from MV/14 for an unknown packet identifier 2872.
2020.03.27 16:01:31 : Warning: Received PUBREL from MV/14 for an unknown packet identifier 2872.
2020.03.27 16:01:31 : Warning: Received PUBREL from MV/14 for an unknown packet identifier 2872.
2020.03.27 16:01:31 : Warning: Received PUBREL from MV/14 for an unknown packet identifier 2872.
2020.03.27 16:01:31 : Warning: Received PUBREL from MV/14 for an unknown packet identifier 2872.
2020.03.27 16:01:31 : Warning: Received PUBREL from MV/14 for an unknown packet identifier 2872.
2020.03.27 16:01:31 : Warning: Received PUBREL from MV/14 for an unknown packet identifier 2872.
```

**Comment by jsaak** [comment]
Forget it, this is some other error in the network. I have retry interval set to 1, so this is probably only a 10 sec lag. (The other remarks about general stability are still true, but i can not reproduce them, so i am closing this)

**Comment by ralight** [comment]
I'm sorry to hear you've been having problems. You mention 1.4.10 and 1.5.7, which makes me think you are using Debian or Ubuntu provided packages. Unfortunately those versions have been stuck with old and buggy versions of libwebsockets, which can cause problems with the whole broker. If you are able to compile your own version that doesn't have websockets support it you don't need it, or to also compile libwebsockets (I have found 2.4.2 to be the best recent version) yourself then you may find things are better.

If you are still on 1.4.10, then please set retry_interval to be a high value, like 600 seconds. It is an anti-feature that causes more problems than it could solve. Setting it to 1 second would be almost guaranteed to cause you problems at some point. The feature was removed in 1.5.

**Comment by jsaak** [comment]
Thank you for your input!
I am indeed using debian.
I will try to compile one without websocket support.

(Retry interval is a stange feature, I agree, TCP layer is already handling this types of errors. It is very much needed in MQTT-SN though when transport layer is not TCP)
