### ISSUE TITLE
CrossCompile mosquitto for ARM

### ISSUE THREAD

**Issue by grjulian** [eclipse/mosquitto#1643]
Hi,

I try to cross-compile mosquitto for arm-linux-gnueabihf, but the Makefile failed.

Can anybody tell me how to do this successfully?

I need to compile a c++-Code from ubuntu for a Linux-angström dev-board.
I can compile the source-code on the host without problems. But if I try to cross-compile i've got the error: "..../arm-linux-gnueabihf/bin/ld: cannot find -lmosquitto"

Thanks

**Comment by ralight** [comment]
In case anybody else is looking, try:

`make CROSS_COMPILE=arm-linux-gnueabi-`
