### ISSUE TITLE
Mqtt Broker Unable to connect to the broker

### ISSUE THREAD

**Issue by yiyang1016** [eclipse/mosquitto#1648]
'mqttTest.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'mqttTest.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\Acer\Downloads\mqttTest\mqttTest\bin\Debug\mqttTest.exe'. Symbols loaded.
Starting MqttDotNet sample program.
Press any key to stop

'mqttTest.exe' (CLR v4.0.30319: mqttTest.exe): Loaded 'C:\Users\Acer\Downloads\mqttTest\mqttTest\bin\Debug\MqttLib.dll'. 
Client connecting

'mqttTest.exe' (CLR v4.0.30319: mqttTest.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'mqttTest.exe' (CLR v4.0.30319: mqttTest.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'mqttTest.exe' (CLR v4.0.30319: mqttTest.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'mqttTest.exe' (CLR v4.0.30319: mqttTest.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'MqttLib.MqttBrokerUnavailableException' in MqttLib.dll
An unhandled exception of type 'MqttLib.MqttBrokerUnavailableException' occurred in MqttLib.dll
Unable to connect to the broker

'mqttTest.exe' (CLR v4.0.30319: mqttTest.exe): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

Here is the exception handler output:
MqttLib.MqttBrokerUnavailableException: 'Unable to connect to the broker'
InnerException:
SocketException: No connection could be made because the target machine actively refused it 54.173.246.124:19682
[mqttTest.zip](https://github.com/eclipse/mosquitto/files/4431074/mqttTest.zip)

**Comment by ralight** [comment]
This isn't a Mosquitto problem as far I can tell, so I'm going to close it.

`SocketException: No connection could be made because the target machine actively refused it`

This is the important error though, you're trying to connect somewhere that isn't listening.
