### ISSUE TITLE
Cannot reconnect a client (async) - socket error

### ISSUE THREAD

**Issue by hetit** [eclipse/mosquitto#1649]
Cannot reconnect a former connected client.
Environment: Raspberry Pi (Scratch), Mosquitto version 1.6.8 (broker and library), installed from the repository.

Test program:

```c++
#include <stdio.h>
#include <unistd.h>
#include <mosquitto.h>

// Callbacks
// =========

// Logging callback
void loggingCB(struct mosquitto *mosq, void *obj, int level, const char *str)
{
  printf(str);
  printf("\n");
}

// Connect with flags callback
void connectCB(struct mosquitto *mosq, void *obj, int rc, int flags)
{
  printf("connectCB() called\n");
}

// Disconnect callback
void disconnectCB(struct mosquitto *mosq, void *obj, int rc)
{
  printf("disconnectCB() called\n");
}

// Main
// ====

int main()
{
  // Library initialization
  mosquitto_lib_init();

  // Create the client
  struct mosquitto *client = mosquitto_new("MOSQUITTO-Test-Client", 0, NULL);
  mosquitto_log_callback_set(client, *loggingCB);
  mosquitto_connect_with_flags_callback_set(client, *connectCB);
  mosquitto_disconnect_callback_set(client, *disconnectCB);
  mosquitto_loop_start(client);

  // Connect
  mosquitto_connect_async(client, "localhost", 1883, 5);

  // Wait for at least one ping
  sleep(7);

  // Disconnect
  mosquitto_disconnect(client);

  // Wait again a little while
  sleep(5);

  // Reconnect
  mosquitto_reconnect_async(client);
  // mosquitto_connect_async(client, "localhost", 1883, 5); //doesn't work either ...

  // Wait for at least one ping
  sleep(7);

  // Shut down the client and the library
  mosquitto_disconnect(client);
  mosquitto_loop_stop(client, false);
  mosquitto_destroy(client);
  mosquitto_lib_cleanup();
}
```
[mosquitto test.txt](https://github.com/eclipse/mosquitto/files/4432602/mosquitto.test.txt)

Test output (no CONNACK for the reconnect):

```
pi@Surveyor:~/Projekte/MQTTcs/build $ ./test/debug/mosquitto_reconnect_1
Client MOSQUITTO-Test-Client sending CONNECT
Client MOSQUITTO-Test-Client received CONNACK (0)
connectCB() called
Client MOSQUITTO-Test-Client sending PINGREQ
Client MOSQUITTO-Test-Client received PINGRESP
Client MOSQUITTO-Test-Client sending DISCONNECT
disconnectCB() called
Client MOSQUITTO-Test-Client sending CONNECT
Client MOSQUITTO-Test-Client sending DISCONNECT
pi@Surveyor:~/Projekte/MQTTcs/build $
```
[Mosquitto test output.txt](https://github.com/eclipse/mosquitto/files/4432613/Mosquitto.test.output.txt)

Broker log (socket error instead of CONNACK):

```
pi@Surveyor:~ $ mosquitto -v
1586036484: mosquitto version 1.6.8 starting
1586036484: Using default config.
1586036484: Opening ipv4 listen socket on port 1883.
1586036484: Opening ipv6 listen socket on port 1883.
1586036513: New connection from ::1 on port 1883.
1586036513: New client connected from ::1 as MOSQUITTO-Test-Client (p2, c0, k5).
1586036513: No will message specified.
1586036513: Sending CONNACK to MOSQUITTO-Test-Client (0, 0)
1586036518: Received PINGREQ from MOSQUITTO-Test-Client
1586036518: Sending PINGRESP to MOSQUITTO-Test-Client
1586036520: Received DISCONNECT from MOSQUITTO-Test-Client
1586036520: Client MOSQUITTO-Test-Client disconnected.
1586036525: New connection from ::1 on port 1883.
1586036532: Socket error on client <unknown>, disconnecting.
^C1586036537: mosquitto version 1.6.8 terminating
pi@Surveyor:~ $
```
[Socket error.txt](https://github.com/eclipse/mosquitto/files/4432614/Socket.error.txt)

**EDIT:** As the timestamp shows, the socket error happens at the second disconnect and not at the reconnect itself (which obviously wasn't processed correctly).

The same sequence using a Paho client IS working!

Broker log with Paho client:

```
pi@Surveyor:~ $ mosquitto -v
1586033008: mosquitto version 1.6.8 starting
1586033008: Using default config.
1586033008: Opening ipv4 listen socket on port 1883.
1586033008: Opening ipv6 listen socket on port 1883.
1586033019: New connection from 127.0.0.1 on port 1883.
1586033019: New client connected from 127.0.0.1 as PAHO-Test-Client (p2, c1, k5).
1586033019: No will message specified.
1586033019: Sending CONNACK to PAHO-Test-Client (0, 0)
1586033025: Received PINGREQ from PAHO-Test-Client
1586033025: Sending PINGRESP to PAHO-Test-Client
1586033026: Received DISCONNECT from PAHO-Test-Client
1586033026: Client PAHO-Test-Client disconnected.
1586033031: New connection from 127.0.0.1 on port 1883.
1586033031: New client connected from 127.0.0.1 as PAHO-Test-Client (p2, c1, k5).
1586033031: No will message specified.
1586033031: Sending CONNACK to PAHO-Test-Client (0, 0)
1586033037: Received PINGREQ from PAHO-Test-Client
1586033037: Sending PINGRESP to PAHO-Test-Client
1586033038: Received DISCONNECT from PAHO-Test-Client
1586033038: Client PAHO-Test-Client disconnected.
^C1586033132: mosquitto version 1.6.8 terminating
pi@Surveyor:~ $
```
[Paho.txt](https://github.com/eclipse/mosquitto/files/4432621/Paho.txt)

Am I missing something with the Mosquitto reconnect procedure?

**Comment by ralight** [comment]
What you're missing is a documentation omission. When you call `mosquitto_disconnect()` it is assumed you don't want this client any more, and the background loop is stopped. This is an important use case if you're using `mosquitto_loop_forever()`. This is referred to in the documentation for `mosquitto_loop_stop()`, but it could be clearer.

Something else that should be clearer is that if you are using `mosquitto_loop_start()` or `mosquitto_loop_forever()`, then they handle reconnections for you so there is no need to use `mosquitto_reconnect()`.

**Comment by hetit** [comment]
Thank you very much for the clue - I totally missed that point. I'm confident I'll find a workaround to be able to _manually_ disconnect and reconnect - at least from an application programmers point of view.

My application is a C++ framework to _configure_ instead of _program_  asynchronous MQTT clients and currently covers the Mosquitto an the Phao library. Its main purpose is to dramatically reduce the development time for _full featured_ asyncronous clients. But unfortunately manual disconnect and reconnect is in its specification :-) But don't bother for now - I'll come back to you if I fail finding a solution.

By the way: _automatic_ reconnect, as you mentioned, works perfectly well for _unintended_ disconnects - even in very very unstable environments.

By the way 2: Thanks to you (and Ian Craggs from the Paho project as well) for your efforts in making MQTT popular!

PS: You may close this issue if everything is said for now, otherwise I will close it in a couple of days.

**Comment by ralight** [comment]
Ah, I understand. That makes perfect sense.

From the point of view of the library, calling `mosquitto_loop_stop()` after your manual disconnect, and then calling `mosquitto_loop_start()` again should work. In fact, calling `mosquitto_loop_stop()` probably shouldn't be necessary, but it is right now. It's possible you will expose a bug there, so do keep in touch.
