### ISSUE TITLE
Implemented Reason Codes

### ISSUE THREAD

**Issue by Andreyooo** [eclipse/mosquitto#1654]
The man page only says that mosquitto sends a reeason code when a client exceeds the message_size_limit.

Is this feature available for other cases aswell?

**Comment by ralight** [comment]
The following reason codes are sent for the different packets:

CONNACK
* accepted
* not-authorized
* bad-authentication-method
* protocol-version
* retain-not-supported
* refused-identifier-rejected
* unspecified
* bad-username-or-password

PUBACK
* success
* no-matching-subscribers
* not-authorized
* implementation-specific (payload too big)

PUBREC
* success
* not-authorized
* implementation-specific (payload too big)

SUBACK
* 0, 1, 2
* unspecified

UNSUBACK
* success
* no-subscription-existed

DISCONNECT
* protocol-error
* unspecified
* retain-not-supported
* topic-alias-invalid
* administrative-action

AUTH
* success
* continue-authentication

They mostly depend on MQTT v5.0 of course. Does that answer your question?

**Comment by Andreyooo** [comment]
Yes, ty very much!
