### ISSUE TITLE
_mosquitto_destroy is canceling thread

### ISSUE THREAD

**Issue by jcavar** [eclipse/mosquitto#166]
Hi again,
So we use our own threads with mosquitto. We are calling `mosquitto_new` from Thread 1 and `mosquitto_loop_forever` from Thread 2. Now, `mosquitto_new` assigns `thread_self()` as `thread_id` which is in our case Thread 1 id. `_mosquitto_destroy` calls then `pthread_cancel` on it so Thread 1 is canceled. 

We were able to workaround this by moving everything to Thread 2, but I think mosquitto should destroy threads only in case `mosquitto_loop_start` is called which is signal to mosquitto to use its own threads.
Does this make sense?

**Comment by ralight** [comment]
Yes, I agree. This should be fixed now. Thanks for the report.

**Comment by jcavar** [comment]
Great, thank you for fixing it this fast!
