### ISSUE TITLE
Issue: After updating brooker  old clients on the field can't authenticate anymore with tlsv1.0

### ISSUE THREAD

**Issue by Ex4nder** [eclipse/mosquitto#1660]
Hi, 
We just had a problem on our server, after updating from mosquitto version accepting Tls V 1.0 1.1 1.2 to a version accepting 1.1. 1.2 1.3 we lost connectivity with the old systems on the field.

Will be possibile to also have support to 1.0 on the new version and specify multiple version to accept or not to accept in the config file? (newer clients use tls V1.2)

Best Regards

**Comment by ptjm** [comment]
The current version of mosquitto has removed support for TLSv1.0. If you don't mind recompile from a modified source, if you remove the text "| SSL_OP_NO_TLSv1" from the first SSL_CTX_set_options() call on line 336 of src/net.c, it should allow connects with all TLS versions supported by your openssl version.

Another alternative would be to have the older clients connect to an older version of mosquitto and forward their messages through a bridge to the newer instance. Another option would be to use stunnel or some similar program as a proxy between the older clients and the new broker.

I shouldn't think you'll see support for TLSv1.0 added back to an official mosquitto release.

**Comment by ralight** [comment]
@Ex4nder As ptjm suggests, we won't be adding TLSv1.0 back into an official release. The solution of modifying net.c to remove `| SSL_OP_NO_TLSv1` and recompiling is valid. Alternatively, we could provide commercial support for this. If that's something you'd like, please get in touch: mosquitto@cedalo.com

**Comment by Ex4nder** [comment]
Hi, I've forked and recompiled with TLSv1.0 back, now it's woking, I think I will eventually, modify also to ble able of more freely choose what TLS Version to opt in or out, not all in, or only one in. Thank you very much for your support. For me the Issue is closed.

**Comment by alexislg2** [comment]
Wow thanks guys
