### ISSUE TITLE
mosquitto_passwd can't update passwords

### ISSUE THREAD

**Issue by Legion2** [eclipse/mosquitto#1664]
When using `mosquitto_passwd` to update a password of an existing user the resulting password file is broken and the user can't authenticate to mosquitto with the new password.

Steps to reproduce:
1. create a password file and configure mosquitto to use it
2. add a user `mosquitto_passwd -b passwordfile test bla`
3. update the user password `mosquitto_passwd -b passwordfile test bla2`
4. try to connect to the broker with the user "test" and password "bla2"

I'm using the docker image `eclipse-mosquitto:1.6.9` for the cli tool and the broker.

**Comment by ralight** [comment]
Thank you for reporting this, it should now be fixed on the `fixes` branch.
