### ISSUE TITLE
Broker exited and can not restart after power on without internet connection

### ISSUE THREAD

**Issue by peterzhen001** [eclipse/mosquitto#1665]
Hi,

My system is Armbian 5.77 on phicomm N1, my broker works fine when internet is connected. My project need run on LAN with out internet. When system power on without internet connection, mosquitto broker exited and can not restart with 'sudo /etc/init.d/mosquitto try-restart'.
Thank you for your kind comments.

**Comment by ralight** [comment]
What version are you using, and what does your config look like?

**Comment by peterzhen001** [comment]
My mosquitto version is1.4.10. 
Issue solved according to #310. Thanks ralight.
