### ISSUE TITLE
how to do?one message only received once.

### ISSUE THREAD

**Issue by x-bb** [eclipse/mosquitto#1669]
how to do?one message only received once.
i start three consumer(clienta / clientb / clientc) subscribe same topic (topic/abc), i want if clienta received the message, then clientb and clientc  ignore this message.
now , in fact all consumer received this message. this is not i want.
how to do ? please ...

**Comment by x-bb** [comment]
i use default config.

**Comment by ralight** [comment]
You can do this with MQTT v5.0 by using shared subscriptions.

Each client should subscribe to `$share/sharename/topic/abc`

`sharename` defines a group of clients and can be any string that doesn't contain a `/`, `+`, or `#`. Only one client out of the group in `sharename` will receive each message published to that topic.

**Comment by x-bb** [comment]
thank ralight. 
but how to do ? use MQTT v5.0 .

**Comment by x-bb** [comment]
ok. thank ralight. it work.
