### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by jcavar** [eclipse/mosquitto#167]
Hi,

I tried to publish podspec to CocoaPods but got these errors:
    - ERROR | name: The name of the spec should match the name of the file.
    - ERROR | [iOS] name: The name of a spec should not contain whitespace.

Would you prefer to call it "Mosquitto" only or "EclipseMosquitto" without space?

**Comment by ralight** [comment]
If the description can use the full Eclipse Mosquitto name then I think the actual podspec can be Mosquitto.
