### ISSUE TITLE
WITH_BUNDLES_DEPS CMake option is not set in correct CMakeLists file

### ISSUE THREAD

**Issue by alexvannobel** [eclipse/mosquitto#1673]
Hi,

The `WITH_BUNDLED_DEPS` option is actually set in the `src` directory, but the option is also used in `lib`. When using CMake and this option, this results in a build failure unless the cmake has been run twice.

The solution is to set the option in the root CMakeLists.txt instead of the one in the `src` directory so both `src` and `lib` have the option defined when building.

I'd be glad to submit the trivial fix as a PR if you'd like to. Should I direct the PR to the `fixes` branch?

**Comment by ralight** [comment]
You could try... but I'm happy to say that it is already fixed in the `fixes` branch. Thanks for taking the time to report it.

**Comment by alexvannobel** [comment]
Ah you're right I didn't try in `fixes`! Thanks for the quick response, I'll close this then.
