### ISSUE TITLE
mosquitto_sub with parameter -F "%J" exits on Windows

### ISSUE THREAD

**Issue by amigian74** [eclipse/mosquitto#1674]
Hello,

if I try to run mosquitto_sub with the format parameter %J on a windows platform, the command exits on the first message immediately (without any result).

I'm running version 1.6.9.

Thx for help in advance

**Comment by ralight** [comment]
Thanks, I'll take a look when I'm booted into Windows.

**Comment by ralight** [comment]
I see the same thing, it's now fixed in the fixes branch and will become part of 1.6.10. Thanks very much!

**Comment by amigian74** [comment]
Thx for the fast response.
