### ISSUE TITLE
Error: Unrecognised command 128 when trying to subscribe to topic

### ISSUE THREAD

**Issue by olereidar** [eclipse/mosquitto#1675]
Hello! 
I am facing some issues with the `mosquitto_sub` command. Whenever I connect to a broker and tries to subscribe to a topic, the error 
```
Error: Unrecognised command 128 
Error: A network protocol error occurred when communicating with the broker.
``` 

is thrown.

I have tried googling the issue without luck. Does anyone know what is going on here? Or what could be the issue? 

Command: 
```
mosquitto_sub -h host -t '#' -d -P pass -i clientid -u user -V mqttv31
Client 10382435CC0CFDE6 sending CONNECT
Client 10382435CC0CFDE6 received CONNACK (0)
Client 10382435CC0CFDE6 sending SUBSCRIBE (Mid: 1, Topic: #, QoS: 0, Options: 0x00)
Error: Unrecognised command 128

Error: A network protocol error occurred when communicating with the broker.

```

Im using mac.

**Comment by ralight** [comment]
`Error: Unrecognised command 128` tells us that the client thinks it is receiving an MQTT packet that has a command of 128, or 0x80. This corresponds to the SUBSCRIBE packet. The broker should never be sending out a subscribe packet to a client, so something odd is going on.

What version of Mosquitto are you using? Could you try the command `mosquitto_sub -h test.mosquitto.org -t '#' -d -i clientid -V mqttv31`?

Just a note - you probably should be using mqttv311 (MQTT v3.1.1) instead. MQTT v3.1 has a few subtle differences to v3.1.1, and I don't believe there are as many brokers that support v3.1 as v3.1.1.

**Comment by olereidar** [comment]
Im using mosquitto_sub version 1.6.9 running on libmosquitto 1.6.9. 

I believe there might be a misconfiguration of the broker. This is an external broker outside my control. I were told it uses MQT v3.1, but running the command with MQT 3.1.1 returns the same error.

The command you posted works. 

I'm closing this issue since it most likely is a misconfiguration on the broker. Thank you for valuable insight! Have a nice day
