### ISSUE TITLE
QoS over bridge

### ISSUE THREAD

**Issue by steve999lee** [eclipse/mosquitto#1681]
**N.B. This has been resolved now**

What behaviour should I expect in the following scenario?

Client A publishes messages to Broker A 
Client B subscribes to the same topic on Broker B

Broker A is a bridge to Broker B.
QoS is 2  throughout

Normally messages are sent OK and I can see the publish and puback etc messages between Broker A and Broker B

1589317562: Sending PUBLISH to Bridge (d0, q2, r0, m43645, 'Bye/11', ... (8 bytes))
1589317562: Received PUBREC from Bridge (Mid: 43645)
1589317562: Sending PUBREL to Bridge (m43645)
1589317562: Received PUBCOMP from Bridge (Mid: 43645, RC:0)

If I stop Broker B, I expect the publish messages to continue to be sent but no puback etc to be received and the message to be resent - just like when a client publishes to a broker.

However - this is what happens...

1589317563: Socket error on client Bridge, disconnecting.
1589317568: Bridge Bridge doing local SUBSCRIBE on topic Bye/+
1589317568: Connecting bridge (step 1) bridge-01 (127.0.0.1:20103)
1589317568: Connecting bridge (step 2) bridge-01 (127.0.0.1:20103)
1589317569: Bridge Bridge sending CONNECT
1589317569: Error creating bridge: Protocol error.

Seems like the paho client buffers messages when the connection to the broker is lost and reesnds them when connection is reestablished but the broker-broker connection doesnt do this.

The MQTT spec covers message delivery retries but I guess technically this only applies to clients (and not bridges)  but obviously it should apply to bridges as well.

> "When a Client reconnects with CleanSession set to 0, both the Client and Server MUST re-send any unacknowledged PUBLISH Packets (where QoS > 0) and PUBREL Packets using their original Packet Identifiers. This is the only circumstance where a Client or Server is REQUIRED to redeliver messages."

**Comment by steve999lee** [comment]
On further testing, its now working as expected - I may have had cleansession true
Thanks

**Comment by ralight** [comment]
Great, I'm glad you've got it working.
