### ISSUE TITLE
What is the point in the docker entrypoint?

### ISSUE THREAD

**Issue by retnikt** [eclipse/mosquitto#1686]
In `docker/1.6/docker-entrypoint.sh` there is
```
#!/bin/ash
set -e
exec "$@"
```

which does literally nothing except execute the arguments. Why is this here? What is its purpose? Why not just omit the ENTRYPOINT directive entirely?

**Comment by ralight** [comment]
It's a convenience to allow adding functionality at a later point - which actually I'm looking at doing soon. It doesn't do any harm at the moment anyway.
