### ISSUE TITLE
Log file flushing is 'slow' on originary log files.

### ISSUE THREAD

**Issue by beretta42** [eclipse/mosquitto#1689]
On an unbusy server, I notice ordinary file logging (*not* stderr, or stdout) doesn't happen until a new log entry is placed. looking at /src/logging.c  I see fflush(), but only if 1 second has elapsed. Unfortunately this check only happens upon the *next* log entry, so the previous log entry get trapped in the kernel.

**Comment by ralight** [comment]
This should be fixed now on the `fixes` branch.
