### ISSUE TITLE
SSL being initialized even if not used

### ISSUE THREAD

**Issue by abiliojr** [eclipse/mosquitto#1693]
On current versions of libmosquitto built with TLS support, openssl gets initialized even when not used. This means ~125 KB of RAM allocated without need, which can be a significant portion of memory used by simple MQTT based processes, and easily add up in some systems (e.g., microservice based ones).

https://github.com/eclipse/mosquitto/pull/1692 contains a patch that changes this behavior.

**Comment by ralight** [comment]
Closed as per your PR :)
