### ISSUE TITLE
Client on local broker get $SYS messages from remote broker

### ISSUE THREAD

**Issue by teslafields** [eclipse/mosquitto#1697]
I wanted to know if is it possible to a client connected to a local broker, in which is bridged to a remote broker, to get the $SYS messages from this remote broker. I am not interested in notifications from local broker, only the remote. Therefore, my conf is such that:

```
listener 1883
log_dest syslog
log_dest stdout
log_dest topic
log_type all
connection_messages true
log_timestamp true
allow_anonymous true
connection bridge-to-losant
cleansession true
try_private false
bridge_attempt_unsubscribe false
notifications false
address test.mosquitto.org:1883
remote_clientid 5ec2da6d8dead300075f9e86
topic test/# both 1
topic broker/clients/total in 0 $SYS/ $SYS/
```

I tried creating a client that subscribes to the local broker in the topic `$SYS/broker/clients/total` this but i got a denied publish:

```
Connecting bridge bridge-to-losant (test.mosquitto.org:1883)
Bridge 5ec2da6d8dead300075f9e86 sending CONNECT
Received CONNACK on connection local.5ec2da6d8dead300075f9e86.
Bridge local.5ec2da6d8dead300075f9e86 sending SUBSCRIBE (Mid: 1, Topic: test/#, QoS: 1, Options: 0x00)
Bridge local.5ec2da6d8dead300075f9e86 sending SUBSCRIBE (Mid: 2, Topic: $SYS/broker/clients/total, QoS: 0, Options: 0x00)
Received SUBACK from local.5ec2da6d8dead300075f9e86
Received SUBACK from local.5ec2da6d8dead300075f9e86
Denied PUBLISH from local.5ec2da6d8dead300075f9e86 (d0, q0, r1, m0, '$SYS/broker/clients/total', ... (4 bytes))
```

Now, if a change the line from my conf: `topic broker/clients/total in 0 $SYS/ $SYS/` to `topic broker/clients/total in 0 "" $SYS/`, then it works when a client subscribes to `broker/clients/total`
```
Received PUBLISH from local.5ec2da6d8dead300075f9e86 (d0, q0, r0, m0, 'broker/clients/total', ... (4 bytes))
Sending PUBLISH to mosq-cpOOPnCio8sIqKj4oT (d0, q0, r0, m0, 'broker/clients/total', ... (4 bytes))
```

But that is not the behavior I want. Therefore, I would like to know if is there some way to make the client receive the message in the original topic ($SYS/broker/clients/total)?

Thanks

**Comment by ralight** [comment]
I'm afraid not. The only part of the $SYS topic hierarchy that can be published to by a client is `$SYS/broker/connection/+/state`.

**Comment by ralight** [comment]
I'm closing this because I don't think it can go any further, I'm not planning on changing this behaviour. If you want to say more, please reopen and add more comments.
