### ISSUE TITLE
Compile mosquitto for QNX 7

### ISSUE THREAD

**Issue by chenSevenHalf** [eclipse/mosquitto#1702]
I have a problem to compile the mosquitto for QNX OS.
I downloaded the file named mosquitto-qnx.zip, then I tried to add it to my QNX momentic IDE,but it failed.
later ,I transfer the file to my linux(ubuntun) platform,and run make, A missing QCC error has occurred.On the ubuntun ,I don't have QCC and corss compiler of QNX.
I don't know how to compile for my QNX ，which is running in the VMware.

**Comment by ralight** [comment]
I think on average I've had about one question on QNX every four years. I don't know much about it, or where this mosquitto-qnx.zip file you have came from. The last time I can be certain that Mosquitto compiled on QNX was about 8 years ago. I'm afraid I think you need to be the one to figure out how to compile on QNX, and then we can look at fixing any problems that occur.

**Comment by chenSevenHalf** [comment]
I just finished up compilation for QNX OS .The MQTT version is 1.6.8.Just like this:
1、首先找到并修改config.mk中的文件，这里以1.6.8版本为例。
WITH_DOCS:=yes
改为WITH_DOCS:=no,非git source进行编译，无需支持。
WITH_BUNDLED_DEPS:=yes
改为WITH_BUNDLED_DEPS:=no
159行	BROKER_LDADD:=$(BROKER_LDADD) -ldl -lm
改为BROKER_LDADD:=$(BROKER_LDADD) -lc -lm –lsocket
220行和223行去掉-lpthread参数
2.mosquitto.conf中添加对root用户支持
199行添加 user root
3.net.c文件
46行和48行头文件删掉。
570-572行宏定义注释掉。
630-642行#ifdef SO_BINDTODEVICE注释掉。
3. 导入QNX IDE进行编译
通过File->Import Projects from File System or Archive，然后选择刚才修改的源文件，可以是压缩包或者非压缩包形式。

**Comment by iscopa** [comment]
I am trying to build the mosquitto libraries using CMakelists.txt and QNX QCC v5.4.0 and get the error "linker cannot find -ldl". I do not know how to remove the flag to that library or to link that library in CMakeLists.txt if needed. Could you please help on this?

Thank you
