### ISSUE TITLE
[QUESTION] mbedtls support planned?

### ISSUE THREAD

**Issue by mabuze** [eclipse/mosquitto#1703]

**Comment by ralight** [comment]
Not at the moment, but if you're working for a company where that is important, then please let us know.

**Comment by MrPointer** [comment]
@ralight I'm working on an Embedded Linux platform, where we use mosquitto both as IPC (We're counting on the recent UDS support) and as external communication.
As we're tight on resources, especially disk size, we had to replace **openSSL** with **mbedTLS** to get some breathing room, but now we're stuck on this end... would love to see support for it anytime soon!

**Comment by madhat1** [comment]
Found this OpenSSL wrapper for mbedTLS, part of libwebsockets, could be useful to wrap mbedTLS with an OpenSSL API:
https://repo.wlpbx.com/smart/libwebsockets/-/tree/master/lib/tls/mbedtls/wrapper
