### ISSUE TITLE
repo.mosquitto.org outdated

### ISSUE THREAD

**Issue by nmaas87** [eclipse/mosquitto#1708]
Dear all,

I saw that the repo.mosquitto.org is still at version 1.6.8 and is missing the 1.6.9 and 1.6.10 releases. Could you please fix that?

Thank you very much for your work! :)

**Comment by numericOverflow** [comment]
Agreed.  Would like to see updated debian package pushed out ASAP.  A Feb release date on 1.6.9 *should* be available 3+ months later...

**Comment by nmaas87** [comment]
Thanks for adding the versions until 1.6.12 - I found out the 1.5.10 and 2.0.0 versions are missing, could you fix that? thank you very much :)!

**Comment by ralight** [comment]
The repo has been up to date for a long time now, so I'm closing this issue.
