### ISSUE TITLE
TZ enviroment in docker

### ISSUE THREAD

**Issue by salvq** [eclipse/mosquitto#1709]
Hello, I am using docker however timezone is not correct for my use case therefore I am using
`-v /etc/localtime:/etc/localtime:ro \` within my docker run command to set the correct time from host machine.

However there is more flexible solution, use `tzdata` package to installation step to your docker and to use `# docker run -e TZ=Europe/Prague`

`RUN apt-get install -y tzdata`

Thanks

**Comment by chainhead** [comment]
The `generic` folder has `Dockerfile` based off of `alpine`. So, continue this [line](https://github.com/eclipse/mosquitto/blob/8123e767dec0dc5ed00446e1127ab1064c6412d6/docker/generic/Dockerfile#L16) to add `tzdata` package.

**Comment by salvq** [comment]
thanks @chainhead I have used local one instead of generic and add below code [from this line](https://github.com/eclipse/mosquitto/blob/8123e767dec0dc5ed00446e1127ab1064c6412d6/docker/local/Dockerfile#L9)

```
RUN apk --no-cache add \
        tzdata \
        nano \
        logrotate
```
