### ISSUE TITLE
TLS issue: Unable to load server key file on Mac

### ISSUE THREAD

**Issue by gmrwvu** [eclipse/mosquitto#1710]
I am using Mac OS Mojave version 10.14.6, openssl version 1.0.2n, and Mosquitto 1.6.9.  Everything in Mosquitto works fine without TLS.  I generated the keys for TLS with the following commands:
Make keys
openssl genrsa -out ca.key 2048
openssl req -x509 -new -nodes -key ca.key -sha256 -days 3650 -out ca.crt
(For cn used MOSQUITTO CERTIFICATE AUTHORITY)
openssl x509 -in ca.crt -noout -text
openssl genrsa -out server.key 2048
openssl req -new -key server.key -out server.csr 
openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt -days 3650 -sha256 
(For cn used IP address of my Mac
openssl x509 -in server.crt -noout -text

I stopped mosquitto and added the following lines to mosquitto.conf:
#MQTT over TLS
listener 8883
cafile /usr/local/Cellar/mosquitto/1.6.9/etc/mosquitto/certificates/ca.crt
certfile /usr/local/Cellar/mosquitto/1.6.9/etc/mosquitto/certificates/server.crt
keyfile /usr/local/Cellar/mosquitto/1.6.9/etc/mosquitto/certificates/server.key

The error I get is the following:
/usr/local/Cellar/mosquitto/1.6.9/sbin/mosquitto -c /usr/local/Cellar/mosquitto/1.6.9/etc/mosquitto/mosquitto.conf
1590960896: mosquitto version 1.6.9 starting
1590960896: Config loaded from /usr/local/Cellar/mosquitto/1.6.9/etc/mosquitto/mosquitto.conf.
1590960896: Opening ipv6 listen socket on port 8883.
1590960896: Opening ipv4 listen socket on port 8883.
1590960896: Error: Unable to load server key file "/usr/local/Cellar/mosquitto/1.6.9/etc/mosquitto/certificates/server.key". Check keyfile.

I have verified that server.key is in the directory indicated, it is a valid pem file and have given all users complete access to the file. The same error occurs. 

Hardlib, a few years ago, recommended making the mosquitto user the server.key file owner.  There is only one user on my Mac so that was not possible. Likewise, a full chain pem file results in the same error. I also saw the closed issue here but that did not resolve the problem.

I am willing to work with you guys to resolve this issue.  Can you recommend a place to start?

**Comment by Sumatt92** [comment]
I copy pasted your procedure and everything works on ubuntu. Dont have mac so....
If working from source, you could use debugger to step through and see where things are going wrong.

**Comment by gmrwvu** [comment]
Thanks, I'll try on ubuntu.

**Comment by gmrwvu** [comment]
I installed on ubuntu as per script above.  the server/broker now starts and I can do a publish/subscribe  
sudo mosquitto_sub -t abc  -h localhost -p 8883 -d --key /etc/mosquitto/certificates/server.key --cert /etc/mosquitto/certificates/server.crt --cafile /etc/mosquitto/certificates/ca.crt --insecure
Client mosqsub|3454-ip-172-31- sending CONNECT
Client mosqsub|3454-ip-172-31- received CONNACK
Client mosqsub|3454-ip-172-31- sending SUBSCRIBE (Mid: 1, Topic: abc, QoS: 0)
Client mosqsub|3454-ip-172-31- received SUBACK
Subscribed (mid: 1): 0
Client mosqsub|3454-ip-172-31- received PUBLISH (d0, q0, r0, m0, 'abc', ... (3 bytes))
123
Client mosqsub|3454-ip-172-31- sending PINGREQ
Client mosqsub|3454-ip-172-31- received PINGRESP

sudo mosquitto_pub -t abc -m 123 -h localhost -p 8883 -d --key /etc/mosquitto/certificates/server.key --cert /etc/mosquitto/certificates/server.crt --cafile /etc/mosquitto/certificates/ca.crt --insecure
Client mosqpub|3444-ip-172-31- sending CONNECT
Client mosqpub|3444-ip-172-31- received CONNACK
Client mosqpub|3444-ip-172-31- sending PUBLISH (d0, q0, r0, m1, 'abc', ... (3 bytes))
Client mosqpub|3444-ip-172-31- sending DISCONNECT

The only difference I can detect with ubuntu and mac is version of openssl 1.1.1 vs 1.0.2n

Anyway, thanks for the suggestion, I will go forward with ubuntu
