### ISSUE TITLE
Docker build fails for 1.6.

### ISSUE THREAD

**Issue by chainhead** [eclipse/mosquitto#1712]
When building with `Dockerfile` for 1.6, I get this error.

```bash
+ wget https://mosquitto.org/files/source/mosquitto-1.6.9.tar.gz -O /tmp/mosq.tar.gz
Connecting to mosquitto.org (85.119.83.194:443)
mosq.tar.gz           34% |**********                     |   207k  0:00:01 ETA
mosq.tar.gz          100% |*******************************|   596k  0:00:00 ETA

+ echo 'd7b62aa0ca680b0d869d6883373903362f98326a6465fc6cd01a0b9e0e8f0333  /tmp/mosq.tar.gz'
+ sha256sum -c -
sha256sum: WARNING: 1 of 1 computed checksums did NOT match
/tmp/mosq.tar.gz: FAILED
+ echo 'Fetching GPG key A0D6EEA1DCAE49A635A3B2F0779B22DFB3E717B7 from ha.pool.sks-keyservers.net'
+ gpg --keyserver ha.pool.sks-keyservers.net --keyserver-options 'timeout=10' --recv-keys A0D6EEA1DCAE49A635A3B2F0779B22DFB3E717B7
Fetching GPG key A0D6EEA1DCAE49A635A3B2F0779B22DFB3E717B7 from ha.pool.sks-keyservers.net
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 779B22DFB3E717B7: public key "Roger A. Light <roger@atchoo.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
+ found=yes
+ break
+ test -z yes
+ gpg --batch --verify /tmp/mosq.tar.gz.asc /tmp/mosq.tar.gz
gpg: can't open '/tmp/mosq.tar.gz.asc': No such file or directory
gpg: verify signatures failed: No such file or directory
```
The `shasum` verification fails, the download of `https://mosquitto.org/files/source/mosquitto-${VERSION}.tar.gz.asc` does not happen and `gpg --batch --verify` fails.

**Comment by Sumatt92** [comment]
I prune containers and images that might contaminate cache, then
docker build -t test:0 .
builds container for me. 
Your checksum doesn't match mine though...

Another thing you could try is to run 
make localdocker
from project directory

**Comment by ralight** [comment]
This should work fine, otherwise the dockerhub builders would have failed. I don't know where your sha256sum came from there, it's definitely wrong. Either way, the generic dockerfile is now updated to work again, and the 1.6 dockerfile is updated for 1.6.10. And you have the option of `make localdocker`, as Matt noted.

**Comment by ralight** [comment]
If you agree, please close this issue or I'll do it in a week or so.
