### ISSUE TITLE
mosquitto -h says: "mosquitto is an MQTT v3.1.1 broker."

### ISSUE THREAD

**Issue by whnr** [eclipse/mosquitto#1713]
Hi! just a tiny thing that is slightly confusing. When you run `mosquitto -h` it says: `mosquitto is an MQTT v3.1.1 broker.` 

Suggestion: Get rid of the version dependence. Or make it complete. I just get started with mqtt and the website says that mosquitto supports v5.

https://github.com/eclipse/mosquitto/blob/8123e767dec0dc5ed00446e1127ab1064c6412d6/src/conf.c#L359

**Comment by liangyuanpeng** [comment]
Yes,this confused me for a long time.

**Comment by ralight** [comment]
Thank you, I hadn't spotted that. It is now fixed!
