### ISSUE TITLE
Will topic and TLS

### ISSUE THREAD

**Issue by KrYpToDeN** [eclipse/mosquitto#1715]
Hello.

Could you help me with sending 'will' topic, using TLS (cetificates).
Logs on my server is OK, but will topic publish not every time.

Testing with MQTT Box, with own software.

Will topic published 1/10 times.

I heard, that this is a problem, using TLS.

**Comment by ralight** [comment]
From your links, it seems like this is a client library problem. The description at https://github.com/marvinroger/async-mqtt-client/issues/193 is pretty clear about that. I'm not well versed with the different embedded client libraries, but your best bet may be following the one linked in that issue for when it gets SSL support.

**Comment by ralight** [comment]
I'm closing this now because it's not related to Mosquitto, best of luck finding something that works for you.
