### ISSUE TITLE
mosquitto_publish_v5 returns MOSQ_ERR_SUCCESS even if not connected to a broker

### ISSUE THREAD

**Issue by BOTorioN** [eclipse/mosquitto#1725]
Hello,

I just upgraded from mosquitto-1.5 to mosquitto-1.6.10 and I see that the mosquitto_publish function now returns a MOSQ_ERR_SUCCESS even if the client is not connected to the broker. It used to return a MOSQ_NO_CONN in this case with the 1.5 version. 
The documentation still mentions that it should return a MOSQ_NO_CONN in this case. 
Is this the wanted behavior? 

Thank you

**Comment by ralight** [comment]
Thanks for the report, and sorry for not getting to this sooner. I've just pushed a fix to the `fixes` branch which should sort this.
