### ISSUE TITLE
max_queued_messages does not apply to bridge

### ISSUE THREAD

**Issue by Andreyooo** [eclipse/mosquitto#1729]
As stated above, if my bridge connection gets closed, messages are queued infinetly. Is this intentional behaviour?

**Comment by Andreyooo** [comment]
Also something I noticed. When clean session set to true for the bridge on connection-loss the broker stores messages up to a count of 1000 then drops them and repeats this process.

Doubling the output of messages did not change the amount of stored messages or the cycle time.

**Comment by ralight** [comment]
I suspect you are using Mosquitto 1.4.15, is that correct? The queuing behaviour did not apply to bridges a long while back but has since been fixed.

The sawtooth pattern comes about because Mosquitto is incorrectly queuing messages for the disconnected bridge, then when it tries to reconnect those messages are cleared out. I've just pushed a change to the `fixes` branch which should stop it doing this.

**Comment by Andreyooo** [comment]
Hey ralight, thx for your time. 

I'm using mosquitto version 1.6.7, iI have set max_queued_messages 100 and clean session false for the bridge. My messages get queued infinitely. I don't have to establish a bridge connection for that. It happens even when no connection was established.

I noticed in the log the message:  **Outgoing messages are being dropped for client local.DDC4000.69.ddc4ke-bridge.**
It get's logged once shortly before the first reconnect cycle but messages don't get dropped.

For me setting clean session to true fixes my issues, but seems still strange to me.

![Anmerkung 2020-07-16 161735](https://user-images.githubusercontent.com/38321084/87686090-66a63300-c784-11ea-841b-e2235f41dcc3.png)

**Comment by ralight** [comment]
This is what I see, using 1.6.7 with `max_queued_messages 100` and `cleansession false`.

![1729](https://user-images.githubusercontent.com/79578/87695267-30b67e00-c787-11ea-8b17-be2395a5f484.png)

**Comment by Andreyooo** [comment]
I see, I will play around with the settings and report back if I find out why I have different behaviour

**Comment by karlp** [comment]
You might also have some stale clients with subscriptions in your persistence db?  it can very much skew things if you don't start from a clean point
