### ISSUE TITLE
error codes for mosquitto_connect_callback_set ommited in documentation

### ISSUE THREAD

**Issue by coffeeaddict19** [eclipse/mosquitto#1730]
Regarding mosquitto_connect_callback_set:

During testing, mosquitto_connect_callback_set threw error 4. mosquitto.h mentions no such code. It is instead, marked 'for future use'.

Some searching revealed error codes 4 and 5 here:
https://github.com/eclipse/mosquitto/blob/386f3cc188cde0b896175c0c844cfdf8dd7ea220/lib/mqtt_protocol.h

enum mqtt311_connack_codes {
	CONNACK_ACCEPTED = 0,
	CONNACK_REFUSED_PROTOCOL_VERSION = 1,
	CONNACK_REFUSED_IDENTIFIER_REJECTED = 2,
	CONNACK_REFUSED_SERVER_UNAVAILABLE = 3,
	CONNACK_REFUSED_BAD_USERNAME_PASSWORD = 4,
	CONNACK_REFUSED_NOT_AUTHORIZED = 5,
};

The issue is that the documentation and the comments in the header are misleading. Request that it be updated to include the omitted error codes.

**Comment by ralight** [comment]
Those comments haven't been changed since before MQTT had usernames and passwords... You're right they're way out of date. It's not sufficiently clear that they are MQTT return codes, not Mosquitto return codes. That should be fixed now, let me know if you think it's still not clear.

**Comment by coffeeaddict19** [comment]
Excellent.

This is the first time I've done this. Don't know the custom. Do I close the issue now?

**Comment by ralight** [comment]
Yes, that's lovely. I prefer to leave it to the reporter to close the bug when they're happy.
