### ISSUE TITLE
BUG: QoS2 message not forwarded to active subscriber

### ISSUE THREAD

**Issue by philbowles** [eclipse/mosquitto#1734]
The Wireshark log says it all: 
![image](https://user-images.githubusercontent.com/27769598/85880494-6b5a7580-b7dc-11ea-98da-8f1b73eddf18.png)

**Comment by ralight** [comment]
Do you have persistence enabled on the broker, if not then it cannot save messages over a restart.

Does the subscriber connect using the same client id as when it originally connected? If you are using MQTT v3, does it have the clean session bit set off when it connected both times? If you are using MQTT v5, does the subscriber set clean start to off on the second connection, and does it set session-expiry interval to be non-zero on its first connection?

If any of these points aren't true, then you wouldn't expect to get the message on the second connection.

**Comment by philbowles** [comment]
@ralight Thank you: you have saved my sanity! I foolishly assumed defult settings would save state data between restarts. I edited conf and set persistent true and the exact expected behviour appears.
```
13:22:25.540 -> SENT 28 (thisSession=5)
13:22:25.780 -> RCVD 28
13:22:26.536 -> SENT 29 (thisSession=6)
13:22:26.643 -> Disconnected from MQTT reason=0
13:22:26.643 -> USER: Disconnect reason=0
13:22:30.546 -> Heartbeat: Heap=47176 seq=29 number of reconnects=4
13:22:30.546 -> No. Incomplete send/rcv pairs=1
13:22:30.546 -> 29,
13:22:31.647 -> Connecting to MQTT...
13:22:31.681 -> 
13:22:31.681 -> SESSION IS DIRTY
13:22:31.681 -> Connected to MQTT: Session=1 Max safe payload 21232
13:22:31.681 -> unifiedSubscribe Psequence @ QoS2
13:22:31.919 -> ***** QoS2 recovery in action! *****
13:22:31.919 -> We have not yet sent any messages, but 29 just came in!
13:22:31.919 -> RCVD 29
13:22:32.687 -> SENT 30 (thisSession=1)
13:22:32.959 -> RCVD 30
13:22:33.663 -> SENT 31 (thisSession=2)
13:22:33.731 -> RCVD 31
13:22:34.677 -> SENT 32 (thisSession=3)
13:22:34.711 -> RCVD 32
```

And I am doubly happy since it proves also my recovery code works correctly, so I shall now release my FULL QoS0/1/2 client with up to 20kb payloads on ESP8266 and ~120kb on ESP32 :)

**Comment by ralight** [comment]
I assume I'm ok to close this then!
