### ISSUE TITLE
Proxmox Ubuntu Appliance /tmp/dlt cannot be opened

### ISSUE THREAD

**Issue by borpin** [eclipse/mosquitto#1735]
Just installed mosquitto on a Proxmox Ubuntu 20.04 appliance.

On startup the following error is seen
```
* mosquitto.service - Mosquitto MQTT v3.1/v3.1.1 Broker
     Loaded: loaded (/lib/systemd/system/mosquitto.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2020-06-28 10:40:31 UTC; 10min ago
       Docs: man:mosquitto.conf(5)
             man:mosquitto(8)
   Main PID: 9184 (mosquitto)
      Tasks: 3 (limit: 4915)
     Memory: 1.9M
     CGroup: /system.slice/mosquitto.service
             `-9184 /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf

Jun 28 10:40:31 mosquitto systemd[1]: Starting Mosquitto MQTT v3.1/v3.1.1 Broker...
Jun 28 10:40:31 mosquitto mosquitto[9184]: 1593340831: Loading config file /etc/mosquitto/conf.d/bridge.conf
Jun 28 10:40:31 mosquitto mosquitto[9184]: [72979.790296]~DLT~ 9184~INFO     ~FIFO /tmp/dlt cannot be opened. Retrying later...
Jun 28 10:40:31 mosquitto systemd[1]: Started Mosquitto MQTT v3.1/v3.1.1 Broker.
```

In the Minimal container, DLT is not running.

I see that https://github.com/eclipse/mosquitto/pull/993 implemented DLT.

Is it possible to disable it?

**Comment by ralight** [comment]
Alas not at the moment, but it really really should be. I've just added support to the `develop` branch, which you could use. Alternatively, compiling without DLT support would do the job.

**Comment by colinl** [comment]
On a PC running Ubuntu 20.04 with Mosquitto installed from the standard Ubuntu repo (version 1.6.9-1) I see this message, and on shutting down mosquitto I see
`~DLT~ 2361~WARNING  ~Lost log messages in user buffer when exiting: 11`
and there is about a 10 second delay when stopping, which is annoying.  Is the delay caused by this problem?  If so is there any workaround to stop it delaying the shutdown?

**Comment by ralight** [comment]
It is the DLT logging that is causing the delay, which is annoying. I've just pushed another change to the `fixes` branch which checks when DLT is available before trying to initialise DLT, which then avoids this delay.

**Comment by colinl** [comment]
OK, thanks.  That doesn't really help in the short term when installing from the Ubuntu repo, but that is not anything that can be fixed here I know.  I had hoped there might be some workaround but there may not be.

**Comment by ralight** [comment]
You could emulate the dlt fifo being available.

The below would work for a once off very very simple case, there are plenty of ways you could automate it depending on what you would prefer.

```
mkfifo /tmp/dlt
cat /tmp/dlt
```

**Comment by colinl** [comment]
OK, Many thanks.

**Comment by sreeharshar84** [comment]
You can suppress the message "]~DLT~141085~INFO     ~FIFO /tmp/dlt cannot be opened. Retrying later..." by adding to your code before calling  dlt_register_app() : 

 dlt_log_init(DLT_LOG_DROPPED);

This will avoid printing out the warning that it is unable to  connect dlt-daemon when only console mode is chosen. There is no
 way in dlt currently to avoid this issue. 

More info:  https://pfefferz.github.io/dlt-daemon-doxygen-built/dlt__common_8c_source.html#l02029

**Comment by ralight** [comment]
@sreeharshar84 Thanks for the hint. The problem here isn't really about the message, but about the big delay on shutdown. This has been fixed in 1.6.11 anyway.

**Comment by joshuakoh1** [comment]
How do I get the 1.6.11 fix? I've installed mosquitto with `sudo apt install mosquitto mosquitto-clients`

**Comment by colinl** [comment]
@joshakoh1 you can install from https://launchpad.net/~mosquitto-dev/+archive/ubuntu/mosquitto-ppa

**Comment by abhinav0927** [comment]
@colinl Can you please explain the steps to install the mosquitto from https://launchpad.net/~mosquitto-dev/+archive/ubuntu/mosquitto-ppa

What version of mosquitto it has? Is it the latest version

**Comment by ralight** [comment]
@abhinav0927 It has the latest version, yes.

The steps are:

```
sudo add-apt-repository ppa:mosquitto-dev/mosquitto-ppa
sudo apt-get update
sudo apt install mosquitto
```
