### ISSUE TITLE
Simultaneous log events are not written to log file straight away

### ISSUE THREAD

**Issue by tt92** [eclipse/mosquitto#1741]
Hi,

I have enabled `log_dest file ...` in my mosquitto.conf.

Eventually, everything is logged as expected.
But when there are multiple messages with the same timestamp, only the first message is written to the log file straight away.
All other messages are kind of handed in later when the next log event occurs!

Here's a short example:

First, I connected a client to my broker:

> ...
> 1594215148: New connection from x.x.x.x on port 1883.

Then I waited about 15 s. The log file was unchanged.

Then I disconnected the client again and suddenly, I see three more messages with an old timestamp in my log:

> ...
> 1594215148: New connection from x.x.x.x  on port 1883.
> 1594215148: New client connected from x.x.x.x  as aaa (p2, c1, k60, u'roger').
> 1594215148: No will message specified.
> 1594215148: Sending CONNACK to aaa (0, 0)
> 1594215204: Received DISCONNECT from aaa

I have the same behaviour on both a win10 and a linux system.

I'm sorry, if I have overlooked an existing issue but I couldn't find anything describing that issue so far. 

Cheers,

Tobias

**Comment by ralight** [comment]
This should now be fixed in the `fixes` branch, thanks for the report.
