### ISSUE TITLE
Private Key in pkcs11 device

### ISSUE THREAD

**Issue by clogwog** [eclipse/mosquitto#1742]
in the current code (master) it looks like i can set an openssl engine in the configuration file using :

```
tls_keyform engine
tls_engine pkcs11

bridge_keyfile  pkcs11:model=ATECC608A;manufacturer=Microchip%20Technology%20Inc;serial=23864EC2CF819601;token=00ABC;object=device;type=private
```

can this be used for picking up my private key from a secure token using pkcs11 ?

**Comment by ralight** [comment]
I'm afraid I don't know, the openssl engine code was contributed and I don't have a great deal of experience in that area of openssl.

**Comment by clogwog** [comment]
I found out that it doesn't . 
I now have a patch  that allows me to pickup the private key from a pkcs11 engine, but it is a bit too crude to suggest as a pull request, it is also very difficult to write tests for without having actual hardware that contains this private key.

it's based off 1.6.10 and i'll attach it here in case anyone needs to do similar.

I have a feeling that this will become more needed as having private keys on a harddisk/sdcard will be frowned upon more and more.

`diff --git a/lib/net_mosq.c b/lib/net_mosq.c
index 3565002..0226323 100644
--- a/lib/net_mosq.c
+++ b/lib/net_mosq.c
@@ -777,10 +777,42 @@ static int net__init_ssl_ctx(struct mosquitto *mosq)
 					}
 #endif
 				}else{
-					ret = SSL_CTX_use_PrivateKey_file(mosq->ssl_ctx, mosq->tls_keyfile, SSL_FILETYPE_PEM);
+					log__printf(mosq, MOSQ_LOG_DEBUG, "trying to load keyfile : %s", mosq->tls_keyfile);
+
+					if( strncmp("pkcs11:", mosq->tls_keyfile, strlen("pkcs11:")) == 0)
+					{
+						//ENGINE_load_builtin_engines();
+						engine = ENGINE_by_id("pkcs11");
+						if(!engine){
+							log__printf(mosq, MOSQ_LOG_ERR, "Error loading %s engine\n", mosq->tls_engine);
+							COMPAT_CLOSE(mosq->sock);
+							mosq->sock = INVALID_SOCKET;
+							return MOSQ_ERR_TLS;
+						}
+						if(!ENGINE_init(engine)){
+							log__printf(mosq, MOSQ_LOG_ERR, "Failed engine initialisation\n");
+							ENGINE_free(engine);
+							COMPAT_CLOSE(mosq->sock);
+							mosq->sock = INVALID_SOCKET;
+							return MOSQ_ERR_TLS;
+						}
+						ENGINE_set_default(engine, ENGINE_METHOD_ALL);
+						
+						EVP_PKEY* key = ENGINE_load_private_key(engine, mosq->tls_keyfile, NULL, NULL);
+						ret = SSL_CTX_use_PrivateKey(mosq->ssl_ctx , key);	
+						// TODO TOM !! Does this need to be freed ? not sure as there is an ENGINE_FINISH call below?
+						//ENGINE_free(engine); /* release the structural reference from ENGINE_by_id() */
+						log__printf(mosq, MOSQ_LOG_DEBUG, "loaded pkcs11 key ");
+
+					}
+					else
+					{
+						ret = SSL_CTX_use_PrivateKey_file(mosq->ssl_ctx, mosq->tls_keyfile, SSL_FILETYPE_PEM);
+					}
 					if(ret != 1){
 #ifdef WITH_BROKER
-						log__printf(mosq, MOSQ_LOG_ERR, "Error: Unable to load client key file, check bridge_keyfile \"%s\".", mosq->tls_keyfile);
+						log__printf(mosq, MOSQ_LOG_ERR, "Error: Unable to load client key file, check bridge_keyfile \"%s\"  error: %d.", mosq->tls_keyfile, ret);
+						ERR_print_errors_fp(stderr);
 #else
 						log__printf(mosq, MOSQ_LOG_ERR, "Error: Unable to load client key file \"%s\".", mosq->tls_keyfile);
 #endif
@@ -811,7 +843,6 @@ static int net__init_ssl_ctx(struct mosquitto *mosq)
 #endif
 		}
 	}
-
 	return MOSQ_ERR_SUCCESS;
 }
 #endif`

**Comment by woelfman** [comment]
@clogwog Using 1.6.5 or newer (earlier versions would process `bridge_keyfile` strictly as a file) you can do:
```
tls_keyform engine
tls_engine pkcs11
bridge_certfile /tmp/client.crt
bridge_keyfile pkcs11:model=ATECC508A;manufacturer=Microchip%20Technology%20Inc;serial=23BC449711E58E2A;token=SSH2P
```
`/tmp/client.crt` is generated using
```
p11tool --export-chain 'pkcs11:token=MCHP;object=device;type=cert' > /tmp/client.crt
```
This requires `cryptoauthlib` >= 3.2 for the export-chain support.

I'm running this setup to connect to AWS on one of my embedded devices. I'm struggling to get it to work on a different device. It seems to be choking at libp11 for some reason:
```
mosquitto -c my.conf
...
Format not recognized!
The key ID is not a valid PKCS#11 URI
The PKCS#11 URI format is defined by RFC7512
The legacy ENGINE_pkcs11 ID format is also still accepted for now
```

**Comment by clogwog** [comment]
@woelfman we have got it working agains AWS IoT as described above. Just a question on how did you create your AWS IoT 'Thing' did you import the manifest file of the 608A TNGTLS ? or did you generate  a csr using the pkcs11 private key ?

we couldn't  get it working using the manifest import, but could get it working using the csr..
I know this is not what should happen as the manifest is an 'allow list' but we have an extra check before we allow the csr through by loading the manifest manually, parsing it and compairing the public keys before we sign the CSR inside IoT

**Comment by woelfman** [comment]
For a new product we've did CSRs. We also have existing products that use our own backend service that will provision the device using the device certificate.
