### ISSUE TITLE
Major bug: shared subscription lost messages when other client disconnects

### ISSUE THREAD

**Issue by avierr** [eclipse/mosquitto#1747]
when client1 and client2 are subscribed to a shared subscription, let's say X
it works perfectly, but if client2 disconnects completely.
client1 will only get half the messages and rest are lost
(similarly if there were 4 clients and 3 disconnect, the remaining client will only get 1/4 the number of messages)

video explaining the same:
https://www.youtube.com/watch?v=iYjNWDvO_F8

I also tried writing a simple nodeJS application just to be sure that the problem is not with the mosquitto_sub command. 
Looks like the issue is with the server. 

No amount of waiting for these subscriptions to clear works, only option is two restart the mosquitto server.
No combination of QOS in publish and subscribe worked

version: 1.6.10

**Comment by avierr** [comment]
never mind I forgot I had enabled -c option (clean: false)

**Comment by ralight** [comment]
Ah good, I was just coming to say the same thing :)
