### ISSUE TITLE
V.1.6.10 Windows  Mosquitto cannot start with quotes as pattern in bridge Topic  

### ISSUE THREAD

**Issue by cieslarchristian** [eclipse/mosquitto#1749]
The MQTT Broker will not start on Windows with the following topic defined for the bridge: 
topic "" out 0 Testtopic/test1 devices/KUKArobotconnection/messages/events/

On Linux the broker can start and runs with the same config. 

If i change the quotes "" to something different it runs, but then my topics are no longer correct.

**Comment by ralight** [comment]
This should be fixed now in the `fixes` branch and will be part of a new release soon.

**Comment by ralight** [comment]
Thanks for the report!

**Comment by cieslarchristian** [comment]
Thank you for the fast fix!
