### ISSUE TITLE
Mosquitto crashes websocket connection with status 502 when it receives long HTTP-headers. 

### ISSUE THREAD

**Issue by tradingpanel** [eclipse/mosquitto#1750]
In my case it was above 1600 bytes. 
Its because browser WS class send all site cookies with WS handshake,

Workaround: use nginx proxy for MQTT websocket and strip cookies header

**Comment by ralight** [comment]
What version of Mosquitto and libwebsockets are you using?

**Comment by tradingpanel** [comment]
mosquitto                            1.6.8-0mosquitto1~buster1    amd64        MQTT version 3.1/3.1.1/5.0 compatible message broker
libwebsockets8:amd64                 2.0.3-3                      amd64        lightweight C websockets library

**Comment by ralight** [comment]
In that case please just add `websockets_headers_size 10000` to your configuration file, replacing the 10000 with the maximum header size you wish to allow.

**Comment by tradingpanel** [comment]
thank you!
