### ISSUE TITLE
A suggestion for persistence

### ISSUE THREAD

**Issue by guilee1** [eclipse/mosquitto#1754]
When I set persistence on, because the  all operation in one thread(mosquitto_main_loop),and persistent operations after each socket processing,. As disk IO is very inefficient, resulting in the impact on the main loop and network processing at the same time. Could i make a single thread to persist? just like Copy-On-write,collect all datas in the mosquitto_main_loop,and persist them in other thread.

**Comment by ralight** [comment]
The upcoming version 2.1 has a plugin interface for persistence, so it would be possible to create a plugin that did disk writing in a separate thread.
