### ISSUE TITLE
How to shutting down Mosquitto Bridge in right way?

### ISSUE THREAD

**Issue by itadakimatsu97** [eclipse/mosquitto#1755]
Dear All,

I have a trouble in backend side when i close brigde by using:
"systemctl stop mosquitto".
So i got a notify from backend "Ungracefully disconnect".

Could you please guide how to disconnect a bridge connection in good way:
- unsubcribe all topics bridging
- perform a graceful disconnect.

Another question:
- Is forced reconnect available? How can i do that?
- is Reloading mosquitto.conf available?

Thank you!

EDIT:
- mosquitto ver 1.6.2

**Comment by hardillb** [comment]
A `kill -HUP <pid>` should re-read the conf file.

**Comment by itadakimatsu97** [comment]
> A `kill -HUP <pid>` should re-read the conf file.

Thanks for reply.
Could you share any document about mosquitto signal handler?

**Comment by hardillb** [comment]
https://github.com/eclipse/mosquitto/blob/master/src/signals.c ?

**Comment by itadakimatsu97** [comment]
> https://github.com/eclipse/mosquitto/blob/master/src/signals.c ?

Do you have any suggestion about above problem?
Currently, for performing disconnect gracefully i cal send_disconnect(), then do_disconnect().
Is it a good way?
