### ISSUE TITLE
mosquitto_passwd command in snapped mosquitto not found

### ISSUE THREAD

**Issue by fkromer** [eclipse/mosquitto#1761]
With the snap version of mosquitto the mosquitto_passwd command did not work in my setup:

```
$ sudo snap install mosquitto
mosquitto 1.6.10 from Mosquitto Team (mosquitto✓) installed
$ sudo mosquitto_passwd -c mosquitto/config/passwd plasmion
sudo: mosquitto_passwd: Command not found
```

If I use the apt package instead it works as usual:

```
$ sudo apt-get install mosquitto
...
$ sudo mosquitto_passwd -c mosquitto/config/passwd plasmion
plasmion16
Password: 
...
```

**Comment by ralight** [comment]
For various good reasons the snap commands are in the format e.g. mosquitto.passwd instead of mosquitto_passwd. All of the other mosquitto_* commands have a snap level alias to give access from mosquitto.pub to mosquitto_pub. I'll see about getting one requested.

**Comment by fkromer** [comment]
Uh, sorry for the false positive. Calling tools via aliases has not become second nature to me yet. Feel free to totally ignore this issue.

**Comment by ralight** [comment]
This is being dealt with here: https://forum.snapcraft.io/t/auto-alias-request-number-two-for-mosquitto/19479

**Comment by ralight** [comment]
That is now fixed, as per the forum post. Thanks for the report!
