### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by koochak-mehdi** [eclipse/mosquitto#1763]
Hi,
I'm trying to compile the "temperature_conversion" example on ubuntu 16.04, and I'm using moquitto 1.6.10 as broker.
mqtt_temperature_conversion binary will be built successfully but, exactly after running the binary file I get the following error.

`Connected with code 0.`
`Segmentation fault`

and this is the log from broker side:

`1596105486: New connection from ::1 on port 1883.`
`1596105486: New client connected from ::1 as tempconv (p1, c1, k60).`
`1596105486: Socket error on client tempconv, disconnecting.`

Can anyone help me?
thanks.

**Comment by ralight** [comment]
My guess is that you have a multiple incompatible mosquitto libraries installed. You could always try and run it in a debugger.

**Comment by koochak-mehdi** [comment]
how should I check if I installed it properly?
I've tried it with apt-get, snap and even tar.gz file ...

**Comment by koochak-mehdi** [comment]
actually I've just changed the -ggdb flag to -g in Makefile and it works now!
Do you have any idea why?

**Comment by koochak-mehdi** [comment]
I've removed it and tried to install just with tar.gz file and it works. thanks.

**Comment by ralight** [comment]
Good, I'm glad you've got it sorted.
