### ISSUE TITLE
websocket listener on localhost

### ISSUE THREAD

**Issue by gerdstolpmann** [eclipse/mosquitto#1764]
This does not work (mosquitto-1.6.10 on Mac):
```
listener 9025 localhost
protocol websockets
```
It just does not create the socket. Omitting `localhost` fixes it (but leaves the socket unprotected).

I'm using this in a testing scenario, and don't want to set passwords for protection.

**Comment by ralight** [comment]
Due to vagaries of the websockets library, it's not currently possible to bind to a hostname when using websockets (this is mentioned in the mosquitto.conf documentation). Using `listener 9025 127.0.0.1` should work just fine.
