### ISSUE TITLE
TCP FIN sent by mosquitto

### ISSUE THREAD

**Issue by veracl** [eclipse/mosquitto#1765]
In my application, I sometimes receive "TCP SOCKET CLOSED" error messages while using MQTT. I am using mosquitto v1.6.10 and the Contiki-NG client implementation.

In the mosquitto log, this looks like this:

```
1596187956: Received PUBLISH from auto-BBEC2275-7B00-00F1-0686-134E2A1AF6AF (d0, q0, r0, m0, '<TOPIC>', ... (23 bytes))
1596187956: Sending PUBLISH to d:quickstart:device:00124b133df0 (d0, q0, r0, m0, '<TOPIC>', ... (23 bytes))
1596187956: Received UNSUBSCRIBE from d:quickstart:device:00124b133df0
1596187956: Socket error on client d:quickstart:device:00124b133df0, disconnecting.
1596187964: New connection from fd00::212:4b00:413:3df0 on port 1883.
1596187964: New client connected from fd00::212:4b00:413:3df0 as d:quickstart:device:00124b133df0 (p5, c1, k90).
```

When I checked a packet capture, I saw that the TCP connection close is initiated by the MQTT broker (first TCP FIN is sent from port 1883). See the pcap: [mosquitto-tcp-fin-1.zip](https://github.com/eclipse/mosquitto/files/5006638/mosquitto-tcp-fin-1.zip)

I have been able to pretty much reliably reproduce this in the following situation: My application subscribes to a topic, receives a bunch of PUBLISHes and responds to each with a PUBLISH on another topic using a topic alias. Finally, it unsubscribes. That's when the "socket error" occurs. (But I've also seen it occur in other situations without any unsubscribe.) Afterwards, it must reconnect.
I have not tried yet to reproduce this independently of my application.

I am not sure this is actually mosquitto's fault, but what could be the reason that it sends the TCP FIN?

**Comment by ralight** [comment]
The problem is caused by the client implementation sending an incorrect UNSUBSCRIBE message. It is missing the "property length field" as described by section 3.10.2.1.1.

I have just pushed a change that makes it clearer that this is a protocol error in the logs.

**Comment by veracl** [comment]
Thank you! I will raise this issue at the contiki-ng repository.

> (But I've also seen it occur in other situations without any unsubscribe.)

I have also been able to reproduce this. Mosquitto sent a TCP FIN after receiving this PUBLISH:

```
MQ Telemetry Transport Protocol, Publish Message
    Header Flags: 0x30, Message Type: Publish Message, QoS Level: At most once delivery (Fire and Forget)
    Msg Len: 79
    Topic Length: 66
    Topic: <TOPIC>
    Properties
        Total Length: 6
        ID: Topic Alias (0x23)
        Topic Alias: 3
        ID: Topic Alias (0x23)
        Topic Alias: 3
    [Topic: <TOPIC>]
    Message: 0,OK
```

I guess that the problem was the double Topic Alias property which is a Protocol Error according to the specification. Anyhow, it was also an issue with my client that I've now been able to fix.

> When a Server detects a Malformed Packet or Protocol Error, and a Reason Code is given in the specification, it MUST close the Network Connection [MQTT-4.13.1-1]. In the case of an error in a CONNECT packet it MAY send a CONNACK packet containing the Reason Code, before closing the Network Connection. In the case of an error in any other packet it SHOULD send a DISCONNECT packet containing the Reason Code before closing the Network Connection.

Have you considered also sending a DISCONNECT with a Malformed Packet/Protocol Error reason code in these cases? That would have certainly helped me figure out what the issue was.

**Comment by ralight** [comment]
The `develop` branch now sends out DISCONNECT for malformed PUBLISH, SUBSCRIBE, and UNSUBSCRIBE packets: https://github.com/eclipse/mosquitto/commit/84e4ba2c1ea20a4fda5d8a1db64fee0a70d79829
