### ISSUE TITLE
`Error: Address already in use` after fresh installation on Debian 9 "Stretch" (most current version, updated with apt-get upgrade)

### ISSUE THREAD

**Issue by martijintro** [eclipse/mosquitto#1768]
```
 mosquitto -v
1596713559: mosquitto version 1.4.10 (build date Wed, 13 Feb 2019 00:45:38 +0000) starting
1596713559: Using default config.
1596713559: Opening ipv4 listen socket on port 1883.
1596713559: Error: Address already in use
```

Does somebody know what that is?

Does `mosquitto -v` try to start a new process on the same port 1883 that is already in use due to the mosquitto background service...? (`service mosquitto status` shows me that is runs which is OK, it must run as a service in our case!)

Thank you for your feedbacks.

With best regards,
Jan

**Comment by martijintro** [comment]
"You will need to install the mosquitto-clients package if you haven't done so already."

Does not really help -> read from https://stackoverflow.com/questions/30207649/address-already-in-use-error-in-mosquitto#:~:text=2%20Answers&text=After%20that%20the%20Error%3Aaddress,able%20to%20run%20properly%20again.&text=You%20will%20need%20to%20install,haven't%20done%20so%20already.

**Comment by martijintro** [comment]
Oh, th `-v` does start mosquitto in a "verbose" mode...?

I was thinking it just verifies and print out the service config / mode.

So problem solved and ready to close.

To the project maintainers: If i was wrong, so just re-open it to find aa adequate solution.

**Comment by ralight** [comment]
Just as a comment - the version in Stretch is way, way out of date (nearly 4 years old). I'd suggest you use the repository at repo.mosquitto.org instead.

**Comment by martijintro** [comment]
OK thank you for your informations!

Stretch is (tool) old in general - i know. But currently, we need it only for development, testing and prototyping purposes.

But:, So i saw, the mosquitto version on buster does also not support MQTT protocol version 5.x...

From which version does mosquitto support the MQTT 5.x version? Maybe you know that?

(The v3.x vs. v5.x thing is (currently) just a theorecial thing for us - we use it with tasmota and their MQTT client functionality is v3.x. only)

**Comment by martijintro** [comment]
Now i added that to sources.list

```
deb https://repo.mosquitto.org/debian stretch InRelease
```

+ the updates the required GPG key. After that, `apt-gte update` was working with the new repo.mosquitto.org-entry.

But: "apt-get upgrade" does not seem to work. I was expecting that this command would update the old mosquitto package from debian.org Strech APT repo...?

Maybe `apt-get upgrade` is only working if the packages come from the same server?

So: Do i need to uninstall the version from Debian Stretch APT-repo first, then install it again with "apt-get install ... "

And: Are there NO confilcts between the versions from

`deb http://deb.debian.org/debian/ stretch contrib main non-free`

Vs.

`deb https://repo.mosquitto.org/debian stretch InRelease`


Maybe (???):

- Do i need to comment out the `deb http://deb.debian.org/debian/ stretch contrib main non-free` entry first?
OR
- Do i need to specify an explicite version number when i use `apt-get install ... `
OR
- Do i need to to NOTHING?


Thank you for your feedbacks! ;-)


Kind regards, Jan

**Comment by martijintro** [comment]
-> when i use  `apt-get install mosquitto`, i get the text that i alredy use the most current version. (but i added the mosquitto apt server url in sources.list!!)

Something seems to be "unclean"...?

**Comment by martijintro** [comment]
Full proof:

```
root@debianoalpr:~# apt-get update
OK:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease
OK:3 http://deb.debian.org/debian stretch-updates InRelease
OK:4 http://deb.debian.org/debian stretch Release
OK:5 https://download.docker.com/linux/debian stretch InRelease
OK:6 https://repo.mosquitto.org/debian stretch InRelease
Paketlisten werden gelesen... Fertig
root@debianoalpr:~#
root@debianoalpr:~#
root@debianoalpr:~# apt-get install -s mosquitto
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
mosquitto ist schon die neueste Version (1.4.10-3+deb9u4).
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  dns-root-data dnsmasq-base iputils-arping libndp0 libteamdctl0 mobile-broadband-provider-info
Verwenden Sie »apt autoremove«, um sie zu entfernen.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 2 nicht aktualisiert. 
```

**Comment by ralight** [comment]
Try this: https://repo.mosquitto.org/debian/readme.txt

**Comment by martijintro** [comment]
Thank you very much, now it works.

But there is a small error in your readme.txt:

Wrong:
`.../sources/list.d/... `


Correct:
` .../sources.list.d/...`

I never saw something different than a `sources.list.d` directory on debian-based systems! ;-)

**Comment by ralight** [comment]
Ah yes, thank you.
