### ISSUE TITLE
Use mosquitto with linux user account

### ISSUE THREAD

**Issue by martijintro** [eclipse/mosquitto#1770]
Sure, there are also some advantages if mosquitto uses its own account, independent from linux users.

But: Is it also possible to use a linux user for mosquitto - similar as some (most) ftp servers for linux do?

Thank you for your feedback.

With best regards,
Jan

**Comment by ralight** [comment]
Yes, it's certainly possible. You could do this by creating an authentication plugin for Mosquitto that used Linux PAM for authentication. I am never going to do this however, and I would strongly suggest that you never do it either.

**Comment by martijintro** [comment]
OK thx.

But no i have an idea:

Does mosquitto use the same password hashing method as linux on /etc/passwd ?

If yes, then i should be (theoretically) possible to /etc/shadow ?

With that code in /etc/mosquitto/mosquitto.conf file:

```
# Use authentication from system users
allow_anonymous false
password_file /etc/shadow
```


...and when i look to the /etc/shadow file, there are a lot of users, but a hash is only defined for "root" and the user created by myself called "user1".

So, in my opinion, that should (theoretically) not be a security hole. (?)

**Comment by martijintro** [comment]
Maybe i need to run mosquitto server as root, so it's able to access the  `/etc/shadow` linux user accounts / passwords file? ;)

**Comment by ralight** [comment]
I trust that you're joking with the final comment.

Mosquitto does not work with /etc/shadow. It never will. Users on an MQTT broker are entirely different to Linux users, you will not change my mind on that.

**Comment by martijintro** [comment]
"I trust that you're joking with the final comment."

I'm not 100% sure for myself... but i also think so - it's more a joke than a serious question! ;-)

Thank you very much for clarification. Will close ticket now.
