### ISSUE TITLE
mosquitto clients to Debian 9 "Stretch" mosquitto server always disconnects

### ISSUE THREAD

**Issue by jayjupdhig** [eclipse/mosquitto#1771]
Same problem with Tasmota 6.5.0 and https://github.com/thomasnordquist/MQTT-Explorer ...

Always reconnections...

The network bridge from VirtualBox 6.0.14 VM should be stable - never had problems with that. (1x with "macvlan" virtual network card set up as a bridge to the virtualbox ethernet bridge. But that's 100% another thing... just "incompatible by design"..)

**Comment by martijintro** [comment]
we use most current mosqutto version vom debian 9 stretch apt repo, debian itself was also updated before installing mosquitto with "apt-get upgrade" ...

**Comment by ralight** [comment]
Can I politely ask you to take a step back and think about whether you would be able to solve your problem based on what you've written here. All I see is "my clients disconnect", which doesn't help me at all. Please take some time to investigate the problem, including upgrading to a more recent version of Mosquitto. Perhaps try connecting to a public broker with your client to make sure there is no problem with the client. If all that fails, then please write here again with a detailed description of what you have and all the details that might be needed to reproduce what you are seeing.

**Comment by martijintro** [comment]
Yes, now i try it with the most current version for debian -> https://github.com/eclipse/mosquitto/issues/1768

The reconnection thing must be a server issue, because Tasmota & MQTT Explorer show me the same messages. The server seems to refuse the connection.

(On the service-based offer from mymqtthub.com, i didn't had that problem with Tasmota & MQTT Explorer. But there are other problems, especially the limitations on free accounts)

But now, i already updated to the most current version for Debian Stretch from your own APT repo server. Will look what happens...

**Comment by martijintro** [comment]
No, same problem! :-(

![1](https://user-images.githubusercontent.com/42765391/89541261-70a8d800-d7fe-11ea-92e8-c43dfef4d4df.jpg)

![2](https://user-images.githubusercontent.com/42765391/89541272-743c5f00-d7fe-11ea-9512-4a2424431fda.jpg)


You you need more informations, so please tell me which ones and how to get them. Thank you very much.

**Comment by martijintro** [comment]
Now i will install th most current VirtualBox 6.0.x version... maybe it helps?

**Comment by ralight** [comment]
It sounds like a networking problem to be honest.

**Comment by martijintro** [comment]
same problem with new VirtualBox 6.0.x version 24... but from Windows to 192.168.178.128 i'm connected with a cable, the sonoff is connected via WLAN.. i would understand it if the problem would only occur on the sonoff WLAN-connected device.

But the server has also another network connection to a 192.168.80.0/24 subnet. My Windows PC is also connected with that. Now i will try to use MQTT Explorer via the 80-subnet...

**Comment by martijintro** [comment]
The Windows PC doesn't seem to have a network problem on both subnets:

192.168.80.105 Debian 9 VirtualBox VM IP ping:

![80](https://user-images.githubusercontent.com/42765391/89544961-09415700-d803-11ea-9540-fa92083d22d7.jpg)


192.168.80.128 Debian 9 VirtualBox VM IP ping:

![178](https://user-images.githubusercontent.com/42765391/89545041-21b17180-d803-11ea-80b8-35d19f28f5ab.jpg)

..and it can't be a problem with cable, because VirtulBox runs on my Windows Workstation. So no cables involved.

But maybe a "default gateway" problem. Because of that, now i will disable 1 of both VM virtual NICs.

**Comment by martijintro** [comment]
To avoid a "default gateway" problem on with > 1 NIC on Linux systems, i commented all other adapters out in /etc/network/interfaces. Then i removed the virtual NIC (bridge) adapter from VirtualBox VM configuration.

Result: Same problem, so no "default gateway" problem with only 1 adapter - completely impossible.

...i'm sorry, but that's just a waste of time - at least in my case!

Now i've found another solution that works like a charm (not one 1 reconnection attempt until now) on my Debian 9 VirtualBox VM called HiveMQ "Community Edition" -> https://github.com/hivemq/hivemq-community-edition

First uninstall the existing Oracle JRE 8 (installed by default, how to do that you will find e.g. on stackoverflow or stackexchange) from Debian 9, then install "Zulu VM / JDK 11" from https://www.azul.com/downloads/zulu-community/?architecture=x86-64-bit&package=jdk, then install the platform-independent .jar file of HiveMQ. (Many many thanks to the HiveMQ and Zulu guys!!)

I'm sorry but to be honest i'm a lil bit disappointed from your product called "mosquitto". But the its support seems, at least, to be well. (@ralight : Thank you anyway!)

I described all steps what i have done and what system config i had that lead to the connections problem. The debian 9 was a clean installation i.m.o., no over-configured 3-4 years old system or something similar...

If you, mosquitto guys, are interested you can build up the same system constellation as i had. (Win 10 2004, VirtualBox 6.14 or .22, Debian Stretch most current, mosquitto from debian.org APT servers or most currrent Debian 9 mosquitto version from your own servers - if you have additional questions, so please don't hesistate to ask me. Will provide all environment informations you want to know...)

Now i can go home and my mind is free from MQTT-broker set up problems - goal achieved for my and my chief. And that's all we need.

**Comment by martijintro** [comment]
So closed, but just re-open it if you like...

Kind regards from Switzerland,
Jan

**Comment by jayjupdhig** [comment]
Still not interested what the problem was? On my side, the problem is 100% solved by using HiveMQ CE...

But: If you need more informations / details etc. about the problem, so don't hesitate to ask me.

If yes, maybe i will use mosquitto again. If not, HiveMQ also works well! ;-)


With kind regards,
Jan

**Comment by ralight** [comment]
Thanks for reopening this, closed issues  don't get seen.

The only way I have been able to reproduce this behaviour, using debian 9 on a VM on Windows 10 2004, is to have MQTT Explorer send invalid subscriptions with an empty topic filter, as I've described above. HiveMQ also correctly rejects those subscriptions though, so it isn't the problem that you are seeing.

Would you be able to run `tcpdump port 1883 -w 1771.pcap` on the VM and run it whilst the problem occurs, then either attach the file here or send it via email if you prefer.

**Comment by jayjupdhig** [comment]
thx will look asap

**Comment by jayjupdhig** [comment]
I also opened an issue on thomasnordquist/MQTT-Explorer#452.

With kind regards,
Jan

**Comment by ralight** [comment]
You mention timeouts there - did you find something useful in the pcap file?

**Comment by jayjupdhig** [comment]
Currently, i can't reproduce it anymore, maybe it's because of an additional Windows 10 2004 update? Really strange...!!

**Comment by jayjupdhig** [comment]
Will re-open it if it occurs again and i'm able to recognize what the problem is, e.g. with `tcpdump` or `WireShark`.

Thank you for your understanding.


Best regards from Switzerland,
Jan
