### ISSUE TITLE
Error: A TLS error occurred.

### ISSUE THREAD

**Issue by GopherJ** [eclipse/mosquitto#1775]
I use [this script](https://github.com/GopherJ/cfg/blob/master/cert/gen-cert.sh) to generate certificate, the generated certificate works well in emqx.

I can also connect to my broker using paho.mqtt.golang without any problem, it works also for MQTTX.

However, it doesn't work with `mosquitto_sub`, when I try:

```
mosquitto_sub -d -t "#"  -p 8883 -u xxx -P xxx  --cafile root-ca.pem --cert client.pem --key client.key
```
OR
```
mosquitto_sub -d -t "#"  -p 8883 -u xxx -P xxx  --cafile root-ca.pem --cert client.pem --key client.key --insecure
```

it always  says
```
Error: A TLS error occurred.
```

A lack of more information makes it hard to debug, any idea on this?

**Comment by GopherJ** [comment]
mosquitto_client: 1.4.15

**Comment by ralight** [comment]
Could you try on a more recent version of Mosquitto? That one is over 2 years old.

**Comment by GopherJ** [comment]
@ralight Hi, I tried mosquitto-clients@1.6.10, I got a different error:

```
OpenSSL Error[0]: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Error: A TLS error occurred.
```

It says `certificate verified failed`, but I can connect with MQTTX and paho.mqtt.golang + golang/tls without problem

**Comment by ralight** [comment]
I've tried the script and can connect just fine with the certificates it generates.

I can get the same error as you if I don't provide the correct hostname for the server I am connecting to, or if the hostname of the server does not match the server certificate. It may be that the other utilities you are using do not carry out these security checks.

**Comment by GopherJ** [comment]
@ralight Hi, thanks for taking time to test it.  In the openssl.cnf's alt_names section, I've provided the IP of the broker when I run the script so normally I think it's fine.

since paho.mqtt.golang & MQTTX  works fine, I think it should also be be accepted by mosquitto 

Since paho.mqtt.golang

**Comment by ralight** [comment]
So your certificate contains a commonName that does not match your hostname, and a single SAN IP entry, and no other SAN entries?

**Comment by GopherJ** [comment]
@ralight Hi, in my certificate it contains:

- DNS.1 = <domain of cloud broker>
- IP.1 = <ip of cloud broker>
- IP.2 = 127.0.0.1

- CN = <ip of broker>

**Comment by GopherJ** [comment]
BTW @ralight I forgot to mention, the same script worked before for mosquitto. I upgraded it to x509v3 recently and added SAN because golang's tls parsing requires x509v3.

After upgrading, it stops working.

I'm wondering is it because of x509v3 which isn't supported by mosquitto?

**Comment by GopherJ** [comment]
See also: https://github.com/eclipse/mosquitto/issues/546

**Comment by GopherJ** [comment]
@ralight Hi, finally I solved my issue, https://github.com/GopherJ/cfg/commit/cff140249f2b40f31a07a1bc49d77c698b0b2d10

There are two problems:

- every certificate must have different CN
- Root Certificate must have `CA:TRUE`

Thanks for your help and sorry for my mistake!
