### ISSUE TITLE
mosquitto_pub does not exit 1 on connection refused

### ISSUE THREAD

**Issue by jflambert** [eclipse/mosquitto#1778]
mosquitto_pub version 1.6.9 running on libmosquitto 1.6.9
using the alpine-3.12 [mosquitto-clients](https://pkgs.alpinelinux.org/package/v3.12/main/x86_64/mosquitto-clients) apk.

```
/ # mosquitto_pub -t test -m test -u gooduser -P goodpass
/ # echo $?
0
```

```
/ # mosquitto_pub -t test -m test -u baduser -P badpass
Connection error: Connection Refused: bad user name or password.
/ # echo $?
0
```

**Comment by ralight** [comment]
That's now fixed in the `fixes` branch, thanks for the report.
