### ISSUE TITLE
Last update in latest tag as well as 1.6 tag having missing shared library

### ISSUE THREAD

**Issue by t-abraham** [eclipse/mosquitto#1783]
The latest update of the MQTT broker broke something off.
It can't find the shared lib. Am I missing something?

error details are as followed

> Attaching to MQTT-Broker
> MQTT-Broker | Error loading shared library libssl.so.48: No such file or directory (needed by /usr/sbin/mosquitto)
> MQTT-Broker | Error loading shared library libcrypto.so.46: No such file or directory (needed by /usr/sbin/mosquitto)
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: X509_NAME_get_text_by_NID: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: X509_LOOKUP_file: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_state: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: TLS_client_method: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: ASN1_STRING_length: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_get_error: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_get_fd: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: ENGINE_free: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: TLS_server_method: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: BN_hex2bn: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: sk_pop_free: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: OBJ_sn2nid: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: EVP_MD_CTX_free: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_get_ex_data: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_write: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: ENGINE_set_default: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_get_ex_data: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: sk_value: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_free: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: OCSP_BASICRESP_free: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSLv23_server_method: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_want: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: EVP_DigestFinal_ex: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_get_SSL_CTX: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: X509_STORE_add_lookup: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: ENGINE_init: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: UI_method_set_reader: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: OCSP_response_status: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_use_certificate_chain_file: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_set_fd: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_get_ex_new_index: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: X509_NAME_ENTRY_get_data: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: BIO_push: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_callback_ctrl: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_set_verify: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: BN_num_bits: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: UI_create_method: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: ENGINE_ctrl_cmd: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: BIO_read: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_set_default_passwd_cb: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_set_default_passwd_cb_userdata: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: BIO_f_base64: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: OCSP_resp_get0: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: RAND_bytes: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: UI_method_get_reader: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: X509_get_subject_name: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_get_peer_cert_chain: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_set_session_id_context: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_set_SSL_CTX: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_set_ex_data: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: CONF_modules_unload: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_get_wbio: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: UI_destroy_method: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_library_init: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: d2i_OCSP_RESPONSE: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: OCSP_single_get0_status: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_set_ex_data: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: BIO_new_socket: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: UI_method_set_closer: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_read: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: EVP_DigestInit_ex: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: ERR_error_string_n: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: X509_STORE_CTX_get_current_cert: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_ctrl: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_new: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: BN_free: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: OPENSSL_add_all_algorithms_noconf: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_shutdown: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: BIO_set_flags: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: OCSP_crl_reason_str: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: OCSP_basic_verify: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: ERR_clear_error: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: OPENSSL_init_crypto: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: UI_method_get_closer: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: EVP_DigestUpdate: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: OCSP_response_status_str: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: OCSP_RESPONSE_free: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_accept: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_new: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: EVP_get_digestbyname: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: UI_OpenSSL: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_get_ex_new_index: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_get_peer_certificate: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: X509_NAME_get_entry: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: BIO_new: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: BIO_ctrl: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: BIO_free: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_load_verify_locations: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: OCSP_cert_status_str: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: X509_get_ext_d2i: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: X509_load_crl_file: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: UI_method_set_writer: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_ctrl: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: X509_STORE_CTX_get_error_depth: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: BN_bn2bin: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: ERR_error_string: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: X509_STORE_set_flags: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_pending: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: EVP_MD_CTX_new: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_use_PrivateKey_file: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_set_cipher_list: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: OCSP_resp_count: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: EC_KEY_free: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: ASN1_STRING_get0_data: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: X509_free: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: ENGINE_finish: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: OCSP_check_validity: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: X509_NAME_get_index_by_NID: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: X509_NAME_print_ex: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: sk_num: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: UI_method_set_opener: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_connect: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_free: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_load_error_strings: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: ERR_get_error: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: UI_method_get_writer: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_set_info_callback: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: BIO_free_all: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_use_PrivateKey: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_get_cert_store: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_get_servername: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: ENGINE_load_builtin_engines: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_check_private_key: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: X509_STORE_CTX_get_ex_data: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: UI_method_get_opener: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: BIO_write: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_CTX_set_alpn_protos: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_get_verify_result: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_get_ex_data_X509_STORE_CTX_idx: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: ENGINE_load_private_key: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: BIO_s_mem: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_get_rbio: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: EC_KEY_new_by_curve_name: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: PEM_read_DHparams: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: ENGINE_by_id: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: SSL_set_bio: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: OCSP_response_get1_basic: symbol not found
> MQTT-Broker | Error relocating /usr/sbin/mosquitto: GENERAL_NAME_free: symbol not found

**Comment by WireFuCo** [comment]
Same issue here, reverted to 1.6.10 tag to get it to work again

**Comment by gregbert42** [comment]
same issue. 1.6.10 tag worked

**Comment by t-abraham** [comment]
I keep thanks for the tag which worked. Any updates from the DevOps regarding the break?

**Comment by ralight** [comment]
Sorry for the trouble, the fix is waiting on the docker official image team now.

**Comment by ralight** [comment]
You could also use the new 1.6-openssl tag as well.

**Comment by ralight** [comment]
This should now be available again.

**Comment by t-abraham** [comment]
Yes its avialable and working back again. Thanks
