### ISSUE TITLE
Problem running mqtt on Synology

### ISSUE THREAD

**Issue by ranrinc** [eclipse/mosquitto#1786]
latest synology running docker.

Somehow 1.6.10 did not have this problem, however 1.6.11 is having this error

logs:
```
chown: /mosquitto/config/mosquitto.conf: Read-only file system
chown: /mosquitto/config: Read-only file system
chown: /mosquitto/config: Read-only file system
```

Unsure how to fixed this mess...

**Comment by caco3** [comment]
I also have an issue on a Synology NAS, see https://github.com/eclipse/mosquitto/issues/1787

But I am not sure if they have the same root cause, so I created another issue.

**Comment by ranrinc** [comment]
So far MQTT keep showing the error and its rebooting constantly.

**Comment by caco3** [comment]
Is `/mosquitto/config` a mounted host folder? Do you have write access there or is it possible that your host system has an issue? It more looks like a docker problem than a Mosquitto problem!

**Comment by caco3** [comment]
And BTW, my issue got solved with the latest docker image

**Comment by ranrinc** [comment]
I dont think its a write issues since I downgrade to 1.6.10 and it work flawlessly. So again unsure what happen.. So no choice that I have to run on 1.6.10 at the time being

**Comment by ralight** [comment]
@ranrinc Once the latest image is built (I have no control over that) you should be up and running again.

**Comment by ranrinc** [comment]
no update as yet..

**Comment by ralight** [comment]
The image was updated days ago, are you sure you have the latest one?

**Comment by ranrinc** [comment]
> The image was updated days ago, are you sure you have the latest one?

latest update still 1.6.11 which is not working for me

**Comment by ralight** [comment]
The version number won't change, it's the docker image which has changed. The image id is `a53767a945f1`, does that match what you have?

**Comment by ranrinc** [comment]
> The version number won't change, it's the docker image which has changed. The image id is `a53767a945f1`, does that match what you have?

yup got it fixed... thanks for the info

**Comment by positron96** [comment]
Pulled latest from dockerhub (1.6.12), still have this issue

**Comment by ralight** [comment]
@positron96 The startup script will attempt to run chown on `/mosquitto` if the user we are running as is root, and if `/mosquitto` is a directory. If it fails, it will print the error messages but should continue just fine.

Is this what you see - the error messages and a running broker, or does it not run?

**Comment by positron96** [comment]
Yes, it's complaining, but seems to be running fine. False alarm.

**Comment by ralight** [comment]
:+1:
