### ISSUE TITLE
Problem building Mosquitto Libraries for QNX 7 from Windows: linker cannot find -ldl

### ISSUE THREAD

**Issue by iscopa** [eclipse/mosquitto#1789]
I am trying to build the mosquitto libraries using CMakelists.txt and QNX QCC v5.4.0 and get the error above. I do not know how to remove the flag to that library or to link that library if needed. Could you please help on this?

Thank you

**Comment by ralight** [comment]
I don't have access to QNX or any experience with it, so can only suggest that you have a look around the cmake files to see what changes are needed. Start with `src/CMakeLists.txt` and look for this block:

```
if (UNIX)
    if (APPLE)
        set (MOSQ_LIBS ${MOSQ_LIBS} dl m)
    elseif(QNX)
        set(MOSQ_LIBS ${MOSQ_LIBS} m socket)
    else(APPLE)
        set (MOSQ_LIBS ${MOSQ_LIBS} dl m)
        find_library(LIBRT rt)
        if (LIBRT)
            set (MOSQ_LIBS ${MOSQ_LIBS} rt)
        endif (LIBRT)
    endif (APPLE)
endif (UNIX)
```

The QNX detection should be working and hence be adding the `m` and `socket` library, but perhaps it isn't. It may be that the `else` block at the end is being used instead. You could try removing the `dl` from there to see. If that works, then I'd be grateful if you figured out how to make QNX detection work in your case so this can be fixed.

**Comment by iscopa** [comment]
Thank you!

The QNX detection did not work, indeed, and your hint worked. However, after introducing the changes I got a new error:

CMakeFiles/mosquitto.dir/net.c.o: undefined reference to symbol 'getpeername@@libsocket.so.2'
... //target/qnx7/x86_64/lib/libsocket.so.3: error adding symbols: DSO missing from command line

Would you please help on that too?

Thank you again

**Comment by ralight** [comment]
I believe that QNX needs to link against the `socket` library, that would need adding to where you removed the `dl`.

**Comment by iscopa** [comment]
Yes, that did work. Thank you very much! :)
