### ISSUE TITLE
mosquitto_connect does not support non blocking mode

### ISSUE THREAD

**Issue by nedo99** [eclipse/mosquitto#1791]
Hi,

When trying to connect to the broker that has an IP address that cannot be resolved, `mosquitto_connect` hangs until the message `Connection timed out` is printed. Is there a way to set this timeout to something shorter?

I am aware of `mosquitto_socket` method which returns socket descriptor, but it is `-1` before connecting, so it is not possible to set any options.  Looking at the code at [connect.c](https://github.com/eclipse/mosquitto/blob/8123e767dec0dc5ed00446e1127ab1064c6412d6/lib/connect.c) I see that there is a blocking parameter but, it is hardcoded and I cannot find the way to set it.

Is there are alternative here?

Regards,
Nedim

**Comment by karlp** [comment]
try https://mosquitto.org/api/files/mosquitto-h.html#mosquitto_connect_async

**Comment by nedo99** [comment]
Yes but it requires to use library with threaded interface which is not what I really want. I use `mosquitto_loop`.

**Comment by ralight** [comment]
I believe that requirement is now out of date, but I'm not entirely sure. Please feel free to give it a try and report back.

**Comment by nedo99** [comment]
I tested it, but not good. `mosquitto_connect_async` returns always success. I guess it expects confirmation from loop thread.

Btw I am using `v1.6.8` mosquitto library.

**Comment by karlp** [comment]
no, you just have to start calling loop(), and you're going to want the on_connect() handler now.

**Comment by nedo99** [comment]
That solved it. Thanks!
