### ISSUE TITLE
1.6.11 Memory Leak

### ISSUE THREAD

**Issue by mbates14** [eclipse/mosquitto#1793]
I am running into a severe memory leak, and I dont know why. Whether I am sending data through it or not, it still munches up RAM. 

The more data I push through, the worse it is of course. but I checked for retained messages, and nothing comes up. So I am not sure where to go from here. tried deleting, recompiling/installing the broker with no change in behavior. Even tried removing and disabling the ACL we had implemented. We send about 1.3GB an hour on traffic on a normal day. (This equates to about 361.1KB/s)

Here is the ubuntu version we are running: This is running inside a VM on an unraid server. 
![image](https://user-images.githubusercontent.com/22461464/90455070-fceeb100-e0c2-11ea-8904-c68e431fb753.png)

![unknown](https://user-images.githubusercontent.com/22461464/90455102-17288f00-e0c3-11ea-97e7-7c346a4c2bdb.png)

After restarting the broker: 
![unknown (1)](https://user-images.githubusercontent.com/22461464/90455117-24de1480-e0c3-11ea-8054-2d504e3fdd9b.png)
 
![unknown (2)](https://user-images.githubusercontent.com/22461464/90455326-cc5b4700-e0c3-11ea-87d8-5f2cebb5d1df.png)

any ideas?

**Comment by mbates14** [comment]
Actually, I think we may have solved it. one of the python scripts was sending as QOS=2 (paho) and was causing RAM to fill up and retain messages, fast... 

BTW, yes this was crashing mosquitto with out of ram errors within hours.

**Comment by ralight** [comment]
Can I just check what was happening? It's not quite clear whether there is a real problem.

If you python script was sending retained messages (which the broker must store) to an infinite number of topics, then queueing limits would not help.

If your python script was sending rapid qos 2 messages to a single topic, which many clients were subscribed to, then the queueing limits should absolutely have helped.

Which situation were you in?

**Comment by mbates14** [comment]
No, the script was not sending retained messages. Only thing was happening, it was sending messages as QOS=2. 

After changing it to 0, Thins stabilized as shown here:
![Screenshot_20200818-105720_Chrome](https://user-images.githubusercontent.com/22461464/90529925-4205f800-e142-11ea-917c-a6d665336eac.jpg)

the python script is a script designed to make other script/shell calls through MQTT. Now sometimes there may be topics being published on, that anyone may not be listening on at the moment. 

If simply disconnecting a client or not listening on a topic that is being pushed as QOS=2 can take down a server like this, Then we have a problem. 

I dont exactly know how to answer your question in more detail? We simply changed this line from qos=2 to 0:

![unknown](https://user-images.githubusercontent.com/22461464/90530168-927d5580-e142-11ea-946d-5573efb31e59.png)

**Comment by ralight** [comment]
I've been trying to reproduce this and have failed so far.

mosquitto.conf:
```
max_queued_bytes 1000
max_queued_messages 5
```

Python spam client:
```
import paho.mqtt.client as mqtt
import time

mqttc = mqtt.Client()
mqttc.connect("localhost", 1883, 60)
mqttc.loop_start()
while True:
    mm = mqttc.publish("mqtt/test", "."*700000, qos=2)
    time.sleep(0.0004)

```

I also had `mosquitto_sub -t \$SYS/broker/publish/bytes/received -v` running so I could check that I'd sent a large number of bytes to the broker.

I ran the broker normally, and using the valgrind massif tool to track the heap memory usage. This is the massif trace for one of those runs, when I set 83.6GB with the python publisher, and tried to stress the system in other ways at the same time to starve the broker of CPU time.
![1793](https://user-images.githubusercontent.com/79578/90539207-75af4500-e177-11ea-9bf8-4d3d9c73ded2.png)

Are there any other configuration or client differences I should be aware of to try to reproduce this?

**Comment by mbates14** [comment]
Let me find out, I have to speak to another person who is operating the server.

**Comment by ralight** [comment]
Thanks

**Comment by mbates14** [comment]
I tried pinging him, Hopefully he will get back with me soon.

**Comment by mbates14** [comment]
Here is info I got back:

`root@mosquitto:/etc/mosquitto# cat mosquitto.conf
# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d


root@mosquitto:/etc/mosquitto# cd conf.d/
root@mosquitto:/etc/mosquitto/conf.d# ls
default.conf  README
root@mosquitto:/etc/mosquitto/conf.d# cat default.conf
allow_anonymous false
password_file /etc/mosquitto/passwd
max_inflight_messages 1
max_queued_bytes 1000
max_queued_messages 5
root@mosquitto:/etc/mosquitto/conf.d#`

**Comment by mbates14** [comment]
This is the pythons cript that had to be modified: 
https://github.com/jpmens/mqtt-launcher

This is generally as-is, he mentioned that he modified the log output to go over a topic instead of a file. Thats it really.

**Comment by ralight** [comment]
This was extremely intermittent to reproduce, with seemingly identical runs sometimes succeeding and sometimes not. I'm quite certain this is fixed, but I'd still like your confirmation that you no longer see the problem.

**Comment by mbates14** [comment]
I figured it was a "planets alignment" scenario. I will have him recompile and update the server, and try again. 

Thanks.
