### ISSUE TITLE
receiving "self published" retained message when subscribe with subscription option : nolocal=true

### ISSUE THREAD

**Issue by DrmagicE** [eclipse/mosquitto#1796]
Publish a retained message and subscribe the topic in the same client connection with subscription option: nolocal=true.
The client will receive the "self published" retained message.

According the spec, it seems the client should not receive the retained message because the subscriber and the sender are the same client.
> Bit 2 of the Subscription Options represents the No Local option. If the value is 1, Application Messages MUST NOT be forwarded to a connection with a ClientID equal to the ClientID of the publishing connection.

**Comment by ralight** [comment]
I think this is something that needs clarification in the spec. My take on this is that the relationship between the sender and the retained message does not remain after the retained message has been set. This means that if a client has a no-local subscription active at the same time as it publishes a retained message to a matching topic, then the message must not be delivered to it. If however, a client publishes a retained message to a topic, and then makes a no-local subscription which matches that topic, then there is no relationship between the retained message and the subscriber, and hence it should be delivered.

**Comment by DrmagicE** [comment]
I agree this case should be clarified in the spec. thanks for your explanation.
