### ISSUE TITLE
Different sizeof(struct mosquitto) in Broker

### ISSUE THREAD

**Issue by dennisip86** [eclipse/mosquitto#180]
1. Set WITH_WEBSOCKETS = yes
2. Print the sizeof(struct mosquitto) in src/read_handle.c:232
3. print the sizeof(struct mosquitto) in lib/send_mosq.c:86
4. Publish a message to a subscriber

I got 448 and 456

**Comment by ralight** [comment]
Yes, that is as expected. struct mosquitto is a private type, you shouldn't be worrying about its size.

The struct mosquitto in src/read_handle.c is as used by the broker.
The struct mosquitto in lib/send_mosq.c is as used by the client library.

The broker and client library have different requirements, so the struct changes.

What is it you're trying to achieve?

**Comment by dennisip86** [comment]
The sizeof(struct mosquitto) 448 and 456 was printed by the same broker.
It will crash when access the member of struct mosquitto declare after:

#  ifdef WITH_WEBSOCKETS
#    if defined(LWS_LIBRARY_VERSION_NUMBER)
	struct lws *wsi;
#    else
	struct libwebsocket_context *ws_context;
	struct libwebsocket *wsi;
#    endif
#  endif

Because struct mosquitto is different size between src/ and lib/ in the same broker!!

**Comment by ralight** [comment]
Thanks, I thought you were worried about the difference between the client and broker struct instead. This is now fixed.
