### ISSUE TITLE
Auth-plugin on Windows

### ISSUE THREAD

**Issue by roebotron** [eclipse/mosquitto#1800]
I'm trying an auth plugin on the Windows distribution (version1.6.11). 
The trouble is not having the symbols available for linkage which are declared in `mosquitto_broker.h` (e.g. mosquitto_client_certificate, mosquitto_log_printf). As the "Dependency Walker" tool shows, they aren't exported by the `mosquitto.dll`. 
Currently I'm not sure if they're only lacking an export declaration or if they aren't part of the DLL at all.

**Comment by ralight** [comment]
Those symbols are part of the broker mosquitto.exe, not the client library, mosquitto.dll. They aren't currently exported by mosquitto.exe though, I'll have to look into that and whether there are issues around exporting symbols from an executable rather than a dll on Windows.

**Comment by ralight** [comment]
I believe this should be fixed in the `develop` branch now.

**Comment by ralight** [comment]
This has been released in version 2.0.
