### ISSUE TITLE
Man page flaw on MQTT v5 property "authentication-method"

### ISSUE THREAD

**Issue by roebotron** [eclipse/mosquitto#1801]
[https://mosquitto.org/man/mosquitto_sub-1.html#properties](url) states that "authentication-method" expects an UTF-8 String _pair_. That's not the case, it expects a single UTF-8 String (`property_mosq.c` line 558).

**Comment by ralight** [comment]
This is fixed in the repo and will be fixed on the web as part of the 2.0 release, so I'm closing this report.

**Comment by ralight** [comment]
Thanks very much for all of these small paper cut issues you have been reporting, they are appreciated.
