### ISSUE TITLE
libmosquitto MQTT5 API - iterate over received properties

### ISSUE THREAD

**Issue by PeterDeHerdt** [eclipse/mosquitto#1802]
### Description
When a callback is called (conack, subscribe, ...) it is possible to check if a certain property ID is available and take the next as well.

Currently we need to check which properties are received and depending on the set of properties do specific actions in our MQTT client build using libmosquitto.

There is currently no API available to iterate over all these received properties, and the structures are `private` defined in a header file that is not part of the public API.

Currently we have copied these structure definitions into our MQTT client code, but we prefer to have a better solution.

**Comment by ralight** [comment]
Hi Peter, the `develop` branch which should be released "soon" has added `mosquitto_property_next()` which lets you iterate through properties. I hope that is sufficient.

**Comment by PeterDeHerdt** [comment]
Hi Roger,

That is great news.

Thanks.

**Comment by ralight** [comment]
This was released in version 2.0.
