### ISSUE TITLE
Invalid configuration options are ignored

### ISSUE THREAD

**Issue by cfstras** [eclipse/mosquitto#1806]
## Example configuration
```
port 1883
listener port 1234 # this is invalid
```

## Expected behavior
Originally, I though this would add a second listener on port 1234. (It's a little hard to see in the docs, that _italics_ are meant to be placeholders).

So the expectation is that mosquitto would not start, or log an error.

## Actual behavior 

However, the journal reports:
```
Aug 28 09:27:58 ldx systemd[1]: Starting LSB: mosquitto MQTT v3.1 message broker...
Aug 28 09:27:58 ldx mosquitto[32249]: Starting network daemon:: mosquitto.
Aug 28 09:27:58 ldx systemd[1]: Started LSB: mosquitto MQTT v3.1 message broker.
```

The invalid setting is completely ignored.

**Comment by ralight** [comment]
I tested on 1.3.5, 1.4.15, 1.5.9, and 1.6.12 and got the same result:

```
$ cat 1806.conf 
port 1883
listener port 1234 # this is invalid
$ mosquitto -c 1806.conf
Error: Invalid port value (0).
Error found at 1806.conf:2.
Error: Unable to open configuration file.
$ echo $?
3
```

What version are you using, and what system are you running on?

**Comment by cfstras** [comment]
Yes, you're right. I just tested again and saw I was following a red hering and looking at the wrong log file.

Also, it seems like the systemd integration for LSB init does not realize when a service exits with code != 0 right after starting... But that's not a problem in mosquitto.
