### ISSUE TITLE
where can mosquitto.pid and mosquitto.db be written when using snap version?

### ISSUE THREAD

**Issue by amitrao17** [eclipse/mosquitto#1808]
where can mosquitto.pid and mosquitto.db be written? all the paths i've tried in mosquitto.conf have quietly not been written to
~/snap/mosquitto
/var/snap/mosquitto/common

i know snaps don't have access to the whole filesystem.

**Comment by ralight** [comment]
The service that runs automatically can access `/var/snap/mosquitto/common`. If you run it manually as a normal user, then `/home/user/snap/mosquitto/common/` is accessible. I've just tested both cases and they work for me. You need to use the config files `/var/snap/mosquitto/common/mosquitto.conf` or `/home/user/snap/mosquitto/common/mosquitto.conf` respectively.

If it still doesn't work, let me know.

**Comment by amitrao17** [comment]
thanks for the response; nope that doesn't work. i'd expect the .pid and maybe the .db file immediately after

sudo snap mosquitto restart

but no, I see nothing. here's some relevant output:

amit@xps:/snap/mosquitto$ grep "snap" /var/snap/mosquitto/common/mosquitto.conf
pid_file /var/snap/mosquitto/common/mosquitto.pid
persistence_location /var/snap/mosquitto/common/

amit@xps:/snap/mosquitto$ ls -l /var/snap/mosquitto/common
total 88
-rw-r--r-- 1 root root 44660 Aug 29 21:42 mosquitto.conf
-rw-r--r-- 1 root root 44555 Aug 25 15:01 mosquitto_example.conf

amit@xps:/snap/mosquitto$ ps aux | grep mosquitto
root     3963302  0.0  0.0   4636   928 ?        Ss   21:44   0:00 /bin/sh /snap/mosquitto/387/launcher.sh
root     3963327  0.0  0.0  23936  3872 ?        S    21:44   0:00 /snap/mosquitto/387/usr/sbin/mosquitto -c /var/snap/mosquitto/common/mosquitto.conf

amit@xps:/snap/mosquitto$ ls -l /var/snap/mosquitto
total 8
drwxr-xr-x 2 root root 4096 Aug 25 15:01 387
drwxr-xr-x 2 root root 4096 Aug 28 21:41 common
lrwxrwxrwx 1 root root    3 Aug 25 15:01 current -> 387

Thanks for your help! I'm running Ubuntu 20.04 (sort of)

**Comment by amitrao17** [comment]
ok, I'm a liar. a mosquitto.db file showed up.
no sign of mosquitto.pid though....

**Comment by ralight** [comment]
47 bytes is empty, yes. Did you store any retained messages or have any durable clients (with clean session set to false) connect? If not, then there wouldn't be anything there. Also note that the persistence file is only written once every 30 minutes by default.

As per the documentation, the pid file is only written if running in daemon mode. The snap doesn't run in daemon mode because there really isn't much point these days.

**Comment by ralight** [comment]
The pid file is now (as of 2.0) always written if the `pid_file` option is used, so I think this can be closed.
