### ISSUE TITLE
No error when providing directory path as configuration file

### ISSUE THREAD

**Issue by Odysseus1710** [eclipse/mosquitto#1814]
If I start mosquitto and provide a directory path as configuration file like `mosquitto -c /etc/` , the broker tells me that it succesfully loaded the conf file: `1599199210: Config loaded from /etc/.`

I think its correct to use the defaults in this case even if there is a valid configuration file within this directory (which mosquitto does) but it is misleading to me that it does not report that the configuration file could not be loaded

**Comment by ralight** [comment]
Thank you, that is now fixed in the `develop` branch.
