### ISSUE TITLE
CONNACK reason code error

### ISSUE THREAD

**Issue by allenzt** [eclipse/mosquitto#1817]
Test steps:
I uses "MQTT.fx 1.7.1" to connect mosquitto broker(1.6.8) with wrong password, it return reason code 5(not authorized). In my view, it should return reason code 4( Connection rejected for damaged username or password). could you help to clarify this? thanks in advance!

mosquitto log:
1599450409: Sending PUBACK to local-api-client (m928, rc0)
1599450411: New connection from 10.5.16.196 on port 1085.
1599450411: Sending CONNACK to 10.5.16.196 (0, 5)
1599450411: Socket error on client <unknown>, disconnecting.
1599450411: New connection from 10.5.16.196 on port 1085.
1599450411: Sending CONNACK to 10.5.16.196 (0, 5)
1599450411: Socket error on client <unknown>, disconnecting.
1599450411: Received PUBLISH from local-api-client (d0, q1, r0, m929, 'v1/io/info', ... (36 bytes))
1599450411: Sending PUBACK to local-api-client (m929, rc0)
1599450413: Received PUBLISH from local-api-client (d0, q1, r0, m930, 'v1/io/info', ... (36 bytes))
1599450413: Sending PUBACK to local-api-client (m930, rc0)
1599450415: New connection from 10.5.16.196 on port 1085.
1599450415: Sending CONNACK to 10.5.16.196 (0, 5)
1599450415: Socket error on client <unknown>, disconnecting.
1599450415: New connection from 10.5.16.196 on port 1085.
1599450415: Sending CONNACK to 10.5.16.196 (0, 5)
1599450415: Socket error on client <unknown>, disconnecting.
1599450415: Received PUBLISH from local-api-client (d0, q1, r0, m931, 'v1/io/info', ... (36 bytes))
1599450415: Sending PUBACK to local-api-client (m931, rc0)
1599450417: Received PUBLISH from local-api-client (d0, q1, r0, m932,

**Comment by ralight** [comment]
Certainly. This is the table from the MQTT v3.1.1 spec.

Value | Return Code   Response | Description
-- | -- | --
4 | 0x04 Connection Refused, bad user name or password | The data in the user name or password is malformed
5 | 0x05 Connection Refused, not authorized | The Client is not authorized to connect

Reason code 4 is definitely for when the format of the data in the username or password is invalid. I would say that means "I have looked at the username/password and it is bad data, so I haven't even attempted to authenticate with it".

Reason code 5 means "The username and password are in a good format, but they do not match any credentials and so authentication failed."

**Comment by allenzt** [comment]
Thanks a lot! I had misunderstood  those reason code.

**Comment by ralight** [comment]
No problem :)
