### ISSUE TITLE
Crash in Mosquitto with threading support enabled on Windows

### ISSUE THREAD

**Issue by santoshks68** [eclipse/mosquitto#1819]
There is a bug in mosquitto_new (lib/mosquitto.c) where the log mutex is being used before it is initialized. This causes a crash when Mosquitto is built with threading support on Windows. In this scenario, mosquitto_new is being called from the constructor of the  C++ wrapper library, mosquittopp

**Comment by ralight** [comment]
Thank you, nicely spotted. This should now be fixed.
