### ISSUE TITLE
mosquitto lib erroneously closes stdin causing mosquitto_pub to fail

### ISSUE THREAD

**Issue by ostkamp** [eclipse/mosquitto#1823]
With the latest origin/fixes commit

a53712a1 (origin/fixes, origin/coverity-fixes) Don't use logging until log mutex is initialised.

the mosquitto library appears to be closing stdin.
This can be easily verified since **mosquitto_pub** command now fails when working with -l option:

```
$ LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH ./client/mosquitto_pub -d -h localhost -t topic -l < /etc/passwd
Client mosq-rUHw2zKr5K8bBcU1o9 sending CONNECT
Client mosq-rUHw2zKr5K8bBcU1o9 received CONNACK (0)

```
with no further output since it got stuck at some fgets(..., stdin) call according to GDB. Looking at filedescriptor list

```
$ ps -ef
ostkamp     4031    2914 99 17:37 pts/0    00:00:18 ./client/mosquitto_pub -d -h localhost -t topic -l
$ ls -l /proc/4031/fd
total 0
lrwx------ 1 ostkamp ostkamp 64 Sep 14 17:37 0 -> 'socket:[74951]
lrwx------ 1 ostkamp ostkamp 64 Sep 14 17:37 1 -> /dev/pts/0
lrwx------ 1 ostkamp ostkamp 64 Sep 14 17:37 2 -> /dev/pts/0
lrwx------ 1 ostkamp ostkamp 64 Sep 14 17:37 3 -> 'socket:[74952]'
lrwx------ 1 ostkamp ostkamp 64 Sep 14 17:37 4 -> 'socket:[74953]'
lrwx------ 1 ostkamp ostkamp 64 Sep 14 17:37 5 -> 'socket:[74954]'
lrwx------ 1 ostkamp ostkamp 64 Sep 14 17:37 6 -> 'socket:[74957]'

```
The stdin alias fd 0 is now suddenly a socket. and not a file.

With the previous commit 298d8494 it still works ok.

**Comment by ralight** [comment]
Thank you, you're quite right. That should now be fixed in the updated `fixes` branch.
