### ISSUE TITLE
Unable to use TLS in CLI tools with system default CAs

### ISSUE THREAD

**Issue by ctron** [eclipse/mosquitto#1824]
Using a simple command line like:

~~~
mosquitto_pub -d  -m '{"foo": "bar"}' -L mqtts://my-server:1234/foo
~~~

I would expect that the command line client tries to establish a connection using TLS, using the system wide CAs. Like `curl`, "HTTPie", …

However, `mosquitto_pub` silently uses non-TLS, which (in the best case) would simply fail:

~~~
Client mosq-XWCkqLXiT8HblH1vWQ sending CONNECT
Error: The connection was lost.
~~~

**Comment by ralight** [comment]
You can use `--capath /etc/ssl/certs` to activate TLS mode with the system CAs, but I agree that using `mqtts://` should do this by default.

**Comment by ctron** [comment]
Also, the path is different on all platforms.

**Comment by ralight** [comment]
This is now done in `develop`.
