### ISSUE TITLE
Port used as address on bridge reconnect

### ISSUE THREAD

**Issue by ElFishle** [eclipse/mosquitto#1828]
Hello,

I have a strange behaviour with a simple bridge configured like:
```
connection bridge-01
address test.mosquitto.org 1883

cleansession true
start_type automatic

topic # out 0
topic # in 0
```

Below is a log file:
```
1600292487: mosquitto version 1.6.9 starting
1600292487: Config loaded from /etc/mosquitto/mosquitto.conf.
1600292487: Opening ipv4 listen socket on port 1883.
1600292487: Opening ipv6 listen socket on port 1883.
1600292487: Connecting bridge (step 1) bridge-01 (test.mosquitto.org:1883)
1600292487: New connection from 127.0.0.1 on port 1883.
1600292487: Connecting bridge (step 2) bridge-01 (test.mosquitto.org:1883)
1600292487: New client connected from 127.0.0.1 as Homeautomation (p2, c1, k60).
1600292495: New connection from 192.168.0.106 on port 1883.
1600292495: New client connected from 192.168.0.106 as PiZeroW (p2, c1, k60).
1600292519: Socket error on client local.buildroot.bridge-01, disconnecting.
1600292524: Connecting bridge (step 1) bridge-01 (1883:1883)
1600292524: Connecting bridge (step 2) bridge-01 (1883:1883)
1600292524: Error creating bridge: Invalid argument.
```
There is a new dynamic IP assigned to the NAT translated network between 1600292495 and 1600292519, so the connection is disconnected. After a while the bridge is tried to be connected again, but this time the used address seems to be overwritten by the port number. Could someone try to explain what happens here? Is that a known issue which is already fixed in a later release?

Regards

Hannes

**Comment by ralight** [comment]
The `address` option is defined as follows:
```
#address <host>[:<port>] [<host>[:<port>]]
```

In other words, it is possible to specify multiple hosts for a bridge, which it can connect to in turn if one host fails. The port number is separated by a `:`, not a ` `, so you are specifying two hosts: `test.mosquitto.org` and `1883`. Try this instead:

```
address test.mosquitto.org:1883
```

**Comment by ElFishle** [comment]
You are very right, thank you very much for clarification. It's sometimes still good to have someone else having a look, just to avoid not seeing the forest because of lots of trees ...
