### ISSUE TITLE
about windows pthreads 

### ISSUE THREAD

**Issue by 975150313** [eclipse/mosquitto#1829]
I referred to this person's project
[https://github.com/coapp-packages/pthreads](url)

And I changed the CMakeList.txt  line56-78 to:

option(WITH_THREADING "Include client library threading support?" ON)
if (WITH_THREADING)
	add_definitions("-DWITH_THREADING")
	if (WIN32)
		if (CMAKE_CL_64)
			#set (PTHREAD_LIBRARIES C:\\pthreads\\Pre-built.2\\lib\\x64\\pthreadVC2.lib)
			set (PTHREAD_LIBRARIES $ENV{Library}\\pthreads\\lib\\pthreads.lib)
		else (CMAKE_CL_64)
			#set (PTHREAD_LIBRARIES C:\\pthreads\\Pre-built.2\\lib\\x86\\pthreadVC2.lib)
			set (PTHREAD_LIBRARIES $ENV{Library}\\pthreads\\lib\\pthreads.lib)
		endif (CMAKE_CL_64)
		#set (PTHREAD_INCLUDE_DIR C:\\pthreads\\Pre-built.2\\include)
		set (PTHREAD_INCLUDE_DIR $ENV{Library}\\pthreads\\include)
	else (WIN32)
		find_library(LIBPTHREAD pthread)
		if (LIBPTHREAD)
			set (PTHREAD_LIBRARIES pthread)
		else (LIBPTHREAD)
			set (PTHREAD_LIBRARIES "")
		endif()
		set (PTHREAD_INCLUDE_DIR "")
	endif (WIN32)
else (WITH_THREADING)
	set (PTHREAD_LIBRARIES "")
	set (PTHREAD_INCLUDE_DIR "")
endif (WITH_THREADING)

The program seems to be working well,and for vs ,nuget can be used to get pthreads ,new version is 2.9.4

As a mature project, I don't think mosquitto should include anything about paths, 
such as C:\\pthreads\\Pre-built.2\\lib\\x64\\pthreadVC2.lib

**Comment by ralight** [comment]
Version 2.1 will have no need for external thread libraries on Windows, so I'm closing this issue.

**Comment by todd-liu** [comment]
@ralight ，hi, what time release 2.1? now it's current tag version is 2.0.15, thanks
