### ISSUE TITLE
on OSX new Xcode 12  causes  a compile error in mosquitto/lib/mosquitto.c

### ISSUE THREAD

**Issue by p-hagen** [eclipse/mosquitto#1831]
Tried to recompile my test platform for the first time since xcode has been upgraded.
now getting this error

`~/GIT/domoticz/extern/mosquitto/lib/mosquitto.c:64:11: error: implicit declaration of function 'mach_absolute_time' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
`
This worked fine until the latest upgrade to xcode 12 where they implemented a fix:

`Clang now reports an error when you use a function without an explicit declaration when building C or Objective-C code for macOS (-Werror=implicit-function-declaration flag is on). This additional error detection unifies Clang's behavior for iOS/tvOS and macOS 64-bit targets for this diagnostic. (49917738)`

Workaround:
if you add #include <mach/mach_time.h> to mosquitto.c it compiles again

I have no idea if this occurs in parts of the mosquitto build.

Consider to make this a conditional include as the  same code compiles without change on a Raspberry pi

**Comment by ralight** [comment]
Thanks for the report, that is now fixed in the fixes branch.
