### ISSUE TITLE
Where can i get "mqtt_pub" and "mqtt_sub" windows exe files only?

### ISSUE THREAD

**Issue by jayjupdhig** [eclipse/mosquitto#1832]
Which means the console clients to publish and subscripe...

thank you very much for your feedbacks.

With kind regards,
Jan

**Comment by ralight** [comment]
If you mean `mosquitto_sub` and `mosquitto_pub`, which are the command line clients that the Mosquitto project provides, then there are Windows installers here: https://mosquitto.org/download/

If you mean something else, then I'm afraid you'll have to look somewhere else :)

**Comment by jayjupdhig** [comment]
Thank you very much. I copied them from the program files folder to another folder called "mqtt_clients", then zipped it, then uploaded it to: https://www.file-upload.net/download-14299938/mqtt_clients.zip.html

...for all they only want the clients and NO mosquitto installtion! ;-)

So ticket can be closed now.
