### ISSUE TITLE
Dashes in MQTT usernames - inconsistent behavior

### ISSUE THREAD

**Issue by bogorad** [eclipse/mosquitto#1833]
`mosquitto_pass` is okay with usernames like `location-type-name`, processes username/pass, stores in the password file. But on connection, the authentication fails.

Should either ban those in `mosquitto_pass` or allow authentication.

**Comment by ralight** [comment]
That's not the behaviour that I see. Here is a recording of me testing this out:

https://asciinema.org/a/Nqme3T1SEzINDx4pFsiLCFdmr

**Comment by ralight** [comment]
I suspect you are really seeing problems when using the `:` character, which is documented as being forbidden, but isn't rejected by mosquitto_passwd. I've changed that so it is now rejected. If you still do have a problem with the literal username `location-type-name` please let me know.

**Comment by bogorad** [comment]
@ralight - I was having consistent problems with usernames containing dashes over TLS, and they went away when I disposed of dashes. Now I've done more testing, including via TLS, and it all works. Sorry for the false alarm, and thank you for responding!
