### ISSUE TITLE
bridge_insecure - Contradicting documentation

### ISSUE THREAD

**Issue by chegancasb** [eclipse/mosquitto#1837]
when accessing "man mosquitto.conf" on the bridge_insecure part it states:

       bridge_insecure [ true | false ]
           When using certificate based TLS, the bridge will attempt to verify
           the hostname provided in the remote certificate matches the
           host/address being connected to. This may cause problems in testing
           scenarios, so bridge_insecure may be set to false to disable the
           hostname verification.

           Setting this option to true means that a malicious third party
           could potentially inpersonate your server, so it should always be
           set to false in production environments.

This sentence "This may cause problems in testing scenarios, so bridge_insecure may be set to **true** to disable the hostname verification." so that it is in line with the parameter name and with the following paragraph.

Seen in version 1.6.9 - Mosquitto Project                 02/27/2020                 MOSQUITTO.CONF(5)

**Comment by ralight** [comment]
Thank you, you are quite right that is confusing. I've just pushed a fix for it.
