### ISSUE TITLE
makefile tries to install from docs directory even when with_docs is turned off

### ISSUE THREAD

**Issue by minghuadev** [eclipse/mosquitto#184]
Hi, This is just a bit annoying, not really a big issue. I've been working around by just comment out this line 40 from makefile: 

         38 install : mosquitto
         39         set -e; for d in ${DIRS}; do $(MAKE) -C $${d} install; done
         40         ##set -e; for d in ${DOCDIRS}; do $(MAKE) -C $${d} install; done
         41         $(INSTALL) -d ${DESTDIR}/etc/mosquitto

Or by surrounding the line with conditions: 

     install : mosquitto
            set -e; for d in ${DIRS}; do $(MAKE) -C $${d} install; done
    +ifeq ($(WITH_DOCS),yes)
            set -e; for d in ${DOCDIRS}; do $(MAKE) -C $${d} install; done
    +endif
            $(INSTALL) -d ${DESTDIR}/etc/mosquitto

The reason I avoid building the docs is for fast turn-around time. I also turn off many other options. And avoid the lib and client directories since I only work on the websocket server part. 

If this can be fixed from the source it may benefit other people too. 

Thanks.

**Comment by ralight** [comment]
Thanks, that's fixed now.

**Comment by minghuadev** [comment]
Thank you very much for the quick response!
