### ISSUE TITLE
Websockets over SSL doesn't work anymore since 1.6.9

### ISSUE THREAD

**Issue by Elleven1** [eclipse/mosquitto#1840]
When enabling a websockets listener with SSL configured, you're not able to connect to the broker via the. No debug output is generated by the broker in this case, what ever is configured for logging (no file output as well as nothing to stdout). 

I tried also using http_dir directive in the conf-file. When requesting non-existing files via HTTPS using a browser, you'll get a 404 back from the broker. BUT when requesting any existing file in the http_dir directory, the response is never getting completed. The HTTP header is received successfully, but the content is not transmitted and the connection between the browser and the broker seems to be kept open endless.

I rolled back my installation step by step from 1.6.12 to 1.6.8 with the same configuration and certs, and everything works fine with 1.6.8, but not with 1.6.9 and above. I'm using the 64 bit Windows version tested on a Wondows 10 (version 2004) as well as on a Windows Server 2019.

My CONF file:
```
listener 1883
protocol mqtt

listener 8883
protocol mqtt
cafile C:\Program Files\mosquitto\certs\CA.crt
certfile C:\Program Files\mosquitto\certs\broker.crt
keyfile C:\Program Files\mosquitto\certs\broker.key

listener 9001
protocol websockets
http_dir C:\Program Files\mosquitto\www

listener 9883
protocol websockets
cafile C:\Program Files\mosquitto\certs\CA.crt
certfile C:\Program Files\mosquitto\certs\broker.crt
keyfile C:\Program Files\mosquitto\certs\broker.key
http_dir C:\Program Files\mosquitto\www

allow_anonymous true
auto_id_prefix MyIoTstuff_

log_type all
websockets_log_level 1023
log_dest stdout
log_dest file debug.log
log_timestamp true
connection_messages true
```

**Comment by karlp** [comment]
what versions of libwebsockets do you have in each of these installations?

**Comment by Elleven1** [comment]
> 
> 
> what versions of libwebsockets do you have in each of these installations?

Not sure, what you're asking!?!? I've downloaded the Mosquitto 64 bit Win-installer from the Mosquitto website like https://mosquitto.org/files/binary/win64/mosquitto-1.6.12-install-windows-x64.exe. I've no idea, which versions of which libs are in there. I downloaded the older versions just by changing the version tag of the download URL and got it all down to 1.6.8.

**Comment by ralight** [comment]
The version of libwebsockets did change in the Windows installers, I've reverted to 2.4.2 and have uploaded a new installer 1.6.12a which uses that version again.

https://mosquitto.org/files/binary/win64/mosquitto-1.6.12a-install-windows-x64.exe

**Comment by Elleven1** [comment]
> 
> 
> The version of libwebsockets did change in the Windows installers, I've reverted to 2.4.2 and have uploaded a new installer 1.6.12a which uses that version again.
> 
> https://mosquitto.org/files/binary/win64/mosquitto-1.6.12a-install-windows-x64.exe

Hi Roger,

I just installed the 1.6.12a and in deed it's working fine now. Thanks a lot for the quick fix :-)

BR,
Armin
