### ISSUE TITLE
How long is stored message removed from persistence buffer?

### ISSUE THREAD

**Issue by itadakimatsu97** [eclipse/mosquitto#1841]
Hi all,

I am studying mosquitto persistence mechanism.
I want to ask 2 question:
- How long is stored message removed from persistence buffer?
- How can i set this value in broker side(mosquitto.conf) and in client side?

Thank all!

**Comment by ralight** [comment]
There are a few things to consider here.

If we only consider MQTT v3.1.1 and MQTT v3.1 clients, then everything is handled on the broker side. Retained messages will be held forever, or until they are cleared. Messages stored in a queue for a client that is not currently connected will also be stored forever, unless the `persistent_client_expiration` option is configured - if it is, then clients will be expired according to that option and any queued messages for them will be removed at the same time.

If we consider MQTT v5 clients as well, then messages can be configured to have an expiry interval, which means they are removed after a certain amount of time if they are retained messages or are queued for delivery to clients. In addition, clients can set their own session expiry interval which is the maximum amount of time they are allowed to be disconnected from the broker before the broker will expire them and any queued messages for them.

I hope that helps.

**Comment by itadakimatsu97** [comment]
@ralight 
Thank you.

**Comment by itadakimatsu97** [comment]
@ralight 
Could you kindly explain this keyword in detailed? "autosave_on_changes [ true | false ]"

`autosave_interval seconds
The number of seconds that mosquitto will wait between each time it saves the in-memory database to disk. If set to 0, the in-memory database will only be saved when mosquitto exits or when receiving the SIGUSR1 signal. Note that this setting only has an effect if persistence is enabled. Defaults to 1800 seconds (30 minutes).

This option applies globally.

Reloaded on reload signal.

autosave_on_changes [ true | false ]
If true, mosquitto will count the number of subscription changes, retained messages received and queued messages and if the total exceeds autosave_interval then the in-memory database will be saved to disk. If false, mosquitto will save the in-memory database to disk by treating autosave_interval as a time in seconds.

This option applies globally.

Reloaded on reload signal.`

Thank you very much!

**Comment by ralight** [comment]
`autosave_on_changes` changes persistence so instead of being written out on a fixed time interval, it is written out based on the number of relevant changes that occur in the broker. So you could specify a value of 1000, for example, and then when 1000 message were received that would be persisted the broker will write out the persistence file.

**Comment by itadakimatsu97** [comment]
@ralight 
I understood your explanation as:
Assume that "autosave_interval 999", "autosave_on_changes true"
If within 1000 seconds, total of "the number of subscription changes, retained messages received and queued messages"  exceeds 999, buffer will be written out the persistence file.
Or if reach 1000 seconds,  buffer will be written out the persistence file aslo.

Am i correct?

**Comment by ralight** [comment]
Not quite - if you set `autosave_on_changes true`, then there is no time element at all. The persistence data is only written out when sufficient changes occur.

**Comment by itadakimatsu97** [comment]
I understood.
Thank you.
