### ISSUE TITLE
Documentation: mosquitto_client_certificate(), X509_free()

### ISSUE THREAD

**Issue by D-r-P-3-p-p-3-r** [eclipse/mosquitto#1842]
The documentation of the function mosquitto_client_certificate() should mention that X509_free() has to be called on the pointer returned by that function.
This currently only becomes apparent if you check out the implementation of mosquitto_client_certificate().

**Comment by ralight** [comment]
Thanks Wolfgang, you're quite right. I've just pushed a fix.
