### ISSUE TITLE
message not sent on exceeded timeout

### ISSUE THREAD

**Issue by xiangtianyu** [eclipse/mosquitto#1843]
I have a similar issue to #1367  with 1.6.9

I try to simulate the timeout situation,so i turnoff the network of my device and wait utill the server shows the log
`1602571228: Client 356776520003075 has exceeded timeout, disconnecting.`

But when i reconnect, the message didn't send to my device.

**Comment by ralight** [comment]
This is an asciicast of me doing what I think you mean, starting with compiling mosquitto 1.6.9 and then connecting clients to it and simulating a network disconnection - and everything works as I would expect. If this doesn't match what you are doing, please let me know so I can understand exactly what you are doing.

https://asciinema.org/a/nrv4Brn8ljSdr0KqlmpwSLeNT

**Comment by xiangtianyu** [comment]
I tried to do like this video,its all right! thank you~ I will try to do something to check my client implement

**Comment by ralight** [comment]
Ok, good luck!
