### ISSUE TITLE
libmosquitto: client - retrieve generated random id

### ISSUE THREAD

**Issue by Hallot** [eclipse/mosquitto#1844]
Hello,

I am using libmosquitto as a client, and let the lib generate a random id by using:  
`struct mosquitto* mosq = mosquitto_new(NULL, true, NULL);`

I would like to get the id generated after that though, and couldn't find a way.  
The value itself is behind an opaque struct, and there doesn't seem to be a function to get this value.

Am I missing something? Is what I am trying to do an anti-pattern in MQTT?

Thank you.

**Comment by ralight** [comment]
There isn't currently a way to retrieve the id, unless you are using MQTT v5. In that case, the broker may send you the client id that it assigned in the CONNACK properties, which you can inspect in the on_connect callback.

**Comment by Hallot** [comment]
So it's the broker that generates the ID, not the client then. Makes sense to truly guarantee unicity.  
Thanks for the quick answer.
