### ISSUE TITLE
pid_file option not honored in config when not daemon

### ISSUE THREAD

**Issue by habazut** [eclipse/mosquitto#1845]
The pid_file option is not honored in the config file unless mosquitto is running as daemon.

As this seems not to be documented I think this is a bug. Otherwise it should be mentioned here:

```
# Write process id to a file. Default is a blank string which means
# a pid file shouldn't be written.
# This should be set to /var/run/mosquitto.pid if mosquitto is
# being run automatically on boot with an init script and
# start-stop-daemon or similar.
#pid_file
```

I am not a systemd expert but I think when running under systemd mosquitto does _not_ run as a daemon and one wants to be able to write a pid_file even if systemd not necessarily _needs_ it (depending on systemd config of course).

Patch:

```
$ git diff @{1}
diff --git a/src/mosquitto.c b/src/mosquitto.c
index f3be9d50..e1d0a16d 100644
--- a/src/mosquitto.c
+++ b/src/mosquitto.c
@@ -395,7 +395,7 @@ int pid__write(struct mosquitto_db *db)
 {
        FILE *pid;
 
-       if(db->config->daemon && db->config->pid_file){
+       if(db->config->pid_file){
                pid = mosquitto__fopen(db->config->pid_file, "wt", false);
                if(pid){
                        fprintf(pid, "%d", getpid());
```

Harald.

**Comment by ralight** [comment]
It is actually documented, but not in mosquitto.conf you are correct: https://mosquitto.org/man/mosquitto-conf-5.html

Regardless, I agree that there's no need to have this limitation so I'm removing it.

**Comment by ralight** [comment]
Thanks for the report!
