### ISSUE TITLE
properties not re-sent after reconnect.

### ISSUE THREAD

**Issue by DSOFreak** [eclipse/mosquitto#1846]
Hi. 
I'm using the mosquitto c library.
My problem is, that i find no way to provide new properties for the reconnect or resend the old properties.
By reconnect I mean the reconnect happening here [loop.c#L317](https://github.com/eclipse/mosquitto/blob/0bdf630c2757047dcbf1fd3ad6b7a245addd87fa/lib/loop.c#L317).

Currently I use a workaround for the issue. See this patch: [reconnect-properties.txt](https://github.com/eclipse/mosquitto/files/5376695/reconnect-properties.txt)

**Comment by ralight** [comment]
This should now be fixed, thanks for the report!
