### ISSUE TITLE
improve websocket polling speed by tracking connection fd and add them to the polled set

### ISSUE THREAD

**Issue by minghuadev** [eclipse/mosquitto#185]
Hi, Can I suggest a patch as attached to improve the websocket response time? The test run on my laptop with an intel B847 1.1GHz processor gives less than 10ms round-trip time. While the original mosquitto would take 350ms on average (50 gets to broker, 100 to the other client, 100 back to broker and 100 to the original client). 

I tracked the code for websocket a little bit. This patch is best to my humble understanding. I have not tracked the code for normal mqtt code path, and the bridge. Please comment about anything it may have missed, or how it should be improved, or any other issues with this approach. 

Update: I initially saw some crashes and asked questions here. It turns out the reason is because I did not run `make clean` after modifying `lib/mosquitto_internal.h` so the data structure built into c files were misaligned. The socket errors on unknown clients are most likely the sessions left in the browser that's not really a concern. I removed the questions here about the crash and deleted the 3rd comment below.

**Comment by minghuadev** [comment]
[patch-poll-websockets-june4.txt](https://github.com/eclipse/mosquitto/files/299175/patch-poll-websockets-june4.txt)

**Comment by minghuadev** [comment]
Regarding the crash, it looks more like a build related issue. I kept one copy of a problematic broker binary. It always causes the crash easily. Yesterday I did run into a few builds with the similar crash but then could not recreate the problem after a while. I'm wondering what could be build related: A build timestamp used as a random number generator seed? Or a database that is keyed into something related to the build time? What other stuffs? 

Also when it crashed, there are many "socket error on client <unknown>" followed by one with a valid client id like "socket error onclient web_39" and the crash: 

    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100356: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100361: Socket error on client <unknown>, disconnecting.
    1465100384: Socket error on client <unknown>, disconnecting.
    1465100384: Socket error on client <unknown>, disconnecting.
    1465100384: Socket error on client <unknown>, disconnecting.
    1465100384: Socket error on client <unknown>, disconnecting.
    1465100384: Socket error on client <unknown>, disconnecting.
    1465100384: Socket error on client <unknown>, disconnecting.
    1465100384: Socket error on client web_39, disconnecting.

When it did not crash, the "client <unknown>" and valid clients are interleaved, like the following: 

    1465105402: Socket error on client <unknown>, disconnecting.
    1465105402: Socket error on client <unknown>, disconnecting.
    1465105402: Socket error on client <unknown>, disconnecting.
    1465105402: Socket error on client web_61, disconnecting.
    1465105402: Socket error on client <unknown>, disconnecting.
    1465105406: Socket error on client web_27, disconnecting.
    1465105406: Socket error on client <unknown>, disconnecting.
    1465105406: Socket error on client <unknown>, disconnecting.
    1465105406: Socket error on client <unknown>, disconnecting.
    1465105408: Socket error on client web_58, disconnecting.
    1465105408: Socket error on client <unknown>, disconnecting.
    1465105409: Socket error on client <unknown>, disconnecting.
    1465105458: Socket error on client web_55, disconnecting.
    1465105460: Socket error on client web_81, disconnecting.
    1465105464: Socket error on client web_22, disconnecting.
    1465105467: Socket error on client web_65, disconnecting.
    1465105486: Socket error on client web_13, disconnecting.
    1465105489: Socket error on client web_55, disconnecting.
    1465105492: Socket error on client web_9, disconnecting.

So far there has be no repeatable way to recreate the problem by building from the source. It's been the exactly same source code. Maybe I could try to manually disassemble the binary that is known to have problem.

**Comment by zhoubug** [comment]
I do not see the process of Pollin and rollout of websocket

**Comment by minghuadev** [comment]
it's behind a call to libwebsocket_service() further down in loop.c. this patch shortens the time sitting on poll() when there are data or space in the socket thus removes the latency of 100ms to reach libwebsocket_service(). hope this answers your question, or please elaborate.

**Comment by zhoubug** [comment]
good job!
thank you for response.
which version of mosquitto can use this patch?
1.4.9?

**Comment by zhoubug** [comment]
libwebsocket can work with external poll may be need more work to do.

**Comment by minghuadev** [comment]
the code was developed on master. the uploaded patch was taken off 1.4.9. the patch to develop branch is very similar if you modify all the `libwebsocket_` to `lws_`, and make some logging changes. the develop branch looks to be faster and with fewer socket errors in the log. with 1.4.9 or the master when you leave a browser client open and restart the broker the socket errors may count up to tens or up to 200 each of them will hold an open fd. sometimes the browser session takes a long time to get recovered. 

you are correct about a few possible further improvements. actually the project lead Roger Light is working on a big refactoring though no idea how that has progressed. so I only intended to solve the most urgent need with little effort here. on the develop branch there is no sign of how the refactoring or redesign is going to be done. since he or somebody implemented the websocket protocol in the paho.mqtt.python client codebase, I won't be surprised if the mosquitto will have its own websocket implementation. 

thanks for the encouraging words. glad to know it may be useful to somebody.

**Comment by PierreF** [comment]
@minghuadev I've applied you patch (from https://github.com/eclipse/mosquitto/issues/185#issuecomment-223791463) and tested with my test case from https://github.com/eclipse/paho.mqtt.python/pull/114: I have the same result, time is unchanged.

**Comment by minghuadev** [comment]
@PierreF Thanks for sharing with us the result. That's interesting. I'd expected the 100ms fixed delay would have been eliminated. When I created the patch, it did show to have worked so. Can you confirm that you are seeing 100ms fixed delay? Or it could be the test pattern that my test case did not cover all the possible cases. 

Another issue #170 that was fixed a while ago is reported to appear again too. It looks something has changed recently.

**Comment by minghuadev** [comment]
ok, I red your paho #114 testcase. it's crossing from mqtt port to websocket. I'll give it a try.

**Comment by ralight** [comment]
This is fixed in 1.4.13.
