### ISSUE TITLE
Internal Message Number

### ISSUE THREAD

**Issue by frkngksl** [eclipse/mosquitto#1852]
I am trying to integrate a buffer to mosquitto implementation. In order to do that, I queue the coming messages in db__message_write switch case. However, I can queue at most 18 messages, mosquitto can't accept anymore messages regardless of queue size. How can I change this limit?

**Comment by ralight** [comment]
I'm not quite sure what you're trying to do? What are you trying to add that isn't covered by the inflight message queue, or the queued message queue?
