### ISSUE TITLE
Clean bridge disconnect sending notification

### ISSUE THREAD

**Issue by krisozzy** [eclipse/mosquitto#1853]
I have mosquitto 1.6.12 running as a daemon which has a bridge connection to another mosquitto broker. The bridge connection is working fine and I can see notifications of the bridge connection status being publish to a topic specified in the mosquitto.conf file.

I have a client connected to broker A subscribed to the bridge notification topic. I start up broker B and I can see on my client the bridge notification topic and payload is 1.
If I kill mosquitto broker B by using killall -TERM mosquitto I see a notification topic with the payload set to 0.

I was expecting that by cleanly closing the broker there should be no notification topic published. According to the man page "This uses the Last Will and Testament (LWT) feature." So if the broker cleanly disconnects surely there should be no notification topic published.

I have tried this with cleansessions set to true and false and both behave the same.

Is this the desired behaviour or is something wrong here?

**Comment by ralight** [comment]
I'm not sure I'd agree that a TERM counts as a clean close :) Ignoring that, there aren't any circumstances where a bridge will send a DISCONNECT message, which means it will always be an unclean disconnection. This is intentional, so that the status message will try to always be correct.

**Comment by krisozzy** [comment]
Thank you for the clarification. It might be worth updating the docs at some point.
