### ISSUE TITLE
With device certificates enforce client id must match certificate common name? 

### ISSUE THREAD

**Issue by torntrousers** [eclipse/mosquitto#1856]
Hi, thanks for the great MQTT broker. 

I've a usecase where I'm using client certificates so have  require_certificate=true and I'd like to the clients to use their certificate common name as the client id. Is there anyway to have Mosquitto enforce this? 

If there is not any way presently would it be out of the question to get that feature added to Mosquitto?

Thanks!

**Comment by ralight** [comment]
There isn't a direct way to force the common name to be the client id, but you can force the common name to be the username, and the username to be the client id:
```
use_identity_as_username true
use_username_as_clientid true
```
Does that work for you?

**Comment by torntrousers** [comment]
Thats interesting! Thank you so much, I will give it a try.

**Comment by torntrousers** [comment]
I need to do more work with our particular use case but that approach does appear to do waht I need so I'll close this. Thanks again.
