### ISSUE TITLE
mosquitto broker API

### ISSUE THREAD

**Issue by mickae1** [eclipse/mosquitto#1857]
Hi,

I would like to create a mosquitto broker on my device ( not the client). 

But I would like to use it with C code. Is it possible ?

I would like When a client connect to my broker, the ability to receive the subscribe ( a callback called ? )

Because I've a lot of metrics, and I don't want to publish all the metrics to my broker. I would like to publish the data only when I receive a subscribe.

Is it doable ?

**Comment by mickae1** [comment]
I've read the code.

Ideally the callback would be called at this line :
https://github.com/eclipse/mosquitto/blob/386f3cc188cde0b896175c0c844cfdf8dd7ea220/src/subs.c#L721

But I don't think that the mosquito broker is designed to be compiled as a library.

**Comment by ptjm** [comment]
You might want to look at the API for access control. See src/mosquitto_plugin.h. You could use mosquitto_auth_acl_check() to track when a client subscribes to a specific topic, and notify your publisher to start publishing. Problem is this won't tell you when the client goes away.

**Comment by mickae1** [comment]
Thx,

It's not possible to add a function mosquitto_auth_acl_remove_sub in this
function ?  => sub__remove

**Comment by ralight** [comment]
The new plugin interface on the `develop` branch gives you access to subscribe and unsubscribe events, but not currently disconnect events, so you couldn't cover every case. I think that's a hole that needs filling.

You could also use `log_dest topics` and look for the subscribe events in your client.
