### ISSUE TITLE
Where are the broker topics and data stored?

### ISSUE THREAD

**Issue by ringmybell** [eclipse/mosquitto#1861]
Maybe this is too basic a question, but I have not found an answer.

Where does Mosquito store the broker topics and the data that is being passed to it? Is this stored in the systems RAM or is stored on the SD Card? Does changing any of the QOS, Retained and Last Will and Testament impact on where Mosquito saves the data? If data is being stored to the SD card can you force it to store on RAM?  

I am running Mosquito on Raspberry Pi and concerned about SD card writes if subscribers are frequently publishing new data.

**Comment by ralight** [comment]
Mosquitto stores all data in memory, but can be configured to store to disk as well. This is done with the `persistence` option in the config file. By default persistence is only written infrequently, so even if you have it enabled it should not be a problem for SD card writes.

**Comment by ringmybell** [comment]
Super, thanks for clearing that up for me.
