### ISSUE TITLE
Date Time Format is not working for the topic logs

### ISSUE THREAD

**Issue by Kaushik-27** [eclipse/mosquitto#1862]
Hello,
Please find the below details:

Configuration:
# =================================================================
# Logging
# =================================================================
log_dest topic
log_type all
connection_messages true
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S

Issue:

When "log_dest stdout" then the time format is proper as configured.
But if "log_dest topic" then only timestamp is sent.

Log e.g. : 
"message":"1603208994: Socket error on client b5edcb96-f7b5-40bb-825f-62e33fc749ff1603171454080, disconnecting."

**Comment by ralight** [comment]
You're quite right, thanks for spotting it. I've just pushed a fix for it.
