### ISSUE TITLE
Seg-Fault in Windows on plugin-load-failure

### ISSUE THREAD

**Issue by roebotron** [eclipse/mosquitto#1866]
On Windows, if loading of a plugin fails, mosquitto (version 1.6.12) crashs with **segmentation fault**.

I debugged my MinGW64 build and found:
### security.c, line 31 ff:
```C++
void LIB_ERROR(void)
{
#ifdef WIN32
	char *buf;
	FormatMessage(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_STRING /* <-- cause */,
			NULL, GetLastError(), LANG_NEUTRAL, (LPTSTR)&buf, 0, NULL);
	log__printf(NULL, MOSQ_LOG_ERR, "Load error: %s", buf);
	LocalFree(buf)
```
`FORMAT_MESSAGE_FROM_STRING` causes Windows to interpret the consecutive NULL as valid pointer...
Replaced by `FORMAT_MESSAGE_FROM_SYSTEM`, I've got a fancy message text.

As I can see, this is not a MinGW-triggered issue.

**Comment by ralight** [comment]
Thanks very much, I've pushed changes for the 1.6.x and develop branches.
