### ISSUE TITLE
Log debug entries to topic destination

### ISSUE THREAD

**Issue by AlexShkunov** [eclipse/mosquitto#187]
Please evaluate a possibility for enhancement: 

currently: "debug type (used for decoding incoming/outgoing network packets) is never logged in topics."

Would it be possible to log debug type towards topic. In order to observe / monitor specific client's CONNACK and PINGRESP packets

**Comment by ralight** [comment]
This can be done (the reason it isn't is simply because the naive approach results in an infinite loop of messages reporting about the debug messages about the debug messages about...)

You'll be getting everything though, and that's quite a lot of data.

**Comment by AlexShkunov** [comment]
I see. PUB-packet would cause the loop. Unfortunately $SYS-topics information doesn't tell much about particular client, in terms of Connect / Ping. Where should I look to so I could modify myself to publish new SYS-topic for PINGRESP and CONNACK packets?

**Comment by ralight** [comment]
Actually it should just be a case of keeping track of whether a message
needs to be logged or not - with the log messages not wanting to be logged.

**Comment by ralight** [comment]
I'm closing this as "won't fix". I think the debug type messages should be kept to the local machine.
