### ISSUE TITLE
Header mosquitto_broker.h missing in mosquitto-dev

### ISSUE THREAD

**Issue by roebotron** [eclipse/mosquitto#1870]
To build a auth-plugin with any serious security function, the methods declared in `mosquitto_broker.h` are essential (e.g. retrieving certificate, client name, or even write to log). They're exported by the executable on Linux (btw.: they aren't on Windows...)

However, this header file **is not included** in the developer's package `mosquitto-dev`, so developers have to grab it from the source package, git or elsewhere. That's a pity.
(version 1.6.12)

**Comment by ralight** [comment]
Which package are you using? I just downloaded one of the debs to check, and it's there:

![header](https://user-images.githubusercontent.com/79578/97581981-23976500-19ed-11eb-885a-6ddc9f64b47d.png)

**Comment by roebotron** [comment]
ubuntu 20.04 "focal"
```
frank@hyperv-ubuntu:~/Workspace/mosquitto-auth-plugin$ sudo apt show -a mosquitto-dev
Package: mosquitto-dev
Version: 1.6.12-0mosquitto1~focal1
Priority: optional
Section: devel
Source: mosquitto
Maintainer: Roger A. Light <roger@atchoo.org>
Installed-Size: 72,7 kB
Depends: mosquitto (<< 1.6.12-0mosquitto1~focal1.1~), mosquitto (>= 1.6.12-0mosquitto1~focal1)
Download-Size: 46,1 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/mosquitto-dev/mosquitto-ppa/ubuntu focal/main amd64 Packages
Description: Development files for Mosquitto
 Mosquitto is a message broker that supports the MQTT protocol.
 .
 This package contains the include files used if you wish to compile a package
 which requires Mosquitto's source file headers.
```
```
frank@hyperv-ubuntu:~/Workspace/mosquitto-auth-plugin$ sudo dpkg -L mosquitto-dev
/.
/usr
/usr/include
/usr/include/mosquitto_plugin.h
/usr/share
/usr/share/doc
/usr/share/doc/mosquitto-dev
/usr/share/doc/mosquitto-dev/changelog.Debian.gz
/usr/share/doc/mosquitto-dev/changelog.gz
/usr/share/doc/mosquitto-dev/copyright
```

**Comment by ralight** [comment]
Thank you. An updated version should be available shortly.
