### ISSUE TITLE
Retained not working as expected in the docker image

### ISSUE THREAD

**Issue by jameskleeh** [eclipse/mosquitto#1871]
I have a project where I'm starting the docker image https://hub.docker.com/_/eclipse-mosquitto. I'm creating the file `/mosquitto/data/mosquitto.conf` with the following contents inside the image:

```
persistence true
persistence_location /mosquitto/data/
log_type all
```

I tested publishing a message with an empty payload, qos = 1, and retained = true. I then added a subscription to the same topic the message was published to, however the retained message never arrived. Are my expectations correct?

**Comment by jameskleeh** [comment]
I did some more testing on my end and it seems like retained = true and an empty payload doesn't work. I assume this is by design

I think the following should be updated to indicate as such https://mosquitto.org/man/mosquitto_pub-1.html# under `--retain` and `--will-retain`

**Comment by ralight** [comment]
@jameskleeh you're right, it is by design. The MQTT spec states that sending a retained message with a zero length payload will clear the retained message on a topic if there is one. I've updated the sections like you suggested though, so people don't have to already know that.

**Comment by jameskleeh** [comment]
Thanks @ralight !
