### ISSUE TITLE
mosquitto_sub run the arm platform error:Unable to connect (Unknown error.).

### ISSUE THREAD

**Issue by aphage** [eclipse/mosquitto#1876]
Running mosquitto_sub on the arm platform returns an error: Unable to connect (Unknown error.).

The mosquitto_connect_bind_v5 function returns a value of 13 in client/client_shared.c line 1237

My cross-compilation parameters are:

make CC=arm-linux-gnueabi-gcc CXX=arm-linux-gnueabi-g++ AR=arm-linux-gnueabi-ar LD=arm-linux-gnueabi-ld CFLAGS="-I/home/alice/work/openssl -1.1.1g/arm-out/include/" LDFLAGS="-L/home/alice/work/openssl-1.1.1g/arm-out/lib -lssl -lcrypto"

**Comment by ralight** [comment]
I've used mosquitto_sub on a few arm platforms without any trouble, so I think it's unlikely but not impossible it is anything specific to arm.

Are you using a keepalive value of less than 5? This is forbidden by the mosquitto library, but doesn't get forbidden by mosquitto_sub.

**Comment by aphage** [comment]
I did not modify the code, I checked the linux settings
`cat /proc/sys/net/ipv4/tcp_keepalive_time
7200
cat /proc/sys/net/ipv4/tcp_keepalive_intvl
75
cat /proc/sys/net/ipv4/tcp_keepalive_probes
9`

But the cross-compiled mosquitto can work
