### ISSUE TITLE
mosquitto keeps using expired certificate

### ISSUE THREAD

**Issue by momoskitto** [eclipse/mosquitto#1877]
when configuring the mosquitto broker with TLS, the path to the certificate can be specified in the configuration file with the certfile option. In my case, this certificate is a letsencrypt certificate, which is valid for 3 months and is renewed automatically by certbot.

Currently there appears to be no way of making the broker reload the certificate (SIGHUP does not reload), meaning that the broker has to be restarted when the certificate is renewed, or it will present an expired certificate to clients.

There should be a way of using the renewed certificate for new connections without disconnecting existing clients.

**Comment by ralight** [comment]
This has now been fixed in the `develop` branch. The server certificate and private key are reloaded on a SIGHUP. Thanks for the report.
