### ISSUE TITLE
Stop log from wrapping around when running as a Windows service

### ISSUE THREAD

**Issue by richlgit** [eclipse/mosquitto#1879]
Could someone please help me understand how I might configure mosquitto to allow its log file size to grow larger than 956,443 when running as a Windows service?  It hits  that size limitation and then wraps around internally, destroying older messages.  I'd love a rollover function but in lieu of that I'd be okay with unlimited growth.  (really) 

'Wishing I had the flexibility of unix-style logging.
TIA

=============================================

c:\Program Files\mosquitto>dir mosquitto.log
 Volume in drive C is OS
 Volume Serial Number is 4631-DEAC

 Directory of c:\Program Files\mosquitto

11/06/2020  11:27 AM           956,443 mosquitto.log
               1 File(s)        956,443 bytes
               0 Dir(s)  129,452,261,376 bytes free

**Comment by ralight** [comment]
This is very odd, I can't think of any reason why it would do that. I'll take a look when I'm in Windows.

**Comment by richlgit** [comment]
Uninstalled 1.6.12a due to issue #1880 which still needs looking at sometime.
Reinstalled 1.6.10a
Log acts as expected and does not wrap.
Could be a problem in 1.6.12a but unsure at this time.
Closing issue with a root cause of gamma rays from outer space.

**Comment by ralight** [comment]
I suspect this is entirely related to 1880 actually.

**Comment by richlgit** [comment]
Cannot repo in 1.6.12b.
Thanks ralight.
