### ISSUE TITLE
mosquitto_rr doesn't actually support v3.1.1

### ISSUE THREAD

**Issue by Arnavion** [eclipse/mosquitto#1881]
A command like:

```sh
mosquitto_rr ... --topic ... --message ... -e ... --protocol-version mqttv311
```

will use the value of `-e` (`cfg.response_topic`) both for [subscribing to](https://github.com/eclipse/mosquitto/blob/3a13205e5e7635fab23bc26ca3898fbfdeec4836/client/rr_client.c#L124) (okay) and [as properties of the PUBLISH message](https://github.com/eclipse/mosquitto/blob/3a13205e5e7635fab23bc26ca3898fbfdeec4836/client/rr_client.c#L281) (not okay). This means `mosquitto_publish_v5` [fails with `MOSQ_ERR_NOT_SUPPORTED`.](https://github.com/eclipse/mosquitto/blob/3a13205e5e7635fab23bc26ca3898fbfdeec4836/lib/actions.c#L51)

On a related note, the response topic is [parsed as a publish topic rather than a subscription topic](https://github.com/eclipse/mosquitto/blob/3a13205e5e7635fab23bc26ca3898fbfdeec4836/client/client_shared.c#L439), which is correct for v5. But for v3.1.1 it's more convenient to parse it as a subscription topic to allow wildcards.

---

Incidentally the man page doesn't document the `-e` parameter. It's mentioned in the synopsis section but not in the options section. Even the synopsis section [incorrectly marks it](https://github.com/eclipse/mosquitto/blob/3a13205e5e7635fab23bc26ca3898fbfdeec4836/man/mosquitto_rr.1.xml#L32) as an optional parameter and groups it within the `{}` group that contains the `-h` and `-L` alternatives.

**Comment by ralight** [comment]
Thank you, that's a good description. It's now fixed, although I disagree with you about the response topic. It would be harder to use in v3.1.1 certainly, but changing to allow wildcards in the response topic doesn't feel right.

**Comment by Arnavion** [comment]
Thanks for the fix.
