### ISSUE TITLE
Is there a website with information about the state of the test server?

### ISSUE THREAD

**Issue by VDelport** [eclipse/mosquitto#1901]
First of all, thank you very much for your project and the opportunity to try out your own application with the MQTT broker test.mosquitto.org. The MQTT broker does not seem to be available at the moment (11/16/20, 3:30 PM UTC)? Is there a website where you can see the current status of the server?

**Comment by ralight** [comment]
No, I'm afraid there isn't. I did check it a few hours after your message and it seemed to be fine then.

**Comment by VDelport** [comment]
Thank you.
