### ISSUE TITLE
mosquitto_pub hangs after an initial connection error in --stdin-line mode

### ISSUE THREAD

**Issue by etihwnad** [eclipse/mosquitto#1904]
Steps to reproduce:
* Start broker with allow_anonymous=false and password_file set to a file of valid user:pass
* run `mosquitto_pub --stdin-line` with an invalid username and/or password

It reports the CONNACK message but keeps accepting input from *stdin*.

Since this is an unrecoverable condition, `mosquitto_pub` should exit.

**Comment by ralight** [comment]
Closing as per your pull request, thanks very much.
