### ISSUE TITLE
Building on Apples new Big Sur operating system requires mach_time.h

### ISSUE THREAD

**Issue by taavi013** [eclipse/mosquitto#1905]
Building on Apples new Big Sur operating system requires inclusion mach_time.h due to function prototype
uint64_t mach_absolute_time(void);

[macos11_mach_absolute_time.patch.txt](https://github.com/eclipse/mosquitto/files/5558835/macos11_mach_absolute_time.patch.txt)

**Comment by ralight** [comment]
Thank you, this was already fixed on the `develop` branch, and I've just made the same change on the `1.6.x` branch.

**Comment by ralight** [comment]
This is in 2.0.0 and shortly in 1.6.13.
