### ISSUE TITLE
pattern keyword in ACL file only applies to users mentioned in the file

### ISSUE THREAD

**Issue by RR-28023** [eclipse/mosquitto#1906]
My understanding from the documentation is that if I have the following aclfile:

```
user mqqtspy
topic read #

pattern readwrite %u/#
pattern read mqttspy/broadcast
```
the expected behaviour is that the **_pattern readwrite_** condition applies **to any client** that connects to the broker. However, it does not. For example, if I want to publish with _user1_ on the topic _user1/test_, it does not work. i.e. I can't succesfuly run: 
```  
mosquitto_pub -h localhost -p 1883 -t user1/test -m "Hello world" -u user1 -P user1
```
However, I am able to successfully execute the above command if I change the config file to: 
```
user user1
topic unrelated/#

user mqqtspy
topic read #

pattern readwrite %u/#
pattern read mqttspy/broadcast
```
Which means that the _pattern readwrite_ is now applying to user1. Is this intended? This would mean that I have to explictly mention all the users in the acl file.

Other info: 
- Ubuntu 18.04.05 LTS
- allow_anonymous is set to false

Thanks

**Comment by ralight** [comment]
It definitely should work like that.

I've just tested with a config of:

```
acl_file ./acl
allow_anonymous false
```

And an acl of:

```
user mqqtspy
topic read #

pattern readwrite %u/#
pattern read mqttspy/broadcast
```

Along with:

```
mosquitto_sub -u mqqtspy -t '#' -v
```

And:

```
mosquitto_pub -t user1/test -m hello -u user1 -P user1
```

I've compiled the broker from source with versions 1.4.15, 1.5.9, and 1.6.12 and they all work here.

What version are you using, and are there any other configuration parameters you've set that might be having an effect?

**Comment by RR-28023** [comment]
I am using version 1.4.15.

I just tried to replicate your example (with the only difference that I also had to give a password for mqttspy) with your acl file and I can't publish with _user1._ If I add _user1_ to the acl, then I can publish.

My `mosquito.conf` file looks like this:
```

# Place your local configuration in /etc/mosquitto/conf.d/

# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d

port 1883

allow_anonymous false
password_file /etc/mosquitto/passwords
acl_file /etc/mosquitto/acl

```
Can't thing of anything else I've done. All my users have passwords.

**Comment by ralight** [comment]
I'd suggest updating to be honest. The 1.4 line of releases is pretty ancient now. You could get the latest version on Ubuntu as a snap (`snap install mosquitto`), with documentation here: https://mosquitto.org/documentation/using-the-snap/ , or the project has a ppa here: http://launchpad.net/~mosquitto-dev/+archive/mosquitto-ppa

**Comment by RR-28023** [comment]
Thanks. I upgraded to the latest and I don't experience this issue anymore.

**Comment by ralight** [comment]
That's good to hear!
