### ISSUE TITLE
💣 Access viloation error at pthreads_mutex_* calls

### ISSUE THREAD

**Issue by raspopov** [eclipse/mosquitto#1914]
Commit 2755fe3c4c9930e2e019a4306cef7de7f50c9a83 introduced a critical error which appears in some versions of **pthreads** due calling pthreads_mutex_lock/unlock functions with uninitialized mutex pointer at:

lib/mosquitto.c:
mosquitto__destroy() -> packet__cleanup_all() -> pthreads_mutex_*()

This commit tried to de-duplicate packet cleanup code by replacing it with one function call but packet__cleanup_all function uses mutex synchronization which is not (yet/already) available at that point of execution flow. Probably we need another packet__cleanup_all_unsafe() function without mutexes.

Access violation confirmed at the latest pthreads4w library for Win32.

**Comment by ralight** [comment]
Thank you! I'm very grateful to get reports like this for unreleased code.

**Comment by raspopov** [comment]
Tested, fixed! 🎈
