### ISSUE TITLE
2.0 documentation

### ISSUE THREAD

**Issue by nojacko** [eclipse/mosquitto#1917]
Is there any updated documentation for the upcoming 2.0 release? In particular I'm looking for plugin documentation. Thanks

**Comment by ralight** [comment]
For writing plugins you mean?

**Comment by nojacko** [comment]
Yeah

 I'm looking to upgrade to 2.0 as soon as possible for the performance but need to migrate a plugin. Not sure where to start.

**Comment by ralight** [comment]
Existing plugins are still supported. If you return `4` from `mosquitto_auth_plugin_version`, then the plugin will work in 2.0 and earlier versions.

I'll get the documentation up for the new interface anyway if course.

**Comment by apptionlabs** [comment]
Oh, that's great! Thanks.

**Comment by nojacko** [comment]
That's great! Thanks.
