### ISSUE TITLE
mosquitto will store qos1/2 msgs without limit when the Internet is off?

### ISSUE THREAD

**Issue by ethsonliu** [eclipse/mosquitto#1918]
A mosq client will publish one qos1/2 msg with the frequency once a second. If I turned off the internet of the client, mosq will store the msgs without limit?

I tested it for 45 minutes, the result is YES.

But I'm not sure(myabe 45min is not enough)!

**Comment by ralight** [comment]
Yes, that's correct.

**Comment by ethsonliu** [comment]
Thanks a lot, I get it.
