### ISSUE TITLE
Error: Unable to create websockets listener on port xxx.

### ISSUE THREAD

**Issue by mitul-srashtasoft** [eclipse/mosquitto#1924]
![Capture](https://user-images.githubusercontent.com/73469192/100970879-d7938f00-355b-11eb-8902-2128d1f6e1fa.PNG)

I'm trying to enable a websocket in a mosquitto, by using this document 
[https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-the-mosquitto-mqtt-messaging-broker-on-ubuntu-16-04](url)

After that i'm compiling by command:

mosquitto -c /etc/mosquitto/mosquitto.conf

then got errors: **Error: Unable to create websockets listener on port 8083.**

**Comment by ralight** [comment]
My first guess would be that there is already something using that port. You could check that with `netstat -lnt` and look for a line with 8083 in.

**Comment by christopolise** [comment]
I ran `netstat -lnt` but none of the entries had 8083 and I still have the same issue

**Comment by ralight** [comment]
Another guess - the version of libwebsockets is too old (older than 2.4), or it didn't have WITH_EXTERNAL_POLL enabled when it was compiled.

**Comment by christopolise** [comment]
What fixed my issue is that I had the mosquitto service running already, and trying to run it again was causing issues. I just ran `sudo systemctl stop mosquitto.service` and then ran mosquitto with my config file using `mosquitto -v -c <path-to-conf-file>` and that seemed to do the trick for me

**Comment by david666-cc** [comment]
是的，我也遇到来这个问题,部署方式为docker，镜像版本为`mosquitto:1.6`。而且我在我自己机器运行是好的，在另一台机器运行是有问题的，最后我发现有问题的这台机器不支持ipv6，`ip a`显示如下：
![image](https://user-images.githubusercontent.com/62531071/119949818-d738f580-bfcc-11eb-9baf-455e075f0c95.png)
**因此解决办法是在`mosquitto.conf`配置文件里面加一行`socket_domain ipv4`**

这真是太奇怪了:joy:

**Comment by ralight** [comment]
It seems as though this error comes about if libwebsockets is compiled without the LWS_WITH_EXTERNAL_POLL flag, and if only a single websockets only listener is defined.

**Comment by ralight** [comment]
I'm closing this because I think it is the LWS compilation problem, if that doesn't work for you then please reopen.
