### ISSUE TITLE
mosquitto show incorrect version 

### ISSUE THREAD

**Issue by iranweld** [eclipse/mosquitto#1928]
Hi
I install mosquitto ver 2 Butt mosquitto show me ver 1.6.7

![Untitled](https://user-images.githubusercontent.com/4194016/101075726-a6e14300-35b7-11eb-88c5-30fe0d86d8b1.png)

**Comment by ralight** [comment]
Could you check that you don't have 1.6.7 installed as well? If you compiled manually then it would probably install to a different place.

**Comment by ralight** [comment]
Could you check that you don't have 1.6.7 installed as well? If you compiled manually then it would probably install to a different place.

**Comment by ralight** [comment]
Could you check that you don't have 1.6.7 installed as well? If you compiled manually then it would probably install to a different place.

**Comment by iranweld** [comment]
Hello Mr Ralight

thanks for your answer 

I download and installed the binary version mosquitto for windows 64 from the mosquitto site

**Comment by iranweld** [comment]
I removed last ver and instal new version , now its show correct version number

Best Regards
