### ISSUE TITLE
Create Mosquitto service manually on Windows

### ISSUE THREAD

**Issue by neilg1** [eclipse/mosquitto#193]
How do I create Mosquitto service from an Windows installer I am authoring ?
I was able to create the service using "sc" command on Windows command line:
sc create "Mosquitto Broker" binPath= "C:\Program Files (x86)\mosquitto\mosquitto.exe" start= auto

The service was created, but fails to start. The Windows event log (under error) lists the reason: 
The Mosquitto Broker service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion

Followed by another another error event:
A timeout was reached (30000 milliseconds) while waiting for the Mosquitto Broker service to connect.

I am able to run the mosquitto on the Windows command line without any issues. Please let me know how to create and start the Mosquitto service.

**Comment by ralight** [comment]
You can install the service with `mosquitto.exe install` or remove it with `mosquitto.exe uninstall`.

The service expects the `MOSQUITTO_DIR` environment variable to be set to the directory where the mosquitto.conf file is located. Perhaps that is why it is failing for you.

**Comment by neilg1** [comment]
Thanks. I am able to create the service. If i install the Mosquitto files thru the Windows installer package, the service runs fine.
When I copy all the files (packaged in the installer and required dependency dlls) in a local folder and then create the service, and start the service. the service fails to start. Its hung in "starting" state.

Please list all the steps the installer is doing so I can incorporate the same in my installer.

**Comment by ralight** [comment]
You can see the installer script at https://github.com/eclipse/mosquitto/blob/master/installer/mosquitto.nsi

The relevant parts are:

   WriteRegExpandStr ${env_hklm} MOSQUITTO_DIR $INSTDIR

This sets the MOSQUITTO_DIR environment variable to the installation directory - both mosquitto.exe and mosquitto.conf must be in this directory.

    SendMessage ${HWND_BROADCAST} ${WM_WININICHANGE} 0 "STR:Environment" /TIMEOUT=5000

This ensures the environment sees the new variable.

    ExecWait '"$INSTDIR\mosquitto.exe" install'

This runs `mosquitto.exe install` to install the service.

**Comment by ralight** [comment]
I believe that this can be closed now, if you disagree please reopen and add more information.

**Comment by neilg1** [comment]
Thanks. It should be closed.

________________________________

**Comment by nygma2004** [comment]
I am not sure if somebody is still monitoring this. I just installed mosquitto on a Win10 machine. I downloaded the install package a few hours ago. The broken runs fine when I run it from the command prompt. The service entry is not created not even after I run "mosquitto install". It just returns to the command prompt after a few seconds without any message. I checked and the MOSQUITTO_DIR environment is correctly set.
Any ideas?

**Comment by nygma2004** [comment]
> @nygma2004 A bit late, sorry I didn't see this. Are you running `mosquitto install` as an admin user?

Yes, I have tried all possible combination. I am using a workaround at the moment, I still need to test what was mentioned somewhere to replace the log folder names with the 8.3 version, like instead of "Program Files" "PROGRA~1" or similar.
