### ISSUE TITLE
CentOS7 cannot stat ‘mosquitto_ctrl’: No such file or directory

### ISSUE THREAD

**Issue by apple3306** [eclipse/mosquitto#1938]
CentOS7 cannot stat ‘mosquitto_ctrl’: No such file or directory.

**Comment by ralight** [comment]
Did you install manually or from a package? If from a package, there's a reasonable chance they haven't updated to include the new executable.

**Comment by JulianCaruso** [comment]
Same problem here on an ubuntu VPS. This is the last part after running sudo make install WITH_CJSON=no

make[2]: Leaving directory '/home/ubuntu/mqtt/mosquitto/apps/db_dump'
make[2]: Entering directory '/home/ubuntu/mqtt/mosquitto/apps/mosquitto_ctrl'
install -d "/usr/local/bin"
install  mosquitto_ctrl "/usr/local/bin/mosquitto_ctrl"
install: cannot stat 'mosquitto_ctrl': No such file or directory
make[2]: *** [Makefile:89: install] Error 1
make[2]: Leaving directory '/home/ubuntu/mqtt/mosquitto/apps/mosquitto_ctrl'
make[1]: *** [Makefile:25: install] Error 2
make[1]: Leaving directory '/home/ubuntu/mqtt/mosquitto/apps'
make: *** [Makefile:89: install] Error 2
ubuntu@ip-172-31-41-189:~/mqtt/mosquitto$

**Comment by ralight** [comment]
Thanks @JulianCaruso. It's very frustrating that I didn't spot this update until after I'd just released 2.0.2. There is a fix in the `fixes` branch though, could you try that?
