### ISSUE TITLE
SIGHUP disconnects bridge connection

### ISSUE THREAD

**Issue by charlemagnelasse** [eclipse/mosquitto#1942]
It was noticed that bridge connections will always be dropped when running "killall -SIGHUP mosquitto". Studying my config, it seems like this only happens when I am *NOT* setting allow_anonymous to true. (default it is false)

Problem is following block https://github.com/eclipse/mosquitto/blob/cc47eaba09d024fc76915f3fd42c364b7cf5b309/src/security_default.c#L1127

    		if(!allow_anonymous && !context->username){
    			mosquitto__set_state(context, mosq_cs_disconnecting);
    			do_disconnect(db, context, MOSQ_ERR_AUTH);
    			continue;
    		}

Of course, a bridge doesn't have a username and as I said, allow_anonymous is false. So mosquitto_security_apply_default will just kick my bridge all the time

If I am just setting a remote_username (to some random value) then following section of code will kick my bridge connection https://github.com/eclipse/mosquitto/blob/cc47eaba09d024fc76915f3fd42c364b7cf5b309/src/security_default.c#L1239

			/* Username/password check only if the identity/subject check not used */
    			if(mosquitto_unpwd_check(db, context, context->username, context->password) != MOSQ_ERR_SUCCESS){
    				mosquitto__set_state(context, mosq_cs_disconnecting);
    				do_disconnect(db, context, MOSQ_ERR_AUTH);
    				continue;
    			}

I think both miss a `!context->is_bridge &&` at the beginning

**Comment by ralight** [comment]
Thanks for the report, I agree with your general suggestion and it should now be fixed and will be part of 2.0.3 shortly.
