### ISSUE TITLE
Debian package is completely out of date

### ISSUE THREAD

**Issue by ghost** [eclipse/mosquitto#1943]
I've noticed that Debian (maintained by @ralight) is still on 1.6.12 while the upstream (also maintained by @ralight) is at 2.0.2

**Comment by ralight** [comment]
Yes, I've been cautious about doing the package upgrades to give problems time to shake out a little (hence the 2.0.2). There are also quite a few packaging differences to take into account, which slows it down. I'm going to be making the new packages for Debain and Ubuntu soon, sorry for the delay.

**Comment by ralight** [comment]
The repo was updated ages ago, so I'm closing this.
