### ISSUE TITLE
Will message not published when disconnecting an already connected client

### ISSUE THREAD

**Issue by rpiper** [eclipse/mosquitto#1946]
I'm testing MQTT Sparkplug B protocol using mosquitto broker, and I noticed that the Will message for clients is not being published by the broker when it disconnects an already connected client on reconnect. Sparkplug relies on Will message to indicate the end of a data session.

If a client connects with a Will message, then a second client connects with the same client Id as the first client, mosquitto is correctly closing the first connection, but it is not publishing the Will message of the first client.

The device I'm testing with is battery powered, and I can reproduce the bug by cycling power to the client while it is connected to the broker. When the client reconnects, mosquitto closes the old connection but does not publish the Will for the first connection.

I managed to fix the issue in my working copy with this one-line change to handle_connect.c:167

```
if(context->clean_start == true){
    sub__clean_session(found_context);
    context__send_will(found_context);
}
```

**Comment by ralight** [comment]
Thanks @rpiper.

I'm not sure whether your suggestions is quite right for all cases. If a client has set a will delay interval, for instance, I do not believe the Will should be sent unconditionally. Leave it with me, I'll get it fixed for 2.0.3.

**Comment by ralight** [comment]
I believe this is now fixed in the `fixes` branch. If you're able to confirm that it works for you that would be nice.

**Comment by rpiper** [comment]
@ralight This fixes the issue. I have confirmed that the Will from previous connections is being published when the client reconnects with `clean_start == true` Thanks mate!
