### ISSUE TITLE
mosquitto_dynamic_security plugin configuration not applied after restart

### ISSUE THREAD

**Issue by martgeier** [eclipse/mosquitto#1962]
When creating a dynamic_security.json using mosquitto_ctrl everything works fine. Add a new user and the user can login right away. dynamic_security.json is correctly created and contains the newly created user.  
After a restart however everyting seems to be lost. The new user can no longer login and using mosquitto_ctrl the admin user is not recognized any longer. 

The log file says the mosquitto_dynamic_security.dll has bee successfully loaded.

In my mosquitto.conf file:
plugin C:\Program Files\mosquitto\mosquitto_dynamic_security.dll
plugin_opt_config_file C:\Program Files\mosquitto\dynamic-security.json

**Comment by ralight** [comment]
Does the config file get updated with your new user? I presume you mean you're adding a new user to the broker when it's running?

**Comment by martgeier** [comment]
Yes, I mean adding a new user to the broker while running. The json file gets updated correctly and the user can also login. When the broker is restarted the new user is no longer able to login. The json file still contains the new user settings however. Also, the admin user, created when creating the json file for the first time, is no longer able to add user or any other operation.

**Comment by martgeier** [comment]
Could this be a problem with file security on Windows? I mean, the broker is unable to read the json file but does not report any errors in the log?

**Comment by ralight** [comment]
It could be, but if that were the case I would expect that it couldn't write the file out in the first session.
