### ISSUE TITLE
2.0.0 编译的过了，安装的时候出现这个文件没找到。问题可能出现在哪里呢。

### ISSUE THREAD

**Issue by phplpf** [eclipse/mosquitto#1969]
-- Installing: /usr/local/lib/mosquitto_message_timestamp.so
-- Installing: /usr/local/lib/mosquitto_payload_modification.so
CMake Error at man/cmake_install.cmake:36 (file):
  file INSTALL cannot find
  "/home/firefly/mosquitto-2.0.0/man/mosquitto_ctrl.1".
Call Stack (most recent call first):
  cmake_install.cmake:59 (include)
  

Makefile:61: recipe for target 'install' failed

**Comment by ralight** [comment]
The man pages aren't stored as compiled files in the repository, only the released tar files. The cmake scripts don't compile the man pages either, but I've fixed that now. Thanks very much.
