### ISSUE TITLE
Compiling cpp wrapper doesn't get the config flags

### ISSUE THREAD

**Issue by jbwdevries** [eclipse/mosquitto#197]
In config.mk, all the customizable options like `WITH_SOCKS` get added to `LIB_CFLAGS`, but `LIB_CFLAGS` doesn't get passed on to the build instruction for mosquittopp.o (`LIB_CXXFLAGS` gets passed instead).

It seems to work with cmake, just not without.

I fixed it for myself by adding `LIB_CFLAGS` to the build instruction, but I'm not sure this is the right way. I tested with 1.4.9 tag, and I don't think there's been any chances to relevant files since.

**Comment by ralight** [comment]
I believe this is working as expected. The wrapper doesn't actually need any of the definitions in LIB_CFLAGS, there is no conditional compilation.

**Comment by jbwdevries** [comment]
Right, but there is a check on WITH_SOCKS.

I made a pull request here: https://github.com/eclipse/mosquitto/pull/198

**Comment by ralight** [comment]
Ah yes, you're quite right. Could you please sign the Eclipse CLA and I'll accept the pull request.

**Comment by jbwdevries** [comment]
I think I signed it now, though not sure how to update the merge request.

**Comment by ralight** [comment]
Thanks, I've checked and all is fine - and nudging the PR updated the checks anyway. All merged now :)
