### ISSUE TITLE
No 2.03 on repo? (stuck @1.64)

### ISSUE THREAD

**Issue by ilgrank** [eclipse/mosquitto#1971]
Hello,maybe I'm missing something.. but the semi-official repo @http://repo.mosquitto.org/debian/ seems not to be updated since August, and it is totally missing any 2.0.x release.
Is this intentional?
Is there another repo for the 2.0.x releases?
Thanks

**Comment by ralight** [comment]
It is intentional, to stage the release a bit to give chance for any bugs to shake out before everybody gets it. I plan to have the Debian repository up to date before the 25th.

**Comment by ralight** [comment]
That plan went awry, there were more issues to deal with. I'm working on them though and it should be available soon.

**Comment by ilgrank** [comment]
..could you please update the repo? 
I understand you're flooded with real issues, but still...

Thanks!

**Comment by ralight** [comment]
@ilgrank it was updated with 2.0.8 on release day. Does it not work for you?
