### ISSUE TITLE
Why keepalive down-limit to 5?

### ISSUE THREAD

**Issue by ethsonliu** [eclipse/mosquitto#1973]
From here: https://github.com/eclipse/mosquitto/commit/8e7e4a9d9a682c710268e050d3c3db1e9e372501

The commit msg is "give a warning", but `return MOSQ_ERR_INVAL` will shutdown the connection, and the document <https://mosquitto.org/api/files/mosquitto-h.html#mosquitto_connect> didn't show any tips.

**Comment by ralight** [comment]
You're right this should be documented.

The reason for the limit is that keepalive is measured with a 1 second granularity, and at low values there isn't much scope for error. I've had a number of people in the past have problems with using low keepalive values and having frequent disconnects 

You could argue that having sub-second resolution is the solution, but personally I don't think it should be necessary.

The minimum value could be dropped, probably as far as 3, maybe even 2, I can't remember the level where the problems arose.

**Comment by ethsonliu** [comment]
I get it, 3ks a lot.
