### ISSUE TITLE
Mosquitto 2.0.4 WebSockets connect failed, but 1.6.2 is works.

### ISSUE THREAD

**Issue by 028820** [eclipse/mosquitto#1974]
I working on 1.6.2,   when I upgrade to 2.0.4,  I got a problem, WebSockets connect failed.
I'm missing some configuration at 2.0.4 ?

exmaple configuration on the below

# mosquitto.conf
```
listener 1883
protocol mqtt
listener 9001
protocol websockets
log_type all

```

# Mosquitto 1.6.2 WebSockets is works

```
# run mosquitto 1.6.2 image
docker run -d -it --name mosquitto -p 1883:1883 -p 9001:9001 eclipse-mosquitto:1.6.2

```
```
docker logs mosquitto -f

1608707499: mosquitto version 1.6.2 starting
1608707499: Config loaded from /mosquitto/config/mosquitto.conf.
1608707499: Opening ipv4 listen socket on port 1883.
1608707499: Opening ipv6 listen socket on port 1883.
1608707499: Opening websockets listen socket on port 9001.


1608707587: New client connected from ::ffff:172.17.0.1 as test (p2, c1, k60).
1608707587: No will message specified.
1608707587: Sending CONNACK to test (0, 0)
1608707600: Received PUBLISH from test (d0, q0, r0, m0, 'test', ... (20 bytes))
1608707660: Received PINGREQ from test
1608707660: Sending PINGRESP to test
1608707720: Received PINGREQ from test
1608707720: Sending PINGRESP to test

```

# Mosquitto 2.0.4 WebSockets connect failed
```
# run mosquitto 2.0.4
docker run -d -it --name mosquitto -p 1883:1883 -p 9001:9001 eclipse-mosquitto:2.0.4

```
```

docker logs 469d75750156 -f
1608707835: mosquitto version 2.0.4 starting
1608707835: Config loaded from /mosquitto/config/mosquitto.conf.
1608707835: Opening ipv4 listen socket on port 1883.
1608707835: Opening ipv6 listen socket on port 1883.
1608707835: Opening websockets listen socket on port 9001.
1608707835: mosquitto version 2.0.4 running

1608707913: Client <unknown> closed its connection.

```

# MQTT GUI Client
[mqttx.app](https://mqttx.app/)

**Comment by ralight** [comment]
You should note that version 2.0 onwards will default to `allow_anonymous false`, so your client is not authorised to connect. Please see https://mosquitto.org/documentation/migrating-to-2-0/ for details of differences in behaviour between 1.x and 2.0.

**Comment by 028820** [comment]
> You should note that version 2.0 onwards will default to `allow_anonymous false`, so your client is not authorised to connect. Please see https://mosquitto.org/documentation/migrating-to-2-0/ for details of differences in behaviour between 1.x and 2.0.

Ehh,  The mosquitto.conf just for simplify,  It's my mistake。

Actually I had both tried allow_anonymous equals true or false.
it's seems like a bug or docker image problem, may be image build problem.


In the below, I post  complete mosquitto.conf configuration and docker command.

##  mosquitto.conf
```

allow_anonymous false

acl_file /mosquitto/config/acl.conf
password_file /mosquitto/config/passwd.conf

max_keepalive 90



# If a client sends a packet which is larger than this value, it will be disconnected
max_packet_size 5120
# Dropped too large PUBLISH 
message_size_limit 5120

max_queued_bytes 50
# max queue size
max_queued_messages 1000
allow_zero_length_clientid false
connection_messages true

log_type error
log_type warning
log_type notice
log_type subscribe
log_type unsubscribe


# websocket
listener 9001
protocol websockets
websockets_log_level all


# websocket ssl
listener 9003
protocol websockets
cafile /mosquitto/config/ssl/chain.pem
keyfile /mosquitto/config/ssl/dev.fiture.com.key
certfile /mosquitto/config/ssl/dev.fiture.com.pem

# mqtt
listener 1883
# mqtt ssl
listener 8883
protocol mqtt
cafile /mosquitto/config/ssl/chain.pem
keyfile /mosquitto/config/ssl/dev.xxxx.com.key
certfile /mosquitto/config/ssl/dev.xxxx.com.pem

```

## Docker Command
```

# mosquitto 1.6.12, websocket is works
docker run -d -it --name mosquitto -p 1883:1883 -p 8883:8883 -p 9003:9003 -p 9001:9001 -v /Users/david/data/mosquitto:/mosquitto eclipse-mosquitto:1.6.12-openssl


# mosquitto 2.0.4,  websocket is connect failed
docker run -d -it --name mosquitto2 -p 1883:1883 -p 8883:8883 -p 9003:9003 -p 9001:9001 -v /Users/david/data/mosquitto:/mosquitto eclipse-mosquitto:2.0.4-openssl

```

The mosquitto 2.0.4  docker logs.

![image](https://user-images.githubusercontent.com/1540528/103202258-dec87580-492c-11eb-8b20-4448698e8e43.png)

Do I need to provide more information?

**Comment by ralight** [comment]
I confess I only had a quick glance and didn't actually check it, what with it being holiday here. I'll have a proper look.

**Comment by 028820** [comment]
> I confess I only had a quick glance and didn't actually check it, what with it being holiday here. I'll have a proper look.

hha, in fact the version 1.6.12 works well for me, that performance is awesome, especial `shared subscriptions` feature of mqtt 5.

It's help me to easy build high available, scale-out IoT system. based-on mqtt brokers routing table and message routing (a little work), that's bottleneck is just only bandwidth.

I try upgrade to 2.0, just only try it's, not must.

Thank you for your to mqtt contributions, happy holiday to you :P

**Comment by ralight** [comment]
I've found the problem now, it's a typo in calculating the end of the `remaining length` part of the packet, for websocket clients only. The fun part is that most clients won't see that problem.

mqttx does see the problem because it is pretty badly behaved in how it sends packets - it sends a new websockets packet (and a new TCP packet) for each part of each MQTT packet. For example, a CONNECT packet with authentication has: command, remaining length, length of protocol string, protocol string, protocol level, connect flags, keepalive, length of client id, client id, length of username, username, length of password, password. Each one of those ends up being a new TCP packet. If you use the default mqttx client id and `username` and `password` as your credentials, this gives you a total on the wire cost of 1010 bytes to transmit a 48 byte MQTT command, when it could be as little as 122 bytes for the on the wire cost. Ouch!

Still, I'm grateful for this behaviour because this might not have got found for a while otherwise.

I'll get the fix into 2.0.5, most likely in early January.

**Comment by ralight** [comment]
I'm afraid this got missed for 2.0.5, I thought I'd already fixed it. I've done it now for 2.0.6.

**Comment by yschroeder** [comment]
Hi @ralight, long time no see :-)

I just happened to update my mosquitto to a recent version (after that libwebsockets regression was finally sorted out with a new release on their side). I can confirm that 2.0.5 does not work when sending large messages via websockets (small messages are fine). 

Current master (f1180dd23a32f4c6b7651abbb2646823f73ee5e4) works for all message sizes (tried a few megabytes in size).

By the way: the problem also exist(ed) with `ngx-mqtt` (https://www.npmjs.com/package/ngx-mqtt) not only `mqttx`.

**Comment by ralight** [comment]
@yschroeder thanks for the feedback, it's good to hear 2.0.6 fixes that for you.

**Comment by therealSMAT** [comment]
I have the same issue as @028820 in `2.0.10` Pub/Sub works perfectly via MQTT but does not work with WebSockets even with the same credentials.
