### ISSUE TITLE
How to get auth_method in v5 plugin?

### ISSUE THREAD

**Issue by cjmdaixi** [eclipse/mosquitto#1975]
Hi,

I found that v4 plugin has a method called `mosquitto_auth_start` which has one argument to get the auth_method from Mosquitto context. However, it seems that there is no alternative argument or interface for v5 plugin to get auth_method?

**Comment by ralight** [comment]
The way you should be able to do this in theory is as follows:

```
int auth_callback(int event, void *event_data, void *userdata)
{
    struct mosquitto_evt_extended_auth *ed = event_data;

    printf("%s\n", ed->auth_method);
    return 0;
}
```

Or to use `mosquitto_client_auth_method(client)`, but unfortunately both of those methods have been missed and so don't exist.

I will add `auth_method` to the struct for 2.0.5, but that won't be until January now.

**Comment by cjmdaixi** [comment]
Well, so I have to code an independent v4 plugin to get the auth_method right now.
