### ISSUE TITLE
Not all published data written using unix sockets on slow clients

### ISSUE THREAD

**Issue by marchaesen** [eclipse/mosquitto#1977]
I am using mosquitto compiled for the IMx8m arm processor from NXP.
Version used is the current fixes branch (9d3732a62d6d2aa19293377cb6a3e75fecb45e20).
Mosquitto is listening on a unix socket.
The client is a client which reads data from mosquitto at a slow rate.
When publishing a topic with a large payload (300k), not all data is received on the client.
The reason for this is that the packet__write returns because it gets an errno EAGAIN from the net__write function and after this the packet_write function is not called again.

I can fix the problem by applying attached patch file.
[patch.txt](https://github.com/eclipse/mosquitto/files/5736773/patch.txt)

Is this patch the correct way of solving the issue or should it be fixed in another way?

**Comment by ralight** [comment]
I've pushed a fix there, but it is for the broker rather than the client, I'll take a look at the client as well. Thanks for reporting!
