### ISSUE TITLE
Mosquitto 2.0.4 on Ubuntu 20.04 use 100% cpu time when connected to Losant ( bridge

### ISSUE THREAD

**Issue by GorazdKikelj** [eclipse/mosquitto#1979]
mosquitto uses 100% cpu after upgrade from 2.0.2 to 2.0.4 when it is connected to Losant brigge broker.losant.com:8883

OS is Ubuntu 20.04.1 LTS

**Comment by ralight** [comment]
This should be fixed now, thanks for reporting it. It will be part of 2.0.5.

**Comment by GorazdKikelj** [comment]
Hi Roger.

 

Great news. Many thx.

 

Best, Gorazd
