### ISSUE TITLE
Mosquitto does not allow connection via External IP Windows 10

### ISSUE THREAD

**Issue by Pelagoutb** [eclipse/mosquitto#1985]
Running Mosquitto on the same PC as Python pub and sub or even mosquitto_sub.exe or mosquitto_pub.exe in command Prompt on Windows 10 does not work with any other IP than 127.0.0.1 or localhost as broker. No contact from outside even with Firewall open on port 1883 not even from the computer calling ist own external IP
Error Message:
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

netstat -a only show the 1883 port on the 127.0.0.1 IP and not on external IP
127.0.0.1:1883         ComputerA        LISTENING

Have tried to connect on same wifi from Other Computer, ESP6288, and Android MQTT app. No connection or Connection Failure.

Installed Versions:
OS: Windows 10 Enterprise, Version 20H2, OS Build 19042.630, Windows Feature Experience Pack 120.2212.31.0
Mosquitto; mosquitto-2.0.4-install-windows-x64.exe
Python 3.9.1 and ESP6288 and Android app.

Could someone explain this error and point me in a direction to solve it.

**Comment by ptjm** [comment]
I assume you're running either without a config file or with a config file that doesn't define a listener. As of mosquitto 2.0, this gives the behaviour you're describing. To listen on addresses other than localhost, you need to have a config file with a "listener" line plus some authentication option. At its most wide-open, you could have

listener 1883
allow_anonymous true

It is, of course, better to restrict the listener to the IP addresses that you need and it's often better to use some kind of authentication mechanism rather than leaving your server wide open.

If you're upgrading from version 1.6 or earlier, you should look at ChangeLog.txt from the installation directory as it has some discussion of breaking changes. You may also want to look at https://mosquitto.org/man/mosquitto-conf-5.html

**Comment by Pelago** [comment]
Spot on! 
Thank you for your support!

**Comment by Pelagoutb** [comment]
It worked perfectly!
Thank you for your support!

**Comment by samshum2** [comment]
windows OS is so Difficult

**Comment by aj-way** [comment]
> At its most wide-open, you could have
> 
> listener 1883
> allow_anonymous true

I've just done an update to my home automation Raspberry Pi and Mosquito stopped working. After a couple of hours of panicking I found this post, edited /etc/mosquitto/mosquitto.conf and fixed it. Thank you very much!

**Comment by sam2khatri** [comment]
> I assume you're running either without a config file or with a config file that doesn't define a listener. As of mosquitto 2.0, this gives the behaviour you're describing. To listen on addresses other than localhost, you need to have a config file with a "listener" line plus some authentication option. At its most wide-open, you could have
> 
> listener 1883
> allow_anonymous true
> 
> It is, of course, better to restrict the listener to the IP addresses that you need and it's often better to use some kind of authentication mechanism rather than leaving your server wide open.
> 
> If you're upgrading from version 1.6 or earlier, you should look at ChangeLog.txt from the installation directory as it has some discussion of breaking changes. You may also want to look at https://mosquitto.org/man/mosquitto-conf-5.html

I tried this but it still didn't accept any external connections. But the same build version works perfectly on Raspberry Pi which is Linux based so what's the exact problem here?

**Comment by electronic4706** [comment]
> If you're upgrading from version 1.6 or earlier, you should look at ChangeLog.txt from the installation directory as it has some discussion of breaking changes. You may also want to look at https://mosquitto.org/man/mosquitto-conf-5.html



> I assume you're running either without a config file or with a config file that doesn't define a listener. As of mosquitto 2.0, this gives the behaviour you're describing. To listen on addresses other than localhost, you need to have a config file with a "listener" line plus some authentication option. At its most wide-open, you could have
> 
> listener 1883
> allow_anonymous true
> 
> It is, of course, better to restrict the listener to the IP addresses that you need and it's often better to use some kind of authentication mechanism rather than leaving your server wide open.
> 
> If you're upgrading from version 1.6 or earlier, you should look at ChangeLog.txt from the installation directory as it has some discussion of breaking changes. You may also want to look at https://mosquitto.org/man/mosquitto-conf-5.html

I tried useful solution on above because I have a problem on below . However it isn't useful for me. Is there anyone help me please ?
_mqtt broker error:_ no connection could be made because the target machine actively refused it.   

_What do I try :_ I am trying connection and send/receive messeges from Esp8266 to local computer . They use same wireless network. i can send ping my from local pc to esp8266. Also ı can send/receive messages between esp8266 and my PC  i use test.mosquitto.org server for MQTT broker  .



I can send ping from computer that installed Mosquitto broker to ESP8266 but i can't subscribe to ESP 8266. Also I can't publish from ESP8266 to  computer that installed Mosquitto broker.
I can communication between ESP8266 and my computer as client  by show broker IP  test.mosquitto.org.
I tried all things about firewall both windows and router. however i couldn't connect IoT device and my pc that ı show MQTT broker. I search it on form website. but it is not working.. :(
Can you help me please ? it shown related network permission but i didn't understand. I chacked network by Netstat but it doesn't show any communication situation for my clients

**Comment by sayurisa** [comment]
> > If you're upgrading from version 1.6 or earlier, you should look at ChangeLog.txt from the installation directory as it has some discussion of breaking changes. You may also want to look at https://mosquitto.org/man/mosquitto-conf-5.html
> 
> > I assume you're running either without a config file or with a config file that doesn't define a listener. As of mosquitto 2.0, this gives the behaviour you're describing. To listen on addresses other than localhost, you need to have a config file with a "listener" line plus some authentication option. At its most wide-open, you could have
> > listener 1883
> > allow_anonymous true
> > It is, of course, better to restrict the listener to the IP addresses that you need and it's often better to use some kind of authentication mechanism rather than leaving your server wide open.
> > If you're upgrading from version 1.6 or earlier, you should look at ChangeLog.txt from the installation directory as it has some discussion of breaking changes. You may also want to look at https://mosquitto.org/man/mosquitto-conf-5.html
> 
> I tried useful solution on above because I have a problem on below . However it isn't useful for me. Is there anyone help me please ?
> **_mqtt broker error:_** no connection could be made because the target machine actively refused it.
> 
> **_What do I try :_** I am trying connection and send/receive messeges from Esp8266 to local computer . They use same wireless network. i can send ping my from local pc to esp8266. Also ı can send/receive messages between esp8266 and my PC i use test.mosquitto.org server for MQTT broker .
> 
> I can send ping from computer that installed Mosquitto broker to ESP8266 but i can't subscribe to ESP 8266. Also I can't publish from ESP8266 to computer that installed Mosquitto broker.
> I can communication between ESP8266 and my computer as client by show broker IP test.mosquitto.org.
> I tried all things about firewall both windows and router. however i couldn't connect IoT device and my pc that ı show MQTT broker. I search it on form website. but it is not working.. :(
> Can you help me please ? it shown related network permission but i didn't understand. I chacked network by Netstat but it doesn't show any communication situation for my clients

Create a new file config named test.conf with 2 lines: 
listener 1883
allow_anonymous true

on Window: mosquitto -v -c  test.conf
on Rasp: mosquitto -v -c  path of test.conf

**Comment by MelisaNS** [comment]
> I assume you're running either without a config file or with a config file that doesn't define a listener. As of mosquitto 2.0, this gives the behaviour you're describing. To listen on addresses other than localhost, you need to have a config file with a "listener" line plus some authentication option. At its most wide-open, you could have
> 
> listener 1883 allow_anonymous true
> 
> It is, of course, better to restrict the listener to the IP addresses that you need and it's often better to use some kind of authentication mechanism rather than leaving your server wide open.
> 
> If you're upgrading from version 1.6 or earlier, you should look at ChangeLog.txt from the installation directory as it has some discussion of breaking changes. You may also want to look at https://mosquitto.org/man/mosquitto-conf-5.html

thank you so much, it help me to solve my problem

**Comment by electronic4706** [comment]
thank you very much Mr./Mrs.
I solved the problem.

**Comment by rmdh68** [comment]
this works great, thank you very much.
Is there a possibility to save these entries? Otherwise I would have to call the "test.conf" file in the console every time before I can connect to the broker.

**Comment by rqxrqx** [comment]
How can I restrict the listener to a IP addresses? 
How can I restrict access to a user with password?

**Comment by rhhollin** [comment]
I have the same issue as many who posted here, trying to connect to the mosquitto mqtt broker running on a Windows 10 PC from an ESP32 on the same wireless subnet, which constantly generates an rc = -2 error. I tried the test.conf approach suggested by sayurisa above, but when I run the the mosquitto -v -c test.conf command, I get an error that says "Error: Only one usage of each socket address (protocol/network address/port) is normally permitted." The ESP32 is disconnected and the Arduino IDE program is not running. There is no other program running that is attempting to access the mqtt broker. I do have a node-red program set to use port 1883 as well, but it is not active when this error is received. Any assistance on what to try next is appreciated !!

**Comment by hlzhang** [comment]
Well done! No clue in the [example config](https://hub.docker.com/_/eclipse-mosquitto?tab=description)  on dockerhub.
```
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
```
An excellent way to waste others time.

**Comment by ksechong** [comment]
> listener 1883
> allow_anonymous true
Hi, thanks a lot on this topic and almost solved my windows mosquitto problem.

Almost, means that this will not work if I am running mosquitto on a command prompt.
it works if mosquitto is running as a service.

So uninstall and re-install with the 'service' checked and edit the config file. it works perfect :)
Probably its my windows user's permission is too low.
