### ISSUE TITLE
mosquitto.8

### ISSUE THREAD

**Issue by woodz-** [eclipse/mosquitto#1989]
when compiling from current

    https://github.com/eclipse/mosquitto.git

still get

    install: cannot stat 'mosquitto.8': No such file or directory

although it should be fixed [for 4 years](https://github.com/eclipse/mosquitto/issues/317)

**Comment by ralight** [comment]
I guess you just did `sudo make install` without building first? Yes, that fails and it shouldn't. I've fixed that, it'll be part of 2.0.5.

**Comment by woodz-** [comment]
Right,
I was operating on a docker which startet a build automatically by sensing current sources mounted on a bind. It did only build, if sources were available without a build dir. If a build dir was available, it just did the make install part. So no immediate previous build.
Thx for the fix
