### ISSUE TITLE
Remapping of QoS in an output bridge doesn't work.

### ISSUE THREAD

**Issue by peppo65** [eclipse/mosquitto#199]
Configure a bridge to a local mosquitto broker in order to re-publish messages on another MQTT broker (e.g. iot.eclipse.org). In the mosquitto.conf file specify a QoS 1 (acknowledge delivery) for the remapped topic, as for example:
`topic # out 1 events/ events/mysystem/`
Then, connect to the local broker and publish a message under _events_ topic with QoS 0: the message will be correctly published on the external broker under _events/mysystem_ topic, but using QoS 0 instead of 1.

**Comment by karlp** [comment]
this is per spec and design.  bridges don't promote qos.  see this thread for more information: https://groups.google.com/forum/#!searchin/mqtt/karl/mqtt/tJMUoVE_9rk/xph_x7PT8IYJ

**Comment by peppo65** [comment]
Thanks Karl, I will read carefully the thread.
At this point it's not clear to me what the QoS in the topic entry (in the bridge config section) is intended for...

**Comment by ralight** [comment]
@peppo65 The QoS in the bridge topic entry is the maximum QoS that will be used. If a message is published with QoS 2 and the bridge has QoS 1, then the message will be transferred across the bridge with QoS 1. MQTT enforces the maximum QoS level as specified by the subscribing client.

**Comment by peppo65** [comment]
@karlp @ralight Thanks for the explanation, now I understand. I think I can close the issue.

**Comment by peppo65** [comment]
@ralight Just for adding a further consideration. I have seen that an option exists in the configuration file (_upgrade_outgoing_qos_) which enables the upgrade of QoS for *any* client. I think it might have sense to provide a similar option for enabling the same kind of QoS promotion, only restricted to bridge connections.
I agree that for a "real" subscribing client the resulting QoS is to be negotiated as the minimum between the original QoS (that is the QoS the message was published with) and the QoS as requested by the client. However, for a bridge (at least for the outgoing direction) the client is actually another broker (B) which never performed a subscription by its own. Rather, it is the originating broker (A) that publishes messages of certain topics onto B: which topics A publishes (and possibly their related QoS) are configured on A. Obviously, at the end of the trip, the final "real" clients connected to B are free to indicate their desired QoS level when they subscribe.

**Comment by peppo65** [comment]
@ralight just to hear your opinion. Thanks a lot.

**Comment by ralight** [comment]
Adding this as a bridge specific option sounds like a reasonable idea to me. Could you open this as a separate bug though to keep things tidy?

**Comment by peppo65** [comment]
Thanks, Roger, I'll open a separate issue.


Meanwhile I've done the modification by myself on the 1.4.9 codebase.
Basically, I've added an entry (upgrade_bridge_qos) in the configuration
and modified a few lines in src/subs.c to handle the upgrading of qos
(subjected to that new boolean setting and the context being a bridge). It
seems to work.
Let me know if you are interested in the modification (that is mainly for
my curiosity, since I'd like to know if I've understood well).

Best regards,

Massimo Perrone





2016-07-01 16:49 GMT+02:00 Roger Light <notifications@github.com>:
