### ISSUE TITLE
test/client test.sh fails with "Timed out"

### ISSUE THREAD

**Issue by mattst88** [eclipse/mosquitto#1990]
Working on packaging mosquitto-2.0.4 in Gentoo/Linux, and I'm seeing the client test fail. I've added `set -x` to see what's going on a little better.

````
macbook /var/tmp/portage/app-misc/mosquitto-2.0.4/work/mosquitto-2.0.4/test # make -C client test
make: Entering directory '/var/tmp/portage/app-misc/mosquitto-2.0.4/work/mosquitto-2.0.4/test/client'
./test.sh
+ export BASE_PATH=../../
+ BASE_PATH=../../
+ export LD_LIBRARY_PATH=../..//lib
+ LD_LIBRARY_PATH=../..//lib
+ export PORT=1888
+ PORT=1888
+ export SUB_TIMEOUT=1
+ SUB_TIMEOUT=1
+ export MOSQ_PID=353902
+ MOSQ_PID=353902
+ sleep 0.5
+ ../../src/mosquitto -p 1888
+ trap 'kill 353902' EXIT
+ ../..//client/mosquitto_sub -p 1888 -W 1 -C 1 -t '$SYS/broker/uptime'
Timed out
+ kill 353902
make: *** [Makefile:8: test] Error 27
make: Leaving directory '/var/tmp/portage/app-misc/mosquitto-2.0.4/work/mosquitto-2.0.4/test/client'
````

Any clues what's going wrong or where to begin debugging?

**Comment by ralight** [comment]
Thanks for maintaining the Gentoo package. The test that is failing relies on the broker publishing to `$SYS/broker/uptime`, and the `mosquitto_sub` client subscribing and receiving that message. If you compile using `WITH_SYS_TREE=no` then that message won't be published, as one example.

The first test isn't crucial, you could comment it out - the subsequent tests all test subscribing anyway.

Alternatively, you could try increasing the SUB_TIMEOUT variable, or changing the line to remove the redirect to /dev/null, and add `-d` :

```
${BASE_PATH}/client/mosquitto_sub -p ${PORT} -W ${SUB_TIMEOUT} -C 1 -t '$SYS/broker/uptime' -d
```

In that case, I get this:

```
./test.sh
+ export BASE_PATH=../../
+ BASE_PATH=../../
+ export LD_LIBRARY_PATH=../..//lib
+ LD_LIBRARY_PATH=../..//lib
+ export PORT=1888
+ PORT=1888
+ export SUB_TIMEOUT=1
+ SUB_TIMEOUT=1
+ export MOSQ_PID=131736
+ MOSQ_PID=131736
+ sleep 0.5
+ ../../src/mosquitto -p 1888
+ trap 'kill 131736' EXIT
+ ../..//client/mosquitto_sub -p 1888 -W 1 -C 1 -t '$SYS/broker/uptime' -d
Client (null) sending CONNECT
Client (null) received CONNACK (0)
Client (null) sending SUBSCRIBE (Mid: 1, Topic: $SYS/broker/uptime, QoS: 0, Options: 0x00)
Client (null) received SUBACK
Subscribed (mid: 1): 0
Client (null) received PUBLISH (d0, q0, r1, m0, '$SYS/broker/uptime', ... (9 bytes))
0 seconds
Client (null) sending DISCONNECT
+ echo 'Simple subscribe ok'
Simple subscribe ok
```

Does that help?

**Comment by mattst88** [comment]
> Thanks for maintaining the Gentoo package

My pleasure. Thank *you* for the awesome software and for taking the time to help with silly problems like this!

> Does that help?

Indeed it does! I changed `SUB_TIMEOUT` to 3 and the test consistently passes for me. I'll make that change in our packaging.

Thank you again! (and my apologies for not responding in a timely fashion)
