### ISSUE TITLE
Windows can not connect outside localhost

### ISSUE THREAD

**Issue by bodemax** [eclipse/mosquitto#1991]
i can not connect to the broker outsite localhost.

If i try to connect with ip: 127.0.0.1 i have no problems. But if i try whit my local ip 192.168.x.x it does not work. I have set the standaard port open on my pc (tcp:1883). still nothing, if i use netstat -a in powershell i se the port is listening. I dont find any solotion on the interent. so i hope you know if this is a bug or a conflict.

i have done this  on my school pc, and i have a lot of software. so conflict is posible.  

tanks in advance
Maxim

**Comment by Gin56** [comment]
I have the same problem... with test.mosquitto.org he working well.

**Comment by ptjm** [comment]
See my answer in #1985. Summary is that as of mosquitto 2.0, you need to define a listener and an authentication method to listen on addresses other than localhost.

**Comment by bodemax** [comment]
> See my answer in #1985. Summary is that as of mosquitto 2.0, you need to define a listener and an authentication method to listen on addresses other than localhost.

Tank u verry much :D
