### ISSUE TITLE
Unable to connect with mqtt protocol when both mqtt and websockets listeners are enabled

### ISSUE THREAD

**Issue by Hallot** [eclipse/mosquitto#1994]
Broker version: 1.6.9 from Ubuntu 20.04 repo, 2.0.4 built from source with websockets support  
Client version: libmosquitto (C) 1.6.12, 2.0.4 built from source

mosquitto.conf:  
```
listener 8883
protocol mqtt

# Uncomment to add Websockets support
#listener 8083 
#protocol websockets

cafile /conf/certs/ca.crt
certfile /conf/certs/broker.crt
keyfile /conf/certs/broker.key

allow_anonymous false
password_file /conf/users.txt

persistence true
persistence_location /data/

log_dest file /logs/mosquitto/mosquitto.log
log_type all
```

Observed behaviour:
- run the broker with this config; connect with my client with the proper certificate/username/password using 8883/mqtt => ok  
- uncomment the two lines for the websockets listener and do the same as above => cannot connect anymore

Broker output in successful case:  
```
1609862445: mosquitto version 1.6.9 starting
1609862445: Config loaded from conf/mosquitto.conf.
1609862445: Opening ipv4 listen socket on port 8883.
1609862445: Opening ipv6 listen socket on port 8883.
1609862449: New connection from 213.55.244.106 on port 8883.
1609862449: New client connected from 213.55.244.106 as 8Bhyjy7o9RqOaRMCGup5dcO (p2, c0, k60, u'service-1').
```

Broker output in failure case (same for both versions):  
```
1609862507: mosquitto version 1.6.9 starting
1609862507: Config loaded from conf/mosquitto.conf.
1609862507: Opening ipv4 listen socket on port 8883.
1609862507: Opening ipv6 listen socket on port 8883.
1609862507: Opening websockets listen socket on port 8083.
1609862510: New connection from 213.55.244.106 on port 8883.
1609862510: Client <unknown> disconnected due to protocol error.
1609863989: New connection from 213.55.244.106 on port 8883.
1609863989: Client <unknown> disconnected due to protocol error.
1609864175: New connection from 213.55.244.106 on port 8883.
1609864175: Client <unknown> disconnected due to protocol error.
1609864274: New connection from 213.55.244.106 on port 8883.
1609864274: Client <unknown> disconnected due to protocol error.
```

On the client side, the `mosquitto_connect_callback_set` is never triggered, however `mosquitto_disconnect_callback_set` sometimes is with error 19/MOSQ_ERR_KEEPALIVE.

It's quite possible the issue is due to a configuration/code error but the log is not really helping pinpoint what.  
Thanks!

**Comment by ralight** [comment]
The issue is that the `cafile`, `certfile`, and `keyfile` options only apply to the most recently defined listener, so when you uncomment your `listener 8083` line the first listener has no encryption applied.

Try this instead, assuming you want TLS on both listeners:

```
listener 8883
protocol mqtt
cafile /conf/certs/ca.crt
certfile /conf/certs/broker.crt
keyfile /conf/certs/broker.key

listener 8083 
protocol websockets
cafile /conf/certs/ca.crt
certfile /conf/certs/broker.crt
keyfile /conf/certs/broker.key
```

**Comment by Hallot** [comment]
That was it, thanks.
