### ISSUE TITLE
mosquitto_ctrl man page description incorrect

### ISSUE THREAD

**Issue by fyta2000** [eclipse/mosquitto#1995]
The man page description for `mosquitto_ctrl` is incorrect. 

```
Description

mosquitto_ctrl is a simple MQTT version 5/3.1.1 client that will publish a single message on a topic and exit.
```
This is the same as the description for `mosquitto_pub`.

**Comment by ralight** [comment]
Thanks very much, well spotted. I've fixed that in the repo and it will be updated on the web as part of the 2.0.5 release.
