### ISSUE TITLE
Service always holds one frame.

### ISSUE THREAD

**Issue by maxvalor** [eclipse/mosquitto#1996]
Hello, I am now confused with a problem: I tried to publish a data which size was 1920 * 1080 * 4 through mosquitto. But I found that the frame was always late. when I sended frame-1, the subscriber got  nothing, and then I sended frame-2, the subscriber got frame-1. When I sended frame-3, the subscriber got frame-2....Is there any configuration I should do to avoid this?

In addition, if I send a empty frame after the data frame, it works correctly sometimes:

publisher:
send data_frame on topic-1
send empty_frame on topic-1
delay(time)

sometimes the subscriber can get correct data and sometimes not.

**Comment by ralight** [comment]
Thanks for the report. I believe this is now fixed in fabdfcc060432f07595b4a10d4f4fb3d075c64dc , which will be part of 2.0.5.
