### ISSUE TITLE
role information lacking

### ISSUE THREAD

**Issue by willem4ever** [eclipse/mosquitto#1997]
when I do 'mosquitto_ctrl dynsec getgroup g_notifier' it shows Groupname: g_notifier Clients:   notifier, but it lacks the role(s) attached ... 

{
			"groupname":	"g_notifier",
			"roles":	[{
					"rolename":	"r_notifier"
				}],
			"clients":	[{
					"username":	"notifier"
				}]
		}

**Comment by ralight** [comment]
Thanks Willem, that is now fixed in `fixes` and will be part of 2.0.5 shortly.
