### ISSUE TITLE
deleting roles, groups in the wrong order causes issues

### ISSUE THREAD

**Issue by willem4ever** [eclipse/mosquitto#1998]
working ...
mosquitto_ctrl dynsec deleterole r_demo
mosquitto_ctrl dynsec deletegroup g_demo

not working ...
mosquitto_ctrl dynsec deletegroup g_notifier
mosquitto_ctrl dynsec deleterole  r_notifier

have to restart mosquitto to make it work again ....

**Comment by ralight** [comment]
Thanks very much, this is fixed and will be in 2.0.5.
