### ISSUE TITLE
bind_interface won't  work on my Raspberry Pi4, Buster tiny

### ISSUE THREAD

**Issue by Joerg55** [eclipse/mosquitto#1999]
I run mosquitto-2.0.4 on my raspberry Pi4 with raspian buster 5.4.79-v71+ (tiny version without desktop). Everything works fine but when i try to use the bind_interface-issue, start of mosquitto fails. logfile says: operation not permitted.

here my mosquitto.config

![grafik](https://user-images.githubusercontent.com/74838448/103936507-cb38be00-5127-11eb-84e0-9ea1548a978c.png)

I read in the mosquitto.conf.example that bind_interface requires elevated privileges. What does that mean? Even startting mosquitto from the commandline via sudo fails. Normally I use mosquitto.service(.simple) in /etc/systemd/system.

looking forward for every kind of help

**Comment by ralight** [comment]
You've done nothing wrong - this option wasn't updated to no longer require elevated priviliges (root). As mosquitto no longer uses root, that meant it would fail. That's now fixed and will be part of 2.0.5. Thanks for the report!
