### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [eclipse/mosquitto#2]
[An extra null pointer check is not needed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for NULL before free(p)?") in functions like the following.
* [_db_client_chunk_restore](https://github.com/eclipse/mosquitto/blob/bf959ef9b0ae0e4d74bf80158ffb0b7c69da533d/src/db_dump/db_dump.c#L34)
* [_mosquitto_will_set](https://github.com/eclipse/mosquitto/blob/bf959ef9b0ae0e4d74bf80158ffb0b7c69da533d/lib/will_mosq.c#L24)
* [_sub_topic_tokenise](https://github.com/eclipse/mosquitto/blob/bf959ef9b0ae0e4d74bf80158ffb0b7c69da533d/src/subs.c#L169)

**Comment by ralight** [comment]
These are already fixed in the develop branch, I don't think there is any benefit to changing it in the bug fixes branch. If you do spot any in develop then they're definite candidates for removal!

**Comment by elfring** [comment]
How do you think about to improve the implementation of [a function like "`db__client_chunk_restore`"](https://github.com/eclipse/mosquitto/blob/4195fde70bdb9e760dcca26512288588733063f0/src/db_dump/db_dump.c#L74 "Update candidate")?
