### ISSUE TITLE
Socket error on client , disconnecting.

### ISSUE THREAD

**Issue by ikarthikeyank** [eclipse/mosquitto#2002]
```
1610111799: New connection from 192.168.1.210 on port 1883.
1610111799: New client connected from 192.168.1.210 as mosq/?>xKJ_VVilfvKNCW7Z (c1, k120).
1610111799: Sending CONNACK to mosq/?>xKJ_VVilfvKNCW7Z (0, 0)
1610111799: Socket error on client mosq/?>xKJ_VVilfvKNCW7Z, disconnecting.
1610111804: New connection from 192.168.1.210 on port 1883.
1610111804: New client connected from 192.168.1.210 as mosq/=iUP?3Z^QY_SCcN^Yu (c1, k120).
1610111804: Sending CONNACK to mosq/=iUP?3Z^QY_SCcN^Yu (0, 0)
1610111804: Socket error on client mosq/=iUP?3Z^QY_SCcN^Yu, disconnecting.
```

I am working on a linux system which has 4 applications connecting to Mqtt broker. In my test cases, I'll abruptly stop 4 application and start again. When application is restarted few clients behave like this -` "Socket error on client mosq/=iUP?3Z^QY_SCcN^Yu, disconnecting."`

PS: I am using `_mosquitto_loop_start()_` for my clients. I will not use `_mosquitto_loop_stop()_` because as per my test cases, I'll stop abruptly. Please tell me where is the issue.

mosquitto version 1.4.10 (build date Wed, 13 Feb 2019 00:45:38 +0000)

mosquitto is an MQTT v3.1 broker.

Is this issue fixed? Do I need to have any other version?

Thanks.

**Comment by ralight** [comment]
Version 1.4.10 is pretty old now, I would definitely recommend upgrading. The version number and build date tell me you're running on Debian Stretch. Luckily for you there is an updated package version 1.6.12 provided by the Mosquitto project for Debian Stretch. There are some details on how to install that package here: https://mosquitto.org/blog/2013/01/mosquitto-debian-repository/

I would also suggest moving up from Debian Stretch if you can, it is no longer receiving security updates.

**Comment by ikarthikeyank** [comment]
Thanks for the quick reply.

As per my understanding, you mean to move up Mosquitto version. Am I right?

I am willing to go out of Debian provided my issue is solved.

Is this issue fixed? If so, can you suggest me a solution to fix this issue?

**Comment by ralight** [comment]
Yes, I think you should upgrade your Mosquitto version, and unless you have a reason to stay on an old version of Debian that doesn't receive security updates, upgrade to a newer version of Debian as well. You haven't given enough information to be able to say whether your issue is solved, but i would imagine so. There have been about 30 Mosquitto releases since 1.4.10, 4 years ago. The 1.4.x line of code isn't supported any more.

**Comment by ikarthikeyank** [comment]
```
1610170216: New client connected from 192.168.1.210 as mosq/i_vVoeCH67qpo<so`x (p1, c1, k120).
1610170216: No will message specified.
1610170216: Sending CONNACK to mosq/i_vVoeCH67qpo<so`x (0, 0)
1610170216: Socket error on client mosq/i_vVoeCH67qpo<so`x, disconnecting.
1610170217: Received PINGREQ from 6685906e-37ff-4b8d-9001-2aec7c20690f1610167085817
1610170217: Sending PINGRESP to 6685906e-37ff-4b8d-9001-2aec7c20690f1610167085817
1610170217: Received PINGREQ from 188f303e-212f-418a-9e03-952a7b3d28e91610083171221
1610170217: Sending PINGRESP to 188f303e-212f-418a-9e03-952a7b3d28e91610083171221
1610170222: New connection from 192.168.1.210 on port 1883.
1610170222: New client connected from 192.168.1.210 as mosq/S<Y4xhGhYC8]bqG;dX (p1, c1, k120).
1610170222: No will message specified.
1610170222: Sending CONNACK to mosq/S<Y4xhGhYC8]bqG;dX (0, 0)
1610170222: Socket error on client mosq/S<Y4xhGhYC8]bqG;dX, disconnecting.
^C1610170223: mosquitto version 1.6.12 terminating
```

Updated to Mosquitto version 1.6.12. Still the issue persists. I would like to stick with Debian Stretch. 

Any luck???

**Comment by ralight** [comment]
Note that your client is still using an old version of the Mosquitto library, I can tell from the `mosq/...` style of client id.

The broker seems to be working fine in your logs, you have some clients connected and sending pings, so it is your specific client that has a problem.

I've attached a minimal example that uses `mosquitto_loop_start()` and that connects just fine. You can test it out, verify it works as expected, then compare it to your code: [min.c](https://github.com/eclipse/mosquitto/files/5790363/min.txt)

**Comment by ikarthikeyank** [comment]
I guess the Application's source code has to be edited. That uses old library. Please tell me if this issue is solved in Mosquitto version 1.6.12 so that I can modify the source code's library.

**Comment by ralight** [comment]
I don't believe it is an issue in the Mosquitto library, I believe it is an issue in your application code. I've given you an example to try out, I'd suggest you do that. You can then confirm for yourself whether the problem lies with the library or the application code.

**Comment by ikarthikeyank** [comment]
Thanks ralight. You were right. There is nothing wrong with the library. 

I was able to find the root cause of the problem. It's the 4 applications that try to connect to mosquitto using a same client id. Even though the client is generated unique and random, the 4 applications try to take the same unique id as client id. That's why they kick each other out. 

For those who still searching for the solution, please assign a unique client id for all your applications.

I'm closing this issue.
