### ISSUE TITLE
topic pattern not working on a bridge

### ISSUE THREAD

**Issue by Rod-O** [eclipse/mosquitto#2003]
instead the bridge subscribes to #
local is 2.0.4
remote is 1.6
no pattern, no remap, just plain # mirroring

**Comment by ralight** [comment]
I'm not quite sure what you mean, could you provide more details?

**Comment by Rod-O** [comment]
This is my bridge configuration:
#connection ORL
address 192.168.1.77:1883
cleansession false
start_type automatic
notifications true
topic facility/1/# in 1

I expect to get the messages only the messages from facility/1/# from the remote system
instead I'm getting ALL the messages, like having instead: topic # in 1

**Comment by ralight** [comment]
Have you ever used `#` on this bridge? I ask because you have `cleansession false`, which means old subscriptions will be kept.

**Comment by Rod-O** [comment]
changed to cleansession true
same results

**Comment by ralight** [comment]
This is what I get:

```
$ ./mosquitto -c m.conf  -v
1610135021: mosquitto version 2.0.4 starting
1610135021: Config loaded from m.conf.
1610135021: Opening ipv4 listen socket on port 1883.
1610135021: Opening ipv6 listen socket on port 1883.
1610135021: Connecting bridge ORL (localhost:1884)
1610135021: Bridge dev.ORL sending CONNECT
1610135021: mosquitto version 2.0.4 running
1610135021: Received CONNACK on connection local.dev.ORL.
1610135021: Bridge local.dev.ORL sending SUBSCRIBE (Mid: 2, Topic: facility/1/#, QoS: 1, Options: 0x00)
1610135021: Received PUBACK from local.dev.ORL (Mid: 1, RC:0)
1610135021: Received SUBACK from local.dev.ORL
```

I can see the subscription to `facility/1/#` there, and I've confirmed the bridge only receives messages in that topic space.

m.conf:
```
listener 1883
allow_anonymous true

connection ORL
address localhost:1884
cleansession false
start_type automatic
notifications true
topic facility/1/# in 1
```

I notice that you have a `#` at the start of the connection line, is that intentional? It makes it into a comment if it is actually in your config file rather than just on the issue text. If you've got another bridge connection above this one, then it could be interacting in a way you don't expect.

```
#connection ORL
```

**Comment by Rod-O** [comment]
my bad, 
I had many retained messages on the DB, these messages were popping up
