### ISSUE TITLE
Cosmetic issues -- 1

### ISSUE THREAD

**Issue by willem4ever** [eclipse/mosquitto#2005]
```
int dynsec_groups__process_add_role(cJSON *j_responses, struct mosquitto *context, cJSON *command, char *correlation_data)
.
.
	mosquitto_log_printf(MOSQ_LOG_INFO, "dynsec: %s/%s | addGroupRole | groupname=%s | rolename=%s | priority=%d",
			admin_clientid, admin_username, groupname, rolename, priority);

	if(dynsec_rolelist__group_add(group, role, priority) != MOSQ_ERR_SUCCESS){
		dynsec__command_reply(j_responses, context, "addGroupRole", "Internal error", correlation_data);
		return MOSQ_ERR_UNKNOWN;
	}
.
.
}
```

1. mosquitto_log_printf should called after dynsec_rolelist__group_add so it will not be called when the group_add fails (like other functions)
2. dynsec_rolelist__group_add(group, role, priority) != MOSQ_ERR_SUCCESS - should check for other possible return codes, now it returns an internal error on e.g. 'MOSQ_ERR_ALREADY_EXISTS'

**Comment by ralight** [comment]
Thanks Willem, they are good points.
