### ISSUE TITLE
addGroupClient another logging issue

### ISSUE THREAD

**Issue by willem4ever** [eclipse/mosquitto#2008]
```
int dynsec_groups__add_client(const char *username, const char *groupname, int priority, bool update_config)
.
.
HASH_FIND(hh, group->clientlist, username, strlen(username), clientlist);
	if(clientlist != NULL){
		/* Client is already in the group */
		return MOSQ_ERR_ALREADY_EXISTS;
	}
```
dynsec_groups__add_client() should return MOSQ_ERR_ALREADY_EXISTS  when client is already in the group  ... dynsec_groups__process_add_client() needs to deal with MOSQ_ERR_ALREADY_EXISTS  .... 

```
else if(rc == MOSQ_ERR_ALREADY_EXISTS) {
       dynsec__command_reply(j_responses, context, "addGroupClient", "Client already member", correlation_data);
}

```

thanks !

**Comment by ralight** [comment]
The original intent of having this report as a success was that if the client is already in the group then it doesn't matter. But thinking about it, I think having it report the true situation is better.
