### ISSUE TITLE
Uptime without unit

### ISSUE THREAD

**Issue by wutu** [eclipse/mosquitto#201]
It would be nice to have uptime without unit, as well as other values. Can I then processes as a string only.

**Comment by ralight** [comment]
I don't really want to break backwards compatibility here, can't you just do the following (or equivalent) before processing?

    uptime[strlen(uptime)-8] = '\0';

**Comment by wutu** [comment]
OK I understand. I can live with that. :smile:

**Comment by ralight** [comment]
Jolly good :)

**Comment by wutu** [comment]
Hello, unfortunately I encounter more and more systems that expect time in seconds (without unit). It would be the solution to add another topic?
`$SYS/broker/uptime_in_seconds` (or something similar).
Thx
