### ISSUE TITLE
mosquitto_ctrl: cannot override command-line parameters when config file is used

### ISSUE THREAD

**Issue by willem4ever** [eclipse/mosquitto#2010]
The processing order in ctrl_config_parse is wrong which prevents parameters used in the config file to be overridden by the same parameter used on the command-line, below order resolves the issue :-)

```
rc = client_config_load(cfg);
if(rc) return rc;

/* Deal with real argc/argv */
rc = client_config_line_proc(cfg, argc, argv);
if(rc) return rc;
```

**Comment by ralight** [comment]
Keep them coming! :)
