### ISSUE TITLE
添加ip地址无法连接？

### ISSUE THREAD

**Issue by w136111526** [eclipse/mosquitto#2012]
你好，我使用mqtt客户端连接mosquitto.exe服务器，填写localhost和127.0.0.1能正常连接，改成本机ip地址192.168.1.56却无法连接是什么原因呢？

**Comment by ralight** [comment]
If you are using Mosquitto 2.0.x, then if you want to connect from an IP address other than 127.0.0.1, you need to configure a listener in your configuration file, and also decide on your security policy. This means either configuring authentication with a password file or plugin, or allowing anonymous (unauthenticated) access.

```
listener 1883
password_file <your password file>
```

```
listener 1883
allow_anonymous true
```

There are more details on https://mosquitto.org/documentation/migrating-to-2-0/

**Comment by ralight** [comment]
Closing because this appears to be resolved. If not, please reopen and add more details.
