### ISSUE TITLE
mosquitto_string_option is not available on ARM

### ISSUE THREAD

**Issue by sbackovic** [eclipse/mosquitto#2014]
Is there any other option to specify tls_engine and tls_keyform using arm64 library?

**Comment by ralight** [comment]
`mosquitto_string_option()` should be available for all platforms from version 1.6 onwards, unless the packager has disabled TLS support, or openssl engine support is not available.

What package are you using?

**Comment by sbackovic** [comment]
Thank you for a quick answer.
I'm using debian libmosquitto-dev package

**Comment by ralight** [comment]
Debian stable only has 1.5.7, so you'll need to get a more recent version. You could try the project provided repo: http://mosquitto.org/2013/01/mosquitto-debian-repository/

**Comment by ralight** [comment]
It seems like this is fixed, so I'm closing this issue. If not, please reopen and add more details.
