### ISSUE TITLE
question: How can I reload mosquitto configuration in Docker without restarting

### ISSUE THREAD

**Issue by gmag11** [eclipse/mosquitto#2023]
Hi,

I'm running a mosquitto service as a service. I use `service mosquitto reload` to update user list without restarting it.

I want to migrate it to docker but I do not know to triger a HUP signal so that it reloads configuration.

What should be the right way to accomplish this? Thanks so much.

**Comment by ralight** [comment]
I haven't used it myself, but this has a description that makes sense:

`https://blog.confirm.ch/sending-signals-docker-container/`

**Comment by gmag11** [comment]
Thank you!!!
