### ISSUE TITLE
Does the Client Support Websocket Transport?

### ISSUE THREAD

**Issue by lsafelix75** [eclipse/mosquitto#2025]
Hi,

I am trying to find information related to websocket with mosquitto lib. But, i can't find any. Can you recommend? and any example with C++ client? Yes, i have googled but ended up in PAHO MQTT. TQ

**Comment by ralight** [comment]
It doesn't as yet, I'm afraid. This is something that I'm tentatively looking into though.

**Comment by lsafelix75** [comment]
@ralight thanks for your clarification.
