### ISSUE TITLE
CJSON discovery fails even if WITH_CJSON=OFF

### ISSUE THREAD

**Issue by madhat1** [eclipse/mosquitto#2026]
When building using **cmake**, and providing -DWITH_CJSON=OFF the cJson discovery process is still running and failing if I don't have cJson installed.

A simple fix in the main CMakeLists.txt will do the trick, surround the following block:

`FIND_PACKAGE(cJSON)`
`if (CJSON_FOUND)`
`    message(STATUS ${CJSON_FOUND})`
`else (CJSON_FOUND)`
`    message(STATUS "Optional dependency cJSON not found. Some features will be disabled.")`
`endif(CJSON_FOUND)`

with an :

`if (WITH_CJSON)`
`...`
`endif()`

That's all!

**Comment by ralight** [comment]
It feels like the whole point of `FIND_PACKAGE(cJSON)` is to deal with this... but ok, if it works I'm happy.

**Comment by madhat1** [comment]
You're right, but logically if `WITH_CJSON=OFF` was provided it's not correct to perform the discovery to begin with and show the 'missing cJson' warning, in this case the use explicitly wants to not use cJson.
` FIND_PACKAGE(cJSON)` may fail if the build environment contains a misconfigured or otherwise irrelevant cJson (for a different architecture for example).
Anyway, the fix solves all potential errors and avoids performing discovery if  `WITH_CJSON=OFF` was provided thus adhering to the developers wishes to 'not use cJson'.
