### ISSUE TITLE
Shared subscriptions not working

### ISSUE THREAD

**Issue by jklimke** [eclipse/mosquitto#2030]
I am currently trying to use shared subscriptions with mosquitto 2.0.5.

It started the mosquitto server using the simplest command line ```mosquitto -v```

When i subscribe to the shared topic via command line client to localhost

```mosquitto_sub -t $share/test_group/test -V mqttv5```

When i publish a message to the corresponding topic, there is no message delivered to the subscribing client (no output generated).

```mosquitto_pub -V mqttv5 -t test -m test```

The complete output of the server is the following:

```mosquitto -v
1610987124: mosquitto version 2.0.5 starting
1610987124: Using default config.
1610987124: Starting in local only mode. Connections will only be possible from clients running on this machine.
1610987124: Create a configuration file which defines a listener to allow remote access.
1610987124: Opening ipv4 listen socket on port 1883.
1610987124: Opening ipv6 listen socket on port 1883.
1610987124: mosquitto version 2.0.5 running
1610987127: New connection from ::1:50833 on port 1883.
1610987127: New client connected from ::1:50833 as auto-1B526590-C93F-961B-A3C9-AEB826BED53F (p5, c1, k60).
1610987127: No will message specified.
1610987127: Sending CONNACK to auto-1B526590-C93F-961B-A3C9-AEB826BED53F (0, 0)
1610987127: Received SUBSCRIBE from auto-1B526590-C93F-961B-A3C9-AEB826BED53F
1610987127: 	/test_group/test (QoS 0)
1610987127: auto-1B526590-C93F-961B-A3C9-AEB826BED53F 0 /test_group/test
1610987127: Sending SUBACK to auto-1B526590-C93F-961B-A3C9-AEB826BED53F
1610987135: New connection from ::1:50834 on port 1883.
1610987135: New client connected from ::1:50834 as auto-B6F87C96-E276-2780-B96C-D5F3BC0AD77C (p5, c1, k60).
1610987135: No will message specified.
1610987135: Sending CONNACK to auto-B6F87C96-E276-2780-B96C-D5F3BC0AD77C (0, 0)
1610987135: Received PUBLISH from auto-B6F87C96-E276-2780-B96C-D5F3BC0AD77C (d0, q0, r0, m0, 'test', ... (4 bytes))
1610987135: Received DISCONNECT from auto-B6F87C96-E276-2780-B96C-D5F3BC0AD77C
1610987135: Client auto-B6F87C96-E276-2780-B96C-D5F3BC0AD77C disconnected.
```

As far as i understood the protocol v5 the publishing to the ```test``` topic should deliver the published message to the one client of a subscription group. Is it a mosquitto bug or did i misunderstand something regarding shared subscriptions?

**Comment by ralight** [comment]
`mosquitto_sub -t $share/test_group/test -V mqttv5`

Almost certainly what is happening is that the `$share` is being interpreted as a variable by your shell. Try:

`mosquitto_sub -t '$share/test_group/test -V mqttv5'`

or

`mosquitto_sub -t \$share/test_group/test -V mqttv5`

**Comment by jklimke** [comment]
Oh my god. I am sorry for that stupid mistake. With the shell variable escaped it worked. :-/. 

As i wanted to provide an easy example i used the command line clients. I also tried it with MQTT_FX and javascript clients and that did not work out but maybe there is another problem with that client.

**Comment by ralight** [comment]
No problem, I recognised it straight away because I've made the same mistake myself lots of times :)

**Comment by jklimke** [comment]
Actually it turned out to be an issue with authentication. It seems that the ACL need to include the ```$share/<group_name>/``` prefix in order to allow a shared subscription

**Comment by ralight** [comment]
From your last comment it seems like this is sorted, so I'm closing the issue.
