### ISSUE TITLE
In what order are retained messages published for wildcard subscriptions?

### ISSUE THREAD

**Issue by vera** [eclipse/mosquitto#2035]
In the following situation:

1. Retained messages have been published on topics matching xyz/#, e.g. xyz, xyz/0, xyz/1, xyz/2
2. Client subscribes to xyz/#

In what order will the retained messages be published to the client? Is the order guaranteed in any way?

From my tests, it doesn't seem to be in publish order (I got xyz/0, xyz/1, xyz/2, xyz even though they were published in a different order).

Thank you!

Edit: After further testing, it appears the messages on xyz/... are published in original publish order, but the message on the top-level topic xyz is always published last. Is that correct?

```
$ mosquitto_pub -t "test2" -r -m "test"
$ mosquitto_pub -t "test2/1" -r -m "test"
$ mosquitto_pub -t "test2/2" -r -m "test"
$ mosquitto_pub -t "test2/" -r -m "test"
$ mosquitto_pub -t "test2/0" -r -m "test"
$ mosquitto_sub -t "test2/#" -v
test2/1 test
test2/2 test
test2/ test
test2/0 test
test2 test
```

**Comment by gdt** [comment]
This is not a bug report.

**Comment by vera** [comment]
Sorry! Reposted on the mailing list.
