### ISSUE TITLE
win10 64 mosquitto 2.0.5 Client <unknown>, not authorised.

### ISSUE THREAD

**Issue by ririfonfon** [eclipse/mosquitto#2036]
hello I have some problem with mosqitto for windows when I start it with this moss.conf:
listener 1883
allow_anonymous false

in shell :
PS C:\Program Files\mosquitto> .\mosquitto -c .\moss.conf -v
1611147942: mosquitto version 2.0.5 starting
1611147942: Config loaded from .\moss.conf.
1611147942: Opening ipv6 listen socket on port 1883.
1611147942: Opening ipv4 listen socket on port 1883.
1611147942: mosquitto version 2.0.5 running
1611147942: New connection from 2.0.0.181:51207 on port 1883.
1611147942: New connection from 2.0.0.181:53958 on port 1883.
1611147942: New connection from 2.0.0.181:50201 on port 1883.
1611147942: Sending CONNACK to 2.0.0.181 (0, 5)
1611147942: Client <unknown> disconnected, not authorised.
1611147942: Sending CONNACK to 2.0.0.181 (0, 5)
1611147942: Client <unknown> disconnected, not authorised.
1611147942: Sending CONNACK to 2.0.0.181 (0, 5)
1611147942: Client <unknown> disconnected, not authorised.
1611147942: New connection from 2.0.0.181:52616 on port 1883.
1611147942: Sending CONNACK to 2.0.0.181 (0, 5)
1611147942: Client <unknown> disconnected, not authorised.
1611147943: New connection from 2.0.0.11:59228 on port 1883.
1611147943: Sending CONNACK to 2.0.0.11 (0, 5)
1611147943: Client <unknown> disconnected, not authorised.
1611147943: New connection from 2.0.0.11:57093 on port 1883.
1611147943: Sending CONNACK to 2.0.0.11 (0, 5)
1611147943: Client <unknown> disconnected, not authorised.
1611147943: New connection from 2.0.0.181:56519 on port 1883.
1611147943: New connection from 2.0.0.181:59104 on port 1883.
1611147943: New connection from 2.0.0.181:54135 on port 1883.
1611147943: Sending CONNACK to 2.0.0.181 (0, 5)
1611147943: Client <unknown> disconnected, not authorised.
1611147943: Sending CONNACK to 2.0.0.181 (0, 5)
1611147943: Client <unknown> disconnected, not authorised.
1611147943: Sending CONNACK to 2.0.0.181 (0, 5)
1611147943: Client <unknown> disconnected, not authorised.
1611147944: New connection from 2.0.0.11:53931 on port 1883.
1611147944: New connection from 2.0.0.11:51140 on port 1883.
1611147944: Sending CONNACK to 2.0.0.11 (0, 5)
1611147944: Client <unknown> disconnected, not authorised.

what did I forget

**Comment by ralight** [comment]
```
listener 1883
allow_anonymous false
```

You've told the broker to not allow anonymous (unauthenticated) logins, but haven't provided a means for clients to authenticate. You could either set `allow_anonymous true`, create a `password_file`, use the [dynamic security plugin](https://mosquitto.org/documentation/dynamic-security/) (perhaps with the [Management Center](https://docs.cedalo.com/latest/docs/management-center/mc-overview) gui), or use a third party authentication plugin.

**Comment by ririfonfon** [comment]
Oh,
thank you
just: allow_anonymous true
