### ISSUE TITLE
Mosquitto broker is not able to process 5000 messages per sec

### ISSUE THREAD

**Issue by saumilsdk** [eclipse/mosquitto#2039]
Mosquitto broker is not able to process 5000 messages per sec incoming and 5000 messages outgoing per sec.

**Comment by ralight** [comment]
Yes it can, but it might depend on what hardware you are using and what your payloads are.

I connected 50 clients each publishing at 1000 msgs/s to a broker, each message was 256 bytes. I also connected a single subscriber. This is all on my 10 year old i5 2500k.

```
$SYS/broker/load/publish/received/1min 2996350.28
$SYS/broker/load/publish/sent/1min 2996350.28
```

This is from a second subscriber just looking at the metrics. That tells us that there were 2996350.28 messages published in 60 seconds (the 1min actually refers to the length of the moving average filter, it's different to the period over which we're measuring). So 2996350.28/60 = 49939.2 msgs/s both in and out, which is exactly what I'd expect.

**Comment by saumilsdk** [comment]
Thank you @ralight looks like I had network latency issues. How many messages can mosquitto broker can queue on receiving and before publishing?

**Comment by ralight** [comment]
You can use the `max_queued_messages` configuration option to choose how many messages to queue before further messages are dropped.

**Comment by saumilsdk** [comment]
Thank you this helps a lot :)
