### ISSUE TITLE
duplicated messages received when bridging

### ISSUE THREAD

**Issue by mhmayyan** [eclipse/mosquitto#204]
I am testing Mosquitto on an Ubuntu machine and two raspberries. I am using bridges between all of them as following 

>Ubuntu Machine
>>connection Ubuntu_to_Pi2
address pi2domain:1883
topic ubuntu/# in 0
topic pi2/# out 0

>>connection Ubuntu_to_Pi3
address pi3domain:1883
topic ubuntu/# in 0
topic pi3/# out 0

> Pi2 Machine
>>connection Pi2_to_Ubuntu
address ubuntudomain:1883
topic pi2/# in 0
topic ubuntu/# out 0

>>connection Pi2_to_Pi3
address pi3domain:1883
topic pi2/# in 0
topic pi3/# out 0

> Pi3 Machine
>>connection Pi3_to_Ubuntu
address ubuntudomain:1883
topic pi3/# in 0
topic ubuntu/# out 0

>>connection Pi3_to_Pi2
address pi2domain:1883
topic pi3/# in 0
topic pi2/# out 0

The problem is that I receive a duplicate message between Ubuntu and Pi3 networks. For example, if I send the following to Ubuntu network

Topic    pi3
Message       hello from Ubuntu network

then I see the message once on Ubuntu network if I listen to '#' BUT I see the message TWICE on Pi3 network. 

The same problem appears when I send messages from Pi3 network like the following 

Topic    ubuntu
Message       hello from Pi3 network

then I see the message once on Pi3 network if I listen to '#' BUT I see the message TWICE on Ubuntu network. 

The same problem sometimes appears on all bridges. 

The problem happens even If I use QoS = 2 or 1

Please help.

**Comment by ralight** [comment]
The problem that you have is that each broker is setting up a bridge connection. So Broker `Ubuntu` is subscribing to  `ubuntu/#` on `Pi2`. Broker `Pi2` is *also* setting up a bridge connection that sends messages to `Ubuntu` on topic `ubuntu/#`. So you've got duplicate messages because you've got two subscriptions.

To fix it, just have one lot of `topic` for each topic.

**Comment by mhmayyan** [comment]
I tried having only one bridge b/n Ubuntu and Pi3 and I took out Pi2 from the network and from the configuration files as well. However, I still have the same problem EVEN if I set the Pi3 to be only receiving from Ubuntu and vise versa I still have the same problem. 

Sometimes, It works very well for some number of messages (10 messages for example) then it starts duplicating the messages.

**Comment by ralight** [comment]
This could be caused by persistence on the central broker having stored the subscriptions from before. Try removing the persistence file on the central broker and trying again.
