### ISSUE TITLE
docker eclipse-mosquitto:2.0 Error: Address not available

### ISSUE THREAD

**Issue by a-wing** [eclipse/mosquitto#2040]
```bash
docker run eclipse-mosquitto:2.0
1611227315: mosquitto version 2.0.5 starting
1611227315: Config loaded from /mosquitto/config/mosquitto.conf.
1611227315: Starting in local only mode. Connections will only be possible from clients running on this machine.
1611227315: Create a configuration file which defines a listener to allow remote access.
1611227315: Opening ipv4 listen socket on port 1883.
1611227315: Opening ipv6 listen socket on port 1883.
1611227315: Error: Address not available
1611227315: mosquitto version 2.0.5 running
```

Error: Address not available

**Comment by citrusvanilla** [comment]
geeze im glad i found this.  i tried to pin the 2.0.5 image as well in my docker-compose yaml and your message made me think it had to do with changing the tab.  i rolled back to 1.6.12 for the time being.  2.0.5 is giving me an error that i had suspected was from the mosquitto daemon possibly running in the background somehow though i could find no evidence supporting this.

**Comment by ralight** [comment]
Mosquitto 2.0 binds to the loopback interface if you don't provide a `listener` configuration. That loopback interface probably isn't available to your docker container, so it fails. If you add `listener 1883` to your configuration it will start working happily again - but note that you also need to configure some form of authentication, or set `allow_anonymous true` if you don't want clients to have to authenticate.

Full details on moving to 2.0 are here: https://mosquitto.org/documentation/migrating-to-2-0/

**Comment by Derkades** [comment]
Is there any way this can be the default for the docker image, for example an environment variable that is set by default in Dockerfile and detected by the mosquitto server? It is somewhat inconvenient to mount a config in the container just to get it to work, the previous version worked fine without any configuration.

Recently the :latest tag (which I admittedly shouldn't have been using) was switched from v1 to v2 and it broke my setup.

**Comment by ralight** [comment]
@Derkades I'm sorry to hear it broke your setup.

The breaking changes have been advertised for the past two months, and the change of the `latest` tag was advertised a week before it happened. I appreciate that not everyone will want to / be able to follow all of the projects they are using for changes like this, but I hope you'll appreciate we have tried to give plenty of opportunity for people to discover that there are breaking changes, and to have chance to do something about them.

Security is by its nature a bit inconvenient. The aim of the breaking changes is to require people to actively think about how they are securing their broker. If they want to allow unauthorised access, so be it, but it definitely shouldn't be the default.

**Comment by TomasVojacek** [comment]
Can be documentation udated page:
https://hub.docker.com/_/eclipse-mosquitto?tab=description
There no info that docker image as it is created does not work.
And there is no info or links info how to fix this?

**Comment by Derkades** [comment]
> I hope you'll appreciate we have tried to give plenty of opportunity for people to discover that there are breaking changes

Yes, and I fully realize it is my mistake for using a :latest image instead of pinning a specific version.

> Security is by its nature a bit inconvenient.

In this case however the default configuration is not more secure, but simply broken in case of docker. Applications in docker are expected to listen on all interfaces. As @TomasVojacek said the documentation on [docker hub](https://hub.docker.com/_/eclipse-mosquitto) does not mention `listener 1883` which means it won't work (--ports does not work for applications binding only to 127.0.0.1 inside the container as far as I know)

**Comment by lepinkainen** [comment]
Thank you for this change, it made me notice:

1. How important Mosquitto is to my home automation setup
2. How badly I'm monitoring that it's actually running 🎉 

This gave me the excuse to tighten up security a bit and add some basic monitoring so that I don't spend two days figuring out why my Zigbee switches don't work :D

**Comment by stahnma** [comment]
I also found this in a docker container loading up on another node. Thus far, I haven't figured out how to pass instruction to the daemon to bind on a public interface without loading in a whole `mosquitto.conf` and that's a file I have to pass around with a docker container and not just a ENV var. Could this be made into an ENV var so it can be handled via a runtime string and not having to pass state somehow to start the container?

**Comment by mosterdt** [comment]
While I think it's a great idea to bind to the loopback interface by default, I do agree with others that the docker container documentation could at least reflect this. The official image documentation has no mention of needing a listener: https://hub.docker.com/_/eclipse-mosquitto , and the docker documentation in this repository also makes no mention: https://github.com/eclipse/mosquitto/tree/master/docker/2.0

If people follow these instructions, they end up with an unreachable mosquitto instance inside a container. While there is great value in not defaulting to all interfaces on a normal system, restricting the listener to localhost inside a docker container serves no real benefit. It forces users to always define a mosquitto.conf. And even if mosquitto binds to every address within a docker container,  it is still up to the user of the container to bind this port to their own network with e.g. `-p 1883:1883`.

**Comment by lepinkainen** [comment]
@mosterdt is correct, there is no added security in having a service be loopback-only inside a Docker container. I can't even think of a use-case where that would be useful. Web servers, databases etc. become completely useless unless something can access it :)

What is allowed to access the container from the outside should be decided by the container configuration when starting up.

**Comment by michaelosthege** [comment]
I'm running a mosquitto Docker container as part of a Gitlab CI for integration tests:

```
test-mypackage:
  stage: test
  image: python:3.7
  services:
  - name: eclipse-mosquitto:1.6.13
    alias: mqtt-ci-broker
  script:
  - pytest ...
```
Passing a configuration file is _much much_ harder than passing an environment variable. In fact the [Gitlab documentation on services](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#passing-environment-variables-to-services) only has examples for how to pass configuration through environment variables.

Please consider to make the listener configurable through an environment variable.

**Comment by 06kellyjac** [comment]
https://hub.docker.com/_/eclipse-mosquitto doesn't document the change in mosquito config location

**Comment by ralight** [comment]
The use of an environment variable was rejected by docker, but you can use the no authentication configuration that is provided:

```
docker run -it -p 1883:1883 eclipse-mosquitto:<version> mosquitto -c /mosquitto-no-auth.conf
```

**Comment by tablatronix** [comment]
nothing like a point release to break everything.. ugh

**Comment by 06kellyjac** [comment]
@tablatronix AFAIK this was a major release going to `2.0.0`, not a minor or patch version bump

---

It may have been latest catching up from `1.X.X` straight to `2.5.0` or something in an effort to delay the breaking change longer for latest tag followers 🤷 Just speculating.

But an unstable tag is an unstable tag and `latest` users need to accept that.
The tag just `2` should give most of the benefits of `latest` but avoid the downside of major version breaking changes

**Comment by melyux** [comment]
I don’t get it, why can’t we pass the listener configuration as an environment variable? Like we can do with MOSQUITTO_USERNAME, etc.?

**Comment by 06kellyjac** [comment]
I thought I read somewhere docker wouldn't let them do that (since its an official docker image) but now I can't find  where I read that so maybe I imagined it 🙃

**Comment by Derkades** [comment]
> I thought I read somewhere docker wouldn't let them do that (since its an official docker image) but now I can't find where I read that so maybe I imagined it upside_down_face

you read it here: https://github.com/eclipse/mosquitto/issues/2040#issuecomment-792349744

**Comment by melyux** [comment]
Yeah, I saw that comment but didn’t know why on earth “docker” would reject an environment variable. @06kellyjac Didn’t know that about official images.

**Comment by salzig** [comment]
out of curiosity: binding an application to "0.0.0.0" inside of a container is like the classic localhost binding, in a way that only the host where the application is run (and other apps on that host inside a container) can access the application. Where is the benefit of running mosquitto only on localhost in a container? So far i can only see downsides.

**Comment by vava24680** [comment]
For those who faced the inconvenient usage when using mosquitto image in GitLab CI, maybe you can consider using the [GitLab Container Registry](https://docs.gitlab.com/ee/user/packages/container_registry/) service to store the mosquitto images with default configuration that can listen on all the interfaces, the GitLab CI can use the images in the project's Container Registry directly. We have used this method to overcome the inconvenience.

**Comment by Tofandel** [comment]
Why just not change the default config file so it includes `listener 1883` so it will work by default for everybody using docker ?

**Comment by mspoehr** [comment]
This just bit me today. This command from above got me up and running:

```
docker run -it -p 1883:1883 eclipse-mosquitto:<version> mosquitto -c /mosquitto-no-auth.conf
```

@ralight why isn't this documented on [eclipse-mosquitto's docker hub page](https://hub.docker.com/_/eclipse-mosquitto)? Adding a short description of the available config files in the container would probably help a lot of people, especially if the default is going to be mosquitto running in local mode.

**Comment by octopop** [comment]
Ran into same issue only to have adding `listener 1883` to my .conf file fixing the issue. Should be added a default or _at least_ be documented on the docker hub page.

**Comment by 06kellyjac** [comment]
> @ralight why isn't this documented on the [eclipse-mosquitto's docker hub page](https://hub.docker.com/_/eclipse-mosquitto)? Adding a short description of the available config files in the container would probably help a lot of people, especially if the default is going to be mosquitto running in local mode.


Yeah, this has been raised months ago: https://github.com/eclipse/mosquitto/issues/2040#issuecomment-783402363

It was added to this README here: https://github.com/eclipse/mosquitto/tree/master/docker/2.0 in this commit 12ff9d5e1491b805605d698c198b681db5c1dcbb but the README on docker hub is either in a different location/repo or needs to be edited by hand in the Docker Hub UI.

Please update the Docker Hub page @ralight because very few people are going to find that README within the docker/2.0 dir.

**Comment by groovenectar** [comment]
Running into a lot of these issues as well with the Docker method...

I saw this in `mosquitto.conf` which reflects some of the comments here:

```
#listener 1883 
#socket_domain ipv4
#uncomment 2 lines above for first run so we get LE certificates. 
#at the same time comment out all lines below. Once you have the certificate
#stop the unencrypted listener
```

So I tried following those directions but I still get:

```
mosquitto_1   | 1647606589: Opening ipv6 listen socket on port 1883.
mosquitto_1   | 1647606589: Error: Address not available
mosquitto_1   | 1647606589: mosquitto version 2.0.14 running
otrecorder_1  | ot-recorder[11]: version 0.8.8 starting with STORAGEDIR=/store
otrecorder_1  | ot-recorder[11]: connecting to MQTT on mosquitto:1883 as clientID ot-recorder-095362d0488f-11 without TLS
otrecorder_1  | Error: Connection refused
docker-recorder_otrecorder_1 exited with code 14
```

Wouldn't mind just having HTTP instead of MQTT, but nothing at all seems to take yet. Trying on Rocky Linux (CentOS) 8

**Comment by groovenectar** [comment]
This seems to do something at least:

`docker run -it -p 1883:1883 eclipse-mosquitto:<version> mosquitto -c /mosquitto-no-auth.conf`

From here: https://github.com/eclipse/mosquitto/tree/master/docker/2.0

So I just need to figure out authentication

**Comment by sb603** [comment]
getting the following in logs..

my conf file looks like:

```
`listener 1883
protocol websockets
allow_anonymous false
persistence true
persistence_location /mosquitto/data
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
password_file /mosquitto/passwd
log_type all
```
`

````
`1657049490: mosquitto version 2.0.14 starting
1657049490: Config loaded from /mosquitto/config/mosquitto.conf.
1657049490: Starting in local only mode. Connections will only be possible from clients running on this machine.
1657049490: Create a configuration file which defines a listener to allow remote access.
1657049490: For more details see https://mosquitto.org/documentation/authentication-methods/
1657049490: Opening ipv4 listen socket on port 1883.
1657049490: Opening ipv6 listen socket on port 1883.
1657049490: Error: Address not available
1657049490: mosquitto version 2.0.14 running
1657049951: mosquitto version 2.0.14 terminating
1657049951: Saving in-memory database to /mosquitto/data//mosquitto.db.
1657049952: mosquitto version 2.0.14 starting
1657049952: Config loaded from /mosquitto/config/mosquitto.conf.
1657049952: Error: Unable to open pwfile "/mosquitto/log/mosquitto.passwd".
1657049952: Error opening password file "/mosquitto/log/mosquitto.passwd".
1657049952: mosquitto version 2.0.14 starting
1657049952: Config loaded from /mosquitto/config/mosquitto.conf.
1657049952: Error: Unable to open pwfile "/mosquitto/log/mosquitto.passwd".
1657049952: Error opening password file "/mosquitto/log/mosquitto.passwd".
1657049953: mosquitto version 2.0.14 starting
1657049953: Config loaded from /mosquitto/config/mosquitto.conf.
1657049953: Error: Unable to open pwfile "/mosquitto/log/mosquitto.passwd".
1657049953: Error opening password file "/mosquitto/log/mosquitto.passwd".
1657049954: mosquitto version 2.0.14 starting
1657049954: Config loaded from /mosquitto/config/mosquitto.conf.
1657049954: Error: Unable to open pwfile "/mosquitto/log/mosquitto.passwd".
```

Anyone else getting the unable to open pwfile constantly?
