### ISSUE TITLE
MQTT 5 suback reasoncodes esp. 135 Not authorized

### ISSUE THREAD

**Issue by laXta** [eclipse/mosquitto#2042]
Dear community,

I am sorry if I am mistaken and also if I now duplicate the issue. As far as I understand the MQTT-5 protocol correctly, the suback packet should give a reason code (135, [see suback](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901171)) when trying to subscribe a topic that the user is not allowed to. But if I subscribe a forbidden topic, I just receive the code 0 | 1 | 2 depending on qos. Anyway I do not receive any values/publish-packet considering the subscription - it just silently fails. Therefore, I assume my acls are correct (publish also throws 135 as expected).

All I found was this [topic](https://github.com/eclipse/mosquitto/issues/1654), where suback reason codes except for "unspecified" seem not be implemented(yet?). Is this still the case or is it a bug? And if it is not implemented, will it be implemented in the near future as I believe it's quite handy, even throwing "unspecified" would be better then a granted response in my opinion.

I currently develop with v. 2.0.5 from snap in a manjaro vm. Furtheremore I mainly use mqttjs as client (of course with protocolVersion: 5 as option). 

Thank you!

**Comment by ralight** [comment]
If you're using an `acl_file` then subscriptions are never forbidden. The ACLs forbid the deliver of PUBLISH to the matching topics only. I'd suggest moving to the dynamic security plugin, it's a lot more flexible and allows control over SUBSCRIBE as well: https://mosquitto.org/documentation/dynamic-security/

**Comment by laXta** [comment]
Hi Roger,

thank you very much for this quick and helpful answer. I didn't know about that limit of acl-files. I will check out the security plugin. I guess that if configured right moquitto will give a negative response then?!

have a nice weekend!

**Comment by laXta** [comment]
Hi Roger,

Now that I set up the dynamic-plugin for mosquitto, the broker rejects the subscriptions as expected with code 135 - nice. Thank you again, really helpt me out!
