### ISSUE TITLE
mosquitto_validate_utf8 

### ISSUE THREAD

**Issue by phplpf** [eclipse/mosquitto#2044]
mosquitto_sub: symbol lookup error: mosquitto_sub: undefined symbol: mosquitto_validate_utf8
nm -D mosquitto_validate_utf8 | grep mosquitto_sub
nm: 'mosquitto_validate_utf8': No such file
请问应该如何解决。1.6.12 和2.0.0 都报这个错 在执行mosquitto_sub mosquitto_pub 时 第二行和第三行是没有查询到该库

**Comment by ralight** [comment]
`mosquitto_validate_utf8()` was introduced in version 1.5, so I wonder if you have a 1.4 version mosquitto library somewhere that is being picked by the runtime linker ahead of the 1.6/2.0 library.

**Comment by ralight** [comment]
I don't think this is directly a Mosquitto problem, so I'm closing this issue. If you think it's still a problem please reopen and add some more details.
