### ISSUE TITLE
No connection to mosquito

### ISSUE THREAD

**Issue by MarkM500** [eclipse/mosquitto#2049]
Hi there,

I have the following problem:
Installed mosquitto eclipse on synology with docker. No problems, also the log says no problems:

> 2021-01-25 19:10:48,stdout,1611601848: Opening ipv6 listen socket on port 1883.

2021-01-25 19:10:48,stdout,1611601848: Opening ipv4 listen socket on port 1883.

2021-01-25 19:10:48,stdout,1611601848: Config loaded from /mosquitto/config/mosquitto.conf.

2021-01-25 19:10:48,stdout,1611601848: mosquitto version 1.6.12 starting

2021-01-25 18:37:22,stdout,1611599842: mosquitto version 1.6.12 terminating

2021-01-25 18:35:44,stdout,1611599744: mosquitto version 1.6.12 running
``
My client says no connection:

> 21:30:31 MQT: Verbindungsversuch...
21:30:31 MQT: Verbindung fehlgeschlagen aufgrund von 192.168.178.23:1883, rc -2. Wiederversuch in 120 s

And also with the terminal on my mac:
ping 127.0.0.1:1883
ping: cannot resolve 127.0.0.1:1883: Unknown host

What is my problem? What can I do?

History: I had it running. But after a failed try to change my password in mosquitto.conf I decided to deinstall mosquito an d to reinstall. But now.....

Thanks a lot for your ideas.
Mark

**Comment by ralight** [comment]
It's difficult to say given the many things that it could be. Have you made sure that port 1883 is accessible through docker?

```
ping 127.0.0.1:1883
```

Ping doesn't work with a port. You should try something like `mosquitto_sub -t '$SYS/# -v -h localhost`.

**Comment by MarkM500** [comment]
Hi,
 thanks.
Tested...but no result after minutes..

![Bildschirmfoto 2021-01-26 um 00 39 19](https://user-images.githubusercontent.com/77006589/105779752-4cd57c00-5f6f-11eb-81fd-20ea4492004d.png)

Also no reaction in the protocol of mosquito.
Hmm...
