### ISSUE TITLE
undefined reference to `mosquitto_callback_register' in mosquitto 2.0.5

### ISSUE THREAD

**Issue by janderholm** [eclipse/mosquitto#2051]
I'm trying to create a plugin for mosquitto 2.0.5 and started by copying the _auth-by-ip_ plugin to a new package. It seems the plugin functions are not available in the library anymore. 

```
cc  -o src/libmosquitto-auth-by-ip.so.1.2.3 src/libmosquitto-auth-by-ip.so.1.2.3.p/lib.c.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libmosquitto-auth-by-ip.so.0 /usr/lib/x86_64-linux-gnu/libglib-2.0.so /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libmosquitto.so -Wl,--end-group
/usr/bin/ld: src/libmosquitto-auth-by-ip.so.1.2.3.p/lib.c.o: in function `mosquitto_plugin_init':
/path/to/mosquitto-auth-by-ip/builddir/../src/lib.c:77: undefined reference to `mosquitto_callback_register'
/usr/bin/ld: src/libmosquitto-auth-by-ip.so.1.2.3.p/lib.c.o: in function `mosquitto_plugin_cleanup':
/path/to/mosquitto-auth-by-ip/builddir/../src/lib.c:82: undefined reference to `mosquitto_callback_unregister'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
The terminal process "/usr/bin/fish '-c', 'ninja'" terminated with exit code: 1.
```

Upon closer inspection, the plugin functions are not available in libmosquitto.so:
```
$ nm -gD /usr/lib/x86_64-linux-gnu/libmosquitto.so.2.0.5 | grep mosquitto_callback_register || echo "Nothing there"
Nothing there
```

Have I missed something? The functions are there in the installed headers, they are just not included in the .so for some reason.

**Comment by janderholm** [comment]
I got it to work by adding `-Wl,--unresolved-symbols=ignore-in-object-files` to the linker. I don't quite understand it, but I assume it has something to do with plugins being dlopened so the functions are available in process anyway.

**Comment by ralight** [comment]
I presume this linker option in your original command didn't help :) `-Wl,--no-undefined`

You're right though, the functions are available in process when mosquitto dlopens the shared plugin. There is no need to link against libmosquitto at all.

**Comment by janderholm** [comment]
No, you are right. This is something meson adds by default so I didn't catch it until I carefully read the post I had just made :-)

Thank you for confirming my suspicion!
