### ISSUE TITLE
"latest" does not point to the latest version on docker-hub

### ISSUE THREAD

**Issue by ccvca** [eclipse/mosquitto#2052]
As version 2 has been release, the latest-Tag on docker-hub should also point to version 2 and not 1.6 release.

https://hub.docker.com/_/eclipse-mosquitto

PS: I'm aware that this might break some "auto update" setups, but that's what you can expect from a major version change.

**Comment by ralight** [comment]
PR submitted: https://github.com/docker-library/official-images/pull/9567
