### ISSUE TITLE
misc/letsencrypt/mosquitto-copy.sh has non-POSIX syntax

### ISSUE THREAD

**Issue by gdt** [eclipse/mosquitto#2056]
Line 15 has == within test, which is a bashism not specified by POSIX.

To fix, just change to =.

(This currently needs to patched in pkgsrc, which has portability checks for non-POSIX usage in scripts starting with /bin/sh, in order to avoid the package build failing.)

**Comment by ralight** [comment]
Thanks Greg. I'm too used to using `==` for equality everywhere.
