### ISSUE TITLE
Config file values are truncated after first space.

### ISSUE THREAD

**Issue by jdwhite** [eclipse/mosquitto#2059]
This issue is present in 1.6.12 and 2.0.6.

In the OPTIONS section of the man pages for `mosquitto_{pub,sub}`, the first sentence reads:

> The options below may be given on the command line, but may also be placed in a config file located at        $XDG_CONFIG_HOME/[mosquitto_pub/sub] or $HOME/.config/[mosquitto_pub/sub] _**with one pair of -option value per line**_.

When parsing `mosquitto_{pub,sub}`, the values are truncated at the first space instead of end of line.  Example:

### ~/.config/mosquitto_sub:
```
-h somehost
-p someport
-F %I [%t]: "%p" (retain=%r qos=%q msgid=%m)
```

yields:
```
$ mosquitto_sub -t \#
2021-01-29T22:55:31-0600
```

I've tried escaping the spaces and putting the entire value in single quotes, but escaping spaces isn't valid and wrapping in single quotes yields:

`'2021-01-29T22:55:31-0600`

### ~/.config/mosquitto_pub
```
-h somehost
-p someport 
-f /home/bob/test dir/msg.txt
```

Will generate an error because the value is truncated:
```
$ mosquitto_pub -t sometopic
Error: Unable to open file "/home/bob/test".
Error loading input file "/home/bob/test".
```

As a workaround I've replaced all spaces with underscores, which is awful.

**Comment by sectokia** [comment]
The culprit is in client_shared.c:
`args[2] = strtok(NULL, " ");`

my suggested bad fix would  be:
`args[2] = (strlen(line)>strlen(args[1]) ? &line[strlen(args[1]+1)] : NULL;
`

**Comment by ralight** [comment]
@sectokia It's much easier than that, just a swap of a `" "` to `""` :)
