### ISSUE TITLE
Load plugin.so error: Undefined symbol "mosquitto_client_username" 

### ISSUE THREAD

**Issue by blusewang** [eclipse/mosquitto#2065]
Why my plugin passed compile,but can't load from conf file?
```
mosquitto -c mosquitto.conf
1612271905: mosquitto version 2.0.5 starting
1612271905: Config loaded from mosquitto.conf.
1612271905: Loading plugin: /usr/home/bluse/mosquitto-pg-auth-plug/auth-plugin.so
1612271905: Error: Unable to load auth plugin "/usr/home/bluse/mosquitto-pg-auth-plug/auth-plugin.so".
1612271905: Load error: /usr/home/bluse/mosquitto-pg-auth-plug/auth-plugin.so: Undefined symbol "mosquitto_client_username"
```
compile command is:
```
cc -I/usr/local/include -I`pg_config --includedir` -L/usr/local/lib -L`pg_config --libdir` -lpq -fPIC -shared auth_plugin.c -o auth-plugin.so
```
Am I missing some thing?
Help!

**Comment by ralight** [comment]
Bit of a guess here... are you on BSD or Mac?

**Comment by ralight** [comment]
If you're building mosquitto yourself, could you please try again using the `fixes` branch?

```
git clone https://github.com/eclipse/mosquitto
cd mosquitto
git checkout fixes
# build as you would have done normally
```

**Comment by blusewang** [comment]
> Bit of a guess here... are you on BSD or Mac?

Yes,build on FreeBSD

**Comment by blusewang** [comment]
> If you're building mosquitto yourself, could you please try again using the `fixes` branch?
> 
> ```
> git clone https://github.com/eclipse/mosquitto
> cd mosquitto
> git checkout fixes
> # build as you would have done normally
> ```

Oh! It work for me! Thank you @ralight ! Your are awesome!!!
