### ISSUE TITLE
Regression: broker cannot load private key with SSL engine

### ISSUE THREAD

**Issue by borisVanhoof** [eclipse/mosquitto#2066]
Hi,

In file src/net.c function net__load_certificates variable "ENGINE* engine" is initialized to NULL and this doesn't change.
This is because a part of the function net__tls_load_verify was moved to net__load_certificates to support reloading of the certificates. https://github.com/eclipse/mosquitto/commit/b2560f5e06577142a653000834cbf985d88cd5be

Also I think calling ENGINE_FINISH in net__load_certificates can cause issues. I don't know what the behavior will be.

This happened for me with Mosquitto v2.0.5.

**Comment by ralight** [comment]
Thanks, I'll take a look.
