### ISSUE TITLE
mosquitto_free crashes in plugin..

### ISSUE THREAD

**Issue by slaesh** [eclipse/mosquitto#2070]
```c

static int callback_message(int event, void *event_data, void *userdata) {
   struct mosquitto_evt_message *ed = event_data;
   struct timespec ts;
   struct tm *ti;

   UNUSED(event);
   UNUSED(userdata);

   mosquitto_log_printf(MOSQ_LOG_ERR, "HERE!");

   const int newLen = 25;
   void *p = mosquitto_malloc(newLen);

   if (p == NULL) {
      if (ed->payloadlen) {
         ((char *)ed->payload)[0] = '_';
      }

      return MOSQ_ERR_SUCCESS;
   }

   clock_gettime(CLOCK_REALTIME, &ts);
   ti = gmtime(&ts.tv_sec);

   strftime((char *)p, newLen, "%Y-%m-%dT%H:%M:%SZ", ti);

   if (ed->payloadlen) {
      // this call crashes !!
      // mosquitto_free(ed->payload);
   }

   ed->payload = p;
   ed->payloadlen = newLen;

   return MOSQ_ERR_SUCCESS;
}

```

what would be the correct way to modify/extend the payload?

**Comment by slaesh** [comment]
even `mosquitto_realloc` crashes..

**Comment by Daedaluz** [comment]
As I understand it, mosquitto will free it for you after return.

**Comment by slaesh** [comment]
But if I change the payload-pointer, mosquitto didn't know the "old one" .. and I think I need to free this mem .. or do they hold an old reference to clear the new and old one.. ?

**Comment by slaesh** [comment]
yeah, indeed.. they store the old refernece! :))
Easy!!

https://github.com/eclipse/mosquitto/blob/f1180dd23a32f4c6b7651abbb2646823f73ee5e4/src/plugin.c#L165

**Comment by slaesh** [comment]
![image](https://user-images.githubusercontent.com/55546823/106783125-3902d780-664b-11eb-8dc9-39ffbb0e4577.png)

**Comment by slaesh** [comment]
thanks @Daedaluz :+1:

**Comment by ralight** [comment]
I'm well aware this all needs properly documenting! (this specific case is demonstrated and commented in the `plugins/payload-modification` example by the way)

**Comment by slaesh** [comment]
Haha, my bad! Just saw the timestamp thing and was catched ;D
