### ISSUE TITLE
mosquitto.org ssl error?

### ISSUE THREAD

**Issue by crotel** [eclipse/mosquitto#2071]
I found `https://mosquitto.org` was down but ping was ok.

and I did `curl -I https://mosquitto.org`
It shows up `curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mosquitto.org:443 `

anything wrong?

**Comment by ralight** [comment]
The webserver was stuck in a crash loop for some reason. Sorted now, thanks!
