### ISSUE TITLE
Websocket data will be truncated if HTTP header is too long

### ISSUE THREAD

**Issue by ccpz** [eclipse/mosquitto#208]
Since libwebsockets V1.7.0, it adds a **max_http_header_data** in info struct:

https://github.com/warmcat/libwebsockets/blob/master/changelog#L370

> - max_http_header_data: 0 for default (1024) or set the maximum amount of known
>   http header payload that lws can deal with.  Payload in unknown http
>   headers is dropped silently.  If for some reason you need to send huge
>   cookies or other HTTP-level headers, you can now increase this at context-
>   creation time.

Therefore if mosquitto's websocket interface receives a HTTP header over 1024 bytes, all additional bytes will be dropped. Maybe it is better to make this value configurable at mosquitto config file?

**Comment by ralight** [comment]
Is this a problem you are seeing in practice? If so, could you give me an example? A single header >1024 bytes is pretty big.

**Comment by ccpz** [comment]
We have a web site based on Laravel framework 5.2, when user login, it will open a websockets channel using paho-javascript library from browser to Nginx reverse proxy, it forwards to  mosquitto websockets server (in order to prevent CSRF problem):

```
location /websockets/ {
        proxy_pass http://127.0.0.1:9001/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;
    }
```

Therefore it will also forwards the full HTTP headers to mosquitto, And here is the PCAP file:
[websockets.zip](https://github.com/eclipse/mosquitto/files/354311/websockets.zip)

**Comment by ccpz** [comment]
We have a web site based on Laravel framework 5.2, when user login, it will open a websockets channel using paho-javascript library from browser to Nginx reverse proxy, it forwards to  mosquitto websockets server (in order to prevent CSRF problem):

```
location /websockets/ {
        proxy_pass http://127.0.0.1:9001/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;
    }
```

Therefore it will also forwards the full HTTP headers to mosquitto, And here is the PCAP file:
[websockets.zip](https://github.com/eclipse/mosquitto/files/355489/websockets.zip)

**Comment by ralight** [comment]
I've had it confirmed that `max_http_header_data` is for the entirety of the headers, I'll see about making this an option.

**Comment by Hades32** [comment]
This is a very practical issue. We share the same domain for all services (including the "/mqtt" websocket endpoint). Therefor all requests will get all the cookies. Cookies with several KB are really nothing special. So, I think the default should be at least 4-8KB.

Currently I work around it with a HAProxy config:
`reqidel ^Cookie:.*`

**Comment by memoryhole** [comment]
It doesn't looks like this made it into a release. What would it take to get it there?

**Comment by ralight** [comment]
@memoryhole I'm pleased to say it is in version 1.6 (so I'm closing this now).
