### ISSUE TITLE
Upgrade from rel 1.6.3 to 2.0.7 KO - Websocket/SSL not started

### ISSUE THREAD

**Issue by arzaman** [eclipse/mosquitto#2083]
Hi 

I have performed and upgrade of my old mosquitto release from rel 1.6.3 to the last one on Ubuntu server  18

```
sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa
sudo apt-get update
sudo apt-get install mosquitto
```

this is installed version
```
apt-cache policy mosquitto
 Installed: 2.0.7-0mosquitto1~bionic1
 Candidate: 2.0.7-0mosquitto1~bionic1
```

these are the log errors
```
1612963521: Error: Unable to create websockets listener on port 8083.
1612963522: Error: Unable to create websockets listener on port 8083.
1612963523: Error: Unable to create websockets listener on port 8083.
1612963524: Error: Unable to create websockets listener on port 8083.
1612963525: Error: Unable to create websockets listener on port 8083.
```

I have struggled to fix some issue with erro on PID file writing but finally I fix it 
but never the less mosquitto does not strart if I try to **eneable websoket port over SSL**

this is my mosquitto conf file

```
pid_file /var/run/mosquitto/mosquitto.pid

allow_anonymous false

password_file /etc/mosquitto/passwordfile
persistence true
persistence_location /var/lib/mosquitto/


include_dir /etc/mosquitto/conf.d
log_type error
log_dest file /var/log/mosquitto/mosquitto.log


listener 1883
listener 1884
listener 9001
protocol websockets
listener 8083
protocol websockets
# socket_domain ipv4


certfile /etc/letsencrypt/live/mydomain.com/cert.pem
cafile /etc/letsencrypt/live/mydomain.com/chain.pem
keyfile /etc/letsencrypt/live/mydomani.com/privkey.pem
```

this is my netstat -lnt output
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:1884            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 :::1883                 :::*                    LISTEN
tcp6       0      0 :::443                  :::*                    LISTEN
tcp6       0      0 :::1884                 :::*                    LISTEN
tcp6       0      0 :::9001                 :::*                    LISTEN
tcp6       0      0 :::80                   :::*                    LISTEN
tcp6       0      0 :::8083                 :::*                    LISTEN
tcp6       0      0 :::21                   :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN

```

I try also to rollback to previous version but I got an error !!

sudo apt-get install mosquitto=1.6.3-0mosquitto1~jessie1

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mosquitto : Depends: libwebsockets3 (>= 1.2) but it is not installable
E: Unable to correct problems, you have held broken packages.

```

I guess there some error in the libwebsocket dependencies but I'm stuk...no way to make websocket work neither to roll back 

```
apt-cache policy libwebsockets-dev
libwebsockets-dev:
  Installed: 2.4.2-0~mosquitto1~bionic1
  Candidate: 2.4.2-0~mosquitto1~bionic1

```

any help how to exit this situation is appreciated
br
Davide

**Comment by ralight** [comment]
I'm not sure, but it is possible this is because the files in `/etc/letsencrypt/live/mydomain.com/` are not accessible by the mosquitto user. There is a script available to use as a letsencrypt hook to copy the scripts to a convenient place: https://github.com/eclipse/mosquitto/blob/master/misc/letsencrypt/mosquitto-copy.sh

**Comment by arzaman** [comment]
thanks @ralight to coming back to me...I'm really deeply in the fog struggling since yesterday to exit the dead lock
I will for sure check the installation of certificates but just few other elments

-it was working perfectly before the upgrade , I did not change path or permission , I just update in the mosquitto.conf file the path for the  PID file

-I try to to roll back to my old version 1.6.3 but i continue to get error mosquitto : Depends: libwebsockets3 (>= 1.2) but it is not installable

-I succeed now to roll back to  1.6.8-0mosquitto1~jessie1  ,  the brokers starts and works fine ony if I comment in the conf file the "protocol websockets"  , as soon as I try to activate the websocket the mosquitto crashes 

-I also update libwesockets
```
sudo apt-get install libssl-dev
sudo apt-get install libwebsockets-dev
```

than frustrated I remove/purge all (including libwebsokets) and re-install from scratch but neither version 2.0.7 nor 1.6.8 works for me with websocket active
```
sudo apt-get purge --remove mosquitto*
sudo apt-get purge --remove libwebsockets-dev*

```
don't really know what to try more :-(
most likely all this attempts creates some mess ..really need a direction to go... to clean everything and re-install with websocket support

sure of your support
br
Davide

**Comment by arzaman** [comment]
Hi 

I fixed somehow the issue...not sure of the root cause but now seems working
here what  I did

1) forced the binding of websocket port 8083 to IPV4 address (with old mosquitto version this was not needed)
```
listener 8083
protocol websockets
socket_domain ipv4
```

and now mu netstat -lnt
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8083            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 :::443                  :::*                    LISTEN
tcp6       0      0 :::1883                 :::*                    LISTEN
tcp6       0      0 :::80                   :::*                    LISTEN
tcp6       0      0 :::21                   :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
```


2) moved my certificates in different directory

```
#certfile /etc/letsencrypt/live/mydomain.com/cert.pem
#cafile /etc/letsencrypt/live/mydomain.com/chain.pem
#keyfile /etc/letsencrypt/live/mydomain.smartpid.com/privkey.pem
certfile /etc/mosquitto/certs/cert.pem
cafile /etc/mosquitto/ca_certificateschain.pem
keyfile /etc/mosquitto/certs/privkey.pem
```

any explanation for that? otherwise you can close the case

thanks
Davide

**Comment by paynor** [comment]
I have the same problem with v. 1.6.12 on Debian 8.
Works fine on port 1883 with SSL - with certs in the letsencrypt/live directory - so read rights are not the problem.
But as soon as 
`listener 8083
protocol websockets`
is added to the conf file, mosquitto does not restart. 
With  just
`listener 8083`
followed by certfile etc., mosquito does restart. It is really the websockets protocol line that causes the problem.
Suggestions?

**Comment by bahientn9x** [comment]
try it, it is woking now

`
sudo apt-get install build-essential python quilt python-setuptools python3
sudo apt-get install libssl-dev
sudo apt-get install cmake
sudo apt-get install libc-ares-dev
sudo apt-get install uuid-dev
sudo apt-get install daemon
sudo apt-get install libwebsockets-dev
`

in mosquitto.conf 

`
listener 1883 
protocol mqtt
listener 8083
protocol websockets
`

and restart mosquitto

**Comment by ralight** [comment]
> #certfile /etc/letsencrypt/live/mydomain.com/cert.pem
> #cafile /etc/letsencrypt/live/mydomain.com/chain.pem
> #keyfile /etc/letsencrypt/live/mydomain.smartpid.com/privkey.pem
> certfile /etc/mosquitto/certs/cert.pem
> cafile /etc/mosquitto/ca_certificateschain.pem
> keyfile /etc/mosquitto/certs/privkey.pem
> 
> any explanation for that? otherwise you can close the case

@arzaman version 2.0 doesn't operate as root when trying to open certificates, so that's why the certificates in `/etc/letsencrypt/live` are causing problems. You can use a certbot hook to copy your certificates and tell the broker to reload them: https://github.com/eclipse/mosquitto/blob/master/misc/letsencrypt/mosquitto-copy.sh

**Comment by ralight** [comment]
@bahientn9x I can't imagine why those changes would have worked for you, but I'm glad you've got it sorted.
