### ISSUE TITLE
How do I unsubscribe to a topic?

### ISSUE THREAD

**Issue by danielserra98** [eclipse/mosquitto#2084]
Hi,
I want to know what command do I have to use to unsubscribe a sub for a certain topic. I used the following command to subscribe  to 2 topics:

~$ mosquitto_sub -t 'A/B' -t 'A/C' -h localhost -c -i zxcvbnmñlkjhgfdsaq -q 2

Now, if I want to unsubscribe from topic 'A/B' what do I have to do?

Also, if I use a clean session do I allways have to disconnect the subscriber to unsubscribe or subscribe to an other topic? 

Thank you!

**Comment by mosterdt** [comment]
Hi danielserra98,

I think you might be reaching the edge of what you can do with the command line tool, and maybe want to look into writing a client that does exactly what you want. You could take a look at Paho (another eclipse project) to do this in any (most) languages: https://www.eclipse.org/paho/index.php?page=downloads.php

**Comment by ptjm** [comment]
You could also use the -U option to mosquitto_sub. I think if you just connect using the same client ID but without the -c flag, it should also unsubscribe everything.

~$ mosquitto_sub -U'A/B' -h localhost -c -i zxcvbnmñlkjhgfdsaq -q 2

**Comment by ralight** [comment]
It looks like this has been resolved in one way or another, so I'm closing this issue.
