### ISSUE TITLE
Websocket listeners are always bound to all addresses

### ISSUE THREAD

**Issue by wille-io** [eclipse/mosquitto#2085]
Hi,

I want to be able to have a (secured) MQTT port, plus a (secured) WebSocket port. 
The MQTT listener was created correctly (localhost on port 9990), but the WebSocket port was not. Instead of binding to 127.0.0.1, it binds to all addresses.

First I used Ubuntu 20.04's version of mosquitto (mosquitto (1.6.9-1)), but because I thought this was a bug in 'an old version' I compiled release 2.0.7 from the releases page (of course with ws support) for myself, but the behaviour is the same.

That's how I tried to implement the configuration:

/etc/mosquitto/mosquitto.conf
```
per_listener_settings true


listener 9990 127.0.0.1
protocol mqtt
connection_messages true


listener 9991 127.0.0.1
protocol websockets
connection_messages true


log_dest stdout
log_type debug
```

How I started mosquitto:
```
$ mosquitto -c /etc/mosquitto/mosquitto.conf -v
1613061604: mosquitto version 2.0.7 starting
1613061604: Config loaded from /etc/mosquitto/mosquitto.conf.
1613061604: Opening ipv4 listen socket on port 9990.
1613061604: Opening websockets listen socket on port 9991.
1613061604: mosquitto version 2.0.7 running
```

Unfortunately, that's what `ss` is telling me:
```
$ sudo ss -tlpn | grep mosquitto
LISTEN 0      100                            127.0.0.1:9990        0.0.0.0:*     users:(("mosquitto",pid=2597824,fd=4))                                         
LISTEN 0      128                                    *:9991              *:*     users:(("mosquitto",pid=2597824,fd=8)) 
```

What did I miss? 

Thank you.

**Comment by ralight** [comment]
The websockets library only works with interfaces, not IP addresses, so  if you use `lo` instead of `127.0.0.1` for the websockets listener it should work ok:

```
per_listener_settings true


listener 9990 127.0.0.1
protocol mqtt
connection_messages true


listener 9991 lo
protocol websockets
connection_messages true


log_dest stdout
log_type debug
```

**Comment by wille-io** [comment]
That works, thank you!
