### ISSUE TITLE
Include Dynamic Security Plugin in the conf man page

### ISSUE THREAD

**Issue by YerayAlonso** [eclipse/mosquitto#2089]
If I understand it correctly, the [Dynamic Security Plugin](https://mosquitto.org/documentation/dynamic-security/) introduced in v2 is an improvement over the `password_file` and `acl_file` options.

However, I see no mention about this plugin in the [conf man page](https://mosquitto.org/man/mosquitto-conf-5.html).

**Comment by ralight** [comment]
Yes you're right.
