### ISSUE TITLE
using pattern in acl-file without %c or %u gives unwanted permissions

### ISSUE THREAD

**Issue by bitfreak25** [eclipse/mosquitto#209]
I've wrote a acl-file like this:

```
pattern read #

user Student
pattern readwrite #

user Global
pattern readwrite #
```

and created the 2 users "Student" and "Global". I expected, that a anonymous user could only read the topics, but he cloud write to it.

Changing the acl-file to something like this solved the problem:

```
topic read #

user Student
topic readwrite #

user Global
topic readwrite #
```

I've see that I've done a bad mistake, but it confused me, that there was no error or something. So, is it possible to give an error with a wrong acl-file or if better a implementation, that lets "pattern" work like "topic" if there is no %c or %u ?

**Comment by ralight** [comment]
I'm not sure what the best thing to do here would be. Your original ACL isn't *wrong*, just not very useful. Perhaps it would be best to produce an error if there isn't a `%c` or `%u` in the pattern.

**Comment by ralight** [comment]
This now rejects patterns that do not contain %c or %u.

**Comment by mikini** [comment]
Commit ecb4006f388c18bbc997d9e3ac45fe8f52775e35 changes the rejection to just emitting a warning. Also see a real world use case discussed in [this mailing list thread](https://dev.eclipse.org/mhonarc/lists/mosquitto-dev/msg01862.html).
