### ISSUE TITLE
Mosquitto no longer allows privileged ports without escalation

### ISSUE THREAD

**Issue by rssk** [eclipse/mosquitto#2098]
I just upgraded to `v2.0.7` on an ubuntu `18.04` machine and I can't seem to bind to privileged ports without escalating the entire service to root via the `user root` config option. Is this the intended method for those of us who need port usage below 1000?

```
root@-------:/root#  lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
root@-------:/root# mosquitto -p 80
1614053033: mosquitto version 2.0.7 starting
1614053033: Using default config.
1614053033: Starting in local only mode. Connections will only be possible from clients running on this machine.
1614053033: Create a configuration file which defines a listener to allow remote access.
1614053033: Opening ipv4 listen socket on port 80.
1614053033: Error: Permission denied
1614053033: Opening ipv6 listen socket on port 80.
1614053033: Error: Permission denied
root@-------:/root#
```

**Comment by Paraphraser** [comment]
To get the previous behaviour, you need a configuration file with at least:

```
listener 1883
allow_anonymous true
```

The omission of the `listener 1883` explains the "Starting in local only mode. Connections will only be possible from clients running on this machine."

`allow_anonymous true` is appropriate if you don't have an existing password file.

See [Migrating to Mosquitto 2.0](https://mosquitto.org/documentation/migrating-to-2-0/)

See also [SensorsIot/IOTstack issue 265](https://github.com/SensorsIot/IOTstack/issues/265).

**Comment by rssk** [comment]
Hey @Paraphraser thanks for the response, but the issue isn't that I can't get clients to connect. I can get clients to connect fine with the migration config changes, the problem is that in order to get mosquitto running on a privileged port I _have_ to use `user root` in the config even running the initial command as root. 

Previously mosquitto would bind ports and deescalate, there are mentions of some changes to this in the migration, but there isn't any mention of it affecting port binding. 

It just seemed odd to require use of `root` for this use case with the migration guide warning `It is still possible to force Mosquitto to run as root, but this is strongly recommended against.`

**Comment by ralight** [comment]
You could use the capability system to do this. Processes with the `CAP_NET_BIND_SERVICE` capability can bind to privileged ports without root.

```
sudo setcap 'CAP_NET_BIND_SERVICE=+ep /usr/sbin/mosquitto' 
```

**Comment by rssk** [comment]
> You could use the capability system to do this. Processes with the `CAP_NET_BIND_SERVICE` capability can bind to privileged ports without root.
> 
> ```
> sudo setcap 'CAP_NET_BIND_SERVICE=+ep /usr/sbin/mosquitto' 
> ```

This ended up working out, thanks for the tip! 

There were a still a couple of issues to overcome that might help someone else in this position.
Oddly, the mosquitto service still can't start and bind ports starting as the root user, no clue why. However running as the `mosquitto` user works fine, and modifying the systemd script `ExecStartPre` permissions gets around mkdir/chown issues:

```
[Unit]
Description=Mosquitto MQTT Broker
Documentation=man:mosquitto.conf(5) man:mosquitto(8)
After=network.target
Wants=network.target

[Service]
Type=notify
NotifyAccess=main
User=mosquitto
ExecStart=/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
ExecStartPre=+/bin/mkdir -m 740 -p /var/log/mosquitto
ExecStartPre=+/bin/chown mosquitto: /var/log/mosquitto
ExecStartPre=+/bin/mkdir -m 740 -p /var/run/mosquitto
ExecStartPre=+/bin/chown mosquitto: /var/run/mosquitto

[Install]
WantedBy=multi-user.target
```
I'm not sure these setup modifications are mosquitto's responsibility, but I think either some mention in the migration guide or readme would be helpful

**Comment by ralight** [comment]
Hmm, yes it seems that dropping privileges with setuid also drops the capabilities that have been set.

**Comment by annlumia** [comment]
On my case:


```sh
mkdir ~/.config/systemd/user
cp /lib/systemd/system/mosquitto.service ~/.config/systemd/user/mosquitto.service
nano ~/.config/systemd/user/mosquitto.service
```

and put comment flag before ExecStartPre

```txt
[Unit]
Description=Mosquitto MQTT Broker
Documentation=man:mosquitto.conf(5) man:mosquitto(8)
After=network.target
Wants=network.target

[Service]
Type=notify
NotifyAccess=main
ExecStart=/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
#ExecStartPre=/bin/mkdir -m 740 -p /var/log/mosquitto
#ExecStartPre=/bin/chown mosquitto: /var/log/mosquitto
#ExecStartPre=/bin/mkdir -m 740 -p /var/run/mosquitto
#ExecStartPre=/bin/chown mosquitto: /var/run/mosquitto

[Install]
WantedBy=multi-user.target
```

save, and then continue with:

```sh
sudo chmod 777 /var/log/mosquitto/mosquitto.log
sudo chmod 777 /var/run/mosquitto
sudo systemctl stop mosquitto
sudo systemctl disable mosquitto
systemctl --user start mosquitto
systemctl --user enable mosquitto
```
