### ISSUE TITLE
can mosquitto run in specifical cpu core?

### ISSUE THREAD

**Issue by linxingyang** [eclipse/mosquitto#2105]
HI.

since mosquitto is single-thread thus using only one core. so in our case,  the rest of cores(let's say 3 of 4 cores) has nothing to do while one core is busy. 
my test result: with 20K connections,  every connection publish 0.5K per-second, the CPU up to 100%, we are aim to more connections, for now we want 100K at least.

so my question is:
can we specifical a mosquitto instance running in a specifcal core? if so we can start up four mosquitto instances in our server and four mosquitto instances runing in four cores(minimum our deploy cost). 

or in another way:
will a mosquitto instance automatic choose a idle core that no other mosquitto instance take up? if so we can start up four mosquitto instances in our server and all four mosquitto use different core(like former example).

i guess you understand our attention, so if there have other ideas can achive the same purpose,  we are glad to try it too.

hope for you help, thanks.
linxy

**Comment by ralight** [comment]
This is entirely down to the scheduler of your operating system. If you run four instances I am quite sure that your operating system will share them out between all four cores.

Please do make sure you are using version 2 instead of 1.6, there were a lot of performance improvements.

**Comment by bahientn9x** [comment]
Try upgrading to version 2.0. After I got to version 2.0 my CPU resources dropped a lot, with 7000 connections but the CPU is almost at rest

**Comment by bahientn9x** [comment]
Try upgrading to version 2. After I got to version 2 my CPU resources dropped a lot, with 7000 connections but the CPU is almost at rest

**Comment by linxingyang** [comment]
thank you guys.

I using the newest mosquitto version(2.0.6) and do some tests these days.

now my test result:  with 40K connections, every connection publish 0.5K per-second, the CPU up to 100% (when add to 43K connections, some clinets start disconnect).

so this is the different in my machine.
* mosquitto 1.6.12   20K+ connections
* mosquitto 2.0.6     40K+ connections
do a great performance improvements in version 2.

but i see a weird phenomenon while doing test:
1、start 5K clients in a test(same publish speed in all my test case : 0.5K per-second), i can see the CPU up to 100%(or 95+%).
2、CPU keep at 100% for a few minutes.
3、start 35K client in another test (CPU is still 100% now), those clients still connect success and no connection disconnect.

so
1、why CPU up to 100% when just 5K clients connected? (sometimes 5K clients take low CPU, so i don't understand why that occur now and then, the machine that running mosquitto just for test and don't work for other programs.)
2、why when CPU is 100% clients still connect success?
is this normal? 

thanks again.
linxy.

**Comment by bahientn9x** [comment]
> thank you guys.
> 
> I using the newest mosquitto version(2.0.6) and do some tests these days.
> 
> now my test result: with 40K connections, every connection publish 0.5K per-second, the CPU up to 100% (when add to 43K connections, some clinets start disconnect).
> 
> so this is the different in my machine.
> 
> * mosquitto 1.6.12   20K+ connections
> * mosquitto 2.0.6     40K+ connections
>   do a great performance improvements in version 2.
> 
> but i see a weird phenomenon while doing test:
> 1、start 5K clients in a test(same publish speed in all my test case : 0.5K per-second), i can see the CPU up to 100%(or 95+%).
> 2、CPU keep at 100% for a few minutes.
> 3、start 35K client in another test (CPU is still 100% now), those clients still connect success and no connection disconnect.
> 
> so
> 1、why CPU up to 100% when just 5K clients connected? (sometimes 5K clients take low CPU, so i don't understand why that occur now and then, the machine that running mosquitto just for test and don't work for other programs.)
> 2、why when CPU is 100% clients still connect success?
> is this normal?
> 
> thanks again.
> linxy.

how can you test such a large number of clients

**Comment by linxingyang** [comment]
i was test with [jMeter](https://jmeter.apache.org/) and [jmeter mqtt plugin](https://github.com/xmeter-net/mqtt-jmeter).

> My server is only using 1-10% CPU with 7000 connections.

yeah, i think CPU should increase with connections increase, so what i see confuse me, now when i see the CPU is 100% i'm not sure is it run out the resource.

linxy.

**Comment by bahientn9x** [comment]
> i was test with [jMeter](https://jmeter.apache.org/) and [jmeter mqtt plugin](https://github.com/xmeter-net/mqtt-jmeter).
> 
> > My server is only using 1-10% CPU with 7000 connections.
> 
> yeah, i think CPU should increase with connections increase, so what i see confuse me, now when i see the CPU is 100% i'm not sure is it run out the resource.
> 
> linxy.

I will experiment with my server to evaluate performance. I'll tell you

**Comment by linxingyang** [comment]
That will be great help, thank you.

linxy.

**Comment by ralight** [comment]
The number of connections doesn't matter too much, on Linux at least. What matters more is the incoming and outgoing message rate.

**Comment by linxingyang** [comment]
Agree with you, before doing tests i was search for some test results as reference and I see you viewpoint at [mqtt-mosquitto-linux-connection-limit](https://stackoverflow.com/questions/10087396/mqtt-mosquitto-linux-connection-limit).
but we still have to estimate the maximum clients number under specical incoming and outgoing message rate (in our case,  the clients maximum publish size/speed is limited),  so we can estimate how many servers(mosquitto instances)  we need when we suppose to support eg: 100K clients.

linxy.

**Comment by ralight** [comment]
That was nearly ten years ago :)

This is more recent: https://twitter.com/MosquittoMQTT/status/1336725848938979328

Again, the clients there are doing nothing in terms of publishing - maintaining idle connections is "easy". If each of those 1 million clients were publishing one message per second it'd be overloaded.

**Comment by bahientn9x** [comment]
> That was nearly ten years ago :)
> 
> This is more recent: https://twitter.com/MosquittoMQTT/status/1336725848938979328
> 
> Again, the clients there are doing nothing in terms of publishing - maintaining idle connections is "easy". If each of those 1 million clients were publishing one message per second it'd be overloaded.

So if the server has a CPU processing speed of 2.6Ghz, it can load how many users send messages per second. And is there any plan for the case if the limit is already reached. Thanks

**Comment by linxingyang** [comment]
> And is there any plan for the case if the limit is already reached. My client base is increasing and I worry it will reach its limit.

It's my concern too, we want cluster deploy plan, but for now mosquitto only support bridge mode, i already tried that, but afraid the vulnerable of center node.

linxy.

**Comment by linxingyang** [comment]
> That was nearly ten years ago :)
>
> This is more recent: https://twitter.com/MosquittoMQTT/status/1336725848938979328
>
> Again, the clients there are doing nothing in terms of publishing - maintaining idle connections is "easy". If each of those 1 million clients were publishing one message per second it'd be overloaded.

1 million clients in a mosquitto instance are impressive, now my goal is achive 1 million clients in mosquitto cluster(does not have any cluster plan/advice yet). 
nginx + moquitto can provide load balance but no idea for communicate between mosquitto instance inside mosquitto cluster, any advices?

linxy.

**Comment by ralight** [comment]
You will probably find that to a degree it is the overall number of messages per second that is the limiting factor rather than the number of clients of message size.

**Comment by linxingyang** [comment]
But it will get different number of messages per second when we pulibsh in different rate, such as 128KB/S and 1024KB/S.
Am i misunderstand? 

linxy.

**Comment by linxingyang** [comment]
I test today that publish in 128KB/S and 1024KB/S, thay have similiar max clients number, is that what you mean 
> number of messages per second that is the limiting factor

linxy.

**Comment by ralight** [comment]
What I means is that you are more likely to find a limit in terms of the number of messages sent/received per second than on the raw bandwidth per second. This is likely to be true to a degree, it doesn't cover all cases. But in your case if you a client trying to send 1,024,000 small messages per second compared to a client trying to send a single 1,024,000 byte message per second you will almost certainly see a difference.
