### ISSUE TITLE
Documented location of example conf file is wrong in default conf file under /etc

### ISSUE THREAD

**Issue by Nodi-Rubrum** [eclipse/mosquitto#2108]
Documented location of example file is wrong in conf file under /etc/mosquitto/mosquitto.conf.  Text in file reads...

\# A full description of the configuration file is at
\# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

The above file reference is bogus.  No such file found after installation.

Appears there is no example conf file at all?

\# find / | grep mosquitto | grep example
/usr/share/doc/mosquitto/examples
/usr/share/doc/mosquitto/examples/pskfile.example
/usr/share/doc/mosquitto/examples/aclfile.example
/usr/share/doc/mosquitto/examples/mosquitto.conf.gz
/usr/share/doc/mosquitto/examples/pwfile.example

\# find /etc | grep mosquitto | grep example
(no result)

\# find /etc | grep mosquitto | grep conf
/etc/mosquitto/conf.d
/etc/mosquitto/conf.d/README
/etc/mosquitto/conf.d/local.conf
/etc/mosquitto/mosquitto.conf

So where is the example file for the actual conf file?

**Comment by ralight** [comment]
Thanks for pointing this out. You did manage to find the examples directory, the name is just slightly different: `/usr/share/doc/mosquitto/examples/mosquitto.conf.gz`

**Comment by ralight** [comment]
This will be fixed in the next debian packages.

**Comment by dachshund-digital** [comment]
Cool.  And yes, I did find the examples in due course.
