### ISSUE TITLE
Behavior of tls_version

### ISSUE THREAD

**Issue by vertecx** [eclipse/mosquitto#2110]
I still seem to have the old behavior of the tls_version option specifying the only supported TLS version, instead of the minimum version, when running the broker version 2.0.8 on Windows. I have not tried on other platforms.

I have tried connecting with different TLS versions using `openssl s_client -tls1_X -connect localhost:8883` and I can only connect using the exact version specified in tls_version. Unless not specifying tls_version at all, then I can use TLS 1.1, 1.2 and 1.3.

Could it be that the changes made to `lib/net_mosq.c` in commit abbeb4494fc5d4691a0a9e117358d7a42dabd995 must also be made in `src/net.c` around line 332? The TLS version code there seems very similar to the old net_mosq code and seems to match the behavior I am seeing when running the broker.

**Comment by ralight** [comment]
Thank you, well spotted. That should have been changed at the same time as the client library, and I honestly thought I had done it. It's fixed now and will be part of the next bug fix release.
