### ISSUE TITLE
Question about Mosquitto Logs

### ISSUE THREAD

**Issue by mike-sandstrom** [eclipse/mosquitto#2112]
Hello, 

I downloaded Mosquitto on a linux server with no open ports aside 22/ssh. I have not used Mosquitto for anything  since it was downloaded a few days ago. However, I have about 50+ messages spanning 2-3 days saying `Saving in-memory database to /var/lib/mosquitto//mosquitto.db`. Could anyone provide information about what exactly this is saying. I haven't created a topic, subscribed to any, nor have I published any messages.

**Comment by jsaak** [comment]
This is normal behaviour, you can read it more in the docs if you search for persistence. The server stores it state to a file periodically, even when no client ever connected to it.

**Comment by mike-sandstrom** [comment]
> This is normal behaviour, you can read it more in the docs if you search for persistence. The server stores it state to a file periodically, even when no client ever connected to it.

Thank you!
