### ISSUE TITLE
How to properly implement MQTTv3.1.1 client QoS 1 and Qos2?

### ISSUE THREAD

**Issue by jsaak** [eclipse/mosquitto#2113]
My question is How to properly implement MQTTv3.1.1 client QoS 1 and Qos2? 
The reason i ask this question publicly is because, other implementations can learn from it.
I know  that there is a specification: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html
But we all know it is not perfect.

So MQTT is running on TCP.
As long as we have a TCP connection open TCP guarantees a lot of things. There will be no lost data, no duplications, and data will be in sent order. That means that re-sending packets does not make sense.

Things change when we lose the TCP connection. In that case it is reasonable to resend those PUBLISH packets, since we know that the other side will not get it any other way.

So I think the correct functionality is something like this:
1. User wants to PUBLISH something.
2. Client stores the message if QoS > 0.(In memory and to file maybe)
3. Client sends PUBLISH if TCP is connected, and MQTT is connected too.
4. When Server answers with PUBACK or PUBREC, we remove the stored PUBLISH. (in case of QoS 2 we need PUBREL and PUBCOMP first, but that does not change anything)
5. If Server does not respond, then we wait as long as the TCP connection is open.
6. If Client gets TCP  disconnect, then we try to connect again, and when successful, we resend the stored PUBLISH messages.

If we agree that this is the correct functionality, then that means that QoS 2 does not make any sense.

What do you think?
Also i am not familiar with MQTT v5, is there an improvement there?

**Comment by jsaak** [comment]
I see that they fixed this in MQTT 5. So what do you suggest, what is a good strategy for writing MQTTv3.1.1 client which uses only mosquitto? Shall I implement it like v5 and ignore the v3 spec?

**Comment by ralight** [comment]
I'm not quite sure what the question is. Your 1-6 list is what happens in 3.1.1 and 5.0. The reason for QoS 2 is that when using QoS 1 you can't be sure where the error occurred if you don't receive a PUBACK. If the server received the PUBLISH and sent you a PUBACK, but your connection failed before it arrived to you, then when you reconnect you will generate a duplicate message.

**Comment by jsaak** [comment]
i got confused.

As i see the main difference between v3 and v5 is that in v3 the client was allowed to retry (while TCP connected), and in v5 it is not allowed any more.
So if i write a v3 client which does not retry then i am following the spec.
(and if i support v5 then i have not to touch it)

Do you agree?

**Comment by ralight** [comment]
You're correct that the v3 spec does forbid retrying, but any implementations doing that are broken in my opinion. So yes, if you are writing a new client/library today I would not implement retry.

**Comment by jsaak** [comment]
Thank you for your feedback!
I am guessing you do not want to merge a ruby mqtt client to mosquitto, right?
