### ISSUE TITLE
MOSQ_ERR_NOT_FOUND

### ISSUE THREAD

**Issue by 120616003** [eclipse/mosquitto#2114]
mqtt 1.4.8
_mosquitto_message_out_update funtion's mosq->out_messages is null
function return MOSQ_ERR_NOT_FOUND
What causes this?

**Comment by ralight** [comment]
Without looking at the source (that version is now years old and out of date), I would guess that it means the message you were trying to update in _mosquitto_message_out_update() wasn't found.

**Comment by 120616003** [comment]
I've solved this problem, because the lower version of the library will cause the connection to exit for processing messages that have been sent but have not been confirmed
