### ISSUE TITLE
Dos `$SYS/broker/heap/current` collect wrong size?

### ISSUE THREAD

**Issue by blusewang** [eclipse/mosquitto#2116]
My mosquitto is compile on FreeBSD12, from `github` source `fixes` branch few days ago, and use my custom plugin and `libwebsockets v2.4.2`.
After `mosquitto` start, the memory usage grow up hour by hour. now `$SYS/broker/heap/current` return size is bigger than top both `SIZE` and `RES` size.
```
bluse@mbp.jf ~ $ mosquitto_sub -i cli -q 1 -L 'mqtts://myhost/$SYS/broker/heap/current' -v
$SYS/broker/heap/current 43190536
```
![image](https://user-images.githubusercontent.com/1764005/110202899-5aebb600-7ea6-11eb-8d28-a018a80ecfc2.png)

But in `top` memory usage is :
```
  PID USERNAME    THR PRI NICE   SIZE    RES STATE    TIME    WCPU COMMAND
21264 daemon        1  20    0    23M    11M select   2:14   0.14% /usr/local/sbin/mosquitto -c /usr/local/etc/mosquitto/mosquitto.conf
```

**Comment by ralight** [comment]
It could be! As you know this wasn't available on FreeBSD until very recently so it wouldn't surprise me if there was something wrong. First things first though - does your plugin call `free()` on any memory given to it by the broker? If there is a mismatch between mosquitto_malloc/mosquitto_free and malloc/free then the memory use will become out of sync.

**Comment by blusewang** [comment]
so that's it! thanks
