### ISSUE TITLE
Cannot establish more than 2047 connections in Windows

### ISSUE THREAD

**Issue by yellowgg2** [eclipse/mosquitto#2122]
Hello,

I am using 2.0.8 version Windows binary downloaded from https://mosquitto.org/download/

Looks like 1.6.9 version Windows binary can establish over 2047 connections. It happens with 2.0.x version

Once I tested on Linux machine, it can establish over 3000 connections. But with Windows, it cannot establish more than 2047.

I've changed Registry on Windows machine instructed [here](https://docs.oracle.com/cd/E26180_01/Search.94/ATGSearchAdmin/html/s1207adjustingtcpsettingsforheavyload01.html)

And also I set `max_connections` to `-1` in `mosquitto.conf`, but still no luck.

Is this OS specific limitation? or is there a configuration to increase the connections in conf file?

Thank you!

**Comment by ralight** [comment]
The old limitation of Windows low level connections was 2048. You won't have been able to open more than that in 1.6.9. Windows has increased the limit to 8192 at some point. I've just pushed a change that takes advantage of that.

**Comment by yellowgg2** [comment]
Thank you for your help!

**Comment by ralight** [comment]
I've improved the Windows installer a bit, and rebuilt it with support for 8192 clients at the same time, so if you get the 2.0.9a installer it supports the higher number.

**Comment by yellowgg2** [comment]
I've tested the update and it works great! Thank you so much for your help!

**Comment by ralight** [comment]
Great! Thanks for reporting back.
