### ISSUE TITLE
dynsec init: Out of memory. Error: Out of memory when mosquitto_ctrl dynsec init

### ISSUE THREAD

**Issue by tennessine** [eclipse/mosquitto#2129]
<img width="1126" alt="QQ20210311-184944@2x" src="https://user-images.githubusercontent.com/4545879/110776072-9d443700-829a-11eb-91a4-0918ee8e7abb.png">

**Comment by tennessine** [comment]
I tested on 3 centos server, got the same error.

**Comment by tennessine** [comment]
I found cJSON_CreateObject returns NULL, but I don't know why.

**Comment by tennessine** [comment]
![Uploading QQ20210311-213610@2x.png…]()

**Comment by tennessine** [comment]
<img width="915" alt="QQ20210311-213610@2x" src="https://user-images.githubusercontent.com/4545879/110795554-ef448700-82b1-11eb-8ef9-0dfb6181be37.png">

**Comment by tennessine** [comment]
I tested on ubuntu desktop 20, it's ok.

**Comment by tennessine** [comment]
Could someone test mosquitto_ctrl dynsec init on centos 7/8 ?

**Comment by tennessine** [comment]
<img width="1375" alt="QQ20210312-014950@2x" src="https://user-images.githubusercontent.com/4545879/110833093-03e74600-82d7-11eb-8a5f-d9e25712cd8d.png">

**Comment by tennessine** [comment]
My gcc version is : gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

I'll use newest gcc to test again.

**Comment by tennessine** [comment]
I gave up

**Comment by tennessine** [comment]
<img width="838" alt="QQ20210312-144131@2x" src="https://user-images.githubusercontent.com/4545879/110902706-43e31300-8341-11eb-9bc4-7fa260fd2525.png">

**Comment by ralight** [comment]
Seems like this is a problem with the RHEL libraries. It's failing on a malloc()  for no reason. I'm not sure what I could do about that.
