### ISSUE TITLE
Mosquitto_rr client not available in mosquito-dev PPA

### ISSUE THREAD

**Issue by fuxoft** [eclipse/mosquitto#2132]
After adding the official mosquitto-ppa repository and doing `sudo apt install mosquitto mosquitto-clients`, mosquitto_rr is not installed (mosquitto_pub and mosquitto_sub are). Is this intentional? Mosquitto_rr is referenced in the official documentation.

**Comment by ralight** [comment]
Thank you. That should be fixed in the new packages available now.

**Comment by fuxoft** [comment]
Wow, that was fast! Thanks.
