### ISSUE TITLE
Build on Solaris x86

### ISSUE THREAD

**Issue by chuckunix** [eclipse/mosquitto#2136]
config.mk check SunOS version and implies SPARC-only compiler options by default(.
The proposed change tested on  x64  for 11.4 SRU29/gcc9
```
[oz]# diff config.mk config.mk.org 
145d144
<       ARCH:=$(shell uname -p)
203,204d201
<       SEDINPLACE:=    
<       ifeq ($(ARCH),sparc)
210,213c207
<       endif
<       ifeq ($(ARCH),i386)
<               LIB_CFLAGS:=$(LIB_CFLAGS) -fPIC 
<       endif
---



```
Rgds,
Dmitry.

**Comment by ralight** [comment]
Thank you, I don't have access to Solaris so it's difficult to test. Your patch doesn't apply however, could you perhaps use `diff -u` instead?

**Comment by chuckunix** [comment]
diff  -u config.mk.org config.mk
--- config.mk.org       2021-03-17 14:53:46.453956729 +0300
+++ config.mk   2021-03-22 08:14:14.194025894 +0300
@@ -142,6 +142,7 @@
 UNAME:=$(shell uname -s)
 
 ifeq ($(UNAME),SunOS)
+        ARCH:=$(shell uname -p)
        ifeq ($(CC),cc)
                CFLAGS?=-O
        else
@@ -199,11 +200,17 @@
 endif
 
 ifeq ($(UNAME),SunOS)
-       ifeq ($(CC),cc)
-               LIB_CFLAGS:=$(LIB_CFLAGS) -xc99 -KPIC
-       else
-               LIB_CFLAGS:=$(LIB_CFLAGS) -fPIC
-       endif
+        SEDINPLACE:=    
+        ifeq ($(ARCH),sparc)
+        ifeq ($(CC),cc)
+                LIB_CFLAGS:=$(LIB_CFLAGS) -xc99 -KPIC
+        else
+                LIB_CFLAGS:=$(LIB_CFLAGS) -fPIC
+        endif
+        endif
+        ifeq ($(ARCH),i386)
+                LIB_CFLAGS:=$(LIB_CFLAGS) -fPIC 
+        endif
 
        ifeq ($(CXX),CC)
                LIB_CXXFLAGS:=$(LIB_CXXFLAGS) -KPIC

**Comment by chuckunix** [comment]
"diff  -u config.mk.org config.mk
--- config.mk.org       2021-03-17 14:53:46.453956729 +0300
+++ config.mk   2021-03-22 08:14:14.194025894 +0300
@@ -142,6 +142,7 @@
 UNAME:=$(shell uname -s)
 
 ifeq ($(UNAME),SunOS)
+        ARCH:=$(shell uname -p)
        ifeq ($(CC),cc)
                CFLAGS?=-O
        else
@@ -199,11 +200,17 @@
 endif
 
 ifeq ($(UNAME),SunOS)
-       ifeq ($(CC),cc)
-               LIB_CFLAGS:=$(LIB_CFLAGS) -xc99 -KPIC
-       else
-               LIB_CFLAGS:=$(LIB_CFLAGS) -fPIC
-       endif
+        SEDINPLACE:=    
+        ifeq ($(ARCH),sparc)
+        ifeq ($(CC),cc)
+                LIB_CFLAGS:=$(LIB_CFLAGS) -xc99 -KPIC
+        else
+                LIB_CFLAGS:=$(LIB_CFLAGS) -fPIC
+        endif
+        endif
+        ifeq ($(ARCH),i386)
+                LIB_CFLAGS:=$(LIB_CFLAGS) -fPIC 
+        endif
 
        ifeq ($(CXX),CC)
                LIB_CXXFLAGS:=$(LIB_CXXFLAGS) -KPIC
"

**Comment by chuckunix** [comment]
> Thank you, I don't have access to Solaris so it's difficult to test. Your patch doesn't apply however, could you perhaps use `diff -u` instead?

diff  -u config.mk.org config.mk
--- config.mk.org       2021-03-17 14:53:46.453956729 +0300
+++ config.mk   2021-03-22 08:14:14.194025894 +0300
@@ -142,6 +142,7 @@
 UNAME:=$(shell uname -s)
 
 ifeq ($(UNAME),SunOS)
+        ARCH:=$(shell uname -p)
        ifeq ($(CC),cc)
                CFLAGS?=-O
        else
@@ -199,11 +200,17 @@
 endif
 
 ifeq ($(UNAME),SunOS)
-       ifeq ($(CC),cc)
-               LIB_CFLAGS:=$(LIB_CFLAGS) -xc99 -KPIC
-       else
-               LIB_CFLAGS:=$(LIB_CFLAGS) -fPIC
-       endif
+        SEDINPLACE:=    
+        ifeq ($(ARCH),sparc)
+        ifeq ($(CC),cc)
+                LIB_CFLAGS:=$(LIB_CFLAGS) -xc99 -KPIC
+        else
+                LIB_CFLAGS:=$(LIB_CFLAGS) -fPIC
+        endif
+        endif
+        ifeq ($(ARCH),i386)
+                LIB_CFLAGS:=$(LIB_CFLAGS) -fPIC 
+        endif
 
        ifeq ($(CXX),CC)
                LIB_CXXFLAGS:=$(LIB_CXXFLAGS) -KPIC

**Comment by chuckunix** [comment]
Good day,

[config.mk.diff.txt](https://github.com/eclipse/mosquitto/files/6180504/config.mk.diff.txt)

**Comment by ralight** [comment]
Thanks, that will be part of 2.0.10 shortly.
