### ISSUE TITLE
database support

### ISSUE THREAD

**Issue by Piranessi** [eclipse/mosquitto#2143]
Hello, is it possible to introduce new feature where ACL file could be replaced with mysql/mongodb?

I have heard about the plugin for auth but it would much easier if such functionality would be built-in mosquitto.

Or at least is there way to reload acl file without restarting whole mosquitto broker (I would like to not disconnect all devices).

**Comment by ralight** [comment]
I would suggest taking a look at the dynamic security plugin, it's part of the Mosquitto project even if it is a plugin: https://mosquitto.org/documentation/dynamic-security/ There's also the Management Center which gives you a web interface for controlling the dynsec plugin. It is open source but isn't part of the Mosquitto project: https://github.com/cedalo/management-center

If you really want mysql/mongodb then I would suggest taking a look at mosquitto-go-auth: https://github.com/iegomez/mosquitto-go-auth

I hope that helps.

**Comment by Piranessi** [comment]
@ralight thanks for answer. I have managed to get mosquitto-go-auth working.
I did not mosquitto dynamic-security and management center though. Management center seems to be very interesting topic.
Thanks again for hints.

**Comment by ralight** [comment]
Good to hear you got it working, I'm going to close this then.
