### ISSUE TITLE
How do I cross compile for ARM? 

### ISSUE THREAD

**Issue by kunalfleethawks** [eclipse/mosquitto#2146]
Hi Team,

I am looking for steps to cross compile mosquitto for custom linux board using poky linux. Can any one help me?

**Comment by karlp** [comment]
I find it pretty hard to believe that yocto doesn't have mosquitto in one of it's standard package sets?  Apparently it's in "meta-networking" so just add that, and then select mosquitto like anything else.... https://stackoverflow.com/questions/61095064/installing-mosquitto-on-yocto#61095900

**Comment by kunalfleethawks** [comment]
I was able to cross compile with latest yocto cross compiler.
