### ISSUE TITLE
regression: mosquitto_pub,sub fail @ client hello when PSK TLS used on port 8883

### ISSUE THREAD

**Issue by jetpax** [eclipse/mosquitto#2152]
tested to mosquitto broker setup for tls - psk from mosquitto_sub version 2.0.9 running on libmosquitto 2.0.9, (with no certificates) 

e.g
mosquitto_sub -h <host>  -p 8883 -t test --psk-identity <id> --psk <key>

fails at Client Hello, since no pre_shared_key Extension is transmitted to the broker

Using another port, eg 8884, proceeds to server hello and connects as expected
e.g
mosquitto_sub -h <host>  -p 8884 -t test --psk-identity <id> --psk <key>

in this case the pre_shared_key Extension is transmitted, which contains the PSK Identity

mosquitto_sub version 1.6.9 running on libmosquitto 1.6.9 connects fine using port 8883

Possibly related to changes in 2.0.0 - 2020-12-03
`- The mosquitto_sub, mosquitto_pub, and mosquitto_rr clients will now load
  OS provided CA certificates by default if `-L mqtts://...` is used, or if
  the port is set to 8883 and no other CA certificates are loaded.`

mosquitto_pub shows the same failure pattern

Seems like client_shared.c l.1266 should be something like 

`}else if(cfg->port == 8883 && !cfg->psk){`

**Comment by ralight** [comment]
Thank you, I've fixed that in the `fixes` branch. Your suggestion was correct, I've just done it slightly differently.

**Comment by jetpax** [comment]
Thank you for the quick fix, much more elegant!
