### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by PBearson** [eclipse/mosquitto#2163]
I was doing some fuzz testing and came across this bug that crashes Mosquitto (confirmed in 2.0.9 and 2.0.7). When a client sends a valid CONNECT packet followed by a malformed CONNACK packet, sometimes it crashes the broker due to a segmentation fault.

The payload: 101000044d5154540502003c03210014000029020001e000

How to replicate: 
`echo 101000044d5154540502003c03210014000029020001e000 | xxd -p -r | nc <host> <port>`

Proof:

Segfault:
![image](https://user-images.githubusercontent.com/11084018/113464489-1696fb80-93fb-11eb-80f6-5231eca6b0d1.png)

GDB info:
![image](https://user-images.githubusercontent.com/11084018/113464512-36c6ba80-93fb-11eb-8f2c-82a62d1509f8.png)

I can generate other payloads which trigger the same crash, in case they are needed. Let me know.

**Comment by ralight** [comment]
Thanks for the fuzzing and the report, I've just pushed a change to fix this and will be making a new release today.
