### ISSUE TITLE
Can mosquitto limit one client one cert ?

### ISSUE THREAD

**Issue by linxingyang** [eclipse/mosquitto#2169]
Hi.    
    I'm using cert from client connect to server, but one cert can use in many clients, i don't find any config item that can forbid duplicate cn (I was experience with OpenVPN, it's has a config item -- duplicate-cn -- uncomment this make one cert only use by one client ), is mosquitto has the same config?   or i need to write a plugin to implement such function?

linxy.

**Comment by ptjm** [comment]
require_certificate true
use_identity_as_username true
use_username_as_clientid true

This will set the username to the CN, then set the client ID to the user name. This will disconnect any current client with the same ID.

**Comment by linxingyang** [comment]
Thank you
It works for me, but like a little trick.

linxy.
