### ISSUE TITLE
Messaging queue

### ISSUE THREAD

**Issue by costagustavom** [eclipse/mosquitto#2174]
Hi, I'm new to mosquitto and i'm trying to create some kind of priority queue for the messages but i can't find how the queue is done. Can someone tell me in which function it's done?

**Comment by ralight** [comment]
Hi there. MQTT doesn't have the concept of priority queues, everything is published in order.

**Comment by costagustavom** [comment]
Thank you for your time. I know that it doesn't have the concept but I'm trying to make it just for study purpose. How mosquitto make sure it is published in order?

**Comment by sectokia** [comment]
They are stored using doubly linked lists (see for example the definition of DL_APPEND in deps/utlist.h)

You can see this implemented in src/database.c

**Comment by costagustavom** [comment]
That's exactly what I wanted! I'm already developing my idea. Appreciated
