### ISSUE TITLE
Client xxxxx has exceeded timeout, disconnecting

### ISSUE THREAD

**Issue by ikarthikeyank** [eclipse/mosquitto#2175]
A mosquitto client xxxxx is connected to localhost.
One more mosquitto client yyyy will be connected to Azure in a separate thread. 
The mosquitto client xxxxx subscribes the data from the localhost and pushes to a buffer. The client yyyy will get the data from the buffer and sends to Azure. 
I am working on a error handling where more than one client with same client id (yyyy) is trying to connect with Azure.

The two clients start to kick out each other.
Connecting
publishing to Azure
Disconnecting
.
.
Connecting
publishing to Azure
Disconnecting
.
.
.
But my issue is, after few minutes, I'm getting the error 

`Client xxxxx has exceeded timeout, disconnecting`

How does the client (yyyy) connecting to Azure affect the client connected to localhost?
I am not getting any disconnect callback for the client xxxxx.
It keeps hanging around.
Not disconnecting, not subscribing, not even sending PINREQ.

**Comment by ikarthikeyank** [comment]
mosquitto logs:

```
1618052495: New connection from ::1:38688 on port 1883.
1618052495: New client connected from ::1:38688 as xxxxx (p2, c1, k60).
1618053579: Saving in-memory database to /var/lib/mosquitto//mosquitto.db.
1618053579: Error saving in-memory database, unable to open /var/lib/mosquitto//mosquitto.db.new for writing.
1618053579: Error: Permission denied.
1618053824: Client xxxxx has exceeded timeout, disconnecting.
```


I am suspecting this. Everytime  Error saving in-memory database occurs, the client is exceeding timeout. Any relation to this?

**Comment by ikarthikeyank** [comment]
I'm using loop_forever. Looks like the loop_forever is not handling the connection properly. Let me try with loop_start once.

**Comment by ikarthikeyank** [comment]
I'm using `mosquitto_loop_forever`. Looks like the` mosquitto_loop_forever` is not handling the connection properly. Let me try with `mosquitto_loop_start` once.

**Comment by ralight** [comment]
It's a bit tricky to say anything without a minimal example of what you are doing. Mosquitto will always disconnect a client after it exceeds its keepalive time. I'd suggest starting simple - get each side of the client connection working correctly in separate programs, then try to combine them later.

**Comment by ikarthikeyank** [comment]
My keepalive is 60 seconds.
timeout in `mosquitto_loop_forever` is negative (-1) i.e default of 1000ms.

Mosquitto will always disconnect a client after it exceeds its keepalive time. But the log says 

`Client xxxxx has exceeded timeout, disconnecting. `

This client is neither disconnected nor connected even after 20 mins. 

It stays still. Where might be the issue?

**Comment by ralight** [comment]
I am reasonably sure that this is a problem with your implementation. There will be some small aspect that you have overlooked, or made a typo somewhere that is causing the problem. I could try to reimplement what you have done, but that would take me a lot of time and there's a good chance that I'd do something different to you. If you'd like some real help, please attach a *minimal* example that shows the problem. That means you should spend a lot of time getting rid of all of the extra code that isn't important to this specific problem. If you do that, you may well find the problem anyway. If you attach your entire project with hundreds of lines of code, I'm not going to look at it.

**Comment by ikarthikeyank** [comment]
I tried to recreate the problem. I'm not getting this error - the client xxxxx has exceeded timeout, disconnecting.


 if the client xxxxx has exceeded timeout, disconnecting. **the broker has to disconnect it's connection right?** So can you please tell me why this is happening? What could be the reason?

**Comment by ikarthikeyank** [comment]
One more finding : 

During azure client disconnection and I'll send that log to mosquitto broker.  At one point of time, the client sends the data to the broker and not getting the return code. I guess there, the client xxxxx is lost.

```
Client _heg_observer_ sending PUBLISH (d0, q0, r0, m522, 'SYSLOG', ... (171 bytes))
local mosquitto publish rc : 0
Message published
Client _heg_observer_ sending PUBLISH (d0, q0, r0, m523, 'SYSLOG', ... (171 bytes))
local mosquitto publish rc : 0
Client xxxxx sending PUBLISH (d0, q0, r0, m527, 'SYSLOG', ... (153 bytes))
.
.
.
.
no return code
```

**Comment by ikarthikeyank** [comment]
One more finding : 

During azure client disconnection and I'll send that log to mosquitto broker.  At one point of time, the client sends the data to the broker and not getting the return code. I guess there, the client xxxxx is lost.

```
Client xxxxx sending PUBLISH (d0, q0, r0, m522, 'SYSLOG', ... (171 bytes))
local mosquitto publish rc : 0
Message published
Client xxxxx sending PUBLISH (d0, q0, r0, m523, 'SYSLOG', ... (171 bytes))
local mosquitto publish rc : 0
Client xxxxx sending PUBLISH (d0, q0, r0, m527, 'SYSLOG', ... (153 bytes))
.
.
.
.
no return code
```

**Comment by ralight** [comment]
I'm sorry, without some code to look at it's impossible to say anything.

```
In my real application, if the client xxxxx has exceeded timeout, disconnecting, the broker has to disconnect it's connection right? So can you please tell me why is this happening? What could be the reason?
```

The problem is that the client hasn't communicated to the broker in its keepalive time. Without a minimal example to look at I can't say any more.

**Comment by ikarthikeyank** [comment]
I can give you the minimal example code. But the issues is not reproducing.

The issue raises only I push some logs to the mosquitto broker. I agree that this is the implementation fault.

My general question is that if the client hasn't communicated to the broker in its keepalive time, will the broker terminate the client's connection?

**Comment by ralight** [comment]
When I say a minimal example, I mean a minimal example that demonstrates the problem you are seeing. In your case that would include publishing messages.

If a client doesn't communicate with the broker in its keepalive time the broker disconnects it. This happens immediately after you see the "client has exceeded" log message.

**Comment by ralight** [comment]
I'm assuming this is no longer an issue, if it is please feel free to reopen and add some more details.
