### ISSUE TITLE
BUG - Retained Flag turned back ON even after clearing and turning OFF

### ISSUE THREAD

**Issue by ZhuDaHai** [eclipse/mosquitto#2185]
1. Running Mosquitto Broker on Home Assistant. Current versions of both:

![Part 0a](https://user-images.githubusercontent.com/14084743/115336074-093a8900-a1d1-11eb-93d8-57fa71faff6e.PNG)

![Part 0b](https://user-images.githubusercontent.com/14084743/115336087-0dff3d00-a1d1-11eb-9d3d-0346fe2d168d.PNG)

2. Current Service AuroraA4/event/Disconnected has 'Retained' flag ON as shown in MQTT Explorer:

![Part 1](https://user-images.githubusercontent.com/14084743/115336145-2e2efc00-a1d1-11eb-8ccc-51932906bdfb.PNG)

3. Sent message to MQTT using Home Assistant MQTT:Publish with Null payload and Retain Flag OFF.

![Part 2](https://user-images.githubusercontent.com/14084743/115336229-5b7baa00-a1d1-11eb-8d32-102fbfd3e56f.PNG)

4. Verified in MQTT Explorer that Disconnected event has been removed (as payload as Null) as expected:

![Part 3](https://user-images.githubusercontent.com/14084743/115336303-8665fe00-a1d1-11eb-84f2-bf5d6803d948.PNG)

5. In Service (OctoPi MQTT Plugin), I have 'Enable Retain Flag' turned OFF:

![Part 4](https://user-images.githubusercontent.com/14084743/115336354-a4336300-a1d1-11eb-9476-40512b18d514.PNG)

6. Turned on OctoPi for AuroraA4, then Disconnect. Verified in MQTT Explorer that 'Disconnected' event does NOT have Retain flag ON (it is OFF / not Retained):

![Part 5](https://user-images.githubusercontent.com/14084743/115336439-d775f200-a1d1-11eb-82cf-4ce2126ef8a4.PNG)

7. Rebooted ENTIRE Home Assistant server, including Mosquitto Broker:

![Part 6](https://user-images.githubusercontent.com/14084743/115336632-2459c880-a1d2-11eb-853b-791c83af60c5.PNG)

8. As soon as Mosquitto Broker restarted, ANOTHER 'Disconnected' event was inserted and this time the RETAIN flag was set ON.
Note that service AuroraA4 was OFF and never turned on again since it was shutdown in Step 6

![Part 8](https://user-images.githubusercontent.com/14084743/115336761-63881980-a1d2-11eb-99ba-efb533e53e1c.PNG)

You can see the original 'Disconnected' event from the AuroraA4 service 5.1 minutes ago, and the NEW one (inserted by Mosquitto Broker just now) with the RETAIN flag turned ON.

Why is Mosquitto Broker inserting a NEW Disconnected event in this service (which I thought only the SERVICE should be allowed to do) and why is it setting the Retain Flag ON (again, I thought ONLY the Service was allowed to set/clear the Retain flag)???

Am I doing something wrong here, or is this a bug that needs to be fixed ASAP?

Background:
I am using OctoPi with MQTT to monitor my 3d Printer. And in the event that OctoPi Disconnects from the 3D Printer (either through a communications error, or an error thrown by the printer's firmware), it sends that message to Home Assistant MQTT Mosquitto Broker that triggers an automation to turn OFF the power to the Tasmotta Sonoff switch, which powers OFF the 3D Printer. Thus avoiding the potential of a FIRE due to a fried MOSFET or other component throwing an error in the firmware and causing a Thermal Runaway.

However, with Mosquitto Broker inserting 'Disconnected' events when Home Assistant reboots. This triggers Home Assistant to run my automation and Shut Down the Printer even though no error or disconnect message was sent by OctoPi, thus Destroying any print job currently running.

![Part 9](https://user-images.githubusercontent.com/14084743/115337691-04c39f80-a1d4-11eb-8cc8-52f9bbbe6dd9.PNG)

**Comment by ZhuDaHai** [comment]
P.S. I also tried with the Payload Checked and with the Retain Checked and with the Retain Switch both ON and OFF. And still each time after rebooting Home Assistant (hence rebooting Mosquitto Broker), the Disconnected Event was reinserted with the Retain Flag ON:

![New Part 2](https://user-images.githubusercontent.com/14084743/115340531-6c301e00-a1d9-11eb-8f7b-be53071706f3.PNG)

![New Part 3](https://user-images.githubusercontent.com/14084743/115340619-9b468f80-a1d9-11eb-8e7d-42c9ff147a6d.PNG)

**Comment by ralight** [comment]
Sorry for the delay replying. If you want to clear a retained message, you must send a message to that topic which has a zero length payload and has the retain flag set. In mosquitto_pub you would do this:

```
mosquitto_pub -t my/topic -r -n`
```

**Comment by ralight** [comment]
Closing because I think this is resolved, if not please feel free to reopen and add more information.
