### ISSUE TITLE
Mosquitto 1.6.12 - user password with $ not accepted

### ISSUE THREAD

**Issue by riccardoch** [eclipse/mosquitto#2186]
Mosquitto version: 1.6.12
System: Ubuntu 20.04

I've configured a password_file and I've noticed that passwords with "$" don't work.
According to documentation we have to avoid ":" for usernames, but no indications about passwords.

**Comment by ralight** [comment]
Here is an asciicast of me testing that out: https://asciinema.org/a/Y9aicL708lyss302FMVzBHAus

My bet is that you suffered from the shell expanding the $ into a variable at some point.

**Comment by riccardoch** [comment]
Thanks for the fast response!
I've a `.sh` with this command inside:
`mosquitto_passwd -b '$1' '$2' '$3'`

At first I thought the same thing, but the password shouldn't work with something like:
bo$1b
while, even with something like this is not working:
DB€Bjb9£jlEv2bNxX92G0££7CS4xQ€6YZmx86g$h9Y1

I tried with the same credentials of your test, but it fails:
`mosquitto_passwd -b /etc/mosquitto/pwfile 'bob' '$bob'`

The difference between my test and yours is that you're creating a new password file (or overwriting the old one), using `-c` option.

**Comment by ralight** [comment]
I created a password file like this:
```
mosquitto_passwd -c -b pwf 'one' 'one'
mosquitto_passwd -b pwf 'two' '$two'
mosquitto_passwd -b pwf 'three' 'bo$1b'
mosquitto_passwd -b pwf 'four' 'DB€Bjb9£jlEv2bNxX92G0££7CS4xQ€6YZmx86g$h9Y1'
```
The resulting file had this in:
```
one:$6$ZPCPOMqM/NjfzNXV$HklivJQIXjNRZ8ZKRGNzoFonB4z+bUjd7EVKke81qk6kpUaxzpzT+Y83UCX3iD7je8ujlvOXJCKhgfC9hg5GVw==
two:$6$M2I3b4viW6jFqV0J$8d0/4lJr1xdUFc6B6VAre4vCxbs2Cu0v7aztMjR/4xozhifgwaVEm2GnrIT4SbVyVFHYFLLdVaEZSFJZclYyWA==
three:$6$ijnk9RiWDKg261nX$B+1nLTfLMn4vyJy3EswVCLrgFxNldQ+y9pnpZET2t4KNitE5an3sGFUwUa/eH4piQSBdIcIJUxPllGTKEgdIgw==
four:$6$VnFAmvAI7yc6wQcn$B1VLZk3eyssv1QNEXnKu3cRPVEnT5I9Ck//KDu2lH9BJHyy9N/BfHOm7Taeu6r50kqw8CSFcdGnp1+w4S+c9tg==
```

Then I tested with all of them succeeding:
![2186](https://user-images.githubusercontent.com/79578/115522322-ea48ff00-a283-11eb-8a00-080ba683664f.png)

Could you try with that literal password file? If that doesn't work then something very odd is going on. If it does work, please paste the contents of your own test password file so I can try it out.

**Comment by ptjm** [comment]
Going back to this:

**Comment by riccardoch** [comment]
@ptjm In my `.sh` I already use double quotes.

@ralight I've tried creating a new password file and everything worked. 
My file is huge, so it's difficult to check, but I've created a script to create a new file and now everything works fine.
Maybe the old file was not well formatted.

Thanks for your help.
