### ISSUE TITLE
mosquitto_pub with QOS 1 exiting on connection loss instead of queuing message

### ISSUE THREAD

**Issue by JsBergbau** [eclipse/mosquitto#2187]
According to https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/

![grafik](https://user-images.githubusercontent.com/37013344/115539129-e5dd1000-a29c-11eb-873f-7b7f4bc30b84.png)

So according to specification sender stores messages until it is successfully delivered.

Execute `mosquitto_pub -t test -h <host> -u <user> -P <PW> -l -q 1`

Type messages one by one and see that they are received. No simulate some kind of network failure like the broker going away
sudo iptables -A OUTPUT -d <broker_IP>/32 -j REJECT

Now type some messages again in above window so that mosquitto_pub should deliver it after connection is re-established. However after some time an error appears `Error: Publish returned 4, disconnecting.` 
mosquitto_pub exits and all messages after connection problems are lost.

So is the MQTT specification unclear or is this a bug in mosquitto_pub? Personally I think with QOS 1 message should get queued up to a configurable limit before messages get dropped.

**Comment by JsBergbau** [comment]
Why has this been closed without any discussion or answer?

**Comment by ralight** [comment]
I'm sorry for not having commented here before, you can see that I addressed this a while back and it's now part of the release.

**Comment by JsBergbau** [comment]
Thank you very much. Just tested and it works now as expected.
