### ISSUE TITLE
Create official Docker Image for Docker Hub

### ISSUE THREAD

**Issue by daudetCA** [eclipse/mosquitto#219]
We are using Mosquitto and starting to use Docker for containerization of our product. After looking on Docker Hub, I have found a number of unofficial images that have been created on various base OS images.

I would like to propose that a Dockerfile is created such that a new Docker image can be built and pushed to Docker Hub, so that there is an official Docker image available to the wider community.

For instance I have created a Dockerfile to install Mosquitto 1.4.8 on top of a minimal Alpine Linux Docker image:

```
FROM alpine:latest
LABEL Description="Mosquitto MQTT Broker"

# Based on:
# https://hub.docker.com/r/najibninaba/mosquitto-docker-image/~/dockerfile/

# Install the latest mosquitto from the pkg repo
RUN apk --no-cache --update add mosquitto && \
    rm -rf /var/cache/apk/*

COPY mosquitto.conf /etc/mosquitto

ENTRYPOINT ["/usr/sbin/mosquitto", "-c", "/etc/mosquitto/mosquitto.conf"]
```

Is it possible to do this or something similar such that when a new version of Mosquitto is built, a new Docker image is pushed to the official Docker Hub registry?

**Comment by xpratpa** [comment]
+1

**Comment by zdnet** [comment]
+1

**Comment by ralight** [comment]
This has been done thanks to @daudetCA.
