### ISSUE TITLE
Mosquitto broker sends only 1020 of the retained messages

### ISSUE THREAD

**Issue by grzegorzkloc** [eclipse/mosquitto#2196]
I am facing the following problem, while working with mosquitto (ver 2.0.10) I initialize the broker, run a simulator app which populates the broker with over 12500 messages with retain set to true.

However, when I connect to the broker (using a WPF app, python app and mosquito_sub.exe) and subscribe using a wildcard I only get 1020 of the retained messages.

As mentioned above, I use three different methods of connection yet everyone of the yields the same result (not all retained messages are being sent out by the broker).

I tried to use all combinations of QOS and the result is the same.

Is that a bug or some kind of error on my behalf.
Your kind help will be much appreciated.

**Comment by karlp** [comment]
do you have 12500 distinct topics?  retain is only one message per topic...

**Comment by grzegorzkloc** [comment]
Yes, there are 12500 distinct topic. The production environment will probably have around 76000 topics. 
The topics are constructed as follows: DeviceInfo/[DeviceName]/[DeviceId}/[Attribute]. There will be 5 or 6 attributes per device. So Initially the simulator populates the broker and my app connects and wants to retrieve all of them however I only get 1020 regardless if I use a C# app, python or mosquitto_sub.
Moreover, I get the same number of messages regardless if I subscribe like so: DeviceInfo/# or like so:  DeviceInfo/+/+/Description (which is one of the attributes.

Any help or guidance will be greatly appreciated.
Also, thank you in advance for any the time and any actions taken.

**Comment by grzegorzkloc** [comment]
Turns out my configuration was incomplete. Adding 
max_inflight_messages count 0 
max_queued_messages count 0
partially solved my problem. 
However, I still do not get all of the messages. If I add the above values to my config (and use the production environment variables) I get exactly 65555 messages.

**Comment by karlp** [comment]
With some load testing software of my own, I found that some of my _publishers_ weren't actually publishing as I expected, is there a chance you could check that end?

**Comment by grzegorzkloc** [comment]
After a close inspection it seems that the following configuration lines seem to work:
```
max_inflight_messages count 0
max_queued_messages count 0
```

I ran tried to run Mosquitto in verbose mode and it seems that my simulator was kept getting disconnected when populating the broker (resulting in lower message count).

When verbose mode is turned off the simulator sends the desired number of messages, all of them are retained correctly and subsequently delivered to the client.

I think this issue can be closed.
@karlp thank you kindly for your time and for guiding me in the right direction.

**Comment by karlp** [comment]
glad you got it sorted.  these sorts of flood rate issues can often come up in load testing, where you have a local network link faster than you might expect.  if you're using qos1 or 2, you _should_ be able to put max inflight messages to ~any number, and still have robust counts, all that should be affected is throughput.  Max queued messages, aiui, doesn't even apply to retained messages though, so it shouldn't have mattered for the _retention_  If you're using qos0, you definitely need to allow higher max in flight, unless you are _certain_ that your subscriber can listen faster than the broker can push.  (and always remember that publisher and subscriber qos are independent variables!)
