### ISSUE TITLE
Mosquitto stopped reciving messages only from one device

### ISSUE THREAD

**Issue by jbrepogmailcom** [eclipse/mosquitto#2197]
Hello,

I have discovered that one of my sensors does not send messages to Home Assistant. After closer investigration it turned out that mosquitto does not reveive messages (checked on mosquitto_sub), but it was receiving messages from all other sensors correctly. Sensor was connected to wifi correctly and could be pinged. So I restarted mosquitto and it immediately started to process messages from the sensor.

So it is possible that messages from particular client or topic are not received, while other messages are? This seems strange.. I do not have old log and new log after restart does not show anything strange, just "client connected".

**Comment by ralight** [comment]
Sorry to hear you've had this odd behaviour. I can't think of a reason why it would occur I'm afraid. What version of Mosquitto are you using?

**Comment by jbrepogmailcom** [comment]
Hello I have mosquitto Home Assistant add-on 5.1.1. This problem happened twice in two days and then it is working again for several days. mosquitto broker restart fixed the issue in both cases. It seems to me that some data that is fetched in memory got corrupted, or the database on the disk and it got repaired after restart.
