### ISSUE TITLE
Mosquitto version update for ubuntu 20.04 

### ISSUE THREAD

**Issue by amin-is** [eclipse/mosquitto#2199]
It is possible to install or update mosquitto version 1.6.12 or newer 2.0 ? Currently 1.6.9 version is default for ubuntu 20.04.

**Comment by ralight** [comment]
The version provided by Ubuntu can't be changed, but you could use the project PPA at https://launchpad.net/~mosquitto-dev/+archive/ubuntu/mosquitto-ppa , or use the snap package version with `snap install mosquitto` and https://mosquitto.org/documentation/using-the-snap/
