### ISSUE TITLE
-i error

### ISSUE THREAD

**Issue by GankLun** [eclipse/mosquitto#2200]
it appears on version based on 2.0.10 windows-x64.
for example, when open command window,execute command: mosquitto_sub -t topicXX -i client1
then open another command window,execute command: mosquitto_sub -t topicXX -i client2.
at last, open another command window,execute command: mosquitto_pub -t topicXX  -m messageXX -i client2.
But,client1 receives the messageXX, client2 receives nothing. and if execute command: mosquitto_pub -t topicXX  -m messageXX -i client1. the client2 receives the messageXX.,client1 receives nothing

**Comment by ralight** [comment]
Hi there,

All client IDs must be unique, when you reuse them the existing client that was using it will be disconnected. That's why your subscribers don't see the messages.

**Comment by GankLun** [comment]
But clientId is unique,I was the first time to use clientID like this.

**Comment by GankLun** [comment]
But [clientId](url) is unique,I was the first time to use clientID like this. 
![Uploading 1620258947(1).png…]()
![Uploading 1620258965(1).png…]()
![Uploading 1620259002(1).png…]()

**Comment by GankLun** [comment]
But clientId is unique,I was the first time to use clientID like this. I mean that  another client receive message,rather than subscribers receive the message.  you can try it for test. just use unique clientid you have never used.

**Comment by GankLun** [comment]
> Hi there,
> 
> All client IDs must be unique, when you reuse them the existing client that was using it will be disconnected. That's why your subscribers don't see the messages.

you mean that the cilentid in "mosquitto_sub" -i and the cilentid in "mosquitto_pub" -i can't be the same one?

**Comment by ralight** [comment]
> > Hi there,
> > All client IDs must be unique, when you reuse them the existing client that was using it will be disconnected. That's why your subscribers don't see the messages.
> 
> you mean that the cilentid in "mosquitto_sub" -i and the cilentid in "mosquitto_pub" -i can't be the same one?

Yes, that is correct.

**Comment by GankLun** [comment]
thanks for your reply,I had expected that publish message to the subscriber like point to point, not all  subscriber that  subscribe the same topic. Is there any method to implemention it ?

**Comment by ralight** [comment]
It's entirely up to you how you arrange your publishers and subscribers. If you want to have a 1:1 mapping then that will work just fine. The problem here though is that you have three different clients but only two client ids. 

Try this:
```
# Window 1
mosquitto_sub -t topicXX -i client1
# Window 2
mosquitto_sub -t topicXX -i client2.
# Window 3
mosquitto_pub -t topicXX -m messageXX -i client3
```

You will find that both client1 and client2 receive the message.

If you want only one of the mosquitto_sub instances to receive the message, they will need to subscribe to a unique topic. Alternatively, if you only want a single client to receive each message, but you don't care which one does, then you could use MQTT v5 shared subscriptions - from what you've said I don't think that's what you want though.

**Comment by ralight** [comment]
I think this has been covered, so I'm closing the issue. If you still have problems please reopen and add more details.
