### ISSUE TITLE
websocket is notworking

### ISSUE THREAD

**Issue by KindHunter** [eclipse/mosquitto#2204]
platform ：CentOS Linux release 7.9.2009
Mosquitto  version：1.6.14  build with  `WITH_WEBSOCKETS:=yes`
mosquitto.conf：

```
per_listener_settings false

listener 1883 127.0.0.1

protocol websockets

connection_messages true

socket_domain ipv4

allow_anonymous true


persistence true

persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

#include_dir /etc/mosquitto/conf

#password_file /etc/mosquitto/pwfile

#acl_file /etc/mosquitto/aclfile

log_timestamp true

log_timestamp_format %Y-%m-%dT%H:%M:%S

log_type all
```

log:
![image](https://user-images.githubusercontent.com/25549282/117912993-1e5b9100-b313-11eb-9357-71c70b18e4b7.png)

However i found mosquitto is not listening on port 1883, and i can't find any abnormal log,  when i change protocol to mqtt, it works fine.

![image](https://user-images.githubusercontent.com/25549282/117913046-37fcd880-b313-11eb-8ae3-3ddb8186945b.png)
![image](https://user-images.githubusercontent.com/25549282/117913086-49de7b80-b313-11eb-8dda-bab060a2260f.png)
![image](https://user-images.githubusercontent.com/25549282/117913139-5fec3c00-b313-11eb-81cc-b5742af28116.png)

**Comment by Joey777210** [comment]
Hello, I'm currently facing the same problem!! 
Did you fix it?

**Comment by KindHunter** [comment]
> Hello, I'm currently facing the same problem!!
> Did you fix it?

not yet，i change version to 2.0.10, still doesn't work

**Comment by ralight** [comment]
I've tested this out myself using the CentOS provided libwebsockets, and compiling Mosquitto 1.6.14 manually and it worked for me. Could you let me know how you compiled/installed Mosquitto?

**Comment by Joey777210** [comment]
In my case, I'm using Ubuntu 16.04, libwebsocket v3.1, mosquitto 1.5.0.      
I set 1883 as mqtt port, 1884 as websockets port. The problem is, mosquitto is listening both 1883 and 1884, but I can only send message throw 1883 use mqtt protocol.    
When I connect 1884, I got network error.    
Then I tried wireshark to check the problem. The result shows, when I connect 1884 with websockets, First tcp handshakes. Then websockets handshakes. And **the server send [FIN + ACK] right away**. I guess maybe there are some reasons server break the connection.  
 
I installed Mosquitto as below:

1. Install compile dependency
```
	    sudo apt-get install cmake
	    sudo apt-get install openssl 
	    sudo apt-get install libssl-dev
```
2.  Install libwebsocket 3.1 
```
	    git clone https://github.com/warmcat/libwebsockets.git
	    cd libwebsockets
	    mkdir build
	    cd build
	    cmake ..
	    make
	    sudo make install
```
3. Install golang(Cause I wrote an auth plugin with go language)
4. Compile Mosquitto
```
            change WITH_WEBSOCKETS:=yes
	    chmod u+x build.sh
	    ./build.sh
```
Here is my build.sh
```
#!/bin/bash

OPENSSL_DIR=/usr/local/Cellar/openssl/1.0.2o_2

OPTS="-DWITH_WEBSOCKETS=ON"

SYS=`uname -s`

if [ ${SYS} == "Darwin" ];then
    echo "Build on Darwin"
    OPTS="${OPTS} -DOPENSSL_INCLUDE_DIR=${OPENSSL_DIR}/include -DOPENSSL_CRYPTO_LIBRARY=${OPENSSL_DIR}/lib/libcrypto.dylib -DOPENSSL_SSL_LIBRARY=${OPENSSL_DIR}/lib/libssl.dylib"
elif [ ${SYS} == "Linux" ];then
    echo "Build on Linux"
else
	echo "OS not supported: ${SYS}"
	exit 1
fi

echo "rm -rf build"
rm -rf build

echo "mkdir build && cd build"
mkdir build && cd build

echo "cmake ${OPTS} ../mosquitto"
cmake ${OPTS} ../mosquitto

echo "make"
make

echo "Now you can build plugin using 'make', and test mosquitto using 'make test'"
echo ""
echo "    cd plugin"
echo "    make"
echo "    make test"
echo ""

```
5. Compile plugin
```
            Enter plugin dir
	    make
	    sudo ldconfig
```
Here is my Makefile
```
all:
	go build -buildmode=c-shared -o plugin.so

```
6. mosquitto.conf 
```
sys_interval 10

use_username_as_clientid true

listener 1884
protocol websockets


auth_plugin plugin.so

# other config
```

**Comment by KindHunter** [comment]
> I've tested this out myself using the CentOS provided libwebsockets, and compiling Mosquitto 1.6.14 manually and it worked for me. Could you let me know how you compiled/installed Mosquitto?

Thanks for your help, I solved my problem.

I found the libwebsockets version on host is v4.2.0, which is not enable `LWS_WITH_EXTERNAL_POLL` by default, so i changed libwebsockets  version to v3.0.1. Now the Mosquitto(v2.0.10 ) is listening on websockets port.

**Comment by ralight** [comment]
Great! I'm glad you've got it working.
