### ISSUE TITLE
Moquitto broker is active but I keep getting Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by disizme** [eclipse/mosquitto#2206]
The broker service is working fine in the server but cannot get mqtt client connect.
It was working fine until yesterday.

error Error: getaddrinfo ENOTFOUND mqtt.kipuwex.com
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
errno: -3008,
code: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'mqtt.kipuwex.com'
}

I had the same issue last week but it got solved on its own. There is no error in the server logs as well.
Please help solve this recurring issue.

**Comment by ralight** [comment]
This is a network/dns problem that is nothing to do with Mosquitto I'm afraid.
