### ISSUE TITLE
broken bridge functionality

### ISSUE THREAD

**Issue by abiliojr** [eclipse/mosquitto#2207]
In develop (and probably other versions of mosquitto), the Bridge functionality is mostly broken (at least in linux). If a bridge fails to connect or gets disconnected, it will never connect again. More specifically, the connection at TCP level will happen, but the CONNECT packet is never sent over the socket.

This issue was introduced in the commit: 6e3738dcf06a08147d16276ff56b9ace41ab993f , which was supposed to fix #2043

**Comment by ralight** [comment]
Interesting this didn't fail for me because I was only checking the first reconnection attempt, which always works fine for me. This was triggered if the first reconnection failed (the remote broker was still down) - all subsequent attempts would fail.

Does the fix work for you?
