### ISSUE TITLE
 How to refuse mqtt client subscribe to "#"?

### ISSUE THREAD

**Issue by CoreyChang** [eclipse/mosquitto#2208]
However I configure the "aclfile", the mqtt client can subscribe to "#".
Any ideas how to refuse mqtt client subscribe to "#"?

**Comment by karlp** [comment]
subscribing doesn't meant it will necessarily be granted all messages.  If the acls only let it receive a certain subtopic, subscribing to # will simply give it what it's allowed to.

you could also use the auth plugins to make your own decisions and block explicitly
