### ISSUE TITLE
Problem: /etc/cron.daily/logrotate: error: Compressing program wrote following message ... 

### ISSUE THREAD

**Issue by jayjupdhig** [eclipse/mosquitto#2209]
I've got that message today: 

```
/etc/cron.daily/logrotate:
error: Compressing program wrote following message to stderr when compressing log /var/log/mosquitto/mosquitto.log.1:
gzip: stdin: file size changed while zipping
```

Does somebody know what this is? Thank you very much for your feedback.

**Comment by jayjupdhig** [comment]
Maybe that question is a lil bit too complex...?

**Comment by ralight** [comment]
You'd find it beneficial to do some searching in the future prior to submitting a request. The message means that the log changed before logrotate compressed it. If you search, there are many people discussing this in many projects. There are things to do to avoid it, but it's not a problem.

You deleted this from the issue report before you added your text, perhaps next time you could provide the information requested:

```
If you are reporting a bug PLEASE include the version of Mosquitto you are
using and what platform (Windows, Ubuntu/Fedora/... Linux, FreeBSD, ...) you
are running on.

Please also note that some systems have old versions of Mosquitto available in
their package repositories. We would be very grateful if you would check to
see whether the bug is still present in a newer version before submitting your
issue.
```

**Comment by jmar83** [comment]
Problem solved by turn off logs mosquitto logs completely... ;-)

**Comment by ralight** [comment]
If that works for you, fine - but it's not a problem anyway.

**Comment by kosuodhmwa** [comment]
Thx

**Comment by SunSDSE** [comment]
Before I moved to the docker environment I did not have an issue running mosquitto natively within linux and using logrotate.    I am now using the docker container and running within a swarm.  It would be nice if there was a clear cut way to use logrotate on the mosquitto logs.  Is there any documentation on how to do this?

**Comment by kosuodhmwa** [comment]
-> I installed it on a debian 10 server with plesk obsidian 18.x...

**Comment by jayjupdhig** [comment]
...
