### ISSUE TITLE
HASS integration doesn't change color of Tasmota light

### ISSUE THREAD

**Issue by Ilhom550** [eclipse/mosquitto#2216]
Hi guys!
I have this bug where when I open my ceiling light (Tuya device flashed with Tasmota link: https://templates.blakadder.com/oeegoo_OEE216.html) with HomeAssistantOS and select a color it would flash this color for not even one second and then go back to white.

**Comment by ralight** [comment]
I would recommend that you open an issue on the home assistant bug tracker instead, I don't see how I can help. Best of luck getting it fixed.
