### ISSUE TITLE
Reconexión  Cliente Mosquito

### ISSUE THREAD

**Issue by CDominguezTC** [eclipse/mosquitto#2217]
Hola a todos, 

Tengo un cliente el cual se conecta al servicio de mosquito para revisar la información que envía un dispositivo de reconocimiento facial, el problema que tengo es que si mi cliente se desconecta se pueden perder los envíos realizados por el dispositivo, ya que no los he procesado, estoy tratando de reconectar mi cliente pero este no me funciona. dejo mi codigo, por si se encuentra una novedad 

package AlohaTiemposListener;

import Controlador.ControladorDispositivoSegurex;
import Controlador.ControladorEmpleados;
import Controlador.ControladorIdentificacion;
import Controlador.ControladorProcesarMacaciones;
import Modelo.ModeloDispositivoSegurex;
import Modelo.ModeloEmpleados;
import Modelo.ModeloIdentificacion;
import Modelo.ModeloProcesarMarcaciones;
import Tools.Tools;
import com.google.gson.Gson;
import com.google.gson.internal.LinkedTreeMap;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.eclipse.paho.client.mqttv3.IMqttDeliveryToken;
import org.eclipse.paho.client.mqttv3.MqttCallback;
import org.eclipse.paho.client.mqttv3.MqttClient;
import org.eclipse.paho.client.mqttv3.MqttConnectOptions;
import org.eclipse.paho.client.mqttv3.MqttDeliveryToken;
import org.eclipse.paho.client.mqttv3.MqttException;
import org.eclipse.paho.client.mqttv3.MqttMessage;
import org.eclipse.paho.client.mqttv3.MqttTopic;

public class AlohaTiemposListener implements MqttCallback {

    MqttClient myClient;
    MqttConnectOptions connOpt;

    static final String BROKER_URL = "tcp://127.0.0.1:1883";
    static final String M2MIO_DOMAIN = "test";
    static final String M2MIO_STUFF = "things";
    static final String M2MIO_THING = "alohalistener";
    static final String M2MIO_USERNAME = "admin";
    static final String M2MIO_PASSWORD_MD5 = "12345";

    // the following two flags control whether this example is a publisher, a subscriber or both
    static final Boolean subscriber = true;
    static final Boolean publisher = true;

    /**
     *
     * connectionLost This callback is invoked upon losing the MQTT connection.
     *
     */
    @Override
    public void connectionLost(Throwable t) {
        System.out.println("Connection lost! ERRRO ==> " + t);
        try {
            Thread.sleep(3000);
            //myClient.disconnect();
            myClient.reconnect();
        } catch (Exception e1) {
            System.out.println("AlohaTiemposListener.AlohaTiemposListener.connectionLost() ERROR ==> " + e1);            
        }
    }
    /**
     *
     * deliveryComplete This callback is invoked when a message published by
     * this client is successfully received by the broker.
     *
     */
    //@Override
    public void deliveryComplete(MqttDeliveryToken token) {
        //System.out.println("Pub complete" + new String(token.getMessage().getPayload()));
    }

    /**
     *
     * messageArrived This callback is invoked when a message is received on a
     * subscribed topic.
     *
     */
    //@Override
    public void messageArrived(MqttTopic topic, MqttMessage message) throws Exception {
        System.out.println("-------------------------------------------------");
        System.out.println("| Topic:" + topic.getName());
        System.out.println("| Message: " + new String(message.getPayload()));
        System.out.println("-------------------------------------------------");
    }

    /**
     *
     * MAIN
     *
     */
    public static void main(String[] args) {
        AlohaTiemposListener smc = new AlohaTiemposListener();
        smc.runClient();
    }

    /**
     *
     * runClient The main functionality of this simple example. Create a MQTT
     * client, connect to broker, pub/sub, disconnect.
     *
     */
    public void runClient() {
        // setup MQTT Client
        String clientID = M2MIO_THING;
        connOpt = new MqttConnectOptions();
        connOpt.setAutomaticReconnect(true);
        connOpt.setCleanSession(true);
        connOpt.setConnectionTimeout(10);
        connOpt.setKeepAliveInterval(60);
        connOpt.setUserName(M2MIO_USERNAME);
        connOpt.setPassword(M2MIO_PASSWORD_MD5.toCharArray());

        // Connect to Broker
        try {
            myClient = new MqttClient(BROKER_URL, clientID);
            myClient.setCallback(this);
            myClient.connect(connOpt);            
        } catch (MqttException e) {
            e.printStackTrace();
            System.exit(-1);
        }

        System.out.println("Connected to " + BROKER_URL);

        // setup topic
        // topics on m2m.io are in the form <domain>/<stuff>/<thing>
        //String myTopic = M2MIO_DOMAIN + "/" + M2MIO_STUFF + "/" + M2MIO_THING;
        String myTopic = M2MIO_DOMAIN;
        MqttTopic topic = myClient.getTopic(myTopic);

        // subscribe to topic if subscriber
        if (subscriber) {
            try {
                int subQoS = 0;
                myClient.subscribe(myTopic, subQoS);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        // publish messages if publisher
//        if (publisher) {
//            for (int i = 1; i <= 10; i++) {
//                String pubMsg = "{\"pubmsg\":" + i + "}";
//                int pubQoS = 0;
//                MqttMessage message = new MqttMessage(pubMsg.getBytes());
//                message.setQos(pubQoS);
//                message.setRetained(false);
//
//                // Publish the message
//                System.out.println("Publishing to topic \"" + topic + "\" qos " + pubQoS);
//                MqttDeliveryToken token = null;
//                try {
//                    // publish message to broker
//                    token = topic.publish(message);
//                    // Wait until the message has been delivered to the broker
//                    token.waitForCompletion();
//                    Thread.sleep(100);
//                } catch (Exception e) {
//                    e.printStackTrace();
//                }
//            }
//        }
        // disconnect
//        try {
//            // wait to ensure subscribed messages are delivered
//            if (subscriber) {
//                Thread.sleep(5000);
//            }
//            myClient.disconnect();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }

    @Override
    public void messageArrived(String string, MqttMessage mm) throws Exception {
//        System.out.println("-------------------------------------------------");
//        System.out.println("| Topic:" + string);
//        System.out.println("| Message: " + new String(mm.getPayload()));
//        System.out.println("-------------------------------------------------");
        //Miramos que tipo de mensaje esta llegando 
        String sms = new String(mm.getPayload());
        System.out.println(sms);
        String jsonString = sms;
        if (sms.contains("mqtt param erro!")) {
            // System.out.println("AlohaTiemposListener.AlohaTiemposListener.messageArrived() Estoy en el mesnajes mqtt param erro!");
        } else {
            //System.out.println("sms" +sms);
            Map<String, Object> retMap = new Gson().fromJson(
                    jsonString, new TypeToken<HashMap<String, Object>>() {
                    }.getType()
            );

            //System.out.println("AlohaTiemposListener.AlohaTiemposListener.messageArrived()" + retMap);
            //Validamos que tipo de mensaje es 
            try {

                if (retMap.containsKey("msg")) {
                    String exprecion = (String) retMap.get("msg");
                    switch (exprecion) {
                        case "mqtt bind ctrl success":
                            if (retMap.containsKey("datas")) {
                                LinkedTreeMap<Object, Object> token = new LinkedTreeMap<>();
                                token = (LinkedTreeMap<Object, Object>) retMap.get("datas");
                                //System.out.println("AlohaTiemposListener.AlohaTiemposListener.messageArrived()");
                                //guardamos el token y el session
                                ModeloDispositivoSegurex modeloDispositivoSegurex = new ModeloDispositivoSegurex();
                                ControladorDispositivoSegurex controladorDispositivoSegurex = new ControladorDispositivoSegurex();
                                modeloDispositivoSegurex = controladorDispositivoSegurex.SearchSerie((String) retMap.get("device_id"));
                                modeloDispositivoSegurex.setToken((String) token.get("device_token"));
                                modeloDispositivoSegurex.setSession((String) token.get("session_id"));
                                controladorDispositivoSegurex.Update(modeloDispositivoSegurex);
                            }
                            break;
                        case "Upload Person Info!":
                            if (retMap.containsKey("datas")) {
                                Tools tools = new Tools();
                                Modelo.ModeloProcesarMarcaciones modeloProcesarMarcaciones = new ModeloProcesarMarcaciones();
                                LinkedTreeMap<Object, Object> marcacion = new LinkedTreeMap<>();
                                marcacion = (LinkedTreeMap<Object, Object>) retMap.get("datas");
                                //System.out.println("AlohaTiemposListener.AlohaTiemposListener.messageArrived()");
                                //guardamos el token y el session
                                ModeloDispositivoSegurex modeloDispositivoSegurex = new ModeloDispositivoSegurex();
                                ControladorDispositivoSegurex controladorDispositivoSegurex = new ControladorDispositivoSegurex();
                                modeloDispositivoSegurex = controladorDispositivoSegurex.SearchSerie((String) retMap.get("device_id"));
                                //Datos del usuario en la marcacion 
                                String user_id = (String) marcacion.get("user_id");
                                String time = (String) marcacion.get("time");
                                if (!user_id.equals("")) {
                                    //Traemos los datos del usuario en el didentificador 
                                    Modelo.ModeloIdentificacion modeloIdentificacion = new ModeloIdentificacion();
                                    Controlador.ControladorIdentificacion controladorIdentificacion = new ControladorIdentificacion();
                                    modeloIdentificacion = controladorIdentificacion.getModelo_Identificacion(user_id);
                                    if (modeloIdentificacion.getId() != 0) {
                                        Modelo.ModeloEmpleados modeloEmpleados = new ModeloEmpleados();
                                        Controlador.ControladorEmpleados controladorEmpleados = new ControladorEmpleados();
                                        modeloEmpleados = controladorEmpleados.getModelo(modeloIdentificacion.getId());
                                        if (modeloEmpleados.getId() != 0) {
                                            modeloProcesarMarcaciones.setCodigo(user_id);
                                            modeloProcesarMarcaciones.setFecha(tools.getFechaMarcacion(time));
                                            modeloProcesarMarcaciones.setHora(tools.getHoraMarcacion(time));
                                            modeloProcesarMarcaciones.setDispositivo(modeloDispositivoSegurex.getNombre());
                                            modeloProcesarMarcaciones.setModeloEmpleados(modeloEmpleados);
                                            modeloProcesarMarcaciones.setModeloIdentificacion(modeloIdentificacion);
                                            Controlador.ControladorProcesarMacaciones controladorProcesarMacaciones = new ControladorProcesarMacaciones();
                                            controladorProcesarMacaciones.InsertMarcacion(modeloProcesarMarcaciones);
                                        }
                                    } else {
                                        modeloProcesarMarcaciones.setCodigo(user_id);
                                        modeloProcesarMarcaciones.setFecha(tools.getFechaMarcacion(time));
                                        modeloProcesarMarcaciones.setHora(tools.getHoraMarcacion(time));
                                        modeloProcesarMarcaciones.setDispositivo(modeloDispositivoSegurex.getNombre());
                                        Controlador.ControladorProcesarMacaciones controladorProcesarMacaciones = new ControladorProcesarMacaciones();
                                        controladorProcesarMacaciones.InsertMarcacion(modeloProcesarMarcaciones);
                                    }
                                }
                            }
                            break;
                    }
                }
            } catch (Exception e) {
                System.out.println("AlohaTiemposListener.AlohaTiemposListener.messageArrived() " + e);
            }
//
//            if (retMap.get("smg").equals("mqtt bind ctrl success")) {
//
//            }

//            sms = sms.replace("{", "").replace("}", "").replace("\"", "").replace("\n", "").replace("\t", "");
//            System.out.println(sms);
//            String[] datos = sms.split(",");
//            HashMap<String, String> hashMapSMS = new HashMap<>();
//            for (String dato : datos) {
//                if (hashMapSMS.containsKey("datas")) {
//                    if (dato.contains("datas")) {
//                        dato = dato.replace("datas:", "");
//                        String smsdeparado[] = dato.split(":");
//                        hashMapSMS.put(smsdeparado[0], smsdeparado[1]);
//                    } else {
//                        String smsdeparado[] = dato.split(":");
//                        hashMapSMS.put(smsdeparado[0], smsdeparado[1]);
//                    }
//                }
//
//            }
            //PorcesaMSM(hashMapSMS);
        }

    }

    @Override
    public void deliveryComplete(IMqttDeliveryToken imdt) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void PorcesaMSM(HashMap<String, String> hashMapSMS) {
        if (hashMapSMS.containsKey("code")) {
            if (!hashMapSMS.get("code").equals("-1")) {
                switch (hashMapSMS.get("msg")) {
                    case "mqtt bind ctrl success":
                        //Respuesta de vinculacion del dispositvo 
                        ModeloDispositivoSegurex modeloDispositivoSegurex = new ModeloDispositivoSegurex();
                        ControladorDispositivoSegurex controladorDispositivoSegurex = new ControladorDispositivoSegurex();
                        modeloDispositivoSegurex = controladorDispositivoSegurex.SearchSerie(hashMapSMS.get("device_id"));
                        modeloDispositivoSegurex.setToken(hashMapSMS.get("device_token"));
                        modeloDispositivoSegurex.setSession(hashMapSMS.get("session_id"));
                        controladorDispositivoSegurex.Update(modeloDispositivoSegurex);
                        System.out.println("AlohaTiemposListener.AlohaTiemposListener.PorcesaMSM() Emparejado con exito ");
                        break;
                }
            }
        }
    }
}

**Comment by Tifaifai** [comment]
Use deepl.com for english language.

**Comment by ralight** [comment]
I'm sorry to hear you're having problems, but I think that you should be asking on the Paho issue tracker instead if you want help with your client code. If you still think there is a problem with Mosquitto, please reopen this issue and provide more details - but really I would want a minimised example that demonstrates a problem rather than a lot of pages of code.
