### ISSUE TITLE
Unable to connect to MQTT broker using Node-red & Local network

### ISSUE THREAD

**Issue by chooimail** [eclipse/mosquitto#2218]
Hi,

**Main problem:**
Unable to connect to MQTT broker on another device within the same local network.

**Own observations:**
Happens for version 2.0.0 and (I assume) above. Also happens when installing the latest version available ver 2.0.10.
- I've only tested these 2 versions

When re-installing to an older version 1.6.9, able to connect to broker.

**Platform:**
Windows 10, 64-bit

**Scenario: (both devices on the same WiFi network)**
Laptop 1 : MQTT broker installed ver 2.0.0
Laptop 2 : Node-red installed
Using the MQTT node, configure MQTT server to be (example) 192.168.0.21 (pointing to laptop 1)
Unable to connect.

Laptop 1 : MQTT broker installed ver 1.6.9
Laptop 2 : Node-red installed
Using the MQTT node, configure MQTT server to be (example) 192.168.0.21 (pointing to laptop 1)
Able to connect.

**Comment by chooimail** [comment]
Sorry... my bad.
Problem solved after properly reading through this URL
https://mosquitto.org/documentation/migrating-to-2-0/

**Comment by ralight** [comment]
Great, I'm glad you've got it sorted.
