### ISSUE TITLE
shell=/usr/bin/mosquitto_pub in config file "wmtbusmeters" dont work 

### ISSUE THREAD

**Issue by niklas007** [eclipse/mosquitto#2220]
"RASPBERRY BUSTER as OS"

Shell Line in wmbusmeters: "installed as snap d"

wmbusmeter.conf
shell=/usr/bin/mosquitto_pub -h localhost -t wmbusmeters/$METER_ID -m "$METER_JSON"

wmbusmeters gives me this log:
May 30 18:10:05 raspberrypi wmbusmeters.wmbusmeters[543]: /bin/sh: 1: /usr/bin/mosquitto_pub: not found

"terminal to terminal works for test"

**Comment by ralight** [comment]
It sounds like this is a problem with wmbusmeters, not mosquitto. Do you have mosquitto_pub installed to /usr/bin/mosquitto_pub? If not, either install it there or point your shell command to the location you do have mosquitto_pub installed.

On raspbian you can install mosquitto_pub with `apt install mosquitto-clients`.

**Comment by ralight** [comment]
I'm closing this because I don't think it's a mosquitto bug, if you disagree please reopen and give some more details.
