### ISSUE TITLE
Support of SNI for Mosquitto Client

### ISSUE THREAD

**Issue by xyklex** [eclipse/mosquitto#2221]
I'm trying to use `mosquitto_sub` to connect to a **mqtt** service that requires setting ALPN and SNI, to the first one I found `--tls-alpn` param, but maybe I'm missing something but can't find anything for setting the SNI.

and this issue https://github.com/eclipse/mosquitto/issues/782 mention that maybe this feature was already set in v1.5

**Comment by ralight** [comment]
Hello,

`SSL_set_tlsext_host_name()` is called on client connection using the hostname provided in `-h`, so it should be working already. It's been a while since I've looked at this, so it's possible something more is required in openssl these days.

**Comment by xyklex** [comment]
Hello @ralight, thanks for your answer

If it helps I tested that the connection works by writing a nodejs small script with ALPN and SNI params, and I was able to connect. So something is not working as expected with the feature in mosquitto clients.

When enabling the debug feature it only shows the CONNECT message and on server side the attempt never passes to the application layer

**Comment by ralight** [comment]
Hi @xyklex,

I've just tested this out using the broker from the `develop` branch, which has support for saving TLS keys in a format that wireshark can use to decode the TLS messages - very useful for this situation.

I tried to connect with `mosquitto_sub --cafile all-ca.crt -t asdf --tls-alpn roger-alpn`

The wireshark output of the client hello packet is in the image below. I've highlighted the SNI and ALPN values, which are exactly as I'd expect. Is there something else that could be happening to cause problems?

![sni](https://user-images.githubusercontent.com/79578/120537646-6f741780-c3dd-11eb-8ffb-b69fc8ba7270.png)

**Comment by xyklex** [comment]
@ralight well I have to say that I was doing it wrong, I used Wireshark to debug after you example, and I found the protocol used used was `ssl` and not `tlsv1.2`. But that is not all, I was not using `--cafile` maybe expecting a miracle :-). After adding that last param it used the correct protocol and everything went fine.

**Comment by ralight** [comment]
Great, I'm glad you got it sorted :)
