### ISSUE TITLE
Constantly disconnect and connect - ESP32 CAM with tasmato firmware

### ISSUE THREAD

**Issue by Enjoy-Combi** [eclipse/mosquitto#2226]
Hi,

I have plenty of esp8266 devices powered with tasmota firmware and not having issue for years.
I have recently added one esp32-CAM AITHINKER powered with tasmota firmware as well. 
This device works for a period of time and start to disconnect from the MQTT broker and reconnect continiously.

I went trough a lot of tests including reflashing, test with a new device, some other firmware version, downgrade mosquitto to v1.6, stopping mostly all services which uses mqtt like zigbee2mqtt, octoprint, domoticz,... no way.

My system / mosquitto version:
- raspberry pi 4 4GB: Linux serveur 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux
- mosquitto version : mosquitto version 2.0.11

In all below logs the device is connected as DEV_EAA038.

From the console under tasmota i get this : 
15:48:27.844 MQT: domoticz/in = {"idx":161,"nvalue":0,"svalue":"28.8;40.6;1;985.7;5","Battery":100,"RSSI":7}
15:48:27.851 MQT: tele/webcam-2/SENSOR = {"Time":"2021-06-10T15:48:27","BME280":{"Temperature":28.8,"Humidity":40.6,"DewPoint":14.1,"Pressure":985.7},"ESP32":{"Temperature":64.4},"PressureUnit":"hPa","TempUnit":"C"}
15:48:27.876 RUL: TELE-ESP32#TEMPERATURE performs "publish domoticz/in {"idx":160,"svalue":"64.4;1"}"
15:48:27.882 MQT: domoticz/in = {"idx":160,"svalue":"64.4;1"}
15:49:49.517 MQT: Tentative de connexion...
15:49:51.656 MQT: Connecté
15:49:51.663 MQT: tele/webcam-2/LWT = Online (persistant)
15:49:51.666 MQT: cmnd/webcam-2/POWER = 
15:51:15.823 MQT: Tentative de connexion...
15:51:17.970 MQT: Connecté
15:51:17.976 MQT: tele/webcam-2/LWT = Online (persistant)
15:51:17.979 MQT: cmnd/webcam-2/POWER = 
15:52:39.396 MQT: Tentative de connexion...
15:52:41.222 MQT: Connecté
15:52:41.229 MQT: tele/webcam-2/LWT = Online (persistant)
15:52:41.232 MQT: cmnd/webcam-2/POWER = 
15:53:47.591 RSL: STATE = {"Time":"2021-06-10T15:53:47","Uptime":"0T07:56:09","UptimeSec":28569,"Heap":124,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":16794,"MqttCount":104,"POWER":"OFF","Dimmer":94,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"SFR_B7A8","BSSId":"E4:5D:51:69:B7:AE","Channel":11,"RSSI":74,"Signal":-63,"LinkCount":1,"Downtime":"0T00:00:05"}}
15:53:47.619 RSL: in = {"idx":161,"nvalue":0,"svalue":"28.4;41.9;1;985.7;5","Battery":100,"RSSI":7}
15:53:47.625 RSL: SENSOR = {"Time":"2021-06-10T15:53:47","BME280":{"Temperature":28.4,"Humidity":41.9,"DewPoint":14.2,"Pressure":985.7},"ESP32":{"Temperature":53.3},"PressureUnit":"hPa","TempUnit":"C"}
15:53:47.649 RUL: TELE-ESP32#TEMPERATURE performs "publish domoticz/in {"idx":160,"svalue":"53.3;1"}"
15:53:47.653 RSL: in = {"idx":160,"svalue":"53.3;1"}
15:54:10.620 MQT: Tentative de connexion...
15:54:12.769 MQT: Connecté
15:54:12.776 MQT: tele/webcam-2/LWT = Online (persistant)
15:54:12.779 MQT: cmnd/webcam-2/POWER = 
15:55:40.949 MQT: Tentative de connexion...
15:55:43.087 MQT: Connecté
15:55:43.094 MQT: tele/webcam-2/LWT = Online (persistant)
15:55:43.097 MQT: cmnd/webcam-2/POWER = 
15:57:11.257 MQT: Tentative de connexion...
15:57:13.405 MQT: Connecté
15:57:13.413 MQT: tele/webcam-2/LWT = Online (persistant)
15:57:13.416 MQT: cmnd/webcam-2/POWER = 
15:58:39.733 MQT: Tentative de connexion...
15:58:41.880 MQT: Connecté
15:58:41.887 MQT: tele/webcam-2/LWT = Online (persistant)
15:58:41.890 MQT: cmnd/webcam-2/POWER = 
15:59:25.820 MQT: tele/webcam-2/STATE = {"Time":"2021-06-10T15:59:25","Uptime":"0T08:01:47","UptimeSec":28907,"Heap":118,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":21209,"MqttCount":108,"POWER":"OFF","Dimmer":94,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"SFR_B7A8","BSSId":"E4:5D:51:69:B7:AE","Channel":11,"RSSI":78,"Signal":-61,"LinkCount":1,"Downtime":"0T00:00:05"}}
15:59:25.852 MQT: domoticz/in = {"idx":161,"nvalue":0,"svalue":"28.0;42.6;1;985.7;5","Battery":100,"RSSI":7}
15:59:25.857 MQT: tele/webcam-2/SENSOR = {"Time":"2021-06-10T15:59:25","BME280":{"Temperature":28.0,"Humidity":42.6,"DewPoint":14.1,"Pressure":985.7},"ESP32":{"Temperature":51.7},"PressureUnit":"hPa","TempUnit":"C"}
15:59:25.881 RUL: TELE-ESP32#TEMPERATURE performs "publish domoticz/in {"idx":160,"svalue":"51.7;1"}"
15:59:25.887 MQT: domoticz/in = {"idx":160,"svalue":"51.7;1"}

From mosquitto.log where there is more data, we can see this during disconnection and reconnection:

1623337644: Received PUBLISH from DVES_CEFBFE (d0, q0, r0, m0, 'tele/lumieres-couloir/STATE', ... (291 bytes))
1623337648: Will message specified (7 bytes) (r1, q1).
1623337648: 	tele/webcam-2/LWT
1623337648: Sending CONNACK to DVES_EAA038 (0, 0)
1623337649: Received PINGREQ from Domoticz_1623324330_9859
1623337649: Sending PINGRESP to Domoticz_1623324330_9859
1623337649: Received PUBLISH from DVES_EAA038 (d0, q0, r1, m0, 'tele/webcam-2/LWT', ... (6 bytes))
1623337649: Received PUBLISH from DVES_EAA038 (d0, q0, r0, m0, 'cmnd/webcam-2/POWER', ... (0 bytes))
1623337649: Received SUBSCRIBE from DVES_EAA038
1623337649: 	cmnd/webcam-2/# (QoS 0)
1623337649: Sending SUBACK to DVES_EAA038
1623337649: Received SUBSCRIBE from DVES_EAA038
1623337649: 	cmnd/tasmotas/# (QoS 0)
1623337649: Sending SUBACK to DVES_EAA038
1623337649: Received SUBSCRIBE from DVES_EAA038
1623337649: 	cmnd/DVES_EAA038_fb/# (QoS 0)
1623337649: Sending SUBACK to DVES_EAA038
1623337649: Received SUBSCRIBE from DVES_EAA038
1623337649: 	domoticz/out/# (QoS 0)
1623337649: Sending SUBACK to DVES_EAA038
1623337649: Received UNSUBSCRIBE from DVES_EAA038
1623337649: 	homeassistant/status
1623337649: Sending UNSUBACK to DVES_EAA038
1623337650: Received PINGREQ from DVES_032172

From syslog where there is more data sent by tasmota we can see:
Jun 10 17:09:00 serveur systemd[1]: Starting Clean php session files...
Jun 10 17:09:00 webcam-salon-2 ESP-MQT: Tentative de connexion...
Jun 10 17:09:00 webcam-salon-2 ESP-MQT: Connecté
Jun 10 17:09:00 webcam-salon-2 ESP-MQT: tele/webcam-2/LWT = Online (persistant)
Jun 10 17:09:00 webcam-salon-2 ESP-MQT: cmnd/webcam-2/POWER = 
Jun 10 17:09:00 webcam-salon-2 ESP-MQT: S'abonner à cmnd/webcam-2/#
Jun 10 17:09:00 webcam-salon-2 ESP-MQT: S'abonner à cmnd/tasmotas/#
Jun 10 17:09:00 webcam-salon-2 ESP-MQT: S'abonner à cmnd/DVES_EAA038_fb/#
Jun 10 17:09:00 webcam-salon-2 ESP-MQT: S'abonner à domoticz/out/#
Jun 10 17:09:00 webcam-salon-2 ESP-MQT: Se désabonner de homeassistant/status
Jun 10 17:09:00 serveur systemd[1]: phpsessionclean.service: Succeeded.
Jun 10 17:09:00 serveur systemd[1]: Started Clean php session files.
Jun 10 17:09:01 serveur CRON[5799]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Jun 10 17:09:17 serveur systemd[1]: Started Session 64 of user pi.
Jun 10 17:09:18 serveur systemd[1]: session-64.scope: Succeeded.
Jun 10 17:09:45 serveur npm[692]: #033[32mZigbee2MQTT:info #033[39m 2021-06-10 17:09:45: MQTT publish: topic 'zigbee2mqtt/Routeur CC2530', payload '{"led":false,"linkquality":55}'
Jun 10 17:10:01 serveur CRON[5921]: (pi) CMD (/home/pi/domoticz/scripts/check-domoticz-active.sh >/dev/null 2>&1)
Jun 10 17:10:29 webcam-salon-2 ESP-MQT: Tentative de connexion...
Jun 10 17:10:29 webcam-salon-2 ESP-MQT: Connecté
Jun 10 17:10:29 webcam-salon-2 ESP-MQT: tele/webcam-2/LWT = Online (persistant)
Jun 10 17:10:29 webcam-salon-2 ESP-MQT: cmnd/webcam-2/POWER = 
Jun 10 17:10:29 webcam-salon-2 ESP-MQT: S'abonner à cmnd/webcam-2/#
Jun 10 17:10:29 webcam-salon-2 ESP-MQT: S'abonner à cmnd/tasmotas/#
Jun 10 17:10:29 webcam-salon-2 ESP-MQT: S'abonner à cmnd/DVES_EAA038_fb/#
Jun 10 17:10:29 webcam-salon-2 ESP-MQT: S'abonner à domoticz/out/#
Jun 10 17:10:29 webcam-salon-2 ESP-MQT: Se désabonner de homeassistant/status
Jun 10 17:10:40 webcam-salon-2 ESP-MQT: tele/webcam-2/STATE = {"Time":"2021-06-10T16:10:29","Uptime":"0T08:12:51","UptimeSec":29571,"Heap":121,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":22109,"MqttCount":116,"POWER":"OFF","Dimmer":94,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"SFR_B7A8","BSSId":"E4:5D:51:69:B7:AE","Channel":11,"RSSI":78,"Signal":-61,"LinkCount":1,"Downtime":"0T00:00:05"}}
Jun 10 17:10:40 webcam-salon-2 ESP-MQT: domoticz/in = {"idx":161,"nvalue":0,"svalue":"27.9;43.2;1;985.6;5","Battery":100,"RSSI":7}
Jun 10 17:10:40 webcam-salon-2 ESP-MQT: tele/webcam-2/SENSOR = {"Time":"2021-06-10T16:10:29","BME280":{"Temperature":27.9,"Humidity":43.2,"DewPoint":14.2,"Pressure":985.6},"ESP32":{"Temperature":51.7},"PressureUnit":"hPa","TempUnit":"C"}
Jun 10 17:10:40 webcam-salon-2 ESP-RUL: TELE-ESP32#TEMPERATURE performs "publish domoticz/in {"idx":160,"svalue":"51.7;1"}"
Jun 10 17:10:40 webcam-salon-2 ESP-SRC: Rule
Jun 10 17:10:40 webcam-salon-2 ESP-CMD: Groupe 0, Index 1, Commande "PUBLISH", Donnée "domoticz/in {"idx":160,"svalue":"51.7;1"}"
Jun 10 17:10:40 webcam-salon-2 ESP-MQT: domoticz/in = {"idx":160,"svalue":"51.7;1"}
Jun 10 17:10:43 serveur npm[692]: #033[32mZigbee2MQTT:info #033[39m 2021-06-10 17:10:43: MQTT publish: topic 'zigbee2mqtt/Lumière WC haut', payload '{"linkquality":55,"state":"OFF"}'
Jun 10 17:10:45 serveur npm[692]: #033[32mZigbee2MQTT:info #033[39m 2021-06-10 17:10:45: MQTT publish: topic 'zigbee2mqtt/Routeur CC2530', payload '{"led":false,"linkquality":55}'
Jun 10 17:11:45 serveur npm[692]: #033[32mZigbee2MQTT:info #033[39m 2021-06-10 17:11:45: MQTT publish: topic 'zigbee2mqtt/Routeur CC2530', payload '{"led":false,"linkquality":55}'
Jun 10 17:11:58 webcam-salon-2 ESP-MQT: Tentative de connexion...
Jun 10 17:11:58 webcam-salon-2 ESP-MQT: Connecté
Jun 10 17:11:58 webcam-salon-2 ESP-MQT: tele/webcam-2/LWT = Online (persistant)
Jun 10 17:11:58 webcam-salon-2 ESP-MQT: cmnd/webcam-2/POWER = 
Jun 10 17:11:58 webcam-salon-2 ESP-MQT: S'abonner à cmnd/webcam-2/#
Jun 10 17:11:58 webcam-salon-2 ESP-MQT: S'abonner à cmnd/tasmotas/#
Jun 10 17:11:58 webcam-salon-2 ESP-MQT: S'abonner à cmnd/DVES_EAA038_fb/#
Jun 10 17:11:58 webcam-salon-2 ESP-MQT: S'abonner à domoticz/out/#
Jun 10 17:11:58 webcam-salon-2 ESP-MQT: Se désabonner de homeassistant/status
Jun 10 17:12:45 serveur npm[692]: #033[32mZigbee2MQTT:info #033[39m 2021-06-10 17:12:45: MQTT publish: topic 'zigbee2mqtt/Routeur CC2530', payload '{"led":false,"linkquality":55}'
Jun 10 17:13:29 webcam-salon-2 ESP-MQT: Tentative de connexion...
Jun 10 17:13:29 webcam-salon-2 ESP-MQT: Connecté
Jun 10 17:13:29 webcam-salon-2 ESP-MQT: tele/webcam-2/LWT = Online (persistant)
Jun 10 17:13:29 webcam-salon-2 ESP-MQT: cmnd/webcam-2/POWER = 
Jun 10 17:13:29 webcam-salon-2 ESP-MQT: S'abonner à cmnd/webcam-2/#
Jun 10 17:13:29 webcam-salon-2 ESP-MQT: S'abonner à cmnd/tasmotas/#
Jun 10 17:13:29 webcam-salon-2 ESP-MQT: S'abonner à cmnd/DVES_EAA038_fb/#
Jun 10 17:13:29 webcam-salon-2 ESP-MQT: S'abonner à domoticz/out/#
Jun 10 17:13:29 webcam-salon-2 ESP-MQT: Se désabonner de homeassistant/status
Jun 10 17:13:45 serveur npm[692]: #033[32mZigbee2MQTT:info #033[39m 2021-06-10 17:13:45: MQTT publish: topic 'zigbee2mqtt/Routeur CC2530', payload '{"led":false,"linkquality":52}'

Some additional informations:
 - the wireless connection is good with signal AP1 SSID (RSSI) | XXXXX (86%, -57 dBm)
 - when having the issue if I restart the device works back for an unpredictable period of time.
 - when having the issue if I restart the raspberry it works back for an unpredictable period of time.

I am totally lost, I have reported this issue to tasmota github and get back that this is not an issue with the firmware.

Any help would be a lot appreciated

[mosquitto.log](https://github.com/eclipse/mosquitto/files/6632525/mosquitto.log)

**Comment by Enjoy-Combi** [comment]
I installed a broker on another raspberry with raspberry OS 64 / mosquitto v1.5.7.
Less socket error but still there:

1623338519: New connection from 192.168.1.5 on port 1883.
1623338519: New client connected from 192.168.1.5 as DVES_EAA038 (c1, k30, u'DVES_USER').
1623339329: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623341130: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623342931: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623344732: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623346533: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623348334: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623350135: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623351936: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623353737: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623355538: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623356090: Socket error on client DVES_EAA038, disconnecting.
1623356094: New connection from 192.168.1.5 on port 1883.
1623356094: New client connected from 192.168.1.5 as DVES_EAA038 (c1, k30, u'DVES_USER').
1623357339: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623359140: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623360941: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623362742: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623364511: Client DVES_EAA038 has exceeded timeout, disconnecting.
1623364511: Socket error on client DVES_EAA038, disconnecting.
1623364543: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623364543: New connection from 192.168.1.5 on port 1883.
1623364543: New client connected from 192.168.1.5 as DVES_EAA038 (c1, k30, u'DVES_USER').
1623364543: Socket error on client DVES_EAA038, disconnecting.
1623364544: New connection from 192.168.1.5 on port 1883.
1623364544: New client connected from 192.168.1.5 as DVES_EAA038 (c1, k30, u'DVES_USER').
1623366344: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623368145: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623369946: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623371747: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623373548: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623375349: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623377150: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1623378951: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.



Would it be due to a timeout somewhere ?

**Comment by ralight** [comment]
I installed a broker on another raspberry with raspberry OS 64 / mosquitto v1.5.7.
Less socket error but still there:

> 1623338519: New client connected from 192.168.1.5 as DVES_EAA038 (c1, k30, u'DVES_USER').
> 1623356090: Socket error on client DVES_EAA038, disconnecting.

`k30` is a keepalive of 30 seconds, so if the client doesn't communicate within 45 seconds it will be disconnected. The logs aren't sufficiently detailed to know whether that is the case (use `log_type debug` to get logs on each message)

> 1623356094: New client connected from 192.168.1.5 as DVES_EAA038 (c1, k30, u'DVES_USER').
> 1623364511: Client DVES_EAA038 has exceeded timeout, disconnecting.
> 1623364511: Socket error on client DVES_EAA038, disconnecting.

This one definitely timed out.

> 1623364543: New connection from 192.168.1.5 on port 1883.
> 1623364543: New client connected from 192.168.1.5 as DVES_EAA038 (c1, k30, u'DVES_USER').
> 1623364543: Socket error on client DVES_EAA038, disconnecting.

This one definitely didn't. 

In the log you posted from version 2.0.11 there are more details on what happened rather than just "Socket error".

> 1623267467: New client connected from 192.168.1.5:53358 as DVES_EAA038 (p2, c1, k30, u'DVES_USER').
> 1623267588: Client DVES_EAA038 closed its connection.

This means that the server saw the connection be closed by the client. It tried to make a read or write with the socket and was told by the OS that it was closed, so it reports it as closed. There's really not much else I can say about it I'm afraid - I'm going to do the same as tasmota and say that everything is fine here, so it must be them... Not much help I realise.

Something that you could do is get a wireshark/tcpdump capture of when this is happening, then we can look at the sequence of TCP packets to see exactly what is closing the connection first, and if we get any other hints from it. If you do manage to get a dump and don't want to share it in public then let me know.

**Comment by Enjoy-Combi** [comment]
Hi,


Many thanks for you post. I start to beleive there is nothing wrong with the firmware, mosquitto or the devices.
I fear this is either due to the supply or an issue with my router.

I have increased to log level to the maximum. tcpdump is now ready for on the computer where mosquitto is.
I have now skills on TCP packets analysis, then it is a case where I should learn many things :-)
Thank you again !

**Comment by Enjoy-Combi** [comment]
Hi,

Apparently going ahead with the troubleshooting. I get the issue when starting motioneye which challenge the devices (in terms of wireless connection, then consumption).
The device get hotter and start lagging.

I beleive that my supply is not power enough in those conditions.
I should have all log including a tcpdump. @ralight , how can send the files to you ?

Many thanks

**Comment by Enjoy-Combi** [comment]
Finally, it was a power issue.
I was powering the board through a powerful supply + ESP32-CAM-MB USB Programmer---> the ESP32-CAM-MB USB Programmer limits the power to the board and I get the issue.
I was powering the board with the supply of 700ma / 5V max ---> same issue.
With a supply with more than 1 Amp directly connected to the 5v pin ---> perfect !

**Comment by ralight** [comment]
Excellent, I wouldn't have thought of that. I'm glad you've got it sorted.
