### ISSUE TITLE
With per_listener_settings to true, global port setting is used

### ISSUE THREAD

**Issue by MarcHamel** [eclipse/mosquitto#2231]
In the version 2.0.11, it is written:

```
# =================================================================
# Listeners
# =================================================================

# Listen on a port/ip address combination. By using this variable
# multiple times, mosquitto can listen on more than one port. If
# this variable is used and neither bind_address nor port given,
# then the default listener will not be started.
```

My understanding of that is if I use listeners only then only ports defined on them will be open. So with the following config I expect to open only port 1884 but Mosquitto starts ports 1884 and 1883.

```
per_listener_settings true
allow_anonymous false
password_file c:\auth.txt
listener 1884
```

The workaround to open only port 1884 is to use global settings by setting per_listener_settings to false. With that bug it seem that if I want to use multiple listeners with per_listener_settings then I will also have the default port opened.

**Comment by ralight** [comment]
If you use `allow_anonymous` without first specifying a listener, then the default listener is activated.

Try this instead:

```
per_listener_settings true
password_file c:\auth.txt
listener 1884
allow_anonymous false
```

**Comment by MarcHamel** [comment]
I tried (port number is different it doesn`t matter) and same thing (see image below). BTW I am under Windows 10 64 bit. 

![test](https://user-images.githubusercontent.com/51212452/122264630-bc5bf180-cea5-11eb-90ee-fa74d657357e.png)

**Comment by ralight** [comment]
Sorry, I wasn't attention it seems! The `password_file` option also enables the default listener, so you really want the below. The idea is that you define the listener, then list the options that are relevant to it.

```
per_listener_settings true
listener 1884
allow_anonymous false
password_file c:\auth.txt
```

**Comment by MarcHamel** [comment]
Seems to work. thanks
________________________________
From: Roger Light ***@***.***>
Sent: Wednesday, June 16, 2021 13:39
To: eclipse/mosquitto ***@***.***>
Cc: Marc Hamel ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [eclipse/mosquitto] With per_listener_settings to true, global port setting is used (#2231)


Sorry, I wasn't attention it seems! The password_file option also enables the default listener, so you really want the below. The idea is that you define the listener, then list the options that are relevant to it.

per_listener_settings true
listener 1884
allow_anonymous false
password_file c:\auth.txt
