### ISSUE TITLE
message callback execute repeatedly while receiving duplicate QoS2 publish message 

### ISSUE THREAD

**Issue by Xsuns** [eclipse/mosquitto#2235]
hi,   everyone.
I'm intergating libmosquitto(extended thread) into a proxy. host is ubuntu/Linux, and the library version is v2.0.8.

I found message callback would execute repeatedly while receiving duplicate QoS2 publish message.

following pictures are my proxy print:
![m20_publish](https://user-images.githubusercontent.com/50979013/122858012-1ea46e80-d34c-11eb-8fe5-8e0b9fee71b6.png)
![m20_publish_duplicate](https://user-images.githubusercontent.com/50979013/122858022-2237f580-d34c-11eb-8a5f-403e2d15ab07.png)
![m20_pubrec_callback](https://user-images.githubusercontent.com/50979013/122859690-fc602000-d34e-11eb-934b-984edb613e9e.png)
![m20_pubrec_callback_dup](https://user-images.githubusercontent.com/50979013/122859692-fd914d00-d34e-11eb-95d6-cb5c59c7da35.png)

you can see the first `[ ]` is timestamp and recoginize they are different message.`net.c:411` is in my message callback function.

 is it a bug? or do I use library incorrectly?

**Comment by karlp** [comment]
Is your callback completing successfully?  If you're failing, it will be considered undelivered.

**Comment by Xsuns** [comment]
it completes and type of return code is void.

**Comment by Xsuns** [comment]
> Is your callback completing successfully? If you're failing, it will be considered undelivered.

it completes and type of return code is void.

**Comment by Xsuns** [comment]
hi  @karlp , I build library without `WITH_BROKER` macro. In this situation, If library receives several same id **PUBLISH** messages before receiving **PUBREL** from broker, message callback will execute repeatedly.

I think the reason is function `handle__pubrel` remove and clean up only one message during once call.

**Comment by Xsuns** [comment]
According [issue #1751](https://github.com/eclipse/mosquitto/issues/1751), I check MQTT Specifications. [Chapter 4.4](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901238) mentions that

_When a Client reconnects with Clean Start set to 0 and a session is present, both the Client and Server MUST resend any unacknowledged PUBLISH packets (where QoS > 0) and PUBREL packets using their original Packet Identifiers. This is the only circumstance where a Client or Server is REQUIRED to resend messages. Clients and Servers MUST NOT resend messages at any other time_

So the problem is our broker dosen't comply with the standard completely.
