### ISSUE TITLE
 mosquitto.org is down

### ISSUE THREAD

**Issue by takiainen** [eclipse/mosquitto#2237]
You website mosquitto.org is down.

**Comment by ralight** [comment]
Thanks, I've given it a nudge and it's working again.

**Comment by 1979139113** [comment]
You website mosquitto.org is down, again
![image](https://user-images.githubusercontent.com/24983597/133728106-dc11bf68-8365-44da-be62-3730a079f790.png)

**Comment by Nonegrace** [comment]
Yes, your website is down today.
