### ISSUE TITLE
Whether the length of the salt should be changed to 16 ?

### ISSUE THREAD

**Issue by fengqiusuo** [eclipse/mosquitto#2239]
https://github.com/eclipse/mosquitto/blob/b7c3d52cd4183ae7d4fb0b798cab679225e3f688/src/password_mosq.c#L60
Hi Team,
    In use, some people think that the length of salt is too short. So I looked up some information on the Internet, which wiki said "The SHA2-crypt and bcrypt methods—used in Linux, BSD Unixes, and Solaris—have salts of 128 bits. These larger salt values make precomputation attacks for almost any length of password infeasible against these systems for the foreseeable future."
    So I wonder whether the length of salt should be changed to 16 would be better. 
Thanks in advance

**Comment by ralight** [comment]
The salt length is now 64 bytes, which is the same length as the hash itself. It will be part of 2.1.0.

**Comment by fengqiusuo** [comment]
Thank you very much.
