### ISSUE TITLE
mosquitto Stops accepting Websocket Connections

### ISSUE THREAD

**Issue by anubhav7495** [eclipse/mosquitto#224]
I have mosquitto broker v1.4.9 running on AWS EC2 on ubuntu 14.04.

After a day or two, the broker stops accepting new connections with this error in browser: 

```
WebSocket connection to 'ws://xx.xxx.xxx.xx:8080/mqtt' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

The Broker accepts connections over tcp on port 1883 through android service and python client. It only rejects websocket connections.

My Locally Running Mosquitto Broker on v1.4.8 works just fine.

My `mosquitto.conf`

```
# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d
```

My `conf.d/main.conf` file:

```
listener 8080
protocol websockets

listener 1883
```

**Comment by ralight** [comment]
What version of libwebsockets are you using?

**Comment by anubhav7495** [comment]
version 1.2.2-1

**Comment by ralight** [comment]
Please consider upgrading to libwebsockets 1.7.x, 1.2.2 is ancient and not well supported in mosquitto.

**Comment by anubhav7495** [comment]
It Happened again. do i need to rebuild the from mosquitto source ?

**Comment by anubhav7495** [comment]
I have libwebsockets 1.7.8 now and it still happens.

**Comment by anubhav7495** [comment]
Shifted to Mosquitto 14.8 on ubuntu 16.04LTS and it is working fine for last 6 days.

--> tried using 1.4.9 again and it crashed in like 8 hours.

--> I think something is wrong between these two versions that breaks websockets

**Comment by Asoul** [comment]
If the server is failed after several hours, I guess maybe some tcp connections not closed well. And exceed the max tcp connections.

Could you try to check the opening connection is closed?

```
ss -s 
```

**Comment by koraysels** [comment]
I have the same issue.. last lines in de log before he shuts down : 

```
1485944870: Socket error on client mqttjs_d191aa74, disconnecting.
1485944870: Socket error on client mqttjs_69234382, disconnecting.
1485944872: New client connected from 84.196.75.214 as mqttjs_d191aa74 (c1, k10, u'mosquitto').
1485944872: New client connected from 84.196.75.214 as mqttjs_69234382 (c1, k10, u'mosquitto').
1485944878: Socket error on client mqttjs_69234382, disconnecting.
```

**Comment by krich11** [comment]
I am having that same issue.  Sometimes it's connection refused for websockets, sometimes it's for the mqtt, sometimes it's both.  It seems like after a mosquitto service restart it will happen again within 24-48 hours.

I have eliminated the service serving on IPv6 interfaces by specifying the IPv4 interface in the config file for both mqtt and websockets:

```
protocol mqtt
listener 1883 192.168.0.5
protocol websockets
listener 8080 192.168.0.5
```

This seems to have eliminated my issue (so far).  I'm about 72 hours into it.

**Comment by leonardopa** [comment]
I am having that same issue.  It is not by time ,  Mosquitto exceeds the file limit SO.  
any ideas ?

**Comment by PierreF** [comment]
Are you still facing this issue ?
It has some common point with #647 and #629: it seems that the listening FD get closed.

**Comment by krich11** [comment]
Yes, but it stopped happening as frequently once I disabled listening on IPv6.  I have since set up a cron job to restart the service each night.  This is effective, but ignoring the problem.  Very occasionally, the 24 hour restart still does not prevent the issue.

I would be willing to enable any logs you think may be helpful in tracking this down.  Please advise.

I reviewed the other two reports and I do agree they may sound similar.  I will have to wait until it happens again so I can compare.

**Comment by ralight** [comment]
@krich11 Could you provide more details of your setup please? Mosquitto version, libwebsockets version, OS, how many clients you are using would all be useful information.

**Comment by ralight** [comment]
This has been without a response for a long time now, and both Mosquitto and libwebsockets have had lots of releases, so I'm closing this issue. If it's still a problem, please reopen and provide more information.
