### ISSUE TITLE
Broker Hang on Bad Configuration

### ISSUE THREAD

**Issue by PBearson** [eclipse/mosquitto#2241]
Mosquitto Version: 2.0.11 (also tested in version 2.0.7 and 1.5)
Platform: Kali 2021.2 and Ubuntu 20.04

There seems to an issue with the broker hanging when the configuration file is given an improper `password_file` argument. Specifically, it seems like the broker hangs when `password_file` is given a directory name instead of a file name, for example:

```
password_file /
```

You can see from the following screenshot that the broker appears to load the config file, but it does not advance after that. 

![image](https://user-images.githubusercontent.com/11084018/123692643-11442400-d825-11eb-82ec-6f75815043af.png)

After some debugging, I found that the program appears to get stuck in [this loop indefinitely](https://github.com/eclipse/mosquitto/blob/b7c3d52cd4183ae7d4fb0b798cab679225e3f688/src/security_default.c#L765).

**Comment by ralight** [comment]
Thanks very much, this is now fixed in the `fixes` branch and will be part of 2.0.12.
