### ISSUE TITLE
mount_point not removed on outgoing messages (version 2)

### ISSUE THREAD

**Issue by alflexRH** [eclipse/mosquitto#2244]
Version: current 2.0.11 from docker

mosquitto.conf:
per_listener_settings true

listener 1883
protocol mqtt
allow_anonymous true

listener 1884
protocol mqtt
mount_point foo/
allow_anonymous true

Client A: `mosquitto_sub -t '#' -p 1883 -v`
Client B: `mosquitto_sub -t '#' -p 1884 -v`

With mosquitto 2.0.11:
When sending with `mosquitto_pub -t 'bas' -m 'hi' -p 1884`:
Client A: foo/bas hi -- As expected. The mount_point foo/  is prepended to 'bas', and it arrives as coming from 'foo/bas'. 
Client B: foo/bas hi -- Not as expected. The mount_point foo/  should have been removed.

With mosquitto 1.6:
When sending with `mosquitto_pub -t 'bas' -m 'hi' -p 1884`:
Client A: foo/bas hi -- As expected. The mount_point foo/  is prepended to 'bas', and it arrives as coming from 'foo/bas'. 
Client B: bas hi -- As expected. the mount_poiint foo/ is removed, and it arrives as coming from 'bas'

**Comment by DanielPeinhopf** [comment]
Yep, i can also confirm this in v2.0.11.

**Comment by D-r-P-3-p-p-3-r** [comment]
Same problem here (also 2.0.11).

**Comment by ralight** [comment]
Thank you, that is now fixed and will be part of 2.0.12 shortly. I've also improved the mount point test to cover this situation.
