### ISSUE TITLE
mosq->current_out_packet_mutex's unlock position is incorrect

### ISSUE THREAD

**Issue by pengyuhuan** [eclipse/mosquitto#2245]
in file lib/connect.c, at the end of function do_client_disconnect, has one line of code: pthread_mutex_unlock(&mosq->current_out_packet_mutex);

 the mutex  is locked out of the function, cause confusion， The correct way is to lock and unlock in the same function。

**Comment by ralight** [comment]
current_out_packet_mutex hsa been removed in the `develop` branch, so I don't think this is relevant any more.
