### ISSUE TITLE
Typo in man-page for mosquitto_passwd

### ISSUE THREAD

**Issue by Nabytovych** [eclipse/mosquitto#225]
Please, fix typo:
> Description
> mosquitto_passwd is a tool for managing password files <B>the the</B> mosquitto MQTT broker.

on the mosquitto_passwd man-page:
https://mosquitto.org/man/mosquitto_passwd-1.html#idm122454815612160

**Comment by ralight** [comment]
Thanks, that's fixed in the repo.
