### ISSUE TITLE
Published Message only received by one connected web application

### ISSUE THREAD

**Issue by leonski1** [eclipse/mosquitto#2250]
I am publishing to a web application (Apache) using Mosquitto running on my Raspberry Pi using this command:
`mosquitto_pub -d -t status  -m "message"`

The web application connects to the mosquitto broker using MQTT over websockets (Paho Client).

If I open the web application only on time, everything is fine and the application always receives the message.
But as soon as I open the web application for example on my phone, too, the only web application that receives a message is the one that has been refreshed last.
My goal is that any number of connected web applications can receive a published message at the same time. 

I also tried to add "-r" to the mosquitto_pub command so that the last message is retained. But then I always have to refresh the web application to receive a new message.

Does anybody know a solution to this problem?

**Comment by Daedaluz** [comment]
Would be good to know your broker version and perhaps look at some code.
But just with the behavior you are describing, it sounds like you might be using the same client-id for all web-clients.

Only one connection per client is allowed. If you do connect with the same client id - the old one will be disconnected by the broker and the new connection will take over.

**Comment by leonski1** [comment]
Thanks for the response! I found the solution. As you suggested I used the same ID every time.
Thank you very much for your help!
