### ISSUE TITLE
Is there a web GUI for mosquitto user and ACL mangement - maybe from a 3rd-party developer...?

### ISSUE THREAD

**Issue by jayjupdhig** [eclipse/mosquitto#2254]
Hi there

Question: As the title says: Is there a web GUI for mosquitto user and ACL mangement - maybe from a 3rd-party developer...?

Does somebody know this?

Thank you for your feedbacks.

With kind regards, Jan

**Comment by abiliojr** [comment]
Cedalo (the current sponsor of Mosquitto) offers a [Management Center](https://docs.cedalo.com/management-center/2.2/mc-overview/). It seems to be free of use for 1 broker.

Does this help?

**Comment by ralight** [comment]
I think this has been answered, so I'm closing the issue. If you need more information, please ask!
