### ISSUE TITLE
Use mosquitto as a forward proxy?

### ISSUE THREAD

**Issue by jayjupdhig** [eclipse/mosquitto#2259]
Problem: Some of our client devices don't support tls/ssl (over port 8883) well... but out MQTT service broker (Cloud Saas) only have port 8883 connections.

So: How can i use mosquitto as a forward proxy?

OUR_NON_SSL_MQTT_DEVICES -> MOSQUITTO_AS_A_FORWARD_PROXY -> OUT_MQTT_SERVICE_BROKER_CLOUD

thank you for your feedbacks.

**Comment by Daedaluz** [comment]
Not sure how your requirements looks like, but you could have a local running mosquitto with a configured bridge to your cloud broker.

There is no direct "proxy" like function in mosquitto that I'm aware of.

This bridge method would not forward identity for example.
Your cloud server would see all those devices coming from one user / client (the bridge) and your devices would connect to the local broker.

**Comment by ptjm** [comment]
You can set up a bridge with a config file like this:

```
listener 1883 myhost.example.com
allow_anonymous false
password_file mosquitto.passwd

connection cloud
address cloud.example.com:8883
bridge_capath mosquitto-ca-path
remote_username example-user
remote_password example-password
topic # out 0
topic example/# in 0
```

As Daedaluz notes, on the cloud broker, you'll have one user, which will need access to all the topics used by any client that connects to the local broker.

A completely different approach which might work for you is to set up a TLS tunnel using stunnel. For that you'd set up a config something like this:

```
[mqtt-cloud]
client = yes
accept = myhost.example.com:1883
connect = cloud.example.com:8883
verifyChain = yes
CApath = mosquitto-ca-path
```

This will just bounce your data directly to the cloud mqtt broker and your client can authenticate against it directly.

**Comment by abiliojr** [comment]
Not sure about your requirements, but another alternative is to use HAProxy, which could be configured to filter unintended traffic (not trivial settings though). If your proxy This can become useful if you want other people that use the same cloud provider to take advantage of your publicly available proxy (if that's the case, of course).

**Comment by gdt** [comment]
This isnt' a bug report; probably best to close it and ask on the list.

**Comment by jayjupdhig** [comment]
Thank you very much for your fast feedback - will look on it ASAP! :-)

**Comment by jayjupdhig** [comment]
Closed... :-)
