### ISSUE TITLE
Problem enabling websocket on version 1.6.9

### ISSUE THREAD

**Issue by ProgrammingPlanet** [eclipse/mosquitto#2262]
I'm using mosquito on Ubuntu 20.04 with official apt repo installation.

When I enable websocket by insert two lines 

listener 9001
protocol websocket

In /etc/mosquito/conf.d/defaults.conf

on restarting broker, command return with error say process exited with error, check journalctl -xe but nothing error there.

And when I check the listings ports, that default tcp port 1883 stops and only 9001 showing.

I didn't try connecting websocket because I need to run both.

OS - Ubuntu 20.04
Mosquito - 1.6.9 by apt repo

**Comment by ralight** [comment]
Did you explicitly define the 1883 listener? If not, it won't be created once you specify another listener.

Alternatively, is there another process running on port 9001 that means Mosquitto cannot start?

**Comment by ralight** [comment]
It seems as though this error comes about if libwebsockets is compiled without the LWS_WITH_EXTERNAL_POLL flag, and if only a single websockets only listener is defined.
