### ISSUE TITLE
Mosquitto subscriber doesn't receive messages after broker is restarted

### ISSUE THREAD

**Issue by HDenied** [eclipse/mosquitto#2265]
I think there is an issue with the broker here as this functionality works use verneMQ

**Env**:
Mosquitto version: b7c3d52 on 10 Jun -> Running on a real server no docker
OS: Debian 10

Library use: paho-mqtt==1.5.1 (Python)

**How to reproduce the issue:**

1 - Make sure broker works
2 - Use these files: [pub](https://github.com/eclipse/paho.mqtt.python/blob/master/examples/client_pub_opts.py) and [sub](https://github.com/eclipse/paho.mqtt.python/blob/master/examples/client_sub_opts.py) but make sure to adopt protocol MQTTv5, so modify the files as follows for the steps below:

mqttc = mqtt.Client(args.clientid, protocol=mqtt.MQTTv5)
mqttc.connect(args.host, port, args.keepalive, clean_start=False)

And the function:

def on_subscribe(mqttc, userdata, mid, granted_qos, properties=None):
    print("Subscribed: " + str(mid) + " " + str(granted_qos))

3 - Run the following commands in 2 different windows:

- For publisher
python ./pub.py -H X.X.X.X -t /test -q 2 -c 0 -d -P 1883 -N 100 -S 1 -k 60 -D

- For subscriber
python ./sub.py -H X.X.X.X  -t /test -q 2 -c 8 -d -P 1883 -k 60 -D

4 - Restart the broker

**Expected behaviour:**

After the broker is restarted, the publisher and the subscriber should continue to tx/rx messages

**Bug**
I see the publisher gaining back the connection, the subscriber connects but doesn't receive any message

**Why I think this is a bug?**
On VerneMQ this works as expected on Mosquitto doesn't, it might not be the library then. In attachment some pics, first is Mosquitto, second VerneMQ

![mosquitto_fails](https://user-images.githubusercontent.com/35076965/127196521-a446d002-bb1a-48e7-8661-702968557fdc.png)

![vernemq_working](https://user-images.githubusercontent.com/35076965/127196626-0b7abb62-84e3-48b2-b5da-5edea13f98f1.png)

**Comment by Daedaluz** [comment]
I'm not sure mosquitto is the buggy broker here.

Your subscriber does not set the session expiry interval property on the connect packet.

Quoting from the mqttv5 specification:
"If the Session Expiry Interval is absent the value 0 is used. If it is set to 0, or is absent, the Session ends when the Network Connection is closed. "

Looking at the database after shutdown, your clients subscriptions are gone. Probably cleared after first disconnect because the session has ended (as i read it). When your subscriber reconnects it therefore starts a new session, without any subscriptions thus no longer receives any new messages.

Making this changes to the subscribing client:
```
import paho.mqtt.properties as props
import paho.mqtt.packettypes as types
....
connectProps = props.Properties(types.PacketTypes.CONNECT)
connectProps.SessionExpiryInterval = 3600
mqttc.connect(args.host, port, args.keepalive, clean_start=False, properties=connectProps)
```
will work.

I'm not sure if the other behavior is intended in verneMQ (as a tweak or something), but it might be a bug there.

**Comment by HDenied** [comment]
Thanks Daedaluz, what you said makes sense, indeed now I double checked:

"If the Clean Start in the CONNECT packet is 0 and there is a session associated with this client ID, the server must resume communication with the client based on the state of the session. If there is no session associated with this client ID, the server must create a new session."

 I think what concerns me is that no message at all is received in Mosquitto from sub perspective, The scenario is that both sub and pub gain back connection after broker restart and both with QOS=2. I would have expected the following behaviour:
- Pub reconnect and send packets starting from mid=1 because the session is not alive anymore, and clean_start=0
- Sub reconnects and receive anyway the packets starting from mid=1 as the session is not alive anymore, and clean_start=0

What you can see here is:
- Pub resumes connection from message 25 (somehow the session persists even if the session expires)
- Sub just connects and doesn't receive anything

In VerneMQ we see a mix of the 2:
- Pub reconnect and sends packets starting from last mid  even if session is not alive anymore, and clean_start=0, according to the standard as you said.
- Sub reconnects and receive anyway the packets starting from mid=1 as the session is not alive anymore, and clean_start=0

As you can see there are 2 different behaviours here, What you say works perfectly now and I even see old missed packages received by the subscriber, however, even if the broker wipes out any data related to the session a subscriber should still be able to receive new messages if it reconnects. Indeed if we think about it, the subscriber which reconnects again, is like a new subscriber, if it is not capable to receive any message from the publisher this would mean that any potential new subscriber shouldn't because there is no difference between a completely new subscriber and an old subscriber reconnecting with a session expired.

Am I missing something here? Thanks for the support!

**Comment by Daedaluz** [comment]
Looking more into the specification 4.1 (Session state);

"In order to implement QoS 1 and QoS 2 protocol flows the Client and Server need to associate state with the Client Identifier, this is referred to as the Session State. **The Server also stores the subscriptions as part of the Session State.**"

so, when the session ends, the current subscriptions are gone and in order to continue receiving new messages the client has to re-subscribe. (this part is missing in the client library i think, or up to the user of the library to handle)

also:
```
The Session State in the Server consists of:

·         The existence of a Session, even if the rest of the Session State is empty.

·         The Clients subscriptions, including any Subscription Identifiers.

·         QoS 1 and QoS 2 messages which have been sent to the Client, but have not been completely acknowledged.

·         QoS 1 and QoS 2 messages pending transmission to the Client and OPTIONALLY QoS 0 messages pending transmission to the Client.

·         QoS 2 messages which have been received from the Client, but have not been completely acknowledged.The Will Message and the Will Delay Interval

·         If the Session is currently not connected, the time at which the Session will end and Session State will be discarded.
```

I do not see MID as a part of session state, and I'm not sure it has any significance for new sessions / old sessions since it doesn't have to start at 1, just an unused one.

So, continuing from message 25 should not be seen as a sign of a resumed session.

**Comment by HDenied** [comment]
I understand, but why then the subscriber is not capable to get any message even if from scratch? Given the fact that the session is expired it should be considered a new user anyway, therefore still capable to read the message sent by the publisher.

**Comment by Daedaluz** [comment]
I believe it can get messages even from scratch. The client just has to redo it's subscriptions once re-connected.
If you move the `mqttc.subscribe(args.topic, args.qos)` part to inside the on_connect function and set properties back to none 
`mqttc.connect(args.host, port, args.keepalive, clean_start=False, properties=None)`
when connecting, you'll see that it continues to receive new messages even though session expiry interval is 0 and the broker restarts.

**Comment by HDenied** [comment]
I think you are right, it turned out that:
1 - the example in the library wasn't robust enough to keep into account the broker crashes
2 - As u said, VerneMQ has a different behaviour, but from a logic point of view it makes more sense to subscribe again in case the session has a clean_start set or session expired because there shouldn't be any memory of the connection, so Mosquitto in this regards looks closer to the standard.

I really appreciated your support, ur suggestion worked, thanks you very much, for me the issue is closed.

**Comment by Daedaluz** [comment]
Glad to be of help!
Please, don't forget to close the issue too if you think there is nothing more to clarify  :+1:
