### ISSUE TITLE
libwebsockets sometimes crash mosquitto

### ISSUE THREAD

**Issue by changqian9** [eclipse/mosquitto#227]
https://github.com/Geodan/gost/issues/40

I can repro this problem 2+ times on my machine. ubuntu 14.04 mosquitto 1.4.8 libwebsocket7

**Comment by ralight** [comment]
Which version of libwebsockets?

**Comment by cordovapolymer** [comment]
https://github.com/Geodan/gost/issues/40#issuecomment-242923469

**Comment by ralight** [comment]
Version 1.2.2 of libwebsockets is buggy and has features missing that are needed for mosquitto. I don't think attempting to support it is a useful use of anybodies time, so I'm going to close this bug.
