### ISSUE TITLE
mosquitto_ctrl create client with Clientid issue 

### ISSUE THREAD

**Issue by taichimaker** [eclipse/mosquitto#2273]
Hi 

My mosquitto version is 2.0.11. It runs on Ubuntu 20.04 LTS. I have setup the Dynamic Security Plugin and I am able to use the mosquitto_ctrl tool to create client wihtout any id. Everything works just fine. I mean I can add group role ACL etc. And assign clients to group and apply roles to groups etc. 

All in all everything works fine until I tried to create client with client id associated to the client. 

The command I am using is as the following:

`mosquitto_ctrl -u admin -h localhost dynsec createClient myClient -i clientid123`

The client myClient  is created by the abovce command. I can actually see the client name shown in the dynamic-security.json file. The following is the section related to the client I created with the above command. 

{
                        "username":     "myClient",
                        "roles":        [],
                        "password":     "...omitted...",
                        "salt": "...omitted...",
                        "iterations":   101
},

**But, as you can see no clientid is shown in the above code.** 

I did use the -i option in my command And I learnt from the dynamic-security plugin online manual that if I want to add client id I should us the following command. 

`mosquitto_ctrl <options> dynsec createClient <username> -i <client id>`

And that's just what I did. add -i then the client id. 

In addition, when using the getClient command, the system responses the following:

```
Username: myClient
Clientid:
```

This double confirms that the client id is not set for "myClient" I just created.

I also did more experiment by manually adding client id to the dynamic-security.json and chage the above json as the following. 

{
                        "username":     "myClient",
                        **"clientid":   "clientid123",**    <- I added this line by editing dynamic-security.json file
                        "roles":        [],
                        "password":     "...omitted...",
                        "salt": "...omitted...",
                        "iterations":   101
},

And then I restarted the mosquitto service. Now the client has clientid. I mean after making the aboce change to json file and restart the service  I had to use the triple of username password and clientid to connect broker. If I dont provide correct clientid. broker will refuse connection. This was not the case before my modification to the json file. 

I am not sure why I cannot use the -i <clientid> option in the mosquitto_ctrl command to add client with Clientid. Would you please check this out? Your time and efforts is very much appreciated!

**Comment by taichimaker** [comment]
This is to follow up the above issue. 
I tried to run mosquitto 2.0.11 on Ubuntu 18.04 LTS and still experience the same issue above. I also asked another seasoned mosquitto user. And he said he is having the same problem. Anyone can help with this? Thanks a lot!

**Comment by ptjm** [comment]
--i allows you to specify the client id for the mosquitto_ctrl connection. To set the client_id for the json file, use -c.

**Comment by ralight** [comment]
-c/-i is confusing, I think I'll add -i as an alias. The real issue here is that unknown options aren't being reported. I'll fix that as well. Thanks very much for the report.

**Comment by taichimaker** [comment]
Thanks a lot for your clarification. I used "-c" to create client with clientid and it works like a charm! Thanks for your awesome work. You guys rock.
