### ISSUE TITLE
mqtt5 no local option

### ISSUE THREAD

**Issue by brianmay** [eclipse/mosquitto#2274]
Does the mosquitto broker support the mqtt no local subscription option?

https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901169

Have been trying to use it, but appears to be ignored, and there doesn't appear to be any documentation to confirm or deny if it is supported. Don't want to spend a a lot of time debugging my code - which appears to be working - only to find that this isn't supported :-).

PS. I tried to subscribe to mosquitto-dev so I could ask there, but after verifying my new account it doesn't recognise my email address any more. I tried 2 times, and got identical results both times. So I can't actually login or reset my password even.

**Comment by ralight** [comment]
Yes it does support the no-local subscription option and there is a test to confirm it works.

I've added an example Python demo that shows this working: [nolocal.txt](https://github.com/eclipse/mosquitto/files/7024451/nolocal.txt)

**Comment by ralight** [comment]
Regarding the mailing list - I'm afraid that's largely out of my hands.

**Comment by brianmay** [comment]
Thanks for the sample code. It seems to work fine against my server.

But I guess I am going to have to stop blaming mosquitto now, and try to work out why this isn't working with my client.

**Comment by brianmay** [comment]
On 2nd thoughts, problem was PEBCAK. Message I thought was generated locally was actually being generated remotely, so was working as designed. Oops.

Thanks for your help.
