### ISSUE TITLE
Socket error on per_listener_settings

### ISSUE THREAD

**Issue by terasolu** [eclipse/mosquitto#2275]
My Mosquitto version is 1.5.7. Everything worked fine, I had the standard configuration in `/etc/mosquitto/mosquitto.conf` and the `/etc/mosquitto/conf.d/main.conf` looked like this:
```
listener 8883
tls_version tlsv1.3
cafile /home/files/certs/ca.crt
certfile /home/files/certs/cert.crt
keyfile /home/files/certs/key.key
require_certificate false
acl_file /etc/mosquitto/accesscontrol.acl
allow_anonymous false
password_file /etc/mosquitto/passwords.pwd
```

Then I edited this file to:
```
per_listener_settings true

listener 8883
tls_version tlsv1.3
cafile /home/files/certs/ca.crt
certfile /home/files/certs/cert.crt
keyfile /home/files/certs/key.key
require_certificate false
acl_file /etc/mosquitto/accesscontrol.acl
allow_anonymous false
password_file /etc/mosquitto/passwords.pwd

listener 8884
tls_version tlsv1.3
cafile /home/files/certsnew/ca.crt
certfile /home/files/certsnew/cert.crt
keyfile /home/files/certsnew/key.key
require_certificate false
acl_file /etc/mosquitto/accesscontrol.acl
allow_anonymous false
password_file /etc/mosquitto/passwords.pwd
```

This was necessary so I don't have to change the firmware on my IoT devices all at once, because they don't check the CA, they check the fingerprint.
I expected that nothing would change, but the result was that all those IoT devices stopped working and failed to connect with the error `Socket error on client <unknown>, disconnecting.`. This happened before when I used the wrong fingerprint, but openssl confirms it's the correct fingerprint.

But it's even worse. When removing the 8884 listener it still doesn't work. Just the added line `per_listener_settings true` seems to make the IoT devices stop connecting.

What am I missing?

**Comment by ralight** [comment]
I'll need to look into this, but in your case you shouldn't actually need `per_listener_settings`. The authentication you have is the same across both listeners, so it can remain global. The certificates are always applied to a single listener only.

**Comment by ralight** [comment]
This was fixed in a later version, you can work around it by setting `allow_zero_length_clientid true` in your config file.

**Comment by terasolu** [comment]
That's it! Thanks a lot! I would never have found that!
