### ISSUE TITLE
Run from snap problem

### ISSUE THREAD

**Issue by Zakys98** [eclipse/mosquitto#2278]
Sorry if this is not right place to write about that. I can delete it, if you want.

So i have installed mosquitto from snap.
It worked as expected and everything installed, but when i tried to run it from command line, it did not find it.
It is there but not in directory /snap/bin
In this direcotry are only there files:
./mosquitto_rr
./mosquitto.sub
./mosquitto_sub
./mosquitto.passwd
./mosquitto.pub
./mosquitto_pub
./mosquitto_passwd
./mosquitto.rr
./mosquitto.ctrl

Why mosquitto is not here ?

**Comment by ralight** [comment]
Mosquitto as a snap is installed as a service, so it isn't in the normal list of binaries. You could start it using the below, for example:

```
sudo systemctl start snap.mosquitto.mosquitto
```

Please also take into account the snap documentation: https://mosquitto.org/documentation/using-the-snap/
