### ISSUE TITLE
Broker does not respond when changing date/time on Windows

### ISSUE THREAD

**Issue by tassi-yuzukko** [eclipse/mosquitto#2282]
Hi.

I'm using mosquitto broker and mosquitto client DLL (mosquitto.dll) on Windows 10 Pro (ver 20H2, build 19042.1110)

I am having following problem:

* if the Windows date/time is changed (like 17:00:00 -> 18:00:00) while the broker is running, the request to the broker will not be processed correctly immediately afterwards.
  (e.g. running 'connect' does not return a response from broker.)
* however, if the request to the broker is executed in the same way after a few seconds have passed, it will be processed correctly.

Is it a known behavior?
Also, if anyone has any suggestions on how to deal with this, please let me know.

**Comment by ralight** [comment]
Thanks for the report, I'll look into it.

**Comment by tassi-yuzukko** [comment]
@ralight

Hello, Roger.
After a lot of research, I found out that there was a problem with my environment.
There does not seem to be any problem with changing date/time in mosquitto.
I'm sorry for wasting your time and I also apologize to the community for the noise.
