### ISSUE TITLE
Default config allows remote, anonymous access, contrary to documentation.

### ISSUE THREAD

**Issue by hraftery** [eclipse/mosquitto#2283]
FreeBSD 12.2, install latest mosquitto binary (2.0.8).

According to the documentation in the config file, and [this migration page](https://mosquitto.org/documentation/migrating-to-2-0/), leaving the configuration file in with default `listener` and `allow_anonymous` settings (ie. not defined) should result in a Broker that actually accepts anonymous users but only on the local machine.

I found that having specified a `password_file`, that the Broker actually accepts **remote** connections from **anonymous** users!

To recreate the issue, simply install FreeBSD 12.2 fresh, run `pkg install mosquitto` and then only add `password_file /usr/local/etc/mosquitto/pwfile` to the conf file. Something has to be done about the pid file bug (either make the `/var/run` directory world writable, or create `/var/run/mosquitto` directory and set permissions to it separately), but once that's done, run the Broker with `/usr/local/sbin/mosquitto -v -c /usr/local/etc/mosquitto/mosquitto.conf` or by enabling in `rc.conf` and using `service mosquitto start`. Either way, clients will now be able to connect to the Broker over the Internet without specifying a username and password.

I was not able to affect this behaviour with various permutations of security settings. There also appears be nothing relevant in the release notes for Mosquitto since 2.0.8, and I can't see how this would be specific to FreeBSD.

I **was** able to restore expected behaviour by adding `listener 1883` to the configuration file. Doing so and restarting the Broker results in it no longer accepting connections from clients unless the correct credentials are supplied.

**Comment by ralight** [comment]
This is definitely a bug in mosquitto. The configuration file uses the `cafile` option without specifying a listener (which is a bit odd), and the bug is that one part of the code thinks that means a listener has been defined, and so it should be accessible to the internet, but another part doesn't consider that the listener has been defined so anonymous access wasn't disabled.

Thanks for the report, this will be part of 2.0.12 shortly.
