### ISSUE TITLE
SSL_CTX is not cleared on disconnect - it conflicts with default MOSQ_OPT_SSL_CTX_WITH_DEFAULTS

### ISSUE THREAD

**Issue by PoltoS** [eclipse/mosquitto#2288]
When no SSL_CTX is specified by the user, no MOSQ_OPT_SSL_CTX_WITH_DEFAULTS set (so by default mosq->ssl_ctx_defaults is true), on first run mosq->ssl_ctx is null, while on second it is already not null and it fall in the error here: https://github.com/eclipse/mosquitto/blob/master/lib/net_mosq.c#L671

So mosq_disconnect and then mosq_connect again will fail.

You should save the SSL_CTX defined by the user in another veriable mosq->user_ssl_ctx and copy it before each connect to ssl_ctx and clear in disconnect.

**Comment by ralight** [comment]
Fixed in my local repo and will be part of 2.0.12 soon.

**Comment by ralight** [comment]
Thanks for the report!
