### ISSUE TITLE
mosquitto-auth-plug make error

### ISSUE THREAD

**Issue by xcmonline** [eclipse/mosquitto#2293]
edit config.mk

BACKEND_MYSQL ?= yes
MOSQUITTO_SRC =/soft/mosquitto/mosquitto-2.0.11
OPENSSLDIR = /usr/lib

make 

[root@host mosquitto-auth-plug-0.1.3]# make clean
rm -f *.o *.so np
(cd contrib/tinycdb-0.78; make realclean )
make[1]: Entering directory `/soft/mosquitto/mosquitto-auth-plug-0.1.3/contrib/tinycdb-0.78'
rm -f *.o *.lo core *~ libcdb[._][aps]* libnss_cdb.so.2* cdb cdb-shared
make[1]: Leaving directory `/soft/mosquitto/mosquitto-auth-plug-0.1.3/contrib/tinycdb-0.78'
[root@host mosquitto-auth-plug-0.1.3]# make
Selected backends:          MySQL
Using mosquitto source dir: /soft/mosquitto/mosquitto-2.0.11
OpenSSL install dir:        /usr/lib

If you changed the backend selection, you might need to 'make clean' first

CFLAGS:   -I/soft/mosquitto/mosquitto-2.0.11/src/ -I/soft/mosquitto/mosquitto-2.0.11/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  -I/soft/mysql-5.7.34/include  -I/src -DDEBUG=1 -I/usr/lib/include
LDFLAGS:   -L/soft/mosquitto/mosquitto-2.0.11/lib/
LDADD:    -L/soft/mysql-5.7.34/lib -lmysqlclient -lpthread -lm -lrt -ldl -L/usr/lib/lib -lcrypto -lmosquitto

cc  -I/soft/mosquitto/mosquitto-2.0.11/src/ -I/soft/mosquitto/mosquitto-2.0.11/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/lib/include   -c -o auth-plug.o auth-plug.c
cc  -I/soft/mosquitto/mosquitto-2.0.11/src/ -I/soft/mosquitto/mosquitto-2.0.11/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/lib/include   -c -o base64.o base64.c
cc  -I/soft/mosquitto/mosquitto-2.0.11/src/ -I/soft/mosquitto/mosquitto-2.0.11/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/lib/include   -c -o pbkdf2-check.o pbkdf2-check.c
cc  -I/soft/mosquitto/mosquitto-2.0.11/src/ -I/soft/mosquitto/mosquitto-2.0.11/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/lib/include   -c -o log.o log.c
cc  -I/soft/mosquitto/mosquitto-2.0.11/src/ -I/soft/mosquitto/mosquitto-2.0.11/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/lib/include   -c -o envs.o envs.c
cc  -I/soft/mosquitto/mosquitto-2.0.11/src/ -I/soft/mosquitto/mosquitto-2.0.11/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/lib/include   -c -o hash.o hash.c
cc  -I/soft/mosquitto/mosquitto-2.0.11/src/ -I/soft/mosquitto/mosquitto-2.0.11/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/lib/include   -c -o be-psk.o be-psk.c
cc  -I/soft/mosquitto/mosquitto-2.0.11/src/ -I/soft/mosquitto/mosquitto-2.0.11/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/lib/include   -c -o backends.o backends.c
cc  -I/soft/mosquitto/mosquitto-2.0.11/src/ -I/soft/mosquitto/mosquitto-2.0.11/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/lib/include   -c -o cache.o cache.c
cc  -I/soft/mosquitto/mosquitto-2.0.11/src/ -I/soft/mosquitto/mosquitto-2.0.11/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/lib/include   -c -o be-mysql.o be-mysql.c
cc  -I/soft/mosquitto/mosquitto-2.0.11/src/ -I/soft/mosquitto/mosquitto-2.0.11/lib/ -fPIC -Wall -Werror  -DBE_MYSQL  `mysql_config --cflags` -I/src -DDEBUG=1 -I/usr/lib/include   -L/soft/mosquitto/mosquitto-2.0.11/lib/ -fPIC -shared -o auth-plug.so auth-plug.o base64.o pbkdf2-check.o log.o envs.o hash.o be-psk.o backends.o cache.o be-mysql.o   `mysql_config --libs` -L/usr/lib/lib -lcrypto -lmosquitto
/usr/bin/ld: cannot find -lmosquitto
collect2: error: ld returned 1 exit status
make: *** [auth-plug.so] Error 1

**Comment by ralight** [comment]
This isn't the issue tracker for `mosquitto-auth-plugin`, but the error `/usr/bin/ld: cannot find -lmosquitto` suggests that you haven't installed the libmosquitto library on your system.

**Comment by xcmonline** [comment]
sudo ln -s /soft/mosquitto/run/lib/libmosquitto.so /soft/mosquitto/mosquitto-2.0.11/lib/libmosquitto.so
