### ISSUE TITLE
ACL File - How to restrict Subscription on topics?

### ISSUE THREAD

**Issue by MarcoWirtl** [eclipse/mosquitto#2296]
Hi, i'm using mosquitto version 1.6.10.

I'm trying to restrict subscriptions from clients.

My ACL:
```
user testuser
topic readwrite testtopic
```

Of course i restartet the Broker and it's starting with the correct Config File.

If I Publish to an other topic e.g. "test" i get the 
`Denied Publish` Message on the Broker.  --> ACL should work!

But the testuser is still able to subscribe to any topics. My expectation was to get a `Denied Subscribing` Message on the Broker or smth similar.
Or i'm wrong?

-----------------------------------

Output on subscribing client on a topic "test" (not in the ACL!):

mosquitto_sub -d -t test -u testuser -P <psw> Client mosq-QcDQ47Y84WRRW7FBiT sending CONNECT

```
Client mosq-QcDQ47Y84WRRW7FBiT received CONNACK (0)
Client mosq-QcDQ47Y84WRRW7FBiT sending SUBSCRIBE (Mid: 1, Topic: test, QoS: 0, Options: 0x00)
Client mosq-QcDQ47Y84WRRW7FBiT received SUBACK
Subscribed (mid: 1): 0

```

-----------------------------------

Output on the MQTT-Broker while subsribing with the client:

```
1630566238: New client connected from 127.0.0.1 as mosq-QcDQ47Y84WRRW7FBiT (p2, c1, k60, u'testuser').
1630566238: No will message specified.
1630566238: Sending CONNACK to mosq-QcDQ47Y84WRRW7FBiT (0, 0)
1630566238: Received SUBSCRIBE from mosq-QcDQ47Y84WRRW7FBiT
1630566238:     test (QoS 0)
1630566238: mosq-QcDQ47Y84WRRW7FBiT 0 test
1630566238: Sending SUBACK to mosq-QcDQ47Y84WRRW7FBiT
```

Any suggestions on that?

**Comment by MarcoWirtl** [comment]
@Daedaluz yes i just receive the 'testtopic' messages.

So the MQTT-Broker always receive and accept the SUBSCRIBE, right?

I thought that the read/write permissions in the ACL should restrict the behaviour, like it does with the 

`Denied PUBLISH` Message.

Thats why I expected to get a

`Denied SUBSCRIBE` message on the broker as well.

**Comment by Daedaluz** [comment]
I'm not sure if there is a setting to control the subscription behavior as well.
But yes.

There are Read/Write/Subscribe actions.

Subscribe: Requests messages with a specific topic pattern.
Read: when a message is matched to a subscription and tells if a client is allowed to get the message or not.
Write: when a client wants to publish a message.

**Comment by ralight** [comment]
@MarcoWirtl at the moment there is no mechanism with ACL files to deny subscriptions. The ACLs in an ACL file are currently exclusively related to publishing - `write` indicates whether the client is allowed to send a publish to a topic, and `read` indicates whether a client is allowed to receive a publish on a topic.

The dynamic security plugin allows control of subscriptions as well as publishes, I'd suggest looking into that if you're really concerned about having subscriptions denied (I agree it is better to be able to deny them than at the publish level), plus it is a lot more flexible in other ways: https://mosquitto.org/documentation/dynamic-security/

**Comment by ralight** [comment]
Oh, since you're using 1.6.10 you wouldn't have access to the dynamic security plugin unless you upgrade.

**Comment by flaviolenz** [comment]
Is there a way to deny uses from subscribing to '#' ?

**Comment by furkanmustafa** [comment]
Here it is; https://github.com/eclipse/mosquitto/blob/master/src/security_default.c#L383

**Comment by Anders-Fromell-ITxPT** [comment]
I guess the idea behind is that you will be allowed to do a wildchar subscribe <topic>/#
but will only get messages from topics you have read acces to..

**Comment by Daedaluz** [comment]
perhaps this can be closed?
