### ISSUE TITLE
file logging not working

### ISSUE THREAD

**Issue by OliverSanftleben** [eclipse/mosquitto#230]
mosquitto.conf
...
log_dest file /var/log/mosquitto.log
log_dest stdout
log_dest syslog
...
log_type all
...

osanftle@ubuntu:/etc/mosquitto$ ls -lisa /var/log/mosquitto.log
1581778 0 -rw-r--r-- 1 mosquitto mosquitto 0 Jul 28 17:29 /var/log/mosquitto.log

**Comment by ralight** [comment]
How did the file get created? I don't think mosquitto has access to that file because of apparmor.

**Comment by OliverSanftleben** [comment]
Thanks, after restarting the system logging works now! I think the old config was taken somehow.
