### ISSUE TITLE
Does mosquitto 1.6.15 support mqtt version 5 ?

### ISSUE THREAD

**Issue by Z-VegetableBird** [eclipse/mosquitto#2303]
Does mosquitto 1.6.15 support mqtt version 5? We use it on embedded systems   thinks

**Comment by ptjm** [comment]
From the ChangeLog.txt file:

1.6 - 20190417
==============
  
Broker features:
- Add support for MQTT v5

I expect you can find the same information somewhere on the mosquitto web site.

**Comment by Z-VegetableBird** [comment]
thank you
