### ISSUE TITLE
Keep alive 0 results in 'identifier rejected'

### ISSUE THREAD

**Issue by Daedaluz** [eclipse/mosquitto#2309]
I just did an upgrade from 2.0.11 to 2.0.12 and noticed that some of my clients started to get "identifier rejected".
After some tracing i managed to narrow it down to this check.

https://github.com/eclipse/mosquitto/blob/42acfdad4135242e965956bb69ceacc5378d9832/src/handle_connect.c#L265-L266

And only for v3 clients it looks like.

~~Apparently some of my clients have the maximum keep alive interval, so the check fails and throws them out.~~

~~I'm wondering if the check technically shouldn't be a `>=` ?~~

~~Of course. I'll just reconfigure my clients to use a lower keep alive since i can't put a higher max keep alive in config.~~
~~It's an edge case since it's probably better to use a lower keep alive anyway, but felt it was a good idea to point it out.~~

Edit:
Sorry, was thinking too fast.
Found other clients with keep alive interval 0 which results in 'identifier rejected'.

Looks like the spec has something to say about this:
```
A Keep Alive value of zero (0) has the effect of turning off the keep alive mechanism. This means that, in this case, the Server is not required to disconnect the Client on the grounds of inactivity.
Note that a Server is permitted to disconnect a Client that it determines to be inactive or non-responsive at any time, regardless of the Keep Alive value provided by that Client.
```

With further digging i found https://github.com/eclipse/mosquitto/issues/2117.

**Comment by rukechen** [comment]
I face the same issue while integrating with Telegraf mqtt output plugin.
If mosquitto version is changed to 1.5.11, everything is working well. If mosquitto version is changed to 2.0.12,  I will get error code 'identifier rejected'. According to the https://github.com/influxdata/telegraf/blob/v1.19.3/plugins/outputs/mqtt/mqtt.go, KeepAlive is set to zero.


![image](https://user-images.githubusercontent.com/18527508/133243777-17685ef0-a31c-434d-b1d7-c8b6455d047b.png)

**Comment by ralight** [comment]
This is a duplicate of #2117 which is now fixed in the `fixes` branch. I'm going to leave it open until the next release so others can find it more easily.

**Comment by Daedaluz** [comment]
I'm not so sure about that.
Looks like the bug is still present in fixes branch. (unless you haven't pushed yet of course)

I think that the change that was prompted by #2117 introduced another bug for v3 protocol.

If I'm not mistaken, current code will still prevent any v3 client from connecting with 0 keep alive.

**Comment by Daedaluz** [comment]
or is the point here that you should set "max_keepalive" to 0 in the config file to allow clients disabling the functionality?

**Comment by Daedaluz** [comment]
closing this.
