### ISSUE TITLE
logging to syslog cannot be stopped

### ISSUE THREAD

**Issue by OliverSanftleben** [eclipse/mosquitto#231]
Hello,

I've tried to deactivate logging to syslog, but messages are still send to /var/log/syslog

service mosquitto stop

mosquitto.conf
...
log_dest file /var/log/mosquitto.log
log_dest stdout
#log_dest syslog
...
log_type all
...

service mosquitto start

osanftle@ubuntu:/etc/mosquitto$ tail -f /var/log/syslog                         Jul 29 10:40:37 ubuntu mosquitto[4188]: Received PINGREQ from oliver.sanftl_135329706
Jul 29 10:40:37 ubuntu mosquitto[4188]: Sending PINGRESP to oliver.sanftl_135329706
Jul 29 10:41:17 ubuntu mosquitto[4188]: Received PINGREQ from oliver.sanftl_133205915
Jul 29 10:41:17 ubuntu mosquitto[4188]: Sending PINGRESP to oliver.sanftl_133205915
...

**Comment by ralight** [comment]
The only way this could occur is if the broker didn't stop for some reason and was using the old config.

You could confirm this by killing the process proper, or by using `pkill -HUP mosquitto` which would cause it to reload the config.

Another alternative would be that there is another syslog line somewhere else, but I presume you would've spotted that.

**Comment by OliverSanftleben** [comment]
Thanks, everything works now! I think the old config was taken somehow.
