### ISSUE TITLE
[Help] Mosquitto sending out initial connection message in Chinese?

### ISSUE THREAD

**Issue by shulist** [eclipse/mosquitto#2315]
Using Linux Mint 20.1, MQTTX 1.6.0 and Eclipse/Mosquitto 2.0.12
Upon first connection the the broker I get a message in Chinese though all devices and apps are set for English. This is a MQTT broker being accessed from the same machine it is installed on. Messages after the first initial connection are correct.

Can anyone shed some light on this?
![MQTTX_Chinese](https://user-images.githubusercontent.com/6595819/133470846-572cce2f-64d9-4ccc-8864-8cfcd9179347.png)

**Comment by Daedaluz** [comment]
hard to say anything else but to check your clients. some program published the message and can't see if it's retained or not.
If it re-appears after multiple connections it might indicate that it's a retained message and can be removed by publishing another, empty message with retained flag on, with the same topic.
`mosquitto_pub -t "hello/world" -n -r` i think it is.
Some testing software somewhere maybe?

**Comment by shulist** [comment]
@Daedaluz it was a retained message. Though it was a fresh install of both Mosquitto and MQTTX so one of them is a culprit but I do not have enough knowledge to investigate further.
