### ISSUE TITLE
no messages from $SYS/broker

### ISSUE THREAD

**Issue by OliverSanftleben** [eclipse/mosquitto#232]
I'm getting no information from $SYS/broker

acl
user gcread
topic read germany/#
topic read spain/#
topic read $SYS/broker/#
user gcwrite
topic write germany/#
topic write spain/#

mosquitto.conf
...
sys_interval 1
...

f.e.
 mosquitto_sub -t '$SYS/broker/version' -u gcread -P gcread
 mosquitto_sub -t '$SYS/broker/uptime' -u gcread -P gcread
-> no messages

/var/log/syslog
Jul 29 10:59:47 ubuntu mosquitto[4188]: New connection from ::1 on port 1883.
Jul 29 10:59:47 ubuntu mosquitto[4188]: New client connected from ::1 as mosqsub/6558-ubuntu (c1, k60, u'gcread').
Jul 29 10:59:47 ubuntu mosquitto[4188]: Sending CONNACK to mosqsub/6558-ubuntu (0, 0)
Jul 29 10:59:47 ubuntu mosquitto[4188]: Received SUBSCRIBE from mosqsub/6558-ubuntu
Jul 29 10:59:47 ubuntu mosquitto[4188]: #011$SYS/broker/uptime (QoS 0)
Jul 29 10:59:47 ubuntu mosquitto[4188]: mosqsub/6558-ubuntu 0 $SYS/broker/uptime
Jul 29 10:59:47 ubuntu mosquitto[4188]: Sending SUBACK to mosqsub/6558-ubuntu

I'm using newest mosquitto version on Ubuntu:
mosquitto version 1.4.9 (build date Fri, 17 Jun 2016 15:43:08 +0100)

**Comment by ralight** [comment]
This works for me. I've just recorded me carrying out the test:

https://asciinema.org/a/b2yqicf73ctfvq7fbk5inarsr

Could you try and replicate that exactly as in the ascii cast? If you do have still have a problem then recording yourself from start to finish would be very useful.

**Comment by OliverSanftleben** [comment]
After stopping all clients and restarting Ubuntu everything seems to work now. So, could it be that despite restarting the service ('service mosquitto stop', 'service mosquitto start') the old configuration was taken?

**Comment by ralight** [comment]
The old config wouldn't have been taken, but it's possible that the broker wasn't restarted for some reason.
