### ISSUE TITLE
libwebsockets18 missing in repo.mosquitto.org Debian Bullseye suite

### ISSUE THREAD

**Issue by MichaIng** [eclipse/mosquitto#2322]
The Debian Mosquitto package depends on `libwebsockets18`. Packages for this library for Bullseye are present in the repo.mosquitto.org [package pool](https://repo.mosquitto.org/debian/pool/main/libw/libwebsockets/), but are not present in the suites [package list files](https://repo.mosquitto.org/debian/dists/bullseye/main/binary-amd64/). Installing Mosquitto hence currently fails on Raspbian/Debian Bullseye.

Please guide me if issues with the repository shall be reported elsewhere.

**Comment by ralight** [comment]
This is absolutely the right place to report it, thank you, I'll see what I can figure out. Debian repos are a bit of a black art!

**Comment by MichaIng** [comment]
Don't make me afraid, I'm going to host an APT repository soon 😄. Since the package is well provided on Buster and Stretch suites, I guess there is only a reference/entry missing in the dak/reprepro or whichever tool/method you use to maintain the repository.

**Comment by MichaIng** [comment]
@ralight 
I hope its fine to give you a ping as reminder. Since the package exists already it shouldn't be difficult to add it to the package list 🙂. Otherwise when lacking time to fix this, please report back as well, so we'll implement a workaround into our installer.

**Comment by jmico** [comment]
As of version 2.0.14 the package libwebsockets18 is properly installed in Debian 11 from http://repo.mosquitto.org (I think it was actually fixed in 2.0.13 but I didn't tested it).

So this issue can be closed now.

**Comment by MichaIng** [comment]
Right, this issue is solved 👍.
