### ISSUE TITLE
docker eclipse-mosquitto 2.0.12 in local only mode.

### ISSUE THREAD

**Issue by Qaldak** [eclipse/mosquitto#2323]
Hi

I updatet my mosquitto from v1.6.9 to v2.0.12. But it's not possible anymore to send MQTT-messages thru mosquitto docker-container.

In docker-container I see following output
```
0: mosquitto version 2.0.12 starting
0: Using default config.
0: Starting in local only mode. Connections will only be possible from clients running on this machine.
0: Create a configuration file which defines a listener to allow remote access.
0: For more details see https://mosquitto.org/documentation/authentication-methods/
0: Opening ipv4 listen socket on port 1883.
0: Error: Address in use
0: Opening ipv6 listen socket on port 1883.
0: Error: Address not available
```

Why default config? see above **0: Using default config**

I defined amosquitto.conf file: 
```
persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_type debug

listener 1883
allow_anonymous true
```

This file is mounted into docker container:
`docker run -itd --name="mosquitto" --restart always -p 1883:1883 -e TZ=Europe/Berlin -v /mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf -v mosquitto_data:/mosquitto/data -v mosquitto_data:/mosquitto/log eclipse-mosquitto:2.0.12`

Should it not be something like "Config loaded from /mosquitto/config/mosquitto.conf."

**Comment by Qaldak** [comment]
after various attempts and restarts and so on, i have adjusted the config file as follows:

```
persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log

listener 1883
allow_anonymous true

```
now the configuration was loaded at startup.
No idea why. Strange.


But another problem:
When I send a message, only sometimes the message can be sent. most of the time I get an "unknown error"
```
~ $ docker exec mosquitto mosquitto_pub -t 'test/topic' -m 'hello, is anybody out there?'
Error: unknown error.

```
According to the protocol:
```
0: New client connected from 127.0.0.1:52696 as auto-AC707FE7-57D1-C9A1-BC30-BE5A565DD1AC (p2, c1, k60).
0: The client auto-AC707FE7-57D1-C9A1-BC30-BE5A565DD1AC has closed its connection.
0: New connection from 127.0.0.1:52698 on port 1883.
0: New client connected from 127.0.0.1:52698 as auto-4D27C688-3FFB-970F-5BB7-EA165496DD2 (p2, c1, k60).
0: The client auto-4D27C688-3FFB-970F-5BB7-EA165496DD2 has closed its connection.
0: New connection from 127.0.0.1:52700 on port 1883.
0: New client connected from 127.0.0.1:52700 as auto-DAB38C04-C6D6-C36D-4F89-DB92EDB6A08A (p2, c1, k60).
0: The client auto-DAB38C04-C6D6-C36D-4F89-DB92EDB6A08A has closed its connection.
0: New connection from 127.0.0.1:52702 on port 1883.
0: New client connected from 127.0.0.1:52702 as auto-C4DFA271-0F33-6C15-9C4B-65A74E517365 (p2, c1, k60).
0: The client auto-C4DFA271-0F33-6C15-9C4B-65A74E517365 has closed its connection.
0: New connection from 127.0.0.1:52704 on port 1883.
0: New client connected from 127.0.0.1:52704 as auto-14CB30B3-DE3E-3EA6-561B-CFEB49327174 (p2, c1, k60).
0: Client auto-14CB30B3-DE3E-3EA6-561B-CFEB49327174 was disconnected.
```

Only the last attempt (with Client... disconnected) was successful.

**Comment by ralight** [comment]
I'm sorry, I don't see any of the behaviour you're describing. It all works exactly as I expect.

The only way the `Using default config.` message will appear is if the config file wasn't passed on the command line. I do note that the timestamp is `0` for all of the log messages, so something is clearly not correct somewhere. That would indicate that the `time(NULL)` call is failing, which is incredibly unlikely. Is there anything interesting/unusual about the hardware/software you are running on?

**Comment by Qaldak** [comment]
No, it runs on a Raspberry Pi 3B.
```
pi@raspberry:~$ uname -a
Linux vision 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

```
Perhaps is related to #2310.

If I choose 1.6.15 there it runs without any problems.

Do you have an idea where I can search further?

**Comment by peter-vanpoucke** [comment]
Thanks for the hint @Qaldak. Checked this post: <https://github.com/alpinelinux/docker-alpine/issues/135#issuecomment-762542148> and found that libseccomp2 needed an update on _Raspberry Pi OS Buster_.

Updated that one by executing ([source](https://jackstromberg.com/2021/07/how-to-add-buster-backports-to-a-raspberry-pi/)):
```bash
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
echo "deb http://deb.debian.org/debian buster-backports main contrib non-free" | sudo tee /etc/apt/sources.list.d/backports.list
sudo apt update
sudo apt install libseccomp2/buster-backports
```
After that, when executing a ping in the container it seemed the error (`ping: clock_gettime(MONOTONIC) failed`) was already fixed. But I've rebuild the containers, just to be sure.

**Comment by Qaldak** [comment]
thanks @peter-vanpoucke  
after update of libseccomp2 it seems to run without any further problems. Also timestamp and timestamp format in log is working again.
