### ISSUE TITLE
Enchancement: Bridge notifications only locally

### ISSUE THREAD

**Issue by AlexShkunov** [eclipse/mosquitto#233]
Would it be possible to introduce a configuration that would publish bridge state only locally (0 | 1). A remote broker does not allow retained messages to be published. However the notifications can be used on a device. E.g. I was thinking to make Raspberry Pi senseHAT App that would monitor the notification and then make it into LED light ( green | red ) based on state.

**Comment by ralight** [comment]
Expanding bridge notifications like you've said seems like a reasonable plan. Needs a little bit of thought as to how it will work with the existing settings.

**Comment by cjmaynard** [comment]
I tested Ben's patch and found that the local client does not get notified when the state goes to '0', such as might be the case if the remote broker is shut down; however, when the remote broker is restarted, the local client does get notified that the state is now '1'.

**Comment by cjmaynard** [comment]
I think there might be a problem here.  Yesterday I tried Ben's patch and set `notifications_local_only true`.  If I have a local client subscribed to `$SYS/broker/connection/+/state` and I shut down the remote broker such that the bridge is no longer connected, my local client does not get the notification update that the state is now '0'. When the remote broker is restarted and the bridge is reestablished, the local client does get the notification update that the state is now '1' though.  (If I don't use `notifications_local_only true`, the client does get both '0' and '1' state changes, as expected ... but of course then the state topic is published across the bridge, which I want to avoid.)

**Comment by karlp** [comment]
I added a comment to https://github.com/eclipse/mosquitto/commit/740b710a0b9f18e5d28d4a9130e2bb3dc5a3c876 as well. I can confirm that I don't get the 0 state when the bridge connection is lost, only the 1 when it's established.  using mosquitto devel branch
