### ISSUE TITLE
repo.mosquitto.org ships expired certification path

### ISSUE THREAD

**Issue by MichaIng** [eclipse/mosquitto#2336]
I hope it is the right place to report issues with the official Mosquitto APT repository. It ships an expired certification path, the one based on the expired `DST Root CA X3` used by Let's Encrypt previously: https://www.ssllabs.com/ssltest/analyze.html?d=repo.mosquitto.org&s=85.119.83.194&latest
The new one is shipped as well, but at least on Debian Stretch and Buster, and I guess on several Ubuntu versions, non-latest OpenSSL/LibSSL selects the expired certification path, which makes APT fail. An upgrade to latest OpenSSL solves the issue as well, but it should be solved also server side by renewing the certificate so that the chain does not contain the expired one anymore.

**Comment by ralight** [comment]
I don't believe this is an issue any longer, so I'm closing this.
