### ISSUE TITLE
Feature request: Inform client when session has been taken over.

### ISSUE THREAD

**Issue by hvxl** [eclipse/mosquitto#2340]
When a session is taken over, the connection to the old client is currently simply closed by mosquitto. This may trigger the client to attempt to reconnect, possibly leading to a fight over a client ID by two or more clients. MQTT v5 defines Disconnect Reason Code 142 for informing the old client of the reason it is being disconnected. Understanding the reason may be used to stop a client from reconnecting, reconnect less aggressively, or picking a different client ID.  So it would be nice if mosquitto could implement this Disconnect Reason Code.

The following patch seems to do the trick: [session_taken_over.diff.txt](https://github.com/eclipse/mosquitto/files/7324612/session_taken_over.diff.txt). The patch has been verified against the latest check-in of the master branch (9afeeb1, version 2.0.12) on linux.

**Comment by ralight** [comment]
Thanks for the suggestion. I've implemented this in the `develop` branch which will become version 2.1.
