### ISSUE TITLE
Disconnect with Will Message broken by check in 7954215

### ISSUE THREAD

**Issue by hvxl** [eclipse/mosquitto#2342]
Mosquitto 2.0.12 no longer sends the will message when a client disconnects with reason code 4. I haven't tested other situations where a will message is supposed to be sent. It was working on version 2.0.11.

Using git bisect, I found that the problem started with check in 7954215.

**Comment by ralight** [comment]
This was fixed in 2.0.13, so I'm closing the issue. Thanks for the report!
