### ISSUE TITLE
 Compilation with MinGW failed when configured with CMake

### ISSUE THREAD

**Issue by cisoakk** [eclipse/mosquitto#2352]
Under Win7, CMake 3.21.3, MinGW 7.3.0, Mosquitto source from git, branch master, commit 9afeeb1a568470871511a78de6b5927010ede1f5

When doing "mingw32-make all"

First, I have to manually add "CC=gcc" before anything else in the CMake generated Makefile or "make" tool tries to start "cc" process instead of gcc and fails on CreateProcess.
Second, something is wrong with OpenSSL detection by CMake, it finds all necessary paths (it shows them in gui at least) but again, you have to manually add include and library paths in CFLAGS and LDFLAGS in the Makefile generated, or it'll fail first with "no include file" and after while linking against OpenSSL and Crypto libs.
Third, there is no directive for linker there to link against ws2_32.lib, so any function call like WSAStartup  gets you "unresolved external" error. After hacking -lws2_32 into Makefile guts I've got 
The last: "gcc: error: libmosquitto.so.1: No such file or directory", where I have stuck. I suspect the order of compilation is wrong and libmosquitto is not compiled before the step it should have been.

**Comment by ralight** [comment]
Sorry for the confusion!
