### ISSUE TITLE
JSON timestamps are not valid ISO 8601

### ISSUE THREAD

**Issue by normanr** [eclipse/mosquitto#2353]
b726e2f1ecb376f5f21cceb8ec572ec719d289aa added a ISO 8601-like output with a `Z` (indicating UTC) _and_ `%z` (offset from UTC). I don't think the `Z` should be present (also the man page doesn't include the `Z` in the example output).

Currently json_print does a special workaround after printing microseconds to replace the `Z` (where `snprintf` wrote it's null byte). It's probably simplest to just drop the microseconds from the time format, and call strftime a second time to format the timezone after the microseconds have been printed, eg:
```
char *bufp = buf;
int buf_size = sizeof(buf);
int n;

n = strftime(bufp, buf_size, "%Y-%m-%dT%H:%M:%S.", ti);
bufp += n; buf_size -= n;

n = snprintf(bufp, buf_size, "%06d", ns/1000);
bufp += n; buf_size -= n;

strftime(bufp, buf_size, "%z", ti);
```

I think it would also make sense to move the `strftime`/`snprintf` calls _before_ the `#ifdef WITH_CJSON` because it can be shared with both parts. Also buf could be made smaller, only the first 32 bytes will ever be used.

**Comment by ralight** [comment]
Yes, the buffer is oversized, I'll drop it but I don't think it's a big deal.

The size passed to snprintf is 9 because the compiler thinks the int could 9 characters long even though we know it will be no more than 6 characters long.

If strftime doesn't give the same length output every time it's a huge bug in strftime.

**Comment by normanr** [comment]
These are both just nits, thanks for the fix!

> The size passed to snprintf is 9 because the compiler thinks the int could 9 characters long even though we know it will be no more than 6 characters long.

int32 can be 10 characters, so not sure where the 9 comes from.

> If strftime doesn't give the same length output every time it's a huge bug in strftime.

y10k problem :grinning: but fair point. iso 8601 requires "prior agreement between the sender and the receiver", when the year is outside [0000, 9999], so unlikely to be an issue for a while.
