### ISSUE TITLE
Migrating from 1.6.x to 2.0.y: Authentication changes (username, no password)

### ISSUE THREAD

**Issue by D-r-P-3-p-p-3-r** [eclipse/mosquitto#2358]
With the following configuration of Mosquitto 1.6.7 a user without a password (but with any non-empty username) could connect to the server:

```
bind_address 127.0.0.1
port 63333

allow_anonymous false

acl_file /bar/foo.acl
```

/bar/foo.acl
```
pattern read $SYS/#
pattern readwrite foo/#
```

After upgrading to Mosquitto 2.0.12 the connect fails.

I assume that the reason is this excerpt from the documentation of Mosquitto 2.0 for allow_anonymous:

>  If set to false then another means of connection should be created to control authenticated client access.

For 1.6.7 it stated:

> If set to false then a password file should be created (see the password_file option) to control authenticated client access.

Does this mean that this is an (intended) change in behavior not mentioned in the migration docs (https://mosquitto.org/documentation/migrating-to-2-0/)?

The migration docs state 

> If you currently have a broker running that has a listener configured in the configuration file,
> but has no other authentication configured and no explicit allow_anonymous setting, then
> your clients will be unable to connect after upgrading to Mosquitto 2.0.

I do have an explicit allow_anonymous setting though. It is "false". Thus, I believe this paragraph does not cover my use case, does it?

The changed behavior is not bad or a problem. I'd just love to understand the reason for what happened.

Also, the documentation in both cases states you "should" do something. It doesn't tell in either case what happens if you don't.

**Comment by ralight** [comment]
In 2.0 the behaviour changed in a way that tightens up the meaning of "anonymous" so it means full authentication. Unfortunately for you that means passing just a username is no longer sufficient - I didn't think that anybody would be using it like this to be honest.

**Comment by D-r-P-3-p-p-3-r** [comment]
Thanks for clearing that up.
It's not a problem for us and nothing that we're relying on. I just wanted to make sure nothing broke and that we aren't doing anything wrong.
