### ISSUE TITLE
update to 2.0.12 breaks simple micropython mqtt 3.1.1 clients

### ISSUE THREAD

**Issue by brianwyld** [eclipse/mosquitto#2361]
My embedded devices using the umqtt micropython MQTT v3.1.1 client (from PyCom and in the micropython respositry)  stopped being able to connect to my 2.0.12 mosquitto server : they get a CONNACK with a response code of 2 (ie bad)
After digging thru the mosquitto code, it seems to me that this is due to the update
"Apply max_keepalive to MQTT v3.1.1 and v3.1 clients." commit on the 21 Aug 2021, which checks the max keepalive config for 3.1.1 clients (where before this only applied to v5 clients).
The umqtt.py code (which is pretty simplistic) always passes 'keepalive' as 0 in the CONNECT attempt, and in the mosquitto default config this now breaks.
Is this correct protocol behaviour (and if so, is there a server side config to avoid it...)?
thanks

**Comment by brianwyld** [comment]
update:  I don't see why the check includes the keepalive=0 case as an error?

**Comment by brianwyld** [comment]
update : I tried setting 
max_keepalive 0
as per the comments in the mosquitto.conf, but the latest docker image for 2.0 doesn't accept this as a legitimate value.

**Comment by brianwyld** [comment]
ok thanks, didn't manage to relate my 'identifier rejected' issue to the keepalive issue until after logging the initial issue.

**Comment by gdt** [comment]
If it's a dup would be good to close this.   And, to read the spec to see if keepalive 0 is legit or not.   If not, seems best to fix the client.

**Comment by brianwyld** [comment]
The client asking for keepalive=0 is legit, the issue is that the server doesn't let you configure max_keepalive=0 for 3.1.1 client so that it can deal with it.
As its a duplicate of #2309 (which is duplicate of #2117, which has a fix in the 'fixed" branch to allow setting max_keepalive to 0). I'm closing this issue.
