### ISSUE TITLE
dynamic-bridge: small typo in man/Makefile

### ISSUE THREAD

**Issue by yvs2014** [eclipse/mosquitto#2363]
there's a small typo in "man/Makefile" file from "dynamic-bridge" branch
https://github.com/eclipse/mosquitto/blob/90566d3f9e5fd31a35b2df3473c1f2316ef5b6c4/man/Makefile#L41

fix example: https://github.com/yvs2014/mosquitto/commit/5130202e765aa9e2f5dbd207c795238807589a5d

**Comment by ralight** [comment]
Thanks very much, that's now fixed.
