### ISSUE TITLE
mosquitto_sub.exe and mosquitto_pub.exe are not valid win32 application

### ISSUE THREAD

**Issue by rickyteng** [eclipse/mosquitto#238]
I used mosquitto-1.4.9-install-cygwin.exe to install on my winXP SP3.
I followed instructions copy required dll. Then mosquitto.exe works.
But mosquitto_sub.exe and mosquitto_pub.exe don't work.
They are not  valid win32 applications.

**Comment by ralight** [comment]
It's a bit tricky for me to do anything about this, I've not had access to an XP box for years. Could you try compiling it yourself with cygwin to see if it works then?

**Comment by rickyteng** [comment]
I try mosquitto-1.4.9-install-cygwin.exe and mosquitto-1.4.9-install-win32.exe. Both mosquitto_sub.exe are not valid win32 application. Maybe it just package wrong exe...
I have downloaded mosquitto-1.2-install-cygwin.exe and msvcr100.dll. mosquitto_sub.exe and mosquitto_pub.exe work.
Maybe I will use one version of mosquitto.exe and another version of mosquitto_pub/mosquitto_sub because I am poor to compile this thing

**Comment by ralight** [comment]
Closing because there hasn't been any update for a while. If you think this is still a problem, please provide more information and reopen.
