### ISSUE TITLE
 mosquitto.conf - port 0 is not valid

### ISSUE THREAD

**Issue by swamper123** [eclipse/mosquitto#2390]
**Error:**
I want to use mosquitto with unix-sockets. It logs that port 0 is not valid, but the docs say:

> 
On systems that support Unix Domain Sockets, this option can also be used to create a Unix socket rather than opening a TCP socket. In this case, the port must be set to 0, and the unix socket path must be given.

**Reproduce steps:**
- got a Pi 3B+ as Hardware base with raspbian/Raspberry Pi OS
- I installed mosquitto via `sudo apt get install mosquitto`.
- I added "listener 0 /tmp/mosquitto.sock" to the mosquitto.conf file
- I start mosquitto via` /usr/sbin/mosquitto -c /path/to/mosquitto.conf ` (otherways via systemctl etc. as well, but this one shows me what is wrong)

**Expectation:**
A Unix socket would be made (or used if already exist) and used by mosquitto. I got the hunch, that `WITH_UNIX_SOCKETS` wasn't used, so that this line: 

https://github.com/eclipse/mosquitto/blob/d5970ca9985f4d3193fe7a359707723090bb13e9/src/conf.c#L1390

was never True. Otherwise a Check for unixpath would be made.

**Comment by swamper123** [comment]
It works fine when I build the binary file, but I would still expect, that it would work with `sudo apt get install mosquitto` as well.

**Comment by ralight** [comment]
I would imagine that the version available in Raspberry Pi OS is just too old to support this.

**Comment by ralight** [comment]
Closing because I think this is resolved. If not, please reopen and provide more details.
