### ISSUE TITLE
Configure auth plug-in per listener

### ISSUE THREAD

**Issue by uvzubovs** [eclipse/mosquitto#242]
It appears that auth plug-in setting is for all listeners. If so, is it possible to define auth plug-in per listener? 

We would like to authenticate the publisher running in-house using the client SSL cert, but consumers running on mobile devices using the security tokens. We are writing the plug-in for token validation, but are concerned that it would overwrite authentication by client cert, and setting the user id to cert's CN.

**Comment by ralight** [comment]
It isn't at the moment, but will be in 1.5.

**Comment by uvzubovs** [comment]
Oh, nice! Would the same apply to acl_file?

**Comment by uvzubovs** [comment]
@ralight Is there a timeline for Mosquitto releases? Say, do you have a possible date for 1.5, or is it "best-effort"? Just trying to understand .... Thanks!

**Comment by ralight** [comment]
1.5 will be released shortly, so I'm closing this because it is implemented.
