### ISSUE TITLE
function mosquitto_loop_start returns MOSQ_ERR_NOT_SUPPORTED

### ISSUE THREAD

**Issue by bagualing** [eclipse/mosquitto#2426]
I got the same issue as [#1309](https://github.com/eclipse/mosquitto/issues/1309) which reported by @realgsg.

It always returns the int 10(MOSQ_ERR_NOT_SUPPORTED) when I call mosquitto_loop_start. What's wrong about this?

Environment:
O.S: Windows 7
mosquitto.dll v2.0.14 (same as v1.6.2) 32bit.

**Comment by ralight** [comment]
Threading isn't supported on windows in 2.0.x, unless you compile it yourself with an appropriate thread library. It will be available in 2.1.x.

**Comment by phoenixx003** [comment]
> 

When will 2.1.x be avaiable ?

I'm having the exact same problem with threading the loop()-function 👍
