### ISSUE TITLE
BUG: mosquitto triggers disconnection with qos = 0

### ISSUE THREAD

**Issue by JamesWang-Moxa** [eclipse/mosquitto#2427]
Mosquitto version: 1.6.15
It happened in the condition of MQTT connection with Qos equals 0.   The broker that I used is "SIOT" which only support connection with Qos = 0 .  When "publish message" is sent, the "PUBACK" shouldn't be replied normally.  But SIOT would reply it with message id equals 0x00.   In handle__pubackcomp() from mosquitto source code, it checks if message id is zero which leads to return MOSQ_ERR_PROTOCOL while communicating with SIOT broker.

Shouldn't it check Qos first before checking message id?

**Comment by karlp** [comment]
why is siot replying with a puback at all? there shouldn't be a puback with qos0, so this is a bug with SIOT, and when the "illegal client" (SIOT) does so, it is disconnected per spec.

**Comment by JamesWang-Moxa** [comment]
> why is siot replying with a puback at all? there shouldn't be a puback with qos0, so this is a bug with SIOT, and when the "illegal client" (SIOT) does so, it is disconnected per spec.

Yes, it's an abnormal behavior regards to SIOT.  But it would be better to have a better or more compatible way to handle an "ACK" by ignore it instead of resetting the connection.

**Comment by karlp** [comment]
It's _per spec_ MQTT compliant to disconnect clients sending illegal packets....  Seriously, if SIOT is this broken, why would you still even try to use it?

**Comment by JamesWang-Moxa** [comment]
I am trying to put mosquitto into our product for mqtt function. Compatibility is one of the most important thing to us. It just doesn't make sense to disconnect with an PUBACK replied when trying to product ion.

取得 Android 版 Outlook<https://aka.ms/AAb9ysg>
________________________________

**Comment by karlp** [comment]
well, it very much does if you want to interop with anything that speaks the protocol MQTT :)  You'll be disconnected by anything that is MQTT compliant if you try and send a PUBACK to a qos0 publish.  Hive/aws/mosquitto, whatever, MQTT spec _requires_ that clients sending illegal packets are disconnected.  See http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718110  (If the link doesn't work well, that's 4.8 "Handling errors")

Same thing in v5: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901258

**Comment by ralight** [comment]
I agree with the points Karl is making. We will remain compliant with the spec and not support a PUBACK with mid=0.
