### ISSUE TITLE
Websockets listener configured for SSL acts like non-SSL listener

### ISSUE THREAD

**Issue by jrlog** [eclipse/mosquitto#243]
I've compiled mosquitto using WITH_WEBSOCKETS:=yes and have successfully connected to mqtt listeners (with and without SSL) and a non-SSL websockets listener. 

When I set up an SSL websockets listener (see below config), I'm able to connect to it successfully without using SSL through browser websockets clients (i.e. http://www.hivemq.com/demos/websocket-client/ and an in-house version of the same thing), but SSL connections on the same port fail with "AMQJS0007E Socket error:undefined."

```
user root

listener 31883
protocol websockets

listener 38883
protocol websockets
certfile /etc/mosquitto/ssl/servercert.pem
keyfile /etc/mosquitto/ssl/key.pem
cafile /etc/mosquitto/ssl/cacert.pem

listener 1883
protocol mqtt

listener 8883
protocol mqtt
certfile /etc/mosquitto/ssl/servercert.pem
keyfile /etc/mosquitto/ssl/key.pem
cafile /etc/mosquitto/ssl/cacert.pem

```

As far as I can tell from a few hours googling this, my configuration for the port-38883 listener appears to be correct, so I'm baffled that that port is accepting non-SSL connections. Any ideas?

**Comment by ralight** [comment]
Is this using libwebsockets version 2.x? If so, please downgrade to libwebsockets 1.7 - they changed the way TLS is enabled. This will be fixed in mosquitto 1.4.10.

See issue #186.

**Comment by jrlog** [comment]
Thanks for the reply ralight. 

I was indeed using libwebsockets 2.0.0. After reading your response, I downgraded to libwebsockets 1.7, and now websockets connections aren't working at all on either SSL and non-SSL websockets listeners. All four cases (SSL and non-SSL on 31883 and 3883) are giving the same error (Connect failed: AMQJS0007E Socket error:undefined.) 

My downgrade process:
1. Downloaded libwebsockets 1.7 source from https://github.com/warmcat/libwebsockets/tree/v1.7-stable
2. Downgrade libwebsockets:
`
unzip libwebsockets-1.7-stable.zip
cd libwebsockets-1.7-stable
mkdir build
cd build
cmake ..
make
make install
export LD_LIBRARY_PATH=/usr/local/lib
'
3. Recompile and install mosquitto 

I should also mention that I'm using your development branch for some performance testing (i.e. https://github.com/ralight/mosquitto/tree/develop). I haven't tried it with the master eclipse branch.

**Comment by uvzubovs** [comment]
@ralight Do you believe SSL should be working with websockets in 1.4.9? Do you have a build/environment where it is working? Could you please share it with us?

**Comment by uvzubovs** [comment]
@ralight Do you know when 1.4.10 will be released, presumably with working websockets over SSL?

**Comment by ralight** [comment]
@jrlog I make absolutely no guarantees about ralight/mosquitto. It is just a dumping ground for things I want to make available a bit but can change at any time. I'd try again with eclipse/mosquitto/fixes.

@uvzubovs All released versions of mosquitto work with libwebsockets with SSL or not, as long as you're using libwebsockets versions between 1.3 and 1.7 inclusive.

**Comment by uvzubovs** [comment]
@ralight Would you please take a quick look at this config and let us know if it's complete and accurate for websockets with SSL:

```
listener 32883
protocol websockets
certfile /etc/mosquitto/ssl/servercert.pem
keyfile /etc/mosquitto/ssl/key.pem
cafile /etc/mosquitto/ssl/cacert.pem
```

Thanks in advance!

**Comment by ralight** [comment]
If you have mosquitto 1.4.x installed with websockets support, libwebsockets 1.3-1.7 installed, the certificates you list are available and valid, and you're actually using that config file then yes that is fine.

**Comment by jrlog** [comment]
@ralight The problem was that I did not fully qualify the domain name of the server in the server-cert CN. provided to the websockets listener. SSL over websockets is working now with eclipse/mosquitto 1.4.10 using libwebsockets 2.0.0. 

Thank you for all of your help! We really appreciate it.

**Comment by hhhxxjj** [comment]
@jrlog I have the same problem. How did you fully qualify the domain name of the server in the server-cert CN used by the websockets listener?  for example, CN=118.190.60.63?

**Comment by hhhxxjj** [comment]
@jrlog  fixed this bug. It seems that server-cert can't not be self-signed, or, should trust it in the Browser.
