### ISSUE TITLE
"Lock" GitHub app is no longer supported, please switch to lock-threads GitHub action

### ISSUE THREAD

**Issue by eclipsewebmaster** [eclipse/mosquitto#2434]
According to https://github.com/dessant/lock-threads-app, the "Lock" GitHub app is no longer supported. It's recommended to use the https://github.com/marketplace/actions/lock-threads GitHub action instead.

Please let us know, when you've set this up so we can remove the outdated GitHub app.

**Comment by ralight** [comment]
Sorry for not doing this earlier. You can remove the old app now.
