### ISSUE TITLE
Inconsistency in PUBLISH received in $SYS

### ISSUE THREAD

**Issue by Happy-Funtimes** [eclipse/mosquitto#2448]
Hi!

Some of the statistics reported by the tool ($SYS/broker/publish/messages/received and $SYS/broker/load/publish/received/+) are ignoring publishes with QoS 2 or the retain flag. 

According to the documentation on the webpage: 'The total number of PUBLISH messages received since the broker started.'.

The cause seems to be that within lib/packet_mosq.c, it only gets added if it matches the PUBLISH control packet 0x30 after applying a bitmask of 0xF5. To my understanding the bitmask should be either 0xF0 or maybe even 0xF8. The reason being that it should only check the first nibble to see if it is the proper control type (publish == 0x3X) and maybe make sure that it isn't a duplicate (0x08).

Currently the 0xF5 bitmask will essentially mean that retain bits and QoS 2 messages will not be recognized and therefore not included in the system statistics.

I may be misunderstanding its purpose, but wanted to raise it as a point of concern as my instance is reporting next to no publishes received despite receiving regular messages.

**Comment by Antoine-Giatec** [comment]
Nevermind, after testing different search methods I found the issue report I was looking for with https://github.com/eclipse/mosquitto/commit/79339ce55f1c105c1b6662c687fd7055744cf4c7

**Comment by ralight** [comment]
I think this is a throwback from veeerry old versions when library callbacks treated qos 0 messages differently, and it must have been pasted across. Nice spot, thank you!
