### ISSUE TITLE
use_username_as_clientid applied separately for websocket

### ISSUE THREAD

**Issue by jakubondrus** [eclipse/mosquitto#2449]
Hi, 

when I was testing some stuff on my test broker, I found out, that using configuration
```
persistence true
persistence_location /mosquitto/data/

user mosquitto

# Port to use for the default listener.
port 1883

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_dest topic

allow_anonymous false

use_username_as_clientid true

include_dir etc/mosquitto/conf.d
```
and 
```
listener 9001
protocol websockets
```
in conf.d, option
`use_username_as_clientid true` 
was applied only for mqtt listener. It is possible to turn it on when I add this line also in websocket listener file, so it needs to be defined on per lietener basis. Since I am not sure, whether this is intended behaviour, I am posting it here.

I am using `iegomez/mosquitto-go-auth:latest-mosquitto_2.0.12` docker image.

**Comment by ralight** [comment]
Thanks for the report, this is behaving as expected. I've updated the documentation to make this a bit clearer.
