### ISSUE TITLE
Improve Cmake to use `target_include_directories()`

### ISSUE THREAD

**Issue by CraigHutchinson** [eclipse/mosquitto#2452]
The existing cmake appears to use 'include_direcrtories' throughout which is Cmake 2.8 legacy (?). This is meaning client code has to include the following increasing bloat and making inclusion more ugly etc:
```
include_directories(${mosquitto_SOURCE_DIR}/lib ${mosquitto_SOURCE_DIR}/lib/cpp
			${mosquitto_SOURCE_DIR}/include
			${STDBOOL_H_PATH} ${STDINT_H_PATH})
target_link_libraries(my_app libmosquitto)
```

If the cmake is updated to use `target_include_directories( libmosquitto PUBLIC .....)` then client code only need to set the link and the includes are included also (support since >CMAKE 2.8.10 ):

```
target_link_libraries(my_app libmosquitto)
```

**Comment by ralight** [comment]
Thanks for the suggestion. This was largely already fixed on the `develop` branch, and the linked pull request cleans things up even more.
