### ISSUE TITLE
mosquitto_connect returns success, but connect_callback is never called.

### ISSUE THREAD

**Issue by ewan1983** [eclipse/mosquitto#2454]
I use Mosquitto v2.0.11 on Linux as client, connect to a remote broker using TLS certs and keys on port 8883.
In the beginning, everything works perfectly: mosquitto_connect returns success, connect_callback called with success, can subscribe to topic, can publish and receive message. Thank you very much. 

However, when I try to test such a condition that client connects to broker's encrypted 8883 port **without any TLS setting**, I expect it will return an error at some point, but it turns out mosquitto_connect returns success, and **connect_callback is never called**.

Here's my initialization code:
```
mosquitto_lib_init();
p_mosq_obj = mosquitto_new(NULL, true, NULL);

// temporarily remove TLS setting for test
//mosquitto_tls_set(p_mosq_obj, "ca.crt", NULL, "client.crt", "client.key", NULL); 

mosquitto_log_callback_set(p_mosq_obj, my_log_callback);
mosquitto_connect_callback_set(p_mosq_obj, my_connect_callback);
mosquitto_message_callback_set(p_mosq_obj, my_message_callback);
mosquitto_subscribe_callback_set(p_mosq_obj, my_subscribe_callback);

int connect_result = mosquitto_connect(p_mosq_obj, 169.2.2.2, 8883, 60);
```
And I call `mosquitto_loop(p_mosq_obj, 10, 1);` in my while(1) mainloop. 

BTW, calling `mosquitto_publish(p_mosq_obj, NULL, topic, strlen(json_string), json_string, 2, 0);` returns `MOSQ_ERR_NO_CONN`

**Comment by ewan1983** [comment]
Hello? Anyone can help?

**Comment by Daedaluz** [comment]
I'm not 100%.

Could be the fact that mosquitto_connect can actually establish a tcp connection to the server, although, it can never reach
a proper mqtt connection state because the broker expects the connection to be encrypted (connect_callback never called).
CON and CONACK packets are never exchanged.

**Comment by Daedaluz** [comment]
Note: adding a disconnect handler results in repetitive disconnects with 7.

```
LOG: Client null sending CONNECT
Connect result: 0
Disconnect callback: 7
LOG: Client null sending CONNECT
Disconnect callback: 7
LOG: Client null sending CONNECT
Disconnect callback: 7
LOG: Client null sending CONNECT
Disconnect callback: 7
LOG: Client null sending CONNECT
Disconnect callback: 7
LOG: Client null sending CONNECT
Disconnect callback: 7
LOG: Client null sending CONNECT
Disconnect callback: 7
LOG: Client null sending CONNECT
Disconnect callback: 7
LOG: Client null sending CONNECT
Disconnect callback: 7

Process finished with exit code 143 (interrupted by signal 15: SIGTERM)
```

**Comment by ewan1983** [comment]
> Note: adding a disconnect handler results in repetitive disconnects with 7.
> 
> ```
> LOG: Client null sending CONNECT
> Connect result: 0
> Disconnect callback: 7
> LOG: Client null sending CONNECT
> Disconnect callback: 7
> LOG: Client null sending CONNECT
> Disconnect callback: 7
> LOG: Client null sending CONNECT
> Disconnect callback: 7
> LOG: Client null sending CONNECT
> Disconnect callback: 7
> LOG: Client null sending CONNECT
> Disconnect callback: 7
> LOG: Client null sending CONNECT
> Disconnect callback: 7
> LOG: Client null sending CONNECT
> Disconnect callback: 7
> LOG: Client null sending CONNECT
> Disconnect callback: 7
> 
> Process finished with exit code 143 (interrupted by signal 15: SIGTERM)
> ```

Thank you mate, this solves my problem. Much obliged.

**Comment by Daedaluz** [comment]
No problem.
Please close if nothing else 👍

**Comment by ewan1983** [comment]
Problem solved. close issue.

**Comment by ewan1983** [comment]
Problem solved. Close issue.
