### ISSUE TITLE
Anonymous setting for websockets is being ignored

### ISSUE THREAD

**Issue by giddyhup** [eclipse/mosquitto#2459]
I just upgraded to mosquitto 2.0.11 from a a pre 2 version using Raspberry Pi OS Bullseye (`Linux XXX 5.10.92-v7l+ #1514 SMP Mon Jan 17 17:38:03 GMT 2022 armv7l GNU/Linux`). I noticed that now I have to explicitly allow anonymous connections. I allowed it (see excerpt from mosquitto.conf below) but websocket connections are being refused.

```
listener 1884
protocol websockets
allow_anonymous true

listener 1883
allow_anonymous true
```

**Comment by giddyhup** [comment]
I got it working with this, I don't know if this is just a workaround or by design. Please close if this is not an issue.

```
# [...]
allow_anonymous true

# [...]
listener 1884
protocol websockets
allow_anonymous true
socket_domain ipv4

listener 1883
allow_anonymous true
socket_domain ipv4
````

**Comment by ralight** [comment]
Thanks, I'm glad you got it sorted.
