### ISSUE TITLE
execute binary file which shows " cannot open shared object file: No such file or directory" errors

### ISSUE THREAD

**Issue by PaulTsai20160627** [eclipse/mosquitto#246]
Hi : 

Here is one problem as I make and execute the examples c file named temperature_conversion.cpp in the folder directory of temperature_conversion in mosquitoo examples folder. due to there showed 
"cannot open shared object file: No such file or directory" , so I search that on the web site:
https://www.gnu.org/software/gsl/manual/html_node/Shared-Libraries.html
which direct me to add 

LD_LIBRARY_PATH=/usr/local/lib

export LD_LIBRARY_PATH

After, adding these two commands , and rerun the execute binary file mqtt_temperature_conversion
it shows the following same error. I do not know why ? and how to solve it?
esp8266@esp8266-VirtualBox:~/mosquitto/examples/temperature_conversion$  LD_LIBRARY_PATH=/usr/local/lib
esp8266@esp8266-VirtualBox:~/mosquitto/examples/temperature_conversion$ export LD_LIBRARY_PATH
esp8266@esp8266-VirtualBox:~/mosquitto/examples/temperature_conversion$ ./mqtt_temperature_conversion 
./mqtt_temperature_conversion: error while loading shared libraries: libmosquittopp.so.1: cannot open shared object file: No such file or directory
esp8266@esp8266-VirtualBox:~/mosquitto/examples/temperature_conversion$ ./mqtt_temperature_conversion 
./mqtt_temperature_conversion: error while loading shared libraries: libmosquittopp.so.1: cannot open shared object file: No such file or directory
esp8266@esp8266-VirtualBox:~/mosquitto/examples/temperature_conversion$ ls
main.cpp  Makefile                     readme.txt                  temperature_conversion.h
main.o    mqtt_temperature_conversion  temperature_conversion.cpp  temperature_conversion.o
esp8266@esp8266-VirtualBox:~/mosquitto/examples/temperature_conversion$ ./mqtt_temperature_conversion 
./mqtt_temperature_conversion: error while loading shared libraries: libmosquittopp.so.1: cannot open shared object file: No such file or directory

**Comment by ralight** [comment]
Did you install the library to /usr/local/lib? If not, your fix of using LD_LIBRARY_PATH won't work. This isn't a mosquitto problem, it's a problem with the way your libraries are configured.

**Comment by ralight** [comment]
There hasn't been any update on this in a while. If you think it's still a problem, please reopen and add more information.
