### ISSUE TITLE
2 different protocols(ws:// and mqtt://) dont share the same topic space

### ISSUE THREAD

**Issue by Lpkuba088** [eclipse/mosquitto#2464]
My mosquitto version: 1.5.7
My linux kernel version:Kernel: Linux 5.10.63-v7+
My device: A raspberry pi 3B+ with Raspbian
Issue:
Hello, i have a program logging my solar electricity stats thats logging the values to my MQTT broker through mqtt://
Now i want to have a separate computer to make a local webpage visualising the data, but when i connect to the port that i put in the config for the websocket protocol i dont see the stats from the logging program, however im sure that the connection is in fact working, i tried posting something in a test topic to the websocket port and i was able to read it in a windows program that supports both protocols, what am i doing wrong.

**Comment by Daedaluz** [comment]
1.5.7 is very old.
Could you try a newer version?

2.0.14 is the latest

**Comment by ralight** [comment]
I'm closing this in the hope that you upgraded to something more recent and the problem went away. If that's not the case, please reopen the issue and provide some more details.
