### ISSUE TITLE
Issue with MQTT v. 3.11

### ISSUE THREAD

**Issue by Bierseppi** [eclipse/mosquitto#247]
When i connect with the Paho lib and Python i can't get a connection.
I searched for a while.
-> Paho uses originally MQTTv3.11 and mosquitto should understand it but does not!
When i use the Version 3.1 in Paho everything is working fine.

Maybe the listener witch supports v3.11 is broken ?

**Comment by ralight** [comment]
Please make sure you are not using an old version of mosquitto. If you are
using Debian/Ubuntu then some of the versions available by default are too
old.
