### ISSUE TITLE
[resolved] failed to cross-compile QNX on ubuntu16

### ISSUE THREAD

**Issue by Gonglja** [eclipse/mosquitto#2486]
When I cross-compiled the library on ubuntu16.04, I could not find `-lpthread` and `-ldl` when linking, causing the build to fail.

After a period of investigation, I found that the following codes were not judged in CmakeLists.txt, which led to the continued search for pthreads during cross-compilation, [while pthread of QNX were in `libc`](https://www.qnx.com/developers/docs/6.5.0SP1.update/com.qnx.doc.neutrino_lib_ref/p/pthread_create.html). 

	else (WIN32)
		find_library(LIBPTHREAD pthread)
		if (LIBPTHREAD)
			set (PTHREAD_LIBRARIES pthread)
		else (LIBPTHREAD)
			set (PTHREAD_LIBRARIES "")
		endif()
		set (PTHREAD_INCLUDE_DIR "")
	endif (WIN32)](https://github.com/eclipse/mosquitto/blob/8212bbe29b6fc0a49c30a15b22a36ff0ac7b9d32/CMakeLists.txt#L79-L87)
Therefore, I made the following modifications.
```text
else (WIN32)
	find_library(LIBPTHREAD pthread)
	if (LIBPTHREAD)
        if (QNX) 
        	set (PTHREAD_LIBRARIES c)
        else (QNX)
            set (PTHREAD_LIBRARIES pthread)
        endif (QNX)
	else (LIBPTHREAD)
		set (PTHREAD_LIBRARIES "")
	endif()
	set (PTHREAD_INCLUDE_DIR "")
endif (WIN32)
```
This way, manually specifying the QNX platform when building the build script can be successful.

The build script is as follows，add  `-DQNX=yes `
```bash
source ~/qos20/qnxsdp-env.sh
mkdir out && cd out
cmake \
        -DCMAKE_C_COMPILER=~/qos20/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.0.0-gcc\
        -DCMAKE_CXX_COMPILER=~/qos20/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.0.0-g++\
        -DOPENSSL_ROOT_DIR=~/openssl1.1.1k/qnx/lib\
        -DCMAKE_INCLUDE_PATH=~/openssl1.1.1k/qnx/include\
        -DCMAKE_INSTALL_PREFIX=`pwd`/out/qnx\
        -DPTHREAD_INCLUDE_DIR=~/qos20/target/qnx7/usr/include/\
        -DLIBPTHREAD=~/qos20/target/qnx7/aarch64le/usr/lib/\
        -DQNX=yes \
        -DHAVE_SYS_EPOLL_H=false\
        ..

make -j12 && make install   
```

The [version(2.0.10)](https://github.com/eclipse/mosquitto/releases/tag/v2.0.10) is verified and can be used normally

**Comment by ralight** [comment]
The cmake scripts have been reworked quite a lot since your report and are using more generic ways of finding thread support. I hope that this fixes things for you. I'm going to close the issue, but if it is still a problem please feel free to reopen it.

If you want to test, please try the `develop` branch.
