### ISSUE TITLE
Some questions about libmosquitto

### ISSUE THREAD

**Issue by FStefanni** [eclipse/mosquitto#2487]
Hi,

sorry for posting here, since I have read that questions hsould go to the mailing list, but no one answered me there...

I am trying to use libmosquitto client API into a project, using the async api, but the followings are not clear to me:

1. I like to perform a check to see the connection status, but no "mosquitto_is_connected()" or similar method is provided. Is there a way to know the status?
2. I do not understand when the callback set with "mosquitto_disconnect_callback_set()" is called. Is it on unexpected disconnections? Or is it called when I call "mosquitto_disconnect()"? Or both?
3. If I understand correctly, the async api should reconnect automatically in case of disconnection. Will it also automatically re-subscribe to the topics?

Can anyone help please?
Thank you,
regards

**Comment by ralight** [comment]
Sorry for the delay replying.

There is no `mosquitto_is_connected()` function - perhaps there should be. You can deduce whether the client currently thinks it is connected by observing the connect and disconnect callbacks.

The disconnect callback will be called after you call `mosquitto_disconnect()`, if there is a network problem, or if the server does not respond to a PINGREQ in time.

The library does not keep track of what topics you subscribe to, you will need to resubscribe - this is best done in the connect callback.

**Comment by FStefanni** [comment]
Hi,

thank you for the infos.
This solves my issues.

Regards
