### ISSUE TITLE
mosquitto_reinitialise documentation error

### ISSUE THREAD

**Issue by rroguski** [eclipse/mosquitto#2489]
Hi,

had a nasty bug in my code and by accident found a documentation error in 
https://github.com/eclipse/mosquitto/blob/master/include/mosquitto.h#L327

In the function's implementation https://github.com/eclipse/mosquitto/blob/master/lib/mosquitto.c#L140 one can see that instead of returning `MOSQ_ERR_NOMEM` it returns `MOSQ_ERR_MALFORMED_UTF8` here: https://github.com/eclipse/mosquitto/blob/master/lib/mosquitto.c#L167

**Comment by ralight** [comment]
Thank you! It actually should be returning `MOSQ_ERR_NOMEM` as well as `MOSQ_ERR_MALFORMED_UTF8`. I've fixed both parts.
