### ISSUE TITLE
MQTT 5 supported on Moquette broker?.

### ISSUE THREAD

**Issue by keshavck** [eclipse/mosquitto#2498]
Does currently broker supports mqtt 5? if not When Can we have MQTT 5 supported on Moquette broker?

**Comment by karlp** [comment]
This is the bug tracker for the mosquitto project, which is not Moquette, even though they are both mqtt (the protocol) brokers.  You probably want to ask this question on the Moquette project bugtracker: https://github.com/moquette-io/moquette

**Comment by keshavck** [comment]
closing
