### ISSUE TITLE
find_package does not find sqlite3

### ISSUE THREAD

**Issue by wrmbaron** [eclipse/mosquitto#2501]
I am using mosquitto develop (2.1.0) on debian10. The find_package for sqlite3 does not work. After changing the case it does. The following line works for me:

`find_package(SQLite3 REQUIRED)`

The previous lower-case version may work on MS-Windows, but should not work on linux or other case sensitive systems.

**Comment by ralight** [comment]
Thank you for the report, this was fixed as part of a cmake cleanup a while ago.
