### ISSUE TITLE
LWM2M nad COAP on top of MQTT

### ISSUE THREAD

**Issue by Frendzel** [eclipse/mosquitto#2507]
Hi guys,
we're looking for implementation of lwm2m server/bs server on top of MQTT instead of UDP + DTLS. Did you consider anything like this in the past? Do you have any idea which project would be the best starting point to work with on that target? I'm considering some californium replacements in Leshan or I'm thinking about coap/leshan wrappers for MQTT. Let me know what do you think about it.
[Slide nr 7](https://wiki.eclipse.org/images/e/e1/LWM2M_MQTT_EclipseIoTDaysGrenoble.pdf)

**Comment by ralight** [comment]
Sorry, I don't think I can help you with that.
