### ISSUE TITLE
mosquitto_pub appends unnecessary bytes for publish messages

### ISSUE THREAD

**Issue by simonmdsn** [eclipse/mosquitto#2518]
Sending a publish message with mosquitto_pub with version 3.1.1 appends bytes `224` and `0` at the end.
Example command:

 `mosquitto_pub -p 6000 -t mytopic -d -m hello123 -V mqttv311` 

produces the following bytes

 `[48, 17, 0, 7, 109, 121, 116, 111, 112, 105, 99, 104, 101, 108, 108, 111, 49, 50, 51, 224, 0]`

Where bytes `[104, 101, 108, 108, 111, 49, 50, 51]` is the payload with the message hello123. But there are more bytes after the payload. The 3.1.1 specification does not mention anything to be appended after the payload?

I tested other MQTT clients, and they do not share behavior with mosquitto_pub. 

I am running Linux 20.04 with mosquitto version 2.0.14.

**Comment by ptjm** [comment]
The 17 in the second byte is the number of bytes remaining in the message. That ends at the "3" of "hello123". 224 0 is the next control message, which is a disconnect (0xe0 0x00).

**Comment by simonmdsn** [comment]
I am so embarassed.
