### ISSUE TITLE
NetBSD support

### ISSUE THREAD

**Issue by amoibos** [eclipse/mosquitto#252]
Hello,
it would be nice if could integrate some patches to recognize NetBSD in your next release. 

--- lib/CMakeLists.txt.orig 2016-06-02 21:20:22.000000000 +0000
+++ lib/CMakeLists.txt  2016-08-28 14:00:33.700421980 +0000
@@ -43,9 +43,9 @@

 set (LIBRARIES ${OPENSSL_LIBRARIES} ${PTHREAD_LIBRARIES})

-if (UNIX AND NOT APPLE)
+if (UNIX AND NOT APPLE AND NOT ${CMAKE_SYSTEM_NAME} MATCHES "NetBSD")
    set (LIBRARIES ${LIBRARIES} rt)
-endif (UNIX AND NOT APPLE)
+endif (UNIX AND NOT APPLE AND NOT ${CMAKE_SYSTEM_NAME} MATCHES "NetBSD")

 if (WIN32)
    set (LIBRARIES ${LIBRARIES} ws2_32)

--- lib/memory_mosq.h.orig  2016-06-02 21:20:22.000000000 +0000
+++ lib/memory_mosq.h   2016-08-28 14:30:34.000000000 +0000
@@ -20,7 +20,7 @@
 #include <stdio.h>
 #include <sys/types.h>

-#if defined(WITH_MEMORY_TRACKING) && defined(WITH_BROKER) && !defined(WIN32) && !defined(**SYMBIAN32**) && !defined(**ANDROID**) && !defined(**UCLIBC**) && !defined(**OpenBSD**)
+#if defined(WITH_MEMORY_TRACKING) && defined(WITH_BROKER) && !defined(WIN32) && !defined(**SYMBIAN32**) && !defined(**ANDROID**) && !defined(**UCLIBC**) && !defined(**OpenBSD**) && !defined(**NetBSD**)
 #define REAL_WITH_MEMORY_TRACKING
 #endif

--- src/CMakeLists.txt.orig 2016-06-02 21:20:22.000000000 +0000
+++ src/CMakeLists.txt  2016-08-28 14:13:03.999103447 +0000
@@ -85,6 +85,8 @@
 if (UNIX)
    if (APPLE)
        set (MOSQ_LIBS ${MOSQ_LIBS} dl m)
-   elseif (${CMAKE_SYSTEM_NAME} MATCHES "NetBSD")
-       set (MOSQ_LIBS ${MOSQ_LIBS} m)

--- config.mk.orig  2016-06-02 21:20:22.000000000 +0000
+++ config.mk   2016-08-28 15:27:03.968104814 +0000
@@ -115,7 +115,7 @@
 BROKER_CFLAGS:=${LIB_CFLAGS} ${CPPFLAGS} -DVERSION="\"${VERSION}\"" -DTIMESTAMP="\"${TIMESTAMP}\"" -DWITH_BROKER
 CLIENT_CFLAGS:=${CFLAGS} ${CPPFLAGS} -I../lib -DVERSION="\"${VERSION}\""

-ifneq ($(or $(findstring $(UNAME),FreeBSD), $(findstring $(UNAME),OpenBSD)),)
+ifneq ($(or $(findstring $(UNAME),FreeBSD), $(findstring $(UNAME),OpenBSD), $(findstring $(UNAME),NetBSD)),)
    BROKER_LIBS:=-lm
 else
    BROKER_LIBS:=-ldl -lm

--- src/net.c.orig  2016-06-02 21:20:22.000000000 +0000
+++ src/net.c   2016-08-28 15:15:07.413097823 +0000
@@ -35,7 +35,7 @@
 #include <tcpd.h>
 #endif

-#ifdef **FreeBSD**
+#if defined(**FreeBSD**) || defined(**NetBSD**)
 #  include <netinet/in.h>
 #  include <sys/socket.h>
 #endif

--- lib/net_mosq.c.orig 2016-06-02 21:20:22.000000000 +0000
+++ lib/net_mosq.c  2016-08-28 15:15:43.540861477 +0000
@@ -34,7 +34,7 @@
 #include <sys/endian.h>
 #endif

-#ifdef **FreeBSD**
+#if defined(**FreeBSD**) || defined(**NetBSD**)
 #  include <netinet/in.h>
 #endif

**Comment by gdt** [comment]
Resolved by https://github.com/eclipse/mosquitto/pull/258 and should be closed.
