### ISSUE TITLE
[new feature] config file validation command

### ISSUE THREAD

**Issue by hongkongkiwi** [eclipse/mosquitto#2521]
At present, I'm just starting mosquitto and praying the config validates correctly (is there any other method?)

If it does not validate correctly, mosquitto will get into an endless start->crash->restart loop.

It would be great if there was a mosquitto config-check command which will exit with code 0 if config is OK or exit code >= 1 if config fails. Then I can run this to check the configuration before starting mosquitto.

This idea is used with something like apache where you have config updates regularly.

It would be nice if it was a build in command to mosquitto, or a separate bin tool, this would be incredibly useful to me on an embedded device. If there's any config problem, I can restore known working config files.

**Comment by abiliojr** [comment]
@hongkongkiwi , could you please try #2527 and give your comments

**Comment by hongkongkiwi** [comment]
Works well! Be great if this could be merged :)

**Comment by ralight** [comment]
Thank you, this was a good suggestion.
