### ISSUE TITLE
mosquitto(all versions) crashes with websockets enabled, segfault error 6 in libwebsockets.so.3.0.0

### ISSUE THREAD

**Issue by cordovapolymer** [eclipse/mosquitto#253]
Mosquitto crashes every second day, I have to restart it manually.
`
kernel: [1006237.390667] mosquitto[25279]: segfault at 54 ip 00007f367c6bd6e4 sp 00007fff389dcd60 error 6 in libwebsockets.so.3.0.0[7f367c6b9000+10000]`

Most interesting thing that I run it on two ports: mqtt 1883  and websockets 8000, it stops listening on mqtt 1883 port but continues operation on websockets 8000. After a restart it fully recovers until the next crash.  

I'm running mosquitto on debian 8.5 jessie installed from the [official repository ](http://repo.mosquitto.org/debian/mosquitto-jessie.list). Current stable Debian 8.5 Jessie  [comes](https://packages.debian.org/jessie/libwebsockets3) with libwebsockets 1.2.2-1.

The issue happened both on 1.4.8 and 1.4.9, I've just updated it to 1.4.10, and it crashed again with exactly the same error and memory addresses.

This issue also has been described in https://github.com/Geodan/gost/issues/40 and https://github.com/eclipse/mosquitto/issues/227

**Comment by cordovapolymer** [comment]
any hope that the issue will be fixed?

**Comment by ralight** [comment]
Honestly, libwebsockets 1.2.2 is buggy anyway so there is little point trying to fix problems associated with it. I think the best thing for me to do is disable websockets support for debian jessie as well.

You can of course go and get a more recent version of libwebsockets and compile it yourself.

**Comment by cordovapolymer** [comment]
> Honestly, libwebsockets 1.2.2 is buggy anyway so there is little point trying to fix problems associated with it. I think the best thing for me to do is disable websockets support for debian jessie as well.

Please do not, Debian will definitely update libwebsockets and the issue will disappear then, the workaround for now is not to send large messages, the issue doesn't happen anymore after I started splitting messages larger than 2048 bytes(a limit may be higher, but I didn't test it).

**Comment by ralight** [comment]
There hasn't been an update here for a while so I'm going to close this issue. If you think this is still a problem, please reopen and add more information.

**Comment by shah253kt** [comment]
I'm still having this problem with mosquitto 1.4.11

**Comment by mdavids** [comment]
It happend to me yesterday - but in general the daemon runs pretty stable.

May  3 17:49:44 localhost kernel: [1189759.369692] mosquitto[776]: segfault at c0ba44d1 ip b73fb66a sp bf81c714 error 5 in libwebsockets.so.7[b73e8000+22000]

1.4.11-0mosquitto2xenial1

Ubuntu 16.04.2 LTS

**Comment by AlReem** [comment]
I am also having the same issue with the following installations.

Server: Ubuntu `16.04.2 LTS` (Xenial)
Mosquitto: `v1.4.8`
libwebsockets: `v2.2.0` (Compiled from source)

Extract from journalctl:
`Jun 11 05:57:28 myserver kernel: mosquitto[23293]: segfault at 8 ip 00007a55e0779b29 sp 00007ffd5a966a80 error 4 in libwebsockets.so.7[7a65f0771000+1f000]`

Please help

**Comment by fezeev** [comment]
By the way. This:
> libwebsockets: v2.2.0 (Compiled from source)

confronts with this:
> Extract from journalctl:
> Jun 11 05:57:28 myserver kernel: mosquitto[23293]: segfault at 8 ip 00007a55e0779b29 sp 00007ffd5a966a80 error 4 in libwebsockets.so.7[7a65f0771000+1f000]

libwebsockets.so.7 is filename for libwebsocket with 1.7.* versions. 
correct libwebsocket 2.2.0 filename will be libwebsockets.so.10

**Comment by silky** [comment]
i'm definitely seeing this as a problem

i don't see segfaults, i just see that connections are defined.

restarting the mosquitto service fixes it

my configuration:

```
# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid

listener 1883
listener 1884
protocol websockets

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d
```

**Comment by silky** [comment]
@ralight  - anything i can do to get some more info for you on why this might be failing?

**Comment by wsw70** [comment]
@silky: if this is still relevant, maybe https://github.com/eclipse/mosquitto/issues/1004#issuecomment-498145961 would help?
