### ISSUE TITLE
user authentication issue

### ISSUE THREAD

**Issue by Saggittarius-A** [eclipse/mosquitto#2544]
![image](https://user-images.githubusercontent.com/57368869/169728516-64c995aa-6b31-47ea-881a-dc3c8853ca94.png)
Whenever we create a new user with already existing userid it just updates the password of that user id without even acknowleding the user that this user id already exists.

**Comment by ralight** [comment]
Just to be clear, the issue you're reporting is that mosquitto_passwd doesn't tell you when it updates a password?

**Comment by naina24** [comment]
It doesn't tell is our password updated or not and when if we try to create new user with existing user id it just overwrites with the new password... It doesn't tell this client id already exists!!

**Comment by ralight** [comment]
Thank you. That's now in the `develop` branch.
