### ISSUE TITLE
Retain Handling Options Does Not Work When Set To 1

### ISSUE THREAD

**Issue by Zephyrus29** [eclipse/mosquitto#2552]
Running Mosquitto v2.0.14 on Ubuntu 20.04. 

When retain handling is set to 0 or 2, the correct behaviour is seen (already sent retained messages are sent on 0 and not on 2) but when set to 1, messages are sent again regardless of if they were previously sent.

I'm running the Paho C MQTT library and have debugged that to see that the flags are set correctly. There's not trace that shows these settings available in Mosquitto.

**Comment by Zephyrus29** [comment]
I'm a dummy. This functionality does work, I had a client side issue

**Comment by karlp** [comment]
would you like to close the issue?
