### ISSUE TITLE
docker scan eclipse-mosquitto shows vulnerablities

### ISSUE THREAD

**Issue by wickywaka** [eclipse/mosquitto#2556]
I ran docker scan on the docker images and it shows some vulnerabilities. I don't know if you guys use this tool regularly or if its any good but I thought I would report it here. Below is the last part of result:

```
Tested 20 dependencies for known vulnerabilities, found 6 vulnerabilities.

Base Image     Vulnerabilities  Severity
alpine:3.14.3  5                1 critical, 3 high, 0 medium, 1 low

Recommendations for base image upgrade:

Minor upgrades
Base Image   Vulnerabilities  Severity
alpine:3.15  0                0 critical, 0 high, 0 medium, 0 low

```

**Comment by ralight** [comment]
Hi,

The docker images are built by the dockerhub official images program, which rebuilds images actively when changes are made in upstream images. I don't know which images you're scanning, but the ones I'm looking at (`eclipse-mosquitto:2`, for example) are based on alpine 3.14.6.

**Comment by wickywaka** [comment]
I do the default pull, and it says its using the latest tag. Don't know how to find out if there is another tag associated with the pulled image. May be I am doing something wrong on my side. I will close the issue.

**Comment by wickywaka** [comment]
Definitely something was wrong on my side. After cleaning cache it doesn't show any vulnerabilities when I scan image with latest tag.
