### ISSUE TITLE
Websockets support not available on containerized Alpine

### ISSUE THREAD

**Issue by bertmelis** [eclipse/mosquitto#2562]
I'm trying to run mosquitto in an Alpine container but it says websockets support is not available:

```
1654862199: Error: Websockets support not available.

1654862199: Error found at /mqtt/mosquitto.conf:38.
```

Line 37 and 38 of the mosquitto.conf are

```
listener 8083
protocol websockets
```

The containerfile is very straightforward:

```
FROM alpine:latest
RUN addgroup -g 1000 mqttgroup && \
    adduser -G mqttgroup -u 1000 -h /mqtt -D mqttuser && \
    apk --no-cache add mosquitto
WORKDIR /mqtt
COPY data/ /mqtt/
RUN chown -R mqttuser:mqttgroup /mqtt
USER mqttuser
RUN mosquitto_passwd -U /mqtt/passwd
EXPOSE 1883 8883 8083 8084
CMD ["mosquitto", "-c", "/mqtt/mosquitto.conf"]
```

Explicitely installing `libwebsockets` doesn't improve.

Versions are (taken from build log):
- Alpine 3.16
- libwebsockets (4.3.1-r0)
- c-ares (1.18.1-r0)
- mosquitto-libs (2.0.14-r0)
- mosquitto (2.0.14-r0)

**Comment by bertmelis** [comment]
Meanwhile I switched to the official docker image and obviously the error is gone. The "only" difference I see is that I used latest Alpine (=3.16) and your official mosquitto image uses Alpine 3.14

**Comment by hardillb** [comment]
You are installing Alpines build of mosquitto, where as the offical mosquitto images build on top of Alpine.

So the difference is that Alpines build of mosquitto hasn't set the flag to enable websockets.

**Comment by bertmelis** [comment]
Ah. They must have changed it then.
