### ISSUE TITLE
mosquitto version 1.6.9 support for bridge_protocol_version mqttv50

### ISSUE THREAD

**Issue by yusufk** [eclipse/mosquitto#2563]
I'm using Mosquitto 1.6.9 on Ubuntu and I'm trying to bridge to a broker that supports MQTT5.

If I set:
bridge_protocol_version mqttv50
I get:
Error: Invalid bridge_protocol_version value (mqttv50).

I tried bridge_protocol_version mqttv5, same result. If I don't set anything, it crashed trying to connect.

**Comment by ptjm** [comment]
Version 1.6 only supported mqttv31 and mqttv311 for bridge_protocol_version. You need to move to version 2.0(.14!) for outbound bridges to talk mqtt 5.

**Comment by yusufk** [comment]
Thank you
