### ISSUE TITLE
Please don't ignore SIGPIPE in the mosquitto client library

### ISSUE THREAD

**Issue by nmeum** [eclipse/mosquitto#2564]
Hello,

Presently, the mosquitto MQTT library ignores `SIGPIPE`:

https://github.com/eclipse/mosquitto/blob/d5970ca9985f4d3193fe7a359707723090bb13e9/lib/mosquitto.c#L112-L114

This is a problem since this will affect all threads of the process running the mosquitto client library. Furthermore, as per `signal(7)` *“A child created via fork(2) inherits a copy of its parent's signal dispositions.”*. That is, any process forked from the process which uses the mosquitto client library will also ignore `SIGPIPE` by default. I believe it to be a very bad idea to have a C library introduce this sort of side-effect since code using the C library may require `SIGPIPE` to not be ignored.

We noticed this at Alpine Linux where we use mosquitto as part of our build infrastructure. See:

* https://github.com/ncopa/mqtt-exec/pull/7
* https://gitlab.alpinelinux.org/alpine/infra/infra/-/issues/10758

Opening this issue here in the hopes that you might consider not modifying signal dispositions in the mosquitto library.

**Comment by ericonr** [comment]
I can think of two alternatives here:

- use [send(2)](https://man7.org/linux/man-pages/man2/send.2.html) with `MSG_NOSIGNAL` on platforms where it's available
- ignore the signal but with a dummy function instead, which can't be inherited (is still uncooperative behavior from a C library, but at least less disruptive for some use cases)

**Comment by ralight** [comment]
Agreed, this is bad behaviour. Thanks for pointing it out.
