### ISSUE TITLE
Publisher gets "Socket error on client mosqpub..." on mac OS x with latest brew build

### ISSUE THREAD

**Issue by dhruvkapur91** [eclipse/mosquitto#257]
$ brew install mosquitto

$ mosquitto

$ mosquitto_pub -t 'test/topic' -m 'hello world'

Log from mosquitto:
⇒  mosquitto
1472678368: mosquitto version 1.4.8 (build date 2016-02-14 11:22:37-0800) starting
1472678368: Using default config.
1472678368: Opening ipv4 listen socket on port 1883.
1472678368: Opening ipv6 listen socket on port 1883.
1472678369: New connection from ::1 on port 1883.
1472678369: New client connected from ::1 as mosqsub/3418-INDhruvK-2 (c1, k60).
1472678371: New connection from ::1 on port 1883.
1472678371: New client connected from ::1 as mosqpub/5300-INDhruvK-2 (c1, k60).
1472678371: Socket error on client mosqpub/5300-INDhruvK-2, disconnecting.

Also I realize that this issue has been potentially fixed in 1.4.10 build number, how do I get that over brew?

**Comment by ralight** [comment]
Bit of a delay replying, sorry. 1.4.10 is in homebrew now.
