### ISSUE TITLE
Latest versions on the 1.6.x release line not available even in mosquitto-dev PPA

### ISSUE THREAD

**Issue by albinsuresh** [eclipse/mosquitto#2571]
None of the recent 1.6.x versions higher than 1.6.9 are available for the Ubuntu 20.04 version. Even after adding the [mosquitto-dev PPA](https://launchpad.net/~mosquitto-dev/+archive/mosquitto-ppa/) to the repository list, only the latest 2.0.x version was available and not the latest ones on the 1.6.x line.

Here are the available package versions after adding the mosquitto-dev PPA:

```
$ apt-cache policy mosquitto
mosquitto:
  Installed: 1.6.9-1
  Candidate: 2.0.14-0mosquitto1~focal1
  Version table:
     2.0.14-0mosquitto1~focal1 500
        500 http://ppa.launchpad.net/mosquitto-dev/mosquitto-ppa/ubuntu focal/main amd64 Packages
 *** 1.6.9-1 500
        500 http://in.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
```

OS version details:
```
Operating System: Ubuntu 20.04.4 LTS
Kernel: Linux 5.13.0-51-generic
Architecture: x86-64
```

**Comment by ralight** [comment]
That's correct, the PPAs only have the most recent versions available. You could try the snap packages instead https://snapcraft.io/mosquitto

**Comment by ralight** [comment]
I'm closing this issue because I think I've addressed it sufficiently to answer what you need. I'm trying to close issues like this to get on top of the issues list. If there is still something left to do on this issue, please reopen it and give more details.
