### ISSUE TITLE
Commit 376226c1 broke building with OPENSSL_NO_ENGINE

### ISSUE THREAD

**Issue by dirkfeytons** [eclipse/mosquitto#2589]
I was building 2.0.14 on Linux against an OpenSSL that is built with `OPENSSL_NO_ENGINE`. The build failed in src/net.c because in `net__tls_load_verify()` there's a call to  `net__load_engine()` but that function is not compiled in.
I traced it back to commit 376226c1.

**Comment by ralight** [comment]
Thank you, that's not an option I've actually come across. That's now fixed and will be in 2.0.15.
