### ISSUE TITLE
start_type lazy didn't reconnect. dump core.

### ISSUE THREAD

**Issue by hakofugu41** [eclipse/mosquitto#259]
Hello,
I am trying to use lazy option, but mosquitto crashed.
Then, dumps core.

ENV: 
 CentOS 6.7
 mosquitto version 1.4.8

Figure:
 mosquitto_pub --send message--> mosquitto(A) --bridge--> mosquitto(B)

I did these steps on my PC. (One host only)

**1.Execute mosquitto(B)**
  $ mosquitto -v 
  
**2.Execute mosquitto(A).**
  Connect mosquitto(A) and mosquitto(B).
  $ mosquitto -c start_type.conf
  (The contents of start_type.conf are below)

**3.Interrupt mosquitto(B) with Ctrl+C.**

**4.Try to reconnect mosquitto(A) and mosquitto(B)**
  $ mosquitto -v 
  Because of threshold option, not reconnected.

**5.Send message to mosquitto(A)**
  $ mosquitto_pub -t /topic/A -m test1 -p 1884

**6.Resend message to mosquitto(A)**
  $ mosquitto_pub -t /topic/A -m test2 -p 1884

**7.mosquitto(A) carashes. Then, dumps core files.**
  Logs:
    1473063013: Connecting bridge bridge_out (127.0.0.1:1883)
    mosquitto: loop.c:451: loop_handle_reads_writes: Assertion `pollfds[context->pollfd_index].fd == context->sock' failed.
    Aborted (core dumped)

----

**start_type.conf**
#for bridge(out)
connection bridge_out
address 127.0.0.1:1883
topic /topic/# out 2
start_type lazy
threshold 2
idle_timeout 10

#for mosquitto_pub
listener 1884

**Comment by hakofugu41** [comment]
I have tried with mosquitto 1.4.10 and show the same behavior.

**Comment by ralight** [comment]
I've been able to reproduce this thanks to your instructions. I've pushed a fix to the "fixes" branch which will either end up in 1.4.11 or 1.5.

Thanks very much for reporting it!

**Comment by hakofugu41** [comment]
Thanks!!! XD
