### ISSUE TITLE
how to install v1.6.15 of ubuntu?

### ISSUE THREAD

**Issue by kervin521** [eclipse/mosquitto#2592]
```
OS: 20.04
arch: amd64/arm64
deb sources:
http://ppa.launchpad.net/mosquitto-dev/mosquitto-ppa/ubuntu
https://ppa.launchpadcontent.net/mosquitto-dev/mosquitto-ppa/ubuntu

I want to install mosquitto 1.6.15,how to do for me?
```

**Comment by ralight** [comment]
I'm afraid you can't do that with the PPA version, only the latest code is available.

You could use docker, the 1.6.x line is available there. Likewise snap packages have the 1.6.x releases available.

I would always suggest using the latest release however.

**Comment by ralight** [comment]
I'm closing this issue because I think I've addressed it sufficiently to answer what you need. I'm trying to close issues like this to get on top of the issues list. If there is still something left to do on this issue, please reopen it and give more details.
