### ISSUE TITLE
MQTTS (ssl/tls) not working when testing with mqttlens: SSL routines:ACCEPT_SR_CLNT_HELLO

### ISSUE THREAD

**Issue by pratheekreddy** [eclipse/mosquitto#2600]
I created ca.crt, server.key, server.crt with openssl and configured it in mosquitto.config.

//mosquito.config
```
port 8883
cafile /mosquitto/cert/ca/ca.crt
keyfile /mosquitto/cert/server/server.key
certfile /mosquitto/cert/server/server.crt
require_certificate true
tls_version tlsv1.2

listener 9001
protocol websockets
cafile /mosquitto/cert/ca/ca.crt
keyfile /mosquitto/cert/server/server.key
certfile /mosquitto/cert/server/server.crt
require_certificate true
tls_version tlsv1.2

allow_anonymous true
use_identity_as_username true
```
when I started the container 
opened the MQTTlens and configured it. then i see below error in the logs
```
New connection from <ip> on port 8883.
1658806071: OpenSSL Error[0]: error:140260FC:SSL routines:ACCEPT_SR_CLNT_HELLO:unknown protocol
1658806071: Socket error on client <unknown>, disconnecting
```

**Comment by ralight** [comment]
`unknown protocol` this almost always means that the client isn't connecting with TLS.

**Comment by ralight** [comment]
I'm closing this issue because I think I've addressed it sufficiently to answer what you need. I'm trying to close issues like this to get on top of the issues list. If there is still something left to do on this issue, please reopen it and give more details.

**Comment by pratheekreddy** [comment]
is there any way to attach TLS in mqtt lens?
