### ISSUE TITLE
Not compiling static libraries

### ISSUE THREAD

**Issue by Ev3nt1ne** [eclipse/mosquitto#2606]
I tried several configurations and commands, but this version (differently from previous ones) is not compiling static libraries.

For reference I'm using 
`make clean binary CC=gcc LIB_CFLAGS="-I../openssl/include/" LIB_LIBADD=-L../compiled/lib WITH_STATIC_LIBRARIES=YES WITH_SHARED_LIBRARIES=no WITH_CJSON=no
`
but with several other combination of commands is not working too.

(also had to add WITH_CJSON=no because mosquitto config.h was tring to include cjson as <cjson/cjson.h>, instead of letting me inlcuding it as a library, like openssl, don't know if this behavior is wanted or it is another bug)

G

**Comment by ralight** [comment]
Try `WITH_STATIC_LIBRARIES=yes` instead of `WITH_STATIC_LIBRARIES=YES` :)

`#include <cjson/cJSON.h>` is the standard way to include the cJSON header, but it does need to be installed - you can't use it straight from the cJSON repository like that.
