### ISSUE TITLE
Wrong reason code on disconnect while session takeover.

### ISSUE THREAD

**Issue by der-b** [eclipse/mosquitto#2607]
I think mosquitto is not complaint whit the MQTT 5.0 specification. I'm using the libmosquitto and if i connect two clients with the same ClientID to the broker, than the reason code of the disconnect callback is 0x7 (unknown reason). The [MQTT specification in section 3.1.4](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901073) states the following: 

> If the ClientID represents a Client already connected to the Server, the Server sends a DISCONNECT packet to the existing Client with Reason Code of 0x8E (Session taken over) as described in [section 4.13](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#S4_13_Errors) and MUST close the Network Connection of the existing Client.

Therefor I think, the correct return code would be 0x8E in my case.

Kind regards,

Bernd

**Comment by ralight** [comment]
This was fixed in the `develop` branch, I've backported that fix for 2.0.15. Thanks for the report!
