### ISSUE TITLE
max_inflight_messages parameter changes the limit set by max_queued_messages

### ISSUE THREAD

**Issue by MariusTeltonika** [eclipse/mosquitto#2611]
Hello,

I'm using `mosquitto version 2.0.11`

and set this configuration on one broker:

mosquitto.conf

```
listener 1883
user root
allow_anonymous true
max_queued_messages 1
```

and on another i configure bridge connection:

mosquitto.conf

```
listener 1883
user root
allow_anonymous true
max_queued_messages 1

connection 1
address 192.168.1.2:1883
notifications false
notifications_local_only false
bridge_protocol_version mqttv31
try_private false
topic t both 2
keepalive_interval 60
```

when i subscribe to the both brokers topic name 't' and publish a message to one both receive them successfully.

Then i disconnect one device and publish multiple messages. Looking at the mosquitto.conf setting `max_queued_messages 1
` should mean, that after reconnecting the client, it should receive only one message. but this is not the case. The client receives 21 messages.

After adding one more option to config file `max_inflight_messages 1` and repeating the same testing method, the client receives 2 messages after it reconnects. 

After looking at the code I noticed that `max_inflight_messages` parameter is by default 20 which corresponds to the strange behavior I have noticed.

So my questions are:

Is this supposed to happen?

How do I configure the broker to only send the message count set by `max_queued_messages` (for example I set it to 1) and only receive the message count I have set by this parameter after the client reconnects to the broker. Because now it is always increased by `max_inflight_messages` parameter.

**Comment by ralight** [comment]
The man page states for `max_queued_messages`:

> The maximum number of QoS 1 or 2 messages to hold in the queue (per client) above those messages that are currently in flight.

The process for outgoing QoS 1 and 2 messages is as follows:

If the number of inflight messages is below the inflight message limit, a PUBLISH will be sent for that message. Once the QoS flow for that message is complete, it is removed from the list of messages that are in flight.

If the number of inflight messages is already at the inflight message limit, then the message is added to the queued message list. When an inflight message completes the QoS flow, a new queued message is moved to being inflight.

If the number of queued messages hits the queued message limit, then further outgoing messages are dropped.

I hope that clears up how this is expected to work.

**Comment by MariusTeltonika** [comment]
Yes it does. Thank you,
