### ISSUE TITLE
Question: What is the difference between issues here and in Bugzilla?

### ISSUE THREAD

**Issue by alisajedi** [eclipse/mosquitto#262]
Hello

This is not a bug report. I just have a question. I am a researcher at University of Alberta, doing research on bug assignment in Github and Bugzilla.
This project is also on Mozilla ( https://bugs.eclipse.org/bugs/describecomponents.cgi?product=Mosquitto ) and there are some issues there.

What is the difference between the bugs reported in Bugzilla and the issues reported here in Github? 
My intuition is that the issues listed in the Github repository are the ones that the developers found under development, but the bugs addressed in Bugzilla are for every user in the open source community. 
Is that true? Please correct me if I'm wrong.
Thank you.

**Comment by ralight** [comment]
The bugzilla components are from before we migrated to github. The bugzilla components should have been archived, I've opened a bug there to make sure this happens - thanks for the reminder!

In other words, please file everything here.

**Comment by alisajedi** [comment]
Thanks @ralight .
