### ISSUE TITLE
Problem  Install mosquito V1.4.10 for windows 10 ordinal 341 not found in dll

### ISSUE THREAD

**Issue by Marco401** [eclipse/mosquitto#263]
For information, no problème with 1.3.5.

**Comment by ralight** [comment]
Most likely this is down to not having the correct version of a dll. The likely candidate is the Visual Studio redistributable. You need the one for Visual Stdio 2012 x86:

https://www.microsoft.com/en-gb/download/details.aspx?id=30679

**Comment by gzalo** [comment]
In my case, I needed to install Win32 OpenSSL **v1.0.2j** Light, not the latest version. Reinstalling the VS redistributable did nothing.

**Comment by nurettin** [comment]
v1.0.2j doesn't exist in the installer's link anymore. And the 1.1.0f version gives this error.

**Comment by ralight** [comment]
Try whatever is the latest version of 1.0.2. 1.1.0 is incompatible with 1.0.2.

**Comment by Serhioromano** [comment]
This is not professional. I know that Mosquitto is free but it become sort of big thing. Amazon AWS recommend to pair their IoT with Mosquitto. So you are part of big picture now. And problems like this are not acceptable. I mean there might be problems of different sorts, but this one that prevent me to use Mosquitto at all make me feel frustrated.

I have this 341 error and I cannot find with Google where i can download 1.0.2 version. It is not available any more. At least give us the link to that version or distribute with this file together. 

I spend all day and it ends with nothing. I have to look for other solutions.
