### ISSUE TITLE
Mosquitto from the Ubuntu PPA not installable on Ubuntu 16.04

### ISSUE THREAD

**Issue by AlucardZero** [eclipse/mosquitto#264]
On a fresh install of Ubuntu 16.04, mosquitto from the [PPA](https://launchpad.net/~mosquitto-dev/+archive/ubuntu/mosquitto-ppa) linked from the [download page](https://mosquitto.org/download/) will not install. `apt-get` returns: **mosquitto : Depends: libwebsockets3 (>= 1.2) but it is not installable**.

Please see the current config and full output:

```
~# apt-cache policy mosquitto
mosquitto:
  Installed: 1.4.8-1build1
  Candidate: 1.4.10-0mosquitto2
  Version table:
     1.4.10-0mosquitto2 500
        500 http://ppa.launchpad.net/mosquitto-dev/mosquitto-ppa/ubuntu xenial/main amd64 Packages
 *** 1.4.8-1build1 500
        500 http://mirrors.linode.com/ubuntu xenial/universe amd64 Packages
        100 /var/lib/dpkg/status

~# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
~# apt-get install mosquitto
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mosquitto : Depends: libwebsockets3 (>= 1.2) but it is not installable
E: Unable to correct problems, you have held broken packages.

~# apt-cache policy libwebsockets3
libwebsockets3:
  Installed: (none)
  Candidate: (none)
  Version table:
```

(I have not held any packages)

[libwebsockets3 is not available in 16.04](http://packages.ubuntu.com/search?keywords=libwebsockets3) and the [distro version is built against libwebsockets7](http://packages.ubuntu.com/xenial/mosquitto).

Therefore, currently one cannot use the PPA version, which is newer than the version in universe.

**Comment by AlucardZero** [comment]
Version: 1.4.10-0mosquitto3 now depends on libwebsockets7 - thank you

**Comment by ralight** [comment]
Great, glad the fix worked.

**Comment by ralight** [comment]
(and thanks for letting us know)
