### ISSUE TITLE
`message_size_limit` should block incoming messages exceeding that limit

### ISSUE THREAD

**Issue by alepez** [eclipse/mosquitto#265]
Start a broker with option `message_size_limit` set to 512
Publish a message of 10MB

Expected:

Broker stop handling the message when 512 bytes of payload has arrived, then drop the message.

Actual:

Broker receives 10MB of data, then drop the message. Process' memory usage increase of at least 10MB.

**Comment by karlp** [comment]
it has to receive the message to drop it.  The remote client is still sending that data, you've got to swallow it, or disconnect the client.

**Comment by alepez** [comment]
I guess there isn't any option to make the broker disconnecting clients not respecting payload size, am I right?

**Comment by ralight** [comment]
You are correct, but actually this should be possible in 1.5.

**Comment by Nzbuu** [comment]
I assume that currently messages that exceed message_size_limit will just be swallowed. Is this correct?

If you're going to disconnect clients for exceeding message_size_limit, then you also need an option to prevent a bridge from sending messages that exceed the limit too, e.g. bridge_outgoing_message_size_limit.

**Comment by ralight** [comment]
I'm bumping this to 1.6 as it got mised in 1.5, sorry for that.

**Comment by ralight** [comment]
`max_packet_size` was added in version 1.6. Bridge control will be in 1.7.
