### ISSUE TITLE
mosquitto.conf: unclear whether option order matters

### ISSUE THREAD

**Issue by m1027** [eclipse/mosquitto#2652]
Hi,

I am observing a significant difference by the order of the options (lines) in mosquitto.conf (using 2.0.15). My example mosquitto.conf has just these two lines:
`socket_domain ipv4`
`listener 1883`
versus
`listener 1883`
`socket_domain ipv4`
The first makes mosquitto fail to start with this output:
`mosquitto version 2.0.15 starting`
`Config loaded from /etc/mosquitto/mosquitto.conf.`
`Opening ipv4 listen socket on port 1883.`
`Opening ipv6 listen socket on port 1883.`
`Opening ipv4 listen socket on port 1883.`
`Error: Address already in use`
The second works:
`mosquitto version 2.0.15 starting`
`Config loaded from /etc/mosquitto/mosquitto.conf.`
`Opening ipv4 listen socket on port 1883.`
`mosquitto version 2.0.15 running`
And there seem to be some other configuration order dependencies AFAIK.
Am I missing something trivial here?

**Comment by Daedaluz** [comment]
Order matters, yes.
My understanding is that this primarily true with the listener related parameters.

I also think that using such a config parameter without first defining a listener, will apply the setting to the _default listener_ and start it.

So, in your case:
having `socket_domain ipv4` before any listener setting would apply `socket_domain ipv4` to the default listener and implicitly start it.
Then you have another `listener 1883` which then collides with the already started default listener.

**Comment by m1027** [comment]
Thaks, that's exactly what I was assuming to happen behind the scenes.

But I find it confusing. Especially because per_listener_settings is off (default). And there are more options to be hit by this.

Is there any documentation about this?
man mosquitto.conf does not seem to mention that at all.

**Comment by m1027** [comment]
Thanks again, for these hints on understanding man mosquitto.conf.

So, I sum up the assumptions as follows:

- The section GENERAL OPTIONS is supposed to specify *global* options, except when per_listener_settings is true, then some of them become, well, per-listener ones.
- The section LISTENERS lists per-listener options, independently from per_listener_settings; there is another "General Options" section within the LISTENERS section but this probably still meant per listener.
- Some of the options trigger the creation of a *default listener* even before the first occurrence of the listener option. (I assume the triggering options are those that are meant per-listener usually).

Maybe this is helpful for someone who finds time to improve man mosquitto.conf a bit.

WFM.
