### ISSUE TITLE
Error when connecting to Mosquitto broker from a MQTT client with mbedtls library that enforces tls1.3

### ISSUE THREAD

**Issue by AviEpstein** [eclipse/mosquitto#2669]
**Error when connecting to Mosquitto broker from a MQTT client with mbedtls library that enforces tls1.3**

1) When connecting to the Mosquitto broker from a MQTT client with mbedtls library that enforces tls1.3 I'm getting on unsupported encrypted extension type "0" (sever name) which causes the mbedtls handshake to fail.

2) After adding a patch to ignore this extension I am able to verify the Mosquitto certificate however a new error appears as the Mosquitto server sends a unexpected handshake message after the handshake is finished.

--------------------------------------------------------------------------------------------------------------------------------------------
1) Is tls 1.3 only, supported by "test.mosquitto.org" server? 
2) Has it been verified against mbedtls when it comes to tls1.3?
3) How can I fix this issue?

**note:**
When enforcing tls1.2 the application works successfully. the issue only comes up when we try to force tls1.3 only from the client side.

**more information:**
connection address:  "test.mosquitto.org"
port number: 8883

**Comment by ralight** [comment]
TLS 1.3 is supported, you can verify this using the openssl tool:

```
openssl s_client -connect test.mosquitto.org:8883 -tls1_3
```

I've done that and looked at the wireshark capture and can't see what you describe. Can you provide any more information, if this is still a problem?

**Comment by AviEpstein** [comment]
this was an issue an the older version of mbedtls once I update to the new version of mbedtls and added app support for session resumption the issue was solved.
thank you for the response!
