### ISSUE TITLE
trivial: example plugin for deny protocol version has error in cleanup code

### ISSUE THREAD

**Issue by karlp** [eclipse/mosquitto#2673]
in https://github.com/eclipse/mosquitto/blob/master/plugins/deny-protocol-version/mosquitto_deny_protocol_version.c#L109 in the cleanup, it tries to unregister a handler (EVT_MESSAGE) that was never registered.  This presumably becomes a noop, but its "wrong" and should be trying to unregister the handler that was registered, EVT_BASIC_AUTH.

**Comment by ralight** [comment]
Thank you!
