### ISSUE TITLE
'--quiet' flag does not suppress warnings

### ISSUE THREAD

**Issue by mskardal** [eclipse/mosquitto#2680]
This issue is pretty much a duplicate of https://github.com/eclipse/mosquitto/issues/1284, but it was closed three years ago.

I have a systemd service that triggers a script where I am sending some messages with the `mosquitto_pub` command. When running the script manually from the command line, no warnings are printed. However, journalctl logs the following message `Warning: unable to locate configuration directory default config not loaded.` whenever the systemd service triggers the  `mosquitto_pub` commands. I have tried using the `--quiet` flag, but the warnings still appear in journalctl. I am using v3.1.1 MQTT broker.

**Comment by st1nga** [comment]
I believe the issue is that `mosquitto_pub` looks in `$HOME/.config/mosquitto_pub` for the config
systemd does not set HOME
I added `Environment` to the service file
```
[Service]
Type=simple
Environment=HOME=%h
```
and that fixed the issue.

**Comment by ralight** [comment]
That warning message was removed in 1.6.3, so if you upgrade to a recent version you should be ok.
