### ISSUE TITLE
Authentication plug-in overrides default behavior

### ISSUE THREAD

**Issue by uvzubovs** [eclipse/mosquitto#269]
Hi. Is there a way for my authentication plug-in to delegate back to Mosquitto's standard logic in some cases? For example, I like Mosquitto's topic access control based on patterns, but if I supply the plug-in, I need to reproduce it myself? Also, my authentication logic applies in some cases, and in others I am perfectly fine with passwords and client SSL certs. Is there a way for me to return "not applicable" as is done in JAAS, for example, so that standard Mosquitto logic kicks in? Thanks!

**Comment by ralight** [comment]
Not at the moment, but this will be possible in version 1.5.

**Comment by ralight** [comment]
This is fixed in version 1.5.
