### ISSUE TITLE
using-lets-encrypt-certificates-with-mosquitto.md suggests using an expired cacert

### ISSUE THREAD

**Issue by mattst88** [eclipse/mosquitto#2692]
DST Root CA X3 (`/etc/ssl/certs/DST_Root_CA_X3.pem`) expired in September 2021. See [1], which says ISRG Root X1 (`/etc/ssl/certs/ISRG_Root_X1.pem`) should be used now.

[1] https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

**Comment by ralight** [comment]
Thank you, that's an old post but having out of date information is no use for anyone.

**Comment by mattst88** [comment]
Thank you!
