### ISSUE TITLE
MQTT bridge send `qos 0` message, If I send message to `qos 1` from another broker.

### ISSUE THREAD

**Issue by Bhautik0110** [eclipse/mosquitto#2694]
### Issue
I have created the bridge between AWS IoT, and Mosquitto. From AWS IoT, I send a message using QoS level 1, Bridge receives the message and sends a message to another client connected to mosquitto. Mosquitto receives the message as expected q1 level. But it sends the message to the subscriber using q0 level.

### Logs
```log
mosquitto-mosquitto1-1  | 1669293603: Received PUBLISH from local.mosquittobridge (d0, q1, r0, m1, 'general/demo/shadow/update', ... (48 bytes)) # Received q0
mosquitto-mosquitto1-1  | 1669293603: Sending PUBLISH to 1 (d0, q0, r0, m0, 'general/demo/shadow/update', ... (48 bytes)) # Why QoS 0?
mosquitto-mosquitto1-1  | 1669293603: Sending PUBACK to local.mosquittobridge (m1, rc0)
mosquitto-mosquitto1-1  | 1669293603: Received PUBLISH from local.mosquittobridge (d0, q1, r0, m1, 'general/demo/shadow/update/accepted', ... (134 bytes))
mosquitto-mosquitto1-1  | 1669293603: Sending PUBACK to local.mosquittobridge (m1, rc0)
mosquitto-mosquitto1-1  | 1669293603: Received PUBLISH from local.mosquittobridge (d0, q1, r0, m1, 'general/demo/shadow/update/documents', ... (815 bytes))
mosquitto-mosquitto1-1  | 1669293603: Sending PUBACK to local.mosquittobridge (m1, rc0)
```

#### Miscellaneous
Deployment method: Docker
Version: 2.0.15

**Comment by NorbertHeusser** [comment]
Just one question about it (as it's not visible in your log):
What is the QOS-Level of the subscribtion ?

The subscription needs to have a QOS >= 1 to forward the messages with qos=1.

**Comment by ralight** [comment]
Closing this because it looks like the question is answered, if not please reopen and provide more information.
