### ISSUE TITLE
I usually get permission denied when I use mosquitto_passwd -b command, is there any problem with my docker-compose ym or configl?

### ISSUE THREAD

**Issue by chenyunhsin** [eclipse/mosquitto#2700]
Hi,picture 1 is my docker-compose yml, and picture 2 is my mosquitto config.
Sometime I occur permission denied when I use command `mosquitto_passwd -b password {username} {password}` to generate username and password to password file, but sometimes not.
Is there any problem with my docker-compose yml or config?
Picture 3 is my files' structure, I'm new to mosquitto, if anyone can help, I'll be very thankful :)
picture 4 is  the error when I enter the command.
<img width="479" alt="截圖 2022-12-05 下午4 52 01" src="https://user-images.githubusercontent.com/58776036/205594454-1d0de455-13e5-46d1-991d-92a3b9e13b72.png">
<img width="514" alt="截圖 2022-12-05 下午4 54 22" src="https://user-images.githubusercontent.com/58776036/205594967-d43a9217-c3f4-4b7f-8ba1-c6f1af1ebcc8.png">
<img width="278" alt="截圖 2022-12-05 下午4 55 23" src="https://user-images.githubusercontent.com/58776036/205595179-987f98a1-dd9f-4d17-a181-c62343e39b45.png">
<img width="918" alt="截圖 2022-12-05 下午5 09 13" src="https://user-images.githubusercontent.com/58776036/205598285-e29a12a4-0c61-40d4-ae5f-33b91474ef78.png">

**Comment by NorbertHeusser** [comment]
Hi,

I don't think there is something wrong with your docker-compose.yml.

It's just a result of the way mosquitto is handlings it's config folder:
By default a process inside the docker container is executed by the root user. So inside the docker container the userid id 0. This will be mapped by the container daemon to a different userid of the host system. But if mosquitto is executed with userid=0 it will always do a privilge drop after reading the config file and switch it's process context to the userid =1883. 
This holds for the mosquitto being executed inside the docker container as well.
To avoid any problems with file permissions from the process inside the docker container the startup script specified as the entry point of the docker container will change ownership of the mosquitto config folder (and recursively to all sub folders and files) to the mosquitto userid=1883.

So after the container is started the config folder and your password file will by owned by userid=1883. The easiest way to avoid any file premission problems would be to execute the mosquitto_passwd as root using a sudo command.
A different solution would be to create a group mosquitto with groudid=1883 on your host system and add your account to the group mosquitto. This way it would be sufficient to give the mosquitto group write permission to the password file.

**Comment by chenyunhsin** [comment]
@NorbertHeusser  thanks a lot :D
