### ISSUE TITLE
mosquitto.conf man page has two entries for use_identity_as_username

### ISSUE THREAD

**Issue by abh** [eclipse/mosquitto#2716]
In the configuration man page the `use_identity_as_username` option is mentioned twice (with slightly different descriptions). I think this one is the duplicate / incorrection entry:

https://github.com/eclipse/mosquitto/blob/a8448a9c7b14bdaee6ec80419d43fd6544e789b6/man/mosquitto.conf.5.xml#L1553

**Comment by ralight** [comment]
Thank you, you are quite right, however this is intentional. One of them describes the case for x509 certificates, the other for TLS-PSK.

**Comment by abh** [comment]
@ralight ah, indeed. I totally missed that when searching on the page for the option to read the documentation for it.

If the formatter allows, having the headers stand out a little more would improve the readability! The header that I pointed an arrow to here blends in pretty good.

<img width="742" alt="Screenshot 2023-04-01 at 17 16 28" src="https://user-images.githubusercontent.com/16861/229323832-e324ccf4-a12f-4714-a0d5-0e34e08f9277.png">
