### ISSUE TITLE
1.4.10 compiling libwebsockets error

### ISSUE THREAD

**Issue by johngag** [eclipse/mosquitto#272]
When compiling 1.4.10 there is a warning and error when compiling with websockets   

    websockets.c: In function ‘callback_mqtt’:
    websockets.c:185:5: warning: implicit declaration of function ‘libwebsocket_get_protocol’ [-Wimplicit-function-declaration]
         p = libwebsocket_get_protocol(wsi);
         ^
    websockets.c:185:7: warning: assignment makes pointer from integer without a cast [enabled by default]
         p = libwebsocket_get_protocol(wsi);

    websockets.c:185: undefined reference to `libwebsocket_get_protocol`

I believe it should be

    libwebsockets_get_protocol

Also file src/mosquitto_broker.h references incorrectly on line 34:

    #    define libwebsocket_get_protocol(A) lws_get_protocol((A))

**Comment by karlp** [comment]
Fixed already in https://github.com/eclipse/mosquitto/commit/03d4b8c27029da25dd350df3ca86dd7a6f1393fe

**Comment by johngag** [comment]
Cool thanks
