### ISSUE TITLE
RST ACK on connect packet

### ISSUE THREAD

**Issue by HamzaHajeir** [eclipse/mosquitto#2720]
Platform: Windows10 64 bits.

Mosquitto versions: 1.6.9 and 2.0.15

The issue:
My client device running on ESP32 can successfully connect to Mosquitto v1.6.9, but after upgrading to v2.0.15 it can no longer connect.

Here's a Wireshark copy of what was happening - RST-ACK on the TCP connect packet:

![image](https://user-images.githubusercontent.com/32960423/210177057-23f805cb-6334-4b51-a0cd-2963f0eddd9a.png)

Where by falling back to 1.6.9, it connects and the error is no longer present:
![image](https://user-images.githubusercontent.com/32960423/210177124-c7b09e16-002f-4902-963a-0536fe7ed88b.png)

There was no change in the configurations in both version.

What matters to say is that MQTT-Explorer and mqtt-spy connects with no issues.

What could be my issue?

**Comment by xlhrld** [comment]
I have the same behaviour with a Shelly Plus HT (humidity/temperature) sensor and mosquitto-2.0.11 (the version shipped by Debian). As soon as the Shelly initiates the TCP handshake, mosquitto will reject it with RST+ACK. I have explicitly set `allow_anonymous true` and no transport encryption for debugging purposes.

I have also set `log_type debug` but logging only starts with a sucessful CONN+ACK it seems. So for the Shelly, nothing turns up in the mosquitto log at all.

A presence publisher on my mobile works as expected, though, under this setup.

**Comment by HamzaHajeir** [comment]
I've tried the solution you provided, but with no success. @xlhrld

**Comment by HamzaHajeir** [comment]
I think it's the listener configuration was not activated.
