### ISSUE TITLE
Some questions about the use of Mosquitto storage

### ISSUE THREAD

**Issue by Xxm-YX** [eclipse/mosquitto#2733]
I want to ask a few questions

1.Mosquitto's session is stored in memory or on the hard disk

2.Whether the session data will be affected by the max_queued_messages configuration. When the client is disconnected, whether the message received by the broker exceeds the maximum queue length will also discard the message

3.When I set cleanSession = false, persistence = true, the broker sent a restart, whether the session information will be persisted to the hard disk, and whether it can be restored to the state before the restart

**Comment by NorbertHeusser** [comment]
Hi,

trying to answer your questions:
1. The session information for sessions started with cleanSession=false will be hold in memory. If the persistence of the broker is activated using persistence=true the broker will write the state of all sessions to disk periodically. But writing the persistent snapshot does not scale well with the volume of messages being in flight. On the develoment branch an additional persistence storage plugin API together with a SQLite plugin was added, which will instead use incremental inserts into SQLIte to store the state. In both implementations the broker will write the current state to disk on graceful shutdown. The state will be restored from disk with the next start of the broker.
2. If the a client with cleanSession=false is disconnected the broker will queue messages for the client in memory (and store to disk a descibed in 1.). Once the max_queued_messages limit for a client is reached the broker will start dropping new messages for this client.
3. As described in 1. the broker will store the in-memory state to disk, if persistence is enabled for the broker or a persistence plugin in configured in the config.

Hope this answers your questions.

**Comment by ralight** [comment]
Closing thanks to the answer above.

**Comment by sivann** [comment]
@NorbertHeusser do you have more info about the SQLITE storage plugin? We are very interested in this to reduce I/O in case of lots of persisted messages.
