### ISSUE TITLE
Improve configuration option documentation

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto#274]
See http://dev.eclipse.org/mhonarc/lists/mosquitto-dev/msg01266.html

**Comment by Asoul** [comment]
+1
I have no idea how the configuration file is parsing, there are too many same keyword, sometimes search an keyword will go to the different listener, and user may misplaced the config

Maybe some YAML file or more structural file is better

**Comment by ralight** [comment]
You're proposing a different issue here. This issue is around documentation, not around changing the file format which is something that will now have a huge impact.

**Comment by M-ax-G** [comment]
Agree with the initial message (referenced in the first post)... I thought I could have a listener on 1883 for the local network (all default config, basically nothing), and another listening on 8883 accessible from the Internet requiring authentication... and also discovered that allow_anonymous is global...

**Comment by ralight** [comment]
All listener options are now labelled as global or per-listener, and will be in 1.6.5.
