### ISSUE TITLE
websockets_origin

### ISSUE THREAD

**Issue by axos88** [eclipse/mosquitto#2747]
On the develop branch, the config file states:

```
# Enforce origin checking for websockets connections. This should be set to the
# string of the host that you wish to allow connections from, as set as the
# Origin header in the http request.
# For example: https://example.com:8080
# If left unset will allow connections from any origin.
# May be set multiple times.
#websockets_origin
```

However if websockets_origin is not set, but the `Origin` header is supplied, the connections is refused.

Repro:

1. Create a mosquitto server using:

```
listener 1883 127.0.0.1

listener 8883 0.0.0.0
certfile /mosquitto/cert.pem
keyfile /mosquitto/key.pem
allow_anonymous false

# Define a listener for encrypted MQTT over WebSockets
listener 8083
protocol websockets
certfile /mosquitto/cert.pem
keyfile /mosquitto/key.pem

#websockets_origin http://www.hivemq.com
```

2. Navigate to the http://www.hivemq.com/demos/websocket-client/
3. Attempt to connect

Expected: To be connected
Actual: Connection refused, the log on the broker side says: Client <unknown> disconnected, non-matching http origin.

More info:

The bug probably resides in https://github.com/eclipse/mosquitto/blob/8c98a6ded49dc3aff4c65ec8f52b93e1391f99e2/src/http_serv.c#L217,L228, which requires a match if the Origin header is supplied. Also not sure how the presence of the header is enforced if there is an actual list of origins set as required.

```

**Comment by ralight** [comment]
This was fixed in the develop branch already, thank you for the report!
