### ISSUE TITLE
Is Mosquitto still maintained?

### ISSUE THREAD

**Issue by Bacto** [eclipse/mosquitto#2748]
Hi,

I don't want to be rude so please don't take this message the wrong way :)

I see that there is +500 issues opened and no commit since August 2022 on Mosquitto repository.
Is this project still maintained? Is Eclipse Foundation nor Cedalo still funding it?

**Comment by NorbertHeusser** [comment]
Yes, Mosquitto is still very actively maintained. And there are a lot of commits, but the Mosquitto branch strategy may be not obvious by the first glimpse. The main development is happening on the development branch. Additionally fixes for the stable release are commit to the fixes branch. The master branch will only be updated, if a new major release is published. 
As there have been massiv extensions to the plugin API there has not been a new major release for a long time now.

**Comment by cicorias** [comment]
Just looking for any roadmap or even a "scientific wild ass guess" :) of when the develop branch or a 2.1 release might occur?  Develop is stable -- and the plugin work is amazing -- just some other leadership folks are wary of using a develop branch...
