### ISSUE TITLE
Logging to stdout not flushing when log_dest stdout added to config file

### ISSUE THREAD

**Issue by rharder** [eclipse/mosquitto#2749]
Problem: When log_dest stdout is specified in the mosquitto.conf file, the stdout logging (via Docker) does not flush to the console.  Not until I shutdown mosquitto do all the log messages suddenly dump to the screen.

If I don't specify any logging in the config file, then it flushes to stdout just fine.  It is when I specify stdout that it no longer works.  Actually I get only one log entry, the first one: "1675958250: mosquitto version 2.0.15 starting".  If I also add a log file to the config file, the stdout output also does not work.

I am using moquitto in docker on Windows with WSL2.

-Rob

**Comment by yusefmaali** [comment]
stdout seems to be buffered.
Give a check here: https://github.com/eclipse/mosquitto/issues/2354
