### ISSUE TITLE
Mosquitto SSL Setup for DNS mapping with Wildcard Certificate

### ISSUE THREAD

**Issue by usharaniyerra** [eclipse/mosquitto#2750]
Hi Team,

We have set up mosquitto recently for our servers with 1883 port. Our device connections are working fine from outside also.

We have installed this setup in windows and using it as a windows service.

But we still want to setup our mosquitto broker with SSL (with port 8883). We have DNS for our mosquitto server with wildcard certificate from our CA. 

Could someone please provide the correct setup (steps) of SSL for our mosquitto like how we can configure the certs in mosquitto.conf file, location to give these cert paths.. etc.

I have gone through few documents, but nothing worked for us.

**Comment by Daedaluz** [comment]
Do you think you could provide config and logs for better troubleshooting?

**Comment by usharaniyerra** [comment]
Hi @Daedaluz ,

Here i am providing the config file we are currently using. But not much difference with the normal conf file. We have just added 'listener' and 'allow_anonymous' only for our conf.

Our mqtt broker is now open with 1883 port only. 

I would like to know the clarification on below points:

- Can wildcard certificate work for MQTT DNS setup
- If we want to setup our own DNS for MQTT, where we need to add it in conf file (I have tried as "listener 8883 mqtt.example.com" but it dint start from services.exe)
- Where can we give the certificates in conf file
- Which cert we need to provide in conf file.. like crt, pem or pfx
- As of now we have server certificates only, is it required to use client certificates for MQTT clients

Please help me with these queries.

And we don't have logs for our MQTT now.

**Comment by Daedaluz** [comment]
I was more referring to some configuration file you tried but didn't work, as you said that you had gone through some unspecified documents.

* I don't see any reason to why a wildcard certificate wouldn't work
* I'm not aware that you have to specify any hostname in the config. The server certificate should be valid for the hostname you are connecting to. The `listener 1883 <ip>` only specifies a listener on a specific interface with the provided IP. (`listener 1883 127.0.0.1` would create a listener that only accept connections on localhost port 1883)
* There are a number of options for tls settings (eg. `certfile` and `keyfile` should be the most common ones), they are listed under the `Certificate based SSL/TLS support` part in the sample config you provided.
* probably either `crt` or `pem` is good. 
* This depends on your requirements, however it's not required for server TLS

```
# -----------------------------------------------------------------
# Certificate based SSL/TLS support
# -----------------------------------------------------------------
# The following options can be used to enable certificate based SSL/TLS support
# for this listener. Note that the recommended port for MQTT over TLS is 8883,
# but this must be set manually.
#
# See also the mosquitto-tls man page and the "Pre-shared-key based SSL/TLS
# support" section. Only one of certificate or PSK encryption support can be
# enabled for any listener.

# Both of certfile and keyfile must be defined to enable certificate based
# TLS encryption.

# Path to the PEM encoded server certificate.
#certfile

# Path to the PEM encoded keyfile.
#keyfile
```

**Comment by usharaniyerra** [comment]
I did setup the same as you suggested. But when i am testing from command prompt getting the below error.

![image](https://user-images.githubusercontent.com/37344123/218634222-99b06292-7b79-463a-a8ae-0651dabc89e7.png)

My certs are valid. We are using them for other services also.

**Comment by Daedaluz** [comment]
I think this suggests at least that the server is running with TLS enabled now.

This looks like that the CA isn't installed on the system you are connecting from, so your client can't verify the host.
Could also be that mosquitto_sub isn't looking for CAs at the place you installed the CA.
You could try add the `--cafile` flag to `mosquitto_sub`  and point it to the trust-chain for your CA, see if it helps.

**Comment by usharaniyerra** [comment]
Hi @Daedaluz ,

Here only i have the actual doubt. We have server certificate from CA and are in the formats pfx, crt, pem. 

Which one we need to install in client system, we dont have an specific ca certificate for client.

Could you please explain little bit more on this step, which cert need to be installed in client, from which location we need to run mosquitto_sub (usually i am running these commands where mosquitto installed).

**Comment by Daedaluz** [comment]
This is a part that depends heavily on what CA you have and how strictly the client verifies the server certificate, and how you want to maintain your trust.

Your server presents a certificate signed by your CA, and the client attempting to connect needs to verify that certificate is actually signed by the claimed CA and that the server is the intended destination.

For example, if you want to trust [let's-encrypt](https://letsencrypt.org/certificates/), you'll probably want the `ISRG Root X1`, `ISRG Root X2`, `R3`, `R4`, `E1` and `E2` in your clients chain of trust in order to be able to fully verify any host that presents a certificate signed by let's encrypt.

I can't really tell you how they should be installed on your system, since the answer to it varies on how you want it to be.

I'm not very familiar with running mosquitto on windows either, and if you are using a well-known CA, it should probably have worked since there should be many certificates that are pre-installed or bundled.

Point is, you need to make `mosquitto_sub` look where the `ISRG Root X2` chain is (assuming let's encrypt).
So, odds are that you might not need to install any cert at all, just point `mosquitto_sub` in the right direction.

**Comment by usharaniyerra** [comment]
But my query is when we give 'require_certificate' to false, client is not required to provide any certificate for server validation.

In this case, i believe we no need to mention any --cafile from client side.

**Comment by Daedaluz** [comment]
Client isn't supposed to provide a certificate, but it needs the CAs certificate / public key to verify the servers certificate upon connection. 

I believe the --cafile flag should just point to a file where all the CAs are stored.

**Comment by ralight** [comment]
For the config file:

```
listener 8883
certfile <path to full certificate chain in pem format>
keyfile <path to key in pem format>
```

If the certificates for your server are signed by a well known CA, then it is likely that the default CA certificates trusted by openssl/the operating system are sufficient. Running as `mosquitto_sub -h <host> -p 8883 ...` will use the OS provided certificates.

If that does not work, you may need to tell the client which CA certificates to trust: `mosquitto_sub -h <host> -p 8883 --cafile <path to CA cert in pem format> ...`.

Alternatively, it may be the case that you do not have the full chain from the CA to the server cert. It is very common for the full chain to be root CA -> intermediate -> server. Your client should have the root CA only, which means the server certificate needs to include the intermediate and server certificates.

You can also try debugging with the openssl command, this may give you more information about what is wrong. Try `openssl s_client -connect <host>:8883`. The openssl command is available for windows at https://slproweb.com/products/Win32OpenSSL.html

**Comment by Daedaluz** [comment]
Perhaps this can be closed?
