### ISSUE TITLE
Connecting to bridge (Not connecting but no errors)

### ISSUE THREAD

**Issue by bjbance** [eclipse/mosquitto#2753]
I have eclipse-mosquitto running in a docker container and I am trying to bridge it to solar assistant. I've verified that both mosquitto and SA are running by using MQTT Explorer. I can connect to both and see topics listed. But the topics in SA are not appearing in mosquitto. I checked the logs and it just keeps repeating the "Connecting bridge" message without any response. My initial search results for the matter always seemed to have a response why it's not connecting like protocol or authentication error. But this one doesn't.

#mosquitto.log
1676378582: New client connected from 10.23.2.12:57653 as frigate (p2, c1, k60, u'user1').
1676378649: Connecting bridge SolarAssistant (192.168.2.200:1883)
1676378731: Connecting bridge SolarAssistant (192.168.2.200:1883)
1676378801: Connecting bridge SolarAssistant (192.168.2.200:1883)
1676378875: Connecting bridge SolarAssistant (192.168.2.200:1883)
1676378966: Connecting bridge SolarAssistant (192.168.2.200:1883)
1676379057: Connecting bridge SolarAssistant (192.168.2.200:1883)
1676379148: Connecting bridge SolarAssistant (192.168.2.200:1883)
1676379239: Connecting bridge SolarAssistant (192.168.2.200:1883)
1676379326: Connecting bridge SolarAssistant (192.168.2.200:1883)
1676379417: Connecting bridge SolarAssistant (192.168.2.200:1883)
1676379443: Client mqtt-explorer-82f31c3f disconnected.
1676379444: New connection from 192.168.2.25:63020 on port 1883.
1676379444: New client connected from 192.168.2.25:63020 as mqtt-explorer-82f31c3f (p2, c1, k60, u'user1').

#bridge configuration located in mosquitto.conf
connection SolarAssistant
remote_username user1
remote_password pass
address 192.168.2.200
topic # out 0
topic # in 0
start_type automatic
remote_clientid mosquitto0

**Comment by Fayyaadh** [comment]
Did you resolve this?

**Comment by bjbance** [comment]
> 

Not really a fix but found a workaround. I guess the issue was with solar assistant. I don't know if it's because Mosquitto was in another ip range or because it was in a docker container. I just deployed Mosquitto in a spare Pi and was able to get it to connect.
