### ISSUE TITLE
Socket error on too fast calls OSX

### ISSUE THREAD

**Issue by PetrBarborka** [eclipse/mosquitto#277]
Hi, I have this sample program using libmosquitto:

```
#include "mosquitto.h"

#include <iostream>
#include <unistd.h>
#include <mosquitto_internal.h>

#define HOST "127.0.0.1"
#define PORT 1883

int main(){

    mosquitto_lib_init();

    const char * message_buf = "test message";

    const char * id = "test_client"; // informative identifier, can be set to anything
    bool clean_session = 1; // delete any previous data
    void * obj = NULL; // this can be set to any data we want the client instance
    // to carry

    struct mosquitto * client_instance = mosquitto_new(id, clean_session, obj);

    mosquitto_connect_async( client_instance, HOST, PORT, 60);
    mosquitto_loop_start( client_instance );
//    usleep(1000);
    mosquitto_subscribe( client_instance, NULL, "test_topic", 2);
    mosquitto_publish(client_instance, NULL,
                      "test_topic", strlen(message_buf),
                      message_buf, 2, false);
    mosquitto_unsubscribe( client_instance, NULL, "test_topic");
//    usleep(1000);
    mosquitto_disconnect( client_instance );
    int force_disconnection = 0;
    mosquitto_loop_stop( client_instance, force_disconnection);
    mosquitto_destroy( client_instance );
    mosquitto_lib_cleanup();

    return 0;
}
```

As you can see, I am using libmosquitto for the client. The broker is mosquitto. I am trying to perform some basic test operations on broker ran on OSX (localhost). This code gives me inconsistent socket errors usually after connect, sometimes after subscribe:

```
./src/mosquitto -v
1474974626: mosquitto version 1.4.10 (build date 2016-09-27 12:16:20+0200) starting
1474974626: Using default config.
1474974626: Opening ipv4 listen socket on port 1883.
1474974626: Opening ipv6 listen socket on port 1883.
1474974636: New connection from 127.0.0.1 on port 1883.
1474974636: New client connected from 127.0.0.1 as test_client (c1, k60).
1474974636: Sending CONNACK to test_client (0, 0)
1474974636: Socket error on client test_client, disconnecting.
```

The error happens every time. If i uncomment the usleep() functions, everything works fine. If I set the sleep time for sth like 300us, it happens in cca 30% cases.

Does anyone have any idea what might be wrong? Is it a mosquitto bug, or am I doing something wrong? Did I not get something about the asynchronous interface? Thanks in advance.

P.S.: the documentation also states that you can put mosquitto_connect_async() after mosquitto_loop_start(). If I do that, the program hangs every time.

**Comment by karlp** [comment]
If you use connect async, put the subscribe calls into an ```on_connect``` callback so you're guaranteed to send them when connected and not before.  No comments (from me) on the doc ordering of loop_start/connect_async

**Comment by PetrBarborka** [comment]
Thank you very much, sir. This is definitely one part of my problem.

**Comment by ralight** [comment]
The approach @karlp suggests is the best approach.

If you think about what you're doing, essentially you are sending the following commands without waiting for a response from the broker:

CONNECT
SUBSCRIBE
PUBLISH
UNSUBSCRIBE
DISCONNECT

As soon as the client sees that the DISCONNECT packet has been sent to the kernel it closes the socket as the spec requires.

This more or less matches what you're seeing. The longer the sleep you put in the greater the chance the messages will make it to the broker, hence it working 30% of the time in your example.

I'll need to check the documentation and the behaviour about loop_start/connect_async.

**Comment by PetrBarborka** [comment]
Thanks for your help - it was a misunderstanding of a concept on my part.
