### ISSUE TITLE
Mosquitto.h/lib cannot find/load Mosquitto.dll

### ISSUE THREAD

**Issue by sudipto1995** [eclipse/mosquitto#2771]
I am trying to use mosquitto.h that comes with binary installation in devel for windows.

I am however having issues when I am trying to run simple test project that relies on it. Header and Libraries linked through VS2019, it compiles and builds fine, but when ran throws "A dependant dll was not found."

I followed the same thread - https://github.com/eclipse/mosquitto/issues/855, but the solution was not mentioned.

Can you please let me know what am I doing wrong?

**Comment by ralight** [comment]
Do you have the mosquitto.dll in the same path as your executable when you try to run it?

**Comment by sudipto1995** [comment]
Yes, I was having them in the same path.

FYI- I was able to resolve the issue with vcpkg.
