### ISSUE TITLE
Feature: Variables in ACL topic of the Dynamic Security Plugin

### ISSUE THREAD

**Issue by lodemo** [eclipse/mosquitto#2784]
Hi,

when handling a lot of clients through the Dynamic Security Plugin, where each client is supposed to only access client-specific topics (ie. client/*clientId*/#), managing this through static ACL rules leads to a lot of roles (one per client).

My suggestion would be, to be able to use dynamic variables in the topic definition of an ACL entry. If it would be possible to use a variable that represents the current client id of the client taking this action, one could solve the above use case through a single role.

Each client could be assigned the same role, while being granted access to only their client id specific topic. In my use case the client id is used, but this could be applied to different attributes too.

If this is already possible i couldnt found any documentation about it in the Dynamic Security Plugin.

Example role using the proposed feature:
```
{
			"rolename":	"clientIdBasedAccess",
			"textdescription":	"Granting a client access to its clientId specific topic.",
			"acls":	[{
					"acltype":	"publishClientSend",
					"topic":	"client/{clientId}/#",
					"priority":	0,
					"allow":	true
				}, {
					"acltype":	"publishClientReceive",
					"topic":	"client/{clientId}/#",
					"priority":	0,
					"allow":	true
				}, {
					"acltype":	"subscribePattern",
					"topic":	"client/{clientId}/#",
					"priority":	0,
					"allow":	true
				}, {
					"acltype":	"unsubscribePattern",
					"topic":	"client/{clientId}/#",
					"priority":	0,
					"allow":	true
				}]
		}
```

**Comment by ralight** [comment]
Thanks for the suggestion - happily, I already agree. The upcoming 2.1 release will allow you to specify `%u` for username and `%c` for client id.

**Comment by lodemo** [comment]
Great to hear! 

Is there a release date for 2.1?

**Comment by ralight** [comment]
Not yet, but it is way overdue.
