### ISSUE TITLE
Libmosquitto client changing outgoing message id

### ISSUE THREAD

**Issue by PetrBarborka** [eclipse/mosquitto#279]
Hi, I am using this code for testing:

```
        // derived from mosquittopp:
        Mqtt_client s = Mqtt_client("test_client_sender");
        ...
        int message_id = 111;
        s.publish(&message_id, topic, payloadlen, payload, 2, 0);
        ... 
        // message mes gets received by another client
        ASSERT_EQ(mes->mid, 111);
```

which fails, because libmosquitto changes the outgoing message id in mosquitto.c:571 like this:

```
	local_mid = _mosquitto_mid_generate(mosq);
	if(mid){
		*mid = local_mid;
	}
```

this changes my int * to 1.

I am wondering - is there a reason for this behavior? I am not terribly reliant on the message id parameter, but why even bother giving people chance to set it when you change it afterwards? Shouldn't it maybe be `if(!mid){ ...` ? 

Anyway, thanks for a great library.

**Comment by karlp** [comment]
You con't control the mid yourself.  The mids are assigned within the protocol, the pointer is for you to _get_ the mid back from the publish call, not for you to provide your own mid.

**Comment by PetrBarborka** [comment]
Oh silly me. Thanks for the explanation.

**Comment by karlp** [comment]
You're not the first, it's quite likely something that could be clarified in the documentation? https://mosquitto.org/api/files/mosquitto-h.html#mosquitto_publish does already say it
