### ISSUE TITLE
Client library loop high CPU load during SSL connect in 2.0.15

### ISSUE THREAD

**Issue by jsopenrb** [eclipse/mosquitto#2794]
The loop is constantly calling `SSL_write` until a connection is established. High CPU load can only be observed if the broker is slow to respond. Usually the initial connection is very fast so the extra load is negligible.
It happens after this change: https://github.com/eclipse/mosquitto/commit/e979a46c048a8c60c53614548c4a98dfd4992cf4

**Comment by ralight** [comment]
Thank you, that's a good spot.

**Comment by jsopenrb** [comment]
Have you seen [my comment on the commit](https://github.com/eclipse/mosquitto/commit/269756a171a63a2ff96f1973df11b6563020201a#commitcomment-110964471)? `mosquitto_want_write` does not have a check for `SSL_is_init_finished` while `mosquitto_loop` does.
