### ISSUE TITLE
Two fast writing clients will lead to disconnect/connect loop

### ISSUE THREAD

**Issue by illuusio** [eclipse/mosquitto#282]
I've tested openSUSE 1.4.10 and noticed that if you have two clients which other is much faster than another (it starts to happen from 40 msg per/second [length doesn't seems to be issue]) it starts to disconnect clients and reconnect with both client running in loop forever.
It happens because on function '_mosquitto_net_read' function recv() returns 0 and it thinks socket has been closed but I think that server just don't respond. I have tested this on local machine and server doesn't say it has disconnected client.
This can be just configuration issue but haven't find any config key to solve this.

update:
It seems client library works same with RabbitMQ MQTT broker and it actually doesn't matter how fast you send. It's only two sending client once. If you only have one you can send as fast as you want

**Comment by ralight** [comment]
I'm not quite clear on exactly what you are doing, could you provide some example code that demonstrates the problem please?

**Comment by ralight** [comment]
I mean, just to be clear are these separate clients or multiple client instances in a single program?

**Comment by illuusio** [comment]
These are two separated clients connecting to one server. I'll try to write simple code but what I use is mainly taken from example.

**Comment by karlp** [comment]
re systemd: https://github.com/eclipse/mosquitto/tree/develop/service/systemd

**Comment by illuusio** [comment]
Nice! I have to add this to openSUSE rpm.. thanks for pointing out!

**Comment by ralight** [comment]
Good to hear you found the problem.
