### ISSUE TITLE
Socket error when PUBLISH and PINGREQ are sent too quickly

### ISSUE THREAD

**Issue by JF002** [eclipse/mosquitto#283]
Hi,

I'm running an MQTT client on an embedded STM32F4 board using the Embedded MQTT C++ Client Libraries from Paho.

Previously, the client was conneting to the Mosquitto Broker 1.3.4, and it was running as expected.
Now, I updated the broker to version 1.4.10, and I frequently get the error “Socket error on client <client>, disconnecting”.

Here is what the client is doing : 
`while (1) {
    messageToSend.qos = ::MQTT::QOS0;
    messageToSend.retained = false;
    messageToSend.dup = false;
    messageToSend.payload = (void*)messageFromApp.message.c_str();
    messageToSend.payloadlen = messageFromApp.message.size();
    mqttClient.publish(messageFromApp.topic.c_str(), messageToSend);

```
// Fix the error
vTaskDelay(100);

mqttClient.yield(10);

 vTaskDelay(1000);
```

  }`

So, every one second, a message is published, and then, the function yield() is called. This function, among other things, sends the PINGREQ message.
If I remove the delay of 100ms between the PUBLISH and the PINGREQ messages, I'll get the socket error quickly.

I don't know if it is an issue in the client lib, the broker or in my code...

Thanks

**Comment by PierreF** [comment]
Do you have any error on the broker log ? If possible enable verbose log on broker (command line option -v or log_type all in configuration file).
The log may help to determine if the error come from the client or the broker.

**Comment by ralight** [comment]
I haven't been able to reproduce this using a desktop client, and this hasn't seen any activity for a while, so I'm going to close it. If you still have a problem, please reopen and provide some more details.
