### ISSUE TITLE
Seeing SSL related errors with sockets being dropped

### ISSUE THREAD

**Issue by murugesan70** [eclipse/mosquitto#285]
Hi,
we are using Mosquitto 1.4.8 on Ubuntu 16.04
we see the OpenSSL errors of undefined_const_function which makes the client to keep dropping connections.

1476122158: OpenSSL Error: error:140F3042:SSL routines:ssl_undefined_const_function:called a function you should not call

Is there a fix that is currently being worked on?

Thanks,
Murugesan

**Comment by pstoll** [comment]
Dupe of https://github.com/eclipse/mosquitto/issues/383?

**Comment by PierreF** [comment]
Closing this issue as it looks like a dup of #383. If you think it's not a duplicate, feel free to reopen this issue.
