### ISSUE TITLE
Can not build on ARM64 Darwin

### ISSUE THREAD

**Issue by themightyoarfish** [eclipse/mosquitto#2858]
[This issue,](https://github.com/eclipse/mosquitto/issues/2514) which was deemed resolved occurs on current master.

```
[ 85%] Linking C shared module mosquitto_dynamic_security.so
Undefined symbols for architecture arm64:
  "_mosquitto_broker_publish", referenced from:
      _send_response in plugin.c.o
  "_mosquitto_callback_register", referenced from:
      _mosquitto_plugin_init in plugin.c.o
  "_mosquitto_callback_unregister", referenced from:
      _mosquitto_plugin_cleanup in plugin.c.o
  "_mosquitto_calloc", referenced from:
      _dynsec_auth__base64_decode in auth.c.o
      _dynsec_clients__config_load in clients.c.o
      _dynsec_clients__process_create in clients.c.o
      _dynsec_groups__config_load in groups.c.o
      _dynsec_groups__process_create in groups.c.o
      _dynsec__config_load in plugin.c.o
      _dynsec_roles__config_load in roles.c.o
      ...
```

cmake invocation is ` cmake ..  -DOPENSSL_ROOT_DIR=/opt/homebrew/Cellar/openssl@1.1/1.1.1u/`

- OS version: 12.6.5
- arch: apple silicon
- compiler: Apple clang version 14.0.0

**Comment by danh1979** [comment]
I also discovered this problem when attempting to update mosquitto in macports: https://trac.macports.org/ticket/67874

At first, I was able to add `-DCMAKE_MODULE_LINKER_FLAGS="-undefined dynamic_lookup"` to my cmake invocation to solve the problem, but perhaps the fix should be here in mosquitto's CMakeLists.txt as follows?
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b8913c2d..145f6255 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -20,7 +20,7 @@ if (WIN32)
 endif (WIN32)
 
 if(APPLE)
-       set(CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS "${CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS} -undefined dynamic_lookup")
+       set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} -undefined dynamic_lookup")
 endif(APPLE)
 
 include(GNUInstallDirs)
```

**Comment by BB-301** [comment]
> I also discovered this problem when attempting to update mosquitto in macports: https://trac.macports.org/ticket/67874
> 
> At first, I was able to add `-DCMAKE_MODULE_LINKER_FLAGS="-undefined dynamic_lookup"` to my cmake invocation to solve the problem, but perhaps the fix should be here in mosquitto's CMakeLists.txt as follows?
> 
> ```diff
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index b8913c2d..145f6255 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -20,7 +20,7 @@ if (WIN32)
>  endif (WIN32)
>  
>  if(APPLE)
> -       set(CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS "${CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS} -undefined dynamic_lookup")
> +       set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} -undefined dynamic_lookup")
>  endif(APPLE)
>  
>  include(GNUInstallDirs)
> ```

@danh1979 

The proposed solution worked for me. Thank you!

As I'm mentioning in https://github.com/eclipse/mosquitto/issues/2744#issuecomment-1777974576, I was having a similar problem while trying to build `master tag v2.0.18` on `macOS Ventura 13.2 (Intel)`.

**Comment by ckrey** [comment]
This issue can be closed as the fix has been merged
