### ISSUE TITLE
mosquitto_passwd -U fails in docker after 2.0.16

### ISSUE THREAD

**Issue by nikarh** [eclipse/mosquitto#2873]
Hi,

after this change https://github.com/eclipse/mosquitto/commit/44b94875b597458e69b06878cc468a7c3c94f41b it seems that running `mosquitto_passwd -U users.conf` in a [docker container](https://hub.docker.com/_/eclipse-mosquitto) always fails with `Error creating backup password file`

## Steps to reproduce

This fails on 2.0.16
```
docker run --rm --entrypoint "" eclipse-mosquitto:2.0.16 ash -c "\
     echo a:a > /mosquitto/users.conf; \
     chmod 660 /mosquitto/users.conf;  \
     mosquitto_passwd -U /mosquitto/users.conf"
```

While older versions don't

```
docker run --rm --entrypoint "" eclipse-mosquitto:2.0.15 ash -c "\
     echo a:a > /mosquitto/users.conf; \
     chmod 660 /mosquitto/users.conf;  \
     mosquitto_passwd -U /mosquitto/users.conf"
```

**Comment by szinn** [comment]
I had this issue as well

**Comment by buroa** [comment]
Seeing this too.

**Comment by googol** [comment]
Experiencing the same issue, running 2.0.16

```
/mosquitto/config $ mosquitto_passwd /mosquitto/config/password.conf new-user
Error creating backup password file "/mosquitto/config/password.conf.bac", not continuing.
```

**Comment by b-r-y** [comment]
i am seeing the same on alpine: mosquitto-2.0.16-r0

Thanks to whoever will fix it :)

**Comment by onedr0p** [comment]
I noticed the same thing, also...

> 600+ issues
> 50+ PRs

What is going on with this repository, is there anyone maintaining it?

**Comment by p2baron** [comment]
This taught me a lesson in using the -latest tag in docker. 
Glad it is being fixed.
