### ISSUE TITLE
All messages dropped when max_queued_messages 0

### ISSUE THREAD

**Issue by Daedaluz** [eclipse/mosquitto#2879]
mosquitto.conf:

```
max_queued_messages 0
allow_anonymous true
listener 1883
```
start mosquitto:
`$ docker run --rm -ti -p 1883:1883 -v $(PWD)/mosquitto.conf:/mosquitto/config/mosquitto.conf eclipse-mosquitto:2.0.16`

subscribe:
`$ mosquitto_sub -v -t "#"`

publish:
`$ mosquitto_pub -t "hello" -m "world"`

---

Mosquitto log:
```
1692604552: mosquitto version 2.0.16 starting
1692604552: Config loaded from /mosquitto/config/mosquitto.conf.
1692604552: Opening ipv4 listen socket on port 1883.
1692604552: Opening ipv6 listen socket on port 1883.
1692604552: mosquitto version 2.0.16 running
1692604552: New connection from 172.17.0.1:33904 on port 1883.
1692604552: New client connected from 172.17.0.1:33904 as auto-BBB3F4DC-A2B8-A350-CAE6-B3B99F9DAC9B (p2, c1, k60).
1692604552: Outgoing messages are being dropped for client auto-BBB3F4DC-A2B8-A350-CAE6-B3B99F9DAC9B.
1692604553: New connection from 172.17.0.1:33906 on port 1883.
1692604553: New client connected from 172.17.0.1:33906 as auto-7B07F536-BDFB-4E81-F8FB-6D973493172F (p2, c1, k60).
1692604553: Outgoing messages are being dropped for client auto-7B07F536-BDFB-4E81-F8FB-6D973493172F.
```

nothing on the subscriber and the pub client hangs and eventually terminates with `Error: Unknown error.`

**Comment by tobiasfrick** [comment]
Ran into the same issue, I think the problem was introduced with 6113eac95a9df634fbc858be542c4a0456bfe7b9 at this line:

https://github.com/eclipse/mosquitto/blob/6113eac95a9df634fbc858be542c4a0456bfe7b9/lib/packet_mosq.c#L157
