### ISSUE TITLE
mosquitto_rr -R does not ignore stale messages

### ISSUE THREAD

**Issue by jwinder-ca** [eclipse/mosquitto#2893]
mosquitto_rr -R is documented that it will not print stale messages (those with retain set), but it does print the stale message and returns without waiting for the response topic (a non-retained occurrence of the topic).

I tested on a Fedora Linux with Mosquitto version 2.0.17 and a different Linux device with Mosquitto version 2.1.0

[user@fedora ~]$ mosquitto_pub -t 'resp' -n -r
[user@fedora ~]$ mosquitto_pub -t 'resp' -m '0' -r
[user@fedora ~]$ mosquitto_rr -R -t 'cmd' -e 'resp' -m '1' -d
Client null sending CONNECT
Client auto-B1257093-19F5-5800-CCA1-B115F3ED29DC received CONNACK (0)
Client auto-B1257093-19F5-5800-CCA1-B115F3ED29DC sending SUBSCRIBE (Mid: 1, Topic: resp, QoS: 0, Options: 0x00)
Client auto-B1257093-19F5-5800-CCA1-B115F3ED29DC received SUBACK
Client auto-B1257093-19F5-5800-CCA1-B115F3ED29DC sending PUBLISH (d0, q0, r0, m2, 'cmd', ... (1 bytes))
Client auto-B1257093-19F5-5800-CCA1-B115F3ED29DC received PUBLISH (d0, q0, r1, m0, 'resp', ... (1 bytes))
0
[user@fedora ~]$

**Comment by ralight** [comment]
You're quite right. I looked in the code and saw a big FIXME - that's now done and will be part of 2.0.18.
