### ISSUE TITLE
Using Mqtt as a Key Value database?[Question]

### ISSUE THREAD

**Issue by sreeisalso** [eclipse/mosquitto#290]
Hi,

Is it possible to use Mqtt as a Key value database for the sensors settings (these settings will be updated occasionally)? this will reduce the need for using multiple libraries (client side database and parsing).

Are there any problems when we have many topics which are not updated as frequent as other sensor data readings?

What is the effect of too many topics in mqtt sever?

Thanks.

**Comment by ralight** [comment]
Yes you could do this.

If you have lots of topics, the broker will use more resources. If you have too many, it will perform poorly.

I'm closing this issue because I don't think it is a bug with mosquitto. If you disagree, please reopen with more information.

**Comment by sreeisalso** [comment]
Hi @ralight,
I have some queries.

1.  How many is "**too many**"?
2.  "poor performance due to many topics" problem can be avoided if use **RocksDB** ?
