### ISSUE TITLE
Dynamic security changes not persisted to disk across restarts

### ISSUE THREAD

**Issue by yobyot** [eclipse/mosquitto#2938]
No matter where I place the Dynamic Security JSON file nor how I change its ownership and permissions, Mosquitto 2.0.18 will _not_ persist any settings across restarts. IOW, it simply does not write the changes to the JSON file.

Please see the annotated screenshots below which document this sequence:

1. Issue `mosquitto_ctrl dynsec listClients` (I'm using an options file for authentication). Confirm admin client exists.
2. Issue `...createClient...` to create client "iotClient"
3. Confirm new client exists via `mosquitto_ctrl`.
4. Restart Mosquitto.
5. Issue ...listClients`. Client added above is not listed.

You can see in the VS code terminal that the user specified in `mosquitto.conf` owns the JSON file. I've also included a screenshot of the JSON file _before_ step 4 above. 

At this point, the client exists but has not been persisted to the JSON file.

I've also included a screenshot of the log file, which appears to show that the `$CONTROL/dynamic-security/v1` topic is receving the requests from `mostquitto_ctrl`.

![1](https://github.com/eclipse/mosquitto/assets/14332263/bf0befd5-b991-4868-b0d8-69f3626efdd4)

![x](https://github.com/eclipse/mosquitto/assets/14332263/c94219cf-1430-4dfb-9131-994139346e61)

![3](https://github.com/eclipse/mosquitto/assets/14332263/a864919c-ece3-479e-bfe0-bf43d8b39064)

**Comment by mrchipset** [comment]
Hi, @yobyot. I have tried the 2.0.18 mosquitto compiled from source code. I haven't caught your problem.
It seems this problem is caused by the write permission on your `dynamic-security.json`. You can try to set the mosquitto runtime user to root evaluate this problem. Another possible way is to use `chown mosquitto:mosquitto /etc/mosquitto/dynamic-security.json` .
Hope that helps.

**Comment by yobyot** [comment]
Thanks, @mrchipset.
