### ISSUE TITLE
Able to subscribe to # wildcard topic, despite ACL

### ISSUE THREAD

**Issue by simonmorley** [eclipse/mosquitto#294]
I was playing with Websockets today and, by chance, decided to subscribe to the '#' topic.

Before long my application was flooded with messages. Initially I thought it was the mysql-auth-plugin causing issues. I removed this and created a v. basic acl file:

```
user b3ce59cef56a0904
topic readwrite #

user IWWfjVCyAm
topic read my/super/topic
```

I've confirmed this is working nicely with the valid topics. 

However, if I subscribe any client to the '#' topic, I am able to bypass these ACLS. I'm lucky enough to get all messages sent - I've tested on a number of clients, and most 1.4.x versions of Mosquitto.

There were a few posts around that suggested this was expected or that it was dropped. However, unless I've done something terribly wrong, it would seem quite a large issue.

**Comment by simonmorley** [comment]
Wait. Subscribing to '#' with a user actually subscribes the client to the topic listed in the acl file.

So, in this case - I get all messages sent to 'my/super/topic'

Is this the intended behaviour? V. confusing.

**Comment by karlp** [comment]
# is "give me everything you can"  Which is clearly going to be only the subset you're allowed to see.  There's now say what mix of what subs may exist in the future that may match.  I'm not sure what's so confusing about it.

**Comment by ralight** [comment]
Another way of looking at this is that the ACL doesn't deny an explicit subscription string, it is allowing/denying subscription patterns.

I'm closing this because I don't think there is a bug in mosquitto, if you disagree please reopen and provide more information.
