### ISSUE TITLE
MQTT 3.1 to 3.1.1

### ISSUE THREAD

**Issue by 3nd0y** [eclipse/mosquitto#295]
Hi Mosquitto

I have installed Mosquitto 1.4 using debian repository. In your blog said that to use MQTT 3.1.1 need 1.4 above and i have it now. But after i tried run mosquitto -h it is said MQTT 3.1, how to update it to be 3.1.1?

Thanks

**Comment by ralight** [comment]
It does support 3.1.1, the usage message just needed updating. I've made that change now, thanks for pointing it out.
