### ISSUE TITLE
I don't konw why use the formula in (mqtt3_db_sys_update)

### ISSUE THREAD

**Issue by EricksonLu** [eclipse/mosquitto#297]
```
uptime = now - start_time
i_mult = 60.0/(double)(now-last_update)

/* 1 minute load */
exponent = exp(-1.0*(now-last_update)/60.0)
/* 5 minute load */
exponent = exp(-1.0*(now-last_update)/300.0);
```

**Comment by EricksonLu** [comment]
in sys_tree.c .I know that's for update mosquitto db.But i don't know why use this formula compute time intervals

**Comment by ralight** [comment]
It's an exponentially damped moving average:

https://en.wikipedia.org/wiki/Moving_average#Application_to_measuring_computer_performance
