### ISSUE TITLE
mosquitto with QOS>0 doesn't deliver all messages

### ISSUE THREAD

**Issue by cordovapolymer** [eclipse/mosquitto#298]
I'm publishing 667 2048bytes messages with QOS 2 or 1 at a high rate. I publish via mqtt, and receive both via mqtt and websocket.
On the client side only 130 of them are received in the best case, When changing to QOS 0 at the publisher all 667 messages are received. Client settings make no difference, If I subscribe with QOS 0 when publishing at QOS 2 or 1 messages are still lost.
I tried to send 256bytes messages, and they were lost as well.
Then I've tried to send 20480bytes messages and as soon as there were only 67 in total, they were delivered with QOS 2 is most cases(not always!), but when switching to QOS 1 half of the messages were lost every time.
I tried It with latest 1.4.10 mosquitto running on my server as well with iot.eclipse.org.

**Comment by karlp** [comment]
I bet you have a publishing script that fires them off and then exits right?
Make sure you're using something like loop_stop, or actually waiting for the on_published of each message to be completed to make sure that you've actually completed the higher qos message acks.

**Comment by cordovapolymer** [comment]
I'm using [mqtt.js](https://github.com/mqttjs/MQTT.js) to send these messages sending them one after another via one connection.
I could store all messages in a queue and send next message only after previous is delivered.. but shouldn't broker itself handle this issue?

**Comment by karlp** [comment]
If you send 100 publish packets at qos >= 1, and then exit, when the broker sends you puback/pubrel sequences, if you're not around to answer the broker will, rightly, discard the messages as incomplete flows.  https://mosquitto.org/api/files/mosquitto-h.html#mosquitto_loop_stop is helpful if you're using libmosquitto.  You'll have to chase it up with mqtt.js on how to correctly wait for network processing to finish.

**Comment by cordovapolymer** [comment]
I don't exit, mqtt.js handles message delivery automatically. 
I've found the solution `max_queued_messages` set to 0 solves the issue.
