### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [eclipse/mosquitto#3]
I would like to point out that identifiers like "[`_MOSQUITTO_H_`](https://github.com/eclipse/mosquitto/blob/5cca6b4239f78b4858b003f99054d23a539ead6b/lib/mosquitto.h#L17)" and "[`_TLS_MOSQ_H_`](https://github.com/eclipse/mosquitto/blob/dc5abcac95f19810de765b377537164249f4c4a6/lib/tls_mosq.h#L17)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by ralight** [comment]
Closed in the develop branch.
