### ISSUE TITLE
Mosquitto on openwrt, installed on arduino YUN. Error message

### ISSUE THREAD

**Issue by pheelan** [eclipse/mosquitto#300]
Hi Folks,
I have set up mosquitto on an arduino YUN; downloaded the openwrt version. I am trying to use an ESP8266 device to connect to this. The ESP device will connect normally to another external broker, but on the mosquitto version for openwrt I get this error message.

1477929323: New connection from 192.168.29.39.
1477929323: Invalid protocol "MQTT" in CONNECT from 192.168.29.39.
1477929323: Socket read error on client (null), disconnecting.

Does anyone know whay this is happening?
Regards
Phil

**Comment by karlp** [comment]
which version of mosquitto is your yun running?  that sort of looks like you have a version of mosquitto prior to around 1.3, when mqtt 3.1.1. support landed.  the "MQTT" protocol is from mqtt3.1.1, not the older mqtt 3.1.

**Comment by pheelan** [comment]
Hi Karlp.
I am using  mosquitto version 0.15 (build date 2016-06-02), this is the build for openwrt

Regards
Phil

**Comment by karlp** [comment]
speak to whoever is building your "openwrt" and tell them to at least come up to something like the present.  mosquitto 0.15 came out in 2012, and is massively out of date.  That sounds like openwrt backfire era, possibly attitude adjustment.  You want to come up to at least openwrt chaos calmer.

**Comment by pheelan** [comment]
Karlp,
The version of OpenWrt  I am using is the latest for the Arduino YUN, also the version of mosquitto (link from mosquitto.org) is also the latest version.

**Comment by karlp** [comment]
And again, Arduino Yun is _massively_ out of date.  Their Lininio distribution is a fork from years ago, that they don't seem to be updating.  You can run _actual_ openwrt/lede from http://downloads.lede-project.org/snapshots/targets/ar71xx/generic/lede-ar71xx-generic-arduino-yun-squashfs-sysupgrade.bin but that won't include any of the arduino special sauce.

Please, this is _not_ a mosquitto issue, you need to speak to your "vendor"  (That's arduino) and demand better support from them.

**Comment by PierreF** [comment]
Do you still have this issue with recent Mosquitto version ?

**Comment by ralight** [comment]
This hasn't received any updates for a long time, so I'm closing it. If it is still a problem, please reopen and provide more details.
