### ISSUE TITLE
Limited size of mosquitto.db

### ISSUE THREAD

**Issue by OliverSanftleben** [eclipse/mosquitto#302]
Hello,

there seems to be a maximum limit for the size of the persistence file mosquitto.db of 256 MB.

If this limit is reached no subscribe and publish will be possible. If I'm starting mosquitto in this state I get no logging, but the process seems to be running.

If I'm using a new .db file in mosquitto.conf, everything works again.

Oliver

**Comment by ralight** [comment]
What system are you running on? I've definitely had .db files bigger than that before.

**Comment by ralight** [comment]
(there's no intrinsic reason why there would be a limit in file size)

**Comment by OliverSanftleben** [comment]
It's running on Ubuntu 14.04.3 LTS. I see also in the documentation (https://mosquitto.org/man/mosquitto-conf-5.html) that the maximum payload size is 268435455 bytes. Maybe there is a connection between these two limits...

**Comment by OliverSanftleben** [comment]
Here is my configuration:

 # Place your local configuration in /etc/mosquitto/conf.d/
 #
 # A full description of the configuration file is at
 # /usr/share/doc/mosquitto/examples/mosquitto.conf.example

 #pid_file /var/run/mosquitto.pid

persistence true
persistence_file mosquitto2.db
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log
log_dest stdout

log_type all

 #auth_plugin /usr/local/lib/mosquitto/auth_plugin_pyauth.so
 #auth_opt_pyauth_module mqtt-auth-oauth2
acl_file /etc/mosquitto/aclfile
password_file /etc/mosquitto/pwfile
allow_anonymous false

include_dir /etc/mosquitto/conf.d

listener 8883
tls_version tlsv1.2
cafile /etc/mosquitto/ca_certificates/ca.crt
certfile /etc/mosquitto/certs/vmz.services.crt
keyfile /etc/mosquitto/certs/vmz.services.key
require_certificate false

listener 1883 127.0.0.1
listener 9001
protocol websockets

listener 9002
protocol websockets
cafile /etc/mosquitto/ca_certificates/ca.crt
certfile /etc/mosquitto/certs/vmz.services.crt
keyfile /etc/mosquitto/certs/vmz.services.key

**Comment by ralight** [comment]
-rw-rw-r-- 1 roger roger 367M Dec  4 22:37 mosquitto.db  

I've just created that file for a test. I've been sent files >256MB. Do you have some process limits in place that would prevent the broker from opening files >256MB? There is nothing in the broker that would prevent you doing that.

**Comment by ralight** [comment]
There hasn't been an update here for a while so I'm going to close this issue. If you think this is still a problem, please reopen and add more information.

**Comment by DavidMont** [comment]
Hi @ralight I seem to have a problem with my `mosquitto.db` file, my mosquitto hangs up when executing this `exec /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf` 

and this is my `mosquitto.db` 
`-rw-r--r-- 1 mosquitto mosquitto 2292645888 Jul 18 07:41 mosquitto.db1 `
 
and when I execute only `exec /usr/sbin/mosquitto` it works, and now what I did to temporarily fixed it

I renamed my `mosquitto.db` to `mosquitto.db1`

What could be the problem to this?

**Comment by karlp** [comment]
It probably didn't hang, it just looked like it.  A db of that size can take a very long (multiple minutes, up to 15-25 even) to process on startup.  (There have been some patches in the past looking at this, but not many people see it)  if you strace mosquitto, you should see it's still very busy I would expect.
