### ISSUE TITLE
MQTT 5 enhanced authentication feature support.

### ISSUE THREAD

**Issue by ting-ms** [eclipse/mosquitto#3038]
According to the Mosquitto documentation, Mosquitto supports enhanced authentication through plugins. However, there is a lack of detailed information on how to configure it. I've attempted to use the plugin from https://github.com/iegomez/mosquitto-go-auth, which allows for configuring a backend to store username/password information and authenticate using username/password credentials. However, I haven't come across anything related to enhanced authentication, such as challenge/response authentication. Any advice on this?

**Comment by Daedaluz** [comment]
the `mosquitto_auth_start` and `mosquitto_auth_continue` callbacks in the plugin interface suggets challange/response authentication should be possible.

Or the  `MOSQ_EVT_EXT_AUTH_START` and `MOSQ_EVT_EXT_AUTH_CONTINUE` callbacks if you use the newer plugin interface.

I haven't seen / heard of  many plugins out there that utilize these methods in the wild, but then again, I haven't really searched for any.

I can imagine that any implementation probably would be very specific and very custom in many cases.

What kind of challenge / response authentication did you need?

**Comment by ting-ms** [comment]
@Daedaluz Thank you for your response. I just want to do some testing about enhanced authentication, so the specific authentication method isn't a critical concern for me right now.

**Comment by ralight** [comment]
As @Daedaluz says, anything related to the enhanced auth is going to be pretty much tied to the specific authentication method you want to use. There aren't any examples for it that I'm aware of.

Apart from writing an example I don't see that there's much else we can add here, so I'm going to close the issue. If you still want help with writing a plugin that makes use of extended authentication, then please reopen and provide details.
