### ISSUE TITLE
socket leakage

### ISSUE THREAD

**Issue by robustor123** [eclipse/mosquitto#304]
when reconnect is needed, previous socket is not closed.
as following modification, the _mosquitto_socket_close() function should be called.
with this fix, I can remove socket leakage problem in mosquitto library. 

static int _mosquitto_reconnect(struct mosquitto *mosq, bool blocking)
{
...
#ifdef WITH_SOCKS
    if(mosq->socks5_host){
        rc = _mosquitto_socket_connect(mosq, mosq->socks5_host, mosq->socks5_port, mosq->bind_address, blocking);
    }else
#endif
    {    
        if(mosq->sock != INVALID_SOCKET){ 
            _mosquitto_socket_close(mosq); //close socket
        }    
        rc = _mosquitto_socket_connect(mosq, mosq->host, mosq->port, mosq->bind_address, blocking);
    }

**Comment by thlassche** [comment]
@ralight Might this be the cause of #303?

**Comment by thlassche** [comment]
Pull request opened for this #305

**Comment by ralight** [comment]
Thanks both, this is now fixed in the fixes branch.
