### ISSUE TITLE
Invalid protocol version 5 in CONNECT from <client-ip>

### ISSUE THREAD

**Issue by MT22067** [eclipse/mosquitto#3046]
I am receiving the following error when connecting my client to the mosquitto broker:
Invalid protocol version 5 in CONNECT from <client-ip>

client: written oin go and implements MQTTv5

mosquitto version: 1.4.15
Platform: Ubuntu 18.04.6 LTS, 4.15.0-213-generic kernel version

**Comment by Daedaluz** [comment]
I don't think the broker had support of mqttv5 that early.
Try go up a few versions, see if that helps.

**Comment by lucapalano** [comment]
Mosquitto **v1.4.15** doesn't support MQTT v5. As from [the first README.md lines in v1.4.15](https://github.com/eclipse/mosquitto/tree/v1.4.15):
> Mosquitto is an open source implementation of a server for version 3.1 and 3.1.1 of the MQTT protocol

The first version with with MQTT v5 support is 1.6.

Best

**Comment by Daedaluz** [comment]
perhaps we can close this?
