### ISSUE TITLE
Some protocol violations or bugs in Mosquitto

### ISSUE THREAD

**Issue by songxpu** [eclipse/mosquitto#3052]
Hi, I have found some protocol specification violations in Mosquitto, attached below are the details.
The version of Mosquitto: version 2.0.18 
The version of the Operating System: Ubuntu 24.04

**Comment by ckrey** [comment]
@songxpu your first example is incorrect:

You are connecting with MQTTv3. If you use CONNECT with MQTTv3.1.1 or MQTTv5, mosquitto correctly disconnects the client because of a malformed packet (see below).

It would be great if you include a mosquitto log for each of your examples and if you could keep the examples as simple as possible (e.g. complex client, username, will messages and SUBSCRIBE messages when you only want to show a UNSUBSCRIBE).

```
1729024663: mosquitto version 2.0.18 starting
...
1729025569: New client connected from 127.0.0.1:62463 as UBF5bcoi97WeTliL7VLF (p1, c0, k35718, u'weNO7m2HwMb4VeRRoXnkGBnpXq').
1729025569: Will message specified (24 bytes) (r0, q1).
1729025569: 	gHbr9Czh
1729025569: Sending CONNACK to UBF5bcoi97WeTliL7VLF (0, 0)
1729025569: Received PUBLISH from UBF5bcoi97WeTliL7VLF (d0, q1, r0, m46593, 'XVKlzx2I3GgzqQ', ... (18 bytes))
1729025569: Sending PUBACK to UBF5bcoi97WeTliL7VLF (m46593, rc0)
1729025569: Received UNSUBSCRIBE from UBF5bcoi97WeTliL7VLF
1729025569: Sending UNSUBACK to UBF5bcoi97WeTliL7VLF
1729025569: Client UBF5bcoi97WeTliL7VLF closed its connection.
...
1729025955: New connection from 127.0.0.1:63245 on port 1883.
1729025955: New client connected from 127.0.0.1:63245 as UBF5bcoi97WeTliL7VLF (p2, c0, k35718, u'weNO7m2HwMb4VeRRoXnkGBnpXq').
1729025955: Will message specified (24 bytes) (r0, q1).
1729025955: 	gHbr9Czh
1729025955: Sending CONNACK to UBF5bcoi97WeTliL7VLF (1, 0)
1729025955: Received PUBLISH from UBF5bcoi97WeTliL7VLF (d0, q1, r0, m46593, 'XVKlzx2I3GgzqQ', ... (18 bytes))
1729025955: Sending PUBACK to UBF5bcoi97WeTliL7VLF (m46593, rc0)
1729025955: Received UNSUBSCRIBE from UBF5bcoi97WeTliL7VLF
1729025955: Client UBF5bcoi97WeTliL7VLF disconnected due to malformed packet.
```

**Comment by ckrey** [comment]
@songxpu your second example is incorrect too:

You are connecting with MQTTv3. If you use CONNECT with MQTTv3.1.1 or MQTTv5, mosquitto correctly disconnects the client because of a malformed packet (see below).

**Comment by ralight** [comment]
@songxpu Thanks for the reports, I've now pushed changes for the remaining issues except for those related to the payload format indicator. The spec states that the broker "MAY" validate the payload. I'm choosing not to do that for the 2.0.x branch.

**Comment by ralight** [comment]
The changes are part of 2.0.20
