### ISSUE TITLE
TLS Compatible Docker Image.

### ISSUE THREAD

**Issue by emvarunp** [eclipse/mosquitto#3059]
Mosquitto Version: 2.0.18
Platform : Ubuntu.

Hi,

Requesting to add a mount point in Docker image
``` 
/mosquitto/certs
```
To mount the SSL/TLS certificates.

If there is any already existing location to store the certificates, that information would be helpful for me.

Thank You,
V.

**Comment by emvarunp** [comment]
@ralight

**Comment by sukesh-ak** [comment]
@emvarunp 
You can refer my write-up here to get started. I setup using caddyserver for SSL (`5.1`) and reverse proxy.
https://github.com/sukesh-ak/setup-mosquitto-with-docker

**Comment by emvarunp** [comment]
issue resolved. Using docker image `eclipse-mosquitto:2.0.18-openssl`, which let me mount the certs into the container.

Thank you,
V.
