### ISSUE TITLE
mosquitto.conf in README.md is broken

### ISSUE THREAD

**Issue by gpayer** [eclipse/mosquitto#3075]
Mosquitto does not event start, not a single error message is given.

**Comment by Daedaluz** [comment]
If this is still relevant, I do not know which mosquito.conf you are referring to. How did you try start mosquito?

**Comment by gpayer** [comment]
I think I tried to follow the "Quick start" section in the README.md. I then found out myself, that this description is seriously lacking in detail, as you need a mosquitto.conf where listeners have to be defined.
So a minimal mosquitto.conf should be included in this "Quick start" section, e.g.:

```
log_dest stdout

listener 1883
allow_anonymous true
```

**Comment by gpayer** [comment]
Why is your first thought that someone will immediately run this on a public server with this conf?
I'm sure it is possible to only listen on `127.0.0.1`, maybe `listener 127.0.0.1:1883` is supported. So this should be reflected in a quick start example to be run in a local development environment.

Or at least put in a reminder that one has to create a conf file first! Is that so hard? Is that too much to ask? At the moment it is suggested that you only have to run `mosquitto` and that is plainly wrong.

**Comment by ralight** [comment]
It's a bit difficult to have a straightforward quick start when almost all of the different packaging solutions out there are incompatible with each other in dealing with config files. It's a bit annoying.

I've added some extra text to make the limitations of running without a config file clear, plus some pointers to the documentation on authentication methods. It's an improvement, but I think that it perhaps needs that part removing and installation method specific guides putting up somewhere instead, with links in the readme.
