### ISSUE TITLE
How to get client IP address?

### ISSUE THREAD

**Issue by joe-average-user** [eclipse/mosquitto#3086]
Hello,

I want to create an auth module for mosquitto that uses amongst other the client IP address. Is mosquitto->address the client IP (in some form (as string))?

Thank you!

**Comment by Miguel-AgRz** [comment]
mosquitto_client_address func

**Comment by Daedaluz** [comment]
I guess this answered the question.
Can we close?

**Comment by joe-average-user** [comment]
Thank you for giving me the chance on a sunday to reply ;-)

**Comment by ralight** [comment]
Sorry, I was being a bit quick at trying to tidy up,

**Comment by joe-average-user** [comment]
Was no offense. I just did not request close myself because was not able to test the suggestion so far. busy busy ...
