### ISSUE TITLE
mosquitto docker image / multiple digest changes in past 3 days / suspicious? 

### ISSUE THREAD

**Issue by reefland** [eclipse/mosquitto#3087]
I have my mosquitto image with SHA pinned at:
```
docker.io/library/eclipse-mosquitto:2.0.18@sha256:c1322c707de51ee034b9fe2204975d8fd716ed6b8a5a39a3dffe53ec024dc30d
```

Over the past 3 days RenovateBot reported many digest updates for this version which does not seem like typical activity for this image. It seems suspicious to me.  Something going on??

![image](https://github.com/user-attachments/assets/7a7b3b12-a5f5-4a25-8ae6-265b83797c12)

**Comment by Daedaluz** [comment]
Does [this](https://github.com/eclipse/mosquitto/issues/2484) help?

**Comment by reefland** [comment]
Sort of...  if there is a known cause it explains why a one off digest with no changes happens, such as in 2022 it referenced the "defunct gpg keyserver".  

It's not just mosquitto, it seems all the docker.io images I have references to had new digests issued without version changes.  None of them had as many as mosquitto which made it stand out.

Thanks.

**Comment by Daedaluz** [comment]
Can we close this?
