### ISSUE TITLE
linker command failed with exit code 1: 

### ISSUE THREAD

**Issue by leonidaas** [eclipse/mosquitto#3092]
When I try to cmake and make the project on my **Macbook Pro M1 with arm64** architecture i get the following error:

[ 11%] Building C object lib/CMakeFiles/libmosquitto.dir/packet_datatypes.c.o
[ 12%] Building C object lib/CMakeFiles/libmosquitto.dir/packet_mosq.c.o
[ 12%] Building C object lib/CMakeFiles/libmosquitto.dir/property_mosq.c.o
[ 13%] Building C object lib/CMakeFiles/libmosquitto.dir/read_handle.c.o
[ 13%] Building C object lib/CMakeFiles/libmosquitto.dir/send_connect.c.o
[ 14%] Building C object lib/CMakeFiles/libmosquitto.dir/send_disconnect.c.o
[ 14%] Building C object lib/CMakeFiles/libmosquitto.dir/send_mosq.c.o
[ 15%] Building C object lib/CMakeFiles/libmosquitto.dir/send_publish.c.o
[ 15%] Building C object lib/CMakeFiles/libmosquitto.dir/send_subscribe.c.o
[ 16%] Building C object lib/CMakeFiles/libmosquitto.dir/send_unsubscribe.c.o
[ 16%] Building C object lib/CMakeFiles/libmosquitto.dir/socks_mosq.c.o
[ 17%] Building C object lib/CMakeFiles/libmosquitto.dir/srv_mosq.c.o
[ 17%] Building C object lib/CMakeFiles/libmosquitto.dir/strings_mosq.c.o
[ 18%] Building C object lib/CMakeFiles/libmosquitto.dir/thread_mosq.c.o
[ 18%] Building C object lib/CMakeFiles/libmosquitto.dir/time_mosq.c.o
[ 19%] Building C object lib/CMakeFiles/libmosquitto.dir/tls_mosq.c.o
[ 19%] Building C object lib/CMakeFiles/libmosquitto.dir/utf8_mosq.c.o
[ 20%] Building C object lib/CMakeFiles/libmosquitto.dir/util_mosq.c.o
[ 20%] Building C object lib/CMakeFiles/libmosquitto.dir/util_topic.c.o
[ 20%] Building C object lib/CMakeFiles/libmosquitto.dir/will_mosq.c.o
[ 21%] Linking C shared library libmosquitto.dylib
ld: unknown options: --version-script=/Users/leon.fuessner/Workspace/mosquitto/lib/linker.version
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libmosquitto.2.0.18.dylib] Error 1
make[1]: *** [lib/CMakeFiles/libmosquitto.dir/all] Error 2
make: *** [all] Error 2

Has anyone experienced something similiar?

**Comment by hpertaia** [comment]
Had same issue. Deleting --version-script link flag from lib/CMakeLists.txt  fixes it.  

As I understand, the reason it happens is because --version-script is a GNU linker flag, and mac linker doesn't support it.

**Comment by ralight** [comment]
This is fixed as in #3125
