### ISSUE TITLE
How do I access 'Local MQTT' with 'DNS' from another device?

### ISSUE THREAD

**Issue by Ridyu** [eclipse/mosquitto#3093]
I made a local server using Mosquito and on my PC.
Another device is trying to connect to an MQTT server that I made Local on my PC.
(it is an environment connected to the same WiFi.)
At this time, is there a way to access the local server using a DNS address instead of an IP address?
I tried putting DNS addresses in MOSQUITTO.conf and host respectively, but I can't access them from other devices

`
[ CMD ]
cd C:\Program Files\mosquitto
mosquitto -v -c broker.conf
`
 mosquitto version 2.0.15 starting
Config loaded from broker.conf.
 Opening ipv4 listen socket on port 1883.
mosquitto version 2.0.15 running

**Comment by Daedaluz** [comment]
You need a DNS server.

Typically, the general home router do have one already, but the support for automatic hostname lookup varies.

On the mosquitto machine, type `hostname` in cmd to get the hostname.

Then you can try on the other machine to connect with  `hostname.local` or `hostname.lan`, perhaps `hostname.home`, or just straight up `hostname` depending on your router.

If you have access to your router, you might be able to override or add new dns names to your mosquitto machine and solve it that way.

**Comment by Ridyu** [comment]
Thank you for your reply.
I have verified that you can connect from another device using [hostname.local]
