### ISSUE TITLE
persistence_file mosquitto.db is not a database

### ISSUE THREAD

**Issue by diana0809** [eclipse/mosquitto#3113]
When I open this file with DBeaver, error has been occured.
![err1](https://github.com/user-attachments/assets/bcad2a01-9c80-487b-9e7a-b0f5a412433e)

mosquitto.conf  
![err](https://github.com/user-attachments/assets/8a77d784-766a-4464-85bb-de3deaa3fa26)

**Comment by sikmir** [comment]
Try [db_dump](https://github.com/eclipse/mosquitto/tree/master/apps/db_dump) instead.

**Comment by karlp** [comment]
(it's not claimed to be a sqlite db anyway....)

**Comment by Daedaluz** [comment]
I think the problem has been highlighted. can we close?
