### ISSUE TITLE
 Mosqitto does not start with -v mosquitto.conf:/mosquitto/config/mosquitto.conf

### ISSUE THREAD

**Issue by dippes** [eclipse/mosquitto#3118]
I am trying to start Eclipse Mosquitto with the command. But the start is aborted with this error message.

`root@hp-server:~#  docker run -d -p 1883:1883 -p 9001:9001 -v mosquitto.conf:/mosquitto/config/mosquitto.conf eclipse-mosquitto`
3d9ab437a12f7af46ccf6376a2baa9cb5a4eac4d333083d81629390f1f93f43b

`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/docker/volumes/mosquitto.conf/_data" to rootfs at "/mosquitto/config/mosquitto.conf": create mount destination for /mosquitto/config/mosquitto.conf mount: cannot mkdir in /var/lib/docker/overlay2/f8e573318cdb826b571e35241e3eeb6cb4b981669fbf4aef68e14c5816d25ed0/merged/mosquitto/config/mosquitto.conf: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.`
root@hp-server:~#

However, if I start with this command (without mosqitto.conf) the container starts without any problems.
docker run -d -p 1883:1883 -p 9001:9001 -v mosquitto.conf:/mosquitto/config/ eclipse-mosquitto

the file exists on the PC (/mosquitto/config/mosquitto.conf)

Does anyone have an idea?

**Comment by ralight** [comment]
Please try mounting a directory instead:

`docker run -p 1883:1883 -v <path containing mosquitto.conf>:/mosquitto/config eclipse-mosquitto`

**Comment by diramazioni** [comment]
I also have issue with docker, with default config (and no volume mounted) I can see mosquitto listening with `netstat` but it doesn't accept connections from clients.
The image is the latest

**Comment by ralight** [comment]
```
## Running without a configuration file
Mosquitto 2.0 requires you to configure listeners and authentication before it
will allow connections from anything other than the loopback interface. In the
context of a container, this means you would normally need to provide a
configuration file with your settings.

If you wish to run mosquitto without any authentication, and without setting
any other configuration options, you can do so by using a configuration
provided in the container for this purpose:
```
docker run -it -p 1883:1883 eclipse-mosquitto:<version> mosquitto -c /mosquitto-no-auth.conf
```
```

**Comment by dippes** [comment]
have given the full path but still docker won't start

root@hp-server:~# docker run -d -p 1883:1883 -p 9001:9001 -v /var/lib/docker/volumes/mosquitto.conf/_data/mosquitto.conf:/mosquitto/config/ eclipse-mosquitto
```
bb55d34f459d2e3840aa63758835a122e72c13f69dbf9d4f4a7c140473585787
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/docker/volumes/mosquitto.conf/_data/mosquitto.conf" to rootfs at "/mosquitto/config": mount /var/lib/docker/volumes/mosquitto.conf/_data/mosquitto.conf:/mosquitto/config (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

That won't work either

docker run -it -p 1883:1883 eclipse-mosquitto: mosquitto -c /mosquitto-no-auth.conf

```
docker: invalid reference format.
See 'docker run --help'.
```


```

**Comment by Daedaluz** [comment]
How about
`docker run -d -p 1883:1883 -p 9001:9001 -v /var/lib/docker/volumes/mosquitto.conf/_data/mosquitto.conf:/mosquitto/config/mosquitto.conf eclipse-mosquitto`?

Long guided explanation:

If you run `docker run --rm -ti eclipse-mosquitto sh` you'll get a shell inside the mosquitto container without mosquitto actually running, then if you run `ls /mosquitto` inside the container you'll see that there are three driectories: `config` `data` and `log`.

If you run `ls -la /var/lib/docker/volumes/mosquitto.conf/_data/mosquitto.conf` on the host, you'll see that mosquitto is a file.

The first docker command: `docker run -d -p 1883:1883 -p 9001:9001 -v /var/lib/docker/volumes/mosquitto.conf/_data/mosquitto.conf:/mosquitto/config/ eclipse-mosquitto` tries to mount the mosquitto.conf file onto the /mosquitto/config directory.

You cannot mount a file onto a directory, hence this fails.

The second docker command that @ralight suggested: `docker run -it -p 1883:1883 eclipse-mosquitto: mosquitto -c /mosquitto-no-auth.conf` has a `:` in it, just after the image name; `eclipse-mosquitto:` this is treated as a tag delimiter like you would run a specific mosquitto image, eg: "eclipse-mosquitto:2.0.19` but the actual tag left out - hence the "invalid reference".

To get this command running, simply remove the `:` after the image name:
`docker run -it -p 1883:1883 eclipse-mosquitto mosquitto -c /mosquitto-no-auth.conf` 

Now, back to the first command; mounting docker volumes this way is probably not encouraged, use the volume name instead like so:

`docker run -d -p 1883:1883 -p 9001:9001 -v mosquitto.conf:/mosquitto/config/ eclipse-mosquitto`

this will mount the volume _directory_ `mosquitto.conf` (not the file mosquitto.conf) to the `/mosquitto/config` directory in the container.

**Comment by ralight** [comment]
Yep, sorry about the typo!

**Comment by dippes** [comment]
These two commands start Mosquitto but the mosquitto.conf is not mounted to "/mosquitto/config/".

`docker run -d -p 1883:1883 -p 9001:9001 -v /var/lib/docker/volumes/mosquitto.conf/_data/mosquitto.conf:/mosquitto/config/mosquitto.conf eclipse-mosquitto`

`docker run -d -p 1883:1883 -p 9001:9001 -v mosquitto.conf:/mosquitto/config/ eclipse-mosquitto`

This command works without configurable.conf

`docker run -it -p 1883:1883 eclipse-mosquitto mosquitto -c /mosquitto-no-auth.conf`

**Comment by dippes** [comment]
Is that what you mean?

If so, the path did not work for me, didn't it?

`docker run -d -p 1883:1883 -p 9001:9001 -v /var/lib/docker/volumes/mosquitto.conf/_data/mosquitto.conf:/mosquitto/config/mosquitto.conf eclipse-mosquitto`

**Comment by Daedaluz** [comment]
But is there a mosquitto.conf inside _data?
 Post `ls -la /var/lib/docker/volumes/mosquitto.conf/_data/`

And if there is a mosquitto.conf in there, post the content of it.

**Comment by dippes** [comment]
root@hp-server:~# ls -la /var/lib/docker/volumes/mosquitto.conf/_data/
total 48
drwxr-xr-x 2 1883 1883  4096 Okt  2 16:07 .
drwx-----x 3 root root  4096 Okt  2 13:08 ..
-rw-r--r-- 1 1883 1883 40449 Sep  7 01:15 mosquitto.conf


[https://pastebin.com/bckA2X63](url)

**Comment by ralight** [comment]
This process works for me:

```
mkdir -p /home/roger/mosquitto/config
mkdir -p /home/roger/mosquitto/data
cat << EOF > /home/roger/mosquitto/config/mosquitto.conf
listener 1883
allow_anonymous true
EOF
docker run -it -v /home/roger/mosquitto/config:/mosquitto/config -v /home/roger/mosquitto/data:/mosquitto/data -p 1883:1883 eclipse-mosquitto:latest
```

In my opinion, always mounting a directory makes more sense than mounting a config file, it's more flexible if you want to add certificates, for example.

The data directory is a good place to store broker generated data, whereas the config directory should be essentially static.
