### ISSUE TITLE
Delay in Receiving messages at Subscriber

### ISSUE THREAD

**Issue by nikhilve99** [eclipse/mosquitto#312]
Hi We are trying to test the mosquitto MQTT Server Ver Installed on OS Ubuntu 14.4
We have 4 core Machine 3GB RAM
Without load the messages are received by subscriber ASAP.
The payload is 30 Bytes Ascii data

When we put a load of 100 user sending data every 2 seconds.

Subscriber receive the messages with a delay of 10-15 seconds. We want to use the setup to have at-least 1000 User sending data every 5 seconds.

The Subscriber is subscribed with wildcard(#).

Please let us know what could be wrong.

**Comment by nikhilve99** [comment]
We are using
MQTT Ver 3.1
Mosquito Ver 1.4

**Comment by ralight** [comment]
Could you please provide more details of what you are doing? For example, what client are you using in your tests? Have you tried any other clients?

**Comment by iamajit381** [comment]
I am also facing this same issue ..when running my website in local publishing and receiving message take no delay but in live/production it takes around approx 10 seconds to receive message.

To publish message we have used Moscapsule (ios)
and to receive message paho (web). so in my application we are sending message from ios device to web. 

It  would be very helpful if you give some suggestion to fix this.

**Comment by PierreF** [comment]
Do you still have this issue ? Are you sure this delay is not the network delay ? (you are talking about local vs mobile network).

**Comment by ralight** [comment]
I'm closing this because it has been inactive for a long time. If you still have the problem, please reopen and provide more details.
