### ISSUE TITLE
Load balancing between client

### ISSUE THREAD

**Issue by vitorrents** [eclipse/mosquitto#313]
Greetings to everyone,

Reading the HiveMQ blog I saw the following entry:
http://www.hivemq.com/blog/mqtt-client-load-balancing-with-shared-subscriptions/

There they explain a feature that, although I think it is not in the standard, is very useful.

"Shared Subscription supports Load balancing to distribute MQTT messages between multiple subscribers in the same group".

I have continued researching and found that another pair of brokers are implementing it.

They are called in a different way:
Shared Subscriptions
Consumer Session Balancing

I could not find anything similar in Mosquitto

How could you implement the load balancing between customer in Mosquitto?
Is there a plugin that does it?

Thanks in advance.

**Comment by vitorrents** [comment]
Apologies: It seems that the link is down,

This is a git that explains very well:

http://www.hivemq.com/docs/hivemq/latest/images/shared-subscriptions/shared_subscriptions.gif

**Comment by toast-uz** [comment]
This is one of the key enhancements of MQTT version 5. I'd like to offer in the future.
At the same time, I can also offer it on current MQTT version by using a non standard directive of conf.

**Comment by daratha** [comment]
Is this shared subscription feature available in the latest version.

**Comment by ralight** [comment]
Yes it is, so actually I will close this issue.

**Comment by k2mahajan** [comment]
Can someone please share a link to the documentation of shared subscription support in eclipse mqtt here?
