### ISSUE TITLE
Websockets in Windows

### ISSUE THREAD

**Issue by campanflaviu** [eclipse/mosquitto#315]
Hello,

I'm trying to add websockets protocol in mosquitto.conf but I can't seem to be able to start the windows service with the 'protocol websockets' line in the configuration file.
I'm using Windows 10 with the latest mosquitto build (1.4.10).

Thanks!

**Comment by ralight** [comment]
Is this using the provided installer, or did you compile yourself? At the moment the installer doesn't have websockets support.

**Comment by campanflaviu** [comment]
That explains it. Will try to build from source. Thanks!

**Comment by ralight** [comment]
You might have to build libwebsockets as well, I don't believe they provide Windows binaries.

**Comment by ralight** [comment]
I'm closing this because I think you have a solution, please feel free to reopen and add more information if you disagree.

**Comment by Aeefire** [comment]
Would there be anyone willing to send me websockets-enabled executables for Windows? I somehow don't manage to get it to compile..
