### ISSUE TITLE
Different authentication strategies for different users.

### ISSUE THREAD

**Issue by vivek1729** [eclipse/mosquitto#322]
I am using mosquitto as a broker and I have two kinds of clients. One would be the superadmin that would sit in the App server. Second would be different clients from the browser connecting through websockets. I will authenticate the browser clients through an HTTP API that sits on the App server itself where I have my superadmin client too. 

How can I have two authentication strategies? So that I can may be check default username password matching for users and in case of failure fall back to HTTP authentication and then finally deny access if both these strategies fail?

Any ideas/suggestions on how to cascade multiple authentication strategies

**Comment by ralight** [comment]
You've already seen mosquitto-auth-plug. In addition to that, version 1.5 will allow you to mix multiple authentication plugins including the built in password file.

**Comment by ralight** [comment]
This has been supported for a long while now, so I am closing this issue.
