### ISSUE TITLE
TLS Bridges only support IPv4

### ISSUE THREAD

**Issue by hardillb** [eclipse/mosquitto#323]
I've been poking round the bridge code to see how easy it would be to move it to doing async DNS look up for #41 and I spotted this in net_mosq.c:

https://github.com/eclipse/mosquitto/blob/master/lib/net_mosq.c#L284-L288

This looks like it limits DNS lookups to only returning IPv4 addresses if the bridge connection is protected by TLS. 

Is there a specific reason for this? IPv6 is only going to get more used more and more, especially in the IoT space. LTE networks are supposed to be IPv6 enabled by default.

**Comment by ralight** [comment]
You're right, it does.

I believe that there were historic problems with openssl and ipv6 which no longer apply. I've changed that now.

**Comment by hardillb** [comment]
Thanks, I'd have stuck in a pull request, but wanted to check if it was deliberate first.
