### ISSUE TITLE
ubuntu libwebsockets reboot problem

### ISSUE THREAD

**Issue by electrocoder** [eclipse/mosquitto#325]
Hi friends. 
I have install to libwebsockets library.
Write Ubuntu 14.04 server "listener 9001 my_server_ip" and "protocol websockets" in  "/etc/mosquitto/mosquitto.conf" file.

Run "mosquitto -c /etc/mosquitto/mosquitto.conf" in terminal and "mosquitto_sub -h my_server_ip -t "#" -v" not problem. It's running.

But when the server is restarted problem  "Error: Connection refused".

~# mosquitto
1480535743: mosquitto version 1.4.8 (build date 2016-11-30 13:43:16-0500) starting
1480535743: Using default config.
1480535743: Opening ipv4 listen socket on port 1883.
1480535743: Opening ipv6 listen socket on port 1883.
1480535743: New connection from 88.238.109.200 on port 1883.

**Comment by electrocoder** [comment]
~# mosquitto -c /etc/mosquitto/mosquitto.conf
1480536669: mosquitto version 1.4.8 (build date 2016-11-30 13:43:16-0500) starting
1480536669: Config loaded from /etc/mosquitto/mosquitto.conf.
1480536669: Opening ipv4 listen socket on port 1883.
1480536669: Opening ipv6 listen socket on port 1883.
1480536669: Opening websockets listen socket on port 9001.
1480536670: New connection from 88.238.109.200 on port 1883.


Not working Ubuntu restart

**Comment by ralight** [comment]
How did you install the broker?

**Comment by ralight** [comment]
I'm closing this due to not enough information, no response, and 14.04 being end of life.
