### ISSUE TITLE
Please provide RPMs etc for WebSocket builds

### ISSUE THREAD

**Issue by Hades32** [eclipse/mosquitto#326]
Your provided packages are very much appreciated, but if one wants to use the WebSocket support you still have to comile yourself.

How about also providing a mosquitto-ws package that provides a version with web sockets built in?

**Comment by ralight** [comment]
If the distros now have libwebsockets support then it should be
straightforward. If they don't, then it's much trickier.

I know fedora has lws, do opensuse and the rest have it?

**Comment by Hades32** [comment]
CentOS and Ubuntu should have them. And it could also be an option to compile it in statically.

And IMHO it wouldn't be too terrible if it only worked for the most common distros...

**Comment by CloCkWeRX** [comment]
I'd be quite keen to see it; I can stop doing https://github.com/CloCkWeRX/chef-mosquitto/blob/master/recipes/source.rb :)

**Comment by Hades32** [comment]
1.4.11 Fedora 25 package does seem to have it now. Although it doesn't actually work... Was anything done here @ralight ?

**Comment by bekarau** [comment]
Who is actually doing the RPM packaging? There's no SPEC file in the tar ball, so I can't feed back a patch to fix the erroneous inclusion of 'libwebsockets' when it doesn't actually link the library.

**Comment by ralight** [comment]
I'm closing this because it has been a while since we have provided rpm packages. If the distro package you're using doesn't have websocket support, it needs taking up with the distro.
