### ISSUE TITLE
Possibility of negative value for timeout variable of the pselect inside mosquitto_loop

### ISSUE THREAD

**Issue by Dollars** [eclipse/mosquitto#329]
If you make a sleep in a loop before calling `mosquitto_loop` it is possible that `now` is greater than `mosq->next_msg_out` which result in a negative value for `timeout`. Then, `pselect` will fail with a `EINVAL` error. Should'nt we add `timeout = timeout < 0 ? 0 : timeout` inside the if block ?

**Comment by ralight** [comment]
Thanks, you're quite right. I've fixed this on the fixes branch.
