### ISSUE TITLE
QoS 2 not being received at all.

### ISSUE THREAD

**Issue by AdamMiltonBarker** [eclipse/mosquitto#331]
Hi guys I have been having issues with clients disconnecting and losing messages that had been published to them so decided to have a play with QoS where previously everything had been QoS 0. 

I have tried publishing the messages with QoS 2 as well as subscribing from the client with the same however nothing happens. I see the following in verbose but nothing on the device at all. 

1481347639: Received SUBSCRIBE from CLIENT
1481347639:     1/Devices/1/23/Commands (QoS 2)
1481347639: CLIENT 2 1/Devices/1/23/Commands
1481347639: Sending SUBACK to CLIENT
1481347639: Received SUBSCRIBE from CLIENT
1481347639:     1/Devices/1/23/AITraining/# (QoS 2)
1481347639: CLIENT 2 1/Devices/1/23/AITraining/#
1481347639: Sending SUBACK to CLIENT
1481347639: Received SUBSCRIBE from CLIENT
1481347639:     1/Devices/1/23/Keys (QoS 2)
1481347639: CLIENT 2 1/Devices/1/23/Keys
1481347639: Sending SUBACK to CLIENT
1481347639: Received SUBSCRIBE from CLIENT
1481347639:     1/Devices/1/23/SSLs (QoS 2)
1481347639: CLIENT 2 1/Devices/1/23/SSLs
1481347639: Sending SUBACK to CLIENT

1481347660: Sending CONNACK to BROKERCLIENT (0, 0)
1481347660: Received PUBLISH from BROKERCLIENT (d0, q2, r0, m1, '1/Devices/1/23/Commands', ... (64 bytes))
1481347660: Sending PUBREC to BROKERCLIENT (Mid: 1)
1481347660: Received PUBLISH from BROKERCLIENT (d0, q2, r0, m2, '1/Devices/1/23/Commands', ... (65 bytes))
1481347660: Sending PUBREC to BROKERCLIENT (Mid: 2)

Any ideas.

**Comment by ralight** [comment]
A QoS 2 message flow involves these messages:

PUBLISH (client to broker in your case)
PUBREC (broker to client)
PUBREL (client to broker)
PUBCOMP (broker to client)

The broker is sending the PUBREC in response to the PUBLISH from your client. Your client doesn't appear to be responding with a PUBREL.

If you are using libmosquitto, are you calling mosquitto_loop_forever() or mosquitto_loop_start(), which are the functions you need to ensure all network traffic is processed. The behaviour of disconnectiing and losing messages that you've already seen would be consistent with not calling one of the loop functions as well.

**Comment by AdamMiltonBarker** [comment]
Thanks for the reply the BROKERCLIENT is a client on my broker, it is sending a command to an additional device, yes mosquitto_loop_forever()  is used in all of my software.

**Comment by AdamMiltonBarker** [comment]
I think the disconnection is due to a long process that happens as a result of a message. Basically a OpenCV EignenFace model training process starts and trains the new model, while this is happening it disconnects, I am fairly certain it is related to that, but, if I start the device client after the message has been sent it does not receive it, but in this case, no matter what whether the client is connected or not, no message is received, during testing I had the two terminals opened, I saw the publish being sent but the active client received nothing.

**Comment by ralight** [comment]
If you've got long processing happening (and it's not in a callback) then you might be better off using loop_start() instead so that it has a separate thread for the network traffic. If your processing happens in a callback that will block the network thread so you might need to think of a different way of dealing with it - pushing data to a queue in the callback, then another thread unrelated to the mqtt client picks up the data from the queue and does the processing.

**Comment by AdamMiltonBarker** [comment]
Thanks it is in a callback, the broker sends a bytearray of the image to the device and the callback picks it up then starts the training processing, it definitely is at this point the client disconnects but will have to check other devices to see if there is any disconnect anywhere else, but I do think in this case it is only on this device and related to the training process. Ok that makes sense on the queue I can sort that out, thanks for the idea. Would still like to find out why no QoS messages get received even when it is not related to the above issue. Litterally, the device receives nothing when using QoS 2

**Comment by ralight** [comment]
Have you been able to verify that QoS 2 works in general using mosquitto_sub and mosquitto_pub?

**Comment by luzhuqun** [comment]
I use mosquitto_pub but it doesn't work, like this `mosquitto_pub -t tokudu/ab7867d9fd60db65 -m 1111 -q 2`  
A QoS 2 message flow involves these messages:
PUBLISH (client to broker in your case)
PUBREC (broker to client)
PUBREL (client to broker)
PUBCOMP (broker to client)

I am new to mosquitto ,I don't know what does this mean, could you please give me an example?

**Comment by AdamMiltonBarker** [comment]
@ralight will get back soon mate. @luzhuqun with QoS 2 the broker should keep trying to send the message until the client receives it, PUBREC will be sent to the client which should then respond with PUBREL, once the broker receives that it completes with PUBCOMP unless I am mistaken.

**Comment by luzhuqun** [comment]
@AdamMiltonBarker I have successed in using mosquitto_pub , I just changed some configs.  
`persistence true ` in mosquitto.conf   and in android app PushService.java
 `private static boolean			MQTT_CLEAN_START          = false;` 
`private static int				MQTT_QUALITY_OF_SERVICE   = 2;`

**Comment by ralight** [comment]
@luzhuqun This is an issue report related to a problem that @AdamMiltonBarker is having. It sounds like you have a different problem so please open a separate issue if you believe it is related to mosquitto. Having said that, the tokudu example you appear to be using is ancient and is a poor example of how to use mqtt anyway, I would suggest looking elsewhere like the Paho Android examples.

**Comment by ralight** [comment]
I'm closing this because it is very old now, and there is plenty of success with people using QoS 2. If it is still a problem, please reopen and add more information.
