### ISSUE TITLE
How to clear mosquitto.db

### ISSUE THREAD

**Issue by ajeshpgkumar** [eclipse/mosquitto#337]
How can I clear my mosquitto.db on a regular interval.

**Comment by electrocoder** [comment]
Hi @ajeshpgkumar. 
persistence [ true | false ]
If true, connection, subscription and message data will be written to the disk in mosquitto.db at the location dictated by persistence_location. When mosquitto is restarted, it will reload the information stored in mosquitto.db. The data will be written to disk when mosquitto closes and also at periodic intervals as defined by autosave_interval. Writing of the persistence database may also be forced by sending mosquitto the SIGUSR1 signal. If false, the data will be stored in memory only. Defaults to false.

**Comment by ajeshpgkumar** [comment]
Hi, thanks for the comments.
But how can I clear it once it exceeds a particular size.

My local broker is running on a limited memory( 512 MB) and I can see the mosquitto.db size is getting increased day by day. So I want to have some logic to clear it.

**Comment by ralight** [comment]
You could use mosquitto_db_dump  in the src/db_dump directory to try and figure out where the space is going. It's pretty crude, you'll probably have to tweak it to get the information you want.

After you've done that, you'll know which retained messages to delete (by publishing a zero length retained message to the topics), or which clients are causing messages to be queued for them. To remove those, connect a client with the same client id and set the clean session flag.

**Comment by karlp** [comment]
The db_dump tool is relatively easy to hack on to do special things too.  Here's an example of dumping all messages for a client id, and a python tool to republish them again. https://github.com/remakeelectric/mosquitto/commit/41554d5dec7df610bc0eb638d48e57bc2354d003

**Comment by ralight** [comment]
Closing because there hasn't been any update for a while. If you think this is still a problem, please provide more information and reopen.
