### ISSUE TITLE
MQTT-SN support

### ISSUE THREAD

**Issue by nginxsantos** [eclipse/mosquitto#341]
Hi,

Does this support MQTT-SN?

Regards, Santos

**Comment by nginxsantos** [comment]
Hi @kartben - can you or any one you kindly clarify on this?

**Comment by ralight** [comment]
Mosquitto doesn't support MQTT-SN yet, no.

**Comment by chaitan94** [comment]
Are there any plans on supporting it in the future? If not, any specific reason for not considering it?
