### ISSUE TITLE
0xc000007b exception when running pub and sub (W10 64-bit)

### ISSUE THREAD

**Issue by naibalucian** [eclipse/mosquitto#342]
I've tried both using the regular win32 installer and building it on my own using [the build notes here](https://github.com/bapowell/bapowell.github.io/wiki/Mosquitto-Build-Notes-(Windows---Visual-Studio)), but both times running mosquitto_pub and mosquitto_sub would throw the above exception. Looking through the dependency walker as a few others before me did (none of the previously reported solutions having helped me) showed that, besides libeay32, ssleay32, msvcr120, mosquitto and the actual executable associated with the publisher (all being in x86), everything else that it relies on is in x64.

What's probably more relevant to me is that even the programs I'm trying to build that make use of it run into similar issues. The temperature conversion example throws the exact same error.

I'm at my wit's end trying to figure this out. I know for sure that I'm the one doing something wrong, but I have no idea what, and nothing that I've looked through pertaining to this issue (such as [this](https://github.com/eclipse/mosquitto/issues/261)) has helped me thus far. Any tips on what I could do?

As far as I'm aware, I'm using the latest version of mosquitto (for both the source I'm trying to build myself and for the installer (1.4.10)), the 2.9.1 w32 version of pthreads, and I've tried both the 1.1.0 and 1.0.2 big (not light) versions of OpenSSL with no luck. As I'm not super experienced, I'm currently using the cmake gui instead of just the cli. I've also tried to build x64 versions of libwebsockets and mosquitto, but to no avail ("library machine type 'X86' conflicts with target machine type 'x64'" and all that, which I think may be the strongest indication that I'm doing something wrong).

If you want any additional information, do let me know.

Update: If it helps, looking at mosquitto_pub through the dependency walker, it's telling me that the following cannot be found:
- API-MS-WIN-CORE-APIQUERY-L1-1-0.DLL
- API-MS-WIN-CORE-APPCOMPAT-L1-1-1.DLL
- API-MS-WIN-CORE-APPINIT-L1-1-0.DLL
- API-MS-WIN-CORE-ATOMS-L1-1-0.DLL
- API-MS-WIN-CORE-COMM-L1-1-0.DLL
- API-MS-WIN-CORE-CONSOLE-L2-1-0.DLL
- API-MS-WIN-CORE-CRT-L1-1-0.DLL
- API-MS-WIN-CORE-CRT-L2-1-0.DLL
- API-MS-WIN-CORE-DATETIME-L1-1-1.DLL
- API-MS-WIN-CORE-DATETIME-L1-1-2.DLL
- API-MS-WIN-CORE-DEBUG-L1-1-1.DLL
- API-MS-WIN-CORE-DELAYLOAD-L1-1-1.DLL
- API-MS-WIN-CORE-ENCLAVE-L1-1-0.DLL
- API-MS-WIN-CORE-ERRORHANDLING-L1-1-1.DLL
- API-MS-WIN-CORE-ERRORHANDLING-L1-1-3.DLL
- API-MS-WIN-CORE-FIBERS-L1-1-1.DLL
- API-MS-WIN-CORE-FIBERS-L2-1-1.DLL
- API-MS-WIN-CORE-FILE-L1-2-1.DLL
- API-MS-WIN-CORE-FILE-L1-2-2.DLL
- API-MS-WIN-CORE-FILE-L2-1-1.DLL
- API-MS-WIN-CORE-FILE-L2-1-2.DLL
- API-MS-WIN-CORE-HEAP-L1-2-0.DLL
- API-MS-WIN-CORE-HEAP-L2-1-0.DLL
- API-MS-WIN-CORE-HEAP-OBSOLETE-L1-1-0.DLL
- API-MS-WIN-CORE-INTERLOCKED-L1-2-0.DLL
- API-MS-WIN-CORE-IO-L1-1-1.DLL
- API-MS-WIN-CORE-JOB-L1-1-0.DLL
- API-MS-WIN-CORE-KERNEL32-LEGACY-L1-1-1.DLL
- API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
- API-MS-WIN-CORE-LIBRARYLOADER-L1-2-0.DLL
- API-MS-WIN-CORE-LIBRARYLOADER-L1-2-2.DLL
- API-MS-WIN-CORE-LIBRARYLOADER-L2-1-0.DLL
- API-MS-WIN-CORE-LOCALIZATION-L1-2-1.DLL
- API-MS-WIN-CORE-LOCALIZATION-L2-1-0.DLL
- API-MS-WIN-CORE-LOCALIZATION-OBSOLETE-L1-3-0.DLL
- API-MS-WIN-CORE-LOCALIZATION-PRIVATE-L1-1-0.DLL
- API-MS-WIN-CORE-MEMORY-L1-1-2.DLL
- API-MS-WIN-CORE-MISC-L1-1-0.DLL
- API-MS-WIN-CORE-NAMEDPIPE-L1-2-0.DLL
- API-MS-WIN-CORE-NAMEDPIPE-L1-2-2.DLL
- API-MS-WIN-CORE-NAMESPACE-L1-1-0.DLL
- API-MS-WIN-CORE-NORMALIZATION-L1-1-0.DLL
- API-MS-WIN-CORE-PERFCOUNTERS-L1-1-0.DLL
- API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL
- API-MS-WIN-CORE-PROCESSENVIRONMENT-L1-2-0.DLL
- API-MS-WIN-CORE-PROCESSSNAPSHOT-L1-1-0.DLL
- API-MS-WIN-CORE-PROCESSTHREADS-L1-1-2.DLL
- API-MS-WIN-CORE-PROCESSTHREADS-L1-1-3.DLL
- API-MS-WIN-CORE-PROCESSTOPOLOGY-L1-2-0.DLL
- API-MS-WIN-CORE-PSAPI-ANSI-L1-1-0.DLL
- API-MS-WIN-CORE-PSAPI-L1-1-0.DLL
- API-MS-WIN-CORE-REALTIME-L1-1-0.DLL
- API-MS-WIN-CORE-REGISTRY-L1-1-0.DLL
- API-MS-WIN-CORE-REGISTRY-L1-1-1.DLL
- API-MS-WIN-CORE-RTLSUPPORT-L1-2-0.DLL
- API-MS-WIN-CORE-SIDEBYSIDE-L1-1-0.DLL
- API-MS-WIN-CORE-STRING-L2-1-0.DLL
- API-MS-WIN-CORE-STRING-OBSOLETE-L1-1-0.DLL
- API-MS-WIN-CORE-STRINGANSI-L1-1-0.DLL
- API-MS-WIN-CORE-SYNCH-L1-2-1.DLL
- API-MS-WIN-CORE-SYSINFO-L1-2-1.DLL
- API-MS-WIN-CORE-SYSINFO-L1-2-3.DLL
- API-MS-WIN-CORE-THREADPOOL-L1-2-0.DLL
- API-MS-WIN-CORE-THREADPOOL-LEGACY-L1-1-0.DLL
- API-MS-WIN-CORE-THREADPOOL-PRIVATE-L1-1-0.DLL
- API-MS-WIN-CORE-WINDOWSERRORREPORTING-L1-1-0.DLL
- API-MS-WIN-CORE-WOW64-L1-1-0.DLL
- API-MS-WIN-CORE-WOW64-L1-1-1.DLL
- API-MS-WIN-CORE-XSTATE-L2-1-0.DLL
- API-MS-WIN-EVENTING-CLASSICPROVIDER-L1-1-0.DLL
- API-MS-WIN-EVENTING-CONSUMER-L1-1-0.DLL
- API-MS-WIN-EVENTING-CONTROLLER-L1-1-0.DLL
- API-MS-WIN-EVENTING-OBSOLETE-L1-1-0.DLL
- API-MS-WIN-EVENTING-PROVIDER-L1-1-0.DLL
- API-MS-WIN-GDI-INTERNAL-UAP-L1-1-0.DLL
- API-MS-WIN-SECURITY-APPCONTAINER-L1-1-0.DLL
- API-MS-WIN-SECURITY-AUDIT-L1-1-1.DLL
- API-MS-WIN-SECURITY-BASE-L1-2-0.DLL
- API-MS-WIN-SECURITY-BASE-PRIVATE-L1-1-1.DLL
- API-MS-WIN-SERVICE-CORE-L1-1-1.DLL
- API-MS-WIN-SERVICE-CORE-L1-1-2.DLL
- API-MS-WIN-SERVICE-MANAGEMENT-L1-1-0.DLL
- API-MS-WIN-SERVICE-MANAGEMENT-L2-1-0.DLL
- API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL
- API-MS-WIN-SERVICE-PRIVATE-L1-1-2.DLL
- API-MS-WIN-SERVICE-WINSVC-L1-2-0.DLL
- API-MS-WIN-CORE-COM-L1-1-1.DLL
- API-MS-WIN-CORE-DELAYLOAD-L1-1-0.DLL
- API-MS-WIN-CORE-IO-L1-1-0.DLL
- API-MS-WIN-CORE-LOCALIZATION-L1-1-0.DLL
- API-MS-WIN-CORE-LOCALREGISTRY-L1-1-0.DLL
- API-MS-WIN-CORE-REGISTRY-PRIVATE-L1-1-0.DLL
- API-MS-WIN-CORE-VERSION-L1-1-0.DLL
- API-MS-WIN-CORE-VERSION-PRIVATE-L1-1-0.DLL
- API-MS-WIN-DEVICES-CONFIG-L1-1-1.DLL
- API-MS-WIN-DEVICES-QUERY-L1-1-1.DLL
- API-MS-WIN-POWER-BASE-L1-1-0.DLL
- API-MS-WIN-POWER-SETTING-L1-1-0.DLL
- API-MS-WIN-SECURITY-CREDENTIALS-L1-1-0.DLL
- API-MS-WIN-SECURITY-CREDENTIALS-L2-1-0.DLL
- API-MS-WIN-SECURITY-GROUPPOLICY-L1-1-0.DLL
- API-MS-WIN-SECURITY-LSALOOKUP-L1-1-1.DLL
- API-MS-WIN-SECURITY-LSALOOKUP-L2-1-1.DLL
- API-MS-WIN-SECURITY-LSAPOLICY-L1-1-0.DLL
- API-MS-WIN-SECURITY-PROVIDER-L1-1-0.DLL
- API-MS-WIN-SECURITY-SDDL-L1-1-0.DLL
- EXT-MS-WIN-ADVAPI32-NPUSERNAME-L1-1-0.DLL
- EXT-MS-WIN-ADVAPI32-NTMARTA-L1-1-0.DLL
- EXT-MS-WIN-ADVAPI32-REGISTRY-L1-1-0.DLL
- EXT-MS-WIN-ADVAPI32-SAFER-L1-1-0.DLL
- EXT-MS-WIN-APPMODEL-DAXCORE-L1-1-0.DLL
- EXT-MS-WIN-APPXDEPLOYMENTCLIENT-APPXDEPLOY-L1-1-0.DLL
- EXT-MS-WIN-APPXDEPLOYMENTCLIENT-APPXDEPLOYONECORE-L1-1-0.DLL
- EXT-MS-WIN-AUTHZ-CONTEXT-L1-1-0.DLL
- EXT-MS-WIN-COM-PSMREGISTER-L1-2-1.DLL
- EXT-MS-WIN-CORE-WINRT-REMOTE-L1-1-0.DLL
- EXT-MS-WIN-EDPUTIL-POLICY-L1-1-0.DLL
- EXT-MS-WIN-EVENTING-RUNDOWN-L1-1-0.DLL
- EXT-MS-WIN-FECLIENT-ENCRYPTEDFILE-L1-1-0.DLL
- EXT-MS-WIN-GDI-CLIPPING-L1-1-0.DLL
- EXT-MS-WIN-GDI-DC-CREATE-L1-1-1.DLL
- EXT-MS-WIN-GDI-DC-L1-2-0.DLL
- EXT-MS-WIN-GDI-DC-L1-2-1.DLL
- EXT-MS-WIN-GDI-DRAW-L1-1-1.DLL
- EXT-MS-WIN-GDI-DRAW-L1-1-3.DLL
- EXT-MS-WIN-GDI-FONT-L1-1-1.DLL
- EXT-MS-WIN-GDI-FONT-L1-1-3.DLL
- EXT-MS-WIN-GDI-INTERNAL-DESKTOP-L1-1-0.DLL
- EXT-MS-WIN-GDI-METAFILE-L1-1-1.DLL
- EXT-MS-WIN-GDI-METAFILE-L1-1-2.DLL
- EXT-MS-WIN-GDI-PATH-L1-1-0.DLL
- EXT-MS-WIN-GDI-PRINT-L1-1-0.DLL
- EXT-MS-WIN-GDI-PRIVATE-L1-1-0.DLL
- EXT-MS-WIN-GDI-WCS-L1-1-0.DLL
- EXT-MS-WIN-GPAPI-GROUPPOLICY-L1-1-0.DLL
- EXT-MS-WIN-KERNEL32-APPCOMPAT-L1-1-0.DLL
- EXT-MS-WIN-KERNEL32-DATETIME-L1-1-0.DLL
- EXT-MS-WIN-KERNEL32-ERRORHANDLING-L1-1-0.DLL
- EXT-MS-WIN-KERNEL32-FILE-L1-1-0.DLL
- EXT-MS-WIN-KERNEL32-QUIRKS-L1-1-0.DLL
- EXT-MS-WIN-KERNEL32-QUIRKS-L1-1-1.DLL
- EXT-MS-WIN-KERNEL32-REGISTRY-L1-1-0.DLL
- EXT-MS-WIN-KERNEL32-SIDEBYSIDE-L1-1-0.DLL
- EXT-MS-WIN-KERNEL32-WINDOWSERRORREPORTING-L1-1-0.DLL
- EXT-MS-WIN-KERNEL32-WINDOWSERRORREPORTING-L1-1-1.DLL
- EXT-MS-WIN-KERNELBASE-PROCESSTHREAD-L1-1-0.DLL
- EXT-MS-WIN-MRMCORER-RESMANAGER-L1-1-0.DLL
- EXT-MS-WIN-NTDSAPI-ACTIVEDIRECTORYCLIENT-L1-1-0.DLL
- EXT-MS-WIN-NTDSAPI-ACTIVEDIRECTORYCLIENT-L1-1-1.DLL
- EXT-MS-WIN-NTUSER-MESSAGE-L1-1-1.DLL
- EXT-MS-WIN-NTUSER-STRING-L1-1-0.DLL
- EXT-MS-WIN-NTUSER-SYNCH-L1-1-0.DLL
- EXT-MS-WIN-NTUSER-WINDOW-L1-1-1.DLL
- EXT-MS-WIN-PROFILE-EXTENDER-L1-1-0.DLL
- EXT-MS-WIN-PROFILE-LOAD-L1-1-0.DLL
- EXT-MS-WIN-RPC-SSL-L1-1-0.DLL
- EXT-MS-WIN-RTCORE-NTUSER-SYSPARAMS-L1-1-0.DLL
- EXT-MS-WIN-RTCORE-NTUSER-WINDOW-EXT-L1-1-0.DLL
- EXT-MS-WIN-SECURITY-CAPAUTHZ-L1-1-0.DLL
- EXT-MS-WIN-SECURITY-CHAMBERS-L1-1-0.DLL
- EXT-MS-WIN-SECURITY-EFSWRT-L1-1-1.DLL
- EXT-MS-WIN-SHELL32-SHELLCOM-L1-1-0.DLL

While all of the following are in x64:

- c:\windows\system32\ADVAPI32.DLL
- c:\windows\system32\GDI32.DLL
- c:\windows\system32\KERNEL32.DLL
- c:\windows\system32\KERNELBASE.DLL
- c:\windows\system32\MSVCR100.DLL
- c:\windows\system32\MSVCRT.DLL
- c:\windows\system32\NTDLL.DLL
- c:\windows\system32\PTHREADVC2.DLL
- c:\windows\system32\RPCRT4.DLL
- c:\windows\system32\SECHOST.DLL
- c:\windows\system32\USER32.DLL
- c:\windows\system32\WIN32U.DLL
- c:\windows\system32\WS2_32.DLL
- c:\windows\system32\BCRYPT.DLL
- c:\windows\system32\BCRYPTPRIMITIVES.DLL
- c:\windows\system32\CABINET.DLL
- c:\windows\system32\CFGMGR32.DLL
- c:\windows\system32\CRYPT32.DLL
- c:\windows\system32\CRYPTBASE.DLL
- c:\windows\system32\CRYPTSP.DLL
- c:\windows\system32\DBGHELP.DLL
- c:\windows\system32\DEVOBJ.DLL
- c:\windows\system32\DEVRTL.DLL
- c:\windows\system32\DHCPCSVC.DLL
- c:\windows\system32\DHCPCSVC6.DLL
- c:\windows\system32\DNSAPI.DLL
- c:\windows\system32\DPAPI.DLL
- c:\windows\system32\DSPARSE.DLL
- c:\windows\system32\IMAGEHLP.DLL
- c:\windows\system32\IPHLPAPI.DLL
- c:\windows\system32\MSASN1.DLL
- c:\windows\system32\MSIMG32.DLL
- c:\windows\system32\NCRYPT.DLL
- c:\windows\system32\NSI.DLL
- c:\windows\system32\NTASN1.DLL
- c:\windows\system32\PROFAPI.DLL
- c:\windows\system32\SAMLIB.DLL
- c:\windows\system32\SSPICLI.DLL
- c:\windows\system32\WINNSI.DLL
- c:\windows\system32\WINSTA.DLL
- c:\windows\system32\WINTRUST.DLL

The only ones in x86 are the last ones, the ones most readily associated with mosquitto:
- LIBEAY32.DLL
- MOSQUITTO.DLL
- MOSQUITTO_PUB.EXE
- MSVCR120.DLL
- SSLEAY32.DLL

Update: The version of pthreads that the guide I mentioned linked me to is x64. Manually getting the x86 version of pthreadVC2.dll from [here](ftp://sourceware.org/pub/pthreads-win32/dll-latest/dll/x86/) solved the issue. There are still apparently some dependency issues when running it with the walker, but at least this is out of the way. It's not the cleanest solution, but it works.

**Comment by alexschwantes** [comment]
hmm I'm having the same issue.. even though I have the x86 version of pthreadVC2.dll. Just can't seem to get it working and it just throws a the 0xc000007b exception.. Quite frustrating that there is no complete install package.

**Comment by kekemuyu** [comment]
I have the same issue too on win7 64-bit.

**Comment by jimdgit** [comment]
As am I. Win 7 64 bit OS
Problem Event Name:	BEX
  Application Name:	mosquitto_sub.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5757fb53
  Fault Module Name:	MSVCR120.dll
  Fault Module Version:	12.0.21005.1
  Fault Module Timestamp:	524f7ce6
  Exception Offset:	000a46bb
  Exception Code:	c0000417
  Exception Data:	00000000
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0798
  Additional Information 2:	07983c3f1ad1e1c7f1099b61a62a242a
  Additional Information 3:	f453
  Additional Information 4:	f453b7c9096536239d561fe2cceb4e80
