### ISSUE TITLE
Bridge mode for multiple brokers

### ISSUE THREAD

**Issue by rokka-n** [eclipse/mosquitto#348]
Hi,

What does this mean?
`Bridges cannot currently be reloaded on reload signal`

**Comment by ralight** [comment]
It means that bridge configuration isn't reloaded by the broker when you send a SIGHUP signal. If you want to update your bridge configuration you need to restart the broker.

**Comment by rokka-n** [comment]
Thank you, that's what I thought.

Do you see obvious problems with the design below? I'm considering to use few brokers are "routers" in bridge mode for publishing to IoT devices. ELB/haproxy 

Of course the limitation is that a single broker performance becomes bottleneck, since publishing topics being copied to all "front-end" brokers.

```
                      ELB/haproxy
              out.mqtt.blahservices.com
                |                 |
           +----+----+       +----+----+
           | broker1 |       | broker2 |
           +----+----+       +----+----+
                |bridge           |bridge  
                |                 |
       +--------+----+------------+---+ 
       |             |                |
  +----+-----+  +----+-----+   +------+---+
  | broker_1 |  | broker_2 |   | broker_x |
  +----------+  +----------+   +----------+
```

**Comment by PierreF** [comment]
Closing as there is no issue.
To get feedback on your architecture design, I suggest you to ask in the Mosquitto mailing-list (https://dev.eclipse.org/mailman/listinfo/mosquitto-dev) where you will reach a larger audience.
