### ISSUE TITLE
dynamic add userName or ClientID

### ISSUE THREAD

**Issue by lewis081** [eclipse/mosquitto#350]
Dear Author:
        I have used mosqitto for a servel of days. 
        Howerver, i did't find a way to solve my problem that I want to use mosqitto server to authenticate user Dynamically. 
        Now, i just know that i need restart server if i want to load updated passwordfile.But, the result is many clients message will loss if i restart server.Therefore, i want to load passwordfile when the server is running.
        Can you give me some tips? Thanks a lot.

**Comment by ralight** [comment]
For the moment the best option is to use a plugin like mosquitto_auth_plugin.

**Comment by PierreF** [comment]
As suggested https://github.com/jpmens/mosquitto-auth-plug/ is probably the best solution.
It is also possible to avoid *restarting* the server but only reloading the configuration by sending a SIGHUP to the mosquitto process. http://mosquitto.org/man/mosquitto-conf-5.html list option that are reloaded, content of password_file is reloaded.
