### ISSUE TITLE
Allow auth plugins to inspect ClientId at login

### ISSUE THREAD

**Issue by brandond** [eclipse/mosquitto#351]
It would be nice if mosquitto_auth_unpwd_check was also passed the ClientId so that it could allow or reject it. Might also be a good extension point to allow the auth back-end to generate or look up a ClientId if one was not provided by the client.

This would probably either require calling mosquitto_auth_unpwd_check for anonymous connections (which I do not believe is currently done), or requiring plugins to provide a new hook for ClientId validation.

Downstream issue: https://github.com/jpmens/mosquitto-auth-plug/issues/192

> If the Server rejects the ClientId it MUST respond to the CONNECT Packet with a CONNACK return code 0x02 (Identifier rejected) and then close the Network Connection [MQTT-3.1.3-9].

**Comment by ralight** [comment]
This is already partially implemented - `const char *mosquitto_client_id()` in the develop branch. I'm leaving this issue open because you can't reject the client id as such at the moment.

**Comment by generalmarty** [comment]
👍 

With current implementation, client ID cannot be trusted.

**Comment by ralight** [comment]
You can now see the client ID in authentication plugins.
