### ISSUE TITLE
feature suggestion

### ISSUE THREAD

**Issue by sonyangchang** [eclipse/mosquitto#352]
In my opinion, the mosquitto project would make great progress if it has the following features:
1. cluster supporting, like DHT.
2. better memory allocation and management, say,mbuf.
3.clients can transmit data in p2p mode.
Just some self opinions for reference.

**Comment by cordovapolymer** [comment]
1. Bridges are supported
2. That could be implemented if someone invests his time into that! 
3. clients can transmit data in p2p mode.
Although its a great idea, p2p isn't implemented in the MQTT protocol.

**Comment by ralight** [comment]
Thanks for the suggestions, clustering is intended but isn't on the immediate roadmap so I am closing this for now.
