### ISSUE TITLE
Websocket support on Alpine or any light weight linux distro

### ISSUE THREAD

**Issue by vivek1729** [eclipse/mosquitto#353]
Absolutely love it that you guys have created a docker file with alpine base image. I am also playing around with an mosquitto broker at work and would really want to base it off of alpine. Is it possible to enable websocket support on alpine or build it from source with this option?

Any help on running mosquitto broker on a lightweight distro like alpine is really appreciated!

**Comment by ralight** [comment]
I'm relying on other people for docker support - is there support for libwebsockets in alpine already?

**Comment by fablec-telecomsante** [comment]
Hi,

There is a great docker implementation of mosquitto over alpine, with websocket support

 - [jllopis/mosquitto](https://hub.docker.com/r/jllopis/mosquitto/)

**Comment by vivek1729** [comment]
@fablec-telecomsante Thanks a lot for pointing that out! It got me started in the right direction :)
