### ISSUE TITLE
Which version of libwebsockets is compatible with mosquitto 1.4.10

### ISSUE THREAD

**Issue by daun8928** [eclipse/mosquitto#356]
I'm using raspberry pi 3 and

I want to build mosquitto with WITH_WEBSOCKETS:=yes option.

I already installed libwebsockets from here: https://github.com/warmcat/libwebsockets
'git clone' and 'cmake'. It was fine.

But when I try to build mosquitto 1.4.10 it keeps showing error message.
I just used 'make' command.

error is like this:

mosquitto.o: In function 'main':
... undefined reference to 'lws_context_destroy'
... undefined reference to 'lws_service'
blah blah blah

Is the version of libwebsockets is a problem?

Thank you.

**Comment by ralight** [comment]
2.0.x definitely works, I've not yet tried 2.1. Using unreleased versions is a bad idea...

The function you're missing should exist in the git cloned version though, are you sure it isn't trying to link against a different version installed on your system?

**Comment by daun8928** [comment]
Thank you so much ralight!
I'll check it out.
Maybe rasp has different version's file of libwebsockets.
Thanks!
