### ISSUE TITLE
Mosquitto power issues

### ISSUE THREAD

**Issue by bachoo786** [eclipse/mosquitto#358]
Hi

I have mosquitto installed on my raspberry pi and have a esp8266 client connected to it. Whenever I restart my pi the esp8266 disconnect's and fails to connect back even if the mosquitto (pi) is up and running until I reboot the esp8266 and then it would connect back.

Can anyone please help on this issue?

Thanks.

**Comment by ralight** [comment]
Sorry but this sounds like the problem is with your esp8266 not reconnecting properly, not with mosquitto. Have you tried the support for whatever client you are using?
