### ISSUE TITLE
Success on Rpi3, Raspbian, Mosquitto & Websocket

### ISSUE THREAD

**Issue by daun8928** [eclipse/mosquitto#359]
I failed so many trials, but at last I succeed on this tutorial: https://www.element14.com/community/community/design-challenges/sci-fi-your-pi/blog/2015/06/22/pizzapi-mosquitto-websockets-success-tutorial

other versions of libwebsockets and mosquitto didn't worked on raspbian...
I don't know why.

I just make note here for people who are trying to setup mosquitto on their own Rpi.

**Comment by ralight** [comment]
Glad you got it working.

libwebsockets 2.1.0 seems to be buggy, 2.0.3 should be fine though. I'm closing this because you've got it fixed, others will still be able to find it in search results.
