### ISSUE TITLE
Can the clients be added to the Docker image?

### ISSUE THREAD

**Issue by jdiamond** [eclipse/mosquitto#364]
Most of the official Docker images containing servers (postgres, mysql, redis, mongo, etc) have the CLI tools installed in them.

It looks like it'd only require adding just one line to the Dockerfile. I can send a PR if you like.

**Comment by ralight** [comment]
Yes please, just open a PR.

**Comment by jdiamond** [comment]
I'm not signing the CLA so somebody else should do it.

**Comment by ralight** [comment]
Just going through old issues, the clients are part of the docker image so I'm closing this.
