### ISSUE TITLE
Building Mosquitto: "libc-ares2-dev" dependency

### ISSUE THREAD

**Issue by stefanoco** [eclipse/mosquitto#370]
While building Mosquitto with `make biinary`out of cloned repository I realized that the requested `libc-ares2-dev`does not exist on Ubuntu (it seems to me that it doesn't exist at all, no reference searching with Google). I ended up installing `libc-ares2` and `libc-ares-dev` and it builds, from its description `libc-ares-dev` is header/static libs for `libc-ares2`. Is this correct?

**Comment by ralight** [comment]
Yes you're right, the build dependency is `libc-ares-dev` which will also pull in `libc-ares2` if you don't already have it installed. I've fixed the readme.
