### ISSUE TITLE
Disconnects all my clients suddenly -> Warning: Received PUBREL from <client-id> for an unknown packet identifier 247.

### ISSUE THREAD

**Issue by DavidMont** [eclipse/mosquitto#374]
```
Warning: Received PUBREL from 14444141 for an unknown packet identifier 247.
Socket error on client <unknown>, disconnecting.
```
Setup
A-Broker 

```
max_inflight_messages 50000
max_queued_messages 10000
port 1883
persistence true
persistence_file mosquitto.db
persistence_location /var/lib/mosquitto/
log_dest syslog
log_dest stdout
log_dest topic
log_dest stderr
connection_messages true
log_timestamp true
allow_anonymous true
log_timestamp true
# bridge
connection ToMQTTClassic123
address <ip>:1883
start_type automatic
topic # both 2 SAMPLE/ SAMPLE/
```

How do mitigate this issue, my broker seems to disconnects its clients suddenly I dont know why?

Im currently using mqtt v 1.4.10 for the broker
And currently using mqtt v1.1.0 for the client paho

**Comment by ralight** [comment]
It sounds more likely that your clients are misbehaving. What client are you using? Can you check with mosquitto_sub instead/as well?

**Comment by DavidMont** [comment]
what do you mean by misbehaving?
Im currently using paho for client in all of our android apps.

**Comment by ralight** [comment]
I mean that if your clients are written incorrectly and not sending a PINGREQ frequently enough then the broker will disconnect them. Likewise, if the client reconnects and sends a "bad" PUBREL then there is a chance the problem is at the client, not the broker. If you can test with something known to be good - mosquitto_sub - then you can determine whether the problem is actually the broker or your client.

**Comment by DavidMont** [comment]
Actually I upgraded from 1.4.8 to 1.4.10 while clients are still connected then this error message happens. It seems like that those clients are connected to 1.4.8 then when i upgraded it, i think it loses its tracks. correct me if wrong. 

tried pub/sub using mqtt tool or should i use command mosquitto_sub?

**Comment by DavidMont** [comment]
Just now i saw `Socket error on client local.ip-local.ToMQTTClassic123, disconnecting.` on our third server, we have deployed 2 and we have existing 1. The question I posted was for the 2nd server that we will be migrating to 3rd server with the same configuration files from 2nd server.

Is this something I should be worry about?

**Comment by ralight** [comment]
Ah, so if there was a problem with your persistence file it would cause the broker to lose track of in-progress messages, yes. That's a definite possibility. If you upgraded your broker then presumably you stopped the broker as part of that upgrade - are the clients now suddenly disconnecting after the upgrade? I mean is it an ongoing problem or did it "just" happen at the upgrade?

**Comment by spurdow** [comment]
Well actually it was happening before we really didnt know the cause, and then there was an issue in 1.4.8 so we thought that upgrading to 1.4.10 would fix it now we only introduced another side effects. But is it possible if we migrate our domain to point to another broker that is a new broker would it fix it?

**Comment by spurdow** [comment]
I just want to ask another question what is the maximum length of client id? Is it max value of integer?

**Comment by ralight** [comment]
Maximum client id is 65535 characters - I wouldn't recommend that size though.

It's impossible to say where the problem lies with the information that you've provided I'm afraid.

**Comment by DavidMont** [comment]
I happened to scroll the logs and found out this

```
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
1486567635: Error: No space left on device.
```

what does this mean? I still have 5 GB of hard disk

**Comment by DavidMont** [comment]
we have successfully migrated our broker to a new one. We have no issues for now. But there is still logs showing `Socket error on client 144444331, disconnecting.`

Also the disconnect problem also happens with the mqtt tool jar. I have seen that the MqttUtility client is from mqtt_tool and its been logging in as socket error same as above message in the defective broker.

**Comment by DavidMont** [comment]
I just want to know if there is a way i could remove all those clients that are connected from the broker and start as clean? im sorry I forgot that all our clients used QOS 2 does this help?

**Comment by DavidMont** [comment]
@ralight  is there a way i can remove all pack identifier for these current client id or all of them for me its ok to remove them because we have our own offline mechanism workflow.

**Comment by ralight** [comment]
Do you definitely have space left on the partition where your persistence file is being written?

**Comment by spurdow** [comment]
@ralight may i know what causes the ram not to go back down? I observed using htop that the ram didnt decrease even though the cpu processing is less than 10% and still the ram stays put for example now is 600mb. and when i restart mosquitto it goes back to 99mb.

**Comment by DavidMont** [comment]
I finally found the issue, its not the error by unknown packet but its one of the reasons. 

below is the responsible for such high cpu usage and ram
```
max_inflight_messages 50000
max_queued_messages 10000
```
plus the client has inflight to 1000 so the server is overloaded by these settings.

**Comment by karlp** [comment]
max queued can be pretty high, that's no problem, I think it's 600000 on one machine I have.  but yeah, max_inflight at 50k will _seriously_ be churning.  The only motivation for such a high inflight number would be for a very high bandwidth, high latency link.  (or moderate bandwidth, but extreme latency)

If you have a "laggy" connection but with "decent" bandwidth, I can't imagine you'd ever need to turn max inflight much over 500, even for very high message rates.

**Comment by ralight** [comment]
@spurdow Observe what happens in htop at the various points in this program for your answer:

https://gist.github.com/ralight/4f80e8717a73748dcaf3aecba2348189
