### ISSUE TITLE
Is it possible to customize mosquitto.c? 

### ISSUE THREAD

**Issue by candemiralp** [eclipse/mosquitto#377]
I'm trying to implement some scenarios after a message reaches to broker immediately. Where can I insert my code that will be executed after a message is received by broker?

**Comment by ralight** [comment]
If you mean a publish message, then try read_handle.c mqtt3_handle_publish().

Perhaps better might be when the message is due to be released to subscribers - that happens in subs.c mqtt3_db_messages_queue().

**Comment by candemiralp** [comment]
Hi, thank you both options are suitable for me.
