### ISSUE TITLE
Remote notifications

### ISSUE THREAD

**Issue by mvorisis** [eclipse/mosquitto#381]
Hi 

I'm trying to implement push notifications to my app that uses mqtt and as I was reading the [documentation](https://mosquitto.org/man/mosquitto_sub-1.html) I found this line that I believe that is the key for this : --will-payload, First of all what file should I edit to put this (maybe mosquitto_sub.1.xml) ?
Anyone who can guide me?

Thanks in advance

**Comment by ralight** [comment]
I'm not quite sure what you're asking. ``--will-payload` is already described in the mosquitto_sub man page.
