### ISSUE TITLE
Static build

### ISSUE THREAD

**Issue by potan** [eclipse/mosquitto#382]
Make static distributive for windows, please.

**Comment by stryku** [comment]
Static build is avaliable on the `develop` branch (:

**Comment by yoonghm** [comment]
I would like to have a statically build mosquitto in Ubuntu, I did this 
```
make  CFLAGS+="-static"   LDFLAGS+="-static"
```

The Makefile is configured to build using shared library libmosquitto.so.1`.  So I have the following messages:

```
cc -shared -static -Wl,--version-script=linker.version -Wl,-soname,libmosquitto.so.1 mosquitto.o actions.o callbacks.o connect.o handle_connack.o handle_ping.o handle_pubackcomp.o handle_publish.o handle_pubrec.o handle_pubrel.o handle_suback.o handle_unsuback.o helpers.o logging_mosq.o loop.o memory_mosq.o messages_mosq.o net_mosq.o options.o packet_mosq.o read_handle.o send_connect.o send_disconnect.o send_mosq.o send_publish.o send_subscribe.o send_unsubscribe.o socks_mosq.o srv_mosq.o thread_mosq.o time_mosq.o tls_mosq.o utf8_mosq.o util_mosq.o will_mosq.o -o libmosquitto.so.1  -lrt -lssl -lcrypto -lpthread -lcares
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginT.o: relocation R_X86_64_32 against hidden symbol `__TMC_END__' can not be used when making a shared object
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:77: recipe for target 'libmosquitto.so.1' failed
make[1]: *** [libmosquitto.so.1] Error 1
make[1]: Leaving directory '/home/s/src/mosquitto-1.5.3/lib'
Makefile:26: recipe for target 'mosquitto' failed
make: *** [mosquitto] Error 2
```

Any possibility to do that?

**Comment by ralight** [comment]
Please try `make WITH_STATIC_LIBRARIES=yes`, that gives you `libmosquitto.a`.

**Comment by yoonghm** [comment]
Hi,

make prefix=/home/s \
>      WITH_WEBSOCKETS=yes \
>      WITH_SRV=yes \
>      WITH_TLS=yes \
>      WITH_UUID=yes \
>      WITH_DOCS=yes \
>      CFLAGS+="-static" \
>      LDFLAGS+="-static" \
>      WITH_STATIC_LIBRARIES=yes
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c mosquitto.c -o mosquitto.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c actions.c -o actions.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c callbacks.c -o callbacks.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c connect.c -o connect.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c handle_connack.c -o
handle_connack.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c handle_ping.c -o handle_ping.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c handle_pubackcomp.c -o
handle_pubackcomp.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c handle_publish.c -o
handle_publish.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c handle_pubrec.c -o
handle_pubrec.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c handle_pubrel.c -o
handle_pubrel.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c handle_suback.c -o
handle_suback.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c handle_unsuback.c -o
handle_unsuback.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c helpers.c -o helpers.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c logging_mosq.c -o logging_mosq.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c loop.c -o loop.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c memory_mosq.c -o memory_mosq.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c messages_mosq.c -o
messages_mosq.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c net_mosq.c -o net_mosq.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c options.c -o options.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c packet_mosq.c -o packet_mosq.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c read_handle.c -o read_handle.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c send_connect.c -o send_connect.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c send_disconnect.c -o
send_disconnect.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c send_mosq.c -o send_mosq.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c send_publish.c -o send_publish.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c send_subscribe.c -o
send_subscribe.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c send_unsubscribe.c -o
send_unsubscribe.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c socks_mosq.c -o socks_mosq.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c srv_mosq.c -o srv_mosq.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c thread_mosq.c -o thread_mosq.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c time_mosq.c -o time_mosq.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c tls_mosq.c -o tls_mosq.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c utf8_mosq.c -o utf8_mosq.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c util_mosq.c -o util_mosq.o
cc -static  -I. -I.. -I../lib -fPIC -DWITH_TLS -DWITH_TLS_PSK
-DWITH_THREADING -DWITH_SOCKS -DWITH_SRV -c will_mosq.c -o will_mosq.o
cc -shared -static -Wl,--version-script=linker.version
-Wl,-soname,libmosquitto.so.1 mosquitto.o actions.o callbacks.o connect.o
handle_connack.o handle_ping.o handle_pubackcomp.o handle_publish.o
handle_pubrec.o handle_pubrel.o handle_suback.o handle_unsuback.o helpers.o
logging_mosq.o loop.o memory_mosq.o messages_mosq.o net_mosq.o options.o
packet_mosq.o read_handle.o send_connect.o send_disconnect.o send_mosq.o
send_publish.o send_subscribe.o send_unsubscribe.o socks_mosq.o srv_mosq.o
thread_mosq.o time_mosq.o tls_mosq.o utf8_mosq.o util_mosq.o will_mosq.o -o
libmosquitto.so.1  -lrt -lssl -lcrypto -lpthread -lcares
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginT.o: relocation
R_X86_64_32 against hidden symbol `__TMC_END__' can not be used when making
a shared object
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:77: recipe for target 'libmosquitto.so.1' failed
make: *** [libmosquitto.so.1] Error 1


It still try to generate libmosquitto.so.1.

**Comment by karlp** [comment]
Why are you trying to modify cflags and ldflags when you are using the WITH_STATIC_LIBRARIES configuration? You're almost definitely breaking the code where it builds shared libraries too.

**Comment by ralight** [comment]
Indeed, don't pass `-static` yourself and it should work fine. If you don't want the shared libraries at all, use `WITH_SHARED_LIBRARIES=no`.

**Comment by ralight** [comment]
I'm going to close this because I think the original and new issue are fixed, if there is still a problem please reopen and provide more details.
