### ISSUE TITLE
Broker fails to store QoS1 message for persistent client after restart

### ISSUE THREAD

**Issue by codami** [eclipse/mosquitto#384]
My setup:
Broker: with persistence enabled (mosquitto.db)
Client1: non persistent (publisher that follows the ACL pattern - see below)
Client2: persistent (subscriber that authenticates as "superuser")
ACL file:
```
user superuser
topic readwrite #

pattern readwrite %u/%c/#
```
Scenario:
1. Start Broker
2. Client2 connects as "superuser" and subscribes successfully for "+/+/status" topic with QoS2
3. Stop Broker
4. Start Broker
5. Client1 connects and publishes for "User1/Client1/status" topic a message with QoS1
6. Client2 connects and subscribes again as before

In this case Client2 should receive the message Client1 sent as soon as it subscribes, but it doesn't.

After some debugging I've got to the point where the ACL check fails. It never gets through [this loop](https://github.com/eclipse/mosquitto/blob/master/src/security_default.c#L245).
I believe the ACL check would have worked for a user subject to the ACL pattern, because these patterns are checked later in the [next loop](https://github.com/eclipse/mosquitto/blob/master/src/security_default.c#L266).

**Comment by codami** [comment]
As suspected, new tests show that the ACL check fails only for user definitions and works fine for ACL patterns.

**Comment by ralight** [comment]
The "problem" here is that persisted clients don't have the username they connected with saved to the persistence db (the rationale being that the messages are associated with a client id and the username may change on reconnection). That would need changing to fix this.

**Comment by codami** [comment]
Following the same rationale would mean that in this scenario (without Broker restart):
1. Start Broker
2. Client2 connects and subscribes
3. Client2 disconnects
4. Client1 connects and publishes
5. Client 2 reconnects

the Broker should also not store any message for Client2 while disconnected.
In my tests it does store them and moreover it uses the username from Client2's previous connection.
Consequently Client2 might loose messages when it connects with a different username. 

For me it looks like the "ACL check" step happens too early in the publishing process.
It should be postponed until it has enough info to decide. The Broker could filter messages once Client2 connects and the username is known.

Thank you for looking into this issue!

**Comment by codami** [comment]
[This](https://github.com/codami/mosquitto/commit/d82e5874caecaf071f238699fb784ba4c6b9b415) is a change that worked for me in both scenarios. Do you see any problems with this kind of solution?

**Comment by ralight** [comment]
This should now be fixed in the fixes branch.
