### ISSUE TITLE
mosquitto.log higher than 236 MB

### ISSUE THREAD

**Issue by FernandoGarcia** [eclipse/mosquitto#385]
Hi!

Actually my mosquito.log has more than 236 MB I would like to know if there a way to limit the size in 50 MB.

The first data on LOG was 20/11/2016 it's long time to me.

Moreover is hard to browse this big file.

Best regards.

**Comment by ralight** [comment]
Assuming you're logging with `log_dest file`, then if you send a `SIGHUP` to the broker then it will close and reopen the log file. This allows you to use something like [logrotate](http://www.linuxcommand.org/man_pages/logrotate8.html) to move the log file out of the way, then start a new log file.

**Comment by FernandoGarcia** [comment]
Thanks for fast reply!

I found this example to be placed in /etc/logrotate.d/mosquitto.

Seems right for you?

```
    /var/log/mosquitto/mosquitto.log {
            rotate 7
            daily
            compress
            size 100k
            nocreate
            missingok
            postrotate
                    /usr/bin/killall -HUP mosquitto
            endscript
    }
```

Source: https://www.raspberrypi.org/forums/viewtopic.php?t=158985&p=1033031

**Comment by FernandoGarcia** [comment]
In my case the path is /var/log/mosquitto.log

**Comment by ralight** [comment]
That does look fine - you'll get 7 days of old logs. Something to bear in mind, if mosquitto can't create /var/log/mosquitto.log for reasons of permissions, then the logrotation would fail. That's the primary reason for using /var/log/mosquitto/ - you can give permission to just that directory to the mosquitto user.

**Comment by FernandoGarcia** [comment]
Worked like a charm!
Thank you very much.

**Comment by ralight** [comment]
Glad to hear it :)
