### ISSUE TITLE
Mosquitto from the Ubuntu PPA not installable on Ubuntu 16.04

### ISSUE THREAD

**Issue by chilicheech** [eclipse/mosquitto#387]
On a fresh install of Ubuntu 16.04, mosquitto from the PPA linked from the download page will not install. apt-get returns: mosquitto : Depends: libwebsockets3 (>= 1.2) but it is not installable. This is similar to #264 that happened with mosquitto-1.4.10, but it's now happening with mosquitto-1.4.11. Package mosquitto-1.4.10 is not available in the repo so I can't install the older version.

Please see the current config and full output:
```
root@1c20e73706b4:~# apt-cache policy mosquitto
mosquitto:
  Installed: (none)
  Candidate: 1.4.11-0mosquitto1
  Version table:
     1.4.11-0mosquitto1 500
        500 http://repo.mosquitto.org/debian jessie/main armhf Packages
     1.4.8-1build1 500
        500 http://ports.ubuntu.com/ubuntu-ports xenial/universe armhf Packages
root@1c20e73706b4:~#

root@1c20e73706b4:~# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
root@1c20e73706b4:~#

root@1c20e73706b4:~# apt-get install mosquitto
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mosquitto : Depends: libwebsockets3 (>= 1.2) but it is not installable
E: Unable to correct problems, you have held broken packages.
root@1c20e73706b4:~#

root@1c20e73706b4:~# apt-cache policy libwebsockets3
libwebsockets3:
  Installed: (none)
  Candidate: (none)
  Version table:
root@1c20e73706b4:~#

root@1c20e73706b4:~# apt-cache policy libwebsockets7
libwebsockets7:
  Installed: (none)
  Candidate: 1.7.1-1
  Version table:
     1.7.1-1 500
        500 http://ports.ubuntu.com/ubuntu-ports xenial/universe armhf Packages
root@1c20e73706b4:~#
```
(I have not held any packages)

[libwebsockets3 is not available in 16.04](http://packages.ubuntu.com/search?keywords=libwebsockets3) and the [distro version is built against libwebsockets7](distro version is built against libwebsockets7).

Therefore, currently one cannot use the PPA version, which is newer than the version in universe.

**Comment by ralight** [comment]
>      1.4.11-0mosquitto1 500
>         500 http://repo.mosquitto.org/debian jessie/main armhf Packages
>      1.4.8-1build1 500
>         500 http://ports.ubuntu.com/ubuntu-ports xenial/universe armhf Packages
> 

It looks like you're trying to install packages for Debian Jessie on to Ubuntu Xenial which would explain the difference. You should try use the Ubuntu packages instead:

https://launchpad.net/~mosquitto-dev/+archive/ubuntu/mosquitto-ppa

There are release specific uploads for each of the current Ubuntu releases so there shouldn't be any problems with them.

**Comment by chilicheech** [comment]
Whoops, my bad. Thanks for the clarification.
