### ISSUE TITLE
Moving apt to snap repository

### ISSUE THREAD

**Issue by sreeisalso** [eclipse/mosquitto#388]
Hi,

IMHO moving to snap repository will eliminate all the problems faced by other developers regarding compilation and package versions mismatch(specially opensll). Also user can get the latest stable version without wait for Ubuntu to release.

Thanks and regards
Sreekanth

**Comment by ralight** [comment]
I disagree with your rationale - developers wanting to compile things won't be using snaps. End users can get the latest version from the ppa.

Having said that, there has been a snap package available for months now :)

https://myapps.developer.ubuntu.com/dev/click-apps/5924/

**Comment by ralight** [comment]
I'm closing this because I think it's already fixed.
