### ISSUE TITLE
Unexpected growth in the .db file

### ISSUE THREAD

**Issue by ashishbajaj99** [eclipse/mosquitto#389]
I have a broker configured with the following settings:

```
<snip>
persistence true
<snip>
```

Further I have a phone client that connects over websocket interface with a fixed unchanged clientid each time, and sets up its cleanSessionFlag to true, so its not a persistent session.

But after every such connection and disconnection, I see the mosquitto.db file growing. On opening the db file in an editor, I see multiple sections of data for each of the connections.

But if the cleanSessionFlag is set to false, the file doesn't grow - there is only one instance of the clientid maintained. But as expected I do receive all the QoS 1 and QoS2 retained messages that I may have missed during the time I didn't have connection. I dont want any of those messages delivered to the client, which is why I changed my client to connect using cleanSessionFlag to false.

This is not something expected right? I am on mosquitto 1.4.10...is there any known issue?

Let me know if you need any logs?

**Comment by ralight** [comment]
The first thing to look at would be what is actually in the persistence file - you could use the mosquitto_db_dump to take a look: https://github.com/eclipse/mosquitto/tree/master/src/db_dump

It might require some fiddling with the db_dump source to find out exactly what is happening.

**Comment by PierreF** [comment]
Do you still experience this issue ?

**Comment by ashishbajaj99** [comment]
Yes, sorry I haven't analysed it yet. Will do so and send you something over the next two weeks. Is that Okay? Sorry lots of other priorities on going at the moment.
________________________________

**Comment by pjchx** [comment]
Hi, I am having similar issue. The db file is growing quickly, I have to manualy delete it every 7-10 days.
Can't install the db analyser log (my linux version is too old for it I think), but looking into raw db I see nothing suspicious - just a large log of my usual mqtt traffic in it.
I had this setup operating for about a year, but this problem started to appear cca 2 months back.
Any hint what I should be looking for in the db file to find the root cause ?

**Comment by karlp** [comment]
try harder to compile the db dump tools.  You probably have a persistent client with a subscripion thhat you didn't intend.  An option that can be very useful to aovid this is ```persistent_client_expiration``` set to say, 7d or similar, or whatever's appropriate for your environment.  THe MQTT spec itself unfortunately says that by default messages are stored infinitely.

**Comment by ralight** [comment]
@pjchx Try the following:

```
git clone https://github.com/eclipse/mosquitto
cd mosquitto
git checkout v1.4.15
cd src/db_dump
make
```
If you have errors, report them here and we'll help - but try and install missing tools first if you can.
This should give you mosquitto_db_dump, which you could then run as `./mosquitto_db_dump --stats <path/to/mosquitto.db>` and post the output here.

**Comment by pjchx** [comment]
hi, I managed somehow to compile on rPi running Jessie. The another rPi running Wheezy (and mosquitto client) compilation did not work. 

Now the dump tool is working. However I deleted the big file yesterday so I have to wait until it builds up again in few days. Then I will analyse.Thanks for the help so far.

p.s.
btw, when compiling on Jessie I had to fix this in db_dump source code:

line 192      for(int i=0; i<msg->payloadlen; i++)

I moved the the i variable definition before the loop.

**Comment by ralight** [comment]
Actually I may have isolated the problem. If you're comfortable with compiling the whole mosquitto source, then try:

```
git clone https://github.com/eclipse/mosquitto
cd mosquitto
git checkout fixes
make
```

If you need websockets, then run `make WITH_WEBSOCKETS=yes` instead. Then run mosquitto from the src directory with your config file.

**Comment by pjchx** [comment]
Hi, my file has just grown again to 230MB
the db_dump says this : 

_root@xxx:/opt/mosquitto-master/src/db_dump# ./mosquitto_db_dump --stats mosquitto.db
DB_CHUNK_CFG:        1
DB_CHUNK_MSG_STORE:  2884449
DB_CHUNK_CLIENT_MSG: 0
DB_CHUNK_RETAIN:     270
DB_CHUNK_SUB:        0
DB_CHUNK_CLIENT:     0_

on --client.stats parameter 
root@xxx:/opt/mosquitto-master/src/db_dump# ./mosquitto_db_dump --client-stats mosquitto.db
root@xxx:/opt/mosquitto-master/src/db_dump# 

...it returns nothing.

any idea what may be wrong ?

**Comment by pjchx** [comment]
...one more thing. 

> Actually I may have isolated the problem. If you're comfortable with compiling the whole mosquitto source, then try:
> 
> ```
> git clone https://github.com/eclipse/mosquitto
> cd mosquitto
> git checkout fixes
> make
> ```
> If you need websockets, then run `make WITH_WEBSOCKETS=yes` instead. Then run mosquitto from the src directory with your config file.

I tried to compile on my Wheezy but no luck:

```
> cc sub_client.o sub_client_output.o client_shared.o -o mosquitto_sub  -L../lib ../lib/libmosquitto.so.1
> /usr/bin/ld: sub_client_output.o: undefined reference to symbol 'clock_gettime@@GLIBC_2.4'
> //lib/arm-linux-gnueabihf/librt.so.1: error adding symbols: DSO missing from command line
> collect2: ld returned 1 exit status
> Makefile:33: recipe for target 'mosquitto_sub' failed
> make[1]: *** [mosquitto_sub] Error 1
> make[1]: Leaving directory '/tmp/mosquitto/client'
> Makefile:26: recipe for target 'mosquitto' failed
> make: *** [mosquitto] Error 2
```

**Comment by ralight** [comment]
The problem isn't an append, it is that in some circumstances some messages were being persisted even when they weren't in use, and then never being freed. This is fixed in the latest release.

I'm sorry, but wheezy is about 9 months past its end of life, it's not supported by Debian and not supported by the Mosquitto project either. Having said that, if you just want the broker then try:

```
make -C src
sudo make -C src install
```

This will build just the broker, which should be ok I think.
