### ISSUE TITLE
can mosquitto publish message over websocket?

### ISSUE THREAD

**Issue by eduard739** [eclipse/mosquitto#391]
first of all, i did make of mosquitto with libwebsockets support, and the broker itself works fine with libwebsocker  listener.
but when i try to use mosquitto _pub to send message to test server, works fine on 1883 port (without websockets) but fail over port 8080 (with websocket) , geting Error: A network protocol error occurred when communicating with the broker.

**Comment by ralight** [comment]
Mosquitto can, but the mosquitto_pub client doesn't have websockets support I'm afraid.

**Comment by eduard739** [comment]
if im building my own program using Mosquitto API function can i publish over websocket?

**Comment by ralight** [comment]
Not at the moment, no.

**Comment by Aeefire** [comment]
@eduard739  Hey! There are still lots of other client libraries available out there with websockets support. E.g. the eclipse javascript mqtt client library I believe only supports websockets. Publishing/Subscribing with it to mosquitto perfectly works for me!

**Comment by eduard739** [comment]
thanks, in the end i used integrated python paho to c (since their c/c++ does not support ws)

**Comment by knmr** [comment]
@eduard739 I am facing the same issue. Mind sharing?

**Comment by eduard739** [comment]
i cant share the code itself since its belong to the company i work at. 
but i can give guild lines.
do the following steps:
a.download python paho mqtt lib and build a simple mqtt client and test that its working fine
b. check how to integrate python with c++, i recommend this guild:
https://www.codeproject.com/Articles/820116/Embedding-Python-program-in-a-C-Cplusplus-code
c. now you can create IPC(i use pipes) between the c++ and python, use the IPC to communicate between the python and c++.

pesudo code:
in c++ 
publish(string topic,string msg)
{
  ipc_cpp_to_py(topic + <some_seperator> + msg)
}  

python:

while True: 
     ipc_read=wait_for_ipc_cpp_to_py_read()
     topic, msg = parshTopicAndMsg(ipc_read)
     mqtt_python_client.publish(topic,msg)

**Comment by knmr** [comment]
I understand completely. This is more than I hoped for. Thank you very much.
