### ISSUE TITLE
Is max_inflight_messages bi-direction or only one way limit?

### ISSUE THREAD

**Issue by Asoul** [eclipse/mosquitto#394]
I am curious about if the max_inflight_messages is bi-direction or only one way limit.

If set the max_inflight_messages to 1 and client subscribed qos 2. While client is receiving a message, does that means client cannot send any message at the same time? and vise versa?

Reference: [http://mosquitto.org/man/mosquitto-conf-5.html](http://mosquitto.org/man/mosquitto-conf-5.html)

```
max_inflight_messages count

The maximum number of QoS 1 or 2 messages that can be in the process of being transmitted 
simultaneously. This includes messages currently going through handshakes and messages
that are being retried. Defaults to 20. Set to 0 for no maximum. If set to 1, this will
guarantee in-order delivery of messages.

Reloaded on reload signal.

```
This question have already post to [stackoverflow](http://stackoverflow.com/questions/42266397/is-max-inflight-messages-bi-direction-or-only-one-way-limit) and sent to `mosquitto-dev-owner@eclipse.org` but have no respond, so I think I should post the question here.

Thanks,
Asoul

**Comment by toast-uz** [comment]
The most suitable place is mosquitto-dev@eclipse.org (not -owner),

In my understanding, the answer is one way. Sorry I've not tested yet. If you get a different result, report again.

**Comment by toast-uz** [comment]
Closing because seemed solved.
