### ISSUE TITLE
flush logging on new connection

### ISSUE THREAD

**Issue by thpham** [eclipse/mosquitto#395]
Hello,

I'm creating kind of presence hack that notify a client status on a $SYS topic. So I found a solution by parsing the log output, but I get the connected status of client, only when it de-connects or if there is another log event very soon after the connection.

example:
```
1488904294: New connection from 192.168.33.1 on port 8883.
1488904294: New client connected from 192.168.33.1 as client-test (c1, k60, u'client-test').
```

as the second line has always the same timestamp, it is flushed only in the next event. and it is often too late.

Is it possible to remove the following condition :  [bug line](https://github.com/eclipse/mosquitto/blob/v1.4.11/src/logging.c#L222) ?

**Comment by karlp** [comment]
removing it would greatly increase the host load for some logging cases.  WHy not just have your clients announce their presence on a topic like a good client?

**Comment by ralight** [comment]
As @karlp says your clients could announce their presence, or you could use topic logging. I don't want to flush on each new connection.
