### ISSUE TITLE
Send duplicate message to bridge

### ISSUE THREAD

**Issue by Asoul** [eclipse/mosquitto#398]
Can I prevent duplicate message sent to bridge?
I've set the duplicate flag from client, but the broker still send new message with dup = 0

```
1488965834: Received PUBLISH from client (d0, q1, r0, m870, 'test/topic', ... (10 bytes))
1488965834: Sending PUBACK to client (Mid: 870)
1488965834: Sending PUBLISH to bridge (d0, q1, r0, m58118, 'B/test/topic', ... (10 bytes))
1488965834: Received PUBACK from bridge (Mid: 58118)
1488965838: Received PUBLISH from client (d1, q1, r0, m870, 'test/topic', ... (10 bytes))
1488965838: Sending PUBACK to client (Mid: 870)
1488965838: Sending PUBLISH to bridge (d0, q1, r0, m58121, 'B/test/topic', ... (10 bytes))
1488965838: Received PUBACK from bridge (Mid: 58121)
```

**Comment by ralight** [comment]
It's been a while without a reply, sorry about that - is this still a problem?

**Comment by PierreF** [comment]
If you need exactly one delivery, you must use QoS=2. With QoS=1, it's possible to get multiple delivery of the same message.

Closing as Mosquitto could not do anything here without breaking MQTT compliance. In your example, Mosquitto should not assume that publish with dup=1 was already received:
> The recipient of a Control Packet that contains the DUP flag set to 1 cannot assume that it has seen an earlier copy of this packet.
> -- http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718038
