### ISSUE TITLE
mosquitto_sub.exe immediate crash

### ISSUE THREAD

**Issue by jtvilm** [eclipse/mosquitto#399]
Hello,

I installed the latest mosquitto broker on Windows 10. The service starts up perfectly fine and configuration works well (bound to localhost:1883). I allowed all traffic in Windows firewall with respect to localhost and the port and configured it not to block both mosquitto_sub.exe and mosquitto_pub.exe.

However, the simplest test with mosquitto_sub.exe -d -t "/test" fails as the program crashes immediately: Windows displays this "There was a problem with..." dialog.

I need to get this broker running for testing purposes locally for now. What could be the cause and how could I obtain more information about what is happening? 

Thanks,
Jan

P.S.: A mosquitto installation with the same version functions without problems on Ubuntu 16.04 in VirtualBox.

**Comment by shah253kt** [comment]
I'm also facing the same problem. I've installed mosquitto version 1.4.11, which should be the latest version. Running mosquitto_pub/sub crashes immediately. I thought this was fixed.

**Comment by jmota77** [comment]
Still suffering this issue. I've read previous release messages but I have not found any solution to fix this.

Someone has any solution to solve this?

**Comment by ralight** [comment]
I'm afraid the only thing I can think is that you haven't got the appropriate libraries installed. Have you got the Visual Studio 2013 x86 redistributable, and the x86 pthreadVC2.dll installed?

**Comment by jmota77** [comment]
I don't know if something is wrong in the way I'm setting up the project. I'm using windows server 2012  R2 x64, I've included the .dll files and I've installed the Visual Studio 2013 x86 redistributable and the pthreadVC2.dll file even the libeay32.dll and the ssleay32.dll. I can't find any solution to this.

**Comment by ralight** [comment]
Did you use openssl 1.0.2? That is what it is compiled against.

**Comment by jmota77** [comment]
Yes, I've tried using different versions, openssl 1.0.2 included. 

I copied the libraries mentioned before in the same folder I have the mosquitto executable. So, I don't know what else I can test.

**Comment by maxiwu** [comment]
having crash issue on windows. mosquitto-1.4.11-install-win32.

details of the problem.
Event name: BEX
error module: ucrtbase.DLL
module version: 10.0.10586.788
exception offset: 00083484
exception code: c0000417

**Comment by ralight** [comment]
The windows installers have been changed substantially since this issue, with the aim of making this problem much less likely. For that reason, I think this is probably fixed and I am going to close the issue. If you are still having problems with a recent version of Mosquitto, please reopen and provide details.
