### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [eclipse/mosquitto#4]
Some parameters (like "[${SYSCONFDIR}](https://github.com/eclipse/mosquitto/blob/62fa209eeb07315297c9a003866f37aab236459b/CMakeLists.txt#L95)" and "[${mosquitto_SOURCE_DIR}](https://github.com/eclipse/mosquitto/blob/db2e66c54311d720bffdf8abd0f7e16a88684fbd/src/CMakeLists.txt#L1)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](https://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes. "CMake splits arguments unless you use quotation marks or escapes.").

**Comment by ralight** [comment]
Closed in the fixes branch.
