### ISSUE TITLE
Sending PUBREC to local.CTRLS-BRIDGE-USER

### ISSUE THREAD

**Issue by nikhilve99** [eclipse/mosquitto#401]
hi,
 i am facing an issue where my other bridge server contineouly sending an error "**## **Sending PUBREC to local.BRIDGE-USER (Mid: 942)
1489031098: Socket error on client local.BRIDGE-USER, disconnecting****"

kindly help me out why we are getting this msg and also provide the solution too.

Regards
Nikhil

**Comment by ralight** [comment]
This could be caused by an incomplete QoS 2 message flow that one broker knows about (the one initiating the PUBREC) but that the other broker does not, hence it rejects it.

This problem was fixed in version 1.4.9.

**Comment by PierreF** [comment]
Do you still have this issue with Mosquitto 1.4.9 or newer ?

**Comment by ralight** [comment]
I presume this is fixed, if not please reopen and add more information.
