### ISSUE TITLE
Breaking change on test.mosquitto.org server recently?

### ISSUE THREAD

**Issue by mcorino** [eclipse/mosquitto#404]
I am using mosquitto 1.4.10 and 1.4.11 and since recently my tests encounter unexpected behaviour in subscribers when testing against the server at test.mosquitto.org.

It seems my subscriber receives spurious data immediately after subscribing. From my logs it seems the subscriber receives a message with the topic name both as topic and payload data.

When I run the same test (same binary) against a local server (same version as the subscriber) there is no such issue (as there was not with the test.mosquitto.org server until recently).

Before I dived more deeply into tracking this I wondered if this is an expected change in behaviour or not.

Any thoughts?

**Comment by mcorino** [comment]
This is the mosquitto logging callback sequence that shows up when the above issue happens:

PSDD::MQTT::Context_Impl::on_logging(0x1980eb0) - Client psdd4ccm/mqtt/6228/0x1961e40 sending SUBSCRIBE (Mid: 1, Topic: Hello/#, QoS: 0)
PSDD::MQTT::Context_Impl::on_logging(0x1980eb0) - Client psdd4ccm/mqtt/6228/0x1961e40 received SUBACK
PSDD::MQTT::Context_Impl::on_logging(0x1980eb0) - Client psdd4ccm/mqtt/6228/0x1961e40 received PUBLISH (d0, q0, r1, m0, 'Hello', ... (5 bytes))

The 5 bytes payload of the PUBLISH message is 'Hello'.

Any idea why the subscriber receives a PUBLISH after successfully subscribing? 
My test publisher has not even started publishing at that moment.

**Comment by ralight** [comment]
It looks like someone else has published a retained message to the topic "Hello", so that's why you are receiving the message straight after subscribing. It's expected behaviour - maybe try a more unique topic.

**Comment by mcorino** [comment]
Ah, of course. Should have thought of that myself.
Thanx.
