### ISSUE TITLE
Using TLS without authorization

### ISSUE THREAD

**Issue by ppedrycz** [eclipse/mosquitto#405]
Hi, 
So far it is not possible to use mosquitto TLS without authorization (one of "mosq->tls_cafile" "mosq->tls_capath" or "mosq->tls_psk" has to be set). It would be great to be able to use TLS for encryption and "mosquitto_username_pw_set" for authorization, for example by: mosquitto_tls_set(mosq, NULL, NULL, NULL, NULL)

**Comment by ralight** [comment]
There is no need to use authorisation with x509 certificates. In the current implementation setting cafile or capath just determines which CA root certificates the client will trust. You get encryption but no authentication.

Having TLS without setting a trusted CA means you trust anybody. It gives you encryption but you've got no assurance about who you are connected to at all.

I don't see this as a useful or secure request, you'll have to do some good explaining as to why this is necessary if you want it to be implemented.

**Comment by ralight** [comment]
No more information, so I'm closing this. If you provide more details it can be reopened.
