### ISSUE TITLE
When internet is down, bridge connection DNS request blocks mosquitto main loop.

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto#41]
migrated from Bugzilla [#472600](https://bugs.eclipse.org/bugs/show_bug.cgi?id=472600)
status UNCONFIRMED severity _normal_ in component _Mosquitto_ for _1.4_
Reported in version _unspecified_ on platform _PC_
Assigned to: Roger Light

On 2015-07-14 05:34:52 -0400, jsaak jsaak wrote:

> An async dns request should be used.
> As a workaround i put ip address instead of domain name.

**Comment by AlexShkunov** [comment]
Faced with the same issue, the block seems to last for 20 seconds. In most of the times - clients get disconnected. Any new information about the item?

**Comment by icraggs** [comment]
Hi Roger.  I thought you used an asynchronous library for DNS requests, to avoid blocking.  Is this not the case?

**Comment by ralight** [comment]
@AlexShkunov The workaround is to use IP addresses if you can.

@icraggs That's just for the client library to provide DNS-SRV lookups. The c-ares library is pretty much abandoned anyway, so not a good prospect. Surprise surprise, this is another thing that will be fixed when moving to libuv.

**Comment by icraggs** [comment]
@ralight Are there any short term workarounds possible?  "Obviously" anyone could implement a bridge as a standalone process, so that's one way.

**Comment by hardillb** [comment]
I'm going to have a look at this soon. The c-ares library seams to have had some recent update to it's github repo so may not be abandoned any more.

**Comment by ralight** [comment]
This has been fixed in 1.4.11 - at least for glibc based systems.
