### ISSUE TITLE
SQLite or MySQL or any other RDBMS support

### ISSUE THREAD

**Issue by DavidMont** [eclipse/mosquitto#410]
SQLite or MySQL or any other RDBMS support.
I really want to trace the queued messages. or I can manually flush it if necessary, Initially I have downloaded the src code and would want to put support to connecting MySQL or SQL. 

Is there any way I could modify this with your help :) ?

**Comment by PierreF** [comment]
For tracing messages in MySQL there is an https://github.com/eclipse/mosquitto/tree/master/examples/mysql_log. Does it fit you needs ?

**Comment by hamed-ta** [comment]
> For tracing messages in MySQL there is an https://github.com/eclipse/mosquitto/tree/master/examples/mysql_log. Does it fit you needs ?

is that practically working on Mosqutto ?

**Comment by ralight** [comment]
Closing this as answered. Please reopen if it is still an issue.
