### ISSUE TITLE
Authentication plugin should not block the broker

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto#42]
migrated from Bugzilla [#472050](https://bugs.eclipse.org/bugs/show_bug.cgi?id=472050)
status NEW severity _enhancement_ in component _Mosquitto_ for _1.4_
Reported in version _1.4_ on platform _All_
Assigned to: Roger Light

On 2015-07-07 08:20:28 -0400, Roger Light wrote:

> Network based authentication lookups can cause a big delay and hence have substantial negative impact on the performance of the broker. This needs an asynchronous approach.
> 
> Thread on mailing list: https://dev.eclipse.org/mhonarc/lists/mosquitto-dev/msg00714.html

**Comment by johanstokking** [comment]
We're running into this as well. I'm curious to what the status is on this matter today?

It would be nice to have asynchronous support for authentication plugins, but I understand that that requires major refactoring in the broker as the loop is single threaded.

**Comment by ralight** [comment]
Yes, as you say this is effectively a huge change because of the need for threading and a different approach to dealing with authentication. I'm afraid it certainly won't be in the next feature release.

**Comment by ralight** [comment]
Async authentication is now possible in plugins.

**Comment by johanstokking** [comment]
Awesome, thanks for getting back here @ralight.
