### ISSUE TITLE
Cannot use self-signed client certificates alongside CA signed server certificates

### ISSUE THREAD

**Issue by devmau5** [eclipse/mosquitto#420]
I have a LestEncrypt server certificate for my mosquitto instance. I am currently using password authentication and am trying to switch to client certificate authentication.

When I add my self-signed CA certificate to the /etc/mosquitto/certs folder and point capath at the folder I still get a TLS error. I am using both capath and cafile parameters in my config file.

Does mosquitto not support doing this ? Or am I just doing it wrong?

**Comment by ralight** [comment]
Did you run `c_rehash` on the certs directory?

**Comment by ralight** [comment]
Closing this as answered.
