### ISSUE TITLE
Broker corrupts persistent database mosquitto.db 

### ISSUE THREAD

**Issue by codami** [eclipse/mosquitto#424]
It can be easily reproduced like this:
1. given you have the following config;
```
persistence true
persistence_file mosquitto.db
persistence_location D:\
log_dest file D:\mosquitto.log
log_type all 
```
2. start the broker
`mosquitto.exe -c mosquitto.conf`

3. start a client with a persistent session that subscribes to SYS topics
`start mosquitto_sub.exe -i Client1 -c -q 2 -t $SYS/broker/# -C 10`

4. wait for around 15 seconds
5. stop the broker
6. start the broker again 

The broker fails to start with:
```
1492007506: Error restoring persistent database, message store corrupt.
1492007506: Error: Couldn't open database.
```

The log file and corrupted db file are here: [files.zip](https://github.com/eclipse/mosquitto/files/916935/files.zip)

**Comment by ralight** [comment]
Thanks for the good writeup. I think this has been fixed in the commit I just made. Are you able to test it for yourself?

**Comment by codami** [comment]
It works fine now, thanks!

**Comment by ralight** [comment]
Great, it'll be part of the next release. Thanks for feeding back.

**Comment by Markuzzzz** [comment]
If i follow fixes-next there is no due date. In which release 1.x.x.x will this be fixed?
