### ISSUE TITLE
MIPS musl malloc segfault

### ISSUE THREAD

**Issue by pbn4** [eclipse/mosquitto#425]
Hello

Today I was trying to cross compile and run my mosquito c++ client using mosquitopp on MIPS machine (Carambola2). The host OS is [LEDE](https://lede-project.org/) , up to date. The build system Makefile with version information can be found ([here](https://git.lede-project.org/?p=feed/packages.git;a=blob;f=net/mosquitto/Makefile;h=bc5ff90b2ad81abf2edb90ed310d97a9ac807ff7;hb=HEAD). It's 1.4.10. The library was built with `gcc version 5.4.0 (LEDE GCC 5.4.0 r3921-3169a6a)`. The C library is musl. 

Here is the stack trace:

```
Program received signal SIGSEGV, Segmentation fault.
unbin (c=0x77db0780, i=1) at src/malloc/malloc.c:228
228		c->prev->next = c->next;
(gdb) bt
#0  unbin (c=0x77db0780, i=1) at src/malloc/malloc.c:228
#1  0x77f83024 in malloc (n=16) at src/malloc/malloc.c:356
#2  0x77db6247 in _mosquitto_malloc (size=<optimized out>) at memory_mosq.c:67
#3  0x77db76a1 in _mosquitto_packet_read (mosq=0x77f439d0) at net_mosq.c:991
#4  0x77db5573 in mosquitto_loop_read (mosq=0x77f439d0, max_packets=1) at mosquitto.c:1156
#5  0x77db598f in mosquitto_loop (mosq=0x77f439d0, timeout=100, max_packets=<optimized out>) at mosquitto.c:947
#6  0x77db5a79 in mosquitto_loop (mosq=<optimized out>, timeout=<optimized out>, max_packets=<optimized out>) at mosquitto.c:846
#7  0x77f46805 in mosqpp::mosquittopp::loop (this=<optimized out>, timeout=<optimized out>, max_packets=<optimized out>) at mosquittopp.cpp:229 
```

The same code works on x86_64 Ubuntu 16.10 with `gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12)` .

**Comment by ralight** [comment]
Can you provide the sample code?

**Comment by pbn4** [comment]
Sorry for bothering, that was my mistake.
