### ISSUE TITLE
websockets listener configuration is odd.

### ISSUE THREAD

**Issue by tomtastic** [eclipse/mosquitto#434]
In `mosquitto.conf`, when using a FQDN to identify the address I want websockets on :

> user@test /etc/mosquitto/ $ egrep -i ^listen\|^prot *.conf
listener 1883 localhost
listener 8883 test.home
listener 8083 test.home    # <--- websockets bind here please
protocol websockets

mosquitto fails to start :
> 1493816600: Creating Vhost 'default' port 8083, 3 protocols
1493816600:  Using SSL mode
1493816600:  SSL ECDH curve 'prime256v1'
1493816600:  interface lo vs test.home
1493816600:  interface enp3s0 vs test.home
1493816600:  interface enp4s0 vs test.home
1493816600:  interface lo vs test.home
1493816600:  interface enp3s0 vs test.home
1493816600:  interface enp4s0 vs test.home
1493816600:  interface lo vs test.home
1493816600:  interface enp3s0 vs test.home
1493816600: Unable to find interface test.home
1493816600: Failed to create default vhost
1493816600: Error: Unable to create websockets listener on port 8083.

Confusingly, one must use either an IP address (a pain when DHCP is in use), or weirdly the interface name (eg. enp3s0) directly?

**Comment by ralight** [comment]
Yes, libwebsockets doesn't let you work with hosts like this, it prefers the interface name. I agree it's weird. I suppose mosquitto should be attempting to resolve the host first and passing the IP to libwebsockets.

**Comment by ralight** [comment]
This is fixed in the upcoming version 2.1.

**Comment by karlp** [comment]
How did you fix this?  I can't see it in the develop commit log.  because once at config load is not going to be super reliable with changing ips....
