### ISSUE TITLE
websocket bind to ipv6

### ISSUE THREAD

**Issue by mtnbrit** [eclipse/mosquitto#437]
Hi, I would like the mosquitto websocket listener to bind to both ipv4 and ipv6. I recompiled libwebsockets enabling IPV6 support, but it still says 'disabled' in the logs. 

```
May  4 23:12:57 dev mosquitto[30914]: mosquitto version 1.4.11 (build date 2017-05-04 23:10:49+0000) starting
May  4 23:12:57 dev mosquitto[30914]: Config loaded from /etc/mosquitto/mosquitto.conf.
May  4 23:12:57 dev mosquitto[30914]: Opening ipv4 listen socket on port 1883.
May  4 23:12:57 dev mosquitto[30914]: Opening ipv6 listen socket on port 1883.
May  4 23:12:57 dev mosquitto[30914]: Opening ipv4 listen socket on port 8883.
May  4 23:12:57 dev mosquitto[30914]: Opening ipv6 listen socket on port 8883.
May  4 23:12:57 dev mosquitto[30914]: Opening websockets listen socket on port 9002.
May  4 23:12:57 dev mosquitto[30914]: Initial logging level 255
May  4 23:12:57 dev mosquitto[30914]: Libwebsockets version: 2.2.0 root@dev-v2.0.0-375-ge304d7b
May  4 23:12:57 dev mosquitto[30914]: IPV6 compiled in but disabled
...
May  4 23:12:57 dev mosquitto[30914]: Creating Vhost 'default' port 9002, 3 protocols, IPv6 off
```

I looked in the libwebsockets source code context.c and see that it requires the context option LWS_SERVER_OPTION_DISABLE_IPV6 be not set in the lws_create_context() call, not sure if mosquitto is setting it mistakenly? or how to control it? Any reason its disabled by default?

**Comment by mtnbrit** [comment]
update, I made it bind to the ipv6 address correctly by changing the ifndef to ifdef LWS_IS_OLD at line 640 of src/websockets.c.

Is it possible this is an error and it in fact is supposed to disable v6 if LWS is an old version?

**Comment by ralight** [comment]
As I remember, LWS treated ipv6 sockets in a way that caused problems. It's been a while though, so things might have changed. I'll have to take a look.

**Comment by ralight** [comment]
The option has been removed now (i.e. it no longer disables IPv6): https://github.com/eclipse/mosquitto/commit/ba0122f9a9c032a2d0c3fe175113b0c829c4e12e
