### ISSUE TITLE
client_shared.c gives empty error message when no broker is running

### ISSUE THREAD

**Issue by minghuadev** [eclipse/mosquitto#440]
I noticed the empty error message and found the use of `strerror_r(errnum, buf, buflen)` is not solid. The man page says it either returns a pointer to the buffer, or to an internal static string. In the latter case, the diff below or something is needed so the error message can be printed properly later. 

    --- a/client/client_shared.cpp
    +++ b/client/client_shared.cpp
    @@ -762,7 +762,11 @@ int client_connect(struct mosquitto *mosq, struct mosq_config *cfg)
                    if(!cfg->quiet){
                            if(rc == MOSQ_ERR_ERRNO){
     #ifndef WIN32
    -                               strerror_r(errno, err, 1024);
    +                               char *ret_err = strerror_r(errno, err, 1024);
    +                               if ( ret_err != err ) {
    +                                       snprintf(err, 1023, "%s", ret_err);
    +                                       err[1023]='\0';
    +                               }
     #else
                                    FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM, NULL, errno, 0, (LPTSTR)&err, 1024, NULL);
     #endif

**Comment by ralight** [comment]
The version of strerror_r that returns a char* is a GNU specific function that is not portable. By default I get the portable version that returns an int (and doesn't have the behaviour you describe). The man page does say I shouldn't be getting the portable version though.

What system are you using this on?

**Comment by minghuadev** [comment]
The system is a ubuntu 16.04.4. It looks by default it uses the GNU version. 

    $ cat t.c
    #if (_POSIX_C_SOURCE >= 200112L || _XOPEN_SOURCE >= 600) && ! _GNU_SOURCE
      #error xsi compatible version
    #else
      #error gnu version
    #endif

    $ gcc t.c
    t.c:5:4: error: #error gnu version
       #error gnu version
        ^

    $ gcc --version
    gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by minghuadev** [comment]
I ran some test and figured out it is due to using g++ to compile. A stackoverflow thread said that g++ turns _GNU_SOURCE on by default, and turning it off breaks libstdc++. I'm linking it with other C++ code, thus using g++ to compile with the same flags. Any idea how to solve this?

**Comment by minghuadev** [comment]
Ok, I'm going to compile C code with gcc, and C++ code with g++. And not to mix the use of libraries either. Will close this ticket in a day or two, in case someone sees there is some obvious mistake here.
