### ISSUE TITLE
websocket support not available

### ISSUE THREAD

**Issue by archunan007** [eclipse/mosquitto#444]
Hi All,

I have downloaded the MQTT server from mosquitto and installed on my local machine.
I can send the data through MQTT client and also i want to get the data from websockets.

while searching MQTT with websockets, it requires libwebsockets 1.7
am new to GitHub, can anyone please help me to setup libwebsocket to windows and get data through websockets. please

![image](https://cloud.githubusercontent.com/assets/25320563/25896719/ec192244-35a2-11e7-9a2c-f06a58d75158.png)

Thanks,
ArchunanK

**Comment by ralight** [comment]
The Windows binaries provided by the project do not have websockets support. If you want websockets support I'm afraid you'll have to compile the broker yourself.

**Comment by archunan007** [comment]
Can you please explain the steps for me.

Thanks a lot,
Archunan K

**Comment by Adi-18** [comment]
Why websocket support can not be included..?

The procedure of rebuild looks not easy:
https://github.com/bapowell/bapowell.github.io/wiki/Mosquitto-Build-Notes-(Windows---Visual-Studio)

**Comment by ralight** [comment]
It's a distribution and licensing support issue I'm afraid. I can't distribute binaries of libwebsockets and they aren't provided by the libwebsockets project, so it's better to just not include support on windows by default.

**Comment by Tchoumi** [comment]
ralight please how i can do that?  so it's better to just not include support on windows by default.

**Comment by ralight** [comment]
This is no longer an issue, websockets support is provided by default on Windows.
