### ISSUE TITLE
mosquitto service problem

### ISSUE THREAD

**Issue by BigGitWorld** [eclipse/mosquitto#445]
Hi!
I have installed a mosquitto (by wget method) in ubuntu 16.04.
everything is ok in the installation.
now I want to edit mosquitto.conf file and then use : 
usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
to apply my changes.
but seems my changes does not apply!
I did a search for "mosquitto.service" in ubuntu, but I could not find any file with this name.
why?
so I think this is my issue.
I attempted to create a "sudo nano /etc/systemd/system/mosquitto.service" file, like this : 
    [Unit]
    Description=Insite MQTT Broker

    [Service]
    ExecStart=/usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
    Restart=always

    [Install]
    WantedBy=multi-user.target

and after it I used : 
    sudo systemctl start mosquitto.service
    systemctl status mosquitto.service
but these commands didnt help me again. because status command give me "activating" or "dead" message and I can not restart my mosquitto service to apply my changes to the mosquitto.conf.
how can I solve this problem?

best regard

**Comment by BigGitWorld** [comment]
is there anyone who help me?

**Comment by ralight** [comment]
Is it because you've already got an instance of mosquitto running?

I'd suggest just installing from the provided repositories.

**Comment by BigGitWorld** [comment]
thank you for your reply.
I dont want use from repo. I need to its source code because I want to apply some plugin on it.
