### ISSUE TITLE
Documentation of message_size_limit

### ISSUE THREAD

**Issue by jamesmyatt** [eclipse/mosquitto#448]
There's nothing (that I can find) in the man pages that describes what will happen when `message_size_limit` is exceeded.

I think that the `mosquitto.conf` man page should also describe what happens when `max_inflight_messages` and `max_queued_messages` are exceeded, although the `mosquitto` man page implies that they are dropped.

**Comment by toast-uz** [comment]
Could you make PR with the appropriate documents of your wish?

**Comment by ralight** [comment]
I hope those changes are clear enough, they'll be in 1.6.5.
