### ISSUE TITLE
Mosquitto QoS 2, usage of retry_interval

### ISSUE THREAD

**Issue by sachingupta141** [eclipse/mosquitto#453]
In mosquitto.conf we can set a config parameter named retry_interval.

As [help ](https://mosquitto.org/man/mosquitto-conf-5.html)page says about this parameter:

retry_interval seconds

> The integer number of seconds after a QoS=1 or QoS=2 message has been sent that mosquitto will wait before retrying when no response is received. If unset, defaults to 20 seconds.

> Reloaded on reload signal.

But It starts some questions over Mosquitto behavior:

After each 20 seconds, Will Mosquitto keep trying to connect indefinitely ? 
As I am not able to find any other parameter to control this iteration.

When Mosquitto provides a way to persist the content of QoS2 traffic, then what is the use of this configuration ? 
As with persistence it should be straight forward. If client is not available then save data in memory. when it comes online, deliver it.

**Comment by ralight** [comment]
I would suggest that you ignore this option, or set it to be a high value. It will be removed in the next version of mosquitto because it actually causes more problems to no real benefit.
