### ISSUE TITLE
Session Resumption not supported if 'require_certificate' set to true?

### ISSUE THREAD

**Issue by comettie** [eclipse/mosquitto#454]
Hello,
I have rebuild mosquitto version 1.4.11 to add websocket support, since the client I am using only supports MQTT over websocket.
'require_certificate' is set to true in the mosquitto.conf file, hence during the TLS handshake server and client exchange their certificates.
After the client has connected to the broker, it may subscribe topics and/or publish messages, eventually it close the connection.
At the next connection attempt, the client starts a session resumption (using the session id received by the Server Hello message got during the previous TLS handshake) but the server suddenly closes the underlying TCP socket after the reception of Client Hello message.

Am I missing some option in the configuration file? or is it a bug?

**Comment by ralight** [comment]
Could you give this command a try?

    openssl s_client -connect <host:port> -reconnect -CAfile <ca cert> -cert <client cert> -key <client key>

This should attempt essentially the same process that you have seen, but without any actually MQTT or websockets traffic. If the resumption is successful, you'll see a line similar to

    Reused, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384

**Comment by comettie** [comment]
The command you suggested did NOT succeed in reopening the connection using the same ID.
I tried to perform the same operation with 1way authentication, it DID succeed in reopening the connection using the same ID.
I am attaching the log of the two commands. I have restricted the ciphers to set supported by our MQTT client. For your info, the MQTT over WS over TLS client I am using is implemented on an embedded device intended for IoT application.

[1way.txt](https://github.com/eclipse/mosquitto/files/1088264/1way.txt)
[mutual.txt](https://github.com/eclipse/mosquitto/files/1088265/mutual.txt)

I tried the other way round, i.e. connecting the MQTT client to an openssl server using the following command (I want the server to request the client certificate):

`openssl s_server -accept <port> -CAfile <ca cert> -cert <server cert> -key <server key> -status -debug -tls1_2 -verify_return_error -Verify 5`


During this test, the client saves the Session ID received by Server Hello message and the handshake is passed but (obviously) the connection is closed after a timeout because there isn't a websocket server responding to the client request.
After that, the client retry opening the connection using the same Session ID and the handshake is passed without exchanging the certificates again.

I wanted to compare the difference in the handshake between mosquito and s_server, so I have grabbed the network traffic with wireshark. The major difference I noticed in the reply to Client Hello message is:
- **_mosquito_** send Server Hello, Certificate, Certificate Request and Server Hello Done messages in a single TCP packet
- **_s_server_** send Server Hello message in a TCP packet and Certificate, Certificate Request and Server Hello Done messages in another TCP packet.

Could this be a clue?

**Comment by ralight** [comment]
What version of libwebsockets are you using?

**Comment by comettie** [comment]
$ ldd /usr/local/sbin/mosquitto
	linux-vdso.so.1 =>  (0x00007ffd47f9e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa3c6627000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa3c6321000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa3c6119000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fa3c5eba000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fa3c5ade000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fa3c58d9000)
	libwebsockets.so.3 => /usr/lib/x86_64-linux-gnu/libwebsockets.so.3 (0x00007fa3c56c8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa3c52ff000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa3c682b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa3c50e1000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa3c4ec8000)

libwebsockets.so.3 comes from Ubuntu package libwebsockets3:amd64 1.2.2-1
Hope it answer the question.

**Comment by karlp** [comment]
That's a _super_ old libwebsockets, 1.3 probably.  So old it's not even on the abi compat chart. There were _many_ bugs in the old version that would be exposed by things like this.  I _highly_ recommend trying a newer lws, at _least_ 1.7.x, preferably 2.x

**Comment by comettie** [comment]
I have manually installed libwebsockets7 v 1.7.3 (newer version gave me dependency trouble on my Ubuntu 14 machine) and recompiled mosquito: it solved the issue!
