### ISSUE TITLE
Possible conflict between init.d & systemd scripts on Debian

### ISSUE THREAD

**Issue by elric91** [eclipse/mosquitto#455]
On debian Jessie, version from mosquitto debian repository: 1.4.12-0mosquitto1, fresh reinstall of the package after a full delete (`apt remove --purge mosquitto`) and manual clean of remaining conf files. Configured on a port with no device (1884)

For some time, I experienced disconnections (*home-assistant in pain :' )* ) and found that mosquitto was **restarting every 330 seconds**, even if I disabled the service (`systemctl stop mosquitto && systemctl disable mosquitto`)

In /var/log/mosquitto/mosquitto.log, the following error was listed every 330 seconds : 
`Error in poll: Interrupted system call`
After some investigations, it seems that even if the service is running, a second instance tries to start every 330 seconds (a foreground execution shows that another instance is trying to reclaim the port that is already in use)

Unregistering the init.d service with `update-rc.d mosquitto disable` did not seem enough but, as a workaround, deleting /etc/init.d/mosquitto and restating through systemd (`systemctl start mosquitto`) solved it

However, this is a **temporary workaround** as an update through apt will certainly put everything in place

**Comment by ralight** [comment]
I believe this should be fixed now, it was hopefully down to a misconfiguration in the packaging scripts.

If it reoccurs, please reopen this bug.
