### ISSUE TITLE
mosquitto: error while loading shared libraries: libwebsockets.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by theunreal** [eclipse/mosquitto#458]
After I manually built mosquitto, I get the following error when trying to run it:

`mosquitto: error while loading shared libraries: libwebsockets.so.10: cannot open shared object file: No such file or directory`

I also built libwebsocket but the path seem wrong, how I can define or place the libwebsockets.so.10 file for mosquitto?

**Comment by ralight** [comment]
If you've installed libwebsockets with `make install` then you probably just need to run `sudo ldconfig` to update the linker cache.
