### ISSUE TITLE
mosquitto service doesnt start without sudo rights

### ISSUE THREAD

**Issue by mpuff** [eclipse/mosquitto#460]
Hello,

after i reboot my machine, i need to start the mosquitto manually with sudo rights.
That was not always so.
Does someone has the same issue?

**Comment by ralight** [comment]
Could you give more details about the system you are running on?

**Comment by Gibber** [comment]
Hi,
I have a similar problem. Mosquitto was working fine last week, then I did a system update/upgrade. Now I have to start mosquitto manually after each reboot. I am running the current release of Rasbian Jessie lite on a Raspberry Pi 2. I installed mosquitto as follows:
$ wget http : //repo.mosquitto.org/debian/mosquitto-repo.gpg.key 
$ sudo apt-key add mosquitto-repo.gpg.key
$ rm mosquitto-repo.gpg.key
$ cd /etc/apt/sources.list.d/
$ sudo wget http : //repo.mosquitto.org/debian/mosquitto-jessie.list
$ sudo apt-get update
$ sudo apt-get install mosquitto mosquitto-clients

I guess I could just create a systemclt start up file to start automatically but I did not need this before the recent update.  Any suggestions appreciated.

**Comment by mpuff** [comment]
i have also installed Debian Jessie on a raspberry pi.
i have the same issue like Gibber!

**Comment by Gibber** [comment]
I do not have to invoke sudo. I can start MQTT just with $ mosquitto

And I do not have elevated privileges. But as you say auto start does not work for me either.

**Comment by imZack** [comment]
@ralight I think this issue is related to the wrong packaging script I mentioned on IRC#mqtt. 

FYI
```
11:10 < yulun> ral: Just find out there is typo in 
http://repo.mosquitto.org/debian/pool/main/m/mosquitto/mosquitto_1.4.12-0mosquitto1.debian.tar.xz
11:11 < yulun> ral: in file "rules", `dh $@ --with-systemd` should be `--with=systemd`
22:55 < ral> yulun: Oooh, thanks.
```

Hoping the content of `repo.mosquitto.org` could be hosted on github, too. So that we could make pull request or something for you.

**Comment by Gibber** [comment]
Worked for me! Thanks imZack!

**Comment by mpuff** [comment]
Thank you, now it is working!
