### ISSUE TITLE
the duration which should be taking  for communication of mosquitto broker with 800 clients

### ISSUE THREAD

**Issue by kushal4** [eclipse/mosquitto#463]
hi,
I am running a testbench with paho client and mosquitto broker.So i created  800 paho clients and communicated it with the mosquitto broker.I gave  the time duration of  5 minutes after which the normal publish  messages  should be stopped sending from paho clients.So after that i see duration of completing the totall flow  completing  to take a time of around 38 minutes to complete. In this 800 clients there are 12 publishers and rest are subscribers and redundant  publisher of topic is avoided in this test bench.So,12 publisher publish to 12 unique topics and there are  multiple subscribes  to the same topic.
Thanks,
Kushal

**Comment by ralight** [comment]
There doesn't appear to be a question or issue here, is that right?
