### ISSUE TITLE
Windows defender detects a trojan in mosquitto-1.4.12-install-win32.exe

### ISSUE THREAD

**Issue by kmpm** [eclipse/mosquitto#464]
On a Windows 2016 server, Windows defender detects the binary linked to by the mosquitto web page as having a trojan called Win32/Pellate.A!cl.

The installer I try to download is mosquitto-1.4.12-install-win32.exe

I could download it on 13th of June but not today when it's the 20th but I could have had outdated definitions at the 13th.
I could install the server on the 13th and even today Windows Defender do not complain about the installed files, just the installer.

**Comment by kmpm** [comment]
Oh and since the installer is detected as being infected I can no longer download it.
My last try was from http://ftp-stud.fht-esslingen.de/pub/Mirrors/eclipse/mosquitto/binary/win32/mosquitto-1.4.12-install-win32.exe

**Comment by kmpm** [comment]
This is most likely a false hit but I wanted to make you aware of it.
VirusTotal doesn't complain and neither do Kaspersky Virusdesk.

**Comment by alpintrekker** [comment]
Same thing on Win8.1.

**Comment by ralight** [comment]
Thanks for reporting this, but I'm quite certain it is a false positive. There are also lots of instances of Windows Defender coming up in other places for this and similar trojans.

**Comment by ralight** [comment]
I'm closing this issue, version 1.4.12 is well out of date now.
