### ISSUE TITLE
Mosquitto on RHEL websocket support not available 

### ISSUE THREAD

**Issue by Eldritch2004** [eclipse/mosquitto#466]
I just tried to update Mosquitto from 1.4..11 to 1.4.12 via yum.
After the update I can't start the service anymore as the new version tells me:
websocket support not available

**Comment by ralight** [comment]
Which repository are you trying to get it from?

**Comment by Eldritch2004** [comment]
http://download.opensuse.org/repositories/home:/oojah:/mqtt/RedHat_RHEL-7/home:oojah:mqtt.repo

**Comment by ralight** [comment]
Are you sure your previous version wasn't from a different place? The version provided for RHEL there has never had websockets support.

**Comment by ralight** [comment]
This issue hasn't received any more information for a while, so I'm going to close it. If it is still a problem, please reopen and provide more details.
