### ISSUE TITLE
Where to find saved clients?

### ISSUE THREAD

**Issue by sjorsvanheuveln** [eclipse/mosquitto#471]
I assume information on clients using the mqtt broker are stored somewhere. Where can I find this database in the mosquitto folder? Thanks for the fantastic program, by the way.

**Comment by ralight** [comment]
If you're using persistence, a file mosquitto.db will be created as per your configuration - probably /var/lib/mosquitto/

You can use the [mosquitto_db_dump program](https://github.com/eclipse/mosquitto/tree/master/src/db_dump) to get a bit of information out of it, but it's really an internal file format.
