### ISSUE TITLE
New major release request

### ISSUE THREAD

**Issue by PierreF** [eclipse/mosquitto#473]
Hi,

the develop branch was not released for quite some time (about 2 years). There are features in this branch that I would like to see released (I'm thinking to #141).

Is there something I can do to help with a develop branch release ?

Thanks

**Comment by toast-uz** [comment]
The action items for v.1.5 ?
https://github.com/eclipse/mosquitto/milestone/1

**Comment by PierreF** [comment]
There is also https://github.com/eclipse/mosquitto/projects/1, but not all items are present in both list.
#242 is present on both list and I've started a PR ( #562 ) to make thing more forward.

@ralight what could be done to help for Mosquitto 1.5 ?

**Comment by toast-uz** [comment]
Also there are many open issues and unconfirmed PRs.
I'd like to proceed this community as much as I can. 
@ralight could you show us what we can help?

**Comment by rbalik** [comment]
Seems like there are a ton of fixes on the develop branch that haven't been released yet. Any plans to do the 1.5 release soon or merge any of these back to 1.4?

**Comment by ralight** [comment]
It's just making its way through the paperwork side of things now.

**Comment by ralight** [comment]
Coming very soon, so I'm closing this.
