### ISSUE TITLE
Not working as expected in specific scenario

### ISSUE THREAD

**Issue by mikeS7** [eclipse/mosquitto#477]
I'm using mosquitto 1.4.12 configured with persistence storage.

Client is connected with retained "will message" with payload 0 (which means disconnected), on connect client sends retained message to the same topic with payload 2 (which means connected).

If connection is lost or keep-alive interval exceeded mosquitto set payload to 0 (will message), but if I restarted mosquitto and the client lost connection at the same time and will not restore connection I've got message with payload 2.
In such scenario connection status is incorrect.

I expect that mosquitto should set payload to "will message" on restart or after keep-alive interval.

**Comment by ralight** [comment]
I think this is fixed now, so I'm closing this pending the release.
