### ISSUE TITLE
Misspelling allow_anonymous prevents Mosquitto broker from starting 

### ISSUE THREAD

**Issue by Mike-Allen** [eclipse/mosquitto#483]
I misspelled allow_anonymous as allow_a**nn**onymous and Mosquitto wouldn't start. Nothing was written to the log file.

Version 1.4.8 build date Tues, May 23, 2017. Ubuntu 16.10 - from Ubuntu repository

**Comment by ralight** [comment]
Logging isn't configured until after the whole config file is loaded. Until that happens, log messages are only printed on stderr. You should be able to see those log messages with `journalctl -xe`

**Comment by Mike-Allen** [comment]
Thanks.

I "assumed" that failure to start because of a spelling error was not the desired behavior. I just commented out lines in the conf file until things started working again.

**Comment by ralight** [comment]
Yeah, it's a bit of a tricky problem to deal with.

**Comment by cjmaynard** [comment]
In keeping with Postel's law (https://en.wikipedia.org/wiki/Robustness_principle), wouldn't it be better if mosquitto just ignored options it doesn't understand?  This would make it a lot easier to create `mosquitto.conf` files that incorporate and test new features, such as "`notifications_local_only true`" from issue #233 or "`allow_sys_update true`" from issue #535.  It would also better accommodate any options that might be deprecated in the future.

**Comment by ralight** [comment]
I agree with the points in the linked article that allowing invalid input can lead to a decrease in robustness and hence will be keeping strict validation of configuration options.
