### ISSUE TITLE
Adding Websocket support for clients in C++

### ISSUE THREAD

**Issue by Ben-Macri** [eclipse/mosquitto#487]
Greetings,
From what I have read and tried to get working Websockets is only supported for the broker.  I wanted to verify that this is the case and if so is there any plan to add support for the pub/sub clients in the near future?

Thank you for your time,
Ben Macri

**Comment by ralight** [comment]
At the moment, yes it is just the broker that supports websockets.

**Comment by Ben-Macri** [comment]
Thank you for the response and setting this up as an enhancement request.  This would be great to see happen.  I'm not sure what your process is with enhancements but feel free to close this if that makes things easier.

**Comment by gosuwachu** [comment]
I am looking for a mqtt client library with websockets support as well!

**Comment by qutab** [comment]
Any updates on this feature request?

**Comment by jmendeth** [comment]
+1

**Comment by gopicisco** [comment]
+1

**Comment by mm-ark** [comment]
+1

**Comment by ralight** [comment]
This is available in the `develop` branch and will be part of the 2.1 release.

**Comment by gopicisco** [comment]
> This is available in the `develop` branch and will be part of the 2.1 release.

Thanks!. May I know when the 2.1 release is planned?

**Comment by ralight** [comment]
"soon"
