### ISSUE TITLE
tcp max connections on ubuntu14.04

### ISSUE THREAD

**Issue by lewis081** [eclipse/mosquitto#488]
mosquitto version: 
1.4.12
question:
tcp max connections can reach 5000+ on windows10.
However, connections on ubuntu just can reach 1024.
I use command[ulimit -n] to change max tcp connections of process. But it has no effect.
How can i impove the connections on ubuntu?
Thank you for your answer.

**Comment by liudf0716** [comment]
after using ulimit -n change max tcp connections, u need restart mosquitto

**Comment by ralight** [comment]
You may also need to change /etc/init/mosquitto.conf:

    limit nofile 4096 4096

**Comment by drgra** [comment]
More detailed discussion here
https://dev.eclipse.org/mhonarc/lists/mosquitto-dev/msg00682.html

**Comment by lewis081** [comment]
@liudf0716 I restart mosquitto server many times.Howerver, it seems no effect. Anyway, thank you for your answer.

**Comment by lewis081** [comment]
@ralight Thank you very much. It works.
But I have something to say about this solution.
I know that the max connections of mosquitto can be seted in /etc/mosquitto/mosquitto.conf. Default is -1.It indicates ulimited connections. 
Therefore, i didn't realize mosquitto need configure other parameters to adjust its connections. My attention towards to system setup.
Though the line has worked, I confuse that the line belongs to system setup or mosquitto setup.
Thank you for your patient answer.
ps: I read the website given by @drgra. I am sorry that I don't understand the reply from you.

**Comment by lewis081** [comment]
@drgra Thank you for answer. I am sorry that I don't understand about their conversation after I read it.

**Comment by tm-chang** [comment]
How to start your mosquitto?
if you use init.d script, Pls put below @script.
ulimit -n 4096

**Comment by lewis081** [comment]
@tm-chang i am sorry about that i can't understand your statement.

**Comment by tm-chang** [comment]
Here is my /etc/init.d/mosquitto script, you can reference.
#!/bin/bash

prog=mosquitto
bin=/usr/local/sbin/$prog
config=/etc/mosquitto/mosquitto.conf
options="-d -c $config"
lockfile=/var/lock/subsys/$prog
pidfile=/var/run/$prog.pid
ulimit -n 30000                                                                <--add this
......

**Comment by ralight** [comment]
This issue hasn't seen any input for a while so I'm closing it. If you still have problems please reopen and add more details.
