### ISSUE TITLE
Make persistence file dynamically updateable

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto#49]
migrated from Bugzilla [#470044](https://bugs.eclipse.org/bugs/show_bug.cgi?id=470044)
status NEW severity _enhancement_ in component _Mosquitto_ for _1.4_
Reported in version _unspecified_ on platform _All_
Assigned to: Roger Light

On 2015-06-12 04:59:16 -0400, Roger Light wrote:

> It would be nice if the persistence file could be updated as necessary, not in a single periodic write.
> 
> Issues with a dynamic approach would include that messages might appear out of order and the need to defragment the file.

**Comment by ralight** [comment]
This is in progress.

**Comment by tucic** [comment]
This would be very nice feature. Is it about the persistence plugin?

**Comment by ralight** [comment]
Yes that's right.

**Comment by q2dg** [comment]
Any news on this?
Thanks!

**Comment by ralight** [comment]
I'm afraid not, it is scheduled for the 2.0 release.

**Comment by ralight** [comment]
This is available in the `develop` branch which will be in 2.1, so I'm closing the issue.
