### ISSUE TITLE
mosquitto_sub can't subscribe to $ topic

### ISSUE THREAD

**Issue by lesjaw** [eclipse/mosquitto#491]
I have a publish topic like this "devices/id_device/$online --> true"

When I try to use 
mosquito_sub -t devices/id_device/$online 
it gave me nothing... No message coming even though I have publish a message to that topic.. 

Using another MQTT client such as Lens, Paho etc the topic does give me the output which is "true"

Is this known problem for mosquitto_sub command line cannot subscribe to topic with char $? 

Let say I have a device which is always publish to topic something like this :
devices/id_device/light --> true
devices/id_device/uptime --> 11455
devices/id_device/$online --> true
devices/id_device/$signal --> 80

Using mosquito_sub I can subscribe to those topic above who has not $ char, they all give the right output base on last message publish.. 

Even if I use mosquito_sub with topic devices/id_device/# still only topic without $ gave me the right message output.. 

Anybody can suggest me another MQTT subscriber using command line? 

Thank you

**Comment by kartben** [comment]
Hi there,
You need to make sure $ is escaped, so you want to do `mosquito_sub -t 'devices/id_device/$online'` (note the quotes) otherwise `$online` is evaluated (very likely to a blank string in your case, therefore you are effectively subscribing to `devices/id_device/`)

**Comment by ralight** [comment]
I'm closing this because @kartben is correct, it's an unfortunate situation that does catch people out.

**Comment by lesjaw** [comment]
Hei hello... Thank you... I can confirm using quotes (') it does work..
