### ISSUE TITLE
Ansible role: debops.mosquitto

### ISSUE THREAD

**Issue by AnBuKu** [eclipse/mosquitto#492]
Maybe interesting to the EclipseMosquitto project:

- https://github.com/debops/ansible-mosquitto
- https://docs.debops.org/en/latest/ansible/roles/ansible-mosquitto/docs/index.html

**Comment by AnBuKu** [comment]
Just an information. Better place?

**Comment by ralight** [comment]
I don't use ansible myself, is the source repository really the best place to store all of that? It would have to be submitted by the original author as well.

**Comment by AnBuKu** [comment]
@ralight Indeed, I would have preferred a better place for such information as well, e.g. something like "mosquitto implementations". Unfortunately I didn't find anything so far. Any hint?

Submission, once the place is known, by the original author @drybjed from DebOps shouldn't be a problem.

Anyhow, I think I close for now, as this looks like not to be the place to inform mosquitto community about new implementations. My apologies for any inconvenience.
