### ISSUE TITLE
Port to event loop library

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto#50]
migrated from Bugzilla [#470008](https://bugs.eclipse.org/bugs/show_bug.cgi?id=470008)
status NEW severity _enhancement_ in component _Mosquitto_ for _1.4_
Reported in version _unspecified_ on platform _All_
Assigned to: Roger Light

On 2015-06-11 17:42:07 -0400, Roger Light wrote:

> Porting to use an event loop library such as libevent, libuv will allow the best performance on all supported platforms. At the moment using poll() is a bottleneck, this would reduce the bottleneck.
> 
> It also gives an opportunity to tidy up the existing code.

**Comment by ralight** [comment]
This is a roadmap item, it doesn't add anything being open here.

**Comment by nullr0ute** [comment]
So if roadmap items aren't being tracked here in the issue tracker where exactly are they being tracked?
