### ISSUE TITLE
Environment variables for Docker image

### ISSUE THREAD

**Issue by waspinator** [eclipse/mosquitto#510]
Is it possible to define configuration parameters as docker environmental variables?

https://mosquitto.org/man/mosquitto-conf-5.html
https://docs.docker.com/compose/environment-variables/

**Comment by ralight** [comment]
No, mosquitto doesn't use any environment variables.

**Comment by efrecon** [comment]
I have just laid my hands onto [this](https://github.com/efrecon/docker-mosquitto). It provides support for environment variables. The resulting image is on the [hub](https://hub.docker.com/r/efrecon/mosquitto/) and is (re)built automatically each time the library image changes.

**Comment by ralight** [comment]
There are no plans to support environment variables in the same style as that image, so I'm going to close this issue.
