### ISSUE TITLE
Can not install mosquitto via yum in CentOS 7

### ISSUE THREAD

**Issue by lioneieChen** [eclipse/mosquitto#512]
Hello, I use yum install mosquitto in CentOS 7, but have the error:"http://download.opensuse.org/repositories/home:/oojah:/mqtt/CentOS_CentOS-7/repodata/primary.xml.gz: [Errno 14] HTTP Error 404 - Not Found
", I think the server must have some problem. Thanks!!!

**Comment by ralight** [comment]
It exists for me... maybe it was a transitory error?

**Comment by lioneieChen** [comment]
yes, it is a transitory error, I have installed, thanks for your reply.
