### ISSUE TITLE
Mosquitto MQTT Bridge-Usage and Configuration

### ISSUE THREAD

**Issue by vishuPPatel** [eclipse/mosquitto#514]
Hello.....Everyone

can you help me how to connect bridge with two Server (Ubuntu server to Ubuntu server) in installed both server mosquitto.
 
and give example link. 

Thanks!!... :)

**Comment by toast-uz** [comment]
I think this link helps you.
http://www.steves-internet-guide.com/mosquitto-bridge-configuration/

**Comment by toast-uz** [comment]
Closing because seemed solved.
