### ISSUE TITLE
Doc glitch in mosquitto.conf.5 / mount_point

### ISSUE THREAD

**Issue by moberhuber** [eclipse/mosquitto#520]
Looking at the docs for mosquitto.conf.5 / mount_point , line 701 here:
https://github.com/eclipse/mosquitto/blob/master/man/mosquitto.conf.5.xml

I think that "...in the topic hierarchy <replaceable>example</replaceable> and above."
should instead read
"...in the topic hierarchy <replaceable>example</replaceable> and below."

since my understaning is, that mount_point will be a forced prefix of any topic.

**Comment by toast-uz** [comment]
I agreed. Could you make PR on fixes branch to fix this issue?

**Comment by ralight** [comment]
This is fixed in my local fixes branch and will be part of 1.5.3 later today.
