### ISSUE TITLE
bridge_protocol_version in default.conf causes Mosquitto to crash

### ISSUE THREAD

**Issue by matswebjorn** [eclipse/mosquitto#521]
I have Mosquitto 1.4.8 installed on an Ubuntu 16.04 LTS with the following configuration 
`
allow_anonymous false
password_file /etc/mosquitto/passwd
bridge_protocol_version mqttv311
`
This results in the following log
`
Opening ipv4 listen socket on port 1883
Opening ipv6 listen socket on port 1883
Error in poll: Interrupted system call.
mosquitto version 1.4.8 terminating
`
But if I comment out `bridge_protocol_version mqttv311` then mosquitto starts without problem.

**Comment by toast-uz** [comment]
Does this always reproduce?
According to the error message, it seems that there was another interrupt during the POLL system call. The other interrupts supposed to be masked beforehand calling POLL, but there may be an unmasked interrupt specific to Ubuntu.
I'm not sure about the relationship with bridge_protocol_version.

**Comment by matswebjorn** [comment]
Yes, it did. If I enable the 'mqttv311' option then it fails

**Comment by toast-uz** [comment]
Could you show whole configuration of both of bridge origin and target? At least, there must be the information of bridge target you did not show. Of course, you can mask specific information such as global IP. If you can minimize them (e.g. Is allow_anonymous false necessary for the issue? If not, delete it.) keeping the issue, it helps understanding.

**Comment by matswebjorn** [comment]
I've poked around in my configuration so that it doesn't need to set the bridge_protocol_version option in order to get the system to work, so my config isn't representative anymore. Have you tried to set the bridge_protocol_version option in your system?

**Comment by toast-uz** [comment]
Yes but my environment was CentOS. I would like to try your detailed configuration on CentOS in order to clarify if this issue depends on OS.

**Comment by toast-uz** [comment]
Of course, I want the minimum set of whole configurations of both of bridge origin and target you can reproduce the issue.

**Comment by matswebjorn** [comment]
OS: Ubuntu 16.04 LTS 64-bit
Mosquitto installed with "sudo apt-get install mosquitto mosquitto-clients"
Config:
log_type debug
log_type error
log_type warning
log_type notice
log_type information
allow_anonymous false
password_file /etc/mosquitto/passwd

This config works. When I restart the mosquitto running in the background I see the following log:
1506013226: mosquitto version 1.4.8 (build date Mon, 26 Jun 2017 09:31:02 +0100) starting
1506013226: Config loaded from /etc/mosquitto/mosquitto.conf.
1506013226: Opening ipv4 listen socket on port 1883.
1506013226: Opening ipv6 listen socket on port 1883.
1506013227: New connection from 127.0.0.1 on port 1883.
1506013227: New client connected from 127.0.0.1 as mosqsub/1965-heimdall (c1, k60, u'nodemcu').
1506013227: Sending CONNACK to mosqsub/1965-heimdall (0, 0)
1506013227: Received SUBSCRIBE from mosqsub/1965-heimdall
1506013227: 	nodemcu/oil (QoS 0)
1506013227: Sending SUBACK to mosqsub/1965-heimdall
1506013241: New connection from 127.0.0.1 on port 1883.
1506013241: New client connected from 127.0.0.1 as mqtt_ae22d405.fa1c58 (c1, k60, u'nodemcu').
1506013241: Sending CONNACK to mqtt_ae22d405.fa1c58 (0, 0)
1506013241: Received SUBSCRIBE from mqtt_ae22d405.fa1c58
1506013241: 	nodemcu/oil (QoS 0)
1506013241: Sending SUBACK to mqtt_ae22d405.fa1c58
1506013287: Received PINGREQ from mosqsub/1965-heimdall

Then I add "bridge_protocol_version mqttv311" to the config and restart the server. This produces the following log, where mosquitto at the end terminates:
1506013226: mosquitto version 1.4.8 (build date Mon, 26 Jun 2017 09:31:02 +0100) starting
1506013226: Config loaded from /etc/mosquitto/mosquitto.conf.
1506013226: Opening ipv4 listen socket on port 1883.
1506013226: Opening ipv6 listen socket on port 1883.
1506013227: New connection from 127.0.0.1 on port 1883.
1506013227: New client connected from 127.0.0.1 as mosqsub/1965-heimdall (c1, k60, u'nodemcu').
1506013227: Sending CONNACK to mosqsub/1965-heimdall (0, 0)
1506013227: Received SUBSCRIBE from mosqsub/1965-heimdall
1506013227: 	nodemcu/oil (QoS 0)
1506013227: Sending SUBACK to mosqsub/1965-heimdall
1506013241: New connection from 127.0.0.1 on port 1883.
1506013241: New client connected from 127.0.0.1 as mqtt_ae22d405.fa1c58 (c1, k60, u'nodemcu').
1506013241: Sending CONNACK to mqtt_ae22d405.fa1c58 (0, 0)
1506013241: Received SUBSCRIBE from mqtt_ae22d405.fa1c58
1506013241: 	nodemcu/oil (QoS 0)
1506013241: Sending SUBACK to mqtt_ae22d405.fa1c58
1506013287: Received PINGREQ from mosqsub/1965-heimdall
1506013287: Sending PINGRESP to mosqsub/1965-heimdall
1506013301: Received PINGREQ from mqtt_ae22d405.fa1c58
1506013301: Sending PINGRESP to mqtt_ae22d405.fa1c58
1506013347: Received PINGREQ from mosqsub/1965-heimdall
1506013347: Sending PINGRESP to mosqsub/1965-heimdall
1506013361: Received PINGREQ from mqtt_ae22d405.fa1c58
1506013361: Sending PINGRESP to mqtt_ae22d405.fa1c58
1506013407: Received PINGREQ from mosqsub/1965-heimdall
1506013407: Sending PINGRESP to mosqsub/1965-heimdall
1506013421: Received PINGREQ from mqtt_ae22d405.fa1c58
1506013421: Sending PINGRESP to mqtt_ae22d405.fa1c58
1506013424: Error in poll: Interrupted system call.
1506013424: mosquitto version 1.4.8 terminating

There are two clients connecting to mosquitto, both running on the same machine: 
mosquitto_sub and a NodeRED instance with a mqtt connector

**Comment by toast-uz** [comment]
Why didn't you add other bridge configurations such as connection and address? I guess the bridge cannot run without them.
See http://www.steves-internet-guide.com/mosquitto-bridge-configuration/

**Comment by toast-uz** [comment]
Any additional information?

**Comment by matswebjorn** [comment]
I have a very limited amount of time to spend debugging parts which I anticipate should work "out of the box". I've now got the system working so this issue is no longer critical for getting the main (much bigger) task done, where I have to put all effort.
I've given input how to reproduce a problem which I anticipate should have been caught by the release test procedure, namely testing various configurations. So I don't have anything more to add.
