### ISSUE TITLE
Win32 mosquitto_sub and mosquitto_pub crashes on start

### ISSUE THREAD

**Issue by matswebjorn** [eclipse/mosquitto#527]
I've just downloaded and installed mosquitto 1.4.14 for my Windows 10 x64 box from [http://www.eclipse.org/downloads/download.php?file=/mosquitto/binary/win32/mosquitto-1.4.14-install-win32.exe], and installed Win32_OpenSSL and pthreads-w32-2-9-1-release.

mosquitto and mosquitto_passwd runs fine from the installation directory, but if I try to start mosquitto_pub or mosquitto_sub then they immediately crash with 0xc000007b.

I've tried to run with either OpenSSL x32 or OpenSSL x64 or both but with the same result. What's so different with the *pub and *sub from mosquitto which seems to be happy with my installation. Any cllue someone?

**Comment by toast-uz** [comment]
Does mosquitto-1.4.14-install-win32.exe support 64bit Windows?

**Comment by matswebjorn** [comment]
The download page for Windows just says "Native build, Windows Vista and up". But what's really odd is that now the [Eclipse website ](https://projects.eclipse.org/projects/technology.mosquitto) claims that 1.4.12 is "Current", and the download page points to 1.4.9 . But the 1.4.14 link that I've used is still valid!! 
Beats me how I got to the 1.4.14 download-link, but I'm absolutely certain that I just went to the download page.

**Comment by toast-uz** [comment]
I agree mosquitto-1.4.14-install-win32.exe is current, but I'm not sure mosquitto supports 64bit Windows. Generally, Win32 application doesn't always run on WOW64 emulation environment of 64bit Windows.

**Comment by matswebjorn** [comment]
1.4.14 is current? Main page doesn't say so, and the download page points to 1.4.9 for Windows.
The download page doesn't state that there aren't any restrictions for x64. So then one would assume that there is at least some minimal test on x64 before the build is published to make sure that the executables at least start

**Comment by toast-uz** [comment]
Definitely 1.4.14 is the latest version of master branch.

**Comment by toast-uz** [comment]
Found similar discussion at #261

**Comment by JHPSoft** [comment]
I had same problems.
when I downloaded 'mos.7z' at this link(http://www.steves-internet-guide.com/downloads/)
and just unzip and execute at unziped folder.
(my case, /mos/mosquitto_sub.exe)
It works without 0xc000007b error.
(I already installed mosquitto which makes error. and I didn't deleted that)

My workspace is Windows server 2016(x64) maybe similar to windows 10, 
and OpenSSL 1.0.2h light(32-bit), VC++ 2015 Redistributable(x64) is installed

**Comment by ralight** [comment]
The Windows version has changed substantially since this was reported, in particular with fewer external libraries being used to make installation easier. I don't believe this should be an issue any more, but if it please reopen and provide more details.
