### ISSUE TITLE
Raspbian Stretch install error

### ISSUE THREAD

**Issue by Obo666** [eclipse/mosquitto#529]
Issue:
cannot install Mosquitto under Raspbian Stretch, following instructions at https://mosquitto.org/2013/01/mosquitto-debian-repository/
with http://repo.mosquitto.org/debian/mosquitto-stretch.list

Error:
pi@raspberrypi:/etc/apt/sources.list.d $ sudo apt-get install mosquitto
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mosquitto : Depends: libssl1.0.0 (>= 1.0.1) but it is not installable
             Depends: libwebsockets3 (>= 1.2) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by hemantkamalakar** [comment]
I am facing the same issue.
`The following packages have unmet dependencies:
 mosquitto : Depends: libssl1.0.0 (>= 1.0.1) but it is not installable
             Depends: libwebsockets3 (>= 1.2) but it is not installable
E: Unable to correct problems, you have held broken packages.`

**Comment by Obo666** [comment]
Yeah, I think quite a few people are. Appears to be a bit of a show stopper. Hopefully a response will be forthcoming.

**Comment by VitaliyZn** [comment]
Same problem(((

**Comment by UriWise** [comment]
Same here :(

**Comment by pauloreal1** [comment]
one more here. same problem in stretch

**Comment by pcmaik** [comment]
Same problem :(

**Comment by szmolnar** [comment]
same issue :-(

**Comment by puytr** [comment]
Same problem :-( Did a clean install twice, to no avail.

**Comment by maddhin** [comment]
same issue:(

**Comment by cflurin** [comment]
have a look here:
https://www.raspberrypi.org/forums/viewtopic.php?t=191027

... build from source

**Comment by MikePRoberts** [comment]
Is this linked to Debian Stretch dropping SSH1- and hence a broader Linux issue?  See
https://www.debian.org/releases/stable/i386/release-notes/ch-information.en.html

**Comment by shubhamt619** [comment]
It works..Everything is working after i used aptitude

**Comment by shubhamt619** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?t=191027#p1203764

**Comment by MikePRoberts** [comment]
Thank you for your quick reply.

A reply on the forum link below suggests that the problem would be solved by your updating your dependency list.  Doing this would enable a load of people using the Pi for IoT and to load Mosquitto the normal way.  Could you do this?

Thank you

Mike

**Comment by spacemishka** [comment]
same here. Could u fix it for Debian Stretch?

Thanks

**Comment by nmaas87** [comment]
would be awesome, thanks a lot!

**Comment by aniketdali** [comment]
I tried this to fix it
wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_amd64.deb
 sudo dpkg -i libssl1.0.0_1.0.1t-1+deb8u6_amd64.deb

**Comment by tmofoshodo** [comment]
The following packages have unmet dependencies:
 mosquitto : Depends: libssl1.0.0 (>= 1.0.1) but it is not installable
             Depends: libwebsockets3 (>= 1.2) but it is not installable
E: Unable to correct problems, you have held broken packages.


aniketdali's comment above will fix the libssl1.0.0 error... but libwebsockets3 is still not installable.

**Comment by davyike** [comment]
Hi all, following aniketdali's tip I've used the following to install on Raspberry Pi with Debian Stretch:

```
cd ~
wget http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
sudo apt-key add mosquitto-repo.gpg.key
cd /etc/apt/sources.list.d/
sudo wget http://repo.mosquitto.org/debian/mosquitto-stretch.list
sudo apt-get update

cd ~
wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_armhf.deb
sudo dpkg -i libssl1.0.0_1.0.1t-1+deb8u6_armhf.deb
wget http://ftp.nz.debian.org/debian/pool/main/libw/libwebsockets/libwebsockets3_1.2.2-1_armhf.deb
sudo dpkg -i libwebsockets3_1.2.2-1_armhf.deb
sudo apt-get install mosquitto mosquitto-clients
```

**Comment by BITRU** [comment]
davyike thank you! worked.

**Comment by tmofoshodo** [comment]
@davyike what model raspberry pi are you using?

**Comment by davyike** [comment]
@tmofoshodo I'm using a Pi 3 Model B. Don't think that should matter as much as the Raspbian image though, I am using the latest Raspbian Stretch Lite, release date 2017-09-07.

**Comment by tmofoshodo** [comment]
@davyike Thanks for the reply.  I am using a Pi Zero W.  Your steps allowed me to install Mosquitto, but I get "Illegal Instruction" when I try to run it.  I'm thinking it might be because Pi Zero W uses ARMv6.  I am going to try on my Pi 3 tonight.

**Comment by davyike** [comment]
@tmofoshodo Ah good point. Yes you may need the armel version instead of the armhf version? I'm not very familiar with that though so do your own research.
You can see all the packages here: [https://packages.debian.org/jessie/libwebsockets3](https://packages.debian.org/jessie/libwebsockets3)
Same would apply for openssl: [https://packages.debian.org/stretch/openssl](https://packages.debian.org/stretch/openssl)
Looking at that I see there's a much newer version of OpenSSL than I'd referenced earlier.

If you can confirm that it's needing armel then the following packages _should_ work (you'll want to uninstall the other ones first of course):
```
http://http.us.debian.org/debian/pool/main/o/openssl/openssl_1.1.0f-3_armel.deb
http://http.us.debian.org/debian/pool/main/libw/libwebsockets/libwebsockets3_1.2.2-1_armel.deb
```

Let me know if you have any luck with that.

**Comment by jahnroux** [comment]
@davyike I am having the same issue on my Pi Zero W. I am running stretch on my Pi 2 and on my Pi Zero W. I am able to use the work around of manually installing libssl and libwensockets3 for the Pi 2 and I can get mqtt running. However, the same process on the Pi Zero W causes me to get the error message:

`pi@raspberrypizero:~ $ mosquitto
Illegal instruction`

I have uninstalled, reinstalled, updated, rebooted, you name it. I can't get mqtt to run on a pi zero under stretch. I may have to reinstall with Jessie tonight.

**Comment by maddhin** [comment]
@jahnroux: did you try davyike's fix w/ the armal packages just one post above?

**Comment by jahnroux** [comment]
@maddhin yes, see below:

```
pi@raspberrypizero:~ $ sudo dpkg -i libwebsockets3_1.2.2-1_armel.deb
dpkg: error processing archive libwebsockets3_1.2.2-1_armel.deb (--install):
 package architecture (armel) does not match system (armhf)
Errors were encountered while processing:
 libwebsockets3_1.2.2-1_armel.deb
pi@raspberrypizero:~ $
```

armel is not compatible with the Pi Zero architecture. I also tried libssl-armel, openssl-armel, all the same issue.

**Comment by davyike** [comment]
@jahnroux It looks like that error message is telling you that you should be using armhf packages, in which case go back to my earlier post. I'm not 100% sure on which Pi models have which architecture, so that exercise is left to the reader :)

**Comment by jahnroux** [comment]
@davyike that is what I am trying to explain, your earlier approach works for my Pi 2, not my Pi Zero. Both the 2 and zero are running stretch. So I am able to install the armhf libssl and libwebsocket3 packages but mosquitto will not start on my Pi Zero. On the Pi 2 I was able to install and get mosquitto running.

**Comment by davyike** [comment]
@jahnroux I see, sorry I misunderstood earlier. I don't have a Pi Zero so am not able to play around and try that. I wonder if @tmofoshodo had any luck? Perhaps it's not the OpenSSL and Websocket3 packages that have the problem, maybe it's the Mosquitto package? Just throwing some ideas out there. If there's a way for you to verify if the OpenSSL and Websocket3 libraries are working, independently from Mosquitto, that would be a good first step.

**Comment by jahnroux** [comment]
@davyike thanks, yeah I don't expect you to solve my problem, I just wanted to let it be known that I ran into the same issue as @tmofoshodo 

I will hack together something tonight to test the packages interdependently before I reinstall with Jessie.

**Comment by jipp** [comment]
Hi

I ran into the same issue. it looks like that stretch has libssl 1.0.2 installed by default.
libwebsockets3 is not available at all.

I'm not a developer but I see a libwebsockets8 library available on stretch

one way around would be to add the jessie sources in the /etc/apt/sources.list.d/ folder - but then I get a mixture of stretch and jessi on the system - which I would like to avoid.

I'm a little clueless now as from the libs I would suggest that libssl is a broken dependency which needsto be removed for mosquitto on Stretch.
For libwebsockets I cannot judge how much effort it would be to update to a new websocket lib.

**Comment by sevos** [comment]
This worked for me:

```
wget http://ftp.us.debian.org/debian/pool/main/libw/libwebsockets/libwebsockets3_1.2.2-1_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.2l-1~bpo8+1_armhf.deb
sudo dpkg -i libwebsockets3_1.2.2-1_armhf.deb
sudo dpkg -i libssl1.0.0_1.0.2l-1~bpo8+1_armhf.deb

# If dpkg reported any packages missing, I used apt-get to get them from stretch repo

sudo apt-get install mosquitto
```

**Comment by pappumaster** [comment]
I am running into the same problems as @jahnroux and @tmofoshodo. I keep receiving illegal instruction whenever I try to run mosquitto. I also tried @sevos solution, but still get the same illegal instruction problem.

Has anyone been able to successfully fix this problem?

**Comment by artreaktor** [comment]
@sevos workaround fixed the issue for me
pi@pi1:~ $ cat /etc/*-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"

**Comment by ThomDietrich** [comment]
@ralight an official statement by the maintainers regarding this issue would be interesting. It seems like a rather important one to sort out - as the comments have shown...
Is anyone looking into a solution or can you give a few details about the challenges? What are the next steps? Very much appreciated! Thanks

**Comment by Cancelor** [comment]
https://www.eclipse.org/forums/index.php?t=msg&th=1089302&goto=1773991&

**Comment by schaumannj** [comment]
+1
Dear authors,
could you please release ore rebuild the mosquitto with new open SSL library to prevent the security risk in version 1.0.0.
Thank you in advance
Jan

**Comment by kostousov-ds** [comment]
> https://www.eclipse.org/forums/index.php?t=msg&th=1089302&goto=1773991&

doesn't work
```
root@pi1:/tmp/mosquitto# mosquitto v
mosquitto: /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by mosquitto)
mosquitto: /usr/lib/arm-linux-gnueabihf/libssl.so.1.0.0: version `OPENSSL_1.0.1' not found (required by mosquitto)
mosquitto: /usr/lib/arm-linux-gnueabihf/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by mosquitto)
```

**Comment by consolacion** [comment]
I only came upon this discussion after I managed to install it.
this is what I did (after I got the unmet dependencies error:
sudo aptitude install mosquitto.
That presented me with  options to "solve it"
![mosquittosolve](https://user-images.githubusercontent.com/8614925/34320806-bef1c25a-e801-11e7-8505-886bc1164362.png)
the first choice i cose 'n', as it would leave the situation intact.
Then I got the option to install the unmet dependencies, for which I chose 'Y'

That did it for me

**Comment by s-hemer** [comment]
But this installs just the version available in the standard Raspbian repository. Funny enough that the package there has the correct dependencies whereas the one from http://repo.mosquitto.org/debian stretch main still depends on libwebsockets3

**Comment by consolacion** [comment]
yes, correct. But in the end I cared more about having an installable 'old' version  than a non installable 'new version'
makes one wonder, wouldnt anybody have tried installing it on stretch before releasing it into thatrepository?

**Comment by Dan-in-CA** [comment]
It is really not that hard to build mosquitto from source on raspbian stretch. See this post:
https://xperimentia.com/2015/08/20/installing-mosquitto-mqtt-broker-on-raspberry-pi-with-websockets/

If you are building on a Raspi with a quad core processor it does not take long either.

**Comment by consolacion** [comment]
Thanks, I will check that out. When i did  my 'solution' I only discovered afterwards that it installed a previous mosquitto distribution, but I didnt really mind. Nevertheless, I´ll give  the link a try

**Comment by rogertheriault** [comment]
@Dan-in-CA thanks - your step by step instructions worked for me (Pi 3, stretch). Reminds me of the days when "make" was really the only option on unix/linux.

**Comment by Dan-in-CA** [comment]
@rogertheriault, 
Thanks for the feedback. 
Looks like the post is getting a lot of traffic but this is the first report of results.

**Comment by rogertheriault** [comment]
@Dan-in-CA that's possibly originating here, that's where I started. Though, compared to his video, my Pi wasn't dusty, it was a newly minted Stretch... (tho I do have some dusty units)
http://bitluni.net/simple-mqtt-broker-setup-on-a-raspberry-pi/

**Comment by borch84** [comment]
@Dan-in-CA  I confirm I was able to install mosquitto using the instructions provided for raspbian stretch

**Comment by jahnroux** [comment]
Has anyone tried the solution in Raspberry Pi Zero W?

**Comment by PierreF** [comment]
This issue if probably "just" #581 (i.e. not related to Rapsbian but only to Stetch).

**Comment by garymcleanuk** [comment]
Had same issue. This fixed (allowed me to work around) it for me.. Add the following line into:- /etc/apt/sources.list/
deb http://archive.raspbian.org/raspbian jessie main contrib non-free

Then run.
sudo apt-get update
sudo apt-get install mosquitto

This new repository let me download and install the old dependencies. Though, it should be using the newer SSL LIBS!!.

**Comment by sihui62** [comment]
Following this post from @Dan-in-CA 

https://xperimentia.com/2015/08/20/installing-mosquitto-mqtt-broker-on-raspberry-pi-with-websockets/

I found an update on that tutorial:

>Updated January 15 2018
As of Jan. 14 2018 the install from the Mosquitto debian repository has been fixed and installs mosquitto with websockets enabled without error.

Bingo, 1.4.14 installs without any errors on a fresh Raspbian Stretch install (RPi3, did not try an RPi Zero)

`Holen:1 http://repo.mosquitto.org/debian stretch/main armhf mosquitto armhf 1.4.14-0mosquitto2 [127 kB]`

**Comment by ralight** [comment]
@swampdogmash It could be that the cpu architecture I've got the packages built for are ARMv7 not the ARMv6 that the zero has. I'll take a look.

**Comment by swampdogmash** [comment]
Oddly I've just built it using the instructions and it worked.... until i installed it as a service....

The following was run after make install completed...

pi@homeautctrl:~ $ mosquitto
1516826943: mosquitto version 1.4.14 (build date 2018-01-24 20:44:55+0000) starting
1516826943: Using default config.
1516826943: Opening ipv4 listen socket on port 1883.
1516826943: Opening ipv6 listen socket on port 1883.

After continuing with the install instructions @ [https://xperimentia.com/2015/08/20/installing-mosquitto-mqtt-broker-on-raspberry-pi-with-websockets/](url)  I then went back to the same issue.

I skipped all the config file editing steps so the config was still identical, simply installed the "git" package, grabbed the unit file and installed as a service...

I was confused before, now I'm baffled but hopefully heping get closer to the issue.

**Comment by swampdogmash** [comment]
... and to make things more confusing i seem to have one shell window open in which Mosquitto will run and one where it won't!

**Comment by swampdogmash** [comment]
To make matters more confusing i seem to have one ssh session where it runs and one where it doesn't

![image](https://user-images.githubusercontent.com/35781133/35357346-24028e24-014b-11e8-8b04-ea367125f7b1.png)

**Comment by swampdogmash** [comment]
..doing nothing it now seems to run manually in all the shells. After a reboot it can be started manually but won't start using the service commands or as part of the boot process. I get the following now:

` mosquitto.service - Mosquitto MQTT Broker daemon
   Loaded: loaded (/etc/systemd/system/mosquitto.service; enabled; vendor preset
   Active: activating (start) since Wed 2018-01-24 21:35:25 GMT; 22s ago
  Process: 1033 ExecStart=/usr/local/sbin/mosquitto -c /usr/local/etc/mosquitto/
   CGroup: /system.slice/mosquitto.service
           └─1034 /usr/local/sbin/mosquitto -c /usr/local/etc/mosquitto/mosquitt

Jan 24 21:35:25 homeautctrl systemd[1]: Starting Mosquitto MQTT Broker daemon...
Jan 24 21:35:25 homeautctrl systemd[1]: mosquitto.service: PID file /var/run/mosquitto not readable (yet?)`

and it seems hung

**Comment by Dan-in-CA** [comment]
You probably need to edit the unit file (moaquitto.service) to point to the exact location of the mosquitto executable and the config file.

**Comment by swampdogmash** [comment]
on it

**Comment by jsaldivias** [comment]
Found the same problem, solved using Consolacion method. Thanks. I agree with you." yes, correct. But in the end I cared more about having an installable 'old' version than a non installable 'new version' "

**Comment by ralight** [comment]
I believe all problems with Raspbian Stretch should now be resolved. I will leave this open another day or so, then close it if there are no further problems.

**Comment by jipp** [comment]
For me the problem is solved
Running fine on raspbian stretch

**Comment by jsaldivias** [comment]
Thanks.Everything is working fine now.  Saludos cordiales, MBA Ing. Jimmy SaldiviasConsultor Proyectos Eléctricos Celular: 593 9 39734688E-mail: j_saldivias@yahoo.com

**Comment by ralight** [comment]
I'm closing this issue then, if you still have problems feel free to reopen it.

**Comment by sharatkanthi** [comment]
This is because the web socket library is not installed. Try running 

sudo apt-get install libwebsockets-dev

before running 

sudo apt-get install mosquitto

**Comment by BouldBadger** [comment]
Hi All,

Did anyone get to the bottom of this? My head is melted
If anyone could help it would be greatly appreciated!!

pi@raspberrypi:/etc/apt/sources.list.d $ sudo apt-get install mosquitto
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mosquitto : Depends: libssl1.0.0 (>= 1.0.1) but it is not installable
             Depends: libwebsockets3 (>= 1.2) but it is not installable
N: Ignoring file 'mosquitto-stretch.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
E: Unable to correct problems, you have held broken packages.
pi@raspberrypi:/etc/apt/sources.list.d $

**Comment by schaumannj** [comment]
Hi,
my solution was to download the sources and build it on Pi. The following steps will describe how to do.
First, you need download the source from site https://mosquitto.org/download/ or clone from github https://github.com/eclipse/mosquitto.


**Install dependencies**

sudo aptitude install libssl-dev
sudo aptitude install libc-ares-dev
sudo aptitude install libwebsockets-dev
sudo aptitude install uuid-dev


**Build mosquitto**

git clone git@github.com:eclipse/mosquitto.git
cd mosquitto
make
# run it
cd src/
./mosquitto
The executable library mosquitto is located in src directory. Enjoy messaging :)

**Comment by BouldBadger** [comment]
Hey schaumannj, thanks for the promt response. 
What do you mean by "build it on Pi" 
So I've download the compressed folder from the link above but I'm not very clear on where to go from there..if you don't mind would you be able to give me a bit of a walk through. 
Thanks again. I'd really appreciate it!!

**Comment by schaumannj** [comment]
Hi BouldBadger,
build it  - > https://en.wikipedia.org/wiki/Make_(software)
on Pi -> raspberry pi, the device itself.

in Linux word is common to build/create the application on particular Linux distribution. it means that each Linux distribution(Ubuntu, Debian, Fedora) has own package on an application which may not be compatible across the distribution. Therefore Linux community share source of the application and you are free to create the application on your favorite distribution. In Windows world, there is mostly only one package for distribution *.exe file.

**Comment by BouldBadger** [comment]
Thanks for your patience exlaining I understand the term now. :)

This is prob very basic so bare with me! 
So I've downloaded the source file to my pc and extracted it. Not sure how to build it on my pi. 
I transferred the files to the Pi via usb and tried running them but no joy. 
On a pc it would be very straight forward - just run the .exe but not sure what to do to build it on my Pi.
As for the other github link there are a million and one files and eqully don't know what to do with any of them.

Thanks!

**Comment by schaumannj** [comment]
there is the package which I use on my Pi https://github.com/schaumannj/mosquitto/tree/master/output
good luck

**Comment by BouldBadger** [comment]
Thanks man, I install it on the pi with "wine" ya?

**Comment by ralight** [comment]
```
Depends: libssl1.0.0 (>= 1.0.1) but it is not installable
Depends: libwebsockets3 (>= 1.2) but it is not installable
```

This suggests you are using the Wheezy version of Raspbian. The Mosquitto packages don't support Wheezy because nobody else supports Wheezy. I would suggest upgrading your Pi to Stretch or Jessie if you can, otherwise the only option is to compile manually.

**Comment by BouldBadger** [comment]
Thanks ralight,

I have stretch installed on a raspberry pi. I'm tempted to change to Jessie as I've had no success. What do you think?

**Comment by ralight** [comment]
Ok, I've checked the packages and the jessie version is the one that depends libwebsockets3. You should check your `/etc/apt/sources.list.d/` directory to make sure the mosquitto related entries are all pointing to stretch.

On that note, you have the following error above, which may be related. All the files should end in just `.list`.
```
N: Ignoring file 'mosquitto-stretch.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
```

**Comment by BouldBadger** [comment]
I would happily pay someone to ssh into my pi and resolve this for me. 
I clearly don't have the knowledge or experience to resolve this on my own and will be annoying everyone here with endless questions. :/

**Comment by kostousov-ds** [comment]
> I would happily pay someone to ssh into my pi and resolve this for me.
> I clearly don't have the knowledge or experience to resolve this on my own and will be annoying everyone here with endless questions. :/

How to contact you?

**Comment by kostousov-ds** [comment]
A couple of years ago, I put together a Mosquitto for stretch. Now it works for me. Where can I upload files?

**Comment by BouldBadger** [comment]
Hey, was away for a bit and didn't see the post. Would be great if you could uplaod it here
https://1drv.ms/f/s!Ah6E3xrT3kXzgZZ5TyGUbHa7W6UM3w

Thanks in advance, appreciate the help!

**Comment by kostousov-ds** [comment]
try this
https://www.dropbox.com/sh/sj8ff4ynldduuqv/AADioWGzt8tJvEUS72b2l6bAa?dl=0

18.07.2019 4:30, BouldBadger пишет:

**Comment by kostousov-ds** [comment]
```
sudo dpkg -i mosquitto_1.4.14-0mosquitto1.2_armhf.deb mosquitto-clients_1.4.14-0mosquitto1.2_armhf.deb libmosquitto1_1.4.14-0mosquitto1.2_armhf.deb
```
