### ISSUE TITLE
Travis OS-X test failed from Oct 5, 2016

### ISSUE THREAD

**Issue by toast-uz** [eclipse/mosquitto#533]
Travis OS-X test failed from Oct 5, 2016 on master and develop branch.
From then, travis OS-X test has used Apple LLVM version 7.3.0 and failed to find OpenSSL. Seemed to fix travis-install.sh or .travis.yml.

**Comment by ralight** [comment]
This is fixed now, thanks for the report. I suppose we shouldn't allow mac to fail either actually.
