### ISSUE TITLE
Setting "connection_messages false" still logs a "New connection from X on port Y." message

### ISSUE THREAD

**Issue by cjmaynard** [eclipse/mosquitto#537]
Regarding the connection_messages option, the [mosquitto.conf man page](https://mosquitto.org/man/mosquitto-conf-5.html) reads:

       connection_messages [ true | false ]
           If set to true, the log will include entries when clients connect
           and disconnect. If set to false, these entries will not appear.

With the default of "connection_messages true", and using mosquitto_pub to test, I see messages like so:

    1504137323: New connection from 127.0.0.1 on port 1883.
    1504137323: New client connected from 127.0.0.1 as mosqpub|2501-test (c1, k60).
    1504137323: Client mosqpub|2501-test disconnected.

... but with "connection_messages false", I still see this message:

    1504137889: New connection from 127.0.0.1 on port 1883.

I would not expect to see that message when setting "connection_messages false".

**Comment by karlp** [comment]
the variable name is perhaps bad, in that it says connections, but the manual text says it's the logs on clients, and that's true?  I'd probably generally agree though, that it's not the ideal behaviour

**Comment by toast-uz** [comment]
+1
I agree this option is not implemented  consistently.
