### ISSUE TITLE
Bridge Enhancement: Add a writable $SYS/broker/bridge/disconnect topic for [temporarily] disconnecting a bridge connection.

### ISSUE THREAD

**Issue by cjmaynard** [eclipse/mosquitto#539]
I posted a query about this and didn't receive any negative feedback about the idea, so I’m opening an enhancement request here in the hope that it could be implemented.  My post is here: http://dev.eclipse.org/mhonarc/lists/mosquitto-dev/msg01611.html.

Basically, I have a bridge that can connect to more than one possible remote broker, each one reachable via a separate interface.  I would like to be able to force the bridge to close its current connection under certain conditions so that it can establish a new connection with the alternate remote broker much quicker than it otherwise would.

The specific use case that I have is that if I’m able to detect that an interface is down (such as if the Ethernet cable becomes disconnected), I would like to cause the bridge to immediately abandon its current connection if it happens to be communicating with a remote broker over that particular interface so that it can more quickly establish a connection with the other remote broker over the other interface, rather than having to wait for timers to expire, which takes much longer to occur.  It is possible to reduce timeout values somewhat, such as the keepalive value, but it’s still not responsive enough and has the unfortunate side-effect of introducing more frequent traffic, which we’d also like to avoid.  It’s important for us to remain connected as much as possible in the event data needs to be sent, but we need to keep data usage as low as possible when we’re not actively transmitting data.  I would think data usage would be a common concern for many people?

I’ve seen some recent activity surrounding issue #535 and while I don’t think the resolution of that issue will directly solve this one, there does seem to be interest in being able to control the broker via writable topics, so in keeping with issue #535, I might propose a writable topic of `$SYS/broker/bridge/disconnect` as a possible solution to this issue.  I’m open to other possible alternatives that accomplish the same goal though.  I’m also fine with adding “`allow_sys_update true`” to the`mosquitto.conf` file, as described in issue #535.

**Comment by toast-uz** [comment]
Hi,
Different from what you want to do, FYI, I tested optimization of current bridge timers in the dual bridge uplink configuration.

Default setting:
- Detecting the disconnection of primary bridge uplink: 60s
- Connecting alternative: 31s
- total: 91s
- background traffic: 0.5 bps/connection (2byte PING * bi-direction / 60s)

Optimized setting:
- Detecting the disconnection of primary bridge uplink: 5s (by setting keepalive_interval 5)
- Connecting alternative: 2s (by setting restart_timeout 1)
- total: 7s
- background traffic: 6.4 bps/connection (2byte PING * bi-direction / 5s)

If the number of connections is less than 10k, it might be a workaround you can right now of your situation.

**Comment by toast-uz** [comment]
@cjmaynard , could you close this issue as a duplicate of #584 and #535 ?

**Comment by cjmaynard** [comment]
I'd be happy to close this issue if someone could please verify that the desired functionality is in fact encapsulated within one of those other issues.  I'm not sure that it is, but I could be mistaken.

For example, I don't think the mere addition of `allow_sys_update [true | false]` means we would now have the ability to force a disconnect, nor do I think `SIGWINCH` gives us this capability either, as that seems to behave differently, i.e., _"The SIGWINCH signal causes mosquitto to try to reconnect to all bridges, which are disconnected at the moment."_

**Comment by toast-uz** [comment]
I think your request is on the road beyond #535 .
You can add a comment and a link of your request on #535 rather than keeping this independent issue.

**Comment by fcarlier** [comment]
on #653 

Envoyé de mon terminal mobile

**Comment by cjmaynard** [comment]
I was asked to close this issue as it will apparently be tracked as part of #535.

**Comment by toast-uz** [comment]
Sorry #535 was closed and #653 is available now. Thanks @fcarlier !
@cjmaynard could you link on #653 ?

**Comment by cjmaynard** [comment]
OK, issue #653 is now linked to this issue.
