### ISSUE TITLE
None of the CentOS / RHEL install instructions work.

### ISSUE THREAD

**Issue by CRCinAU** [eclipse/mosquitto#540]
The URL for the repos listed are dead across the board for RHEL, OpenSUSE and CentOS.

All come up with a 404 error.

**Comment by mturalenka** [comment]
according to status page from opensuse.org they have major outage now for download page:

> The data partition showed major issues - resulting in a shutdown of the file system. We are currently analyzing the problem and trying to bring the service up again.
https://status.opensuse.org/

**Comment by ralight** [comment]
I'm closing this because we haven't provided rpm packages for a while now.
