### ISSUE TITLE
libmosquitto should allow subscribing to more than 1 topic at once within a single subscibe packet.

### ISSUE THREAD

**Issue by cjmaynard** [eclipse/mosquitto#543]
The MQTT specification allows for multiple topics to be sent in a single SUBSCRIBE packet (See section 3.8 of http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf, and specifically the example provided in section 3.8.3.1, table 3.5 and Figure 3.23).  As far as I can tell, libmosquitto does not allow a client to subscribe to more than 1 topic at a time, but it ought to allow a client to make use of this capability as it reduces the subscription overhead and the number of application turns, which can be especially noticeable if the client is subscribed to many different topics (and not necessarily to '#').

**Comment by Elko29** [comment]
Hi cjmaynard,

It is quite to subscribe to several topics in a Mosquitto client !

You need to use `mosquitto_subscribe()` function and you can call it as many time as you need to subscribe  : 
```
mosquitto_subscribe(mosq,NULL,"tata/toto1",0);
mosquitto_subscribe(mosq,NULL,"tata/toto2",0);
mosquitto_subscribe(mosq,NULL,"titi/toto",0);
```

And to process when you receive a sub you need this function :
`mosquitto_message_callback_set(mosq, on_message);`
`on_message` is a pointer to a `static void` function like as follow, where you can do whatever you want by sorting message by topic name :

```
static void on_message(struct mosquitto *m, void *udata,const struct mosquitto_message *msg) 
{
	if(!strcmp(msg->topic,"tata/toto1"))
	{
		printf("message on topic : tata/toto1");
	}

	if(!strcmp(msg->topic,"tata/toto2"))
	{
		printf("message on topic : tata/toto2");
	}

	if(!strcmp(msg->topic,"titi/toto"))
	{
		printf("message on topic : titi/toto");
	}
}
```

I'm doing this to subscribe more than 15 topics at same time and it's work very well :-)

**Comment by karlp** [comment]
@Elko29 that's not what this ticket is about.  That's of course possible, but you _can't_ do a subscribe like ```subscribe(list_of_topics, list_of_qos)```  Which is allowed in the standard.

It has a miniscule but real overhead that some people want to optimize out.

**Comment by toast-uz** [comment]
I understood the requirement. 
But in my opinion, such advanced functions are not necessary for libmosquitto. Because, paho may be a better alternative in the area of mqtt client libraries, while mosquitto may be the best in brokers.

**Comment by cjmaynard** [comment]
Perhaps it's not as important for client connections to local brokers, but I think it would be beneficial when implementing bridges with multiple topics.  It would help cut down on the overhead and number of turns.

**Comment by ralight** [comment]
This is now fixed in the `develop` branch.
