### ISSUE TITLE
Publish Denied still sends PUBACK to client even though message is not published

### ISSUE THREAD

**Issue by glynj-bsquare** [eclipse/mosquitto#547]
I'm using QOS one, and the mosquitto-auth-plugin (https://github.com/jpmens/mosquitto-auth-plug).
My client is being told that a message is published even if the auth plugin tells mosquitto that the client is not allowed to publish to a specific topic.

In read_handle.c, the ACL check that (correctly) fails to give permission is here:

	/* Check for topic access */
	rc = mosquitto_acl_check(db, context, topic, MOSQ_ACL_WRITE);
	if(rc == MOSQ_ERR_ACL_DENIED){
		_mosquitto_log_printf(NULL, MOSQ_LOG_DEBUG, "Denied PUBLISH from %s (d%d, q%d, r%d, m%d, '%s', ... (%ld bytes))", context->id, dup, qos, retain, mid, topic, (long)payloadlen);
		goto process_bad_message;
	}else if(rc != MOSQ_ERR_SUCCESS){
		_mosquitto_free(topic);
		if(payload) _mosquitto_free(payload);
		return rc;
	}
<snip>
And it jumps to here:

process_bad_message:
	_mosquitto_free(topic);
	if(payload) _mosquitto_free(payload);
	switch(qos){
		case 0:
			return MOSQ_ERR_SUCCESS;
		case 1:
			return _mosquitto_send_puback(context, mid);
<snip>

LOG output from mosquitto:
1505130599: |-- mosquitto_auth_acl_check(..., TEST-M3-1, TEST-M3-1, u/2011/TEST-M3-1, MOSQ_ACL_WRITE)
1505130599: |-- aclcheck(TEST-M3-1, u/2011/TEST-M3-1, 2) AUTHORIZED=0 by (null)
1505130599: |--  Cached  [F640CB1BAFC55ED9E56D27E9B3A4AACD8F0AF482] for (TEST-M3-1,TEST-M3-1,2)
1505130599: Denied PUBLISH from TEST-M3-1 (d0, q1, r0, m5, 'u/2011/TEST-M3-1', ... (135 bytes))
1505130599: Sending PUBACK to TEST-M3-1 (Mid: 5)

LOG output from my client (info only):
170911_114959 PubMQTTMessage() 301 MOQTT Publish: 5, Topic: u/2011/TEST-M3-1
170911_114959 onpublish_callback() 189 MOQTT Published MID: 5

Is there a way to tell from the struct mosquitto * passed to the publish callback that the message was not published? If not, how can the client know?

**Comment by toast-uz** [comment]
I think your requirement cannot be realized, because MQTT v.3.1.1 spec., chapter 3.3.5 told that "If a Server implementation does not authorize a PUBLISH to be performed by a Client; it has no way of informing that Client. It MUST either make a positive acknowledgement, according to the normal QoS rules, or close the Network Connection."

For MQTT version 5, you will get the information by PUBACK reason code 0x87 (Not authorized).

**Comment by glynj-bsquare** [comment]
Thanks, that's useful to know. I'll close this issue.
