### ISSUE TITLE
How to Tracking Mosquitto_log file in GUI base

### ISSUE THREAD

**Issue by vishuPPatel** [eclipse/mosquitto#548]
Hello.......Developer Team

i using eclipse mosquitto in ubuntu pc,it's great service.

i want to asking question for eclipse_mosquitto how to monitoring .????

1)mosquitto server is Running or exited??

2)how much user connected to server(get the numeric figure)??

3)how much user connected to the server (user list) ??

4) how to Tracking  log file in to GUI base???

above asking question is it possible for implement?? If yes how to do it??and if No why not tracing mosquitto_log file tracking into the GUI base form

**Comment by toast-uz** [comment]
You may get useful comments quickly by posting at mosquitto-dev ML (https://dev.eclipse.org/mailman/listinfo/mosquitto-dev). This place is basically for bugs.

**Comment by toast-uz** [comment]
Closing as no information for a long time.

**Comment by vishuPPatel** [comment]
How to monitor our server using any API or any GUI platform give me the information about the any service to helpful for these type problem phase.???

**Comment by toast-uz** [comment]
Sorry this place is not for questions. You can post questions at mosquitto-dev ML.
But the answer of your subject "in GUI base" might not be gotten in any mosquitto community. Because mosquitto does not offer any GUI. You had better post at somewhere generic server management communities. The answers of some of your detailed questions might be gotten at mosquitto-dev ML.

**Comment by vishuPPatel** [comment]
hello.... @toast-uz  any idea about you best (Different type of )GUI platform providing Community??

Thanks In Advance .....!!!!!

**Comment by toast-uz** [comment]
You can get useful comments quickly by posting at mosquitto-dev ML (https://dev.eclipse.org/mailman/listinfo/mosquitto-dev), or at generic MQTT forum (https://groups.google.com/forum/#!forum/m) Please close this.

**Comment by vishuPPatel** [comment]
why mosquitto server automatically stop??

Active: active (exited) since Tue 2018-04-03 04:59:29 UTC; 7h ago

Thanks!!!.....
