### ISSUE TITLE
Is the mosquitto_message_free function needed for incoming messages ?

### ISSUE THREAD

**Issue by zinahe** [eclipse/mosquitto#549]
Hi,

I understand that this function (**mosquitto_message_free**) frees the resources tied to a message. But I would like to know if it needs to be called at the end of a message_handler_callback function for incoming messages ? 

Thanks

**Comment by toast-uz** [comment]
I'm not sure what you mean. Is it a question or a report for bugs? Could you please clarify what the issue? If a question, you had better post mosquitto-dev ML.

**Comment by zinahe** [comment]
Hi,
Assume I'm writing a callback function to handle incoming messages: 

`#include <stdio.h>`
`void my_message_callback(struct mosquitto *mosq, void *obj, const struct mosquitto_message *message)`
`{`
`printf ("Got message: %s\n", (char *)message->payload);`
`}`

My question is that do I need to call **mosquitto_message_free** at the end of the function ?

Regards,

**Comment by toast-uz** [comment]
I'm not sure that. What I said was this place is for bugs and you can post mosquitt-dev ML for questions of mosquitto.

**Comment by archerian** [comment]
not sure if this has been answered elsewhere, you don't have to free the message in your callback as its done internally by _mosquitto_message_cleanup after on_message is called.

**Comment by zinahe** [comment]
@archerian, thank you. I figured it out in the end, but still, I am grateful for the response.

Cheers,
