### ISSUE TITLE
Best version of mosquitto to compile with WebSocket?

### ISSUE THREAD

**Issue by JohnzBallad** [eclipse/mosquitto#553]
I previously installed a version and after changing the config file to compile with webscokets, my mosquitto can't write logs or make persistence DB. 

In the "log" via CMD, after I type: mosquitto -c default.conf with this conf:

```user mosquitto

connection_messages true

port 1883
protocol mqtt

listener 9001
protocol websockets

autosave_interval 10
autosave_on_changes false

persistence true
persistence_file mosquitto.db
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log
allow_anonymous true
```

Still can't write logs/persistence. Should I compile a better version? For the record, I want to make a webpage just like [Paho Mqtt js](https://github.com/eclipse/paho.mqtt.javascript/tree/master/utility) to use on my local network at first. :D

**Comment by toast-uz** [comment]
You should close this issue and use mosquitto-dev ML before you are sure of bugs of mosquitto.
Regarding log, you must set directives of log_type and websockets_log_level. Further useful comments can be get on dev-ML.

**Comment by JohnzBallad** [comment]
Still confused. Still with log problems. Did you even read my issue? ._.

**Comment by toast-uz** [comment]
Sorry for confusing you. I said about just one possibility. I like to talk further at mosquitto-dev ML until this issue is classified as mosquitto itself.

**Comment by toast-uz** [comment]
Closing as no information for a long time. If you have any more information, post at mosquitto-dev ML or open a new issue.
