### ISSUE TITLE
connect to xamarin mqtt server

### ISSUE THREAD

**Issue by nm-a** [eclipse/mosquitto#554]
Hi,
Can we use this client library to connect xamarin mqtt server.

https://github.com/xamarin/mqtt

thank you
-n m reddy

**Comment by toast-uz** [comment]
This place is basically for reporting bugs of mosquitto. You should close this issue and post at https://groups.google.com/forum/#!forum/mqtt  about which mqtt client library is recommended. That place is for generic mqtt discussions.
