### ISSUE TITLE
Cannot start websocket listener, error `Unable to create websockets listener on port 9001`

### ISSUE THREAD

**Issue by ralienpp** [eclipse/mosquitto#555]
I have encountered a problem with the version of mosquitto that is distributed in the repositories of Debian Stretch, as well as the one from the Mosquitto repositories at http://repo.mosquitto.org/debian/mosquitto-stretch.list

This is my configuration file

```
listener 1883 127.0.0.1
listener 9001 127.0.0.1
protocol websockets
```

When I start the server, it fails with `Unable to create websockets listener on port 9001`. I made sure that the port is not in use by another process, and I also tried to bind it to another port, just to make sure that's not the cause.

After a lot of tinkering I noticed a related issue, https://github.com/eclipse/mosquitto/issues/170, which made me try something else, adjusting the config as such:

```
listener 1883 127.0.0.1
listener 9001
protocol websockets
```

I removed the interface from the websocket listener, effectively binding it to `0.0.0.0`. This did the trick and now mosquitto starts correctly; I then used `iptables` to block the port unless the connection comes from localhost.

My first suggestion is to make the error message more informative, so one could get some clues about why the listener cannot be created. What is puzzling is the fact that after doing this, I went back and set it to the original configuration - and it started correctly too! Obviously, something is fishy about it. How can I troubleshoot this matter?

System details:

- mosquitto 1.4.10-3
- libwebsockets8:amd64 2.0.3-2
- Debian GNU/Linux 9
- Linux debian 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux

**Comment by toast-uz** [comment]
Your first suggestion is difficult.
Mosquitto itself can show little about Websocket, because all belong with libwebsockets.
To debug websocket, you should set mosquitto.conf that:

```
log_type all
websockets_log_level 255
```

Mosquitto send websockets_log_level to libwebsockets.
Report logs if you encounter this issue again.

**Comment by toast-uz** [comment]
@ralienpp solved your issue?

**Comment by toast-uz** [comment]
Closing as no information for a long time. If you have any more information, open a new issue.
