### ISSUE TITLE
Windows service - after x time the service stops and can't be started anymore

### ISSUE THREAD

**Issue by gbr8cke** [eclipse/mosquitto#558]
Every x time (weeks), the service stops and can't be started anymore. 
The service manager tries to start it - you see the process start, but after a while the process stops.
-> A timeout was reached (30000 milliseconds) while waiting for the Mosquitto Broker service to connect.

I have to delete the service and reinstall to solve the problem...
What can I do more to debug this?

**Comment by szarta** [comment]
Is this still happening?  What platform is this, what mosquitto version is this, and what overall mosquitto configs do you have?

**Comment by gbr8cke** [comment]
The problem is solved - it was running on Windows server 2008R2 (Mosquitto 1.4.14). Our IT service changed the service path executable on a wrong way (because of a CERT remark / sweep). The CERT made the remark there are no quotes around the path during installation of the service. They advice to create the service path like this: "C:\Program Files (x86)\Siemens\Mosquitto\mosquitto.exe" run
