### ISSUE TITLE
How much Mobile data consumption while using mosquito broker?

### ISSUE THREAD

**Issue by likewwddaa** [eclipse/mosquitto#559]
If GSM client didn't sub and pub ,wat's the mobil data consumption?

**Comment by toast-uz** [comment]
Question of generic MQTT protocol? You can post at https://groups.google.com/forum/#!forum/mqtt for getting better answers.

**Comment by toast-uz** [comment]
@likewwddaa could you agree my comment?

**Comment by toast-uz** [comment]
Closing as no information for a long time.
