### ISSUE TITLE
Active (Exited) server how to automatically run running stage ????

### ISSUE THREAD

**Issue by vishuPPatel** [eclipse/mosquitto#561]
bellow generated log that show acctive but(Exited) this is how to running automatically 

● mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
   Loaded: loaded (/etc/init.d/mosquitto; bad; vendor preset: enabled)
   **Active: active (exited)** since Mon 2017-09-25 11:58:40 UTC; 13s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1805 ExecStop=/etc/init.d/mosquitto stop (code=exited, status=0/SUCCE
  Process: 1814 ExecStart=/etc/init.d/mosquitto start (code=exited, status=0/SUC

Sep 25 11:58:40 DemoServer systemd[1]: Stopped LSB: mosquitto MQTT v3.1 message
Sep 25 11:58:40 DemoServer systemd[1]: Starting LSB: mosquitto MQTT v3.1 message
Sep 25 11:58:40 DemoServer mosquitto[1814]:  * Starting network daemon: mosquitt
Sep 25 11:58:40 DemoServer mosquitto[1814]:    ...done.
Sep 25 11:58:40 DemoServer systemd[1]: Started LSB: mosquitto MQTT v3.1 message
lines 1-12/12 (END)

Thanks!!!!....

**Comment by toast-uz** [comment]
You may get useful comments quickly by posting at mosquitto-dev ML (https://dev.eclipse.org/mailman/listinfo/mosquitto-dev) for such "How to" questions.
This place is basically for bugs.

**Comment by toast-uz** [comment]
Could you report current situation, and more information about your environment and the reproducing procedure?

**Comment by vishuPPatel** [comment]
Same as this above write problem (Current phase the problem).

Current configuration about the my system (testing on Ubuntu server ON mosquitto setup but after the few hours goes in to "Active: active (exited)" ) .

**Comment by toast-uz** [comment]
Your report is too simple to be solved.
How did you install mosquitto? What is your mosquitto.conf? How long did mosquitto run?
What is your operation around mosquitto stopped? What is your mosquitto.log?
Show the whole information  for the 3rd party to reproduce the issue.

I installed mosquitto by using only "sudo apt-get install mosquitto" on clean Ubuntu 16.04.3 LTS, and did not reproduce your issue.

```
● mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
   Loaded: loaded (/etc/init.d/mosquitto; bad; vendor preset: enabled)
   Active: active (running) since Wed 2018-03-07 12:22:01 UTC; 17min ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 1
   Memory: 596.0K
      CPU: 381ms
   CGroup: /system.slice/mosquitto.service
           └─2997 /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf

Mar 07 12:22:01 ip-172-31-18-250 systemd[1]: Starting LSB: mosquitto MQTT v3.1 m
Mar 07 12:22:01 ip-172-31-18-250 mosquitto[2988]:  * Starting network daemon: mo
Mar 07 12:22:01 ip-172-31-18-250 mosquitto[2988]:    ...done.
Mar 07 12:22:01 ip-172-31-18-250 systemd[1]: Started LSB: mosquitto MQTT v3.1 me
```

**Comment by vishuPPatel** [comment]
hello.... Mosquitto Team 

why my mosquitto server is automaically stop??????

sudo systemctl status mosquitto.service

● mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
   Loaded: loaded (/etc/init.d/mosquitto; bad; vendor preset: enabled)
   **Active: active (exited) since Tue 2018-04-03 04:59:29 UTC; 7h ago**
     Docs: man:systemd-sysv-generator(8)
  Process: 119320 ExecStop=/etc/init.d/mosquitto stop (code=exited, status=0/SUCCESS)
  Process: 119330 ExecStart=/etc/init.d/mosquitto start (code=exited, status=0/SUCCESS)

Apr 03 04:59:29 DemoServer systemd[1]: Starting LSB: mosquitto MQTT v3.1 message
Apr 03 04:59:29 DemoServer mosquitto[119330]: * Starting network daemon: mosquitt
Apr 03 04:59:29 DemoServer mosquitto[119330]: ...done.
Apr 03 04:59:29 DemoServer systemd[1]: Started LSB: mosquitto MQTT v3.1 message
lines 1-12/12 (END)

**Comment by toast-uz** [comment]
Closing as duplicated with #509 .
@vishuPPatel please post on one thread for one issue, and do not post this issue on the other irrelative threads.
