### ISSUE TITLE
Windows broker does not start when include_dir is configured

### ISSUE THREAD

**Issue by marleau** [eclipse/mosquitto#564]
When I configure the include_dir option, the Windows broker exits with the following error:

```
Error: Unable to open include_dir 'C:\path\to\conf\dir'.
Error found at mosquitto.conf:9.
Error: Unable to open configuration file.
```

I have tried the following paths:

* `C:\path\to\conf\dir`
* `C:\\path\\to\\conf\\dir`
* `C:/path/to/conf/dir`

Has anyone successfully started the service with this option configured?

**Comment by toast-uz** [comment]
I tried and I could by C:\path\to\conf\dir on Windwos10 (32bit), although my Windows indicated \ as Yen mark due to localized as Japanese version. Also I could by relative path specification.

Could you check your permission with the dir?
To clarify the problem, could you make the confdir under your home directory and use relative path specification?

**Comment by marleau** [comment]
I checked the permissons for all the folders in the path. There are read permissions for all users.

After testing the home directory and relative paths, I still got the same error.
I opened cmd as Administrator and ran mosquitto from its Program Files (x86) folder.

For relative path, I made a `testing` folder in `C:\Program Files (x86)\mosquitto` and have tried the following:
- `.\testing`
- `testing`

In my home directory, I made a `testing` folder and have tried the following:

- `%USERPROFILE%\testing`
- `%HOMEDRIVE%%HOEMPATH%\testing`

**Comment by toast-uz** [comment]
I had no problem on a testing folder in C:\Program Files\mosquitto as both of Administrator and general user. Could you tell me your Windows version and bit?

**Comment by marleau** [comment]
I'm on Windows 7 64-bit.

I found the problem: the Windows filesystem is _not_ case-sensitive, but mosquitto is.

**Comment by marleau** [comment]
Thought I resolved the issue, but ran into the same problem on Windows 10 64-bit.

Eventually I was able to get mosquitto working.
Turns out that there _must_ be a .conf file in the include_dir for mosquitto to start.
