### ISSUE TITLE
Modifying files in client/lib folder doesn't seem to work

### ISSUE THREAD

**Issue by annedroiid** [eclipse/mosquitto#569]
I'm writing an extension to mosquitto, however I'm having the issue that only changes that I make in the src folder are actually reflected in the final mosquitto server and mosquitto_pub/mosquitto_sub clients. I originally set it up with CMake and compiled all of that, and now to rebuild the clients/server I run `make clean` and then `make` in the src and client folders. They compile fine and new clients are built, however no changes I made in the c files in the client/lib folders are actually in the compiled programs. Anyone know what is going on? Am I misunderstanding something about how to compile it or how it runs?

eg. I modified _mosquitto_handle_connack() in lib/read_handle_client.c to print a different message at line 32 (`_mosquitto_log_printf(mosq, MOSQ_LOG_DEBUG, "Client %s received CONNACK", mosq->id);`) however no matter what I change the text to it still displays the original text. I even modified _mosquitto_packet_handle() in lib/read_handle.c so that when it receives a CONNACK it doesn't do anything, but when I compile and re-run it still handles the CONNACK like in the standard mosquitto.

**Comment by toast-uz** [comment]
The cause seems to belong with your environment or operation, because many PR succeeded to revise lib folder.
Try to make without Cmake in order to clarify the issue.

```
$ pwd
/your-mosuqitto-folder
$ make clean
$ make binary
$ sudo make install WITH_DOCS=no
```
