### ISSUE TITLE
build issue in v1.4.14 - also what version of openssl to use ?

### ISSUE THREAD

**Issue by kdp-dev** [eclipse/mosquitto#570]
I'm seeing the following issue when trying to build v1.4.14 from source using the following command. Also what version of openssl to use
~/oss/mosquitto$ make WITH_SRV=no WITH_UUID=no WITH_WEBSOCKETS=yes WITH_TLS=yes binary
--
--
--
make -C cpp
make[2]: Entering directory '/home/ubuntu/oss/mosquitto/lib/cpp'
g++ -Wall -ggdb -O2  -I. -I.. -I../lib  -fPIC -c mosquittopp.cpp -o mosquittopp.o
g++ -shared  -Wl,-soname,libmosquittopp.so.1 mosquittopp.o -o libmosquittopp.so.1 ../libmosquitto.so.1
make[2]: Leaving directory '/home/ubuntu/oss/mosquitto/lib/cpp'
make[1]: Leaving directory '/home/ubuntu/oss/mosquitto/lib'
make[1]: Entering directory '/home/ubuntu/oss/mosquitto/client'
cc -c pub_client.c -o pub_client.o -Wall -ggdb -O2  -I../lib -DVERSION="\"1.4.14\"" -DWITH_TLS -DWITH_TLS_PSK -DWITH_SOCKS
cc -c client_shared.c -o client_shared.o -Wall -ggdb -O2  -I../lib -DVERSION="\"1.4.14\"" -DWITH_TLS -DWITH_TLS_PSK -DWITH_SOCKS
cc pub_client.o client_shared.o -o mosquitto_pub  -L../lib ../lib/libmosquitto.so.1
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_num'
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_init_ssl'
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_pop_free'
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_value'
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_init_crypto'
../lib/libmosquitto.so.1: undefined reference to `SSL_CTX_set_options'
collect2: error: ld returned 1 exit status
Makefile:8: recipe for target 'mosquitto_pub' failed
make[1]: *** [mosquitto_pub] Error 1
make[1]: Leaving directory '/home/ubuntu/oss/mosquitto/client'
Makefile:21: recipe for target 'mosquitto' failed
make: *** [mosquitto] Error 2

**Comment by kunaldp-dev** [comment]
ignore the above command used. 
the one i used is 
$ make WITH_SRV=yes WITH_UUID=yes WITH_WEBSOCKETS=yes WITH_TLS=yes binary

**Comment by toast-uz** [comment]
Could you run only 'make binary' in order to clarify the issue?
Especially, compiling with WEBSOCKETS makes the matter complicated.

Did you operate as follows to enable libraries?

```
$ sudo cat /etc/ld.so.conf.d/liblocal.conf
/usr/local/lib64
/usr/local/lib
$ sudo ldconfig
```

**Comment by kunaldp-dev** [comment]
@toast-uz 
I tried to build again with 'make binary' and saw the same results as shown in my first comment. 

$ make binary
set -e; for d in lib client src; do make -C ${d}; done
make[1]: Entering directory '/tmp/mosquitto/lib'
make -C cpp
make[2]: Entering directory '/tmp/mosquitto/lib/cpp'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/tmp/mosquitto/lib/cpp'
make[1]: Leaving directory '/tmp/mosquitto/lib'
make[1]: Entering directory '/tmp/mosquitto/client'
cc pub_client.o client_shared.o -o mosquitto_pub  -L../lib ../lib/libmosquitto.so.1
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_num'
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_init_ssl'
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_pop_free'
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_sk_value'
../lib/libmosquitto.so.1: undefined reference to `OPENSSL_init_crypto'
../lib/libmosquitto.so.1: undefined reference to `SSL_CTX_set_options'
collect2: error: ld returned 1 exit status
Makefile:8: recipe for target 'mosquitto_pub' failed
make[1]: *** [mosquitto_pub] Error 1
make[1]: Leaving directory '/tmp/mosquitto/client'
Makefile:21: recipe for target 'mosquitto' failed
make: *** [mosquitto] Error 2


However, I got the build working by running cmake and then running the command
'$ make WITH_SRV=no WITH_UUID=no WITH_WEBSOCKETS=yes WITH_TLS=yes binary'
And this is on a Ubuntu-16.04.3 LTS . As mentioned in the readme.md file, cmake need not be run on platforms except Windows/Mac OSX.

Also the issue may have been because of two different versions of OpenSSL installed on my machine. The makefile may have been generated using version 1.0.0 and using cmake updates that, I guess. And yes. I did use ldconfig to load libraries.

**Comment by toast-uz** [comment]
By your error messages, the compiler seemed to fail to find proper libssl.so. Maybe, your libssl.so was installed at a non standard directory, or there are duplicate libssl.so.

Check your openssl libraries as follows:
```
$ sudo find / -name libssl.so
$ sudo find / -name libcrypto.so
```
FYI, my openssl version is 1.0,1e and the libraries at /usr/lib64 on CentOS:
```
$ openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
$ rpm -q openssl
openssl-1.0.1e-60.el7_3.1.x86_64
$ ls -l /usr/lib64/libssl*
-rwxr-xr-x. 1 root root 315072 May 30 15:31 /usr/lib64/libssl3.so
lrwxrwxrwx. 1 root root     16 Aug  1 11:06 /usr/lib64/libssl.so -> libssl.so.1.0.1e
lrwxrwxrwx. 1 root root     16 Jul 31 11:38 /usr/lib64/libssl.so.10 -> libssl.so.1.0.1e
-rwxr-xr-x. 1 root root 454008 Feb 20  2017 /usr/lib64/libssl.so.1.0.1e
$ ls -l /usr/lib64/libcrypto*
lrwxrwxrwx. 1 root root      19 Aug  1 11:06 /usr/lib64/libcrypto.so -> libcrypto.so.1.0.1e
lrwxrwxrwx. 1 root root      19 Jul 31 11:38 /usr/lib64/libcrypto.so.10 -> libcrypto.so.1.0.1e
-rwxr-xr-x. 1 root root 2025760 Feb 20  2017 /usr/lib64/libcrypto.so.1.0.1e
```

**Comment by toast-uz** [comment]
@kunaldp-dev have you solved your issue?

**Comment by yunju123** [comment]
I got same issue.
I am using same opeessl version as @toast-uz  and I have libssl and libsrypto files under /usr/lib64/. 

I am not sure mosquitto v1.4.14 support openssl < 1.1.0.
Because "OPENSSL_sk_pop_free" seems like new from openssl > 1.1.0.

**Comment by toast-uz** [comment]
@yunju123 check the library path recognized properly as followings:

```
$ ldconfig -p | grep libssl
	libssl3.so (libc6,x86-64) => /lib64/libssl3.so
	libssl.so.10 (libc6,x86-64) => /lib64/libssl.so.10
	libssl.so (libc6,x86-64) => /lib64/libssl.so
$ ldconfig -p | grep libcrypto
	libcrypto.so.10 (libc6,x86-64) => /lib64/libcrypto.so.10
	libcrypto.so (libc6,x86-64) => /lib64/libcrypto.so
```

**Comment by yunju123** [comment]
Here are my results.

$ ldconfig -p | grep libssl
	libssl3.so (libc6,x86-64) => /lib64/libssl3.so
	libssl.so.10 (libc6,x86-64) => /lib64/libssl.so.10
	libssl.so.6 (libc6,x86-64) => /lib64/libssl.so.6
	libssl.so.1.1 (libc6,x86-64) => /lib64/libssl.so.1.1
	libssl.so (libc6,x86-64) => /lib64/libssl.so

$ ldconfig -p | grep libcrypto
        libcrypto.so.10 (libc6,x86-64) => /lib64/libcrypto.so.10
 	libcrypto.so.6 (libc6,x86-64) => /lib64/libcrypto.so.6
        libcrypto.so.1.1 (libc6,x86-64) => /lib64/libcrypto.so.1.1
        libcrypto.so (libc6,x86-64) => /lib64/libcrypto.so

After I removed *so.6 and *so.1.1 and execute "ldconfig" so I got same library path as you
But I got same error during build Mosquitto 1.4.5

**Comment by yunju123** [comment]
I installed mosquitto 1.4.5 about 2 years ago.
I got some issue report (memory leak) so I need to build again to look into it. 

And I 'm sorry I wrote wrong result on my previous comment.
Here are my system. 

$ ldconfig -p | grep libssl
        libssl3.so (libc6,x86-64) => /usr/lib64/libssl3.so
        libssl.so.10 (libc6,x86-64) => /usr/lib64/libssl.so.10
        libssl.so (libc6,x86-64) => /usr/lib64/libssl.so

$ ldconfig -p | grep libcrypto
        libcrypto.so.10 (libc6,x86-64) => /usr/lib64/libcrypto.so.10
        libcrypto.so (libc6,x86-64) => /usr/lib64/libcrypto.so


$ ls -l /usr/lib64 | grep libssl
lrwxrwxrwx   1 root root        16 2017-12-11 17:07 libssl.so -> libssl.so.1.0.1e
-rwxr-xr-x   1 root root    444184 2016-05-02 19:18 libssl.so.1.0.1e
lrwxrwxrwx   1 root root        16 2017-12-11 17:07 libssl.so.10 -> libssl.so.1.0.1e
-rwxr-xr-x   1 root root    257120 2014-11-26 13:18 libssl3.so

$ ls -l /usr/lib64 | grep libcrypto
lrwxrwxrwx   1 root root        19 2017-12-11 17:07 libcrypto.so -> libcrypto.so.1.0.1e
-rwxr-xr-x   1 root root   1969952 2016-05-02 19:18 libcrypto.so.1.0.1e
lrwxrwxrwx   1 root root        19 2017-12-11 17:07 libcrypto.so.10 -> libcrypto.so.1.0.1e


So my /lib64 is not symbolic link. and all libssl* and libcrypto* files are placed on right path.

**Comment by yunju123** [comment]
I solved my issue. 

After I removed /usr/local/include/openssl folder, I can build Mosquitto. 

I think that folder was created when I tried to install openssl 1.1.0 but I don't why that folder makes fail to build mosquitto. 

Have any idea?

**Comment by toast-uz** [comment]
Maybe the compiler looked up /usr/local/include/openssl and used incompatible header files. After you deleted them, it looked up /usr/include/openssl and used proper files.

**Comment by toast-uz** [comment]
I ask again @kunaldp-dev have you solved your issue?

**Comment by kdp-dev** [comment]
@toast-uz apologies for not noticing this. I didn't quite resolve this issue. instead the following command works for me currently (removed the 'binary')
make WITH_SRV=yes WITH_UUID=yes WITH_WEBSOCKETS=yes WITH_TLS=yes

**Comment by toast-uz** [comment]
Inform me the information I asked you on 4 Oct 2017.
If you don't want to solve the beginning  issue now, you can close this.

**Comment by toast-uz** [comment]
Closing because no information for a long time. Re-open a new issue if you've had yet.

**Comment by ranchochen** [comment]
> I solved my issue.
> 
> After I removed /usr/local/include/openssl folder, I can build Mosquitto.
> 
> I think that folder was created when I tried to install openssl 1.1.0 but I don't why that folder makes fail to build mosquitto.
> 
> Have any idea?

it works for me. THKS.
