### ISSUE TITLE
Brokers Dies on Windows (512 connections)

### ISSUE THREAD

**Issue by ericGTT** [eclipse/mosquitto#573]
When I have 510-512 connections the broker dies. 
Running on Windows (The documentation I read said 1024 unless running on Windows Server.)
I tried both Windows Server and Windows 7.
And using TLS.
Mosquitto Version 1.4.14
Running as a service

-- Update --
I found out if I set " _setmaxstdio(2048);" and compile code I can get more connections. Most I've had was about 2200+ connections. (I'm still testing it.)

**Comment by ralight** [comment]
Closing as per merged PR.
