### ISSUE TITLE
callback for delivery complete?

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/mosquitto#577]
This library gives callbacks for a successful connection, disconnection, publish([1](https://mosquitto.org/api/files/mosquitto-h.html#mosquitto_publish_callback_set)) etc. But there is no callback for successful delivery( as in Paho client[[delivery_complete](http://www.eclipse.org/paho/files/cppdoc/classmqtt_1_1callback.html#a7165d51b17104475f679254d25b4ba97)] ). Is it possible to provide a similar callback in Mosquitto?

Use case: That kind of a callback is useful for app developers who do offline persistence. My application could take messages one after another from SQLite DB and publish. On successful delivery, I could delete published message from SQLite. Currently, to cover the case of an application crash, I will need to use file persistence which could be avoided if a callback on delivery is provided.

**Comment by karlp** [comment]
delivery_complete == on publish. 

when you call mosquitto_publish, you can provide a pointer to get a MID for tracking, and the on_publish callback fires with the MID that has completed. From the documentation you linked to
```
Set the publish callback.  This is called when a message initiated with mosquitto_publish has been sent to the broker successfully.
```
