### ISSUE TITLE
Bridge Connection Fails on v 1.4.14

### ISSUE THREAD

**Issue by timpur** [eclipse/mosquitto#580]
On version 1.4.14 bridge connections fain on windows 10 (server 2016). This issue seems to be low level where the broker wont respond to the tcp sync packet from the remote (from wireshark).

Same computer v1.4.10 works perfectly.

Apart from this i dont know how else to help. The logs just say unknown error while connecting.

**Comment by marleau** [comment]
I'm also having this issue with version 1.4.14 on Windows 10.
I don't have any issues bridging with version 1.4.9.

Here is an excerpt of my logs.

```
1510095695: mosquitto version 1.4.14 (build date Tue 11/07/2017 14:42:35.84) starting
1510095695: Config loaded from mosquitto.conf.
1510095695: Opening websockets listen socket on port 9001.
1510095695: Opening ipv6 listen socket on port 1883.
1510095695: Opening ipv4 listen socket on port 1883.
1510095695: Bridge local.computer.factory-bridge doing local SUBSCRIBE on topic #
1510095695: Connecting bridge factory-bridge (x.x.x.x:1883)
1510095695: Bridge computer.factory-bridge sending CONNECT
1510095695: Error creating bridge: Unknown error.
1510095695: Warning: Unable to connect to bridge factory-bridge.
```

Here is the bridge configuration.

```
connection factory-bridge
address x.x.x.x
topic # out "" ""
notifications false
cleansession true
bridge_protocol_version mqttv311
```

**Comment by timpur** [comment]
sorry should of posted my log also. I get the same error ` Error creating bridge: Unknown error.`
Did looking into the issue using wireshark and i saw that mosquitto wouldn't respond to the tcp packets of the handshake from the remote mqtt broker. It was weird.

**Comment by PierreF** [comment]
Just to be sure:
* There is two broker: Broker A and Broker B
* Logs and configuration comes from Broker A. Therefor bridge is configured for Broker A to connect to Broker B
* Broker A don't response to Syn packet from Broker B ? Since broker B should not open a connection, I assume it's a syn+ack packet.

The fact that error is "Unknown error" + no response to Syn packet makes me wonder if it's not a firewall/security policy issue ? Could you retry with more permissive firewall configuration ?

**Comment by timpur** [comment]
Your understanding is right, but with out changing anything, but the version of mosquitto things work.

**Comment by jsirpoma** [comment]
I think this is same as #478.

**Comment by ralight** [comment]
I agree, this is the same as #478 which is now fixed in the `fixes` branch.
