### ISSUE TITLE
Websocket-Headers are case-sensitive

### ISSUE THREAD

**Issue by dbaumgarten** [eclipse/mosquitto#585]
Hi,

I am trying to get mosquitto to run behind caddy as a reverse-proxy and encountered some problems.

Caddy changes the Header-Names "Sec-WebSocket-\*" to "Sec-Websocket-\*" (note the lowercase s) when proxying a websocket request to the mosquitto upstream-server.

Mosquitto does not seem to like this and just closes the connection.
It is annoying that caddy modifies the header-names, but the RFCs say that header-names should be case-insensitive, so Mosquitto should be able to handle this.

I am running mosquitto 1.4.1 on a raspberry pi (v1) with raspbian jessie and installed mosquitto using this tutorial: https://mosquitto.org/2013/01/mosquitto-debian-repository/ .

There is a closed issue for libwebsockets on this topic: https://github.com/warmcat/libwebsockets/issues/137 , so maybe mosquitto would only need to update ?

**Comment by toast-uz** [comment]
Seems the issue of libwebsockets. What do you require for mosquitto?

**Comment by dbaumgarten** [comment]
Libwebsockets already fixed this bug. Now I would really like mosquitto to use a new enuogh version of libwebsockets and (most importantly) update the package-manager packages accordingly.

I am especially interested in the http://repo.mosquitto.org/debian/dists/jessie/ repo. (the arm version)

**Comment by toast-uz** [comment]
This is an issue of packaging for Debian, right?
For general Linux,  there is no packaging of mosquitto with libwebsockets. It must be made from the source files. Therefore, this issue cannot appear.

**Comment by dbaumgarten** [comment]
Yes it is.
I just updated from debian jessie to stretch and now everything is working as expected. (The deb-package in the stretch repo depends on a new enough version of libwebsockets)

This solution works for me, so I will close the Issue.
