### ISSUE TITLE
mosquitto_sub --verbose => impossible to distinguish btw topic and payload

### ISSUE THREAD

**Issue by the0ne** [eclipse/mosquitto#587]
using mosquitto_sub with parameter --verbose will output: `topic payload` followed by a newline.
as the topic may contain spaces as well as tabs the output should be formatted as `"topic" payload` followed by a newline to be able to distinguish between topic and payload. please note that any double-quote in the topic needs to be escaped in the output as well.

**Comment by toast-uz** [comment]
I can understand what and why you wish, but cannot understand the necessity.
Generally, there are few topics contain spaces, your wish will be hard to use for many other topics.
If you want to handle something by logs such a detailed level, you should make custom client by using libmosquitto.

**Comment by karlp** [comment]
This is why you have client libraries to format and handle things anyway you wish.  Perhaps try -d and see if that's more suitable for your needs.  For very many people, the existing -v is ideal, as it _doesn't_ try and do any "helpful" escaping or reformatting.

**Comment by the0ne** [comment]
I can understand your doubts, but in what terms is it correct to output
`this is the topic name this is the payload`
with no delimiting at all?

**Comment by toast-uz** [comment]
@theOne try the new option -F of mosquitto_sub on develop branch.
Refer:
https://dev.eclipse.org/mhonarc/lists/mosquitto-dev/msg01683.html
https://github.com/eclipse/mosquitto/blob/develop/man/mosquitto_sub.1.xml

**Comment by the0ne** [comment]
@toast-uz thanks for pointing this out!

**Comment by toast-uz** [comment]
What's wrong with -F option and --verbose ?

```
$ mosquitto_sub -h test.mosquitto.org -t "/toast-uz/#" --verbose
/toast-uz/test Hello
^C
$ mosquitto_sub -h test.mosquitto.org -t "/toast-uz/#" -F "%t:%p" --verbose
/toast-uz/test:Hello
^C
```

**Comment by the0ne** [comment]
Didn't realize from the comment above that -F was meant as a flag in _combination_ with --verbose.
So that looks like a great solution. Thanks!

**Comment by toast-uz** [comment]
@theOne , I have an additional comment.
According to the source file, using -F option ignores --verbose option. -F behaves as an upward compatible of --verbose .
