### ISSUE TITLE
mosquitto_pub & mosquitto_sub do not display Russian letters

### ISSUE THREAD

**Issue by YuriyMan** [eclipse/mosquitto#593]
The latest version.
The mosquitto server works well with Russian letters.
But "mosquitto_pub" & "mosquitto_sub" do not display Russian letters.
How to fix the situation ?
Thanks in advance

**Comment by karlp** [comment]
MQTT only transports bytes in payloads.  There's no provision _anywhere_ in the protocol for attempting to convey string encoding in message payloads.  the _pub/_sub tools must make an assumption for attempting to print them out, but this cannot ever be correct in all situations.

**Comment by YuriyMan** [comment]
1. I do not consider this behavior to be normal. And in the confirmation of my opinion I ask the question: Then why mosquitto Winwos-server and other Android-applications transmit messages in Unicode (works correctly with Russian letters) ?

2. If you think that this behavior is normal, then what can I do to solve the problem ?

**Comment by karlp** [comment]
The _broker_ is only transferring bytes.  The mqtt _protocol_ only transfers bytes.  Whether those are raw jpeg frames, or encoded text is completely transparent to the broker.  Some applications will might automatically attempt to decode text in the local locale.  mosquitto_sub is simply directly writing the bytes from the payload back to stdout, and the pub_client is just fgets from the cli,

**Comment by karlp** [comment]
To follow up on this... as the clients are both just transmitting the bytes as received, if both sides are actually assuming the same encoding, this just works.  If each side are different, then this is just like mail or anything else....

A subscriber, receives two messages
```
$ mosquitto_sub -t "karl/test" -h test.mosquitto.org
basdf
джинсы
^C
```
A publisher, sends two messages.
```
$ mosquitto_pub -t "karl/test" -h test.mosquitto.org -m basdf
$ mosquitto_pub -t "karl/test" -h test.mosquitto.org -m "джинсы"
$
```

So mosquitto, and mosquitto_sub/pub are transparently passing what they receive.  If you need to _reencode_ you need to speak to your clients and implement that in a higher layer.

**Comment by YuriyMan** [comment]
**karlp**, Thanks a lot for your help !
1. Understood: the Russian letters were sent by MQTT-client "MQTT Spy" in Unicod encoding.
2. Now I can answer my question "What should I do ?": My script converts Russian letters into Unicod encoding and in this form passes them to mosquitto_pub.exe, which passes them to the mosquitto MQTT server. Android-client gets them in Unicod encoding and now correctly displays Russian letters !

**Comment by YuriyMan** [comment]
Unfortunately, just typed the page and saw your message, in which you described in detail, the same thing.
But there were questions:
A) Why at the beginning of the '$'?
B) Why is "karl / test" in quotes?
C) Why basdf without quotes?
Here in the examples in another way:
http://mosquitto.org/man/mosquitto_pub-1.html.

**Comment by YuriyMan** [comment]
I found out experimentally:
I. The topic can also be written in Russian letters
II. Quotations are necessary (in messages and topics), if the text has Russian letters AND spaces!

**Comment by karlp** [comment]
A) just indicating my shell prompt, that these were commands I executed.
B) habit
C) bad habit :)

I believe this issue can be closed now?

**Comment by YuriyMan** [comment]
Thank you again for your help.
The problem is solved!
