### ISSUE TITLE
why mqtt client receive the old subscribe message when connect to the mosquitto server?

### ISSUE THREAD

**Issue by zhuweijia** [eclipse/mosquitto#594]
hello, sorry，my english is poor. I have some problems：
I implemented a mqtt client myself and use mosquitto as my mqtt server，but，my mqtt client always receive the old subscribe message when client connect to server。（everytime，after the connection between the client and the server is established， i will subscribe some topic ）
i want to know how can i do ，the client do not receive the old subscribe message when connect to the server。
PS：i find close the mosquitto server then reopen the mosquitto server，at this time，my mqtt client do not receive the old subscribe message，but i can't often close and open mosquitto server。

this is chinese description：
我自己实现了一个mqtt客户端，使用mosquitto开源程序作为服务端，但是有一个问题，每一次我的客户端和服务端连接后，就会收到旧的以前订阅的消息（由于我是每次建立连接后，就向服务端段订阅一些主题）。我想知道是不是哪些设置的不对导致的，怎么才能做到每一次连接上服务端，保持着全新的状态，不要收到旧的消息。
有大佬懂的话，帮下忙啊，谢谢

**Comment by masterhou** [comment]
I use  mosquitto version 1.4.14, do not have this problem.
I think your mqtt sub client maybe have some bugs.

**Comment by karlp** [comment]
I would imagine you are getting some retained messages.  mosquitto_sub with the -d flag will show you the retain flag settings.  You can use mosquitto_pub to send null messages to clear retained messages.

**Comment by zhuweijia** [comment]
@masterhou  yes，i am agree with you，i want to know what problems my mqtt sub client might have，or  where might have problems？thank you

**Comment by zhuweijia** [comment]
@karlp  i don't know what you mean，i use mosquitto_sub with the -d flag，and here is content：
client mosqsub/169628-xxx sending CONNECT
client mosqsub/169628-xxx received CONNACK
client mosqsub/169628-xxx sending SUBSCRIBE (Mid :1 Topic: Testxxx , Qos:0)
client mosqsub/169628-xxx received SUBACK
Subscribed (mid :1):0
client mosqsub/169628-xxx received PUBLISH (d0, q0, r1, m0, 'Testxxx', ... (164 bytes) )
{......specific message.......}

PS:this time，i use the **mosquitto client** not my mqtt client to subscribe topic，and i use **my mqtt client to publish message**，the **mosquitto sub client** always receive the old subscribe message when connect to server.

**server：**mosquitto
**client sub ：**mosquitto_sub
**client pub：** my mqtt client
i know my client my have some bugs，but i don't know where might have bugs.
thank you.

**Comment by karlp** [comment]
Yes, exactly. see you have "r1" there?  That's a retained message.  Those are kept by the broker per topic, forever, and will always re-appear.  You can clear them by publishing a null with retain to that topic, and you can ignore them on your clients if you want to leave them there.  This is normal, expected behaviour.  Please close this ticket.

**Comment by zhuweijia** [comment]
ok，i know，but i find there is ”r0“ when the mosquitto client first time receive this publish message .then i exit the mosquitto client，and re execute the mosquitto client（here，i also close my publish client），this time there is turn to “r1”，after that ，repeat exit and re execute the mosquitto client，receive the publish message are all is “r1”.

**Comment by ralight** [comment]
The retained bit has different meanings. When a client sets it on a message being sent to the broker it tells the broker to retain the message. When the client receives a message from the broker, if the retain bit is not set it means that the client receiving the message was already subscribed to the topic when the publishing client sent the message, i.e. the message is "fresh". In the same case, if the retain bit is set then it means the message is a retained message that was sent before the receiving client subscribed to the topic, i.e. the message is "stale" and you don't know how long ago it was sent.

What you're seeing is completely normal.

**Comment by joaolucasd** [comment]
> ok，i know，but i find there is ”r0“ when the mosquitto client first time receive this publish message .then i exit the mosquitto client，and re execute the mosquitto client（here，i also close my publish client），this time there is turn to “r1”，after that ，repeat exit and re execute the mosquitto client，receive the publish message are all is “r1”.

Yes! I have the same problem. The thing is, this first and only r1 publish opens my shades all the time!
