### ISSUE TITLE
Feature request: Improve TLS error messages

### ISSUE THREAD

**Issue by oej** [eclipse/mosquitto#596]
When debugging issues, there's only one TLS error message for a large number of causes, which is quite irritating. 
I can look into improving this, but need some advice code-wise.

Today, there's one result code returned from the library to the client - like mosquitto_pub. We can either expand this and add a large number of TLS errors or add another global error code, like the "last known TLS error" that a client can get through a function if further details are wanted.

What would be a good way to handle this?

**Comment by dontsovcmc** [comment]
+1 it's  better

**Comment by codeadict** [comment]
👍

**Comment by toast-uz** [comment]
Your wish was already implemented on the latest develop branch, while not on master branch.

Sample on develop:
```
$ mosquitto_sub -d -t "#" -h localhost -p 8883 --cafile /home/centos/tls_test/test-bad-root-ca.crt --insecure --tls-version tlsv1
Client mosqsub|2475-ip-172-31- sending CONNECT
OpenSSL Error: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Error: A TLS error occurred.
```

Same on master:
```
$ mosquitto_sub -d -t "#" -h localhost -p 8883 --cafile /home/centos/tls_test/test-bad-root-ca.crt --insecure --tls-version tlsv1
Client mosqsub|2767-ip-172-31- sending CONNECT
Error: A TLS error occurred.
```

**Comment by toast-uz** [comment]
@oej, could you confirm that my comment satisfied your wish?

**Comment by ralight** [comment]
You could also use `ERR_get_error()` from OpenSSL to retrieve the error codes in a similar manner to what is done in the develop branch.

**Comment by toast-uz** [comment]
Closing this issue because solved on develop.
