### ISSUE TITLE
Not all time user subscribe to topic mosquitto_auth_acl_check called

### ISSUE THREAD

**Issue by fvezzoli** [eclipse/mosquitto#598]
When logged user subscribe to topic not all times the mosquitto_auth_acl_check function called.
In this manner the user is free to subscribe to all topic without control.

**Comment by toast-uz** [comment]
Could you show the version and a procedure of reproducing the issue?

**Comment by fvezzoli** [comment]
I use mosquitto 1.4.12 with auth plugin from https://github.com/jpmens/mosquitto-auth-plug.
But also with simple plugin with minimal log no all time the acl check functions is called.

The config for plugin is:
```
port 1883
protocol mqtt
allow_anonymous false
auth_plugin /etc/mosquitto/auth-plug.so
auth_opt_backends http
auth_opt_http_ip 192.168.177.250
auth_opt_http_port 5000
auth_opt_http_hostname antani.local
auth_opt_http_getuser_uri /auth
auth_opt_http_superuser_uri /superuser
auth_opt_http_aclcheck_uri /acl
auth_opt_auth_cacheseconds 5
auth_opt_acl_cacheseconds 5
```

**Comment by fvezzoli** [comment]
Here the simple log plugin

```
#include <string.h>
#include <string.h>
#include <mosquitto.h>
#include <mosquitto_plugin.h>

int mosquitto_auth_plugin_version(void)
{
	mosquitto_log_printf("@@ mosquitto_auth_plugin_version @@");
	return MOSQ_AUTH_PLUGIN_VERSION;
}

int mosquitto_auth_plugin_init(void **user_data, struct mosquitto_auth_opt *auth_opts, int auth_opt_count)
{
	mosquitto_log_printf("@@ mosquitto_auth_plugin_init @@");
	return MOSQ_ERR_SUCCESS;
}

int mosquitto_auth_plugin_cleanup(void *user_data, struct mosquitto_auth_opt *auth_opts, int auth_opt_count)
{
	mosquitto_log_printf("@@ mosquitto_auth_plugin_cleanup @@");
	return MOSQ_ERR_SUCCESS;
}

int mosquitto_auth_security_init(void *user_data, struct mosquitto_auth_opt *auth_opts, int auth_opt_count, bool reload)
{
	mosquitto_log_printf("@@ mosquitto_auth_security_init @@");
	return MOSQ_ERR_SUCCESS;
}

int mosquitto_auth_security_cleanup(void *user_data, struct mosquitto_auth_opt *auth_opts, int auth_opt_count, bool reload)
{
	mosquitto_log_printf("@@ mosquitto_auth_security_cleanup @@");
	return MOSQ_ERR_SUCCESS;
}

int mosquitto_auth_acl_check(void *user_data, const char *clientid, const char *username, const char *topic, int access)
{
	mosquitto_log_printf("@@ mosquitto_auth_acl_check @@");
	return MOSQ_ERR_SUCCESS;
}

int mosquitto_auth_unpwd_check(void *user_data, const char *username, const char *password)
{
	mosquitto_log_printf("@@ mosquitto_auth_unpwd_check @@");
	return MOSQ_ERR_SUCCESS;
}

int mosquitto_auth_psk_key_get(void *user_data, const char *hint, const char *identity, char *key, int max_key_len)
{
	mosquitto_log_printf("@@ mosquitto_auth_psk_key_get @@");
	return MOSQ_ERR_AUTH;
}
```

**Comment by toast-uz** [comment]
It seems that Mosquitto after v1.3.5 temporarily disabled ACL checks on subscriptions.

**Comment by fvezzoli** [comment]
I try to find piece of code limit function call in order to create pull request for restore the full functionality but i have some problem to understand the point where this limitation is present.

**Comment by toast-uz** [comment]
The place is from the line 696 in the function mqtt3_handle_subscribe in src/read_handle_server.c of the latest master branch.
Could you try the latest develop branch which re-enabled ACL checks on subscriptions.

**Comment by fvezzoli** [comment]
Yes, and running correctly.
but in develop branch the plugin function is different from released
version, is correct?

Il 29 ott 2017 11:48 PM, "toast-uz" <notifications@github.com> ha scritto:

**Comment by toast-uz** [comment]
You are right. The place was transferred to src/handle_subscribe.c on develop branch.

**Comment by toast-uz** [comment]
@fvezzoli, could you confirm that my comment met your wish?

**Comment by ralight** [comment]
There are two potential ways of checking subscription requests. The first is by explicit string, i.e. "disallow all subscription requests that match the text string '#'". The second is to do pattern based matching, i.e. "disallow any subscription topic that matches against the acl topic 'fvezzoli/+/+/temperature'". The second case is more complicated because potentially we have to compare two wildcard strings.

**Comment by fvezzoli** [comment]
Yes, the second test is more complicated, but on function call the test is make for allow subscription.
For all sub request the function is called and the test is demanded to function called.

**Comment by toast-uz** [comment]
@fvezzoli your original issue was solved on develop, right? Could you close this issue?

**Comment by fvezzoli** [comment]
Yes, I test the develop branch with testing plugin and all OK.
I close the issue.
