### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by esarearthur** [eclipse/mosquitto#599]
make[1]: Entering directory `/home/iotadmin/mosquitto/man'
xsltproc mosquitto.8.xml
warning: failed to load external entity "/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl"
compilation error: file manpage.xsl line 3 element import
xsl:import : unable to load /usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
compilation error: file mosquitto.8.xml line 4 element refentry
xsltParseStylesheetProcess : document is not a stylesheet
make[1]: *** [mosquitto.8] Error 5
make[1]: Leaving directory `/home/iotadmin/mosquitto/man'
make: *** [docs] Error 2

I keep getting this error when I am comling

**Comment by toast-uz** [comment]
Check "Building from source" in readme.md.

**Comment by toast-uz** [comment]
@esarearthur , did my comment make sense?

**Comment by Tifaifai** [comment]
On your linux system, have you ````/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl```
Have you installed the package ?
Closed topic ?

**Comment by mrizvic** [comment]
You have to install following packages: `xsltproc docbook-xsl`
Then it will work.

**Comment by karlp** [comment]
or, much simpler, just do ```make binary``` instead of ```make```

**Comment by ralight** [comment]
Or `make WITH_DOCS=no`

**Comment by ralight** [comment]
I'm closing this because it's not really a bug, if you disagree please reopen and say why.
