### ISSUE TITLE
Is allow_zero_length_clientid option documented somewhere?

### ISSUE THREAD

**Issue by gautaz** [eclipse/mosquitto#600]
Hello,

Since [version 1.3](https://mosquitto.org/2014/03/version-1-3-released/), the `allow_zero_length_clientid` option seems available in `mosquitto.conf`.
However I cannot find an explanation for this option in the [mosquitto.conf manual page](https://mosquitto.org/man/mosquitto-conf-5.html).

Is there a particular reason for this?

**Comment by toast-uz** [comment]
I guess it is just a simple mistake. There is the description of the allow_zero_length_clientid option in the default mosquitto.conf file.

**Comment by gautaz** [comment]
You're right, it's all available [here](https://github.com/eclipse/mosquitto/blob/master/mosquitto.conf), thank you.

I see that `auto_id_prefix` is also to be documented, do you want me to keep this issue opened until the man pages are up to date?

**Comment by toast-uz** [comment]
I do.
Could you make a pull request to fix the man pages?

**Comment by gautaz** [comment]
I'll look into it, the only modification needed is on the [XML file](https://github.com/eclipse/mosquitto/blob/master/man/mosquitto.conf.5.xml), right ?

**Comment by toast-uz** [comment]
You're right.

**Comment by ralight** [comment]
This is fixed and will be part of 1.5.3 shortly, thanks for reporting it!
