### ISSUE TITLE
TLS issues with mosquitto_pub and mosquitto_sub

### ISSUE THREAD

**Issue by codeadict** [eclipse/mosquitto#605]
**Version:** 1.4.14 running on libmosquitto 1.4.14.
**OpenSSL:** OpenSSL 1.0.2l  25 May 2017
**OS:** MacOS "Sierra", Gentoo Linux, Ubuntu Linux

**Description:**

I'm trying to connect to a server using `mosquitto_pub` and `mosquitto_sub` like:

```
 mosquitto_sub -h myserver.com -p 8883 -u authorization -P mypassword --insecure --cafile /Users/codeadict/Downloads/certificate.pem -t /things --tls-version tlsv1.2 -d
```

And always getting:

```
Client mosqsub|11754-andromeda sending CONNECT
Error: A TLS error occurred.
```

I have tried the same using  Python and Golang with paho and is working perfect. Same for MQTT.fx

**Comment by toast-uz** [comment]
If you use mosquitto_sub on the latest develop branch, you can get the detailed error messages.
See #596 .

**Comment by toast-uz** [comment]
@codeadict did my comment help you?

**Comment by codeadict** [comment]
Yes, this is solved. Can be closed now.
