### ISSUE TITLE
Docker image availability

### ISSUE THREAD

**Issue by ruimarinho** [eclipse/mosquitto#606]
Hi,

The latest official image available on [Docker Hub](https://hub.docker.com/_/eclipse-mosquitto/) contains a vulnerability fixed in mosquitto v1.4.12+.

I can see that the master branch [does not contain versions](https://github.com/eclipse/mosquitto/tree/master/docker) 1.4.10+, while the [developer branch does](https://github.com/eclipse/mosquitto/tree/develop/docker). Since v1.4.14 has been released, is there any reason for not having this merged into master?

cc @daudetCA

**Comment by lukecyca** [comment]
I am using 1.4.12 because that's the latest available as an official mosquitto image on Docker Hub.

It's disappointing that official docker image releases don't coincide with official mosquitto releases.I would expect that 1.4.14 be on Docker Hub.

**Comment by ruimarinho** [comment]
In the meantime I've created https://hub.docker.com/r/ruimarinho/mosquitto/.

**Comment by lukecyca** [comment]
Thanks. I'll use yours for now then.

**Comment by triplepoint** [comment]
I, too,  would appreciate keeping the Docker Hub mosquitto image up to date with project releases.

You can configure github to notify Docker Hub when new git tags are pushed; this would be the most reliable and hands-free way to do it.

https://docs.docker.com/docker-hub/builds/#link-to-a-hosted-repository-service

Please take the time to set this up.

**Comment by triplepoint** [comment]
Any news on this?  The current published docker container is still standing at 1.4.12, and I see 1.5.1 was released a week or so ago.  

Bugfixes aren't effective if they're not deployed.

**Comment by efrecon** [comment]
Not that I know, I am also waiting for the maintainers to merge this and adapt the Docker image generation. I would be happy to help if necessary or if I've missed anything in the process.

**Comment by triplepoint** [comment]
Ok, here's a PR adding a dockerfile that pulls the tarball specified in the build-arg.
https://github.com/eclipse/mosquitto/pull/926

The idea is this:
```
cd docker/from_dist
docker build -t eclipse-mosquitto:1.5.1 --build-arg VERSION="1.5.1" .
docker run --rm -it eclipse-mosquitto:1.5.1
```

So it's on the user to keep the docker image label matching the build-arg that was used when it was built, but otherwise it's as clear as translation of the Alpine package build script as I could make:
https://github.com/alpinelinux/aports/blob/master/main/mosquitto/APKBUILD

I've never contributed to an Eclipse project before, and the administration looks pretty involved. 
 Comments or advice very welcome on the PR, or here.

**Comment by ruimarinho** [comment]
@ralight I think this can be closed now, right? Is the docker image being updated automatically on Docker Hub based on this repository's tags?

**Comment by ralight** [comment]
Indeed, I'm closing it now, the Docker image is being kept up to date.
