### ISSUE TITLE
what is the matter for  test.mosquitto.org?

### ISSUE THREAD

**Issue by saintthor** [eclipse/mosquitto#607]
the  Connected client count is down to 0.

**Comment by toast-uz** [comment]
Could you close this?

**Comment by saintthor** [comment]
why close without answer?
there was more than 8000 connections before i started this issues. and now less than 2000.
and i can not connect with mqtt.js this days. isn't there somthing wrong?

**Comment by toast-uz** [comment]
Sorry I'm not sure about that, because I'm a third party with test.mosquitto.org .
I tried just now and was able to connect. 

I'm afraid that I'm not sure you can get the convinced answer under no guaranteed condition of  test.mosquitto.org .
