### ISSUE TITLE
Topic match issue

### ISSUE THREAD

**Issue by shevast** [eclipse/mosquitto#618]
According to non-formative comment in mqtt v3.1.1 documentation
`“sport/#” also matches the singular “sport”, since # includes the parent level.`

I run **mosquitto** broker, subscribe on _sport/#_ using **mosquitto_sub**, publish message with topic _sport_, and subscriber successfully received this message. It's ok.

But also I expected that _+/#_ will also match singular _sport_, but this is not true.
Is my expectation wrong, or mosquitto doesn't handle matching properly this case?

Thank you

**Comment by szarta** [comment]
What version of mosquitto are you testing with?  I tested each release version 1.4  up to latest (1.4.14) and they all work with the behavior you describe in the second case:

mosquitto_sub -v -t "+/#"
mosquitto_pub -t "sport" -m "something"

My subscriber correctly receives the publish.

**Comment by shevast** [comment]
I use version 1.4.14, and I don't know why, but now I can't reproduce this, everything works fine.
However, I still think that it can be some kind of unstable, because if I add following line:
`do_check("+/#", "sport", false);`
to `mosquitto-1.4.14/test/lib/cpp/09-util-topic-matching.cpp`, test failed on this line.

./09-util-topic-matching.test
s: +/# t: sport
