### ISSUE TITLE
Mosquitto wont start on boot

### ISSUE THREAD

**Issue by Gabefire** [eclipse/mosquitto#627]
Ive tried multiple service files to try to get this working but it keeps giving me the same error. I'm using Linux Mint. Any suggestions? 

● mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
   Loaded: error (Reason: Invalid argument)
  Drop-In: /etc/systemd/system/mosquitto.service.d
           └─override.conf
   Active: inactive (dead)
     Docs: man:mosquitto(8)
           man:mosquitto.conf(5)
           man:systemd-sysv-generator(8)

Nov 22 02:51:02 hqtt-Latitude-E6510 systemd[1]: mosquitto.service: Service has more than one ExecStart= setting, which is only all
Nov 22 02:54:25 hqtt-Latitude-E6510 systemd[1]: mosquitto.service: Service has more than one ExecStart= setting, which is only all
Nov 22 02:57:37 hqtt-Latitude-E6510 systemd[1]: mosquitto.service: Service has more than one ExecStart= setting, which is only all
Nov 22 03:00:12 hqtt-Latitude-E6510 systemd[1]: mosquitto.service: Service has more than one ExecStart= setting, which is only all
Nov 22 03:01:35 hqtt-Latitude-E6510 systemd[1]: mosquitto.service: Service has more than one ExecStart= setting, which is only all
Nov 22 03:03:20 hqtt-Latitude-E6510 systemd[1]: mosquitto.service: Service has more than one ExecStart= setting, which is only all
Nov 22 03:04:36 hqtt-Latitude-E6510 systemd[1]: mosquitto.service: Service has more than one ExecStart= setting, which is only all
Nov 22 03:04:50 hqtt-Latitude-E6510 systemd[1]: mosquitto.service: Service has more than one ExecStart= setting, which is only all
Nov 22 03:04:51 hqtt-Latitude-E6510 systemd[1]: mosquitto.service: Service has more than one ExecStart= setting, which is only all
Nov 22 03:04:51 hqtt-Latitude-E6510 systemd[1]: mosquitto.service: Service has more than one ExecStart= setting, which is only all

[Unit]
Description=Mosquitto MQTT Broker
Documentation=man:mosquitto(8)
Documentation=man:mosquitto.conf(5)
ConditionPathExists=/etc/mosquitto/mosquitto.conf
After=xdk-daemon.service

[Service]
ExecStart=/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
ExecReload=/bin/kill -HUP $MAINPID
User=mosquitto
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target

**Comment by karlp** [comment]
That systemd unit file appears to be from mint itself.
mosquitto mainline doesn't provide a system unit file, and the devel branch has this file: https://github.com/eclipse/mosquitto/blob/develop/service/systemd/mosquitto.service.simple

I suggest you take this up with mint to fix their unit file they're shipping.

**Comment by Gabefire** [comment]
I changed the mosquitto.service file to the devel branch file and got this error


● mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
   Loaded: error (Reason: Invalid argument)
  Drop-In: /etc/systemd/system/mosquitto.service.d
           └─override.conf
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)

Nov 22r 10:40:21 hqtt-Latitude-E6510 systemd[1]: mosquitto.service: Service has m
Nov 22 10:40:21 hqtt-Latitude-E6510 systemd[1]: mosquitto.service: Service has m
Nov 22 10:40:21 hqtt-Latitude-E6510 systemd[1]: mosquitto.service: Service has m


[Unit]
Description=Mosquitto MQTT v3.1/v3.1.1 Broker

[Service]
ExecStart=/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
Restart=on-failure

[Install]
WantedBy=multi-user.target
