### ISSUE TITLE
duplicate clientId not disconnected

### ISSUE THREAD

**Issue by dave-co** [eclipse/mosquitto#631]
When I use multiple mosquitto_sub instances with identical clientId values to connect to the same broker & topic, they all remain connected and receive messages.  According to my reading of the MQTT spec, when a subscriber connects with a clientId that is already connected to the server, then the server should disconnect the earlier client:

> If the ClientId represents a Client already connected to the Server then the Server MUST disconnect the existing Client [MQTT-3.1.4-2]

To test this I'm running 1.4.8 on Ubuntu 16.04.3 LTS and I've set up mosquitto to require a username and password to connect.  I then open four console windows, three subscribers:

`mosquitto_sub -h localhost -t test -u <username> -P <password> -i user01 -q 2 -V mqttv311`

and one for the publish:
`mosquitto_pub -h localhost -t test -m "hello world" -u <username> -P <password> -q 2`

It seems random which subscriber receives the message, when I think only one should receive the message: the last one to connect.  I've tried it with both mqttv311 and the default mqttv31, as well as with qos 0, I get the same behaviour.

**Comment by karlp** [comment]
what's actually happening is that the mosquitto_sub's are being continually disconnected (old is disconnected when new one connects) and reconnecting, as mosquitto_sub automatically attempts a reconnection when it's lost.

you can add the -d flag and see this happening on each of them.  I don't think you can turn this off, and it's generally considered useful for most use cases of mosquitto_sub, but if you had your own client code that didn't reconnect, you'd see the behaviour you expect.

**Comment by dave-co** [comment]
@karlp  Ah, ok, I'll try that this evening.  Thanks for the explanation.

**Comment by toast-uz** [comment]
@karlp seems right. @dave-co you can watch easily by enabling debug log of Mosquitto broker.

mosquitto.conf:
```
log_type all
```

**Comment by PierreF** [comment]
This issue seems resolved. If not, feel free to reopen.
