### ISSUE TITLE
Where's Roger Light?

### ISSUE THREAD

**Issue by Tifaifai** [eclipse/mosquitto#634]
Hello,

Où est Charlie ? Where's Wally? Where's Waldo? Where is our friend roger light ?

Roger, is everything okay with you and your baby?

I think some PRs need your validation. 

See You Later

**Comment by hui6075** [comment]
guy, I have sent a mail(roger@atchoo.org) to him some hours ago, include a Mosquitto cluster design and actual implementation code, but I don’t know whether he would give me a advice reply. Could you give me some other guys mail? I would like to forward the mail to anyone who would give me some advise and code review.

**Comment by PierreF** [comment]
@hui6075 the best way to get advise is a message to Mosquitto devel mailing list. If related to code or for a code review, submit a PR.

**Comment by hui6075** [comment]
@PierreF ,thank you, I have subscribed mosquitto-dev@eclipse.org, and posted a mail to this list. could you see the mail? I saw the mail server have no response and the mail resend always..

**Comment by kartben** [comment]
yes, your email made it :)

**Comment by hui6075** [comment]
@kartben cool, thanks!

**Comment by karlp** [comment]
@Tifaifai There's responses on the mailing list for this exact item, can we please close this ticket now?
