### ISSUE TITLE
Installation on windows of 1.4.14 does not work ! Even after supplying missing DLL's it fails to start.

### ISSUE THREAD

**Issue by nurquhar** [eclipse/mosquitto#637]
I have downloaded the windows installer for 1.4.14 and followed the instructions to source the 'missing' DLL's. 

After installing on Win7 when I run mosquitto.exe I get the error that application will not start 0xC000007b

Issue 1 - The latest OpenSSL Light 1.1.0g after installation does not provide the required DLL's libeay32.dll ssleay32.dll.  To get these I had install OpenSSL Light 1.0.2m instead.

Issue 2 - I also had to find VCRUNTIME140.dll because this was missing, no instruction are given that this is required or where to get it.

Issue 3 - After following all this it does not run !!!

Can someone please do a clean install with the latest available OpenSSL and pthreads and explain how to make it install and run.  The current instructions do not work !

**Comment by archerian** [comment]
The 3rd party DLLs I use to run mosquitto on Windows 2008 are libeay32dll, ssleay32.dll, pthreadVC2.dll and the VC runtime. The pthreads dll is available from its sourceforge website, you seem to have got the other two.  Dependency screenshot below.

![image](https://user-images.githubusercontent.com/10156612/33526205-aa9a2d70-d80b-11e7-83d4-2445829c4d30.png)

**Comment by archerian** [comment]
I noticed the 32 bit installer fails to install properly first time. What I do is run it once, then go to the mosquitto directory in Program Files and add the three 3rd party dlls to the folder and re-run the installer. Second time around it works fine, the service is added to Services and can be started. The initial failed install attempt creates the directory for mosquitto but doesnt have the 3rd party libs. I do all of this only after installing the VC runtime.

**Comment by nurquhar** [comment]
Problem is even after you solve the missing DLL's and re-run the installer it the exe's will not work, see my install and run below.  You get the same error after running the installer also. 👍 
![image](https://user-images.githubusercontent.com/34193510/33527290-0887908c-d846-11e7-83b4-b93b35678983.png)

**Comment by nurquhar** [comment]
You get the same error running the installer 👍 
![image](https://user-images.githubusercontent.com/34193510/33527501-f019b4fe-d849-11e7-8310-258458e65029.png)

**Comment by archerian** [comment]
Can you try installing the VC runtime via the installer? Try the 32 bit version, I'm using that one.

**Comment by nurquhar** [comment]
Would it not be normal practice to include such a dependencys in the installer, MS say you can do this.
[Determining Which DLLs to Redistribute](https://msdn.microsoft.com/en-us/library/8kche8ah.aspxl)
I am downloading the x86 VC2015 redist, I will let you know when its done if it works.

**Comment by nurquhar** [comment]
I have sourced VCRUNTIME140.dll from the SysWOW64 directory on another the Win7 m/c. This should be the 32bit version of the DLL.

Putting this in the mosquitto directory the installer now works correctly, thank-you.

My conclusion and recomendation to the developers would be this : 

1) The per-requisite instructions given by the installer need updating with regard to the OpenSSL.  The latest installer available, OpenSSL Light 1.1.0g, does not provided the required DLL's. You have to use and older version OpenSSL Light 1.0.2m.

2) VCRUNTIME140.dll is not indicated as a per-requisite in the installer.  This either needs to be added as i) a referenced source with a download reference, ii) perhaps the mosquitto build could be altered to use a static library instead, iii) VCRUNTIME140.dll could be distributed by the installer.
