### ISSUE TITLE
Memory leak in c-client lib 

### ISSUE THREAD

**Issue by ahmedmoustafa94** [eclipse/mosquitto#638]
### issue

This is the memory leak test using valgrind for a program that uses libmosquitto 

command used:
 valgrind -v --leak-check=full --show-leak-kinds=all --track-origins=yes  ./controller_v1 

results:
==14568== HEAP SUMMARY:
==14568==     in use at exit: 64 bytes in 2 blocks
==14568==   total heap usage: 10,144 allocs, 10,142 frees, 818,083 bytes allocated
==14568== 
==14568== Searching for pointers to 2 not-freed blocks
==14568== Checked 677,152 bytes
==14568== 
==14568== 32 bytes in 1 blocks are still reachable in loss record 1 of 2
==14568==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14568==    by 0x5D61E77: CRYPTO_malloc (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==14568==    by 0x5E18B3E: sk_new (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==14568==    by 0x5ADA4E9: ??? (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==14568==    by 0x5ADC5E8: SSL_COMP_get_compression_methods (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==14568==    by 0x5AE1D72: SSL_library_init (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==14568==    by 0x4E40A34: ??? (in /usr/lib/x86_64-linux-gnu/libmosquitto.so.1)
==14568==    by 0x4E3DB60: mosquitto_lib_init (in /usr/lib/x86_64-linux-gnu/libmosquitto.so.1)
==14568==    by 0x402024: initialize (controller.c:219)
==14568==    by 0x401CF3: main (controller.c:88)
==14568== 
==14568== 32 bytes in 1 blocks are still reachable in loss record 2 of 2
==14568==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14568==    by 0x5D61E77: CRYPTO_malloc (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==14568==    by 0x5E18B5C: sk_new (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==14568==    by 0x5ADA4E9: ??? (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==14568==    by 0x5ADC5E8: SSL_COMP_get_compression_methods (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==14568==    by 0x5AE1D72: SSL_library_init (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==14568==    by 0x4E40A34: ??? (in /usr/lib/x86_64-linux-gnu/libmosquitto.so.1)
==14568==    by 0x4E3DB60: mosquitto_lib_init (in /usr/lib/x86_64-linux-gnu/libmosquitto.so.1)
==14568==    by 0x402024: initialize (controller.c:219)
==14568==    by 0x401CF3: main (controller.c:88)
==14568== 
==14568== LEAK SUMMARY:
==14568==    definitely lost: 0 bytes in 0 blocks
==14568==    indirectly lost: 0 bytes in 0 blocks
==14568==      possibly lost: 0 bytes in 0 blocks
==14568==    still reachable: 64 bytes in 2 blocks
==14568==         suppressed: 0 bytes in 0 blocks

so there is leak from SSL_COMP_get_compression_methods 

### possible fix:

Call SSL_COMP_free_compression_methods(); after CRYPTO_cleanup_all_ex_data();

**Comment by ralight** [comment]
I'm reluctant to make changes related to this. This is not a memory leak that increases in size, and is only 64 bytes anyway. The downside to freeing the memory (by using the openssl cleanup function) is that it means it would be impossible to use libmosquitto properly in a program that uses openssl itself, or another library that uses openssl.
