### ISSUE TITLE
Add configuration option aliases to documentation

### ISSUE THREAD

**Issue by CodingSpiderFox** [eclipse/mosquitto#642]
In the meanwhile, trying to understand the "username" option in the config file I got from someone else, I had a look at the code. I found out that "username" and "password" options are an alias for "remote_username" and "remote_password". This should be documented in the mosquitto.conf because otherwise this is quite confusing (also see my first two posts in #640)

**Comment by karlp** [comment]
Or, they shouldn't be, as they are deprecated options that are not to be used, and are only parsed for backwards compatibility with older config files.

**Comment by CodingSpiderFox** [comment]
Yes, that's true. I have to talk to the people who gave me the config
