### ISSUE TITLE
Support of reading configuration options from environment variables

### ISSUE THREAD

**Issue by CodingSpiderFox** [eclipse/mosquitto#643]
I want to be able to store passwords etc. which mosquitto (as bridge) uses in my environment variables.

For example, I set 4 variables in the .profile file of the user under which I start mosquitto:

MOSQUITTO_PASS1 = "PASSWORD"
MOSQUITTO_USER1 = "USER"
MOSQUITTO_PASS2 = "PASSWORD"
MOSQUITTO_USER2 = "USER"

Then, I the mosquitto.conf file, I want to be able to use these variable's values for the configuration variables.

**Comment by karlp** [comment]
Possibly duplicate of #640

**Comment by karlp** [comment]
I still question what you will use to _set_ those variables,but hey, security people like to do things their own ways, and far be it from me to get involved at that point

**Comment by CodingSpiderFox** [comment]
I would simply insert the /home/mosquitto-user/.profile file so they are loaded when the user is logged in. I think this way, they will be available to mosquitto if the user "mosquitto-user" starts the mosquitto software.

**Comment by CodingSpiderFox** [comment]
Found a soultion using docker with .env file and a script that puts the passwords from env vars to where they belong
