### ISSUE TITLE
mosquitto_want_write does not check for want_connect when SSL is enabled

### ISSUE THREAD

**Issue by jsopenrb** [eclipse/mosquitto#648]
I want to use `mosquitto_want_write` to decide whether mosquitto socket should be included in `writefds` or not, but from what I can see in `mosquitto_loop` is that write should not be checked when SSL is enabled and socket is not yet connected. Is this correct behaviour for `mosquitto_want_write`? Or should it behave like this:

```
bool mosquitto_want_write(struct mosquitto *mosq)
{
#ifdef WITH_TLS
  if(mosq->ssl){
    if(mosq->want_write){
      return true;
    }
    else if(mosq->want_connect){
      return false;
    }
  }
#endif
  if(mosq->out_packet || mosq->current_out_packet){
    return true;
  }
  else{
    return false;
  }
}
```

**Comment by PierreF** [comment]
Hi,
thanks for catching it. I've copied the logic from mosquitto_loop to mosquitto_want_write.
