### ISSUE TITLE
closing already closed sockets, not invalidating socket handle, _mosquitto_socket_nonblock

### ISSUE THREAD

**Issue by edwin-oetelaar** [eclipse/mosquitto#649]
https://github.com/eclipse/mosquitto/blob/46630e7325a82644be1a6fef00ef30bbd52c7ef6/lib/net_mosq.c#L326

also on lines 
340
425
442
1247
1275
1293
1299

I think the ```_mosquitto_socket_nonblock``` is misleading, it closes the socket as a side-effect.

```
if(_mosquitto_socket_nonblock(*sock)){
	COMPAT_CLOSE(*sock); /* This is wrong, the socket is already closed by _mosquitto_socket_nonblock() call */
        continue;
```

**Comment by ralight** [comment]
Thanks for spotting this, it's not a fatal problem but nice to have fixed anyway.
