### ISSUE TITLE
Get list of connected clients 

### ISSUE THREAD

**Issue by prasadnadendla** [eclipse/mosquitto#655]
Is there a way to fetch list of active client ids? I tried using the **$SYS/broker/clients/connected**  topic but it's only giving the count of connected clients NOT the client id details

**Comment by ralight** [comment]
No, this isn't possible, but is something that you could implement in your application layer.

**Comment by prasadnadendla** [comment]
can we expect this feature in the next release ? Also what's the best practice to handle at application layer ?

**Comment by ralight** [comment]
No, it's unlikely that this would ever be supported.

You should try to come up with a scheme that works for the requirements that you have.

**Comment by toast-uz** [comment]
Seems to similar with #622 .

**Comment by PierreF** [comment]
Closing as duplicate of #622
