### ISSUE TITLE
develop branch does not compile on Windows

### ISSUE THREAD

**Issue by archerian** [eclipse/mosquitto#656]
Several issues prevent a successful build on Windows..  some of which are

strncasecmp not available (use_strnicmp)
closedir not available (use FindClose)
undeclared local variables in config__get_dir_files (len, i, dh/fh)
SigThreadProc function might be missing a closing brace, and undeclared before use at CreateThread

**Comment by ralight** [comment]
Thanks we'll take a look. For completeness, what are you using to build with?

**Comment by archerian** [comment]
VS 2017 (15.15.1)

**Comment by ralight** [comment]
This commit fixes the build with VS 2015. It disables static libraries by default for the moment.

Thanks for reporting it.
