### ISSUE TITLE
$SYS/broker/clients/disconnected is -1 sometimes

### ISSUE THREAD

**Issue by positron96** [eclipse/mosquitto#659]
Hello. I am monitoring my cloudmqtt instance via `$SYS/broker/clients/disconnected` and `$SYS/broker/clients/connected` topic and notice that several times a day I get disconnected clients count equal to -1.  My setup has two clients connected constantly and one connecting every 10 minutes (posting a message and disconnecting). No clients are persistent. Most of the time I see `clients/connected`=2 and `clients/disconnected`=0 but sometimes `clients/connected`=3 and `clients/disconnected`=-1. This strange state is kept for around 10 seconds, than correct values 2/0 arrive. (sometimes I get an increment of connected clients count followed by decrement but it seems ok in my setup)

Something like that:
Disconnected count:
````
0   2017-12-26 7:30:15 pm 
-1  2017-12-26 7:30:04 pm 
0   2017-12-26 2:00:15 pm 
-1  2017-12-26 2:00:04 pm 
0   2017-12-26 11:11:13 am
````

Connected count:
````
2  2017-12-26 7:30:15 pm 
3  2017-12-26 7:30:04 pm 
2  2017-12-26 3:50:15 pm 
3  2017-12-26 3:50:04 pm  
2  2017-12-26 2:00:15 pm   
3  2017-12-26 2:00:04 pm   
2  2017-12-26 11:11:13 am
````

Version of mosquitto on cloudmqtt is 1.4.10 (from `$SYS/broker/version`)

**Comment by PierreF** [comment]
Closing as duplicate of #287.
$SYS/broker/clients/inactive is the deprecated alias of $SYS/broker/clients/disconnected
