### ISSUE TITLE
Error saving persistence file in Windows

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto#66]
migrated from Bugzilla [#464779](https://bugs.eclipse.org/bugs/show_bug.cgi?id=464779)
status RESOLVED severity *major* in component *Mosquitto* for *1.4*
Reported in version *1.4* on platform *PC*
Assigned to: Roger Light

Original attachment names and IDs:
- _[mosq141.png](https://bugs.eclipse.org/bugs//attachment.cgi?id=252452)_ (ID 252452)
- _[2015-04-16_11-10-10.jpg](https://bugs.eclipse.org/bugs//attachment.cgi?id=252468)_ (ID 252468)

On 2015-04-16 06:34:05 -0400, Szymon Kochanski wrote:

> Created attachment 252452
> bug persistence windows 1.4.1
> 
> In Windows 7.
> 
> In mosquitto.conf I am setting:
> persistence true
> persistence_file mosquitto.db
> persistence_location C:\
> 
> I am running mosquitto as Administrator.
> 
> This file is created: C:\mosquitto.db.new
> 
> I the verbose output I am seeing:
> 1429180388: Saving in-memory database to C:\mosquitto.db.
> 1429180388: Error: No such file or directory.
> 
> See the attached screenshots.
> 
> Thank you!

On 2015-04-16 06:44:10 -0400, Szymon Kochanski wrote:

> Note:
> I used Windows 7 x64.

On 2015-04-16 07:44:09 -0400, Szymon Kochanski wrote:

> I think, I found a workaround.
> 
> If you set up the persistence filename to:
> 
> persistence_file mosquitto.db.new 
> 
> in the mosquitto.conf then it works.

On 2015-04-16 08:50:54 -0400, Szymon Kochanski wrote:

> Further findings:
> 
> The problem only exists when mosquitto.db file does not exist. Once it's created it works fine.
> 
> A better workaround:
> 1. Set:
> persistence_file mosquitto.db
> 2. Start mosquitto - mosquitto.db.new would get created.
> 3. Kill mosquitto.
> 4. Manually move/rename mosquitto.db.new to mosquitto.db
> 5. Start mosquitto again.
> 
> :)

On 2015-04-16 11:26:47 -0400, Cristian Manuel Vertiz Fernandez wrote:

> (In reply to Szymon Kochanski from comment # 2)
> > I think, I found a workaround.
> > 
> > If you set up the persistence filename to:
> > 
> > persistence_file mosquitto.db.new 
> > 
> > in the mosquitto.conf then it works.
> 
> I set the persistence filename to mosquitto.db.new, but it creates mosquitto.db.new.new and it still isn't working
> 
> I worked with mosquitto 1.4.1 in Windows 7 x64

On 2015-04-16 11:28:37 -0400, Cristian Manuel Vertiz Fernandez wrote:

> Created attachment 252468
> In reply to Szymon Kochanski from comment # 2

On 2015-04-16 11:31:23 -0400, Szymon Kochanski wrote:

> > I set the persistence filename to mosquitto.db.new, but it creates
> > mosquitto.db.new.new and it still isn't working
> 
> It's called bad luck. ;) And that's why I recommended workaround 2.

On 2015-04-17 03:36:35 -0400, Szymon Kochanski wrote:

> (In reply to Szymon Kochanski from comment # 6)
> > > I set the persistence filename to mosquitto.db.new, but it creates
> > > mosquitto.db.new.new and it still isn't working
> > 
> > It's called bad luck. ;) And that's why I recommended workaround 2.
> 
> Actually workaround # 1 works if you do the following:
> 1. Set:
> persistence_file mosquitto.db
> 2. Start mosquitto - mosquitto.db.new would get created.
> 3. Kill mosquitto.
> 4. Set:
> persistence_file mosquitto.db.new
> 5. Start mosquitto again.
> 
> That's why it worked for me.

On 2015-04-17 16:20:55 -0400, Roger Light wrote:

> Thanks for the report, this is now fixed in the master branch and will be part of 1.4.2.

**Comment by chelliwell** [comment]
Hi, I'm having the same problems as above, using 1.4.15 (build date 23/03/2018 10:26:57.31)
Even these suggested workarounds aren't helping; I'm running from a non-Admin command prompt, trying to write the persistence file to a directory which has no restrictions for me to write/delete/etc. 
But the .new file keeps getting created with some admin privileges, resulting in errors:
```
1530103263: Saving in-memory database to C:\Temp\mosquitto.db.
1530103263: Error: Permission denied.
```
the first time, then:
```
1530103283: Saving in-memory database to C:\Temp\mosquitto.db.
1530103283: Error saving in-memory database, unable to open C:\Temp\mosquitto.db.new for writing.
1530103283: Error: Bad file descriptor.
```
I've tried adding Full Control permissions for Everyone on the file(s), but without any success. Tried that on the .new then removing the .new, but mosquitto just seems to re-create a write-protected .new again.
Config file has:
```
autosave_interval 20
persistence true
persistence_file mosquitto.db
persistence_location C:\Temp\
```

Is there something else I'm missing here?
