### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by autofit** [eclipse/mosquitto#661]
Subscribing to topic:c/v1/lock_unbind/1000062
QoS:1
Sub msg:c/v1/lock_unbind/1000062
Subscribing to topic:c/v1/reset/1000062
QoS:1
Sub msg:c/v1/reset/1000062

Connection lost
     cause: (null)

**Comment by PierreF** [comment]
Closing as no information provided.

Is this happening on client side ?
What are those message ? Custom log on specific place ?  What happen on the other side (server log).
What are you doing to product this issue ?

From those logs, I would guess that you are subscribing to c/v1/lock_unbind/1000062 and c/v1/reset/1000062. I don't reproduce any connection lost by just subscribing to topic.

Feel free to reopen the issue with more information so we can try to reproduce this issue.
