### ISSUE TITLE
install mosquitto-clients can not download libmosquitto 

### ISSUE THREAD

**Issue by mcmellow** [eclipse/mosquitto#662]
After the command: $ sudo apt-get install mosquitto-clients
The following errors  are received: 
Err:1 http://repo.mosquitto.org/debian stretch/main armhf libmosquitto1 armhf 1.4.12-0mosquitto1
  404  Not Found [IP: 85.119.83.194 80]
Err:2 http://repo.mosquitto.org/debian stretch/main armhf mosquitto-clients armhf 1.4.12-0mosquitto1
  404  Not Found [IP: 85.119.83.194 80]
E: Failed to fetch http://repo.mosquitto.org/debian/pool/main/m/mosquitto/libmosquitto1_1.4.12-0mosquitto1_armhf.deb  404  Not Found [IP: 85.119.83.194 80]
E: Failed to fetch http://repo.mosquitto.org/debian/pool/main/m/mosquitto/mosquitto-clients_1.4.12-0mosquitto1_armhf.deb  404  Not Found [IP: 85.119.83.194 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

After the command: $ sudo apt-get install mosquitto-clients --fix-missing 
The following errors  are received: 
Err:1 http://repo.mosquitto.org/debian stretch/main armhf libmosquitto1 armhf 1.4.12-0mosquitto1
  404  Not Found [IP: 85.119.83.194 80]
Err:2 http://repo.mosquitto.org/debian stretch/main armhf mosquitto-clients armhf 1.4.12-0mosquitto1
  404  Not Found [IP: 85.119.83.194 80]
Unable to correct missing packages.
E: Failed to fetch http://repo.mosquitto.org/debian/pool/main/m/mosquitto/libmosquitto1_1.4.12-0mosquitto1_armhf.deb  404  Not Found [IP: 85.119.83.194 80]
E: Failed to fetch http://repo.mosquitto.org/debian/pool/main/m/mosquitto/mosquitto-clients_1.4.12-0mosquitto1_armhf.deb  404  Not Found [IP: 85.119.83.194 80]
E: Aborting install.

Please help
McMelloW

**Comment by Tifaifai** [comment]
In the website ```http://repo.mosquitto.org/debian/pool/main/m/mosquitto/,``` you can see the transfert from Mosquitto 1.4.12 to Mosquitto 1.4.14

You can make : 
  ```apt-get update``` or by hand

  ```sudo dpkg -i DEB_PACKAGE``` DEB_PACKAGE is for example : libmosquitto1_1.4.14-0mosquitto1 ~ nows1_armhf.deb  or  mosquitto-clients_1.4.14-0mosquitto1 ~ nows1_armhf.deb 

or better solution, read```compiling.txt```

**Comment by mcmellow** [comment]
Thanks for the update. anf it worked OK.
I found a link to build it from source on my raspberry. This took some time but it worked OK.

**Comment by Tifaifai** [comment]
You're welcome ! you can close ;)
