### ISSUE TITLE
Windows Install directions Incorrect

### ISSUE THREAD

**Issue by schellem** [eclipse/mosquitto#664]
The Open SSL assemblies the directions call for do not exist in the latest Open SSL Light version.

**Comment by karlp** [comment]
And what is this "Light" version?  Is that what the documentation calls for?

**Comment by karlp** [comment]
(if you're talking about these shining light repackages, then of course they don't work in the light version, the light version is by definition excluding all the developer libraries you actually need)

**Comment by schellem** [comment]
The directions explicitly state 'light' version and if I remember correctly that is the only option to download.
![openssl](https://user-images.githubusercontent.com/5617425/34508741-bb0abfae-f010-11e7-8a3e-41159f926f5c.PNG)

**Comment by karlp** [comment]
ok, my bad, you're looking at something different to what I was looking at.

**Comment by ralight** [comment]
You need openssl 1.0.2, not 1.1.0.

**Comment by mgrusin** [comment]
The "heavy" SSL version of 1.1.0 does not have the required files either.

The above dependencies window really needs this information and probably the mosquitto download page as well. The current install instructions do not work.

**Comment by ralight** [comment]
The windows installer has been improved a lot, so I think this can be closed now.
