### ISSUE TITLE
UNSUBSCRIBE with no topic is accepted and responded with UNSUBACK

### ISSUE THREAD

**Issue by uboscolo** [eclipse/mosquitto#665]
I am using mosquitto broker 1.4.14 on ubuntu 16.04.

/usr/sbin/mosquitto -h
mosquitto version 1.4.14 (build date Tue, 11 Jul 2017 00:29:26 +0100)

mosquitto is an MQTT v3.1.1/v3.1 broker.
....

I am using mqtt paho python client to connect to the broker and send an UNSUBSCRIBE message with no topics.

Based on http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf   

Section: [MQTT-3.10.3-2].
The Payload of an UNSUBSCRIBE packet MUST contain at least one Topic Filter. 
An UNSUBSCRIBE packet with no payload is a protocol violation

I was expecting the connection to be closed and to not receive the UNSUBACK message.

Probably not an important issue, but please let me know your comments.
I have attached a wireshark trace for reference

[unsub_no_topics.pcapng.gz](https://github.com/eclipse/mosquitto/files/1600577/unsub_no_topics.pcapng.gz)

**Comment by toast-uz** [comment]
Exactly! It's a bug on both of master and develop branch.

**Comment by toast-uz** [comment]
Fixed only on develop branch because of a minor issue.

**Comment by ralight** [comment]
That fix has now been merged, thanks very much both of you.
