### ISSUE TITLE
Getting several messages in one TCP/IP payload

### ISSUE THREAD

**Issue by arturioxas** [eclipse/mosquitto#666]
I would like to ask if mosquitto server supports getting several messages in one payload. I would like to compress several messages and have less overhead and therefore save some data.

**Comment by toast-uz** [comment]
Completely depends on the end-applications. MQTT message payload can be any binary data. Generic MQTT broker (includes Mosquitto) transfers the payload transparently.

You can talk at https://groups.google.com/forum/#!forum/mqtt about this type of generic MQTT questions, or at Mosquitto-dev ML about Mosquitto specific questions.
