### ISSUE TITLE
mosquitto 1.4.14 on official docker repository

### ISSUE THREAD

**Issue by Foxhunt** [eclipse/mosquitto#669]
Hi,

is it possible to publish mosquitto 1.4.14 on the official eclipse-mosquitto docker repository?

It has been six months since it got added to the develop branch with #500.
This was already addressed in #606, but not commented by any maintainer.

Is there a place to get in touch? The Paho channel on the clipse.org Mattermost server is kind of dead. So i'm asking here.

**Comment by vinceskahan** [comment]
Doesn't it depend on what packages Alpine Linux provides upstream ?  Read the Dockerfile.

Edit the Dockerfile to use alpine:3.7 and specify mosquitto=1.4.14-r3 in it and build your own container that way.  Works fine.

**Comment by Foxhunt** [comment]
That is what we ended up doing.

`FROM eclipse-mosquitto:latest ` should provide you the _latest_ mosquitto version, but it doesen't.
The needed Dockerfile is already on the develop branch, so it could be published to the official Docker Hub repository. So building your own alpine + mosquitto image would not be necessary.

**Comment by vielmetti** [comment]
v1.5 is out now, and I've noted this at https://github.com/docker-library/official-images/issues/4358

**Comment by J0WI** [comment]
https://github.com/docker-library/official-images/blob/master/library/eclipse-mosquitto should be updated

**Comment by sasincj** [comment]
Hi, Why docker hub is not updated with latest mosquitto version. When mosquitto 1.5.3 will be available at docker hub?

**Comment by ralight** [comment]
1.5.3 is now available on the official image and will be kept up to date.
