### ISSUE TITLE
Wrong version in package list for armhf on stretch.

### ISSUE THREAD

**Issue by ludeeus** [eclipse/mosquitto#671]
I know there has been issues with installing on stretch with missing dependencies.

This issue is mainly regarding `mosquitto-clients` but aslo `libmosquitto1`.
The closest I found to this was this closed one: #662 

Error message:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libc-ares2 libmosquitto1
The following NEW packages will be installed:
  libc-ares2 libmosquitto1 mosquitto-clients
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 98.9 kB/175 kB of archives.
After this operation, 403 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 http://repo.mosquitto.org/debian stretch/main armhf libmosquitto1 armhf 1.4.12-0mosquitto1
  404  Not Found [IP: 85.119.83.194 80]
Err:2 http://repo.mosquitto.org/debian stretch/main armhf mosquitto-clients armhf 1.4.12-0mosquitto1
  404  Not Found [IP: 85.119.83.194 80]
E: Failed to fetch http://repo.mosquitto.org/debian/pool/main/m/mosquitto/libmosquitto1_1.4.12-0mosquitto1_armhf.deb  404  Not Found [IP: 85.119.83.194 80]
E: Failed to fetch http://repo.mosquitto.org/debian/pool/main/m/mosquitto/mosquitto-clients_1.4.12-0mosquitto1_armhf.deb  404  Not Found [IP: 85.119.83.194 80]
```
And yes I have tried `sudo apt-get update`.
The issue is that the package for armhf is pointing to version `1.4.12-0mosquitto1`
http://repo.mosquitto.org/debian/dists/stretch/main/binary-armhf/Packages
And when inspecting the pool, the 404 make sense, as there are no packages for `1.4.12`, only `1.4.14`.

The package list for both [amd64](http://repo.mosquitto.org/debian/dists/stretch/main/binary-amd64/Packages) and [i386](http://repo.mosquitto.org/debian/dists/stretch/main/binary-i386/Packages) points to `1.4.14`.

**Comment by ralight** [comment]
Could you try with the updated repository now please? I've lost raspberry pi building capabilities and have had to get into cross compiling, so I'm not as confident about the result.

**Comment by ludeeus** [comment]
@ralight Tested it now, an version 1.4.14 downloaded and installed as expected 👍 
Thanks! :D

**Comment by ralight** [comment]
I presume you checked to see it was running as well... :)

**Comment by ludeeus** [comment]
@ralight 
That is correct :)
```
sudo systemctl status mosquitto.service
● mosquitto.service - Mosquitto MQTT Broker
   Loaded: loaded (/lib/systemd/system/mosquitto.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2018-01-14 17:19:29 UTC; 3h 32min ago
```
