### ISSUE TITLE
Mosquitto process 636 failed

### ISSUE THREAD

**Issue by willgower** [eclipse/mosquitto#672]
Trying to set up mosquitto on openhabian. I cant get it working and when i look at its status:

`sudo systemctl status mosquitto -l`

I get the following response:

```
● mosquitto.service - Mosquitto MQTT Broker
   Loaded: loaded (/lib/systemd/system/mosquitto.service; enabled)
   Active: failed (Result: start-limit) since Sat 2018-01-13 21:15:08 GMT; 16h ago
     Docs: man:mosquitto(8)
           https://mosquitto.org/
  Process: 636 ExecStart=/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf (code=exited, status=1/FAILURE)
 Main PID: 636 (code=exited, status=1/FAILURE)

Jan 13 21:15:07 openHABianPi systemd[1]: Unit mosquitto.service entered failed state.
Jan 13 21:15:08 openHABianPi systemd[1]: mosquitto.service holdoff time over, scheduling restart.
Jan 13 21:15:08 openHABianPi systemd[1]: Stopping Mosquitto MQTT Broker...
Jan 13 21:15:08 openHABianPi systemd[1]: Starting Mosquitto MQTT Broker...
Jan 13 21:15:08 openHABianPi systemd[1]: mosquitto.service start request repeated too quickly, refusing to start.
Jan 13 21:15:08 openHABianPi systemd[1]: Failed to start Mosquitto MQTT Broker.
Jan 13 21:15:08 openHABianPi systemd[1]: Unit mosquitto.service entered failed state.
```

Any ideas on what process 636 is and how I can fix this? Thanks

**Comment by karlp** [comment]
636 is probably just the PID of that time.

You almost definitely have an config file problem.

try running "sudo /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf" (the ExecStart= line) yourself and see what the real error is.  (IMO, this is a systemd failing in how it presents these failures)

**Comment by willgower** [comment]
Cheers, I am getting:

`1515948081: Error: Unable to open log file /var/log/mosquitto/mosquitto.log for writing.`

Any idea how to solve this?

**Comment by ralight** [comment]
Either /var/log/mosquitto doesn't exist, or it isn't owned by the `mosquitto` user, or the write permissions are missing.

Try `sudo mkdir /var/log/mosquitto` then `sudo chown mosquitto /var/log/mosquitto`

Finally, check if /var/log/mosquitto/mosquitto.log already exists and that it doesn't have the correct ownership/permission.

**Comment by willgower** [comment]
@ralight the directory and log file do exist. How do i check/change permissions?

**Comment by willgower** [comment]
You were right, I figured how to change the permissions and that has fixed it

**Comment by fcarlier** [comment]
# cd /var/log
# mkdir mosquitto
# cd mosquitto
# touch mosquitto.log

and restart mosquitto

Envoyé de mon terminal mobile

**Comment by karlp** [comment]
@fcarlier that won't help at all if the mosquitto process isn't running as root, please be careful with such advice.

**Comment by karlp** [comment]
@willgower if your issue has been resolved, please close this ticket.
