### ISSUE TITLE
SigThreadProc thread runs at 100% single core usage

### ISSUE THREAD

**Issue by archerian** [eclipse/mosquitto#673]
When running mosquitto server from the develop branch, the second thread created to handle external signals is maxing out a core.

Specifically, in signals.c

`DWORD WINAPI SigThreadProc(void* data) `

is using a core at 100%. For now I have commented out 

`CreateThread(NULL, 0, SigThreadProc, NULL, 0, NULL);`

on mosquitto.c, disables starting that thread.

**Comment by archerian** [comment]
For this issue, I think WaitForMultipleObjects(sizeof(evt) / sizeof(HANDLE), evt, FALSE, INFINITE); in line 121 in signals.c should be 
WaitForMultipleObjects(3, evt, FALSE, INFINITE); 

or maybe static HANDLE evt[4]; in line 110 should be static HANDLE evt[3];

Having an extra uninitialized wait handle could lead to WAIT_FAILED which keeps the infinite loop churning CPU.

**Comment by kynowoo** [comment]
Same problem.
 WaitForMultipleObjects() returns WAIT_FAILED immediately with Last error ERROR_INVALID_HANDLE.
Thanks @archerian for the solution.

**Comment by ralight** [comment]
This was fixed a while back, thanks for the solution.
