### ISSUE TITLE
build 1.4.14 docker image failed

### ISSUE THREAD

**Issue by vklonghml** [eclipse/mosquitto#675]
Hi all,

i want to get 1.4.14 docker image, but it does not exist in docker hub, so i build it from docker file, and an error as below:

root@ceph-deploy:~/mosquitto/docker/1.4.14# docker build -t eclipse-mosquitto:1.4.14 .
Sending build context to Docker daemon  5.12 kB
Step 1 : FROM alpine:edge
 ---> 5c4fa780951b
Step 2 : MAINTAINER David Audet <david.audet@ca.com>
 ---> Using cache
 ---> ab2f5e86b72a
Step 3 : LABEL Description "Eclipse Mosquitto MQTT Broker"
 ---> Using cache
 ---> 2816df35c98e
Step 4 : RUN apk --no-cache add mosquitto=1.4.14-r0 &&     mkdir -p /mosquitto/config /mosquitto/data /mosquitto/log &&     cp /etc/mosquitto/mosquitto.conf /mosquitto/config &&     chown -R mosquitto:mosquitto /mosquitto
 ---> Running in 162232bcce91
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  mosquitto-1.4.14-r4:
    breaks: world[mosquitto=1.4.14-r0]
The command '/bin/sh -c apk --no-cache add mosquitto=1.4.14-r0 &&     mkdir -p /mosquitto/config /mosquitto/data /mosquitto/log &&     cp /etc/mosquitto/mosquitto.conf /mosquitto/config &&     chown -R mosquitto:mosquitto /mosquitto' returned a non-zero code: 1

does anybody know this issue, thank you in advance.

**Comment by KrishnakNamburi** [comment]
was this issue resolve? how did you resolve it? I see the sam error with 1.14.12-r0.


fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  mosquitto-1.4.15-r0:
    breaks: world[mosquitto=1.4.12-r0]
The command '/bin/sh -c apk --no-cache add mosquitto=1.4.12-r0' returned a non-zero code: 1

**Comment by ralight** [comment]
The docker file has been extensively rewritten and a new version uploaded so this problem has probably been fixed. I'm going to close this, if you still have problems, please open a new issue.
