### ISSUE TITLE
Connection state (notifications=true) only for local brokers

### ISSUE THREAD

**Issue by ksheurs** [eclipse/mosquitto#677]
Question - is there a way to enable the `$SYS/broker/connection/<clientid>/state` topic but only for the local brokers / clients? We are using AWS IoT which does not allow `notifications true`, but with that set to false local devices connected to our bridge have no idea about the upstream connection state to AWS IoT. Thank you!

**Comment by cjmaynard** [comment]
As far as I'm aware, this is not yet possible.  I think this issue is basically a duplicate of issue #233 though and can probably be closed as such, no?

**Comment by cjmaynard** [comment]
As far as I’m aware, this is not yet possible.  See https://github.com/eclipse/mosquitto/issues/233​​​​
- Chris

**Comment by ksheurs** [comment]
Thanks Chris. Yes duplicate of #233. Closing.
