### ISSUE TITLE
Storing messages without calling .php file

### ISSUE THREAD

**Issue by pokal4u** [eclipse/mosquitto#678]
HI,
Using the below code to sending /receiving messages successfully.
is there a way to stored these messages for later accessing without calling .php file?

var client = new Paho.MQTT.Client("domain", Number(1883),  "myClientId" + new Date().getTime());
client.onConnectionLost = onConnectionLost;
client.onMessageArrived = onMessageArrived;
client.onMessageDelivered = onMessageDelivered;

function onStart() {
	client.connect({userName : username,password : password,onSuccess:onConnect,onFailure:doFail,useSSL:true,cleanSession:false});
}
function doFail(responseObject) {
	console.log("Connection failed"+responseObject.errorMessage);
}
function onConnect() {  
	console.log("Connected<br>");		
}
function onMessage() {
	var message=$("#message").val();  
	client.subscribe("chat/"+from_user);
	message = new Paho.MQTT.Message(message);
	message.destinationName = "chat/"+to_user;
	client.send(message);
	$("#message").val('');
}
function onConnectionLost(responseObject) {	
	if (responseObject.errorCode !== 0) {
		console.log("onConnectionLost:"+responseObject.errorMessage);
	}
}
function onMessageArrived(message) {
	console.log(message);
	$("#conversation").append("You:"+message.payloadString+"<br>");
}
function onMessageDelivered(message) {
	$("#conversation").append("Me:"+message.payloadString+"<br>");
}

Thanks
Srinivas

**Comment by ralight** [comment]
I'm not really sure what your question is and how it relates to mosquitto, can you clarify?

**Comment by pokal4u** [comment]
Here I am using broker mosquito. So I need to store messages into db or files or anywhere without using any php file.

**Comment by ralight** [comment]
I see - in that case you'll need to write a client that subscribes to the topics you are interested in and then stores them in a database. That could be something like this: https://github.com/eclipse/mosquitto/blob/master/examples/mysql_log/mysql_log.c
