### ISSUE TITLE
Improvement: write information about Will message to the log

### ISSUE THREAD

**Issue by barrierbank** [eclipse/mosquitto#680]
Mosquitto (1.4.14) never logs information about the will message, even with the "-v" command line option.

It would be useful if Mosquitto could log the basic information about the will message, either at will_set or on connection: topic, message length, retain flag and QOS at least.  As it stands, we had to modify the code to find out whether a third party device was setting the retain flag on its Will message.

**Comment by toast-uz** [comment]
Understood.
You can create new PR for realizing it. I guess you need to add new logging codes of the will message after the codes of connected logs in src/handle_connect.c on develop branch.

**Comment by shallax** [comment]
I've submitted here: https://github.com/eclipse/mosquitto/pull/682

**Comment by toast-uz** [comment]
Closing as a new feature request. Regarding https://mosquitto.org/ , this place is for reporting bugs. Refer from PR to this issue.
