### ISSUE TITLE
Static compile

### ISSUE THREAD

**Issue by cedricve** [eclipse/mosquitto#687]
Hello, I've found that it's possible to static compile the mosquito library: https://github.com/eclipse/mosquitto/blob/develop/config.mk#L87. However I didn't found any variable in the CMakelists.txt file? Any reason why this isn't available yet?

Love this library <3

**Comment by karlp** [comment]
as per the readme, the cmakefiles are only for windows builds.  If you're creating armbian packages, use the makefile as intended.

**Comment by cedricve** [comment]
thanks @karlp, but how to compile static on OSX/Windows then?

**Comment by karlp** [comment]
now  you're asking the actual question :)  probably because you're the first to want to.

**Comment by cedricve** [comment]
hah 👍  well weird thing is that we've previously made it work with this commit branch https://github.com/kerberos-io/machinery/blob/master/cmake/External-Mosquitto.cmake#L5. But upgrading to develop branch won't work anymore. Was wondering what changed, before diving deep.

**Comment by karlp** [comment]
ok, so now you're providing all the information you reallly couldll have provided up front :)

- osx/windows, used to make static library ok
- switched to develop branch, can't do it anymore.

That's a quite different issue altogether! (I'lll let someone else answer)

For my own education though, what's the motivation for requiring static builds anyway?

**Comment by cedricve** [comment]
sorry about the lack of info @karlp. We don't want to give our users the possibility to mess with different versions of dependencies (which makes it very hard to debug and support). The Kerberos.io project is open-source by the way.

**Comment by cedricve** [comment]
Yep correct with this commit (9c6a5f3cf0ff6d70f3579257620ce8ace5d1eba6), it started using the WITH_STATIC_LIBRARIES variable to determine if it should build static libraries or not.

https://github.com/eclipse/mosquitto/blob/9c6a5f3cf0ff6d70f3579257620ce8ace5d1eba6/lib/CMakeLists.txt#L1

However there is no way to enable the property when using CMake. I'll create a PR for this.

**Comment by cedricve** [comment]
hmm, my bad unfortantely I used "yes/no" instead of "ON/OFF". Closing this.
