### ISSUE TITLE
Mixed mode in Authentication

### ISSUE THREAD

**Issue by ntthanh** [eclipse/mosquitto#690]
Hi Mosquitto experts,

Is this possible for Mosquitto to enable a mixed mode Authentication to support SSL Client Certificate Auth (request_certificate true) and Username/password (with password_file) over TLS to live together? 

Thanks a lot in advance for your help!
Thanh

**Comment by toast-uz** [comment]
I didn't try but I guess the answer is true by reading the Authentication section of https://mosquitto.org/man/mosquitto-conf-5.html . Did you read and try it?

**Comment by toast-uz** [comment]
Closing. If you have any more question, post at mosquitto-dev ML.
