### ISSUE TITLE
SUBSCRIBE with U+0000 is acknowledged

### ISSUE THREAD

**Issue by uboscolo** [eclipse/mosquitto#693]
I am using mosquitto broker 1.4.14 on ubuntu 16.04.

/usr/sbin/mosquitto -h
mosquitto version 1.4.14 (build date Tue, 11 Jul 2017 00:29:26 +0100)

mosquitto is an MQTT v3.1.1/v3.1 broker.
....

I am using mqtt paho python client to connect to the broker and send a SUBSCRIBE message with a topic that contains 0x00 (U+0000).

Based on http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf

MQTT-4.7.3-2

            Topic Names and Topic Filters MUST NOT include the null character (Unicode U+0000).

I was expecting the connection to be closed and to not receive the SUBACK message.

Probably not an important issue, but please let me know your comments.
I have attached a wireshark trace for reference

**Comment by uboscolo** [comment]
[mqtt_subscribe_with_0x00.pcapng.gz](https://github.com/eclipse/mosquitto/files/1707945/mqtt_subscribe_with_0x00.pcapng.gz)

**Comment by toast-uz** [comment]
Could you try the latest develop branch? Seems to begin to check UTF-8 strings strictly on develop branch. 

Based on "A UTF-8 encoded string MUST NOT include an encoding of the null character U+0000. If a receiver (Server or Client) receives a Control Packet containing U+0000 it MUST close the Network Connection [MQTT-1.5.3-2]."

**Comment by ralight** [comment]
@uboscolo thanks this is a good find. The 1.4 code doesn't do any UTF-8 checking so I don't propose to fix this there. The develop branch does do UTF-8 checking but doesn't catch this, I'll work up a fix.

**Comment by uboscolo** [comment]
Hi, I have verified that the SUBSCRIBE is now fixed in the dev branch. However a similar issue occurs for the PUBLISH, I have attached a new trace, let me know if you'd like it to track it in a different issue
[invalid_topic.pcapng.gz](https://github.com/eclipse/mosquitto/files/1904254/invalid_topic.pcapng.gz)

**Comment by ralight** [comment]
I think the latest change covers all the bases.

**Comment by uboscolo** [comment]
Yes, I confirm - see latest trace

[4_7_3_2_successful.pcapng.gz](https://github.com/eclipse/mosquitto/files/1907784/4_7_3_2_successful.pcapng.gz)
