### ISSUE TITLE
mosquitto_sub "-x" option

### ISSUE THREAD

**Issue by claud9999** [eclipse/mosquitto#697]
According to: http://mosquitto.org/man/mosquitto_sub-1.html there is a "-x" flag but I'm not seeing it in the 1.4.14 mosquitto_sub on my machine and also not seeing it in  https://github.com/eclipse/mosquitto/blob/master/client/client_shared.c so I'm guessing this is either old or future.

Also the link to the bug information in the online man page is also outdated: https://bugs.eclipse.org/bugs/describecomponents.cgi?product=Mosquitto

**Comment by Tifaifai** [comment]
In develop branch, you have a new function ```check_format``` in client_shared.c
https://github.com/eclipse/mosquitto/blob/develop/client/client_shared.c#L39

```-F x```
Argument line is -F (https://github.com/eclipse/mosquitto/blob/develop/client/client_shared.c#L464)
Option x (payload in hex)

``` mosquitto/man/mosquitto_sub.1.xml``` is OK in develop branch.

http://mosquitto.org/man/mosquitto_sub-1.html is for master branch. Delete 
```
-x
Print published message payloads as hexadecimal data.
```

**Comment by ralight** [comment]
You're right, the recent website change has resulted in the wrong man pages being up on the web. That should be fixed now. Thanks for reporting it, if you agree that it's fixed please close the issue.
