### ISSUE TITLE
Dynamic topics broker via mosquitto.conf

### ISSUE THREAD

**Issue by becklo** [eclipse/mosquitto#703]
Hi, 

I would like to know if it is possible to change dynamically a broker subscription via the mosquitto.conf file without restarting my broker ? 
It would be use to adapt the subscription to the flow of data (if there are not too many messages all priority are received otherwise only high priority messages will be receive). 

Best regards.

**Comment by toast-uz** [comment]
The broker cannot filter published messages. Only the publisher can control its publishing.
You can add an external app beside the broker. The app can realize your requirement by subscribing all messages and publishing  filtered messages. You can easily make the app by using Node-RED.

**Comment by becklo** [comment]
Thank you, it worked perfectly !

**Comment by toast-uz** [comment]
Great! Could you close this issue?
