### ISSUE TITLE
$SYS - websocket connections

### ISSUE THREAD

**Issue by szymonskirgajllo** [eclipse/mosquitto#707]
Hi

how can I get number of connected users via websocket?

$SYS/broker/clients/connected gives me the number of connected clients but only via mqtt protocol

**Comment by karlp** [comment]
I can't find it, but I seem to recall a fix for this not too long ago on the develop branch.  EIther way, this works on the develop branch at least.

**Comment by szymonskirgajllo** [comment]
@karlp thanks for reply

when you have a plan to release a new stable version?

**Comment by ralight** [comment]
The version running on test.mosquitto.org (1.4.14) sends $SYS/broker/clients/connected just fine - see it at https://test.mosquitto.org/sys/

**Comment by szymonskirgajllo** [comment]
@ralight i cant use 1.4.14 because there is a bug which described here: https://github.com/eclipse/mosquitto/issues/633 

(i've added comment with steps to reproduce that problem)

**Comment by ralight** [comment]
Closing because 633 is resolved and so >1.4.14 is now possible here.
