### ISSUE TITLE
Broker hogging up memory when subscriber with -c flag disconnects.

### ISSUE THREAD

**Issue by karandeepdps** [eclipse/mosquitto#711]
Hey, i am sending **1000000 messages(using mqtt-malaria)** of **size 300** to my **mosquitto broker 1.1.14** running on aws t2.micro centos 7.

I have observed that if my **consumer disconnect**, **% age of memory used by broker start increasing.**
**Even after dumping the packets to local DB memory consumption does not decrease.**

>   PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                    
>  3634 ec2-user  20   0  640m 603m 4916 R 99.8 **60.8**  46:06.62 mosquitto 

                  
I tried to reconnect the consumer following are the observations.

1. **Local DB size reduces to bytes when all the packets are delivered.**
2. **%MEM usage remains the same.**

The only way to reduce Ram is restarting the broker.

Below is my mosquitto.conf file:

> `# Place your local configuration in /etc/mosquitto/conf.d/
> 
> pid_file /var/run/mosquitto.pid
> 
> persistence true
> #persistence_location /var/lib/mosquitto/
> persistence_location ./
> 
> 
> log_type all
> log_dest topic
> log_dest stdout
> log_dest file ./mosquitto.log
> 
> max_inflight_messages 1000
> max_queued_messages 1000000
> #include_dir /etc/mosquitto/conf.d
> persistence_file kd.db
> autosave_interval 30
> autosave_on_changes false`
>

**Comment by karlp** [comment]
As I understand it, (not a developer) the persistence file is _just_ a backup of what's in ram.  It doesn't take the place of ram.  So if you have queued messages, they are in ram and on disk.  The persistence_file is _only_ for persisting across restarts of the broker, not for reducing ram usage.

**Comment by karandeepdps** [comment]
Ok then I will try persistent_client_expiration duration

**Comment by karandeepdps** [comment]
bump. still hogging up memory.

**Comment by karlp** [comment]
so, did you verify that your clients were expired?

**Comment by karandeepdps** [comment]
yes, the client(consumer) got expired but still, memory hogging is there.

**Comment by karandeepdps** [comment]
I testing with emqtt and everything works fine with erlang broker.

**Comment by ralight** [comment]
I suspect that what you are seeing is an artefact of the way heap memory allocation works. If I allocate a load of memory, then free all of the memory except for the very final item that I allocated, then it isn't possible for the heap to be shrunk even though the actual memory in use by the process is reduced.

See https://github.com/ralight/heap-allocation for an example.

**Comment by karandeepdps** [comment]
I was suspecting the same.Will update you with more details.Thanks.

**Comment by mdemblani** [comment]
Hi, are there any updates on this thread. Lately, we also have been seeing a similar behavior on our MQTT Broker. Extending the resources available to MQTT seems to work, but instead it just pushes this issue behind. Doesn't help in permanently addressing it.

I am using MQTT within a docker container.

**Comment by ralight** [comment]
@mdemblani If you have more specific information you can give about your situation please reopen this issue, otherwise I think the original author hasn't responded for a while now so I'm closing it.
