### ISSUE TITLE
VS2015 snprintf config.h

### ISSUE THREAD

**Issue by Wiz-IO** [eclipse/mosquitto#714]
#ifdef WIN32
#if _MSC_VER < 1900 // vs2015 already have this function
#define snprintf _snprintf_s 
#endif

**Comment by Wiz-IO** [comment]
ups, sorry, it is allredy done

**Comment by toast-uz** [comment]
Shall I close this issue?

**Comment by Wiz-IO** [comment]
yes - my mistake
it is ok
