### ISSUE TITLE
Allow passing in openssl SSL_CTX or SSL objects

### ISSUE THREAD

**Issue by daurnimator** [eclipse/mosquitto#715]
I'd like to use more advanced TLS options than what [`mosquitto_tls_set`](https://mosquitto.org/api/files/mosquitto-h.html#mosquitto_tls_set) allows.
Could you add an API that allows passing in an openssl `SSL_CTX*` or `SSL*`?

**Comment by karlp** [comment]
Is this the same as https://github.com/eclipse/mosquitto/pull/567 or would you like something different?

**Comment by daurnimator** [comment]
Slightly different. That pr only lets you modify the existing one, not use your own. Using your own would be a more general solution.

**Comment by ralight** [comment]
Does 8470ca89b9ea4123e386455bb30bcd6f548792a4 work for you?

**Comment by ralight** [comment]
I'm closing this, it'll be part of version 1.5.

**Comment by daurnimator** [comment]
Please add the openssl 1.0.2 compat I mentioned above.
There's still enough distros using 1.0.2 that not having it is going to be a major compatibility pain.

**Comment by daurnimator** [comment]
Thankyou :) I see it was added in b2bb48ac2bfd3ec4496837d831b6af18fa42a3e8

**Comment by daurnimator** [comment]
Btw, have you tested with LibreSSL? It needs the fallback path too I believe.

**Comment by daurnimator** [comment]
> Thankyou :) I see it was added in b2bb48a

Btw, I'm not sure you want either path to be taken when `WITH_TLS` is false.
