### ISSUE TITLE
v1.4.15 breaks TLS on Windows

### ISSUE THREAD

**Issue by vertecx** [eclipse/mosquitto#716]
Hello,

After upgrading from Mosquitto 1.4.14 to 1.4.15 on Windows (Native, not Cygwin), my TLS enabled clients are no longer able to connect. The following error is displayed in Mosquitto when a client tries to connect:

```
1520272062: New connection from 192.168.0.152 on port 8883.
1520272062: Socket error on client <unknown>, disconnecting.
```

I've noticed the switch from OpenSSL 1.0 to 1.1 and I've replaced the old DLL:s (libeay32.dll, libssl32.dll, ssleay32.dll) with the new (libcrypto-1_1.dll, libssl-1_1.dll) from Win32 OpenSSL v1.1.0g Light.

I’ve done some testing and found the following:

- Compiling 4f838e51611b9a71f2e3e98e6fddd02a5c1b4c03 (Tag v1.4.15) against Win32 OpenSSL v1.0.2n make the problem go away.
- There is a difference in behavior when handling the first packet received depending on which OpenSSL version Mosquitto is compiled against. In the file lib/net_mosq.c, function _mosquitto_packet_read, starting at line 1033 the following code exists:

```c
#ifdef WIN32
   errno = WSAGetLastError();
#endif
   if(errno == EAGAIN || errno == COMPAT_EWOULDBLOCK){
      return MOSQ_ERR_SUCCESS;
   }else{
      switch(errno){
         case COMPAT_ECONNRESET:
            return MOSQ_ERR_CONN_LOST;
         default:
            return MOSQ_ERR_ERRNO;
      }
   }
```

- Some lines before this code, errno is set in a call to _mosquitto_net_read where SSL_read returns -1 and SSL_get_error returns SSL_ERROR_WANT_READ for the first packed, independent of OpenSSL version.

- When running 1.0.2n, errno has a value of 11 (EAGAIN) before the call to WSAGetLastError. After the call, errno holds the value 10035 (COMPAT_EWOULDBLOCK). This causes the function to return MOSQ_ERR_SUCCESS.

- When running 1.1.0g, errno has a value of 11 (EAGAIN) before the call to WSAGetLastError. After the call, errno holds the value 0. This causes the function to return MOSQ_ERR_ERRNO.

- When MOSQ_ERR_SUCCESS is returned, _mosquitto_packet_read  is eventually recalled and SSL_read 
starts returning decrypted data. When MOSQ_ERR_ERRNO is returned, the client is immediately disconnected.

- By ignoring the value of errno and instead always return MOSQ_ERR_SUCCESS, it is possible to trick TLS into working when compiling against OpenSSL 1.1.0g. The first or first few calls to SSL_read will fail but eventually start working as they are retired instead of the client being disconnected.

- I've not looked in to what is causing WSAGetLastError to return different values.

**Comment by ralight** [comment]
The openssl upgrade to 1.1.0 was unintentional, there has been porting work done in the 1.5 branch, but not for 1.4.x. I'll see about getting the package updated.

**Comment by vertecx** [comment]
I can confirm that the new Mosquitto installer for Windows, version 1.4.15a, works as expected and is linked against OpenSSL 1.0.

Thank you for fixing the issue! :thumbsup:

**Comment by ralight** [comment]
Thank you, and sorry for the delay getting it sorted.
