### ISSUE TITLE
ubuntu14.0 storage size of ‘wspoll’ isn’t known    

### ISSUE THREAD

**Issue by waytai** [eclipse/mosquitto#717]
loop.c:493:22: error: storage size of ‘wspoll’ isn’t known                                                  
    struct lws_pollfd wspoll;

**Comment by waytai** [comment]
mosquitto-1.4.15

**Comment by karlp** [comment]
you look like you've tried enabling websockets, but either don't have libwebsockets, or have a very incompatible version?

**Comment by Tifaifai** [comment]
I'm use libwebsocket 2.4.1, and lws_pollfd is ok.

https://libwebsockets.org/lws-api-doc-master/html/libwebsockets_8h_source.html

you can fix this problem after removing the existing libwebsockets library and compiling the latest version from the source.

**Comment by waytai** [comment]
@Tifaifai  thank you, and  I used newly libwebsocket from git , and now is all right.

**Comment by toast-uz** [comment]
Solved and close this issue?
