### ISSUE TITLE
Incorrect Conf (mqtt CA certificate problem) [Stretch - armhf]

### ISSUE THREAD

**Issue by Deiv70** [eclipse/mosquitto#718]
## My Enviroment:

_**#** **¡¡** I read the Documentation of Mossquitto from here: https://mosquitto.org/man/mosquitto-conf-5.html **!!** **#**_
+ My Repo is: [Stretch main](http://repo.mosquitto.org/debian/mosquitto-stretch.list)
      -> Installed on a RP3 [arch=armhf] which is running on 32-bit mode
      -> The Mosquitto Version is the repo lastest:
           ```mosquitto version 1.4.15 (build date Wed, 28 Feb 2018 11:29:47 +0000)```
           ```mosquitto is an MQTT v3.1.1/v3.1 broker.```

+ My .conf file is (spelling revised, thanks to @ralight):
```
#allow_anonymous true
allow_anonymous false
password_file /etc/mosquitto/passwd

listener 1883 127.0.0.1

listener 883
cafile /etc/mosquitto/certs/ca.cert
certfile /etc/mosquitto/certs/osmc.crt
keyfile /etc/mosquitto/certs/osmc.key
require_certificate false

listener 9883
protocol websockets
cafile /etc/mosquitto/certs/ca.cert
certfile /etc/mosquitto/certs/osmc.crt
keyfile /etc/mosquitto/certs/osmc.key
require_certificate false
```

_**#!** The comented lines are there becouse of the tests that I realised with the different options to check the program behavoir_

## **My problem is that I get:**
```
1520773293: mosquitto version 1.4.15 (build date Wed, 28 Feb 2018 11:29:47 +0000) starting
1520773293: Config loaded from /etc/mosquitto/conf.d/OpenHAB.conf.
1520773293: Opening ipv4 listen socket on port 1883.
1520773293: Opening ipv4 listen socket on port 883.
1520773293: Opening ipv6 listen socket on port 883.
1520773293: Error: Unable to load CA certificates. Check cafile "/etc/mosquitto/certs/ca.cert".
```

But I have a boubt, _mqtt_ protocol **gaves me problems with CA Certificate** while _websockets_ not.
Is it not suported by the _mqtt_ protocol??

**Comment by ralight** [comment]
Please check your spelling, you've used `require_cerfiticate` and it should be `require_certificate`.

**Comment by Deiv70** [comment]
Sorry, I edited it

**Comment by Deiv70** [comment]
Now my .con is:
```
#allow_anonymous true
allow_anonymous false
password_file /etc/mosquitto/passwd

listener 1883 127.0.0.1

listener 883
#cafile /etc/mosquitto/certs/ca.cert
#certfile /etc/mosquitto/certs/osmc.crt
#keyfile /etc/mosquitto/certs/osmc.key
require_certificate false

listener 9883
protocol websockets
cafile /etc/mosquitto/certs/ca.cert
certfile /etc/mosquitto/certs/osmc.crt
keyfile /etc/mosquitto/certs/osmc.key
require_certificate false
```

But I have a boubt, _mqtt_ protocol gaves me problems with CA Certificate while _websockets_ Not
Is it not suported by the protocol??
