### ISSUE TITLE
Rotating Timed Logging

### ISSUE THREAD

**Issue by vrst37** [eclipse/mosquitto#720]
Hello guys,
I would like to enable logging from mosquitto broker into a file and would like to create a new file every day, and delete all files older than x number of days automatically.

This feature is present in many applications and logging libraries.

Does mosquitto broker have a similar feature? If not, can we add it to the list of things to be implemented?

**Comment by ralight** [comment]
I don't think this is within the scope of mosquitto, there are already utilities which are designed specifically to handle this case - logrotate is a good example.

**Comment by Tifaifai** [comment]
Package logrotate : [Tutorial / Example](https://www.digitalocean.com/community/tutorials/how-to-manage-logfiles-with-logrotate-on-ubuntu-16-04)

**Comment by vrst37** [comment]
I agree with the comments.
