### ISSUE TITLE
running as root

### ISSUE THREAD

**Issue by sekyHC** [eclipse/mosquitto#724]
In config files it says:
```
# When run as root, drop privileges to this user and its primary
# group.
# Leave blank to stay as root, but this is not recommended.
# If run as a non-root user, this setting has no effect.
# Note that on Windows this has no effect and so mosquitto should
# be started by the user you wish it to run as.
# user mosquitto
```

If I run it as a root and this is still commented out, it will fallback to mosquitto user. It is running as root only when I explicitly tell him to use: user root

This is on version 1.4.12

**Comment by karlp** [comment]
blank is not the same as commented out, would be my understanding?

**Comment by ralight** [comment]
Like Karl says, your options for running as root are:

    user root

or

    user

**Comment by sekyHC** [comment]
If I do 
```
user root
```
it works fine, but if I do
```
user
```
I get following error:
```
# mosquitto -c /etc/mosquitto/mosquitto.conf 
Error: Empty user value in configuration.
Error found at /etc/mosquitto/mosquitto.conf:43.
Error: Unable to open configuration file.
```
this is why I opened issue

**Comment by ralight** [comment]
Thank you! I have updated the documentation.
