### ISSUE TITLE
Documentation for snap

### ISSUE THREAD

**Issue by eifinger** [eclipse/mosquitto#726]
Hi, I found out that there is a snap image for mosquitto "mosquitto-simple".
Installing it from the "edge" channel works, it started the broker and I can connect to it.

But how can I configure it? I couldn't find any information on it and any commands like "mosquitto-simple.mosquitto or mosquitto-simple.help" don't work.

Is there a documentation for the mosquitto-simple snap?

**Comment by ralight** [comment]
mosquitto-simple was just that - simple. No configuration possible. This has now been changed thanks to some input from Ubuntu, and there is a version which allows you to provide your own configuration files. When you run it you should get information on where to place the config file. If you do try it, could you give some feedback on your experience?

**Comment by eifinger** [comment]
Can you provide a link to this version you are referencing? I was not able to find it. Thank you!

**Comment by ralight** [comment]
Right, there is a whole new snap - just mosquitto, not mosquitto-simple. It is currently only available in the candidate channel, so you would do "snap install --candidate mosquitto".

This sets a version of mosquitto to run using configuration in $SNAP_COMMON, i.e. /var/snap/mosquitto/common - it expects a file mosquitto.conf to be present in that directory, or else just uses default configuration.

You can also run the mosquitto snap as a user, in which case the configuration needs to be in $SNAP_USER_COMMON, which is /home/<user>/snap/mosquitto/common

**Comment by eifinger** [comment]
Thank you very much!
I moved away from Ubuntu Core from the time being as I couldn't find enough documentation to really get ahead. But If I get the chance to use it again I will provide some feedback.
