### ISSUE TITLE
No data from $SYS/broker/heap/current and $SYS/broker/heap/maximum

### ISSUE THREAD

**Issue by bbrighttaer** [eclipse/mosquitto#727]
Hello,
pls, I am using mosquitto version 1.4.15 and I would want to keep track of the current and maximum heap records. I have tried subscribing to $SYS/broker/heap/maximum and $SYS/broker/heap/current but I do not get any data from the broker.
Any help on this?

**Comment by karlp** [comment]
can you get any $SYS/# topics?  are you perhaps jsut a victim of shell quoting?
```
mosquitto_sub -t '$SYS/#' -v
vs
mosquitto_sub -t "$SYS/#" -v
vs
mosquitto_sub -t $SYS/# -v
```
Only the first will work as "expected" the others will expand $SYS as a shell variable.

**Comment by lanker** [comment]
Make sure that your mosquitto is built with WITH_MEMORY_TRACKING enabled (and WITH_SYS_TREE, of course).

**Comment by ralight** [comment]
I'm going to close this issue because I think @karlp is probably correct. If you've still got a problem, please reopen the bug and provide some more details.
