### ISSUE TITLE
Error: Duplicate persistence_location

### ISSUE THREAD

**Issue by hav0ck** [eclipse/mosquitto#728]
So I was able to get Mosquitto up and running with no "major" issues really.
I initially setup my broker on port 1883, I'd like to have 1883 as the unsecure internal port, 8883 as the secure external port.

I setup my conf file to have the listener on 1883 and a second listener on 8883. However when I try to start Mosquitto I get the follow error message:

> Error: Duplicate persistence_location value in configuration.
> Error found at /etc/mosquitto/mosquitto.conf:26.
> Error: Unable to open configuration file.
 

My config looks like this:
```
pid_file /var/run/mosquitto.pid

listener 1883
persistence true
persistence_location /var/lib/mosquitto/
persistence_file mosquitto.db
log_dest file /var/log/mosquitto/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true
allow_anonymous false
password_file /etc/mosquitto/pwfile
acl_file /etc/mosquitto/aclfile.acl

listener 8883
persistence true
persistence_location /var/lib/mosquitto/
persistence_file secure-mosquitto.db
log_dest file /var/log/mosquitto/secure-mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true
allow_anonymous false
password_file /etc/mosquitto/pwfile
acl_file /etc/mosquitto/aclfile.acl
certfile /etc/letsencrypt/live/home.FQDN/cert.pem
cafile /etc/letsencrypt/live/home.FQDN/chain.pem
keyfile /etc/letsencrypt/live/home.FQDN/privkey.pem
```

**Comment by Tifaifai** [comment]
Hi,
You have the same problem with log_type and log_dest for example ...
This parameter is unique and global for your mosquitto server.
You can read : 
Global :
https://github.com/eclipse/mosquitto/blob/4f838e51611b9a71f2e3e98e6fddd02a5c1b4c03/src/mosquitto_broker.h#L103
Different Listener :
https://github.com/eclipse/mosquitto/blob/4f838e51611b9a71f2e3e98e6fddd02a5c1b4c03/src/mosquitto_broker.h#L72

Maybe rewrite this part for your case ;) but it's interessting for different log for example ;)

C-U

**Comment by hav0ck** [comment]
So there can only be one Persistence and one log file for a broken despite having multiple listeners?

Would this be a better config format then?
```
pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/
persistence_file mosquitto.db
log_dest file /var/log/mosquitto/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true
allow_anonymous false
password_file /etc/mosquitto/pwfile
acl_file /etc/mosquitto/aclfile.acl

#Internal Listener
listener 1883

#External Listener
listener 8883
certfile /etc/letsencrypt/live/home.FQDN/cert.pem
cafile /etc/letsencrypt/live/home.FQDN/chain.pem
keyfile /etc/letsencrypt/live/home.FQDN/privkey.pem
```

**Comment by Tifaifai** [comment]
Exactly, one persistence/log/etc. 
Normally, your file config is OK but you can testing your config ;)

**Comment by Tifaifai** [comment]
Close ?
