### ISSUE TITLE
CONNACK received after sending CONNECT with invalid client id

### ISSUE THREAD

**Issue by uboscolo** [eclipse/mosquitto#732]
I am using mosquitto broker 1.4.15 on ubuntu 16.04.
[invalid_username.pcapng.gz](https://github.com/eclipse/mosquitto/files/1826647/invalid_username.pcapng.gz)

/usr/sbin/mosquitto -h
mosquitto version 1.4.15 (build date Wed, 28 Feb 2018 11:29:47 +0000)

mosquitto is an MQTT v3.1.1/v3.1 broker.

I am using mqtt paho python client to connect to the broker and send a CONNECT message with

invalid user name == 0x010001

Based on http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf

[MQTT-3.1.3-4]
The ClientId MUST be a UTF-8 encoded string as defined in Section 1.5.3.

[MQTT-1.5.3-2]
A UTF-8 encoded string MUST NOT include an encoding of the null character U+0000. If a receiver (Server or Client) receives a Control Packet containing U+0000 it MUST close the Network Connection.

Please let me know your comments.
I have attached a wireshark trace for reference

**Comment by toast-uz** [comment]
Thank you very much for your many contributions. Because of a lot of changes on develop branch, I appreciate if you can test each of your proposed issues not only on master branch but also on develop branch.
