### ISSUE TITLE
SSL3_GET_SERVER_CERTIFICATE:certificate verify failed;SSL3_GET_RECORD:wrong version number

### ISSUE THREAD

**Issue by systemzsz** [eclipse/mosquitto#734]
**Hello, I had met a problem about using bridge with ssl. 
mosquttio.conf as:**

port 1984
cafile  /home/itouchtv/mosquitto-1.4.14/myCA/ca.crt
certfile /home/itouchtv/mosquitto-1.4.14/myCA/server.crt
keyfile /home/itouchtv/mosquitto-1.4.14/myCA/server.key
tls_version tlsv1
require_certificate false
use_identity_as_username false

connection itouchtvMqtt16.6
address im16.itouchtv.cn:1984
topic itouchtv/# both 1 "" ""

bridge_attempt_unsubscribe true
remote_clientid backup_clientid
local_clientid master_clientid
cleansession true
remote_username admin
remote_password password
bridge_cafile /home/itouchtv/mosquitto-1.4.14/myCA/ca.crt
bridge_certfile /home/itouchtv/mosquitto-1.4.14/myCA/client.crt
bridge_keyfile /home/itouchtv/mosquitto-1.4.14/myCA/client.key

**And there are errors:**

1521017807: OpenSSL Error: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version
1521017807: OpenSSL Error: error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure
1521017807: Socket error on client <unknown>, disconnecting.

1521515309: Bridge master_clientid doing local SUBSCRIBE on topic itouchtv/#
1521515309: Connecting bridge itouchtvMqtt16.6 (im16.itouchtv.cn:1984)
1521515309: Bridge backup_clientid sending CONNECT
1521515309: OpenSSL Error: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
1521515309: Socket error on client master_clientid, disconnecting.

1521515938: New connection from 172.18.16.6 on port 1984.
1521515938: OpenSSL Error: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
1521515938: Socket error on client <unknown>, disconnecting.

**FireWall Status:**
iptables: Firewall is not running.

**I need some help, thank you very much.**

**Comment by toast-uz** [comment]
To resolve bridge issues, you should show mosquitto.conf and error logs of BOTH of bridge client and server. Maybe you are forcing tlsv1 on bridge server and use tlsv1.1 (default) on bridge client.

**Comment by systemzsz** [comment]
I use the certificate which signed byWoTrus Company, but there are some error, can you help me solve them?

port 1984
cafile /home/itouchtv/mosquitto-1.4.14/myCA/ca.crt
certfile /home/itouchtv/mosquitto-1.4.14/myCA/server.crt
keyfile /home/itouchtv/mosquitto-1.4.14/myCA/server.key
require_certificate false

mosquitto_sub -p 1984 -t \$SYS/broker/bytes/\# -v --cafile /usr/local/mosquitto-1.4.14/myCA/ca.crt

ERROR LOG:
1521787287: OpenSSL Error: error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown
1521787287: OpenSSL Error: error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure

**Comment by toast-uz** [comment]
Could you give me the latest status or shall I close this issue?
