### ISSUE TITLE
mosquitto_sub doesn't work in non-network setup

### ISSUE THREAD

**Issue by lategoodbye** [eclipse/mosquitto#736]
Hi, i'm want to use mosquitto on a Embedded device (Debian Stretch armhf) without a network interface / connection. The mosquitto broker is listing on loopback interface. As long as my development system (mosquitto v1.4.10) has a IP address mosquitto_sub / mosquitto_connect() works as expected. But if the system doesn't have a IP address (e.g. DHCP configured and not connected), i will get this error:

```
mosquitto_sub -t '#'
Unable to connect (Lookup error.).
```

I expect that mosquitto_sub connects to the loopback address regardless there is a IP address available or not.

Since v1.4.10 is rather old, i also tried 1.4.15 but it shows the same behavior.

There is nothing special about my mosquitto.conf:
```
# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log
include_dir /etc/mosquitto/conf.d
```

**Comment by ralight** [comment]
"Lookup error" sounds more like a host name / DNS issue to me. The default behaviour is to connect to `localhost`, is this host name configured? Does `ping localhost` work?

**Comment by lategoodbye** [comment]
Here is the output in case the issue is reproducible:

```
root@mydevice:/etc# cat /etc/hosts
127.0.0.1       localhost
127.0.1.1       mydevice

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

root@mydevice:/etc# cat /etc/hostname
mydevice

root@mydevice:~# ping 127.0.0.1
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.345 ms
...

root@mydevice:~# ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.201 ms
...

root@mydevice:~# netstat -l | grep 1883
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN
tcp6       0      0 [::]:1883               [::]:*                  LISTEN
```

**Comment by ralight** [comment]
I'm not really sure what else to suggest. It doesn't really do anything special with the network.

**Comment by lategoodbye** [comment]
Since #869 has been fixed, we can close this.
