### ISSUE TITLE
MQTT Broker repeatedly sends retained messages?

### ISSUE THREAD

**Issue by Diamundo** [eclipse/mosquitto#739]
Hi All,

I'm not sure if this is the right location, but here's the problem:
- I'm using Node.js with [MQTT.js](https://github.com/mqttjs/MQTT.js)
- I've connected to ```mqtt://m2m.eclipse.org```
- I've set two retained messages at _"one/test"_ and _"two/test"_
- With the Nodejs client, I've subbed to _"one/#"_ and _"two/#"_
- Every 30min 40s I receive the retained messages again.

I've already posted this issue over at [the MQTT.js github #795](https://github.com/mqttjs/MQTT.js/issues/795), but perhaps it's more a broker-problem than an MQTT.js problem.

**Comment by karlp** [comment]
does your client ever see a disconnect/reconnect to m2m.eclipse.org?

**Comment by ralight** [comment]
It's possible that m2m.eclipse.org has some network configuration that restricts network sessions to 30 minutes. If this is the case, you will disconnect and reconnect and when you resubscribe the retained messages will be resent. They will always be sent when a subscription is requested, but not in any other situation.

**Comment by Diamundo** [comment]
@ralight this could very well be the case, however (as stated at [the mqtt.js issue](mqttjs/MQTT.js/issues/795)) I went 2h10m without receiving the retained messages this afternoon. Then I received them, then 30m49s later again, and now it's been 43 minutes without messages again (haven't received any yet since 14:50, 43 min ago)... 

I think the right location to ask that question isn't at this repository? Where would be the right location to ask?

**Comment by ralight** [comment]
I'm not sure what you're trying to achieve really. Your application should be able to cope with repeat transmission of retained messages.

**Comment by Diamundo** [comment]
@ralight you're completely right. Without a doubt!
However, what I don't understand is why I'm repeatedly (at almost exactly 30m40s intervals) getting the messages again, it almost seems like a problem with the broker. I've decided to switch back to a different broker which I tested briefly and which didn't have what I call a problem. Thanks for your help!
