### ISSUE TITLE
Mosquitto > 1.4.10 from http://mosquitto.org/2013/01/mosquitto-debian-repository/ not working on Pi Zero W (ARM6)

### ISSUE THREAD

**Issue by bouwew** [eclipse/mosquitto#740]
I just installed Mosquitto 1.4.15 onto my Pi Zero W via http://mosquitto.org/2013/01/mosquitto-debian-repository/
After starting it manually, I receive an error: segmentation fault.

After a search I found out that the latest working version is 1.4.10, and indeed, this version works.
But, apparently, all versions after 1.4.10 are broken for ARM6.

A fix would be very much appreciated.

**Comment by ralight** [comment]
This should be fixed now, please give it a try and reopen the bug if you still have problems.
