### ISSUE TITLE
Mosquitto.conf installed as mosquitto.conf.example on unix platforms

### ISSUE THREAD

**Issue by nicola-lunghi** [eclipse/mosquitto#742]
Here the install copy **mosquitto.conf.example**
https://github.com/eclipse/mosquitto/blob/2097ab0aceb6289576729e84fa8b59eb502b8ef8/Makefile#L43

but here the uninstall remove **mosquitto.conf**

https://github.com/eclipse/mosquitto/blob/2097ab0aceb6289576729e84fa8b59eb502b8ef8/Makefile#L50

On CMakeLists.txt the file installed is **mosquitto.conf**
https://github.com/eclipse/mosquitto/blob/2097ab0aceb6289576729e84fa8b59eb502b8ef8/CMakeLists.txt#L95

**Comment by ralight** [comment]
Thank you, I've changed the uninstall target for the makefile.
