### ISSUE TITLE
Mosquitto config option to force MQTT version

### ISSUE THREAD

**Issue by vrst37** [eclipse/mosquitto#743]
I think an option to force MQTT protocol version would be nice to implement in the config file.

**Comment by karlp** [comment]
For what motivation?  there's already a protocol option for each listener?

**Comment by vrst37** [comment]
Yes but the protocol can only be MQTT or Websockets. How can we use that variable to force mosquito broker to accept only specified MQTT protocol version?

**Comment by karlp** [comment]
yes, but why would you want to?  It's one thing to specify a protocol to use when connecting as a client (in the client library and in bridge config) to support remote brokers that only support specific protocols, but as a broker, why would you ever want to restrict this?

**Comment by ralight** [comment]
Sorry, but I agree with @karlp here. It is intended that all listeners support all versions of the MQTT protocol that mosquitto supports.
