### ISSUE TITLE
Prevent Subscribe to #

### ISSUE THREAD

**Issue by iambudi** [eclipse/mosquitto#744]
I've tried both using pattern and using topic to allow authenticated user to subscribe to certain topic, but client can still subscribe and receive data using #. Is this expected behaviour or can it be turned off?

```
# when using pattern
pattern read weather/hourly/%u

# when using topic
user android 
topic read weather/hourly/+
```
mosquitto_sub can still subscribe and receive by subscribing to weather/#. I want client to only subscribe to complete topic weather/hourly/android

mosquitto version 1.4.14 (build date 2017-10-22 16:34:39+0100) OSX High Sierra

**Comment by ralight** [comment]
The ACL configuration at the moment does not prevent subscription, it only prevents messages being delivered on that subscription. What you should see is that a subscription to '#' will succeed, but only messages sent to weather/hourly/username are received. Is this the case?

**Comment by ralight** [comment]
It's possible to restrict access to `#` using the dynamic security plugin, so I'm closing this issue.
