### ISSUE TITLE
No file : auth_plugin_pwd.c / auth_plugin_acl.c

### ISSUE THREAD

**Issue by Tifaifai** [eclipse/mosquitto#748]
No files (auth_plugin_pwd.c and  auth_plugin_acl.c) then break down the Travis CI process : 
 
https://github.com/eclipse/mosquitto/blob/3121d38c9171830ddf256073a131763c6dd2efcd/test/broker/c/Makefile#L12

https://github.com/eclipse/mosquitto/blob/3121d38c9171830ddf256073a131763c6dd2efcd/test/broker/c/Makefile#L15

THX

**Comment by ralight** [comment]
Thanks, I'd missed adding them on my local copy.
