### ISSUE TITLE
Websocket connection not working in Docker image 

### ISSUE THREAD

**Issue by dersimn** [eclipse/mosquitto#754]
You're using the default `mosquitto.conf` from alpine which is not enabling web-socket connections, however your readme files suggest that web-sockets are available (`-p 9001:9001`).

**Comment by dersimn** [comment]
This issue is regarding the current readme on Docker Hub: https://hub.docker.com/_/eclipse-mosquitto/

**Comment by ralight** [comment]
This is fixed and awaiting review: https://github.com/docker-library/official-images/pull/4987

**Comment by ralight** [comment]
It is now in the official image, thanks for reporting it.
