### ISSUE TITLE
Mosquitto 1.4.15 on Linux Mint does not have websockets support

### ISSUE THREAD

**Issue by dkurzaj** [eclipse/mosquitto#755]
I have added the Websocket support by creating the file /etc/mosquitto/conf.d/websocket.conf and putting inside it the following lines:
```
listener 1883
listener 1884
protocol websockets
```
Then restarted the mosquitto server:
```
$ sudo service mosquitto restart
```
And tried to reload the configuration, but faced those errors:
```
$ sudo mosquitto -v -c /etc/mosquitto/mosquitto.conf
Error: Websockets support not available.
Error found at /etc/mosquitto/conf.d/websocket.conf:3.
Error found at /etc/mosquitto/mosquitto.conf:13.
```
I'm wondering if it's related to: #708.
I'm on Linux Mint 18.3 and use the Debian Wheezy Mosquitto repo : `deb http://repo.mosquitto.org/debian wheezy main`

**Comment by ralight** [comment]
Debian Wheezy doesn't have libwebsockets so it is not possible to provide websockets support for it I'm afraid.

**Comment by dkurzaj** [comment]
Oh ok, thank you for the information! And sorry for the false issue then…
