### ISSUE TITLE
A bridge waits for restart timeout to connect to broker when using ADNS

### ISSUE THREAD

**Issue by lwindg** [eclipse/mosquitto#756]
When using ADNS, the first time to check status is **always** `EAI_INPROGRESS` (from my test); that cause the bridge spends at least "**restart timeout**" (default 30 seconds) to connect to the broker.

I found `restart_t` is set to `1` for quick restart ([bridge.c#L135](https://github.com/eclipse/mosquitto/blob/master/src/bridge.c#L135)), but it seems not enough. 

Maybe it should allow more time for DNS lookup.

**Comment by ralight** [comment]
I think this has been fixed in 1.5.3 and the upcoming 1.5.4. I'm going to close this, if it's still an issue please reopen.
