### ISSUE TITLE
Can't connect to mosquitto broker

### ISSUE THREAD

**Issue by djmauro** [eclipse/mosquitto#760]
I'm running in ubuntu VM.  My client is written in Ruby.  I m using the ruby-mqtt client gem.  

When I attempt to connect to the broker on localhost:1883 I get the following error message:

  ` MQTT::Client.connect: Failed to read byte from socket  (host:port = 192.168.0.161:1883)`

I understand that this means that the broker has closed the connection.  Not sure why.  If I connect not to localhost but to test.mosquitto.org, for example, it works.  This indicates that the client ruby software works.  If I use mosquitto_sub/pub to the localhost broker, it works, which indicates that the mosquitto broker is working.  It is just the combination of my client and the localhost broker that has issues.  Must be something painfully obvious, but I'm missing it.

**Comment by toast-uz** [comment]
The error message seems produced by ruby-mqtt. Could you show the mosquitto-broker's logs?

**Comment by djmauro** [comment]
The log reads as follows when issuing MQTT::Client.connect('localhost', 1883):

```
Apr  2 06:53:07 local mosquitto[2171]: New connection from 127.0.0.1.
Apr  2 06:53:07 local mosquitto[2171]: Invalid protocol "MQTT" in CONNECT from 127.0.0.1.
Apr  2 06:53:07 local mosquitto[2171]: Socket read error on client (null), disconnecting.
```

**Comment by toast-uz** [comment]
What is the version of mosquitto-broker?

**Comment by djmauro** [comment]
I was trying to find that out. There is no 'mosquitto --version' command. I just tried 

apt-cache policy mosquitto


and got:
 
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 9.0px 'Lucida Console'}  

 
mosquitto:
 
 Installed: 0.15-2ubuntu1.2
 
 Candidate: 0.15-2ubuntu1.2
 
 Version table:
 
 *** 0.15-2ubuntu1.2 0
 
 500 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe amd64 Packages
 
 100 /var/lib/dpkg/status
 
 0.15-2ubuntu1 0
 
 500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages

Also, I recently did an 'apt-get install mosquitto' so I should have the latest.
Thanks.

**Comment by djmauro** [comment]
While some mystery remains I seem to have figured it out - many thanks to toast-uz for pushing me in the right direction.  

Turns out there were two problems.  
1. The first was the MQTT protocol version.  The latest version of ruby-mqtt api sets it to the latest, 3.1.1, by default.  I must have an early version of the mosquitto broker (even though I did an 'apt-get install mosquitto' ) because it seems to be rejecting the connection attempt based on this version.  Setting it to the older version, 3.1, makes things work.  
2. Getting past the first problem I was still getting a connect failure.  This was because my application registers many connection on behalf of different front-end clients.  So the first connect attempt would succeed.  However, if you don't set the client_id field in the connect request then the broker will close that connection when it receives the next connect request (because the (empty) id is effectively the same).  Does anyone know if this still an issue with 3.1.1?
Thanks again.

**Comment by toast-uz** [comment]
Definitely "Invalid protocol "MQTT" in CONNECT from 127.0.0.1" means refusing unsupported version 3.1.1 by the broker. Therefore, I guess your broker is old. You can find the version message in the mosquitto.log on restarting the broker. Also you can find the instruction of installing the latest version on Ubuntu at https://mosquitto.org/download/ .

**Comment by djmauro** [comment]
Yep, that must be the problem.  Even though I re-downloaded the mosquitto broker the version remained at 0.15, which I believe is from June of last year.  I'll check out your link to find out how to force an update.  Thanks for your help, toast-uz.

**Comment by karlp** [comment]
no, 0.15 is from _years_ ago.  You definitely don't want to be using it.

Your issue number 2, reconnecting with the same client id, is per MQTT spec, so it's a "bug" in your application design, not something in the broker or the client libraries.

**Comment by djmauro** [comment]
Ya, I don't know how that happened - I have the latest version now.  The "bug" was just me not understanding how the mosquitto connection management worked.  I now add a unique client id for each individual connection to the broker.  Seems to work well.  
Thanks all for weighing in on this issue!
