### ISSUE TITLE
Doesn't it support websocket on Windows?

### ISSUE THREAD

**Issue by DayTimeDreamer** [eclipse/mosquitto#762]
Doesn't it support websocket on Windows? We want develop a chat app base on mosquitto.

**Comment by karlp** [comment]
Sure, but I don't think the precompiled binaries include libwebsockets.  But you can totally do that yourself.

**Comment by ralight** [comment]
That's correct, we don't provide websockets enabled binaries for Windows, but there is nothing stopping you doing that.
