### ISSUE TITLE
Publish actual version to docker hub

### ISSUE THREAD

**Issue by nixikanius** [eclipse/mosquitto#763]
As I see in [releases page](https://github.com/eclipse/mosquitto/releases) current actual version of the mosquitto is **1.4.15**. But the latest published version of the mosquitto at [docker hub](https://hub.docker.com/r/library/eclipse-mosquitto/tags/) is **1.4.12**, which is almost 1 year old.

I have one problem with persistence functionality and want to check the mosquitto at last version using docker. Please push the actual version of the mosquitto to docker hub.

Thanks.

**Comment by chriswue** [comment]
Looks like 1.5 should be on there soon as well: https://github.com/docker-library/official-images/pull/4987

**Comment by ralight** [comment]
1.5.3 is indeed now on the official image and should be kept up to date now, so I'm closing this.
