### ISSUE TITLE
hang when starting mosquitto on Pi

### ISSUE THREAD

**Issue by andysc** [eclipse/mosquitto#773]
This was all working find until a few days ago.

On a Pi 3 running Raspbian Jessie...

Now, I can't start mosquitto with the config file.
```sudo mosquitto -v -c /etc/mosquitto/mosquitto.conf```
just hangs with no console output at all.
It creates a listener on 1883, but doesn't accept connections on it.
ctrl-c doesn't kill it - have to use ctrl-\

config file: 
```
# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d
```
nothing (ending in .conf) in conf.d
plenty of space in root file system (in which /var lives)

```mosquitto version 1.3.4 (build date 2014-08-22 06:10:51+0000) ```

If I don't specify a conf file and just start mosquitto, it works fine.

**Comment by karlp** [comment]
is the persistence file very big? it can take a long time to load, and it appears to do nothing while doing so.  This was particularly noticeable with older mosquittos, which you are very certainly using :)

**Comment by ralight** [comment]
Karl is right - there were big improvements in loading persistence files in 1.4.

**Comment by andysc** [comment]
it wasn’t very big (about 11k, ISTR), but I deleted it anyway to see if it helped - it didn’t.

I can try commenting out lines one by one from the config file until it improves - that would be a good exploration, wouldn’t it.

Andy

**Comment by ralight** [comment]
Ok, no 11k should be instantaneous so I can't imagine it is that. We were thinking more like x00MB.

My next guess would be if you've got a bridge then a DNS lookup might be blocking? Something else that is solved in later versions :)

**Comment by ralight** [comment]
Correct, only .conf files are used.

Maybe strace would give some hints about what is happening?

**Comment by andysc** [comment]
I’ll do some more experiments … thanks

**Comment by andysc** [comment]
ok, well, in the end, I deleted all the log files in /var/log/mosquitto, and it seems to work now.

I think part of what set me on the wrong track was the log_dest file statement, which (I now realise) stops it printing to stdout as well.

It definitely *wasn’t* working, as I couldn’t connect to it over 1883, but later, my investigations may have been misguided due to that lack of console output.

All working fine, now, though, so thanks for your help, and sorry for slightly wasting your time ;)

Andy

**Comment by ralight** [comment]
Well ok, I'm glad it's working even if we don't know what the problem was.
