### ISSUE TITLE
mosquitto_publish mid  invalid

### ISSUE THREAD

**Issue by gongyb** [eclipse/mosquitto#774]
`

libmosq_EXPORT int mosquitto_publish( | struct | mosquitto | * | mosq,
-- | -- | -- | -- | --
  |   | int | * | mid,
  | const | char | * | topic,
  |   | int |   | payloadlen,
  | const | void | * | payload,
  |   | int |   | qos,
  |   | bool |   | retain | )

I publish a message use particular mid, but on_publish callback mid is wrong. 
`

void |   | (*on_publish)(struct mosquitto *, void *, int)
-- | -- | --

`

I view the source code found
>    local_mid = _mosquitto_mid_generate(mosq);
    if(mid){
            *mid = local_mid;  //line 577
    }

I think line 577 should be modified to
`local_mid = *mid;`

After the revision, retest and found that everything is normal.

**Comment by gongyb** [comment]
My special MID is an int number, like 999, but in on_publish callback, the mid value is 1.  on_publish callback MID shouldn't be 999?

>int mid_sent=999;
mosquitto_publish(mosq, &mid_sent, topic, msglen, message, qos, retain);

>void on_publish_callback(struct mosquitto *mosq, void *obj, int mid){
	//print mid=1, shouldn't be mid=999?
}

**Comment by karlp** [comment]
no.  you _cannot_ specify the mid to publish.  mid_sent is an OUTPUT parameter, it is written by the library, so you can correlate in the  on_publish callback.
```C
int mid_sent;
mosquitto_publish(mosq, &mid_sent, topic, len, msg, qos, retain);
printf("we published with mid: %d\n", mid_sent);
....
on_publish_callback(mosq, obj, mid) {
   printf("mid %d has completed publishing\n", mid);
}
```

**Comment by gongyb** [comment]
Okay, I understand now, thanks！
