### ISSUE TITLE
mosquitto_sub sends password in plaintext over what should be mqtts connection

### ISSUE THREAD

**Issue by johnbcoughlin** [eclipse/mosquitto#776]
We are trying to use mosquitto_sub to connect to a MQTT broker over mqtts/8883, and seeing the client just hang with no output. In the process of investigating, we came across the following oddity, which is both alarming and I hope can help shed some light on the situation.

Steps to reproduce:

1. Start capturing packets:
```
sudo tcpdump -i eth0 -s 65535 -w /tmp/packet-dump
```

2. Attempt to connect to an MQTT broker:
```
mosquitto_sub -h broker-sandbox.everyware-cloud.com -p 8883 -v -t '#' -u i-dont-exist -P whatever --tls-version tlsv1.2
```

3. Open the packet dump in Wireshark. There is a packet with protocol "SSL" and info "Continuation Data", which contains the username and password, unencrypted:

<img width="175" alt="screen shot 2018-04-10 at 3 03 26 pm" src="https://user-images.githubusercontent.com/2209490/38585892-67b45592-3cd0-11e8-9380-cfdd54861344.png">

Version info and notes:
- Mosquitto 1.4.15
- Ubuntu 16.04

Thank you for any help or insight you can provide.

**Comment by ralight** [comment]
The reason this is happening is because you need to use `--cafile` or `--capath` to enable TLS connections. This is already mentioned in the client documentation, but I have just pushed a commit that makes it much more prominent: ba3b41ef6090ed1094655b6cf97c9e477d86b973

**Comment by ralight** [comment]
I'm closing this issue, if you think it's still a problem please reopen and add some more details.
