### ISSUE TITLE
Mosquitto wont start - error: invalid user 'mosquitto'.

### ISSUE THREAD

**Issue by dastrix80** [eclipse/mosquitto#777]
Edit: fixed

**Comment by Tifaifai** [comment]
close !

**Comment by ralight** [comment]
For completeness, the answer is `user root`, not `username root`.

**Comment by rohitsay89** [comment]
I am facing the same error on a beaglebone black trying to run the mosquitto server.
1527086891: mosquitto version 1.5 starting
1527086891: Config loaded from mosquitto.conf.
1527086891: Opening ipv4 listen socket on port 1883.
1527086891: Opening ipv6 listen socket on port 1883.
1527086891: Error: Invalid user 'mosquitto'.

Can you please clarify where should I put the user and username parameters. Is it using the default config file and is '/etc/mosquitto/mosquitto.conf' correct location for that ?
