### ISSUE TITLE
MQTT tls-psk setup

### ISSUE THREAD

**Issue by adriamas** [eclipse/mosquitto#778]
I'm trying to setup MQTT with tls-psk.
MQTT works fine without it, but I want to add some security.

I added the following two entries to my config file:
psk_hint myhint
psk_file /etc/mosquitto/pskfile

In /etc/mosquitto/pskfile i wrote the following row
testID:abcdef

And then started the server successfully, and tried to connect with
mosquitto_sub --psk-identity testID --psk abcdef -h {my ip} -p 8881 -t testTopic
getting the following error: "Unable to connect (A TLS error occurred)".
The server sees an incoming connection, and then "Socket error on client <unknown>, disconnecting".

I noticed that trying to subscribe to a topic without the flags --psk-identity and --psk works...
Am i configuring my server wrong?

**Comment by ralight** [comment]
Did you make sure the psk configuration options come after the listener definition?

I just tested this config and it worked fine:
```
port 8881
psk_hint myhint
psk_file pskfile
```

**Comment by adriamas** [comment]
That's the problem. I didn't understand they had to be put right after the listener
Thanks
