### ISSUE TITLE
Having problems connecting with test.mosquitto.org

### ISSUE THREAD

**Issue by inventvictor** [eclipse/mosquitto#789]
Thank you in advance.

I have been trying to connect to the broker from my PC and also from a piece of embedded device but to no avail...It does not connect at all.

 I have ascertained that its not a network issue rather an issue from the broker.

Love to hear from you soon.

Victor.

**Comment by ralight** [comment]
Sorry about that - I've been trying to track down a very rare bug which I've just caught and so the broker was down for that reason. It seems the bug is in an external component, so sorry for the inconvenience.
