### ISSUE TITLE
Logging: Sending of SUBACK is logged but UNSUBACK is not logged

### ISSUE THREAD

**Issue by barrierbank** [eclipse/mosquitto#790]
In mqtt3_handle_unsubscribe, the sending of UNSUBACK is not logged.

mqtt3_handle_subscribe calls _mosquitto_send_suback which logs that the SUBACK is being sent, but mqtt3_handle_unsubscribe calls _mosquitto_send_command_with_mid which doesn't log anything.

This can cause confusion during debugging because it can make the reader of the log file think that UNSUBACK is not being sent.

**Comment by toast-uz** [comment]
I agree with you. Only UNSUBACK is not logged, right?

**Comment by barrierbank** [comment]
As far as I know this only affects UNSUBACK.

**Comment by toast-uz** [comment]
Could you submit a new PR of this issue. I'd like to close this as a new feature request. Regarding https://mosquitto.org/ , this place is for reporting bugs. I will wait for submitting the new PR.

**Comment by toast-uz** [comment]
Thanks @ckrey . Closing.
