### ISSUE TITLE
mosquitto -d inside docker wont start

### ISSUE THREAD

**Issue by hochmayrfa** [eclipse/mosquitto#792]
I'm trying to create a docker image based on openjdk:alpine, and I need to run mosquitto in background. 
**mosquitto -d** or  **mosquitto --daemon** wont start the process.

My Dockerfile :
```
FROM openjdk:alpine
RUN apk add --update mosquitto
RUN mosquitto -d
EXPOSE  1883 9001

#Other Actions
...
```

Without the -d it works well but I don't want my terminal to be blocked because I have to do other actions. 
Any clue ?

**Comment by Assar63** [comment]
Due to docker constraints this will not be possible.
Please read docker manual.

**Comment by hvanmegen** [comment]
Does it have a log directory available at /var/log/mosquitto? This is what kept my mosquitto from starting on my Raspberry Pi when I remounted my /var/log/ to tmpfs upon rebooting; I had to manually create the folder with write access for user 'mosquittto' in order for the service to be able to start.

**Comment by Assar63** [comment]
A docker container is supposed to run a single application. The init process is intentionally left out.
To run a process in background in a docker container will serve *no* purpose.
A mosquitto container should run mosquitto and mosquitto allone. other mqtt utilizing applications should have their own containers.
