### ISSUE TITLE
Documentation to write plugins?

### ISSUE THREAD

**Issue by nowox** [eclipse/mosquitto#794]
I would like to write a plugin for mosquitto that can translate topics from an architectural form to a semantic one. By looking at the API I saw this function `mosquitto_subscribe_callback_set` which looks like what I am looking for. On the subscribe event, the broker trig my callback that translate the topic name for another one. 

Next is how to write a plugin. The only example I have found is [mosquitto-auth-plug](https://github.com/jpmens/mosquitto-auth-plug) which does not use such callbacks. 

Is there any documentation, examples, clues to help me write this plugin?

**Comment by Tifaifai** [comment]
Maybe write on mosquitto-dev mailing list (http://dev.eclipse.org/mhonarc/lists/mosquitto-dev/maillist.html) for this question. ;)

**Comment by nowox** [comment]
Thanks for your answer. I think I'll fork mosquitto and implerment some kind of hooks as it is offered in hivemq.

**Comment by toast-uz** [comment]
@nowox could you close this issue?
