### ISSUE TITLE
ACL for subscriptions are disabled globally

### ISSUE THREAD

**Issue by drahnr** [eclipse/mosquitto#795]
Instead of disabling ACL checks for the default security plugin, all auth plugins can not filter subscriptions.

**Comment by drahnr** [comment]
master `src/read_handle_server.c` line 702, the `#ifdef 0` contains elaboration why it was disabled.

The issue is, while it is true for the default plugin, the subscription ACLs are thus _Never_ neforeced, no matter which plugin.

**Comment by ralight** [comment]
You'll be happy to hear that version 1.5 does pass acl subscription checks to the authentication plugins.

**Comment by drahnr** [comment]
@ralight how about a fix for 1.4.15? Is this going to happen anytime soon or am I going to stick with a custom patched instances?

**Comment by ckrey** [comment]
I think this can be closed as answered (in 2018)
