### ISSUE TITLE
mosquitto listens on all interfaces by default

### ISSUE THREAD

**Issue by jasperla** [eclipse/mosquitto#797]
The default configuration for mosquitto doesn't bind to a particular address and therefore listens on all available interfaces. This introduces a risk as many setups (as evidenced by Shodan) don't appear to configure the `bind_address` and allow anyone to subscribe to any topic.

Perhaps it would be better to bind to `localhost` by default or adjust the default configuration to have the same effect.

**Comment by karlp** [comment]
perhaps it would be better for people to read manuals?  this isn't a service that is installed without knowledge.

**Comment by ralight** [comment]
Let's keep the grump down a bit Karl.

I'm in two minds about this. In contrast to something like mysql where there is a real possibility that nothing outside of localhost will need to connect, a broker only listening on localhost isn't really much use. Changing the setting would break just about every single installation as well.

On the other hand, I do very much agree with the idea of minimising exposure.

**Comment by jasperla** [comment]
Roger, I'm well aware that adjusting the default in code will break all existing setups. Perhaps that's why adjusting the configuration file explicitly to `bind_address 127.0.0.1` would make it clear to users why and it's easy enough for them to adjust the configuration to match their setup.

**Comment by gdt** [comment]
Do we have an idea of the fraction of thoughtfully-configured installs that want to listen on the network, vs listening only on localhost?   I am generally a don't-listen-by-default type for things that are often local (databases), but it seems the point of an MQTT broker is usually (overwhelmingly usually?) to be accessible to wherever the publishers and subscribers are.

**Comment by ptjm** [comment]
You might want to consider the approach taken by redis, where this issue had to be addressed but the principle author had similar concerns. By default, redis listens on all interfaces, but only accepts commands from unix sockets or the IP loopback interfaces.  A client which attempts to send a command through the network interface gets a surprisingly detailed error message explaining how to configure the application to avoid that problem. The MQTT version of that might be to return status code 3 in the CONNACK and emit an error message on the server side.

I think the objective of this change would be to protect people who are just trying mosquitto out, and, say, running it without a config file on an inadequately firewalled dev machine or in a termux session on their phone. In redis, the restricted behaviour is turned off if you explicitly turn it off or configure the listen addresses. In mosquitto, if you only put the restricted behaviour in place for instances running without a config file, and add a command-line option to disable it for people who run in production without a config, you probably won't have many issues with broken installations, while still protecting naive new users.

**Comment by toast-uz** [comment]
I guess we should not compare mosquitto and databases like Redis. Because, databases are used locally, therefore, they must deny the anonymous accesses from the internet by default. Mosquitto should compare with web-servers rather than databases. Regarding Apache httpd serverr, it permits all accesses from the internet by default. Recently, the default access controls are provided by OS level or IaaS like AWS EC2 security group. Therefore, I think mosquitto should be as it is.

**Comment by Michael-hub-3** [comment]
I believe since version 2.0 and onward mosquitto listens only on the loopback interface if no configuration file is specified. So I think this issue can be closed if I am not mistaken?

**Comment by ralight** [comment]
Yes! Thanks for spotting it.
