### ISSUE TITLE
DNS lookup requests in bridge (client) mode  are completely blocking main event processing if DNS not responding

### ISSUE THREAD

**Issue by anklimov** [eclipse/mosquitto#802]
DNS lookup requests in bridge (client) mode  are completely blocking main event processing if DNS not responding
From mosquitto.log:
```
1524728542: Connecting bridge pi2cloudmqtt (m23.cloudmqtt.com:nnnnn)
1524728582: Error creating bridge: Temporary failure in name resolution.
```
Repeated attempts to lookup DNS and establish bridge need to be moved to separate thread

**Comment by ralight** [comment]
Asynchronous DNS lookups are carried out when compiled with WITH_ADNS=yes, which should be in place for versions of mosquitto from repo.mosquitto.org. What version do you have, and where did it come from?
