### ISSUE TITLE
ACLs does not working as expected

### ISSUE THREAD

**Issue by oliverlorenz** [eclipse/mosquitto#803]
I have the problem, that my acls does not working as I would expect. Here my mosquitto configuration:

```
mosquitto -h       
mosquitto version 1.4.14 (build date Mon, 10 Jul 2017 23:48:43 +0100)

mosquitto is an MQTT v3.1.1/v3.1 broker.

Usage: mosquitto [-c config_file] [-d] [-h] [-p port]

 -c : specify the broker config file.
 -d : put the broker into the background after starting.
 -h : display this help.
 -p : start the broker listening on the specified port.
      Not recommended in conjunction with the -c option.
 -v : verbose mode - enable all logging types. This overrides
      any logging options given in the config file.
```

command:
```
/usr/sbin/mosquitto -c /owntracks/mosquitto/mosquitto.conf
```

**/owntracks/mosquitto/mosquitto.conf** 
```

autosave_interval 1800
connection_messages true
log_dest stderr
log_dest topic
log_type error
log_type warning
log_type notice
log_type information
log_type all
log_type debug
log_timestamp true

max_inflight_messages 20
max_queued_messages 9000
message_size_limit 10240
allow_anonymous false

password_file /owntracks/mosquitto/mosquitto.passwd
acl_file /owntracks/mosquitto/mosquitto.acl

persistence true
persistence_location /mosquitto/config/
persistence_file mosquitto.db
persistent_client_expiration 1m

listener 1883

listener 8883
certfile /etc/letsencrypt/live/******/cert.pem
cafile /etc/letsencrypt/live/******/chain.pem
keyfile /etc/letsencrypt/live/******/privkey.pem
```

**/owntracks/mosquitto/mosquitto.acl**
```
topic read $SYS/#

user user1
topic readwrite   owntracks/user1/mobile
topic read        owntracks/user4/mobile
topic read        owntracks/user2/mobile
topic read        owntracks/user9/mobile
topic read        owntracks/user5/mobile
topic read        owntracks/user6/mobile
topic read        owntracks/user3/mobile

[...] # MORE USER CONFIGURATIONS

user user9
topic readwrite    owntracks/user9/mobile
topic read        owntracks/user1/mobile

user admin
pattern read      owntracks/#
pattern readwrite owntracks/+/+/cmd

# This affects all clients.
pattern write $SYS/broker/connection/%c/state
```

The Problem is, that `user9` is also receiving messages from topic `owntracks/user2/mobile` and I don't get it, what is wrong with my configuration. I would expect that `user9` only able to receive `owntracks/user9/mobile` and `owntracks/user1/mobile`

Can somebody help me?

**Comment by drahnr** [comment]
see #795

**Comment by ralight** [comment]
@drahnr You're mistaken. The ACLs may not prevent subscription, but they do prevent messages being received. 

@oliverlorenz - the problem is this line

```pattern read      owntracks/#```

You've used `pattern` here instead of `topic`. `pattern` applies to all users, so you've let everybody have access to everything in owntracks/#

**Comment by oliverlorenz** [comment]
@ralight Thank you a lot! :smile: That solves my problem! 

After you showed me the right way, I found the sentence "Pattern ACLs apply to all users even if the "user" keyword has previously been given." in the man page. So a RTFM in my direction would be vaild :wink: 

Anyways. Maybe it would be better to move this sentence before the description of this functionality. I think this was the reason why I missed it. Just a suggestion
