### ISSUE TITLE
Configuration file doesn't strip whitespace correctly

### ISSUE THREAD

**Issue by nicola-lunghi** [eclipse/mosquitto#804]
if in my mosquitto conf file I put a line like this
``
certfile /etc/mosquitto/certs/server.crt 
``
With a space at the end of the line mosquitto says

```
 Error: Unable to load server certificate "/etc/mosquitto/certs/server.crt ". Check certfile.
```

**Comment by karlp** [comment]
what version of mosquitto is this? I thought this was fixed.

**Comment by nicola-lunghi** [comment]
i have to check is the standard in Ubuntu 16.04 probably is an old version

**Comment by ralight** [comment]
No, you're quite right this is a bug. I thought we'd covered it before as well. I've committed a fix. Thanks for reporting it!
