### ISSUE TITLE
mosquitto in centos can't connect

### ISSUE THREAD

**Issue by raniak** [eclipse/mosquitto#806]
hello all
I installed mosquitto on centos 7, but there is a problem. I can't connect to it using any client.
do I have to add aditional configuration ? or there is a bug in this package?

**Comment by karlp** [comment]
Is it running? what version is it? waht does the log file say?

**Comment by raniak** [comment]
it is running 
and I tested it using mosquitto_sub and mosquitto_pub
can you tell me how to enable logging ?

**Comment by raniak** [comment]
it is version 1.4.15

**Comment by ralight** [comment]
If you have managed to get some results using mosquitto_pub and mosquitto_sub then the problem isn't with mosquitto, but with mqtt.fx. Are you sure you have the correct host settings in mqtt.fx and that there isn't a firewall in the way?

**Comment by raniak** [comment]
it was a firewall problem.
issue resolved. thanks :+1:
