### ISSUE TITLE
mosquitto container & tls not working

### ISSUE THREAD

**Issue by raniak** [eclipse/mosquitto#811]
hello all,
I have a problem with mosquitto docker image & tls encryption
I enabled tls in mosquitto.conf ( using Dockers volume)
and I generated the certificate
but when I try to connect with a mosquitto client, connection fails
I include the certificate while connecting
but when I repeat the steps on mosquitto Windows service ( not using docker) connection succeeds.
can somebody tell me how to configure tls on mosquitto docker image ?

thanks,
Rania

**Comment by ralight** [comment]
Are you able to provide any more information on how to reproduce what you are seeing? An example configuration would be a good start.

**Comment by ralight** [comment]
This hasn't seen any update for a long time, so I'm going to close it. The docker image has since been substantially updated as well. If it is still an issue, please reopen and provide more details.
