### ISSUE TITLE
How many user can connect to Mosquitto?

### ISSUE THREAD

**Issue by iranappo** [eclipse/mosquitto#812]
Hi
How many user can connect to This broker?
My app have 1 million users that i want to add chat feature to it
Maybe?

**Comment by Tifaifai** [comment]
What is your application ? 
```
The MQTT protocol provides a lightweight method of carrying out messaging using a publish/subscribe model. This makes it suitable for Internet of Things messaging such as with low power sensors or mobile devices such as phones, embedded computers or microcontrollers.
```
But it's true that we can do anything and divert technology ;) 👍

**Comment by iranappo** [comment]
Oh Thank you for your reply
My application is chat
My users are more than 1 million and i dont know mosquito can response my needing
I know mosquito can answer to 100k users,is it?Can you help me about chat and mqtt brokers?
    On Saturday, 5 May 2018, 19:46:18 GMT+4:30, Tifaifai Maupiti <notifications@github.com> wrote:  
 
 
What is your application ?
The MQTT protocol provides a lightweight method of carrying out messaging using a publish/subscribe model. This makes it suitable for Internet of Things messaging such as with low power sensors or mobile devices such as phones, embedded computers or microcontrollers.

But it's true that we can do anything and divert technology ;) 👍

**Comment by systemzsz** [comment]
I use mosquitto as IM, and it's a challenge to deal with so many users. Do you has some suggestions?

**Comment by iranappo** [comment]
No i have no suggestionRather i need a way for use many users
   On Tuesday, 15 May 2018, 12:09:22 GMT+4:30, zhongshzh <notifications@github.com> wrote:  
 
 
I use mosquitto as IM, and it's a challenge to deal with so many users. Do you has some suggestions?

**Comment by toast-uz** [comment]
I had evaluated mosquitto with up to 200k connections. The performance declined as the number of conns increased. It might depend on the rate of transferring messages, I guess connecting 1M clients will be serious for mosquitto. I heard some commercial mqtt broker products can solve the performance under the massive scenario by using Erlang/Elixer.

**Comment by iranappo** [comment]
Oh very good
do you know this product?
   On Tuesday, 15 May 2018, 17:24:17 GMT+4:30, toast-uz <notifications@github.com> wrote:  
 
 
I had evaluated mosquitto with up to 200k connections. The performance declined as the number of conns increased. It might depend on the rate of transferring messages, I guess connecting 1M clients will be serious for mosquitto. I heard some commercial mqtt broker products can solve the performance under the massive scenario by using Erlang/Elixer.

**Comment by toast-uz** [comment]
A candidate is IBM MessageSight. 
https://stackoverflow.com/questions/29106219/which-mqtt-server-for-1m-connections

**Comment by iranappo** [comment]
Thank you so much
   On Tuesday, 15 May 2018, 18:38:59 GMT+4:30, toast-uz <notifications@github.com> wrote:  
 
 
A candidate is IBM MessageSight.
https://stackoverflow.com/questions/29106219/which-mqtt-server-for-1m-connections

**Comment by iranappo** [comment]
Sure
