### ISSUE TITLE
Debian packages  for arm64?

### ISSUE THREAD

**Issue by ludiazv** [eclipse/mosquitto#815]
I've tried to use the mosquitto repo in an arm64 board and I receive this msg:
```
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'http://repo.mosquitto.org/debian stretch InRelease' doesn't support architecture 'arm64'
```
Is there any alternative for this arch?

Thnx,

**Comment by vielmetti** [comment]
I just installed on a stock Debian 9 system running arm64

```
Get:4 http://deb.debian.org/debian stretch/main arm64 mosquitto arm64 1.4.10-3+deb9u1 [119 kB]
```

**Comment by vielmetti** [comment]
I was able to build v1.5 from source, see #816 for that story.

**Comment by toast-uz** [comment]
@ludiazv was this issue solved by @vielmetti 's comment?

**Comment by ludiazv** [comment]
Yes, I was able to build from the source. I would recommend, however, to add the arm64 releases to deb packages would be better. The number of 64bits arm boards is growing fast.
