### ISSUE TITLE
mosquttio not running well in multicore machines.

### ISSUE THREAD

**Issue by systemzsz** [eclipse/mosquitto#817]
I had put mosquttio running in a machine which with 4 CPU and 8G memory.  
But the performance seemed not very good. Every 4 seconds, I publish a message but only about 1000 subscribers can be serviced stably.

There are 2 questions. 
**How can I improve mosquttio's performance, is any settings can be setted?
Does mosquttio achieve parallel processing but not only work in one CPU?**

**Comment by toast-uz** [comment]
As for 1st question, l need more information about your test conditions.
As for 2nd one, the answer is working on one CPU.

**Comment by systemzsz** [comment]
**Just single mosquitto, some settings I changed in mosquitto.conf.**

max_queued_messages 1000
persistence false
log_dest file mosquitto.log
log_type information
auth_plugin auth-plug.so

**and use mqtt SSL ,websocket SSL.**

**Every 4 sec, I used JMETER to send a message to topic A.  At the same time, 1000 subscribers subscribed topic A. There were no errors on JMETER before I added more 100 or 200 subscribers.**

**Comment by toast-uz** [comment]
For the 1st question, you'd better test step by step in order to clarify the bottleneck.
QoS and using websockets make significant performance impact to mosquitto.

**Comment by systemzsz** [comment]
ok, thanks.
You can close this issue.
