### ISSUE TITLE
 C++11 port to use std::thread and std::mutex

### ISSUE THREAD

**Issue by fireworm71** [eclipse/mosquitto#818]
I think it would be amazing to use the platform agnostic features introduced in C++11: std::thread and std::mutex in replacement of the pthreads library.

This would greatly simplify the setup required on Windows.

**Comment by ralight** [comment]
Sorry, apart from the C++ wrapper, mosquitto is going to remain C, so C++11 features aren't usable. I'm going to close this as "won't fix". Thanks for your comments anyway.
