### ISSUE TITLE
Auth plugin v3 interface incomplete?

### ISSUE THREAD

**Issue by Daedaluz** [eclipse/mosquitto#819]
https://github.com/eclipse/mosquitto/blob/4c9548cc7ca03522287c2b19a191f5f89cd49fa8/src/security.c#L422

I was writing a security plugin to mosquitto 1.5 with the new v3 interface, but to my surprice i did not recieve all the message fields (like qos and payload). Only topic seems to be set. =(

I'd also like to add that i'd like the auth plugin to be able to modify the message fields.
One point here would be to force minifying json payloads. Just a thought.

**Comment by karlp** [comment]
Surely it would not be the remit of an "auth" plugin to be doing transformations.  Surely auth would be authorized/not authorized.  You're introducing a massive performance bottleneck if payloads have to be recopied in and out of every plugin, with arbitrary changed lengths.

**Comment by Daedaluz** [comment]
Granted that an "auth" plugin should concern itself with auth tasks.
But, the bottleneck is only as bad as the plugin make it to be.
It would be up to the author of the plugin to decide whether a transformation or a simple packet drop would be worth the overhead.
I see no reason for a plugin on this level, not to be able to do what it wants with a passing message.
As it is a security module i'd prefer more power than less.

Why would the whole message have to be recopied in and out? can't one just use the original one as input and another as output if it's transformed or same if not?

**Comment by Assar63** [comment]
Another reason to pass payload on to the security module would be that the security module is the only place in a complete system where exact knowledge of connected identity is known. This makes it the only point where exact traceability would be achieved.

And, the function prototype states that data is available to use.

**Comment by Assar63** [comment]
If a security reason would arise, a modification of payload would be correct.
At the moment I can only think of the retain flag. The main broker can this way protect itself from misbehaving clients, or if central broker in cascading brokers systems should not retain messages.
This could be used as a kind of "local retain".

**Comment by toast-uz** [comment]
Closing as a new feature request. Discuss at mosquitto-dev ML if you want to contine.
