### ISSUE TITLE
There is a problem with the parameters obtained by this interface（mosquitto_auth_unpwd_check）

### ISSUE THREAD

**Issue by huangbug** [eclipse/mosquitto#820]
rc = opts->auth_plugin_configs[i].plugin.unpwd_check_v3(
                                        opts->auth_plugin_configs[i].plugin.user_data,
                                        context,
                                        username,
                                        password);
The incoming parameter context->address is xxx.xxx.xxx.xxx, the parameter  client->address obtained by the calling function(mosquitto_auth_unpwd_check) is (null), i don't know why?

The call function is below:
mosquitto_auth_unpwd_check(void *user_data, const struct mosquitto *client, const char *username, const char *password)
mosquitto version: v1.5

**Comment by robymus** [comment]
Use the following function, from `mosquitto_broker.h`:

```c
/*
 * Function: mosquitto_client_address
 *
 * Retrieve the IP address of the client as a string.
 */
const char *mosquitto_client_address(const struct mosquitto *client);
```

Accessing members of the mosquitto struct from the plugin didn't work for me either, thus functions gets the address correctly.

**Comment by ralight** [comment]
I think this is resolved so I'm closing it. To be clear, you should always use the accessor functions.
