### ISSUE TITLE
How to get the topic in on_subscribe, on_publish, on_unsubscribe?

### ISSUE THREAD

**Issue by LJenny** [eclipse/mosquitto#822]
Hello, I'm using the mosquitto for mqtt. It's nice.

I'm wondering that how to get the topic in on_subscribe, on_publish, on_unsubscribe?
Of course, I know that there is the mid value when calling subscribe() and I can match it in on_subscribe callback.
But is there an another way like parsing topic from in_packet or out_packet?

Thanks in advance.

**Comment by toast-uz** [comment]
Closing because this place is not for a question. Look at the instruction (https://mosquitto.org/).
