### ISSUE TITLE
Is it possible to have encrypted password instead of clear-text password for the "remote_password" configuration?

### ISSUE THREAD

**Issue by wumintao** [eclipse/mosquitto#823]
Hi all, 
 In the mosquitto configuration options, there is a "remote_password" parameter, which only accepts the clear-text value. Is it possible to use the encrypted value for this parameter?

Best Regards,

Mintao

**Comment by karlp** [comment]
This is not an encryption value at all. Please review the MQTT spec on what usernames and passwords are.  What are you really asking?  

(You may like to consider username/password as "public ID part A" and "public ID part B", they're simply two fields transmitted to the broker, they have no meaning beyond that)

**Comment by wumintao** [comment]
Hi Karl,
The issue here is that the password is kept at the configuration file as clear-text, which is security concern.
 I have to use the username and password pair since the remote server is using username and password to control the access on the topics.
Is it possible to add in another option field like “remote_encrypted_password”, which is used to keep the encrypted password instead?


Best Regards,

Mintao

**Comment by Assar63** [comment]
Hi @wumintao!
To use passwords in any type of automated way is raising concerns.
To place passwords in clear text or in any encrypted way for that matter enforces me to think "environment". The file itself need to be placed out of reach from unauthorized users. This is not limited to Mosquitto. Database clients, web servers and ssh servers do have the same need.
Have a look at how access to the file /etc/shadow is done. Personally I should set -rw-r--- in "others" for /etc/mosquitto/mosquitto.conf file and also set it to be owned by root:mosquitto. This way you need to be root to modify the file and be part of mosquitto group to read it.

**Comment by Assar63** [comment]
... and if authentication is needed, implement an authentication module!

**Comment by wumintao** [comment]
Hi,
The access right has been set on the config file. However, there is concern from our customer on the clear text password, because there is chance that the root user password is compromised and then password is leaked out. Therefore, I was proposing another option parameter with encrypted password for such case.

Best Regards,

Mintao

**Comment by Assar63** [comment]
One problem with an encrypted password is that you also need to store the password for the password on the same machine.
To gain access to a protected file like I exemplified above means that the user already have access to root password, which is of far more concern.

**Comment by Assar63** [comment]
I proposed implementing an authentication module. 
You can find a couple of them online.
Have a look at this one. I think it will fullfill your needs.
https://github.com/jpmens/mosquitto-auth-plug

**Comment by Assar63** [comment]
And here is a more simple one 
https://github.com/sskaje/mosquitto_auth_plugin_md5

**Comment by karlp** [comment]
@wumintao please, remember, the "password" for a bridge is _never_ encrypted _by definition in the protocol_  This is why I say it's pointless to try and encrypt it in the config file, and why you should not get hung up or distracted on the fact that it's called "password"  http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349247

This is without even _starting_ on the debates about user protections on files, whether you should have per user passwords so that loss isn't critical, the merits of env vars vs config files, and alllll of that further discussion.

**Comment by toast-uz** [comment]
Closing because this place is not for a question. Look at the instruction (https://mosquitto.org/).
