### ISSUE TITLE
/usr/bin/ld: unrecognized option '--dynamic-list=linker.syms'

### ISSUE THREAD

**Issue by mfe-** [eclipse/mosquitto#824]
Hi, I tried to compile mosquitto on my nas machine. The build it self works but it will throw at the end the message:

`/usr/bin/ld: unrecognized option '--dynamic-list=linker.syms'`

As a workaround I tried:

`make CFLAGS='-Wl,--export-dynamic'` but the result is the same.</br>

The last output of the `make CFLAGS='-Wl,--export-dynamic'` command:
  
```
cc -Wl,--export-dynamic  -I. -I.. -I../lib  -DVERSION="\"1.5\"" -DWITH_BROKER -DWITH_TLS -DWITH_TLS_PSK -DWITH_UUID -DWITH_BRIDGE -DWITH_PERSISTENCE -DWITH_MEMORY_TRACKING -DWITH_SYS_TREE -DWITH_EC -DWITH_EPOLL -c websockets.c -o websockets.o  
cc -Wl,--export-dynamic  -I. -I.. -I../lib  -DVERSION="\"1.5\"" -DWITH_BROKER -DWITH_TLS -DWITH_TLS_PSK -DWITH_UUID -DWITH_BRIDGE -DWITH_PERSISTENCE -DWITH_MEMORY_TRACKING -DWITH_SYS_TREE -DWITH_EC -DWITH_EPOLL -c ../lib/will_mosq.c -o will_mosq.o
In file included from ./mosquitto_broker_internal.h:21:0,
                 from ../lib/will_mosq.c:21:
../config.h:34:0: warning: "_POSIX_C_SOURCE" redefined
 #  define _POSIX_C_SOURCE 200809L

In file included from /usr/include/stdio.h:28:0,
                 from ../lib/will_mosq.c:17:
/c/opt/gcc-7.1/lib/gcc/sparc-unknown-linux-gnu/7.1.0/include-fixed/features.h:180:0: note: this is the location of the previous definition
 #  define _POSIX_C_SOURCE 199506L

cc mosquitto.o bridge.o conf.o conf_includedir.o context.o database.o handle_connack.o handle_connect.o handle_ping.o handle_pubackcomp.o handle_publish.o handle_pubrec.o handle_pubrel.o handle_suback.o handle_subscribe.o handle_unsuback.o handle_unsubscribe.o logging.o loop.o memory_mosq.o net.o net_mosq.o packet_mosq.o persist.o plugin.o read_handle.o security.o security_default.o send_connack.o send_connect.o send_disconnect.o send_mosq.o send_publish.o send_suback.o send_subscribe.o send_unsubscribe.o service.o signals.o subs.o sys_tree.o time_mosq.o tls_mosq.o utf8_mosq.o util_mosq.o websockets.o will_mosq.o -o mosquitto  -ldl -lm -lrt -Wl,--dynamic-list=linker.syms -lssl -lcrypto -luuid
/usr/bin/ld: unrecognized option '--dynamic-list=linker.syms'
/usr/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:59: mosquitto] Error 1
make[1]: Leaving directory '/c/backup/mosquitto-1.5/src'
make: *** [Makefile:26: mosquitto] Error 2
```
 ld:  
mosquitto-1.5# /usr/bin/ld --version
GNU ld version 2.15
Copyright 2002 Free Software Foundation

My gcc:
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/c/opt/gcc-7.1/bin/../libexec/gcc/sparc-unknown-linux-gnu/7.1.0/lto-wrapper
Target: sparc-unknown-linux-gnu
Configured with: ../gcc-7.1.0/configure CC=/opt/gcc-4.6/bin/gcc CXX=/opt/gcc-4.6/bin/g++ --enable-languages=c,c++ --prefix=/opt/gcc-7.1 --with-cpu=v7 Thread model: posix
gcc version 7.1.0 (GCC)

**Comment by karlp** [comment]
how did you manage to end up with binutils 2.15 with gcc 7.1?

**Comment by mfe-** [comment]
@karlp the gcc environment is a custom build from sources.

**Comment by toast-uz** [comment]
Is your environment sparc? Is there any information mosquitto supports your environment?

**Comment by mfe-** [comment]
@toast-uz is some kind of sparc. You can find the information about that little machine here: http://wiki.dietpc.org/index.php/DIET-PC_on_SPARC_ReadyNAS

**Comment by toast-uz** [comment]
Sorry I'd like to ask again "Is there any information mosquitto supports your environment?".
I guess sparc is not supported by mosquitto. Of course, you can request supporting sparc as a new feature request.

**Comment by karlp** [comment]
I still suspect your bintuils is simply wildly out of date. The last patch release for binutils 2.15 was in 2005.  You're using a self built toolchain, please just update your binutils too.

**Comment by mfe-** [comment]
I upgreaded to `binutils-2.31.1` which fixed the problem. Thanks!
