### ISSUE TITLE
Socket error on client when connecting to localhost

### ISSUE THREAD

**Issue by KristerBC** [eclipse/mosquitto#827]
Hi,

I have a problem connecting to the the broker, if the broker is on the same machine as the client.
As you can see on the picture below, it is only occuring, it's only happening with a client from localhost.

It is throwing the error, when the client is subscribing.

![image](https://user-images.githubusercontent.com/12972327/40324071-a772cf92-5d37-11e8-8f3b-b91738a1cb3e.png)

Anybody else having the same issue ?
I am using Mosquitto 1.4.15

**Comment by toast-uz** [comment]
Seemed your custom client on Paho. Could you reproduce the same error by using mosquitto_sub?

**Comment by toast-uz** [comment]
Closing as no information for a long time. Feel free to reopen if you are having this issue yet.
