### ISSUE TITLE
libmosquittopp ABI change without soname bump

### ISSUE THREAD

**Issue by dwmw2** [eclipse/mosquitto#829]
I believe https://github.com/eclipse/mosquitto/commit/ff79432364fd87827c81838ba7ac3e7e6dc780a3#diff-98a7c4fe4359211e79c0437347c96953 changed the ABI of the `mosquittopp` class.

Applications linked against the previous `libmosquittopp.so.1` ABI no longer work. Shouldn't we have changed the soname to `libmosquittopp.so.2` along with that change?

**Comment by toast-uz** [comment]
Mosquitto v1.5 released, and the new ABI has already spread. We cannot rewind the time. How should we treat this issue?

**Comment by toast-uz** [comment]
Closing as no information for a long time. Feel free to reopen if you are having this issue yet.

**Comment by barsnick** [comment]
Well observed by David.

We have observed serious issues with clients compiled against libmosquittopp-1.4.10, but running with 1.5.4, and vice versa. Most notably: The former get a spontaneous disconnect after connect to the the broker, the latter just segfault.

David's (visual?) observation is confirmed not only by our crashes, but also by this (automatically generated and interpreted) binary compatibility report:
https://abi-laboratory.pro/index.php?view=compat_report&l=mosquitto&v1=1.4.15&v2=1.5&obj=5ee13&kind=abi#Type_Problems_High

I also believe the ABI's version (soname) should have been bumped.

**Comment by dwmw2** [comment]
I suppose the best thing to do is to bump the soname now, belatedly. At least older binaries which attempt to run against a new build of the library will fail correctly and gracefully.

**Comment by ralight** [comment]
I agree, bumping the soname now is the least worst option.

Please also note that libmosquittopp is going to go away in version 2.0: https://mosquitto.org/roadmap/
