### ISSUE TITLE
configuration error

### ISSUE THREAD

**Issue by korish23** [eclipse/mosquitto#831]
$  /usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
1527045665: mosquitto version 1.5 starting
1527045665: Config loaded from /etc/mosquitto/mosquitto.conf.
1527045665: Error: Unable to load auth plugin "/etc/mosquitto/auth-plug.so".
1527045665: Load error: /etc/mosquitto/auth-plug.so: undefined symbol: OPENSSL_add_all_algorithms_noconf

**Comment by toast-uz** [comment]
I will close this issue in the near future, as no information for a long time.

**Comment by toast-uz** [comment]
Closing as no information for a long time. Feel free to reopen if you are having this issue yet.
