### ISSUE TITLE
How to make Mosquitto public ?

### ISSUE THREAD

**Issue by hiteshpratyushv** [eclipse/mosquitto#832]
I have a mosquitto broker running on my raspberry pi. Right now, I am able to connect to the broker via devices connect on the local network but for my project I want to connect it via the whole internet
I know port forwarding is an option but I don't have much knowledge about this so it would be nice if someone could just give me the steps to do so. Thanks in advance.

**Comment by Tifaifai** [comment]
Maybe post on mosquitto-dev mailing List ;)
