### ISSUE TITLE
Support of MQTT 5

### ISSUE THREAD

**Issue by johb** [eclipse/mosquitto#834]
Hello,

I would like to know what the current status of MQTT 5 support is.

Are there already any plans/ some code?

I couldn't find anything.

**Comment by toast-uz** [comment]
Refer #519 .

**Comment by ptjm** [comment]
https://mosquitto.org/blog/2018/05/press-release/
"The MQTT v5 compliant release is planned for the end of August 2018."

**Comment by toast-uz** [comment]
Closing because this place is not for a question. Look at the instruction (https://mosquitto.org/).

**Comment by AtosNicoS** [comment]
Are there any updates on mqtt5 support yet?

**Comment by ralight** [comment]
Unfortunately not, other work unrelated to mosquitto has had to take precedence.

**Comment by toast-uz** [comment]
If my PR #519 submitted can be used, I can update the PR based on the latest mosquitto. I wanted to make some PRs in order to support mqtt v5, but I could not due to wait the confirmation of first PR for one year.

**Comment by RobertoMalatesta** [comment]
@ralight 
just to give a hand, is there a git repo or a branch of mqtt5 unstable code we can start testing ?

--R
