### ISSUE TITLE
Mosquitto wont auto start on Ubuntu 18.04

### ISSUE THREAD

**Issue by dastrix80** [eclipse/mosquitto#836]
hi all, used the apt-get install method.

It works fine when starting manually but doesnt upon reboot.

Im a little confused being new to linux. Can anyone assist me in working out why?

Thanks! 

ive literally tried everything (spent 8hrs so far, no luck) I can get it running manually from the command line and used these instructions to install - https://www.vultr.com/docs/how-to-install-mosquitto-mqtt-broker-server-on-ubuntu-16-04

It also starts fine using mosquitto -d

This, however fails, nothing actually runs

kris@OpenHAB:~$ systemctl status mosquitto.service
● mosquitto.service - Mosquitto MQTT Broker
   Loaded: loaded (/etc/systemd/system/mosquitto.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-05-28 16:41:59 AEST; 5min ago
  Process: 3368 ExecStart=/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf (code=exited, status=3)
 Main PID: 3368 (code=exited, status=3)

May 28 16:41:59 OpenHAB systemd[1]: mosquitto.service: Service hold-off time over, scheduling restart.
May 28 16:41:59 OpenHAB systemd[1]: mosquitto.service: Scheduled restart job, restart counter is at 5.
May 28 16:41:59 OpenHAB systemd[1]: Stopped Mosquitto MQTT Broker.
May 28 16:41:59 OpenHAB systemd[1]: mosquitto.service: Start request repeated too quickly.
May 28 16:41:59 OpenHAB systemd[1]: mosquitto.service: Failed with result 'exit-code'.
May 28 16:41:59 OpenHAB systemd[1]: Failed to start Mosquitto MQTT Broker.
kris@OpenHAB:~$

if I run it manually:

kris@OpenHAB:~$ mosquitto -c /etc/mosquitto/mosquitto.conf
1527490252: Error: Unable to open log file /var/log/mosquitto/mosquitto.log for writing.
kris@OpenHAB:~$

**Comment by dastrix80** [comment]
EDIT:

If I remove the reference to the log file in my conf file, then it runs OK.

Seems a permission issue for the log file. Any thoughts on how I can correct this as Id like the log

**Comment by g3rb3n** [comment]
chmod mosquitto:mosquitto /var/log/mosquitto solves the problem, without the need to disable logging.
