### ISSUE TITLE
in-memory database saving to disk drops all client connections every 30 minutes

### ISSUE THREAD

**Issue by mehdilauters** [eclipse/mosquitto#840]
Hi,
It appears that every half an hour I get all my devices disconnected and reconnected. Some are using the javascript mqtt implementation, some a [lwmqtt](https://github.com/256dpi/arduino-mqtt) implementation and some a paho python version.

Kernel version
````Linux ggs 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux````

Distribution
````
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
````
Mosquitton version
````
mosquitto version 1.4.10 (build date Fri, 22 Dec 2017 08:19:25 +0000)
mosquitto is an MQTT v3.1 broke
````
Websockets are enabled in the mosquitton configuration.

By enabling debug logs on the configuration file I noticied that the last log line before all my clients are kicked is ````1527606408: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.````

From the documentation ````autosave_interval```` defaults to 30 minutes. I made a test to 1 minute of interval, and all devices are kicked every minute so the workaround is to set a value of 0 to save database only at exit.

From a device side, I get a [LWMQTT_NETWORK_FAILED_WRITE](https://github.com/256dpi/arduino-mqtt/blob/master/src/lwmqtt/lwmqtt.h#L18) error.

Regards

**Comment by karlp** [comment]
a) retest on a recent version
b) what's your keepalive set to? is it really short?
c) how big is your db? if you have a lot to save, and it blocks while it does, and your keepalive is really short, you could be just timing out your clients.

**Comment by toast-uz** [comment]
I will close this issue in the near future, as no information for a long time.

**Comment by toast-uz** [comment]
Closing as no information for a long time. Feel free to reopen if you are having this issue yet.
