### ISSUE TITLE
Snap service crashes on /snap/mosquitto/33/usr/local/sbin/mosquitto: not found

### ISSUE THREAD

**Issue by physicsG** [eclipse/mosquitto#842]
The Mosquitto service crashes at startup when running as snap. journalctl show the following error:

> May 30 15:08:48 GRMW802 snap[12265]: /snap/mosquitto/33/launcher.sh: 41: /snap/mosquitto/33/launcher.sh: /snap/mosquitto/33/usr/local/sbin/mosquitto: not found

That is not so strange, because `/snap/mosquitto/33/usr/local/sbin` does not exist. The mosquitto launcher can, however, be found in `/snap/mosquitto/33/usr/sbin/`, hereby omitting `local`.

**Comment by toast-uz** [comment]
The latest commit "Fix snap launcher path." might fix this issue.
https://github.com/eclipse/mosquitto/commit/75fc908bba90d4bd06e85efc1c4ed77952ec842c

Could you try?

**Comment by ralight** [comment]
This has been fixed for a while, sorry for the inconvenience!
