### ISSUE TITLE
Bridge does not works (loop) on docker image (eclipse-mosquitto:latest)

### ISSUE THREAD

**Issue by titos-carrasco** [eclipse/mosquitto#843]
Works good on 1.4.10

my config:
connection Mosquitto
  address test.mosquitto.org:1883
  start_type automatic
  try_private true
  bridge_protocol_version mqttv311
  bridge_attempt_unsubscribe true
  cleansession true
  notifications false
  topic # both 0 xxxxx/ xxxxx/

**Comment by karlp** [comment]
So what does _not_ work then?  Can you provide more detail please?

**Comment by toast-uz** [comment]
I will close this issue in the near future, as no information for a long time.

**Comment by toast-uz** [comment]
Closing as no information for a long time. Feel free to reopen if you are having this issue yet.
