### ISSUE TITLE
Android build

### ISSUE THREAD

**Issue by rb0urd0n** [eclipse/mosquitto#853]
Hi all,

I'm trying to build a client for Android, but there is a lack of information about this...

I've successfully built a static lib and used it but got this behavior:
- I can connect to the server (got connection logs on the server)
- I can run mosquitto_loop_start, return code say it's OK
- Then I can publish neither subscribe: return code say it's OK but the server doesn't receive anything

I think the problem comes from my build.

Any idea, suggestion or doc about this?

Thanks.

**Comment by llulioscesar** [comment]
Do you want to create a service in the background or just use it in an activity?

**Comment by llulioscesar** [comment]
Create my service by guiding me through this tutorial maybe it will help you. It is explained step by step [Tutorial](https://wildanmsyah.wordpress.com/2017/05/11/mqtt-android-client-tutorial/)

[another tutorial](http://androidkt.com/android-mqtt/)

**Comment by toast-uz** [comment]
Closing because this place is not for a question. Look at the instruction (https://mosquitto.org/).

**Comment by rb0urd0n** [comment]
I can't find any information/instruction about building for Android there...
