### ISSUE TITLE
mosquitto bridge to baidu iot hub  failed with identifier refused

### ISSUE THREAD

**Issue by boycechen** [eclipse/mosquitto#854]
The follows is my baidu cloud connect conf file:
root@IoT-Broker:/home/pi# more /etc/mosquitto/conf.d/baidu.conf
connection bri_to_baidu
address iott.mqtt.iot.bj.baidubce.com:1883
topic # both 0  iot/baiduyun/ iot/baiduyun/
remote_clientid dev322
local_clientid  dev233
#clientid        dev123
cleansession true
start_type automatic
try_private false
remote_username iott/device
remote_password rkidA9v2oDAMQhbA3GQHkXTZjZZV0pHfY37UBYvUXvQ
notifications true
bridge_protocol_version mqttv311
#bridge_tls_version tlsv1
bridge_insecure true
log_type all

but when I use command mosquitto -c /etc/mosquitto/mosquitto.conf -v  
failed with the follows error:
root@IoT-Broker:/home/pi# mosquitto -c /etc/mosquitto/mosquitto.conf -v
Warning: Bridge bri_to_baidu using insecure mode.
1528178628: mosquitto version 1.4.10 (build date Fri, 22 Dec 2017 08:19:25 +0000) starting
1528178628: Config loaded from /etc/mosquitto/mosquitto.conf.
1528178628: Opening ipv4 listen socket on port 1883.
1528178628: Opening ipv6 listen socket on port 1883.
1528178628: Bridge dev233 doing local SUBSCRIBE on topic iot/baiduyun/#
1528178628: Connecting bridge bri_to_baidu (iott.mqtt.iot.bj.baidubce.com:1883)
1528178628: Bridge dev322 sending CONNECT
1528178628: Received CONNACK on connection dev233.
**1528178628: Connection Refused: identifier rejected**
1528178628: Socket error on client dev233, disconnecting.
^C1528178630: mosquitto version 1.4.10 terminating
1528178630: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.

**Comment by karlp** [comment]
are you sure your remote clientid is correct?

**Comment by karlp** [comment]
from what I can translate of https://cloud.baidu.com/doc/IOT/IOTService.html#.E8.BF.9E.E6.8E.A5IoT.20Hub.E6.9C.8D.E5.8A.A1 it would appear that you put your "token" (that you put in as remote_password) as the clientid. but either way, this is just an issue with working out the credentials that baidu requires in which place, there's nothing mosquitto can do here.

**Comment by karlp** [comment]
notifications are effectively "publish" to the $SYS/broker/connection/<clientid>/status topic.  These can and often are blocked by remote brokers.  (any rabbitmq  server, azure, etc), You can change the topic, with notifications_topic, or turn off notifications (and also only remote notifications with 1.5 or later)
