### ISSUE TITLE
Mosquitto.h/lib cannot find/load Mosquitto.dll

### ISSUE THREAD

**Issue by AistisT** [eclipse/mosquitto#855]
I am trying to use mosquitto.h that comes with binary installation in devel for windows.

I am however having issues when I am trying to run simple test project that relies on it. Header and Libraries linked through VS2017, it compiles and builds fine, but when ran throws "A dependant dll was not found." 
When using Dependency Walker on compiled exe I can see that Mosquitto.dll is not being loaded. I've even moved mosquitto.dll to same folder as header/lib files, but that has no effect.

I've followed all instructions while installing the broker and I know it works because I can publish a message through mossquitto_pub.exe and receive it in .Net Core code, yet no matter what I can't get c/c++ side to work.

**Comment by AistisT** [comment]
Creating a new project in vs 2015, produces actual error messages on compilation. Cannot open mosquitto.dll, and if its copied into devel folder, it returns corrupted/cannot read file error.

**Comment by AistisT** [comment]
![image](https://user-images.githubusercontent.com/14581924/41294924-1df919da-6e51-11e8-9435-0666f0b684b0.png)

Seems quite few dll's are not found by mosquitto.dll, vs 2017 c++ redists are installed, which are upgrade to vs 2015 c++redists,

**Comment by ralight** [comment]
I'm not sure what I'm seeing in that image, could you explain what the different symbols mean please?

**Comment by AistisT** [comment]
I've managed to solve this a while ago, this can be closed.
