### ISSUE TITLE
mosquitto client: unexpected behavior with --insecure

### ISSUE THREAD

**Issue by uboscolo** [eclipse/mosquitto#859]
I am seeing the below error even though I specify  --insecure 
Client ub_test sending CONNECT
OpenSSL Error: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Error: A TLS error occurred

I am using 1.5

some analysis:

in ./client/client_shared.c, we seem to set the cert_reqs always to true, independently of the --insecure option:

        if((cfg->tls_version || cfg->ciphers) && mosquitto_tls_opts_set(mosq, 1, cfg->tls_version, cfg->ciphers)){
                if(!cfg->quiet) fprintf(stderr, "Error: Problem setting TLS options.\n");
                mosquitto_lib_cleanup();
                return 1;
        }

then in ./lib/net_mosq.c we do:

                        if(mosq->tls_cert_reqs == 0){
                                SSL_CTX_set_verify(mosq->ssl_ctx, SSL_VERIFY_NONE, NULL);
                        }else{
                                SSL_CTX_set_verify(mosq->ssl_ctx, SSL_VERIFY_PEER, mosquitto__server_certificate_verify);
                        }

this seems to make the insecure options ineffective, any thoughts?

**Comment by toast-uz** [comment]
Could clarify which is your insistence, the implementation is wrong compared with the description (reporting a bug), or the description is ineffective (wish enhancement)?

```
--insecure
When using certificate based encryption, this option disables verification of the server hostname in the server certificate. This can be useful when testing initial server configurations but makes it possible for a malicious third party to impersonate your server through DNS spoofing, for example. Use this option in testing only. If you need to resort to using this option in a production environment, your setup is at fault and there is no point using encryption.
```

**Comment by uboscolo** [comment]
Reporting a bug.

--Umberto

**Comment by toast-uz** [comment]
According to the description of insecure option, I guess it ignores only the server hostname in the server certificate, does not ignore the server certificate. The insecure option turns on mosq->tls_insecure, but not influenced to mosq->tls_cert_reqs.

in ./lib/tls_mosq.c the function mosquitto__server_certificate_verify implemented as the description.

What do you think about that?

**Comment by uboscolo** [comment]
ok, so there's no way to take this path via configuration right?

if(mosq->tls_cert_reqs == 0){
    SSL_CTX_set_verify(mosq->ssl_ctx, SSL_VERIFY_NONE, NULL);

**Comment by ralight** [comment]
That is not possible with mosquitto_pub/sub, correct. You should question your motives for wanting this though! :) If you are using encryption but not asking for, nor verifying the server certificates then what is the point in encrypting in the first place?

You do have the option of writing your own version of the tools that don't carry out any verification at all.

I don't believe this is a bug, but am happy to keep discussing it further. If you are satisfied, please close the issue.

**Comment by toast-uz** [comment]
Closing as no information for a long time. Feel free to reopen if you are having this issue yet.
