### ISSUE TITLE
Connection unstable with keepalive=2

### ISSUE THREAD

**Issue by barrierbank** [eclipse/mosquitto#865]
The lowest supported keepalive value, 2 seconds, results in an stable connection even if the connection is solid.  Intermittently we see:

```
Jan 01 05:44:52 mosquitto[711]: 1577857492: Client my-app has exceeded timeout, disconnecting.  
Jan 01 05:44:52 my-app[645]: 20200101 05:44:52.096 >>> [warning] Disconnected unexpectedly: 7
Jan 01 05:44:52 my-app[645]: 20200101 05:44:52.101 >>> [info] Disconnected.
Jan 01 05:44:52 mosquitto[711]: 1577857492: Socket error on client my-app, disconnecting.
```
Here, 7 means MOSQ_ERR_CONN_LOST.

I took a look at the code:
https://github.com/eclipse/mosquitto/blob/master/src/loop.c#L246
```
now - context->last_msg_in < (time_t)(context->keepalive)*3/2
```

If context->keepalive is 2, this comparison is ```now - context->last_msg_in < 3```.  The client is pinging the broker every 2 seconds and the resolution of the values "now" and "context->last_msg_in" is one second.  It seems likely that if the clock is read at the wrong instant then this comparison could fail.  For example, "last_msg_in" occurs at +999 milliseconds (time_t of 0 seconds) and "now" occurs at +3001 milliseconds (time_t of 3 seconds), the difference of the actual times is 2002 milliseconds and so falls within the 3 seconds limit, but the difference of the time_t values is 3 and so fails the comparison.

This could be improved by changing "<" to "<=", or alternatively adding 1 or 2 on the right hand side.

**Comment by karlp** [comment]
given that keepalive is defined by spec in seconds, with behaviour based on half of that, I actually think it's user failure to try and use a keepalive of 2 seconds.  But yes, you could increase the overhead for everyone by doing all the calculations in millis or finer instead.  

You can't simply change the < to a <= or add 1 or 2 as that will make it very much non compliant on more reasonable values like 30/60/90.

**Comment by barrierbank** [comment]
Thanks for your quick reply on this.

At the moment the code is inconsistent.  If "WITH_WEBSOCKETS" is defined, it does in fact use <= rather than <.

Code reference:
https://github.com/eclipse/mosquitto/blob/master/src/loop.c#L81

```
if(context->keepalive && now - context->last_msg_in > (time_t)(context->keepalive)*3/2){
```
Since it is using > to detect timeout, the condition for no timeout is the opposite i.e. <=.

So either L81 or L246 is "very much non compliant", to use your phrase.  Which one is it?

**Comment by toast-uz** [comment]
It's a very tricky story, so I cannot agree your insistence that it is a bug. If you really want to fix it, you should post a PR as an improvement.

**Comment by ralight** [comment]
This definitely should be consistent. I'm inclined to take the opinion that we should disconnect the client if it *exceeds* keepalive*3/2, rather than meets it. This means a "<=" in the first case. For low keepalive this gives more leeway, for normal keepalive it is only a small percentage change in favour of the client.

If Mosquitto did have a mechanism to reject low keepalive values (or, as in MQTT 5, force the keepalive to a particular value), then this would be configurable. In that case you would have just chosen to set 1 or 2 second as the limit and still had this problem. Please don't use such a low value, I'd set 10 as your minimum.  In many cases the disconnection will be noticed much quicker that that anyway.

**Comment by ralight** [comment]
I've pushed a change to make the two checks consistent, that is as much as I can offer on this at the moment. You've got a bit more grace on your low timeouts. If you're happy with that, please close the issue.

**Comment by barrierbank** [comment]
Great!  Thanks for making this change.

In the meantime our client has agreed to switch to the far more sensible value of 15 seconds, so the issue doesn't affect us now, but it will help future users who opt for overly-intensive pinging.
