### ISSUE TITLE
mosquitto 1.5 "forgets" subscriptions

### ISSUE THREAD

**Issue by ckrey** [eclipse/mosquitto#866]
Situation:

- Client connects and subscribes to 4 topics with QoS1
- Client disconnects 
- Other clients publish to the subscribed topics and get queued
- When Client re-connects with CleanSession=false, queued messages are delivered to Client
...
Until something goes wrong and the Client does not get queued messages on re-connect although
sessionPresent is set in CONNACK

The situation does not clear up over time. A restart of mosquitto releases the block and the 
queued messages are delivered on the next re-connect.

Hint:
I found duplicate clients in the output of `mosquitto_db_dump --client-stats mosquitto.db`

```
SC: 4 SS: 145 MC: 367 MS: 111150   ck00iPhoneSE
...
SC: 0 SS: 0 MC: 0 MS: 0   ck00iPhoneSE
```

**Comment by ckrey** [comment]
mosquitto.log and mosquitto.db file are available on request per DM

**Comment by toast-uz** [comment]
@ckrey could you try #893 ?

**Comment by ckrey** [comment]
@toast-uz yes #893 fixes the problem

This can be easily recreated/tested using the example in #874

**Comment by toast-uz** [comment]
Thanks @ckrey .
Shall I close this issue as duplicate with #874 ? Of course, this is the original. But, I'd like to keep #874 because there are further discussion in it.

**Comment by ckrey** [comment]
I think we can close this issue because
- it seems to have the same underlying problem as #874 and
- I did not find a way to reproduce it deliberately
