### ISSUE TITLE
Publishing retain messages control

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto#87]
migrated from Bugzilla [#452924](https://bugs.eclipse.org/bugs/show_bug.cgi?id=452924)
status NEW severity _enhancement_ in component _Mosquitto_ for _1.5_
Reported in version _unspecified_ on platform _PC_
Assigned to: Roger Light

On 2014-11-23 17:01:10 -0500, Roger Light wrote:

> (imported from launchpad)
> 
> The mosquitto_auth_acl_check allows to control if a client is allowed to publish on a given topic.
> For different reasons, it may be interesting to control if a client has the right to publish with the retain option on a given topic.
> Eg: if we have no control on the client part, the client could flood the broker by publishing retained messages leading to a memory overflow on the broker.

On 2015-01-28 05:28:00 -0500, Roger Light wrote:

> Part of the authentication/access control review for 1.5.

**Comment by Hades32** [comment]
Would this issue only allow plugins do handle this, or would it be possible in the acl.conf ? This would be pretty important

**Comment by ralight** [comment]
Plugins have the ability to keep track of the `retain` status of publishes, so I am closing this. There are no plans to extend support to the acl_file feature.
