### ISSUE TITLE
v1.5

### ISSUE THREAD

**Issue by ZhouBox** [eclipse/mosquitto#870]
I use this conf file in v1.4.14, when I use in v1.5, I found websockets conf no used , I cat not connected to websockets port.

**Comment by timoline** [comment]
like #837 ?

**Comment by toast-uz** [comment]
Please change the subject to the outline of the candidate bug you want to report.

**Comment by toast-uz** [comment]
Closing as no information for a long time. Reopen and change the subject if you want to report a new bug.
