### ISSUE TITLE
Mosquitto :Socket error on client

### ISSUE THREAD

**Issue by Chalno** [eclipse/mosquitto#872]
when Mosquitto  run on  ubuntu server in virtualbox,that's ok.
when Mosquitto  run on a real ubuntu server machine with 4 network cards,every 40 minutes,  Mosquitto :Socket error on client.

**Comment by toast-uz** [comment]
Could you show your conf file and log file? Could you reproduce your issue with one netwrok card?

**Comment by ralight** [comment]
Do you have any details of the clients you are using, such as what program/library they are using, and the keepalive time?

**Comment by toast-uz** [comment]
Closing as no information for a long time. Feel free to reopen if you are having this issue yet.
