### ISSUE TITLE
Too much useless calls of packet__write()

### ISSUE THREAD

**Issue by shevast** [eclipse/mosquitto#877]
I use mosquitto client library in my application for publishing messages. 

Publish data flow is ~0.2 MB/s (~1200 - 1500 msgs/s, each msg ~120 Bytes). 
Max inflight messages set to 3000.
Sometimes broker goes offline, as result output queue starts to grow (actually on my application side, but after reconnect it is scheduled to mosquitto). After reconnect queue is large enough (~100K - 200K messages).

**mosquitto_loop_write()** has logic to call **packet__write()** N times, where N is sum of lengths of input and output queue. If **packet__write()** returns _MOSQ_ERR_SUCCESS_, and _errno_ isn't set to _EAGAIN_/_COMPAT_EWOULDBLOCK_, it will be called again.

Problem is that **packet__write()** will return _MOSQ_ERR_SUCCESS_ without _errno_ set even in case if mosquitto has no more packets to write (_mosq->out_packet_ is NULL).
In my case this led to ~100K-200K extra **packet__write()** calls with every **mosquitto_loop_write()** call. As result **mosquitto_loop()** spends most of time doing this job, output queue increasing simultaneously, and, consequently, amount of extra **packet__write()** invocations grows too.

Actually even if no disconnects occurred, **mosquitto_loop_write()** does large amount of useless calls to **packet__write()** (equal to queue length), but this is not critical, just slows down data exchange with broker.

I think it will be good to implement a way for **packet__write()** to notify caller (**mosquitoo_loop_write()** in this case), that there are no more work to do (no more packets to write), so it can stop calling it again and again.

After I add following to **packet__write()**:
`
if (!mosq->out_packet && !mosq->current_out_packet) {
		errno = EAGAIN;
	}
`
problems are gone, and speed of data exchange increased.

Please, let me know me if this will be fixed,
Thank you

**Comment by toast-uz** [comment]
Please change the subject If you insist on reporting a bug for mosquitto. This place is not for a question, for a new feature request, or for an improvement request. Look at the instruction (https://mosquitto.org/).

**Comment by shevast** [comment]
I can't find instructions on reporting bug by provided link. I reported
issue on github first, but it was left without answer, so I decide to try
here. Can you please instruct me what should I do?

пт, 27 июл. 2018 г., 14:01 toast-uz <notifications@github.com>:

**Comment by shevast** [comment]
How can I change subject to point that this is a bug?

**Comment by toast-uz** [comment]
At the beginning, I cannot determine this is a bug or not. Therefore, I'd like to clarify your intent.

I think the bug is not to work according to the defined specification. There is no specification of performance for mosquitto. Therefore, this problem is not a bug, but an improvement, except for a significant degrade from the former version of mosquitto.
 
My recommend is to close this issue and create a new PR. You could implement.

**Comment by shevast** [comment]
I agree that non-optimal implementation of writing data is not critical most of time (just slows down communication a little), and situation described in issue is very uncommon. But when it happens result is almost zero data transmission and - consequently - out of RAM (no way to reestablish normal communication, only restart).
I will try to research who may expect on such implementation (to break nothing) and create pull request with fix. 

p.s. I just hoped that someone already know why that 'for'-loop there and it will easier for him to fix this properly. That's why I started issue.
