### ISSUE TITLE
Old versions not archived on debian repository

### ISSUE THREAD

**Issue by tim-bitreactive** [eclipse/mosquitto#879]
Old versions are not archived in the debian repository at http://repo.mosquitto.org/debian/
Affects: 1.4.15-0mosquitto3~jessie1 armhf which is no longer accessible.
This will break version-locked installations such as dockerfile definitions.

**Comment by toast-uz** [comment]
Please change the subject If you insist on reporting a bug for mosquitto. This place is not for a question nor for a new feature request. Look at the instruction (https://mosquitto.org/).

**Comment by ralight** [comment]
This is down to the Debian repository management tools being used. It seems possible to keep old debs around, but they wouldn't be referred to in the repository packages file, so I'm not sure how useful this would be.

The alternative is to find different Debian repository tools, which I'll be honest isn't something I look forward to.

**Comment by tim-bitreactive** [comment]
Which tools are you currently using?
https://github.com/freight-team/freight should support multiple versions of the same package, as should 
https://www.aptly.info/

**Comment by ralight** [comment]
Some of the tools that are part of Debian itself, `reprepro` is the current repo. I've been looking at `mini-dinstall` which seems to do the job and I can make it so any existing users don't see any changes.
`freight` sounds good, but they say 

> Freight uses hard links aggressively to drop old packages from the cache and use as little storage as possible. 

Aptly sounds more promising, I'm taking a look at that now.

**Comment by ralight** [comment]
We're now using aptly and old versions are available.

https://mosquitto.org/blog/2018/08/updated-debian-repository-backend/

**Comment by tim-bitreactive** [comment]
`apt-get install -y mosquitto=1.4.15-0mosquitto4~jessie1` on armhf works as expected.
Thanks for your quick support and effort!
