### ISSUE TITLE
Mosquitto 1.5 rejecting Nyamuk connection

### ISSUE THREAD

**Issue by tronar** [eclipse/mosquitto#880]
New to MQTT, playing with python clients from OpenWRT to Ubuntu 16.04 broker.

Using Nyamuk, seemed fine and small. Broker was distro provided 1.4.8 if memory serves.
Wanted to have different ACLs per listener (direct for sensors RW, WS for dashboards, RO) so moved to 1.5. 

Nyamuk connections were then rejected. Changing to "protocol=3" solved the issue.

Now from Nyamuk docs "protocol=4" wich is the default relates to MQTT 3.1.1 and "protocol=3" relates to 3.1. I do not know enough, but something changed in 1.5 that breaks it, and it seemed worth reporting.

**Comment by toast-uz** [comment]
Seemed the issue for Nyamuk.
Mosuqitto v1.5 added some strict check of protocol. Nyamuk's malfomed packt on mqtt v3.1.1 cannot  be accepted.
I captured Nyamuk's CONNECT packet and found there are extra two bytes on v3.1.1 while valid on v3.1. Nyamuk seems keep the same size of packet buffer regardless protocol version, although the size of the protocol identifier ("MQIsdp" on v3.1, "MQTT" on v3.1.1) is different. Therefore, it makes extra bytes on v3.1.1.

**Comment by toast-uz** [comment]
I've reconfirmed this by replacing the line 123 in nyamuk/mqtt_pkt.py from  ```self.remaining_length = 12 + payload_len``` to ```self.remaining_length = 10 + payload_len```. You can find to connect mosquitto v1.5 on mqtt v3.1.1 after the patch.

**Comment by toast-uz** [comment]
Great! Shall I close this issue?

**Comment by tronar** [comment]
Sure thing, I've added a comment on Nyamuk's site. Thanks again!
