### ISSUE TITLE
limit of simultaneous clients

### ISSUE THREAD

**Issue by llulioscesar** [eclipse/mosquitto#881]
I have a vps with the following specifications:

1 Core (s) 3.1 GHz
1 GB of RAM
Debian 9 x64

perform tests with mqtt-benchmark establishing 500 clients, but when it reaches the customer 381 throws socket error

the vps monitor in the ovh administration control panel indicates that the processor is at 10% and ram memory at 30% and upon receiving the error it decreases the processor to 3% and the ram to 20%.

https://www.npmjs.com/package/mqtt-benchmark

my application waits between 2000 and 5000 devices in several farms with palm oil

I want to buy a dedicated server
CPU: Intel Xeon E3-1245v5 - 4 / 8t - 3.5GHz /3.9GHz
RAM: 16GB DDR4 ECC 2133 MHz
Disks: SoftRaid 2x2TB
Debian 9 x64

I want to know the maximum number of connections supported by the vps and by the dedicated server

**Comment by Tifaifai** [comment]
Mosquitto version ?
Maybe replace palm oil ;)

**Comment by Tifaifai** [comment]
1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.5

Have you the same problem with 1.4.15 or 1.5 ?
1.4.10 -> Last commit 16 August 2016 ;)

**Comment by llulioscesar** [comment]
install version 1.5
[https://ibb.co/d7TzWo](url)

run no ssl
`mqtt-benchmark --broker=mqtt://pigajeh8u665pphioze0.fincareport.com:1883 --qos=1 --clients=500 --subqos=1 -d`
[https://ibb.co/c2upWo](url)

run ssl
Change settings and add certificates to a mosquito in your configuration
`mqtt-benchmark --broker=mqtts://pigajeh8u665pphioze0.fincareport.com:8883 --qos=1 --clients=500 --subqos=1 -d`
[https://ibb.co/iNxexT](url)

the problem was nginx. I used it as a reverse proxy
[https://ibb.co/nfiKxT](url)

**Comment by llulioscesar** [comment]
probe with 1200 client and receive error, I'm not using nginx. It is connecting directly to mosquitto with ssl

`mqtt-benchmark --broker=mqtts://pigajeh8u665pphioze0.fincareport.com:8883 --qos=1 --clients=1200 --subqos=1 -d`

status vps
[https://ibb.co/jSPvMo](https://ibb.co/jSPvMo)

error
[https://ibb.co/iiWxZ8](https://ibb.co/iiWxZ8)

**Comment by karlp** [comment]
You are running into common system limits that limit processes to (often) 1024 filehandles.  

You need to go away and read about system tuning for your operating system to remove these sorts of limitations.

**Comment by toast-uz** [comment]
https://mosquitto.org/ show you that this place is for "Report bugs or submit changes".
You need to talk at another place in order to avoid confusing other people searching bugs.

**Comment by toast-uz** [comment]
Closing because this place is not for a question. Look at the instruction (https://mosquitto.org/).
