### ISSUE TITLE
mosquitto - auto start after reboot issues

### ISSUE THREAD

**Issue by chris-008** [eclipse/mosquitto#882]
Hi,

After reboot of my pi, mosquitto won't start even though when checking the status, it says it's active:

pi@orangepizero:~$ sudo systemctl status mosquitto.service
● mosquitto.service - Mosquitto MQTT Broker
   Loaded: loaded (/etc/systemd/system/mosquitto.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2018-07-14 23:51:07 CEST; 15ms ago
     Docs: man:mosquitto(8)
           man:mosquitto.conf(5)
 Main PID: 1330 (mosquitto)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/mosquitto.service
           └─1330 /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf

Jul 14 23:51:07 orangepizero systemd[1]: Started Mosquitto MQTT Broker.

It's only after i manually start
sudo mosquitto 
that everything starts working.

I checked all auto start after reboot sequences and tried them but nothing helps so far?

Any help is much appreciated!!

**Comment by anfractuosity** [comment]
Have you had a look at the mosquitto log file? ( cat /var/log/mosquitto.log, if i recall correctly)

**Comment by dews** [comment]
Try this 

    sudo systemctl enable mosquitto

**Comment by chris-008** [comment]
Hi guys,  
Can’t seem to find the log file.
Tried the enable option already but doesn’t help.
Thx for your suggestions though

**Comment by toast-uz** [comment]
@chris-008 did you find the log file?

**Comment by ralight** [comment]
@chris-008 If this is still an issue, try running manually with exactly the same command as systemd uses:

`/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf`

This may highlight the error.

**Comment by chris-008** [comment]
hi guys, sorry haven't been online much lately during the summer holidays. 
Thanks for the info though , will check it soon and give feedback!

**Comment by chris-008** [comment]
so I found the log file under /var/log/mosquitto/mosquitto.log.
Next error is produced frequently:

1531629123: mosquitto version 1.5 starting
1531629123: Config loaded from /etc/mosquitto/mosquitto.conf.
1531629123: Opening ipv4 listen socket on port 1883.
1531629123: Error: Address already in use

After some googling, I found that it seems because two copies of mosquitto are running?
I will therefore delete mosquitto and start all over, will keep you posted.

**Comment by toast-uz** [comment]
Thanks. I found the same "Error: Address already in use" reported on #894 .

**Comment by chris-008** [comment]
Here is a copy of my conf file:

# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

log_type all

allow_anonymous false
password_file /etc/mosquitto/passwd
listener 1883


I tried changing the mosquitto username and passwordfile again,as this in some cases helped, but to no avail.

pi@orangepizero:~$ mosquitto -c /etc/mosquitto/mosquitto.conf
1534028168: Error: Unable to open log file /var/log/mosquitto/mosquitto.log for writing.

So it seems like I don't have write acces to the " /var/log/mosquitto/mosquitto.log" file ?

Referring to #894, I have commented out the listener 1883 and rebooted, but no change.

**Comment by Tifaifai** [comment]
try this : 
$ touch /var/log/mosquitto/mosquitto.log
$ chmod 777 /var/log/mosquitto/mosquitto.log

**Comment by chris-008** [comment]
thx for the help, the error is gone.
Still not working though.

**Comment by chris-008** [comment]
Yess...Got it working!!!

Went through quite a lot of websites about this matter, seems to be a known problem.
So this worked for me: 
Have the mosquitto.service file configured as follows:

![image](https://user-images.githubusercontent.com/32146240/43997512-a430ad40-9ddd-11e8-9929-f5d302f779bb.png)

then comment the listener line in the mosquitto conf file : 
![image](https://user-images.githubusercontent.com/32146240/43997516-c781743c-9ddd-11e8-8de8-b3ca70a1e8fa.png)
![image](https://user-images.githubusercontent.com/32146240/43997523-e457e082-9ddd-11e8-87a2-5d6dcc7c4198.png)


hope this helps!

**Comment by sanhardik** [comment]
@chris-008 
Thanks for the code. 
However, I see that all the logs go to the syslog file rather than the log destination mentioned in the mosquitto conf file. 
`log_dest file /var/log/mosquitto/mosquitto.log`
