### ISSUE TITLE
websocket not support?

### ISSUE THREAD

**Issue by waytai** [eclipse/mosquitto#884]
Error: Websockets support not available.                                                                    
Error found at mosquitto.conf:841.                                                                          
Error: Unable to open configuration file.

**Comment by toast-uz** [comment]
Need manual compile for using websockets. Did you Google "mosquitto websocket install"?

**Comment by toast-uz** [comment]
Please change the subject If you insist on reporting a bug. This place is not for a question. Look at the instruction (https://mosquitto.org/).

**Comment by waytai** [comment]
I have manual compile and set config.mk   WITH_WEBSOCKETS:=yes   ，but is still not support

**Comment by toast-uz** [comment]
Report your installing procedure from installing websockets, your mosquitto version, and your environments. First time you use mosquitto with websockets?

**Comment by Tifaifai** [comment]
For Websockets compilation, you can read : 
https://github.com/eclipse/mosquitto/issues/303#issuecomment-364653575

**Comment by Tifaifai** [comment]
@toast-uz Maybe add this procedure in Readme.md (Build Dependencies) because this question isn't first time to be ask ;) (But actually none pull request is push ;) )

**Comment by waytai** [comment]
and I have question, mosquitto is support device online and offline topic, I have find a project based on this  project that support device online and offline topic.

git@github.com:houjixin/mosquitto-1.4.11-opt.git

**Comment by Tifaifai** [comment]
maybe come back into original project ;) Last version is 1.5 after 1.4.12, 1.4.13, 1.4.14, 1.4.15 ;)

**Comment by toast-uz** [comment]
@Tifaifai Seems different issue from #303 . @waytai cannot run mosquitto with libwebsockets.

**Comment by Tifaifai** [comment]
#303 is procedure to compile websockets !

**Comment by waytai** [comment]
@Tifaifai   ubuntu14.04, and I  have used newest libwebsocket and newest mosquitto to compile, is also not support.
