### ISSUE TITLE
does auth plugin support Certificate based SSL?

### ISSUE THREAD

**Issue by vklonghml** [eclipse/mosquitto#887]
hi all, 
i want to use mosquitto_plugin.h to develop our auth plugin with certificate, but i have read the  mosquitto_plugin.h, just find the mosquitto_auth_psk_key_get function for psk, 
not found the some method for certificate with ssl, could i use mosquitto_auth_psk_key_get for certificate, if someone knows the situation, let me know, thank you in advance!

**Comment by toast-uz** [comment]
Please change the subject If you insist on reporting a bug. This place is not for a question. Look at the instruction (https://mosquitto.org/).

**Comment by toast-uz** [comment]
Closing as no information. Reopen if you want.
