### ISSUE TITLE
error while building the image eclipse-mosquitto:1.4.12

### ISSUE THREAD

**Issue by KrishnakNamburi** [eclipse/mosquitto#889]
I see the below issue while building image.
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  mosquitto-1.4.15-r0:
    breaks: world[mosquitto=1.4.12-r0]
The command '/bin/sh -c apk --no-cache add mosquitto=1.4.12-r0' returned a non-zero code: 1

**Comment by ralight** [comment]
This is now handled because the docker image is built differently, so I'm closing this issue.
