### ISSUE TITLE
TLS password callback doesn't input password

### ISSUE THREAD

**Issue by Nolaan** [eclipse/mosquitto#895]
Hello,
I've a certificate encrypted and I can connect, publish and subscribe to the broker. However I'm running a test where I first launch the program before the broker. Then when I launch the broker, the program tries to connect but I guess it is unable to decrypt the certificate because the broker replies : 

> New connection from 127.0.0.1 on port 9888.
> Socket error on client <unknown>, disconnecting.

Any ideas on how to go about?

**Comment by toast-uz** [comment]
I cannot clarify your error with these messages.
You are trying to connect between your client program and mosquitto broker with TLS?
Your program use any mqtt client library?
Did you try to connect between mosquitto_pub / sub and mosquitto broker with TLS?

**Comment by Nolaan** [comment]
Yes as stated everything works fine and I'm using the library. Now I'm testing a edge case where : 
1) The broker is offline
2) My program is launched with the broker still offline and tries to connect to it
3) The broker is back online.

Now what happens is that the program connects to the broker but the connection fails with the aforementioned error.
On the broker side :
> New connection from 127.0.0.1 on port 9888.
> Socket error on client , disconnecting.

My program side :
> Hit my_tls_callback 
> Mosquitto LOG :  Client someguyfrom@web.com sending CONNECT

**Comment by Nolaan** [comment]
Second thought the client name is taken from the certificate so I maybe wrong (unless it's kept in memory), and actually the certificate is decrypted but somehow the connection still fails.

**Comment by toast-uz** [comment]
Let me reconfirm the situation.
- Your set of tests works fine except for one case you described above?
- Your client uses libmosquitto?
- Which do you think is caused by libmosquitto or mosquitto broker?
- How do you convince it is a bug, not due to your application codes, your environment, nor your operation?

**Comment by Nolaan** [comment]
My bad I was mishandling the return code for mosquitto_connect and waiting in the callback instead.
Thanks.
