### ISSUE TITLE
Mosquitto build fails with error!!! handle_connect.c:33:25: fatal error: uuid/uuid.h: No such file or directory

### ISSUE THREAD

**Issue by girishkumarbk** [eclipse/mosquitto#899]
ENCE -DWITH_MEMORY_TRACKING -DWITH_SYS_TREE -DWITH_EC -DWITH_EPOLL -c handle_connect.c -o handle_connect.o
handle_connect.c:33:25: fatal error: uuid/uuid.h: No such file or directory
compilation terminated.
Makefile:83: recipe for target 'handle_connect.o' failed
make[1]: *** [handle_connect.o] Error 1
make[1]: Leaving directory '/home/netiotroot/cb/mosquitto/src'
Makefile:26: recipe for target 'mosquitto' failed
make: *** [mosquitto] Error 2

**Comment by karlp** [comment]
You need libuuid if you want to support automatically creating clientids.  You can turn this off.  This is covered by the build requirements: https://github.com/eclipse/mosquitto#build-dependencies

**Comment by ralight** [comment]
Alternatively, build with `make WITH_UUID=no`. libuuid is only used for the broker to generate random ids when a client with zero length client id connects.
