### ISSUE TITLE
Set unauthenticated localhost listener

### ISSUE THREAD

**Issue by cconde** [eclipse/mosquitto#905]
Hi,

I'm trying to have an unauthenticated listener bound to localhost while at the same time use another listener with a password file.
Say a password protected internet accessible interface and a anonymous login listener in a different interface (LAN)

I can successfully do this per separate, but I can't figure out how to do this.

I've been reading the man pages, I now know all the different authentication methods.
Also I can create a lot of listeners in different ports with different protocol and filter options.

How can I specify the authentication  per listener?

Thanks and excuse me if it's obvious and it went over my head,
Ivan

**Comment by karlp** [comment]
There were answers given in the mqtt mailing post you necro'd.  They're still valid....

**Comment by ralight** [comment]
Please take a look at the `per_listener_settings` option: http://mosquitto.org/man/mosquitto-conf-5.html

```
per_listener_settings true

listener 1883 localhost
allow_anonymous true

listener 1884 192.168.1.1
allow_anonymous false
password_file pwfile
```

**Comment by cconde** [comment]
Thank you very, very much.

I've googled, I can swear I've browsed man pages and I can believe I missed a so self explanatory option. 

@ralight, thank you specially for taking the time to write down the solution
