### ISSUE TITLE
How can I change publish payload size?

### ISSUE THREAD

**Issue by StoyanVP** [eclipse/mosquitto#906]
Hello, i use version 1.4.15 for windows, and pubsub client for esp8266.
For example, I send the following json string:
{"parameter0":1,"parameter1":2,"parameter2":3,"parameter3":4,"parameter4":5,"parameter5":6,"errCode":7}
Once it adds another object:
{"parameter0":1,"parameter1":2,"parameter2":3,"parameter3":4,"parameter4":5,"parameter5":6,"parameter6":7,"errCode":7}
Broker reject message.

I was trying to edit the configuration file mosquitto.conf:
message_size_limit 0
or 
message_size_limit 268435455 
Then I restarted service, but without success.
How can I change publish payload size?

And one more question ...
At the beginning, the esp8266 module is published with the following topic module/sensor1
Then I changed it to devCotrol/status. 
But with this new topic the client does not receive the messages.
Can I somehow clear the old topic in broker?

**Comment by karlp** [comment]
pubsubsclient defaults to a hard limit of 128 bytes, see https://github.com/knolleary/pubsubclient#limitations  so if you're using that, this is, "as design" and not something related to mosquitto at all.

**Comment by ralight** [comment]
I don't think this is a bug with mosquitto. Could you please try publishing with a different client like mosquitto_sub to verify whether this is the broker rejecting or the client?

**Comment by StoyanVP** [comment]
Thanks for the answers.
Indeed, the problem is not with the broker, I tested it with MQTT.fx client.
Is in the library "pubsubclient" that I use, as **toast-uz**  wrote.
There is a definition  MQTT_MAX_PACKET_SIZE, which is by default 128 bytes.
But no effect when I raise it.
I have to turn my question to the knolleary/pubsubclient
