### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by odidev** [eclipse/mosquitto#908]
```Mosquitto-docker``` is working fine for ```arm64v8``` architecture as well.
I have executed the test cases and verified the working.

In addition,  ```alpine``` is also supporting ```mosquitto``` in its ```aarch64``` releases.
I would be happy to raise a **PR** if you allow me.

There is one more possibility where we can make this package multi-architecture supported, if we remove hard-coded version of ```mosquitto-1.4.14-r0``` to just ```mosquitto```.

Regards,

**Comment by odidev** [comment]
Hi Guys,

Any update regarding this?
In my view, it is better to make ```mosquitto``` independent of hard-coded version numbers, as it would not break any future build too.

Regards,

**Comment by karlp** [comment]
feel very free to propose a PR that makes it more clear what you're requesting.

**Comment by lag-linaro** [comment]
@karlp, since @odidev serviced your request, would you be kind enough to follow up on it please?

The PR submitted by @odidev LGTM.

**Comment by odidev** [comment]
```Eclipse-Mosquitto``` now supports ```arm64v8```.
Thanks, everyone for your kind support.
Closing this issue now.

Regards,
