### ISSUE TITLE
MQTT log unreadable!!!

### ISSUE THREAD

**Issue by ducarpit** [eclipse/mosquitto#910]
Hi,
i have an Ubuntu server and i configured on it an MQTT server.
Unfortunatly, in the logs on /var/log/mosquitto directory, there is at the beginning of the lines a number (in internet the people say it is the milliseconds from the service start).
Is there a way to change this option in the mosquitto.conf file and put the date and the time in the log intead of the milliseconds?
Example:
`04.08.2018 19:02:09 Saving in-memory database to /var/lib/mosquitto/mosquitto.db. `
Thanks to all

Christian

**Comment by karlp** [comment]
No.  You can however use syslog instead of stdout/stderr (see the manual for log_dest) and then configure whatever logging format you like

**Comment by ducarpit** [comment]
Ok perfect,
i added these lines in the /etc/mosquitto/mosquitto.conf file:

```
log_dest syslog
log_facility 0
log_type error
log_type warning
log_type information
log_timestamp true
```
and this line in the /etc/rsyslog.conf file:

`local0.* -/var/log/mosquitto/mosquitto.log`

and the restart the two services.

Now i can see the date and the time in the log.
How can i produce a more verbose log? Is there a parameter?
Thanks a lot

Christian

**Comment by toast-uz** [comment]
Look at log_type directive in mosquitto.conf .

**Comment by toast-uz** [comment]
@ducarpit , is this issue solved?

**Comment by ducarpit** [comment]
@toast-uz How can i do this?
