### ISSUE TITLE
installation on windows

### ISSUE THREAD

**Issue by danielstock** [eclipse/mosquitto#914]
i installed mosquitto as windows services,
and it's execute file path is configured as：
d:\Program Files (x86)\mosquitto\mosquitto.exe run

does it use mosquitto.conf as the broker config file by default？

**Comment by toast-uz** [comment]
Exactly "run" option is implemented on Windows, I cannot find any document about this option. Could you use sc.exe for managing services?

**Comment by ralight** [comment]
When run as a service, the broker loads a config file from %MOSQUITTO_DIR%/mosquitto.conf.
