### ISSUE TITLE
client tools don't default port number when TLS is disabled

### ISSUE THREAD

**Issue by karlp** [eclipse/mosquitto#921]
Originally reported at: https://github.com/openwrt/packages/issues/6765

stepping through this with a debugger shows that the code arrives at mosquitto_connect_bind() with the port parameter still being -1, which then fails.

The code around: https://github.com/eclipse/mosquitto/blob/master/client/client_shared.c#L981-L996 in client_connect() doesn't appear to handle the defaults properly with WITH_TLS unset.

workaround is simply adding the -p option manually.

**Comment by ralight** [comment]
I fixed this on `fixes`... yesterday.

https://github.com/eclipse/mosquitto/commit/3d3b7fc46f904aeec7cea47ec74ead235ea09408
