### ISSUE TITLE
make[2]: ./09-plugin-auth-context-params.py: Command not found

### ISSUE THREAD

**Issue by GAZ082** [eclipse/mosquitto#922]
That test fails.
Linux 4.14.52+ #1123 Wed Jun 27 17:05:32 BST 2018 armv6l GNU/Linux (raspberry pi zero w)
Version: 1.5.1

**Comment by ralight** [comment]
How annoying! It got missed when adding to the commit. It's in the repository now.

**Comment by GAZ082** [comment]
I hate to be the Test Grinch :P

**Comment by ralight** [comment]
Not at all!
