### ISSUE TITLE
Duplicate sections in mosquitto.conf

### ISSUE THREAD

**Issue by dylanhart** [eclipse/mosquitto#923]
The SSL/TLS sections in the example mosquitto.conf seem to duplicated (possibly in error):

* https://github.com/eclipse/mosquitto/blob/f6f509031aacc6c9b6793c6ea8cfb59dccc19136/mosquitto.conf#L196-L292
* https://github.com/eclipse/mosquitto/blob/f6f509031aacc6c9b6793c6ea8cfb59dccc19136/mosquitto.conf#L348-L432

Is this to signify that each extra listener can have it's own SSL/TLS settings?

**Comment by toast-uz** [comment]
Exactly!

**Comment by toast-uz** [comment]
> Is this to signify that each extra listener can have it's own SSL/TLS settings?
maybe I think so.
The delimiter is '-'  at the SSL/TLS section, while '=' at the listener section. It's the evidence of difference of sub-hierarchies.

**Comment by dylanhart** [comment]
Maybe the lower section could be a shorter blurb on how the same settings can be applied? In its current state, the file is easy to get lost in. Also it seems that they aren't exactly 1-to-1 with information.

**Comment by ckrey** [comment]
I think in the current version 2.0.19 the lower section is much shorter and is bridge specific. Can we close the issue?
