### ISSUE TITLE
Windows binary downloads 1.5.1 not available

### ISSUE THREAD

**Issue by pavel-ch** [eclipse/mosquitto#929]
mosquitto-1.5.1-install-windows-x32 and 64.exe are not available, writing:
Eclipse downloads - file unavailable
Hope it is ok using an issue for this type of problem.

**Comment by Velok** [comment]
For a workaround go to this page and click on the download button: http://www.eclipse.org/downloads/download.php?file=/mosquitto/binary/

**Comment by ralight** [comment]
Yes absolutely fine to report that sort of thing here. I fixed it the other day, sorry about the different mistakes in *both* urls.

**Comment by pavel-ch** [comment]
Thank you.
