### ISSUE TITLE
Subscription matching is inefficient

### ISSUE THREAD

**Issue by zinid** [eclipse/mosquitto#930]
On a large number of subscriptions mosquitto performs very slowly when a PUBLISH message gets matched against existing subscriptions. Here is `gprof` output:
```
Flat profile:

Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total           
 time   seconds   seconds    calls  Ts/call  Ts/call  name    
 87.58    128.19   128.19                             sub__search
 11.12    144.47    16.28                             mosquitto_main_loop
  0.87    145.75     1.28                             db__message_write
  0.05    145.82     0.07                             packet__write
  0.05    145.89     0.07                             sub__add_recurse
  0.03    145.94     0.05                             handle(short, bool __restrict, short, char, long double, int, bool,...)
  0.03    145.98     0.04                             handle__connect
  0.03    146.02     0.04                             mosquitto_acl_check
  0.03    146.06     0.04                             sub__add
...
```
It seems like `sub__search()` from [subs.c](https://github.com/eclipse/mosquitto/blob/master/src/subs.c) has `O(N)` complexity (at least I have such impression from looking briefly at its code).

Mosquitto version is f6f509031aacc6c9b6793c6ea8cfb59dccc19136

**Comment by karlp** [comment]
prpbably dupe of https://github.com/eclipse/mosquitto/issues/216

i t hought i remember a pull for t his too, or a ML thread, but can't find it right now.

**Comment by zinid** [comment]
Duplicate of #216
