### ISSUE TITLE
pls convert timestamp to datetime in mosquitto.log

### ISSUE THREAD

**Issue by pakair** [eclipse/mosquitto#934]
from /var/log/mosquitto/mosquitto.log
1535206407: New connection from 127.0.0.1 on port 1883.
1535206407: New client connected from 127.0.0.1 as mosqsub/32191-mint (c1, k60).
1535206459: Socket error on client mosqsub/32191-mint, disconnecting.

is it possible to format the timestamp to datetime (like syslog)?
date -d @1535206459

**Comment by karlp** [comment]
just use syslog.  You don't have to use stdout to a file.  ```log_dest syslog``` will get you whatever formatting you desire.

**Comment by ralight** [comment]
I'm closing this as `wontfix` here because I don't want to break the log format and there is a method to get what you want already. If you are struggling to get the format from syslog that you want, please post again.

**Comment by esinyor** [comment]
This is fixed in v1.6.1 or possibly earlier. 

`log_timestamp_format format`

https://mosquitto.org/man/mosquitto-conf-5.html
