### ISSUE TITLE
Install as service on Windows 64 bit - Unknown option 'install'

### ISSUE THREAD

**Issue by ntyrrell** [eclipse/mosquitto#936]
When attempting to install the latest version of Mosquitto (1.5.1) on Windows  (Windows 10 x64 architecture), it fails to install as a service when following the instructions in the readme-windows.txt file. When run with the verbose flag, it prints the following error message;
```
C:\Program Files\mosquitto>mosquitto -v install
Error: Unknown option 'install'.
mosquitto version 1.5.1

mosquitto is an MQTT v3.1.1 broker.

Usage: mosquitto [-c config_file] [-d] [-h] [-p port]

 -c : specify the broker config file.
 -d : put the broker into the background after starting.
 -h : display this help.
 -p : start the broker listening on the specified port.
      Not recommended in conjunction with the -c option.
 -v : verbose mode - enable all logging types. This overrides
      any logging options given in the config file.
```

**Comment by ralight** [comment]
Yes, installing/uninstalling the Windows service expects an exact argument of `install` or `uninstall`. It is a completely separate mode that runs the install/uninstall step and then exits. The `-v` option is for the normal mode of operation. Does that make sense?

**Comment by ntyrrell** [comment]
Thank you for your response.
However, when attempting to install without the flag, it does not appear to actually install the service. After checking the list of services on my Windows machine, no service with a name similar to "Mosquitto" is available.

**Comment by ntyrrell** [comment]
Sorry, my fault - seems to have appeared after restarting the machine. Closing (very sorry for time taken).
