### ISSUE TITLE
Debian packages for 1.5.1 and link missing at mosquitto.org

### ISSUE THREAD

**Issue by jpmens** [eclipse/mosquitto#939]
We've been spoiled in the past by having Debian/CentOS binary packages available via the Mosquitto repositories very soon after a release, so I'd like to ask whether it's to be expected that we haven't seen packages for 1.5.1 yet? (This is not a complaint! :-) )

~~Also, just a small note that version 1.5.1 is not linked to from [https://mosquitto.org/download/](https://mosquitto.org/download/) although it's available at [https://mosquitto.org/files/source/](https://mosquitto.org/files/source/).~~

**Comment by ralight** [comment]
It's not intentional at all, other tasks have just got in the way. I normally try to get the packages sorted out even before announcing the release, but didn't have that luxury this time. I'll devote more time!

**Comment by jpmens** [comment]
Thank you very much: we're now seeing packages for 1.5.3. Much appreciated!

**Comment by ralight** [comment]
Thanks for remembering about this bug :)
