### ISSUE TITLE
How to run multiple Windows service instances of Mosquitto

### ISSUE THREAD

**Issue by panyi-dev** [eclipse/mosquitto#940]
How to run multiple Windows service instances of Mosquitto

**Comment by ralight** [comment]
When running as a service on Windows, mosquitto expects the config file to be at %MOSQUITTO_DIR%/mosquitto.conf, there is only that choice if you are running as a proper service.

If you run as a normal executable then you can have as many instances as you wish.

**Comment by ralight** [comment]
Running multiple mosquitto services on Windows will be possible with the 2.1 release. You should rename the exe, e.g. mosquitto_1884.exe, and that version of the service will expect to load its config from %MOSQUITTO_1884_DIR%/mosquitto.conf
