### ISSUE TITLE
Code for setting the TCP_NODELAY option is wrong

### ISSUE THREAD

**Issue by rfalke** [eclipse/mosquitto#941]
The code in the current master is:
```
	if(setsockopt(new_sock, IPPROTO_TCP, TCP_NODELAY, &flag, sizeof(int) != 0)){
		log__printf(NULL, MOSQ_LOG_WARNING, "Warning: Unable to set TCP_NODELAY.");
	}
```

But the parentheses are set wrong which results in a call `setsockopt(..., 1)` which the kernel answers with EINVAL.

**Comment by ralight** [comment]
Thank you! That's now fixed in the `fixes` branch.
