### ISSUE TITLE
How the mosquitto handle overlapped subscriptions?

### ISSUE THREAD

**Issue by mrpre** [eclipse/mosquitto#944]
Scenario:  
Client A subscribe `/dev/+`with Qos 0 and `/dev/123` with Qos 1, then Client B publish message to topic: `/dev/123`.      
Question:  
My question is will the Mosquitto publish two message for each Qos subscription ? The specification says yes but my experiment shows no.   

 [MQTT-3.3.5-1]  
```
When Clients make subscriptions with Topic Filters that include wildcards, 
it is possible for a Client’s subscriptions to overlap so that a published message might match multiple filters.
 In this case the Server MUST deliver the message to the Client respecting the maximum QoS 
of all the matching subscriptions.
```  
Is my scenario wrong ?

**Comment by toast-uz** [comment]
I think MQTT-3.3.5-1 saids the broker MUST transfer at least one message with the highest QoS under the multiple subscriptions matching, and MAY transfer every message correspond with each subscription. Do you require the MAY condition?

**Comment by mrpre** [comment]
@toast-uz I'm just confused and I don't need this condition. Thank you for your explaining.

**Comment by toast-uz** [comment]
Thanks. Could you close this?
