### ISSUE TITLE
I can take data with mosquitto_subscribe_simple but i can not publish it to clients.

### ISSUE THREAD

**Issue by BehindSoftware** [eclipse/mosquitto#946]
I used mosquitto_lib_init(); at main function and i call check_topic_data function, i can take data with mosquitto_subscribe_simple but i can not publish it to clients.

`
void check_topic_data(){
	int rc;
	struct mosquitto_message *msg;
	struct mosquitto *mosq = NULL;

	rc = mosquitto_subscribe_simple(
			&msg, 1, true,
			"87896AE0/temperatura", 0,
			"broker.hivemq.com", 1883,
			NULL, 60, true,
			NULL, NULL,
			NULL, NULL);
	tnSetLabelCaption(labelVehicleSpeed, (char *)msg->payload);
	rc = mosquitto_publish(mosq,(int*)msg->mid,"#",msg->payloadlen,msg->payload,msg->qos,msg->retain);
	if(rc){
		printf("\n******************OK PUBLISH:%s*****************",(char*)msg->payload);
	}
	printf("%s %s\n", msg->topic, (char *)msg->payload);
	mosquitto_message_free(&msg);

	mosquitto_lib_cleanup();
}
`

**Comment by kumar003vinod** [comment]
Not sure if this is the actual problem, but topic `#` is not a valid topic.

**Comment by toast-uz** [comment]
@BehindSoftware could you answer for @kumar003vinod 's pointing out.

**Comment by BehindSoftware** [comment]
Yes, i have solve the problem, yet. First of all, i saw invalid parameter problem (Problem 3 in mosquitto library) when i printed rc variable. Then, i had changed my topic, but i took client connection problem. I used connection callback in pub_client.c files. Now, it is working well.

**Comment by toast-uz** [comment]
Great! Could you close this?

**Comment by BehindSoftware** [comment]
Of course :)
