### ISSUE TITLE
Allow mosquitto_sub to open persistent session and exit (allow -C 0)

### ISSUE THREAD

**Issue by benbarbour** [eclipse/mosquitto#952]
This behaviour would be useful to me in a test I'm trying to write. Something like:

```
mosquitto_sub -i myTestClient -t myTopic --disable-clean-session -C 0
```

would cause mosquitto_sub to create a new persistent session and then exit without waiting for anything to be received. Then I could do some other things, including publishing a message to `myTopic` with `mosquitto_pub`, and then call `mosquitto_sub` again with a higher count to receive that message.

Currently I just get a `Error: Invalid message count "0".` message and it exits.

**Comment by karlp** [comment]
if yo're doing this by hand, just press ctrl-c?  if you're scripting this already, using scripting support?

**Comment by benbarbour** [comment]
Not by hand. What do you mean by "scripting support"?

**Comment by ralight** [comment]
Could you also try

```
mosquitto_pub -i myTestClient -t throwaway -c -n
```

Not very elegant I'll admit, but it should do the job for now.

**Comment by benbarbour** [comment]
That LGTM - thanks!
