### ISSUE TITLE
Enabling session resumption using session ids

### ISSUE THREAD

**Issue by sachinrj4** [eclipse/mosquitto#954]
I have wrote the paho-client programs( 1-publisher  ,1-subscriber) using C language. And I am able to transmit the data  through mosquitto broker with TLSv2.  Now i want to enable session  resumption using session ID.. What changes are to be done in my  mosquitto broker configuration file and in my client C  programs...Openssl says server needs to generate session ids, which  means mosquitto in this context. I went through all the  documents....will mosquitto support session resumption?

**Comment by kumar003vinod** [comment]
Mosquitto supports session resumption since v1.3. There is a [thread](https://dev.eclipse.org/mhonarc/lists/mosquitto-dev/msg01605.html) on mosquitto dev if you need to know more about it.

**Comment by sachinrj4** [comment]
Thank you for your response..But the thread has little information and tough to understand it. And it deals with session tickets and not session IDs.

**Comment by Assar63** [comment]
I use this quite much.
One key word to read more about is "clean session". The meaning of "clean session" is changing a bit when MQTT 5 is emerging, so I recommend you to dig in to documentation on the version or combinations of versions you are going to use.

**Comment by sachinrj4** [comment]
> I use this quite much.
> One key word to read more about is "clean session". The meaning of "clean session" is changing a bit when MQTT 5 is emerging, so I recommend you to dig in to documentation on the version or combinations of versions you are going to use.


Since you use this quite much.
Have you tried session resumption using session IDS?

**Comment by Assar63** [comment]
For TLS we use stunnel in the "front" so the mosquitto broker is not
dealing with TLS at all in backend.


Den tors 20 sep. 2018 kl 11:17 skrev sachinrj4 <notifications@github.com>:

**Comment by sachinrj4** [comment]
> more
Yes i do know that TLS part is done by openssl library not by mosquitto.
When i set clean session to 0, session resumption is working( optimization of handshake is seen through wireshark) What is the default time out ?

**Comment by ralight** [comment]
TLS session resumption uses the defaults provided by OpenSSL, you'd have to check there.

**Comment by sachinrj4** [comment]
PAHO-C client programs need to disable clean session flag so that session resumption is enabled. 
It works and verified using wireshark.
