### ISSUE TITLE
Support for HTTP proxy

### ISSUE THREAD

**Issue by santoshks68** [eclipse/mosquitto#955]
Are there are any plans to support HTTP proxy in the Mosquitto library? As explained in this AWS article,
https://aws.amazon.com/blogs/iot/mqtt-with-tls-client-authentication-on-port-443-why-it-is-useful-and-how-it-works/
most corporate IT infrastructures tend to restrict inbound and outbound traffic to specific ports. Many of them use the HTTP proxy and not the SOCKS proxy.  When support for ALPN in Mosquitto is implemented, this would most likely be the next enhancement request!

**Comment by toast-uz** [comment]
Duplicated with #924 . Could you confirm it?

**Comment by santoshks68** [comment]
Well I am  not so sure that incorporating ALPN support in Mosquitto implies support for HTTP proxy. I think these features would possibly go together but are not necessarily the same. Or maybe my understanding is wrong!

**Comment by santoshks68** [comment]
So what you are saying is it would be meaningless to support ALPN in Mosquitto without also adding HTTP proxy support? Currently, Mosquitto only allows to specify a SOCKS5 proxy.

**Comment by toast-uz** [comment]
At least, AWS uses ALPN to support mqtt via http proxy. If you insist other scenarios, please describe other examples.

**Comment by toast-uz** [comment]
Then, close this issue as duplicated, and reopen after you have other scenarios.

**Comment by santoshks68** [comment]
Duplicated with #924#924, Support for ALPN in Mosquitto .  Closing the issue

**Comment by MikeDombo** [comment]
ALPN isn't enough for HTTP proxy because Mosquitto is still making a direct connection. It needs additional options to first connect to an HTTP proxy and then to the MQTT bridge.

**Comment by toast-uz** [comment]
Indeed.
Your points are 2) and 3) of https://www.eclipse.org/lists/mosquitto-dev/msg01795.html ?
Could you create a new issue focusing on them?
