### ISSUE TITLE
websocket issue with libwebsocket 3.0.0

### ISSUE THREAD

**Issue by ramarro123** [eclipse/mosquitto#956]
Hello,

trying mosquitto with libwebsocekt 3.0.0 make impossible to use websocket, with both ssl or plain.
the connection stay open but without response.

i try with alpinelinux. 
libwebsocket 2.4 seems fine, but i can't update at 1.5.x without having to recompile libwebsocket and i am a big fan of things that work out of the box :)

any plan to fix it?

**Comment by toast-uz** [comment]
Using v1.5.1? There are many fixes between v1.5.0 and v1.5.1.

**Comment by ramarro123** [comment]
yeah, even with 1.5.1 it doesn't work, i add "1.5.x" cos i try with both 1.5 and 1.5.1 :)
i try with alpine linux now the def in repo for edge it's 1.5.1 (that doesn't work)
https://pkgs.alpinelinux.org/packages?name=mosquitto&branch=edge

unfortunately even 3.8 seems broken for the same probelm (libwebscoket 3.0.0)
3.7 have libwebsocket 2.4 and it work

**Comment by fcarlier** [comment]
Have you a error log ?

**Comment by ramarro123** [comment]
it doesn't log anything with the default conf file, if you  wish to try, you can try this dockerfile

https://github.com/eclipse/mosquitto/pull/799/files

the pull request propose a version with libwebsocket 3.0.0 and 1.5.1, websocket wont work with that docker file. change libwebsocket to 2.4.2 make it work (that's what i am using now, a custom dockerfile
https://raw.githubusercontent.com/ramarro123/mosquitto/master/1.5.1/Dockerfile)

**Comment by karlp** [comment]
We're using lws 3.0.0 and mosq 1.5.1 quite happily in openwrt.  Can you share mroe about how you built your LWS? is there a chacne you're picking up stale distro versions of LWS that are conflicting or anything?

**Comment by ramarro123** [comment]
this is how i build a docker image, based on alpine, and lws get
compiled inside docker container


FROM alpine:3.7

ARG VERSION=1.5.1
ARG WS_VERSION=3.0.0

RUN set -ex \
    # Add build dependencies, remove after build
    && apk --no-cache add --virtual .build-deps \
        build-base \
        openssl-dev \
        c-ares-dev \
        util-linux-dev \
        zlib-dev \
        cmake \
    # Add fetch dependencies, remove after build
    && apk --no-cache add --virtual .fetch-deps \
        git \
        curl \
    # Add run dependencies, keep after build
    && apk --no-cache add --virtual .run-deps \
        openssl \
        zlib \
        c-ares \
        util-linux \
    # Manually compile and install libwebsockets to keep relying on openssl
    && mkdir /tmp/libwebsockets \
    && cd /tmp/libwebsockets \
    && curl -sqL
https://github.com/warmcat/libwebsockets/archive/v${WS_VERSION}.tar.gz
| tar zxf - \
    && cd libwebsockets-${WS_VERSION} \
    && mkdir build \
    && cd build \
    && cmake .. \
        -DCMAKE_BUILD_TYPE=MinSizeRel \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_VERBOSE_MAKEFILE=TRUE \
    && make \
    # Do not make install blindly as installing the examples is neither needed
    # nor works.
    && cmake -DCOMPONENT=libraries -P cmake_install.cmake \
    && cmake -DCOMPONENT=dev -P cmake_install.cmake \
    # Checkout and compile, versions are branched with a "v" in front of the
    # version number, but tagged at the Docker registry without the "v".
    && git clone --depth 1 -b v${VERSION}
https://github.com/eclipse/mosquitto.git /tmp/mosquitto \
    && cd /tmp/mosquitto \
    # Manually patch the Makefile to arrange for not making the documentation
    # (and not having to bring in xslt). This is to be able to run against older
    # version of Mosquitto where WITH_DOCS did not (yet) exist.
    && sed -i -e "s|^DOCDIRS=.*$|DOCDIRS=|g" Makefile \
    # Since we compile under Alpine, with musl, we cannot add support for async
    # dns lookup as this requires glibc
    && make \
        WITH_WEBSOCKETS=yes \
        WITH_SRV=yes \
        WITH_ADNS=no \
        prefix=/usr \
    # Manually patch the Makefile to make sure we can still run on older
    # releases of Mosquitto where WITH_STRIP did not (yet) exist.
    && sed -i -e "s|(INSTALL) -s|(INSTALL)|g" -e
's|--strip-program=${CROSS_COMPILE}${STRIP}||' */Makefile */*/Makefile
\
    && make WITH_DOCS=no prefix=/usr install \
    && addgroup -S mosquitto \
    && adduser -S -D -H -h /var/empty -s /sbin/nologin -G mosquitto -g
mosquitto mosquitto \
    && mkdir -p /mosquitto/config /mosquitto/data /mosquitto/log \
    && cp /etc/mosquitto/mosquitto.conf.example
/mosquitto/config/mosquitto.conf \
    && chown -R mosquitto:mosquitto /mosquitto \
    && apk --purge del .build-deps .fetch-deps \
    && rm -rf /tmp/libwebsockets \
    && rm -rf /tmp/mosquitto \
    && rm -rf /var/cache/apk/*

# Expose MQTT port
EXPOSE 1883
EXPOSE 9999

COPY docker-entrypoint.sh /
COPY mosquitto.conf /mosquitto/config/mosquitto.conf
COPY acls /mosquitto/config/acls
COPY passwd /mosquitto/config/passwd

RUN chmod 777 /docker-entrypoint.sh
RUN chmod 777 /mosquitto/config/mosquitto.conf
RUN chmod 777 /mosquitto/config/acls
RUN chmod 777 /mosquitto/config/passwd

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]


Il giorno ven 7 set 2018 alle ore 16:07 Karl Palsson <
notifications@github.com> ha scritto:

**Comment by karlp** [comment]
and people wonder why docker has a bad name?  I've no idea what's wrong, but I'd imagine that your "build" isn't following the actual build instructions of either package.  For starters, drop the "patching" of the mosquitto makefile and just run "make binary" like the documentation describes (or the WITH_DOC=no, I guarantee you're not building old enough versions for this sort of cargo to worth carrying).  I've not looked further at this giant blob, there simply isn't enough viable information to diagnose what's not working for you.

**Comment by ramarro123** [comment]
mosquitto.conf get mounted cos i used it during test with 1.4.x (that work) and with libwebscoket 2.4 that work...

the current setup it's mosuitto 1.5.1 with libwebsocket 2.4 :) and it's working pretty fine, so i won't complain about libwebsocket i have found a way to make it work downgrading libwebsocket.

mosquitto.conf mounted have the additional listeners for websocket , fyi :)

**Comment by Auswaschbar** [comment]
I believe I've run into what I think is the same problem. Unlike ramarro123 I am not compiling anything, just using the packages shipped with alpine linux.

If I use alpine-3.7 as a base (mosquitto 1.4.15, libwebsockets 2.4.0), websockets work fine. Updrading to 3.8 (mosquitto 1.4.15, libwebsockets 3.0.0) or edge (mosquitto 1.5.1, libwebsockets 3.0.0) makes all requests to the websocket port hang infinitely, no matter what client I use. The regular protocol still works.

In all cases, the startup log says "Opening websockets listen socket on port 9001"

mosquitto.conf:

`# this will listen for mqtt on tcp
listener 1883

# this will expect websockets connections
listener 9001
protocol websockets`

**Comment by Auswaschbar** [comment]
# Update

The problem seems to be gone with some recent updates in alpine edge. The configuration I posted above works flawlessly now when using alpine:edge as a base image, with mosquitto 1.5.5-r1 and libwebsockets 3.1.0-r0.

**Comment by ralight** [comment]
Thanks for the feedback @Auswaschbar , perhaps it was a bug in 3.0.0 that was fixed in 3.1.0. I'm going to close this now.
