### ISSUE TITLE
Getting SSL errors "version MOSQ_1.5 not found (required by mosquitto_pub)" on v1.5.1 of mosquitto_pub

### ISSUE THREAD

**Issue by eschercode** [eclipse/mosquitto#957]
I built 1.5.1 from source a couple of days ago, and was starting testing on my (letsencrypt) SSL config:

`mosquitto_pub -h mqtt.foobar.com -p 8883 --capath /etc/ssl/certs -u foobar -P "" -t foobar -m foobar`

This was returned:
`/usr/lib/x86_64-linux-gnu/libmosquitto.so.1: version 'MOSQ_1.5' not found (required by ./mosquitto_pub)`

Is there a hard-coded old version check (accidentally checking for the old version) in the `mosquitto_pub` code?

To verify that my mosquitto TLS settings are OK, I've also tried it on `mosquitto_pub` v1.4.15-2 (the standard Ubuntu 18.04 package), and posting from Paho's python client. Both work fine.

**Comment by ralight** [comment]
It looks like the linker is taking the library from your 1.4.15 install. Did you install your compiled version as well? If so, it is probably in /usr/local/lib and your linker cache just needs updating, which you can do with `sudo ldconfig`

**Comment by eschercode** [comment]
Must have been it; installing in a new container doesn't have the issue. Thanks.

**Comment by ralight** [comment]
Great, glad you've got it sorted.

**Comment by Bagunda** [comment]
I have same issue.
I dont understand. What I should to do

**Comment by ralight** [comment]
@Bagunda you should check that you don't have multiple versions of libmosquitto.so.1 installed. It looks like you have a version 1.5.x client, with a version 1.4.x (or lower) library.

**Comment by ratara** [comment]
Hi,
Mosquito is using dynamic bound libraries. Those libraries are expected to
be at a specific location. In your case it could be possible that mosquitto
finds a library with the wrong version.
You should check those location and which libraries are installed.
If you have no clue how your system is set up or have no chances to change
it, you could bind those library statically.
I hope it helps.



Bagunda <notifications@github.com> schrieb am Sa., 27. Apr. 2019, 02:18:
