### ISSUE TITLE
Hassio logging

### ISSUE THREAD

**Issue by au190** [eclipse/mosquitto#960]
Mosquitto logging time is not human vissibile, its timestamp. Can you write time in the logging ?

**Comment by kumar003vinod** [comment]
Hi @au190 ,
Same issue is already reported at #299 and #934.

**Comment by toast-uz** [comment]
@au190 , could you confirm this issue is duplicated and agree with closing?

**Comment by au190** [comment]
Hi 
Ist not realy helped me. I don't know hoow toconvert tiemstamp to time :(
Can you give me an example ?
Here is my config in Hassio.

{
  "plain": true,
  "plain_websockets": false,
  "ssl": true,
  "ssl_websockets": true,
  "anonymous": false,
  "logins": [
    {
      "username": "admin",
      "password": "pw"
    }
  ],
  "customize": {
    "active": false,
    "folder": "mosquitto"
  },
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}


Thx

**Comment by jpmens** [comment]
User should use syslog for logging and then use any format supported by their syslog. This has been rightly marked as #wontfix several times IIRC.

**Comment by au190** [comment]
Yes I saw that, and I would like to set up the syslog, but I could not find  /etc/mosquitto/mosquitto.conf  in the hassio configuration. Where can I do this config ? In the console log if that is the default what is the purpose of timestap, its not readable by human :)

**Comment by ralight** [comment]
I'm closing this as "wontfix" and agree with @jpmens, your best bet is to talk to hassio.
