### ISSUE TITLE
Installation on mac os

### ISSUE THREAD

**Issue by bgsantos86** [eclipse/mosquitto#964]
Mac OS High Sierra 10.13.6

I tried install mosquito by terminal like instructions `brew install mosquitto` or `sudo brew install mosquitto` , but I got a error message like this: *Error: Running Homebrew as root is extremely dangerous and no longer supported.*

Have any other way to install Mosquitto by terminal in Mac OS?

**Comment by toast-uz** [comment]
If you run as ```sudo brew install something``` , you can always look the error you reported. Not depends on mosquitto at all.

**Comment by jpmens** [comment]
> Running Homebrew as root is extremely dangerous and no longer supported.

So, don't. 

This works fine here:

```
brew install mosquitto
```

**Comment by bgsantos86** [comment]
tks guys!!! I did working here!!
