### ISSUE TITLE
mosquitto_pub.exe succeed to other broker, but libmosquitto not

### ISSUE THREAD

**Issue by mstranne** [eclipse/mosquitto#967]
I am trying to connect to an mqtt broker using libmosquitto. 
However, using moquette broker on android works fine. 
But I also need one for Windows/UWP, therefore I would prefere an C# lib because I am working on Unity.

However, for that I've tried xamarin mqtt broker and GnatMq. Both servers are working fine as they should but when I try to connect via libmosquitto I do not get a connection, but also do not get any error. connect, subscribe  and subscribing an event handler is all returning MOSQ_ERR_SUCCESS.
But The Broker does not show an connected client and sending messages are returning MOSQ_ERR_NO_CONN. 

But when I use mosquitto_pub.exe  via terminal connecting to the server is working.

Whats the difference using the lib, or how is the standard configuration of mosquitto_pub? Is it different to the standart config of the client? Any ideas what I am making wrong?

**Comment by ralight** [comment]
My guess is that you're missing some steps in your use of the library. The code below is roughly a minimal example of what you're trying to do I think, so you can compare to what you have.

```
#include <stdio.h>
#include <mosquitto.h>

void on_connect(struct mosquitto *mosq, void *priv, int rc)
{
	mosquitto_subscribe(mosq, NULL, "my/subscription", 0);
}

void on_message(struct mosquitto *mosq, void *priv, const struct mosquitto_message *msg)
{
	printf("%s %s\n", msg->topic, (const char *)msg->payload);
}

int main(int argc, char *argv[])
{
	struct mosquitto *mosq;

	mosquitto_lib_init();

	mosq = mosquitto_new(NULL, 1, NULL);
	if(!mosq){
		printf("Error: Unable to create mosquitto instance.\n");
		return 1;
	}

	mosquitto_connect_callback_set(mosq, on_connect);
	mosquitto_message_callback_set(mosq, on_message);

	if(mosquitto_connect(mosq, "localhost", 1883, 60)){
		printf("Error: Unable to connect.\n");
		return 1;
	}

	mosquitto_loop_forever(mosq, -1, 1);

	mosquitto_lib_cleanup();

	return 0;
}

```

**Comment by mstranne** [comment]
No with this code its behaviour is excextly the same ...

No error messages and no connection

**Comment by ralight** [comment]
mosquittopp will make no difference.

Could you just confirm - you've used exactly that code with nothing else?

**Comment by mstranne** [comment]
Ok.

Yeah I am using this code:

```
#include <string>
#include <iostream>
#ifdef WIN32
#include <windows.h>
#else
#include <unistd.h>
#endif

#include <mosquittopp.h>

//#include <MosquittoSubscriberIF.h>

using namespace std;

void on_connect(struct mosquitto *mosq, void *priv, int rc)
{
	mosquitto_subscribe(mosq, NULL, "gps", 0);
}

void on_message(struct mosquitto *mosq, void *priv, const struct mosquitto_message *msg)
{
	printf("%s %s\n", msg->topic, (const char *)msg->payload);
}

int main(int argc, char *argv[])
{
	cout << "Starting..." << endl;
	struct mosquitto *mosq;

	mosquitto_lib_init();

	cout << "init geschafft.." << endl;

	mosq = mosquitto_new("test", 0, NULL);
	if (!mosq) {
		printf("Error: Unable to create mosquitto instance.\n");
		return 1;
	}



	if (mosquitto_connect(mosq, "127.0.0.1", 1883, 60)) {
		printf("Error: Unable to connect.\n");
		return 1;

		
	}

	mosquitto_subscribe(mosq, NULL, "gps", 1);

	//mosquitto_loop_forever(mosq, -1, 1);

	mosquitto_connect_callback_set(mosq, on_connect);
	mosquitto_message_callback_set(mosq, on_message);

	/*
	if (mosquitto_loop(mosq, 5, 60)) {
		printf("Error: Unable to connect.\n");
		return 1;
	}
	*/

	mosquitto_lib_cleanup();

	cout << "Finished..." << endl;
	getchar();
	return 0;
}
```
Using moquette broker on android works still fine, but  xamarin mqtt broker and GnatMq on Windows do not work with the code, but using mosquitto_pub.exe

**Comment by ralight** [comment]
This:

    //mosquitto_loop_forever(mosq, -1, 1);

And this:

	/*
	if (mosquitto_loop(mosq, 5, 60)) {
		printf("Error: Unable to connect.\n");
		return 1;
	}
	*/

Are both commented out. This means you aren't running the main loop of the client. Try uncommenting the `mosquitto_loop_forever()` line.

**Comment by mstranne** [comment]
also with the loop, it is not working to connecto to the C# broker.
However, I do not understand why the subscribe exe is working fine....

**Comment by mstranne** [comment]
No difference ...
No errors, but also no connection.
In Unity I am logging the ID whenever a new client connects. 

<img width="950" alt="capture1" src="https://user-images.githubusercontent.com/18437246/46134455-30ac5d80-c243-11e8-8378-b1b34ae04300.PNG">
Ok, I am using exactly your code, exept the id is not NULL and a printf before  the loop.

Here is the code I used now:
```
using namespace std;

void on_connect(struct mosquitto *mosq, void *priv, int rc)
{
	mosquitto_subscribe(mosq, NULL, "my/subscription", 0);
}

void on_message(struct mosquitto *mosq, void *priv, const struct mosquitto_message *msg)
{
	printf("%s %s\n", msg->topic, (const char *)msg->payload);
}

int main(int argc, char *argv[])
{
	struct mosquitto *mosq;

	mosquitto_lib_init();

	mosq = mosquitto_new("lib", 1, NULL);
	if (!mosq) {
		printf("Error: Unable to create mosquitto instance.\n");
		return 1;
	}

	mosquitto_connect_callback_set(mosq, on_connect);
	mosquitto_message_callback_set(mosq, on_message);

	if (mosquitto_connect(mosq, "localhost", 1883, 60)) {
		printf("Error: Unable to connect.\n");
		return 1;
	}

	printf("starting loop forever");
	mosquitto_loop_forever(mosq, -1, 1);

	mosquitto_lib_cleanup();

	return 0;
}

```

**Comment by ralight** [comment]
Is this still a problem? From your last post it looks to have worked up until it would have received messages, and I don't know if you published any to tell if that is working.
