### ISSUE TITLE
Configure SSL/TLS 

### ISSUE THREAD

**Issue by nordleif** [eclipse/mosquitto#968]
Does anyone have a link that explains how to configure SSL/TLS on Mosquitto?
I have used the mosquitto-tls page to create certificates with my hostname as CN and this config:

port 8883
cafile C:\mosquitto\certs\ca.crt
certfile C:\mosquitto\certs\server.crt
keyfile C:\mosquitto\certs\server.key
tls_version tlsv1

Run this in console:
mosquitto.exe -c mosquitto.conf -v
mosquitto_pub.exe -<hostname>  -p 8883 -t test -m test --cafile "c:\mosquitto\certs\client.crt"

The server returns:
1537210620: New connection from fe80::a81d:a6b0:6069:ba14 on port 8883.
1537210620: OpenSSL Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
1537210620: Socket error on client <unknown>, disconnecting.

**Comment by nordleif** [comment]
Hello ralight
Your asciicast works like a charm. 
The mosquitto-tls page should have a link to your guide. 
Thank you for all you help and time.

**Comment by ralight** [comment]
Agreed! I've done that now.

**Comment by satsdeva** [comment]
@ralight  : Could you please share  about the configuration details for  "SSL in web socket Protocol" connection.
