### ISSUE TITLE
Bridge multiple-address ？

### ISSUE THREAD

**Issue by chinausers** [eclipse/mosquitto#969]
I need help.My mosquitto version is 1.4.15. 
connection  test
address 127.0.0.1:3883,address 120.0.0.1:1883
topic room1 both 0

erroot log as follows
1537345978: Connecting bridge test (127.0.0.1:3883)
1537346006: Sending PINGREQ to local.wanke-S088170H.test2
1537346007: Received PINGRESP from local.wanke-S088170H.test2
1537346008: Connecting bridge test (120.26.111.85:9618)
1537346008: Bridge wanke-S088170H.test sending CONNECT
1537346008: Error creating bridge: Connection refused.
It seems that #481 equally.
I've tried to set round_robin = true. But it doesn't seem to work out. Or the latest version has worked out, but it doesn't seem stable enough. I need a solution.
Thank you!

**Comment by ralight** [comment]
It's difficult to say from what you've posted - the configuration has an error (using a comma as the address separator), but it doesn't match your log file.

I've just committed some fixes to the `fixes` branch regarding multiple addresses, could you give them a try?

**Comment by chinausers** [comment]
Yes.It's very Good.

**Comment by chinausers** [comment]
Yes.It's very Good.
