### ISSUE TITLE
Mosquitto continue to push data to subscriber even  the publisher is closed?

### ISSUE THREAD

**Issue by frankiezdh** [eclipse/mosquitto#976]
## Base Information
-  mosquttio version is 1.4.12
-  mosquttio was running in a **docker container** 

## Operation
- A lot of messages publish to mosquitto by  publisher.
- The publishing last 1 hour.
-  Close the connection of producer.
-  The expect result is  that the subscriber can not read data from mosquitto, but the subscriber still read data from mosquitto.

**Comment by ralight** [comment]
Sorry it's not quite clear what the problem is here. Could you explain a bit further please?

**Comment by frankiezdh** [comment]
It is a not a issue. Something wrong about environment.  Thank you guys.
