### ISSUE TITLE
PPA (Trusty) v 1.5.3 : E: Sub-process /usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by nelmos** [eclipse/mosquitto#979]
Error during installation on Ubuntu trusty with package 1.5.3-0mosquitto1~trusty.

Error dpkg during postinstall on a clean install :
`invoke-rc.d: initscript mosquitto, action "start" failed.`

No problem during an update with a previous version installed.

after test, i found that the file /etc/init/mosquitto.conf is not present after install on a new system.

I use this file (from a previous install of 1.4.15) to fix this problem :
```

description "Mosquitto MQTTv3.1 broker"
author "Roger Light wroger@atchoo.org" 

start on net-device-up 

respawn 

exec /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
```

**Comment by ralight** [comment]
I've added the upstart file back in. The packaging got a bit of a refresh this time round and I'm sorry that just got missed for Trusty. Could you confirm that it works for you?

**Comment by nelmos** [comment]
Thanks for your reply.
All good for me.

Thanks for this Quixfix and for all the works on Mosquitto

**Comment by gdt** [comment]
This ticket is stale and should be closed.
