### ISSUE TITLE
Installing mosquitto as a service on Windows

### ISSUE THREAD

**Issue by GHaccount123** [eclipse/mosquitto#980]
Running `mosquitto.exe install` in the command line on Windows 10 does not create a Windows service.

Another user mentioned the same issue in [this link](https://github.com/eclipse/mosquitto/issues/193)

**Comment by igloo15** [comment]
I noticed this as well if you pass the `-v` argument mosquitto says `install` is an unknown option so I guess it was removed at some point.

**Comment by ralight** [comment]
You can't use `-v`, it is just `mosquitto install` or `mosquitto uninstall`. It only works as an admin user as well, maybe that is the problem. I have added some error messages for version 1.5.5 which make this more obvious.

**Comment by maythamfahmi** [comment]
mosquitto install does not return error, and when restrating my computer no service has been installed, I am not sure but I guess there must be some thing more  to be done before it get works correctly.

**Comment by ralight** [comment]
This has been working in more recent versions for a long while now, and the upcoming 2.1 release lets you easily install as multiple services as well: https://github.com/eclipse/mosquitto/blob/develop/README-windows.txt
