### ISSUE TITLE
Core dump in mosquitto log

### ISSUE THREAD

**Issue by ganeshthorner** [eclipse/mosquitto#981]
![image](https://user-images.githubusercontent.com/43740602/46530035-2d097e00-c8b6-11e8-8b6c-9f6944924f7e.png)

**Comment by dadaobusi** [comment]
It seems that mqtt do not support multi thread.Try to use it in single process .

**Comment by ralight** [comment]
As there hasn't been a response for a while and this needs extra information to do anything more, I'm going to close this issue. If it is still a problem for you, please reopen the issue and provide more information.
