### ISSUE TITLE
mosquitto_pub -l and cmake problem

### ISSUE THREAD

**Issue by majekw** [eclipse/mosquitto#983]
Hello,

`mosquitto_pub -l` compiled using cmake on Linux gives error:
`Error: '-l' mode not available, threading support has not been compiled in.`

It looks like using cmake, `WITH_THREADING` is set only in lib/ directory with local CMakeLists.txt and it's not a global Makefile flag. This way client/ doesn't see `WITH_THREADING` set and this was no issue until dde005ef92190dffd1bab0ddbfcfd8c5dbe17bc8.

I put `WITH_THREADING` related config also to client/ directory in https://github.com/eclipse/mosquitto/pull/982 and it fixes issue for me.

I suppose that this was also broken on Mac and maybe WIN, but went unnoticed.

**Comment by ralight** [comment]
This is closed thanks to your PR and will be in 1.5.4 shortly.
