### ISSUE TITLE
Session resumption

### ISSUE THREAD

**Issue by sachinrj4** [eclipse/mosquitto#984]
I have mosquitto-client programs written using C . 
And I am able to transmit the encrypted data through mosquitto broker with TLSv1.2. 
Now i want to enable session resumption using session ID.

1. What changes are to be done in my mosquitto broker configuration file and in my mosquitto- client C programs?

Previously i had written paho-client programs in which session resumption was working by setting _clean session_ flag to **false**.
The same thing of setting clean_session to false in mosquitto client program didnt enable session resumption.

**Comment by kumar003vinod** [comment]
Hi @sachinrj4 , you already have one open issue ( #954 ) regarding session resumption.

**Comment by sachinrj4** [comment]
> Hi @sachinrj4 , you already have one open issue ( #954 ) regarding session resumption.

But that issue was w.r.t PAHO-client programs.

**Comment by ralight** [comment]
It has been possible to provide custom SSL_CTX handles for a while now, which gives you complete control over what happens with TLS connections. See the MOSQ_OPT_SSL_CTX and MOSQ_OPT_SSL_CTX_DEFAULTS options.
