### ISSUE TITLE
How to make the broker be connected from external network?

### ISSUE THREAD

**Issue by wz003** [eclipse/mosquitto#987]
I installed mosquitto via homebrew and used the command to build a broker, which allowed me to subscribe/publish messages on local host like 

mosquitto_pub -h "127.0.0.1" -t topic/state -m "12321"

I would like to know how to build my own broker that can be connected from external network?

Sincere gratitude for any keyword or resource

**Comment by ralight** [comment]
This is a networking question rather than mosquitto specific.

You need to find the external ip address of the computer you have installed mosquitto on, then from a different computer use that ip address. On your home network that might be something like:

```
mosquitto_pub -h 192.168.1.10 -t topic/state -m 12321
```

**Comment by yvs2014** [comment]
If the computer with installed mosquitto on is nat'ed, is there some way to make an outgoing websocket connection to an external server?

**Comment by ralight** [comment]
It isn't possible to make outgoing websockets connections from the broker I'm afraid.
