### ISSUE TITLE
Suggestion: flush the memory for persistence messages

### ISSUE THREAD

**Issue by mced** [eclipse/mosquitto#989]
As far I understand how mosquitto works, the "offline messages" are stored in memory - and on disk if `persistence_file` is setup. If mosquitto exceeds the amount of available ram due to persistent messages, it get killed by OOM killer even persistence on disk is setup.

What do you think to flush the memory when the offline messages are stored on disk and retrieve them when a client with a stored session reconnects ? That would allow to install mosquitto on low memory system.

**Comment by ralight** [comment]
This is a good suggestion and is something that is already on the roadmap, it is a bit more complicated than you might think though. I'm going to close this because it's already being considered.

**Comment by mced** [comment]
@ralight Is it planned to be implemented in the next major 2.0 release ?

> ## Disk persistence improvements
> A new disk persistence interface will be created to allow persistence to occur
immediately, rather than periodically. This will allow queued messages for
disconnected clients to be removed from memory, and reduce the periodic pause
caused when writing the persistence file.
