### ISSUE TITLE
 Your stickers page is not working

### ISSUE THREAD

**Issue by ernestgwilsonii** [eclipse/mosquitto#992]
Go here:
https://mosquitto.org/stickers/
Click the **submit** button

Results:
This page isn’t working
mosquitto.org is currently unable to handle this request.
HTTP ERROR 500

**Comment by ralight** [comment]
Unfortunately moo don't seem to support their API any more, so this just doesn't work. I keep hoping they will fix it. I've put up a notice on the page as to how to do it manually.
