### ISSUE TITLE
Any plans to support TLS v1.3?

### ISSUE THREAD

**Issue by cristian-recoseanu** [eclipse/mosquitto#994]
Hi,

Are there any plans to support TLS v1.3?

Thanks!

**Comment by ralight** [comment]
TLS v1.3 is already supported as soon as you have a version of openssl that supports it. There isn't yet the option of restricting access to TLS v1.3 only, but that is on the list for 1.6.

**Comment by ralight** [comment]
This is now explicitly supported in the `develop` branch.
