### ISSUE TITLE
can support mqtt-sn and continuous storage？

### ISSUE THREAD

**Issue by wuhenfeike** [eclipse/mosquitto#997]
can support mqtt-sn and continuous storage？

**Comment by ralight** [comment]
There are no plans to support mqtt-sn at the moment, I would suggest trying the mqtt-sn gateway from Eclipse Paho.

Changes to the way storage is used is on the roadmap, and some evaluation work has been carried out in that regard. As that's already something we're looking into, I'm going to close this issue, I hope that's ok.
